#!/bin/bash

# =============================================================================
# Start Backend and Mobile App (Local IP - No Tunnel)
# =============================================================================
# This script starts the backend and Expo using local IP address only.
# Both devices must be on the same WiFi network.
# =============================================================================

set -e  # Exit on error

# Configuration
BACKEND_DIR="micro-service-boilerplate-main"
MOBILE_DIR="mobile"
BACKEND_PORT=4000
SUPABASE_PROJECT_REF="nhgdjnqfqpjiavkdosfx"
SUPABASE_URL="https://${SUPABASE_PROJECT_REF}.supabase.co"
SUPABASE_KEYS_FILE=".secrets/supabase_api_keys.json"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get local IP address (Mac-specific)
LOCAL_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -1)

if [ -z "$LOCAL_IP" ]; then
    echo -e "${RED}Error: Could not detect local IP address${NC}"
    exit 1
fi

# =============================================================================
# Cleanup Function
# =============================================================================
cleanup() {
    echo -e "\n${YELLOW}Shutting down...${NC}"
    
    if [ ! -z "$BACKEND_PID" ]; then
        echo "Stopping backend (PID $BACKEND_PID)"
        kill $BACKEND_PID 2>/dev/null || true
    fi
    
    # Kill any remaining processes on port 4000
    lsof -ti:$BACKEND_PORT | xargs kill -9 2>/dev/null || true
    
    echo -e "${GREEN}Cleanup complete${NC}"
    exit 0
}

trap cleanup SIGINT SIGTERM EXIT

# =============================================================================
# Check for port conflicts
# =============================================================================
if lsof -Pi :$BACKEND_PORT -sTCP:LISTEN -t >/dev/null ; then
    EXISTING_PID=$(lsof -ti:$BACKEND_PORT)
    echo -e "${YELLOW}Port $BACKEND_PORT already in use by: $EXISTING_PID. Sending SIGTERM.${NC}"
    kill -15 $EXISTING_PID 2>/dev/null || true
    sleep 2
    
    # Force kill if still running
    if lsof -Pi :$BACKEND_PORT -sTCP:LISTEN -t >/dev/null ; then
        kill -9 $EXISTING_PID 2>/dev/null || true
        sleep 1
    fi
fi

# =============================================================================
# Update mobile/.env with local IP
# =============================================================================
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}🌐 Using Local IP Address${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "Local IP: ${GREEN}http://${LOCAL_IP}:${BACKEND_PORT}${NC}"
echo -e "Backend API: ${GREEN}http://${LOCAL_IP}:${BACKEND_PORT}/api/v1${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"

cd "$MOBILE_DIR"
echo -e "\nUpdating .env with local IP..."

# Resolve Supabase keys from the local secrets file (never printed).
cd ..
if [ ! -f "$SUPABASE_KEYS_FILE" ]; then
    echo -e "${RED}Error: Missing $SUPABASE_KEYS_FILE. Re-run Supabase provisioning or place keys file there.${NC}"
    exit 1
fi

SUPABASE_ANON_KEY=$(python3 - <<'PY'
import json
p=".secrets/supabase_api_keys.json"
data=json.load(open(p))
for item in data:
    if item.get("name") == "anon":
        print(item.get("api_key","").strip())
        break
PY
)

SUPABASE_SERVICE_ROLE_KEY=$(python3 - <<'PY'
import json
p=".secrets/supabase_api_keys.json"
data=json.load(open(p))
for item in data:
    if item.get("name") == "service_role":
        print(item.get("api_key","").strip())
        break
PY
)

cd "$MOBILE_DIR"

# Create or update .env file with local IP
cat > .env << EOF
# API Configuration (Auto-generated by start-backend-and-mobile-local.sh)
# Updated: $(date)

# API URL - Backend endpoint
EXPO_PUBLIC_API_URL=http://${LOCAL_IP}:${BACKEND_PORT}/api/v1

# Socket URL - WebSocket endpoint
EXPO_PUBLIC_SOCKET_URL=http://${LOCAL_IP}:${BACKEND_PORT}

# API Key - Backend authentication key
EXPO_PUBLIC_API_KEY=local-dev-api-key

# Supabase (Auth)
EXPO_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
EXPO_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
EOF

echo -e "${GREEN}✅ Updated .env with local IP${NC}"

# Save IP to docs for reference
cd ..
echo "http://${LOCAL_IP}:${BACKEND_PORT}" > docs/CURRENT-LOCAL-URL.txt
echo -e "${GREEN}✅ Saved local URL to docs/CURRENT-LOCAL-URL.txt${NC}"

# =============================================================================
# Start Backend
# =============================================================================
echo -e "\n${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Starting Backend...${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"

cd "$BACKEND_DIR"
echo "Starting backend (npx nps serve)"
SUPABASE_URL="${SUPABASE_URL}" \
SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY}" \
SUPABASE_SERVICE_ROLE_KEY="${SUPABASE_SERVICE_ROLE_KEY}" \
API_KEY="local-dev-api-key" \
PAYMENTS_DISABLED="true" \
PUSH_NOTIFICATIONS_ENABLED="false" \
npx nps serve > /tmp/backend.log 2>&1 &
BACKEND_PID=$!

# Wait for backend to be ready
echo "Waiting for backend to start..."
for i in {1..30}; do
    if lsof -Pi :$BACKEND_PORT -sTCP:LISTEN -t >/dev/null ; then
        echo -e "${GREEN}✅ Backend is running on port $BACKEND_PORT${NC}"
        break
    fi
    if [ $i -eq 30 ]; then
        echo -e "${RED}Error: Backend failed to start${NC}"
        tail -n 50 /tmp/backend.log
        exit 1
    fi
    sleep 1
done

# Test backend health
echo -e "\nTesting backend health endpoint..."
sleep 2
HEALTH_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://${LOCAL_IP}:${BACKEND_PORT}/api/v1/health)
if [ "$HEALTH_RESPONSE" -eq 200 ]; then
    echo -e "${GREEN}✅ Backend health check passed (HTTP 200)${NC}"
else
    echo -e "${YELLOW}⚠️  Backend health check returned: HTTP $HEALTH_RESPONSE${NC}"
fi

# =============================================================================
# Start Expo
# =============================================================================
echo -e "\n${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Starting Expo...${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"

cd "../$MOBILE_DIR"

echo -e "\n${GREEN}✅ Setup Complete!${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "Backend: ${GREEN}http://${LOCAL_IP}:${BACKEND_PORT}/api/v1${NC}"
echo -e "Socket:  ${GREEN}http://${LOCAL_IP}:${BACKEND_PORT}${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${YELLOW}Make sure your mobile device is on the same WiFi network!${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}\n"

npx expo start --clear

# Keep script running
wait $BACKEND_PID
