#!/bin/bash
set -euo pipefail

# Simple helper to run the backend API (nps serve), expose it via ngrok,
# and launch Expo with the tunnel URL wired into the app. Press Ctrl+C once
# to stop Expo; the backend and ngrok processes are cleaned up automatically.

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKEND_DIR="${ROOT_DIR}/micro-service-boilerplate-main"
MOBILE_DIR="${ROOT_DIR}/mobile"
BACKEND_PORT=4000
NGROK_LOG="$(mktemp -t ngrok-log.XXXXXX)"

if [[ ! -d "${BACKEND_DIR}" ]]; then
  echo "Backend directory not found: ${BACKEND_DIR}" >&2
  exit 1
fi

if [[ ! -d "${MOBILE_DIR}" ]]; then
  echo "Mobile directory not found: ${MOBILE_DIR}" >&2
  exit 1
fi

cleanup() {
  if [[ -n "${BACKEND_PID:-}" ]] && ps -p "${BACKEND_PID}" >/dev/null 2>&1; then
    echo "\nStopping backend (PID ${BACKEND_PID})"
    kill "${BACKEND_PID}" >/dev/null 2>&1 || true
    wait "${BACKEND_PID}" 2>/dev/null || true
  fi

  if [[ -n "${NGROK_PID:-}" ]] && ps -p "${NGROK_PID}" >/dev/null 2>&1; then
    echo "Stopping ngrok (PID ${NGROK_PID})"
    kill "${NGROK_PID}" >/dev/null 2>&1 || true
    wait "${NGROK_PID}" 2>/dev/null || true
  fi

  if [[ -f "${NGROK_LOG}" ]]; then
    rm -f "${NGROK_LOG}"
  fi
}

trap cleanup EXIT INT TERM

# Free the backend port if something else is already listening on it.
if PIDS=$(lsof -tiTCP:"${BACKEND_PORT}" -sTCP:LISTEN 2>/dev/null); then
  if [[ -n "${PIDS}" ]]; then
    echo "Port ${BACKEND_PORT} already in use by: ${PIDS}. Sending SIGTERM."
    while read -r pid; do
      kill "${pid}" >/dev/null 2>&1 || true
    done <<<"${PIDS}"
    sleep 2
    # If still busy, force kill.
    if lsof -tiTCP:"${BACKEND_PORT}" -sTCP:LISTEN >/dev/null 2>&1; then
      echo "Port ${BACKEND_PORT} still busy; sending SIGKILL."
      while read -r pid; do
        kill -9 "${pid}" >/dev/null 2>&1 || true
      done <<<"${PIDS}"
      sleep 1
    fi
  fi
fi

echo "Starting backend (npx nps serve)"
(
  cd "${BACKEND_DIR}"
  npx nps serve
) &
BACKEND_PID=$!

# Wait until the backend port is listening so Expo can hit the API immediately
for attempt in {1..30}; do
  if lsof -iTCP:"${BACKEND_PORT}" -sTCP:LISTEN >/dev/null 2>&1; then
    echo "Backend listening on port ${BACKEND_PORT}"
    break
  fi
  if ! ps -p "${BACKEND_PID}" >/dev/null 2>&1; then
    echo "Backend process exited early; check logs above." >&2
    exit 1
  fi
  sleep 1

  if [[ ${attempt} -eq 30 ]]; then
    echo "Backend did not start within expected time." >&2
    exit 1
  fi
done

# Ensure ngrok is available
if ! command -v ngrok >/dev/null 2>&1; then
  echo "ngrok CLI not found in PATH. Please install it from https://ngrok.com/download" >&2
  exit 1
fi

echo "Starting ngrok tunnel (ngrok http ${BACKEND_PORT})"
ngrok http "${BACKEND_PORT}" --log=stdout >"${NGROK_LOG}" 2>&1 &
NGROK_PID=$!

# Wait for ngrok to publish a tunnel
API_BASE_URL=""
for attempt in {1..30}; do
  if ! ps -p "${NGROK_PID}" >/dev/null 2>&1; then
    echo "ngrok exited unexpectedly. See log at ${NGROK_LOG}" >&2
    exit 1
  fi

  NGROK_URL=$(curl -sf http://127.0.0.1:4040/api/tunnels | \
    python3 -c "import json,sys; data=json.load(sys.stdin); print(next((t['public_url'] for t in data.get('tunnels', []) if t.get('proto')=='https'), ''), end='')" 2>/dev/null || true)

  if [[ -n "${NGROK_URL}" ]]; then
    API_BASE_URL="${NGROK_URL%/}/api/v1"
    echo "ngrok tunnel ready: ${NGROK_URL}"

    ENV_FILE="${MOBILE_DIR}/.env"
    echo "Updating ${ENV_FILE} with new ngrok URL"
    
    # Create or update .env file with ngrok URL
    cat > "${ENV_FILE}" << EOF
# API Configuration (Auto-generated by start-backend-and-mobile.sh)
# Updated: $(date)

# API URL - Backend endpoint via ngrok tunnel
EXPO_PUBLIC_API_URL=${NGROK_URL}/api/v1

# Socket URL - WebSocket endpoint via ngrok tunnel
EXPO_PUBLIC_SOCKET_URL=${NGROK_URL}

# API Key - Backend authentication key
EXPO_PUBLIC_API_KEY=local-dev-api-key
EOF

    echo "✅ Updated .env with ngrok URL"

    NGROK_DOC="${ROOT_DIR}/docs/CURRENT-NGROK-URL.txt"
    if [[ -d "${ROOT_DIR}/docs" ]]; then
      printf '%s\n' "${NGROK_URL}" >"${NGROK_DOC}"
    fi
    break
  fi

  sleep 1

  if [[ ${attempt} -eq 30 ]]; then
    echo "Timed out waiting for ngrok tunnel. Check log at ${NGROK_LOG}" >&2
    exit 1
  fi
done

echo "Starting Expo (npx expo start --tunnel)"
cd "${MOBILE_DIR}"
EXPO_PUBLIC_API_URL="${API_BASE_URL}" NODE_OPTIONS="${NODE_OPTIONS:-}" npx expo start --tunnel
