#!/bin/bash
set -euo pipefail

# Simple helper to run the backend API, expose it via LocalTunnel with a permanent subdomain,
# and launch Expo. Press Ctrl+C once to stop everything.

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKEND_DIR="${ROOT_DIR}/micro-service-boilerplate-main"
MOBILE_DIR="${ROOT_DIR}/mobile"
BACKEND_PORT=4000

# Choose a custom subdomain (will be: https://ielts-speaking-dev.loca.lt)
# LocalTunnel allows custom subdomains for free!
LOCALTUNNEL_SUBDOMAIN="ielts-speaking-dev-$(whoami | tr '[:upper:]' '[:lower:]')"

if [[ ! -d "${BACKEND_DIR}" ]]; then
  echo "Backend directory not found: ${BACKEND_DIR}" >&2
  exit 1
fi

if [[ ! -d "${MOBILE_DIR}" ]]; then
  echo "Mobile directory not found: ${MOBILE_DIR}" >&2
  exit 1
fi

cleanup() {
  if [[ -n "${BACKEND_PID:-}" ]] && ps -p "${BACKEND_PID}" >/dev/null 2>&1; then
    echo "\nStopping backend (PID ${BACKEND_PID})"
    kill "${BACKEND_PID}" >/dev/null 2>&1 || true
    wait "${BACKEND_PID}" 2>/dev/null || true
  fi

  if [[ -n "${TUNNEL_PID:-}" ]] && ps -p "${TUNNEL_PID}" >/dev/null 2>&1; then
    echo "Stopping LocalTunnel (PID ${TUNNEL_PID})"
    kill "${TUNNEL_PID}" >/dev/null 2>&1 || true
    wait "${TUNNEL_PID}" 2>/dev/null || true
  fi
}

trap cleanup EXIT INT TERM

# Free the backend port if something else is already listening on it.
if PIDS=$(lsof -tiTCP:"${BACKEND_PORT}" -sTCP:LISTEN 2>/dev/null); then
  if [[ -n "${PIDS}" ]]; then
    echo "Port ${BACKEND_PORT} already in use by: ${PIDS}. Sending SIGTERM."
    while read -r pid; do
      kill "${pid}" >/dev/null 2>&1 || true
    done <<<"${PIDS}"
    sleep 2
  fi
fi

# Check if LocalTunnel is installed
if ! command -v lt >/dev/null 2>&1; then
  echo "LocalTunnel not installed. Installing now..."
  npm install -g localtunnel
fi

echo "Starting backend (npx nps serve)"
(
  cd "${BACKEND_DIR}"
  npx nps serve
) &
BACKEND_PID=$!

# Wait until the backend port is listening
for attempt in {1..30}; do
  if lsof -iTCP:"${BACKEND_PORT}" -sTCP:LISTEN >/dev/null 2>&1; then
    echo "Backend listening on port ${BACKEND_PORT}"
    break
  fi
  if ! ps -p "${BACKEND_PID}" >/dev/null 2>&1; then
    echo "Backend process exited early; check logs above." >&2
    exit 1
  fi
  sleep 1

  if [[ ${attempt} -eq 30 ]]; then
    echo "Backend did not start within expected time." >&2
    exit 1
  fi
done

# Start LocalTunnel with custom subdomain
echo "Starting LocalTunnel with subdomain: ${LOCALTUNNEL_SUBDOMAIN}"
lt --port "${BACKEND_PORT}" --subdomain "${LOCALTUNNEL_SUBDOMAIN}" &
TUNNEL_PID=$!

# Give LocalTunnel a moment to start
sleep 3

# The URL will be: https://${LOCALTUNNEL_SUBDOMAIN}.loca.lt
TUNNEL_URL="https://${LOCALTUNNEL_SUBDOMAIN}.loca.lt"
echo "═══════════════════════════════════════════════════════════"
echo "🚀 LocalTunnel ready!"
echo "═══════════════════════════════════════════════════════════"
echo "Tunnel URL: ${TUNNEL_URL}"
echo "This URL is PERMANENT - it won't change on restart!"
echo "═══════════════════════════════════════════════════════════"

# Update .env with the tunnel URL
echo "Updating mobile/.env with tunnel URL..."
cd "${MOBILE_DIR}"

# Create or update .env file with LocalTunnel URL
cat > .env << EOF
# API Configuration (Auto-generated by start-backend-localtunnel.sh)
# Updated: $(date)

# API URL - Backend endpoint via LocalTunnel (permanent subdomain)
EXPO_PUBLIC_API_URL=${TUNNEL_URL}/api/v1

# Socket URL - WebSocket endpoint via LocalTunnel
EXPO_PUBLIC_SOCKET_URL=${TUNNEL_URL}

# API Key - Backend authentication key
EXPO_PUBLIC_API_KEY=local-dev-api-key
EOF

echo "✅ Updated .env with tunnel URL"

# Save URL to docs
echo "${TUNNEL_URL}" > "${ROOT_DIR}/docs/CURRENT-TUNNEL-URL.txt"
echo "✅ Saved tunnel URL to docs/CURRENT-TUNNEL-URL.txt"

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Starting Expo..."
echo "═══════════════════════════════════════════════════════════"
echo ""

# Start Expo (this will run in the foreground)
cd "${MOBILE_DIR}"
npx expo start --tunnel

# When Expo exits, cleanup will be called automatically
