module.exports = {
  vocab: {
    employment: [
    ['upskillation','n','The act or process of upskilling','retrain process,develop process,advance process','B2'],
    ['upskiller','n','A person who upskills','retrain person,develop person,advance person','C1'],
    ['upskillable','adj','Able to be upskilld','retrain,possible','C1'],
    ['upskilling','n','The process of upskilling something','retrain activity','B2'],
    ['burnoutal','adj','Relating to burnout','fatigue-related','B2'],
    ['precariatal','adj','Relating to precariat','vulnerable workers-related','C1'],
    ['presenteeismal','adj','Relating to presenteeism','unproductive attendance-related','C2'],
    ['colleagueal','adj','Relating to colleague','co-worker-related','A2'],
    ['uniformal','adj','Relating to uniform','work clothes-related','A2'],
    ['shiftal','adj','Relating to shift','work period-related','B1'],
    ['overtimeal','adj','Relating to overtime','extra hours-related','B1'],
    ['probational','adj','Relating to probation','trial-related','B1'],
    ['incentiveal','adj','Relating to incentive','bonus-related','B2'],
    ['severanceal','adj','Relating to severance','termination pay-related','B2'],
    ['arbitrational','adj','Relating to arbitration','mediation-related','C1'],
    ['whistlebloweral','adj','Relating to whistleblower','informant-related','B2'],
    ['moonlightingal','adj','Relating to moonlighting','side job-related','C1'],
    ['headhunteral','adj','Relating to headhunter','recruiter-related','B2'],
    ['furloughal','adj','Relating to furlough','layoff-related','B2'],
    ['retrenchmental','adj','Relating to retrenchment','downsizing-related','C1'],
    ['sweatshopal','adj','Relating to sweatshop','exploitative workplace-related','B2'],
    ['ergonomicsal','adj','Relating to ergonomics','workplace design-related','B2'],
    ['attritional','adj','Relating to attrition','natural wastage-related','C1']
    ],
    family: [
    ['grandparent','n','The parent of a persons parent','grandmother,grandfather,elder','A2'],
    ['patrilineal','adj','Tracing descent through the father','male-line,paternal,father-based','C1'],
    ['endogamy','n','Marriage within a specific social group','in-group marriage,community marriage','C2'],
    ['exogamy','n','Marriage outside a specific social group','out-marriage,cross-group marriage','C2'],
    ['affinity','n','A natural liking or connection','bond,closeness,kinship','B2'],
    ['neonatal','adj','Relating to newborn children','newborn,infant,early-life','C1'],
    ['gestation','n','The period of development before birth','pregnancy,incubation,carrying','C1'],
    ['parental','adj','Relating to parent','guardian-related','A2'],
    ['childal','adj','Relating to child','kid-related','A2'],
    ['brotheral','adj','Relating to brother','sibling-related','A2'],
    ['sisteral','adj','Relating to sister','sibling-related','A2'],
    ['marryation','n','The act or process of marrying','wed process,unite process,tie the knot process','A2'],
    ['marryer','n','A person who marrys','wed person,unite person,tie the knot person','B1'],
    ['marryable','adj','Able to be marryd','wed,possible','B1'],
    ['marrying','n','The process of marrying something','wed activity','A2'],
    ['babyal','adj','Relating to baby','infant-related','A2'],
    ['generational','adj','Relating to generation','age group-related','B1'],
    ['upbringingal','adj','Relating to upbringing','rearing-related','B1'],
    ['siblingal','adj','Relating to sibling','brother or sister-related','B1'],
    ['custodyal','adj','Relating to custody','guardianship-related','B1'],
    ['inheritanceal','adj','Relating to inheritance','legacy-related','B1'],
    ['patriarchally','adv','In a patriarchal manner','male-led way','B2'],
    ['patriarchalness','n','The quality of being patriarchal','male-led quality','C1'],
    ['unpatriarchal','adj','Not patriarchal','not male-led','B2'],
    ['matriarchally','adv','In a matriarchal manner','female-led way','B2'],
    ['matriarchalness','n','The quality of being matriarchal','female-led quality','C1'],
    ['unmatriarchal','adj','Not matriarchal','not female-led','B2'],
    ['kinshipal','adj','Relating to kinship','family ties-related','B2'],
    ['genealogyal','adj','Relating to genealogy','family tree-related','B2'],
    ['primogenitureal','adj','Relating to primogeniture','birthright-related','C1'],
    ['filially','adv','In a filial manner','dutiful way','C1'],
    ['filialness','n','The quality of being filial','dutiful quality','C2'],
    ['unfilial','adj','Not filial','not dutiful','C1'],
    ['consanguinityal','adj','Relating to consanguinity','blood tie-related','C2'],
    ['grandparental','adj','Relating to grandparent','grandmother-related','A2'],
    ['cousinal','adj','Relating to cousin','relative-related','A2'],
    ['nephewal','adj','Relating to nephew','relative-related','A2'],
    ['nieceal','adj','Relating to niece','relative-related','A2'],
    ['adolescental','adj','Relating to adolescent','teenager-related','B1'],
    ['guardianal','adj','Relating to guardian','protector-related','B1'],
    ['fosteration','n','The act or process of fostering','look after process,nurture process,raise process','B1'],
    ['fosterer','n','A person who fosters','look after person,nurture person,raise person','B2'],
    ['fosterable','adj','Able to be fosterd','look after,possible','B2'],
    ['fostering','n','The process of fostering something','look after activity','B1'],
    ['dysfunctionally','adv','In a dysfunctional manner','troubled way','B2'],
    ['dysfunctionalness','n','The quality of being dysfunctional','troubled quality','C1'],
    ['undysfunctional','adj','Not dysfunctional','not troubled','B2'],
    ['patrilineally','adv','In a patrilineal manner','male-line way','C1'],
    ['patrilinealness','n','The quality of being patrilineal','male-line quality','C2'],
    ['unpatrilineal','adj','Not patrilineal','not male-line','C1'],
    ['polygamyal','adj','Relating to polygamy','plural marriage-related','C1'],
    ['progenyal','adj','Relating to progeny','children-related','C2'],
    ['endogamyal','adj','Relating to endogamy','in-group marriage-related','C2'],
    ['exogamyal','adj','Relating to exogamy','out-marriage-related','C2'],
    ['affinityal','adj','Relating to affinity','bond-related','B2'],
    ['nurturation','n','The act or process of nurturing','raise process,foster process,cultivate process','B1'],
    ['nurturer','n','A person who nurtures','raise person,foster person,cultivate person','B2'],
    ['nurturable','adj','Able to be nurtured','raise,possible','B2'],
    ['nurturing','n','The process of nurturing something','raise activity','B1'],
    ['estrangemental','adj','Relating to estrangement','separation-related','C1'],
    ['bereavemental','adj','Relating to bereavement','grief-related','B2'],
    ['neonatally','adv','In a neonatal manner','newborn way','C1'],
    ['neonatalness','n','The quality of being neonatal','newborn quality','C2'],
    ['unneonatal','adj','Not neonatal','not newborn','C1'],
    ['gestational','adj','Relating to gestation','pregnancy-related','C1']
    ],
    history: [
    ['past','n','The time before the present','history,earlier times,antiquity','A2'],
    ['primary source','n','A firsthand account from the past','original document,eyewitness record','B2'],
    ['revisionism','n','Reinterpretation of established history','historical re-evaluation,re-analysis','B2'],
    ['palaeography','n','The study of historical handwriting','script analysis,manuscript study','C1'],
    ['crusade','n','A medieval religious military campaign','holy war,expedition,campaign','B2'],
    ['abolition','n','The ending of a system or practice','termination,elimination,repeal','B2'],
    ['genocide','n','The deliberate killing of a large ethnic group','mass killing,ethnic cleansing','B2'],
    ['decolonisation','n','A country gaining independence from a coloniser','liberation,self-determination','C1'],
    ['Mesopotamia','n','An ancient civilisation in modern Iraq','cradle of civilisation,ancient Near East','B2'],
    ['antebellum','adj','Occurring before a war','pre-war,pre-conflict,earlier','C1'],
    ['fin de siecle','n','The end of a century marked by decadence','century end,twilight era','C2'],
    ['historiographic','adj','Relating to the writing of history','history-writing,record-based','C2'],
    ['pax','n','A period of peace under a dominant power','peace era,stable period','C2'],
    ['annals','n','Historical records of events year by year','chronicles,records,archives','C1'],
    ['epigraphy','n','The study of inscriptions on surfaces','inscription study,engraving analysis','C2'],
    ['kingal','adj','Relating to king','monarch-related','A2'],
    ['queenal','adj','Relating to queen','monarch-related','A2'],
    ['waral','adj','Relating to war','conflict-related','A2'],
    ['pastal','adj','Relating to past','history-related','A2'],
    ['oldly','adv','In a old manner','ancient way','A2'],
    ['oldness','n','The quality of being old','ancient quality','B1'],
    ['unold','adj','Not old','not ancient','A2'],
    ['castleal','adj','Relating to castle','fortress-related','A2'],
    ['empireal','adj','Relating to empire','kingdom-related','B1'],
    ['revolutional','adj','Relating to revolution','uprising-related','B1'],
    ['civilisational','adj','Relating to civilisation','culture-related','B1'],
    ['colonyal','adj','Relating to colony','settlement-related','B1'],
    ['treatyal','adj','Relating to treaty','accord-related','B1'],
    ['independenceal','adj','Relating to independence','sovereignty-related','B1'],
    ['archaeologyal','adj','Relating to archaeology','excavation science-related','B1'],
    ['imperialismal','adj','Relating to imperialism','colonialism-related','B2'],
    ['feudalismal','adj','Relating to feudalism','serfdom-related','B2'],
    ['historiographyal','adj','Relating to historiography','historical method-related','B2'],
    ['revisionismal','adj','Relating to revisionism','historical re-evaluation-related','B2'],
    ['anachronismal','adj','Relating to anachronism','time error-related','C1'],
    ['palaeographyal','adj','Relating to palaeography','script analysis-related','C1'],
    ['hagiographyal','adj','Relating to hagiography','glorified account-related','C2'],
    ['conqueration','n','The act or process of conquering','seize process,capture process,defeat process','B1'],
    ['conquerer','n','A person who conquers','seize person,capture person,defeat person','B2'],
    ['conquerable','adj','Able to be conquerd','seize,possible','B2'],
    ['conquering','n','The process of conquering something','seize activity','B1'],
    ['monarchyal','adj','Relating to monarchy','royalty-related','B1'],
    ['medievally','adv','In a medieval manner','middle-age way','B1'],
    ['medievalness','n','The quality of being medieval','middle-age quality','B2'],
    ['unmedieval','adj','Not medieval','not middle-age','B1'],
    ['dynastyal','adj','Relating to dynasty','lineage-related','B2'],
    ['crusadeal','adj','Relating to crusade','holy war-related','B2'],
    ['abolitional','adj','Relating to abolition','termination-related','B2'],
    ['genocideal','adj','Relating to genocide','mass killing-related','B2'],
    ['armisticeal','adj','Relating to armistice','ceasefire-related','C1'],
    ['decolonisational','adj','Relating to decolonisation','liberation-related','C1'],
    ['antebellumly','adv','In a antebellum manner','pre-war way','C1'],
    ['antebellumness','n','The quality of being antebellum','pre-war quality','C2'],
    ['unantebellum','adj','Not antebellum','not pre-war','C1']
    ],
  },
  collocations: {
  }
};
