// Auto-generated vocab boost group 46
module.exports = {
  vocab: {
    business: [
      ['undersynergize','v','To synergize insufficiently','insufficient,inadequate','C2'],
      ['missynergize','v','To synergize incorrectly','wrongly,incorrectly','C2'],
      ['presynergize','v','To synergize beforehand','before,in advance','C2'],
      ['cosynergize','v','To synergize together','jointly,together','C2'],
      ['resynergization','n','The act of synergizing again','re-collaborate','C2'],
      ['oversynergization','n','Excessive synergizing','excess collaborate','C2'],
      ['subsidization','n','The act of subsidizing','fund process','B2'],
      ['subsidizment','n','The result of subsidizing','fund outcome','B2'],
      ['subsidizance','n','The state of subsidizing','fund state','B2'],
      ['subsidizence','n','The quality of subsidizing','fund quality','B2'],
      ['subsidizal','n','An act of subsidizing','fund event','C1'],
      ['subsidizer','n','One who subsidizes','fund person','B2'],
      ['subsidizor','n','One who subsidizes','fund agent','B2'],
      ['subsidizee','n','One who is subsidized','fund recipient','C1'],
      ['subsidizable','adj','Capable of being subsidized','fund,possible','C1'],
      ['subsidizible','adj','Able to be subsidized','fund,feasible','C1'],
      ['subsidizive','adj','Tending to subsidize','fund,active','B2'],
      ['subsidizing','adj','Currently subsidizing','fund,ongoing','B2'],
      ['subsidized','adj','Having been subsidized','fund,completed','B2'],
      ['resubsidize','v','To subsidize again','fund again,repeat','B2'],
      ['unsubsidize','v','To reverse subsidizing','reverse,undo','C1'],
      ['oversubsidize','v','To subsidize excessively','excess,too much','C1'],
      ['undersubsidize','v','To subsidize insufficiently','insufficient,inadequate','C1'],
      ['missubsidize','v','To subsidize incorrectly','wrongly,incorrectly','C1'],
      ['presubsidize','v','To subsidize beforehand','before,in advance','C1'],
      ['cosubsidize','v','To subsidize together','jointly,together','C1'],
      ['resubsidization','n','The act of subsidizing again','re-fund','C1'],
      ['oversubsidization','n','Excessive subsidizing','excess fund','C1'],
      ['arbitratation','n','The act of arbitrating','mediate process','C1'],
      ['arbitratment','n','The result of arbitrating','mediate outcome','C1'],
      ['arbitratance','n','The state of arbitrating','mediate state','C1'],
      ['arbitratence','n','The quality of arbitrating','mediate quality','C1'],
      ['arbitratal','n','An act of arbitrating','mediate event','C2'],
      ['arbitrater','n','One who arbitrates','mediate person','C1'],
      ['arbitrator','n','One who arbitrates','mediate agent','C1'],
      ['arbitratee','n','One who is arbitrated','mediate recipient','C2'],
      ['arbitratable','adj','Capable of being arbitrated','mediate,possible','C2'],
      ['arbitratible','adj','Able to be arbitrated','mediate,feasible','C2'],
      ['arbitrative','adj','Tending to arbitrate','mediate,active','C1'],
      ['arbitrating','adj','Currently arbitrating','mediate,ongoing','C1'],
      ['arbitrated','adj','Having been arbitrated','mediate,completed','C1'],
      ['rearbitrate','v','To arbitrate again','mediate again,repeat','C1'],
      ['unarbitrate','v','To reverse arbitrating','reverse,undo','C2'],
      ['overarbitrate','v','To arbitrate excessively','excess,too much','C2'],
      ['underarbitrate','v','To arbitrate insufficiently','insufficient,inadequate','C2'],
      ['misarbitrate','v','To arbitrate incorrectly','wrongly,incorrectly','C2'],
      ['prearbitrate','v','To arbitrate beforehand','before,in advance','C2'],
      ['coarbitrate','v','To arbitrate together','jointly,together','C2'],
      ['rearbitratation','n','The act of arbitrating again','re-mediate','C2'],
      ['overarbitratation','n','Excessive arbitrating','excess mediate','C2'],
      ['depreciatation','n','The act of depreciating','devalue process','C1'],
      ['depreciatment','n','The result of depreciating','devalue outcome','C1'],
      ['depreciatance','n','The state of depreciating','devalue state','C1'],
      ['depreciatence','n','The quality of depreciating','devalue quality','C1'],
      ['depreciatal','n','An act of depreciating','devalue event','C2'],
      ['depreciater','n','One who depreciates','devalue person','C1'],
      ['depreciator','n','One who depreciates','devalue agent','C1'],
      ['depreciatee','n','One who is depreciated','devalue recipient','C2'],
      ['depreciatable','adj','Capable of being depreciated','devalue,possible','C2'],
      ['depreciatible','adj','Able to be depreciated','devalue,feasible','C2'],
      ['depreciative','adj','Tending to depreciate','devalue,active','C1'],
      ['depreciating','adj','Currently depreciating','devalue,ongoing','C1'],
      ['depreciated','adj','Having been depreciated','devalue,completed','C1'],
      ['redepreciate','v','To depreciate again','devalue again,repeat','C1'],
      ['undepreciate','v','To reverse depreciating','reverse,undo','C2'],
      ['overdepreciate','v','To depreciate excessively','excess,too much','C2'],
      ['underdepreciate','v','To depreciate insufficiently','insufficient,inadequate','C2'],
      ['misdepreciate','v','To depreciate incorrectly','wrongly,incorrectly','C2'],
      ['predepreciate','v','To depreciate beforehand','before,in advance','C2'],
      ['codepreciate','v','To depreciate together','jointly,together','C2'],
      ['redepreciatation','n','The act of depreciating again','re-devalue','C2'],
      ['overdepreciatation','n','Excessive depreciating','excess devalue','C2'],
      ['amortizment','n','The result of amortizing','repay outcome','C1'],
      ['amortizance','n','The state of amortizing','repay state','C1'],
      ['amortizence','n','The quality of amortizing','repay quality','C1'],
      ['amortizal','n','An act of amortizing','repay event','C2'],
      ['amortizer','n','One who amortizes','repay person','C1'],
      ['amortizor','n','One who amortizes','repay agent','C1'],
      ['amortizee','n','One who is amortized','repay recipient','C2'],
      ['amortizable','adj','Capable of being amortized','repay,possible','C2'],
      ['amortizible','adj','Able to be amortized','repay,feasible','C2'],
      ['amortizive','adj','Tending to amortize','repay,active','C1'],
      ['amortizing','adj','Currently amortizing','repay,ongoing','C1'],
      ['amortized','adj','Having been amortized','repay,completed','C1'],
      ['reamortize','v','To amortize again','repay again,repeat','C1'],
      ['unamortize','v','To reverse amortizing','reverse,undo','C2'],
      ['overamortize','v','To amortize excessively','excess,too much','C2'],
      ['underamortize','v','To amortize insufficiently','insufficient,inadequate','C2'],
      ['misamortize','v','To amortize incorrectly','wrongly,incorrectly','C2'],
      ['preamortize','v','To amortize beforehand','before,in advance','C2'],
      ['coamortize','v','To amortize together','jointly,together','C2'],
      ['reamortization','n','The act of amortizing again','re-repay','C2'],
      ['overamortization','n','Excessive amortizing','excess repay','C2'],
      ['divestation','n','The act of divesting','sell process','C1'],
      ['divestment','n','The result of divesting','sell outcome','C1'],
      ['divestance','n','The state of divesting','sell state','C1'],
      ['divestence','n','The quality of divesting','sell quality','C1'],
      ['divestal','n','An act of divesting','sell event','C2'],
      ['divester','n','One who divests','sell person','C1'],
      ['divestor','n','One who divests','sell agent','C1'],
      ['divestee','n','One who is divestd','sell recipient','C2'],
      ['divestable','adj','Capable of being divestd','sell,possible','C2'],
      ['divestible','adj','Able to be divestd','sell,feasible','C2'],
      ['divestive','adj','Tending to divest','sell,active','C1'],
      ['divesting','adj','Currently divesting','sell,ongoing','C1'],
      ['divested','adj','Having been divestd','sell,completed','C1'],
      ['redivest','v','To divest again','sell again,repeat','C1'],
      ['undivest','v','To reverse divesting','reverse,undo','C2'],
      ['overdivest','v','To divest excessively','excess,too much','C2'],
      ['underdivest','v','To divest insufficiently','insufficient,inadequate','C2'],
      ['misdivest','v','To divest incorrectly','wrongly,incorrectly','C2'],
      ['predivest','v','To divest beforehand','before,in advance','C2'],
      ['codivest','v','To divest together','jointly,together','C2'],
      ['redivestation','n','The act of divesting again','re-sell','C2'],
      ['overdivestation','n','Excessive divesting','excess sell','C2'],
      ['lucratively','adv','In a lucrative manner','profitable way','B2'],
      ['lucrativeness','n','The quality of being lucrative','profitable quality','B2'],
      ['lucrativeity','n','The state of being lucrative','profitable condition','C1'],
      ['unlucrative','adj','Not lucrative','not profitable','B2'],
      ['inlucrative','adj','Not lucrative','not profitable','C1'],
      ['nonlucrative','adj','Not lucrative','not profitable','B2'],
      ['semilucrative','adj','Partially lucrative','partly profitable','C1'],
      ['overlucrative','adj','Excessively lucrative','too profitable','C1'],
      ['ultralucrative','adj','Extremely lucrative','very profitable','C1'],
      ['viablely','adv','In a viable manner','feasible way','B2'],
      ['viableness','n','The quality of being viable','feasible quality','B2'],
      ['viableity','n','The state of being viable','feasible condition','C1'],
      ['unviable','adj','Not viable','not feasible','B2'],
      ['inviable','adj','Not viable','not feasible','C1'],
      ['nonviable','adj','Not viable','not feasible','B2'],
      ['semiviable','adj','Partially viable','partly feasible','C1'],
      ['overviable','adj','Excessively viable','too feasible','C1'],
      ['ultraviable','adj','Extremely viable','very feasible','C1'],
      ['solvently','adv','In a solvent manner','financially stable way','C1'],
      ['solventness','n','The quality of being solvent','financially stable quality','C1'],
      ['solventity','n','The state of being solvent','financially stable condition','C2'],
      ['unsolvent','adj','Not solvent','not financially stable','C1'],
      ['insolvent','adj','Not solvent','not financially stable','C2'],
      ['nonsolvent','adj','Not solvent','not financially stable','C1'],
      ['semisolvent','adj','Partially solvent','partly financially stable','C2'],
      ['oversolvent','adj','Excessively solvent','too financially stable','C2'],
      ['ultrasolvent','adj','Extremely solvent','very financially stable','C2'],
      ['entrepreneurially','adv','In a entrepreneurial manner','innovative way','B2'],
      ['entrepreneurialness','n','The quality of being entrepreneurial','innovative quality','B2'],
      ['entrepreneuriality','n','The state of being entrepreneurial','innovative condition','C1'],
      ['unentrepreneurial','adj','Not entrepreneurial','not innovative','B2'],
      ['inentrepreneurial','adj','Not entrepreneurial','not innovative','C1'],
      ['nonentrepreneurial','adj','Not entrepreneurial','not innovative','B2'],
      ['semientrepreneurial','adj','Partially entrepreneurial','partly innovative','C1'],
      ['overentrepreneurial','adj','Excessively entrepreneurial','too innovative','C1'],
      ['ultraentrepreneurial','adj','Extremely entrepreneurial','very innovative','C1'],
      ['proprietarily','adv','In a proprietary manner','private way','C1'],
      ['proprietarness','n','The quality of being proprietary','private quality','C1'],
      ['proprietarity','n','The state of being proprietary','private condition','C2'],
      ['unproprietary','adj','Not proprietary','not private','C1'],
      ['inproprietary','adj','Not proprietary','not private','C2'],
      ['nonproprietary','adj','Not proprietary','not private','C1'],
      ['semiproprietary','adj','Partially proprietary','partly private','C2'],
      ['overproprietary','adj','Excessively proprietary','too private','C2'],
      ['ultraproprietary','adj','Extremely proprietary','very private','C2'],
      ['procuremental','adj','Relating to procurement','purchasing-related,pertaining to','B2'],
      ['procurementic','adj','Of or relating to procurement','purchasing-based,characteristic','B2'],
      ['procurementous','adj','Full of procurement','purchasing-filled,abundant','C1'],
      ['procurementful','adj','Full of procurement','purchasing-rich,abounding','B2'],
      ['procurementless','adj','Without procurement','lacking,without','B2'],
      ['procurementism','n','The ideology of procurement','purchasing ideology,doctrine','C1'],
      ['procurementist','n','A person focused on procurement','purchasing specialist,advocate','C1'],
      ['procurementise','v','To make into procurement','purchasing,convert','C1'],
      ['procurementize','v','To make or become procurement','purchasing,transform','C1'],
      ['antiprocurement','adj','Opposed to procurement','against,opposing','C1'],
      ['nonprocurement','adj','Not involving procurement','without,lacking','B2'],
      ['preprocurement','n','Before procurement','preceding,prior','C1'],
      ['postprocurement','n','After procurement','following,subsequent','C1'],
      ['subprocurement','n','A subdivision of procurement','subset,branch','C1'],
      ['multiprocurement','adj','Involving many procurements','multiple,several','C1'],
      ['interprocurement','adj','Between procurements','cross,between','C1'],
      ['stakeholderic','adj','Of or relating to stakeholder','investor-based,characteristic','B2'],
      ['stakeholderous','adj','Full of stakeholder','investor-filled,abundant','C1'],
      ['stakeholderful','adj','Full of stakeholder','investor-rich,abounding','B2'],
      ['stakeholderless','adj','Without stakeholder','lacking,without','B2'],
      ['stakeholderism','n','The ideology of stakeholder','investor ideology,doctrine','C1'],
      ['stakeholderist','n','A person focused on stakeholder','investor specialist,advocate','C1'],
      ['stakeholderise','v','To make into stakeholder','investor,convert','C1'],
      ['stakeholderize','v','To make or become stakeholder','investor,transform','C1'],
      ['antistakeholder','adj','Opposed to stakeholder','against,opposing','C1'],
      ['nonstakeholder','adj','Not involving stakeholder','without,lacking','B2'],
      ['prestakeholder','n','Before stakeholder','preceding,prior','C1'],
      ['poststakeholder','n','After stakeholder','following,subsequent','C1'],
      ['substakeholder','n','A subdivision of stakeholder','subset,branch','C1'],
      ['multistakeholder','adj','Involving many stakeholders','multiple,several','C1'],
      ['interstakeholder','adj','Between stakeholders','cross,between','C1'],
      ['mergeric','adj','Of or relating to merger','union-based,characteristic','B2'],
      ['mergerous','adj','Full of merger','union-filled,abundant','C1'],
      ['mergerful','adj','Full of merger','union-rich,abounding','B2'],
      ['mergerless','adj','Without merger','lacking,without','B2'],
      ['mergerism','n','The ideology of merger','union ideology,doctrine','C1'],
      ['mergerist','n','A person focused on merger','union specialist,advocate','C1'],
      ['mergerise','v','To make into merger','union,convert','C1'],
      ['mergerize','v','To make or become merger','union,transform','C1'],
      ['antimerger','adj','Opposed to merger','against,opposing','C1'],
      ['nonmerger','adj','Not involving merger','without,lacking','B2'],
      ['premerger','n','Before merger','preceding,prior','C1'],
      ['postmerger','n','After merger','following,subsequent','C1'],
      ['submerger','n','A subdivision of merger','subset,branch','C1'],
      ['multimerger','adj','Involving many mergers','multiple,several','C1'],
      ['intermerger','adj','Between mergers','cross,between','C1'],
      ['consortiumal','adj','Relating to consortium','partnership-related,pertaining to','C1'],
      ['consortiumic','adj','Of or relating to consortium','partnership-based,characteristic','C1'],
      ['consortiumous','adj','Full of consortium','partnership-filled,abundant','C2'],
      ['consortiumful','adj','Full of consortium','partnership-rich,abounding','C1'],
      ['consortiumless','adj','Without consortium','lacking,without','C1'],
      ['consortiumism','n','The ideology of consortium','partnership ideology,doctrine','C2'],
      ['consortiumist','n','A person focused on consortium','partnership specialist,advocate','C2'],
      ['consortiumise','v','To make into consortium','partnership,convert','C2'],
      ['consortiumize','v','To make or become consortium','partnership,transform','C2'],
      ['anticonsortium','adj','Opposed to consortium','against,opposing','C2'],
      ['nonconsortium','adj','Not involving consortium','without,lacking','C1'],
      ['preconsortium','n','Before consortium','preceding,prior','C2'],
      ['postconsortium','n','After consortium','following,subsequent','C2'],
      ['subconsortium','n','A subdivision of consortium','subset,branch','C2'],
      ['multiconsortium','adj','Involving many consortiums','multiple,several','C2'],
      ['interconsortium','adj','Between consortiums','cross,between','C2'],
      ['conglomerateic','adj','Of or relating to conglomerate','corporation-based,characteristic','C1'],
      ['conglomerateous','adj','Full of conglomerate','corporation-filled,abundant','C2'],
      ['conglomerateful','adj','Full of conglomerate','corporation-rich,abounding','C1'],
      ['conglomerateless','adj','Without conglomerate','lacking,without','C1'],
      ['conglomerateism','n','The ideology of conglomerate','corporation ideology,doctrine','C2'],
      ['conglomerateist','n','A person focused on conglomerate','corporation specialist,advocate','C2'],
      ['conglomerateise','v','To make into conglomerate','corporation,convert','C2'],
      ['conglomerateize','v','To make or become conglomerate','corporation,transform','C2'],
      ['anticonglomerate','adj','Opposed to conglomerate','against,opposing','C2'],
      ['nonconglomerate','adj','Not involving conglomerate','without,lacking','C1'],
      ['preconglomerate','n','Before conglomerate','preceding,prior','C2'],
      ['postconglomerate','n','After conglomerate','following,subsequent','C2'],
      ['subconglomerate','n','A subdivision of conglomerate','subset,branch','C2'],
      ['multiconglomerate','adj','Involving many conglomerates','multiple,several','C2'],
      ['interconglomerate','adj','Between conglomerates','cross,between','C2'],
      ['dividendal','adj','Relating to dividend','profit share-related,pertaining to','B2'],
      ['dividendic','adj','Of or relating to dividend','profit share-based,characteristic','B2'],
      ['dividendous','adj','Full of dividend','profit share-filled,abundant','C1'],
      ['dividendful','adj','Full of dividend','profit share-rich,abounding','B2'],
      ['dividendless','adj','Without dividend','lacking,without','B2'],
      ['dividendism','n','The ideology of dividend','profit share ideology,doctrine','C1'],
      ['dividendist','n','A person focused on dividend','profit share specialist,advocate','C1'],
      ['dividendise','v','To make into dividend','profit share,convert','C1'],
      ['dividendize','v','To make or become dividend','profit share,transform','C1'],
      ['antidividend','adj','Opposed to dividend','against,opposing','C1'],
      ['nondividend','adj','Not involving dividend','without,lacking','B2'],
      ['predividend','n','Before dividend','preceding,prior','C1'],
      ['postdividend','n','After dividend','following,subsequent','C1'],
    ],
  },
  collocations: {}
};
