'use strict';
module.exports = {
  vocab: {
    travel: [
      ["accommodation","noun","A place to live or stay temporarily","lodging,housing","A2"],
      ["backpack","noun","A bag carried on the back when travelling","rucksack,knapsack","A2"],
      ["boarding","noun","The act of getting onto an aircraft or ship","embarkation,entry","A2"],
      ["brochure","noun","A small booklet with information about a product or place","pamphlet,leaflet","A2"],
      ["cabin","noun","A small room on a ship or aircraft","compartment,berth","B1"],
      ["camping","noun","The activity of staying in a tent outdoors","outdoors living,tent stay","B1"],
      ["commute","verb","To travel regularly between home and work","travel daily,journey to work","B1"],
      ["cruise","noun","A voyage on a ship for pleasure","sea voyage,sailing trip","B1"],
      ["customs","noun","The place at a border where goods are checked","border control,checkpoint","B1"],
      ["delay","noun","A period of time by which something is late","holdup,setback","B2"],
      ["departure","noun","The act of leaving a place","leaving,exit","B2"],
      ["destination","noun","The place to which someone is going","target,endpoint","B2"],
      ["embassy","noun","The official residence of an ambassador","consulate,diplomatic mission","B2"],
      ["excursion","noun","A short journey or trip for pleasure","outing,trip","B2"],
      ["fare","noun","The money paid for a journey on public transport","ticket price,cost","B2"],
      ["ferry","noun","A boat that carries passengers across water","boat,vessel","C1"],
      ["guidebook","noun","A book of information about a place for visitors","travel guide,handbook","C1"],
      ["hitchhike","verb","To travel by getting free rides from passing vehicles","thumb a ride,get a lift","C1"],
      ["hostel","noun","A place providing cheap accommodation for travellers","guesthouse,inn","C1"],
      ["itinerary","noun","A planned route or journey","schedule,travel plan","C2"],
      ["jet lag","noun","Tiredness felt after a long flight across time zones","travel fatigue,time zone syndrome","A2"],
      ["luggage","noun","Suitcases and bags used when travelling","baggage,cases","A2"],
      ["motel","noun","A roadside hotel for motorists","motor hotel,inn","A2"],
      ["passport","noun","An official document for international travel","travel document,ID","A2"],
      ["platform","noun","A raised surface where passengers board trains","station area,boarding area","B1"],
      ["resort","noun","A place frequented for holidays and recreation","holiday destination,retreat","B1"],
      ["runway","noun","A strip of hard ground where aircraft take off","airstrip,landing strip","B1"],
      ["sightseeing","noun","The activity of visiting places of interest","touring,exploring","B1"],
      ["souvenir","noun","A thing kept as a reminder of a place visited","memento,keepsake","B1"],
      ["suitcase","noun","A case with a handle for carrying clothes","bag,trunk","B2"],
      ["terminal","noun","A building at an airport for passengers","airport building,departure hall","B2"],
      ["ticket","noun","A piece of paper giving the holder a right to travel","pass,boarding pass","B2"],
      ["tourism","noun","The commercial organisation of holidays and visits","travel industry,hospitality","B2"],
      ["tourist","noun","A person travelling for pleasure","visitor,traveller","B2"],
      ["trekking","noun","Making a long or difficult journey on foot","hiking,walking","B2"],
      ["vacation","noun","An extended period of leisure away from work","holiday,break","C1"],
      ["visa","noun","An endorsement on a passport permitting entry","entry permit,travel authorisation","C1"],
      ["voyage","noun","A long journey by sea or in space","journey,trip","C1"],
    ],
    government: [
      ["abolish","verb","To formally put an end to a system or practice","end,eliminate","A2"],
      ["authority","noun","The power to give orders or make decisions","power,jurisdiction","A2"],
      ["ballot","noun","A process of voting in an election","vote,poll","A2"],
      ["bureaucracy","noun","A system of government with many rules and processes","administration,red tape","A2"],
      ["campaign","noun","An organised effort to achieve a political goal","drive,movement","B1"],
      ["candidate","noun","A person who applies for a job or runs for office","applicant,nominee","B1"],
      ["constitution","noun","The fundamental principles of governing a state","charter,basic law","B1"],
      ["debate","noun","A formal discussion on a particular topic","discussion,argument","B1"],
      ["decree","noun","An official order issued by a legal authority","edict,order","B1"],
      ["diplomat","noun","An official representing a country abroad","ambassador,envoy","B2"],
      ["election","noun","A formal process of choosing a person for office","vote,ballot","B2"],
      ["enact","verb","To make a bill or proposal into law","pass,legislate","B2"],
      ["federal","adj","Relating to a system of government with central and regional authority","national,central","B2"],
      ["govern","verb","To conduct the policy and affairs of a state","rule,administer","B2"],
      ["ideology","noun","A system of ideas forming the basis of a political theory","doctrine,belief system","B2"],
      ["legislation","noun","Laws collectively enacted by a legislature","law,statute","C1"],
      ["liberty","noun","The state of being free within society","freedom,independence","C1"],
      ["mayor","noun","The elected head of a city or town","city leader,municipal head","C1"],
      ["minister","noun","A senior member of government heading a department","secretary,official","C1"],
      ["monarchy","noun","A form of government with a monarch as head","kingdom,royal rule","C2"],
      ["opposition","noun","A group that disagrees with those in power","rival party,dissent","A2"],
      ["parliament","noun","The supreme legislative body of a country","legislature,congress","A2"],
      ["petition","noun","A formal written request signed by many people","appeal,plea","A2"],
      ["policy","noun","A course of action adopted by a government","strategy,plan","A2"],
      ["political","adj","Relating to the government or public affairs","governmental,civic","B1"],
      ["president","noun","The elected head of a republic","head of state,leader","B1"],
      ["reform","noun","A change made to improve a system or institution","improvement,amendment","B1"],
      ["regulation","noun","A rule or directive made by an authority","rule,guideline","B1"],
      ["republic","noun","A state where power is held by elected representatives","democracy,commonwealth","B1"],
      ["senate","noun","The upper house of a legislative assembly","upper chamber,legislative body","B2"],
      ["sovereign","adj","Possessing supreme authority over a territory","independent,autonomous","B2"],
      ["treaty","noun","A formally concluded agreement between states","pact,accord","B2"],
      ["vote","verb","To formally indicate a choice in an election","cast a ballot,poll","B2"],
    ],
    crime: [
      ["arrest","verb","To seize someone by legal authority","detain,apprehend","A2"],
      ["assault","noun","A physical attack on another person","attack,battery","A2"],
      ["bail","noun","Temporary release of an accused person awaiting trial","bond,surety","A2"],
      ["burglar","noun","A person who commits burglary","thief,robber","A2"],
      ["convict","verb","To declare someone guilty of a criminal offence","find guilty,sentence","B1"],
      ["court","noun","A place where legal cases are heard","tribunal,law court","B1"],
      ["detective","noun","A person who investigates crimes","investigator,inspector","B1"],
      ["evidence","noun","Information indicating whether something is true","proof,testimony","B1"],
      ["fine","noun","A sum of money paid as a penalty","penalty,charge","B1"],
      ["forgery","noun","The action of producing a fraudulent copy","counterfeit,fake","B2"],
      ["fraud","noun","Wrongful deception intended for financial gain","scam,swindle","B2"],
      ["guilty","adj","Responsible for a specified wrongdoing","culpable,blameworthy","B2"],
      ["handcuffs","noun","A pair of lockable rings for securing a prisoner s wrists","restraints,manacles","B2"],
      ["innocent","adj","Not guilty of a crime or offence","not guilty,blameless","B2"],
      ["judge","noun","A public official who decides cases in a court of law","magistrate,justice","B2"],
      ["jury","noun","A group of people who decide the verdict in a trial","panel,tribunal","C1"],
      ["kidnap","verb","To take someone away illegally by force","abduct,seize","C1"],
      ["lawyer","noun","A person who practises law","attorney,solicitor","C1"],
      ["motive","noun","A reason for doing something, especially a crime","reason,cause","C1"],
      ["offence","noun","A breach of law or rule","crime,violation","C2"],
      ["prison","noun","A building where criminals are confined","jail,penitentiary","A2"],
      ["punishment","noun","A penalty imposed for breaking a law or rule","sentence,penalty","A2"],
      ["robbery","noun","The action of taking property unlawfully by force","theft,burglary","A2"],
      ["sentence","noun","The punishment assigned to a defendant found guilty","verdict,judgement","A2"],
      ["smuggle","verb","To move goods illegally into or out of a country","traffic,bootleg","B1"],
      ["suspect","noun","A person thought to be guilty of a crime","accused,defendant","B1"],
      ["theft","noun","The action of stealing","robbery,larceny","B1"],
      ["trial","noun","A judicial examination of evidence in a court","hearing,case","B1"],
      ["vandalism","noun","Deliberate destruction of public or private property","damage,defacement","B1"],
      ["verdict","noun","A decision on an issue of fact in a civil or criminal case","judgement,ruling","B2"],
      ["victim","noun","A person harmed as a result of a crime","sufferer,target","B2"],
      ["witness","noun","A person who sees an event take place","observer,bystander","B2"],
    ],
    media: [
      ["anchor","noun","A presenter of a news programme","newsreader,host","A2"],
      ["audience","noun","The group of people who watch or listen to a show","viewers,spectators","A2"],
      ["broadcast","verb","To transmit a programme by radio or television","air,transmit","A2"],
      ["caption","noun","A title or brief explanation under an illustration","subtitle,legend","A2"],
      ["celebrity","noun","A famous person, especially in entertainment","star,public figure","B1"],
      ["channel","noun","A television or radio station","station,network","B1"],
      ["circulation","noun","The number of copies of a newspaper sold","distribution,readership","B1"],
      ["column","noun","A regular section in a newspaper on a particular topic","feature,article","B1"],
      ["correspondent","noun","A journalist reporting from a particular place","reporter,journalist","B1"],
      ["coverage","noun","The reporting of news by the media","reporting,journalism","B2"],
      ["documentary","noun","A film giving a factual account of something","factual film,report","B2"],
      ["editor","noun","A person responsible for the content of a publication","chief writer,publication head","B2"],
      ["headline","noun","A heading at the top of a newspaper article","title,banner","B2"],
      ["interview","noun","A formal meeting for gathering information","questioning,conversation","B2"],
      ["journalist","noun","A person who writes for newspapers or media","reporter,writer","B2"],
      ["magazine","noun","A periodical publication with articles and illustrations","periodical,journal","C1"],
      ["mainstream","adj","The ideas and activities shared by most people","conventional,popular","C1"],
      ["media","noun","The main means of mass communication","press,broadcasting","C1"],
      ["news","noun","Newly received information about recent events","report,bulletin","C1"],
      ["paparazzi","noun","Photographers who pursue celebrities for pictures","press photographers,tabloid photographers","C2"],
      ["podcast","noun","A digital audio file available for downloading","audio show,internet broadcast","A2"],
      ["press","noun","Newspapers and journalists collectively","media,journalism","A2"],
      ["publish","verb","To prepare and issue a book or article for sale","print,release","A2"],
      ["reporter","noun","A person who reports news for a media outlet","journalist,correspondent","A2"],
      ["review","noun","A critical assessment of a book, film, or performance","critique,evaluation","B1"],
      ["satellite","noun","An artificial body placed in orbit for communication","orbiter,relay","B1"],
      ["script","noun","The written text of a broadcast or film","screenplay,dialogue","B1"],
      ["subscriber","noun","A person who pays to receive a publication regularly","member,follower","B1"],
      ["tabloid","noun","A newspaper with shorter articles and many pictures","popular press,red-top","B1"],
    ],
    communication: [
      ["accent","noun","A distinctive way of pronouncing a language","pronunciation,dialect","A2"],
      ["barrier","noun","An obstacle that prevents communication","obstacle,impediment","A2"],
      ["bilingual","adj","Able to speak two languages fluently","dual-language,two-tongued","A2"],
      ["body language","noun","Communication through physical behaviour","nonverbal cues,gestures","A2"],
      ["clarify","verb","To make a statement less confused and more understandable","explain,elucidate","B1"],
      ["convey","verb","To communicate or make known","express,transmit","B1"],
      ["dialogue","noun","A conversation between two or more people","discussion,exchange","B1"],
      ["eloquent","adj","Fluent and persuasive in speaking","articulate,expressive","B1"],
      ["empathy","noun","The ability to understand another person s feelings","compassion,understanding","B1"],
      ["fluent","adj","Able to speak a language easily and accurately","proficient,articulate","B2"],
      ["gesture","noun","A movement of the body to express an idea","motion,signal","B2"],
      ["gossip","noun","Casual talk about other people s private affairs","rumour,chatter","B2"],
      ["interpret","verb","To explain the meaning of information or actions","translate,decipher","B2"],
      ["jargon","noun","Special words used by a particular profession","terminology,lingo","B2"],
      ["lecture","noun","A formal talk delivered to an audience","speech,presentation","B2"],
      ["literate","adj","Able to read and write","educated,lettered","C1"],
      ["misunderstand","verb","To fail to interpret something correctly","misconceive,misinterpret","C1"],
      ["native speaker","noun","A person who speaks a language as their first language","mother-tongue speaker,first-language speaker","C1"],
      ["negotiate","verb","To try to reach an agreement through discussion","discuss,bargain","C1"],
      ["persuade","verb","To cause someone to believe or do something","convince,influence","C2"],
      ["pronounce","verb","To make the sound of a word or letter","articulate,enunciate","A2"],
      ["public speaking","noun","The act of making speeches in public","oratory,rhetoric","A2"],
      ["slang","noun","Very informal words used by a particular group","colloquialism,informal language","A2"],
      ["stammer","verb","To speak with involuntary pauses and repetitions","stutter,falter","A2"],
      ["summarise","verb","To give a brief statement of the main points","condense,recap","B1"],
      ["translate","verb","To express the meaning of words in another language","interpret,convert","B1"],
      ["verbal","adj","Relating to or in the form of words","oral,spoken","B1"],
      ["whisper","verb","To speak very softly using the breath","murmur,hush","B1"],
    ],
    sports: [
      ["amateur","noun","A person who engages in an activity as a pastime","hobbyist,nonprofessional","A2"],
      ["athlete","noun","A person who competes in sports","sportsperson,competitor","A2"],
      ["championship","noun","A contest for the position of champion","tournament,competition","A2"],
      ["coach","noun","A person who trains and instructs athletes","trainer,instructor","A2"],
      ["defeat","noun","An instance of being beaten in a competition","loss,failure","B1"],
      ["equipment","noun","The items needed for a particular activity","gear,apparatus","B1"],
      ["fitness","noun","The condition of being physically healthy","health,wellness","B1"],
      ["foul","noun","An unfair or invalid action in a game","infringement,violation","B1"],
      ["goalkeeper","noun","A player whose role is to stop the ball entering the goal","keeper,goalie","B1"],
      ["gymnasium","noun","A room or building equipped for physical exercise","gym,fitness centre","B2"],
      ["league","noun","A group of sports teams that compete against each other","division,conference","B2"],
      ["marathon","noun","A long-distance running race of about 42 kilometres","endurance race,long run","B2"],
      ["medal","noun","A metal disc given as an award for achievement","prize,award","B2"],
      ["opponent","noun","A person competing against another","rival,adversary","B2"],
      ["penalty","noun","A punishment imposed for breaking a rule in sport","sanction,forfeit","B2"],
      ["referee","noun","An official who watches a game to enforce the rules","umpire,judge","C1"],
      ["score","noun","The number of points achieved in a game","result,tally","C1"],
      ["spectator","noun","A person who watches a show or game","viewer,onlooker","C1"],
      ["stadium","noun","An enclosed area for sports events with seating","arena,ground","C1"],
      ["substitute","noun","A player who replaces another during a game","replacement,reserve","C2"],
      ["tournament","noun","A series of contests between a number of competitors","championship,competition","A2"],
      ["trophy","noun","A cup or other decorative object awarded as a prize","cup,award","A2"],
      ["umpire","noun","An official who rules on plays in some sports","referee,judge","A2"],
      ["victory","noun","An act of defeating an opponent","win,triumph","A2"],
      ["workout","noun","A session of vigorous physical exercise","training,exercise session","B1"],
    ],
    food: [
      ["appetiser","noun","A small dish eaten before a main meal","starter,hors d oeuvre","A2"],
      ["bake","verb","To cook food by dry heat in an oven","roast,cook","A2"],
      ["beverage","noun","A drink other than water","drink,refreshment","A2"],
      ["bland","adj","Lacking strong flavour or character","tasteless,mild","A2"],
      ["boil","verb","To heat a liquid until it bubbles and turns to steam","simmer,cook","B1"],
      ["broth","noun","A thin soup made by boiling meat or vegetables","stock,bouillon","B1"],
      ["cuisine","noun","A style or method of cooking","cooking,gastronomy","B1"],
      ["delicacy","noun","A choice or expensive food","treat,luxury food","B1"],
      ["dessert","noun","A sweet course served at the end of a meal","pudding,sweet","B1"],
      ["dine","verb","To eat dinner, especially in a formal setting","eat,have dinner","B2"],
      ["flavour","noun","The distinctive taste of a food or drink","taste,savour","B2"],
      ["garnish","verb","To decorate food with a small amount of another food","decorate,embellish","B2"],
      ["grill","verb","To cook food on a metal frame over heat","barbecue,char-grill","B2"],
      ["ingredient","noun","A component part of a recipe","element,constituent","B2"],
      ["marinate","verb","To soak food in a sauce to add flavour","soak,steep","B2"],
      ["menu","noun","A list of dishes available in a restaurant","bill of fare,food list","C1"],
      ["nutrition","noun","The process of providing food necessary for health","nourishment,sustenance","C1"],
      ["organic","adj","Produced without artificial chemicals","natural,chemical-free","C1"],
      ["pastry","noun","A dough of flour, fat, and water used in baking","pie crust,baked goods","C1"],
      ["portion","noun","An amount of food served to one person","serving,helping","C2"],
      ["preservative","noun","A substance used to prevent food from decaying","additive,conserving agent","A2"],
      ["recipe","noun","A set of instructions for preparing a dish","formula,directions","A2"],
      ["roast","verb","To cook food by prolonged exposure to heat","bake,grill","A2"],
      ["seasoning","noun","Salt, herbs, or spices added to food for flavour","spice,condiment","A2"],
      ["simmer","verb","To cook gently just below boiling point","stew,cook slowly","B1"],
      ["spicy","adj","Flavoured with or containing strong spices","hot,peppery","B1"],
      ["utensil","noun","A tool or container used in a kitchen","implement,instrument","B1"],
      ["vegan","adj","Using no animal products at all","plant-based,cruelty-free","B1"],
      ["vegetarian","noun","A person who does not eat meat","non-meat eater,herbivore","B1"],
      ["waiter","noun","A person who serves food in a restaurant","server,attendant","B2"],
    ],
    housing: [
      ["apartment","noun","A set of rooms forming a residence","flat,unit","A2"],
      ["attic","noun","The space at the top of a house under the roof","loft,garret","A2"],
      ["balcony","noun","A platform projecting from the wall of a building","terrace,veranda","A2"],
      ["basement","noun","The floor of a building partly or entirely below ground","cellar,lower level","A2"],
      ["ceiling","noun","The upper interior surface of a room","overhead,roof interior","B1"],
      ["chimney","noun","A vertical channel for smoke from a fireplace","flue,smokestack","B1"],
      ["corridor","noun","A long passage in a building","hallway,passageway","B1"],
      ["curtain","noun","A piece of fabric hung to cover a window","drape,blind","B1"],
      ["detached","adj","Describing a house not joined to another","standalone,separate","B1"],
      ["doorbell","noun","A bell in a building that can be rung by visitors","buzzer,chime","B2"],
      ["elevator","noun","A platform for moving people between building floors","lift,escalator","B2"],
      ["fence","noun","A barrier enclosing an area of ground","railing,enclosure","B2"],
      ["fireplace","noun","A place for a domestic fire in a wall","hearth,grate","B2"],
      ["floor","noun","The lower surface of a room","ground,storey","B2"],
      ["furnish","verb","To provide a house with furniture and fittings","equip,fit out","B2"],
      ["garage","noun","A building for housing a motor vehicle","carport,car shelter","C1"],
      ["insulation","noun","Material used to prevent loss of heat","lagging,weatherproofing","C1"],
      ["landlord","noun","A person who rents out property","property owner,lessor","C1"],
      ["lease","noun","A contract by which one party rents property","rental agreement,tenancy","C1"],
      ["mortgage","noun","A loan for buying property","home loan,property loan","C2"],
      ["plumbing","noun","The system of pipes and fixtures for water","water system,piping","A2"],
      ["refurbish","verb","To renovate and redecorate a building","renovate,restore","A2"],
      ["rent","noun","A regular payment for the use of property","lease payment,rental","A2"],
      ["roof","noun","The structure forming the upper covering of a building","rooftop,covering","A2"],
      ["staircase","noun","A set of stairs and its surrounding structure","steps,stairway","B1"],
      ["suburb","noun","An outlying residential area of a city","outskirts,residential area","B1"],
      ["tenant","noun","A person who occupies rented property","renter,lessee","B1"],
      ["terrace","noun","A row of houses built in one block","row house,townhouse","B1"],
      ["ventilation","noun","The provision of fresh air to a room or building","air circulation,airing","B1"],
      ["warehouse","noun","A large building for storing goods","depot,storehouse","B2"],
    ],
    transport: [
      ["accelerate","verb","To increase in speed","speed up,go faster","A2"],
      ["bicycle","noun","A vehicle with two wheels powered by pedalling","bike,cycle","A2"],
      ["carriage","noun","A separate section of a passenger train","coach,wagon","A2"],
      ["collision","noun","An instance of one moving object hitting another","crash,accident","A2"],
      ["congestion","noun","Overcrowding of vehicles causing slow traffic","traffic jam,gridlock","B1"],
      ["crossroads","noun","A point where two or more roads meet","intersection,junction","B1"],
      ["cyclist","noun","A person who rides a bicycle","biker,rider","B1"],
      ["diesel","noun","A type of fuel used in some engines","fuel,gas oil","B1"],
      ["engine","noun","A machine that converts energy into motion","motor,powerplant","B1"],
      ["expressway","noun","A highway designed for fast traffic","motorway,freeway","B2"],
      ["freight","noun","Goods transported in bulk by vehicle","cargo,shipment","B2"],
      ["helmet","noun","A hard protective hat","headgear,hard hat","B2"],
      ["highway","noun","A main road for fast long-distance travel","motorway,expressway","B2"],
      ["intersection","noun","A point where two roads cross each other","crossroads,junction","B2"],
      ["lane","noun","A division of a road for a single line of traffic","track,strip","B2"],
      ["locomotive","noun","A powered railway vehicle for pulling trains","engine,train engine","C1"],
      ["motorist","noun","The driver of a car","driver,car operator","C1"],
      ["overtake","verb","To pass while travelling in the same direction","pass,go past","C1"],
      ["pavement","noun","A raised paved area for pedestrians beside a road","sidewalk,footpath","C1"],
      ["pedestrian","noun","A person walking along a road","walker,foot traveller","C2"],
      ["petrol","noun","A liquid fuel used in vehicles","gasoline,fuel","A2"],
      ["registration","noun","The action of registering a vehicle officially","licensing,enrolment","A2"],
      ["roundabout","noun","A road junction where traffic moves in one direction around a central island","rotary,traffic circle","A2"],
      ["seatbelt","noun","A belt used to secure a person in a vehicle","safety belt,harness","A2"],
      ["speed limit","noun","The maximum speed at which a vehicle may legally travel","maximum speed,speed restriction","B1"],
      ["toll","noun","A charge payable for permission to use a road or bridge","fee,charge","B1"],
      ["traffic","noun","Vehicles moving on a public road","road traffic,vehicles","B1"],
      ["tram","noun","A passenger vehicle powered by electricity on rails","streetcar,trolley","B1"],
      ["vehicle","noun","A thing used for transporting people or goods","car,transport","B1"],
    ],
    employment: [
      ["applicant","noun","A person who applies for a job","candidate,job seeker","A2"],
      ["appraisal","noun","An assessment of the value of an employee s work","evaluation,review","A2"],
      ["apprentice","noun","A person learning a trade from a skilled employer","trainee,learner","A2"],
      ["benefits","noun","Advantages provided in addition to salary","perks,extras","A2"],
      ["career","noun","An occupation undertaken for a significant period","profession,vocation","B1"],
      ["colleague","noun","A person one works with","co-worker,associate","B1"],
      ["commute","noun","A regular journey between home and workplace","daily travel,journey to work","B1"],
      ["dismiss","verb","To order someone to leave a job","fire,sack","B1"],
      ["freelance","adj","Working for different companies at different times","independent,self-employed","B1"],
      ["interview","noun","A formal meeting to assess a job applicant","job interview,screening","B2"],
      ["maternity leave","noun","Time off work granted to a mother before and after childbirth","parental leave,pregnancy leave","B2"],
      ["minimum wage","noun","The lowest wage permitted by law","base pay,lowest pay","B2"],
      ["occupation","noun","A person s regular work or profession","job,profession","B2"],
      ["overtime","noun","Time worked beyond normal working hours","extra hours,additional work","B2"],
      ["part-time","adj","Employed for fewer hours than normal","half-time,casual","B2"],
      ["payslip","noun","A document showing an employee s pay and deductions","wage slip,pay statement","C1"],
      ["promotion","noun","Advancement to a higher position at work","advancement,upgrade","C1"],
      ["qualification","noun","A quality or skill that makes someone suitable","credential,certification","C1"],
      ["recruit","verb","To find and employ new staff","hire,employ","C1"],
      ["redundant","adj","No longer needed at work","laid off,surplus","C2"],
      ["resign","verb","To voluntarily leave a job","quit,step down","A2"],
      ["resume","noun","A summary of a person s qualifications and experience","CV,curriculum vitae","A2"],
      ["shift","noun","A scheduled period of work","work period,turn","A2"],
      ["skill","noun","The ability to do something well","expertise,ability","A2"],
      ["strike","noun","A refusal to work as a form of protest","walkout,industrial action","B1"],
      ["supervise","verb","To observe and direct the work of others","oversee,manage","B1"],
      ["trainee","noun","A person undergoing training for a job","apprentice,intern","B1"],
      ["unemployed","adj","Without a paid job but available to work","jobless,out of work","B1"],
      ["vacancy","noun","An unoccupied position or job","opening,available post","B1"],
      ["workload","noun","The amount of work to be done by a person","tasks,assignments","B2"],
    ],
    family: [
      ["adolescence","noun","The period following puberty during which a young person develops","teenage years,youth","A2"],
      ["ancestor","noun","A person from whom one is descended","forebear,forefather","A2"],
      ["bond","noun","A strong connection between people","tie,link","A2"],
      ["bride","noun","A woman on her wedding day","wife-to-be,newlywed","A2"],
      ["childhood","noun","The state or period of being a child","youth,early years","B1"],
      ["custody","noun","The protective care of someone, especially a child","guardianship,care","B1"],
      ["descendant","noun","A person descended from a particular ancestor","offspring,heir","B1"],
      ["divorce","noun","The legal ending of a marriage","separation,dissolution","B1"],
      ["engagement","noun","A formal agreement to get married","betrothal,promise","B1"],
      ["extended family","noun","A family group including relatives beyond parents and children","wider family,relatives","B2"],
      ["foster","verb","To bring up a child that is not one s own by birth","raise,care for","B2"],
      ["groom","noun","A man on his wedding day","husband-to-be,bridegroom","B2"],
      ["guardian","noun","A person who looks after the interests of a child","protector,carer","B2"],
      ["heir","noun","A person who inherits property or a title","inheritor,successor","B2"],
      ["household","noun","A house and its occupants","family,home","B2"],
      ["inherit","verb","To receive property or a title from a predecessor","come into,be left","C1"],
      ["marriage","noun","The legally recognised union of two people","wedding,matrimony","C1"],
      ["maternity","noun","The period during and after pregnancy","motherhood,pregnancy","C1"],
      ["nephew","noun","A son of one s brother or sister","male relative,kin","C1"],
      ["niece","noun","A daughter of one s brother or sister","female relative,kin","C2"],
      ["nuclear family","noun","A family consisting of parents and their children","immediate family,core family","A2"],
      ["orphan","noun","A child whose parents are dead","parentless child,ward","A2"],
      ["parenting","noun","The activity of bringing up a child","child-rearing,upbringing","A2"],
      ["reunion","noun","A gathering of people who have been apart","get-together,homecoming","A2"],
      ["sibling","noun","A brother or sister","brother or sister,kin","B1"],
      ["single parent","noun","A person bringing up a child alone","lone parent,solo parent","B1"],
      ["spouse","noun","A husband or wife","partner,life companion","B1"],
      ["stepfather","noun","A man married to one s mother but not one s biological father","step-parent,mother s husband","B1"],
      ["toddler","noun","A young child who has just learned to walk","infant,small child","B1"],
      ["upbringing","noun","The way a child is raised and cared for","childhood,rearing","B2"],
      ["wedding","noun","A marriage ceremony","nuptials,marriage ceremony","B2"],
    ],
    arts: [
      ["abstract","adj","Relating to art that does not represent reality","non-representational,conceptual","A2"],
      ["canvas","noun","A piece of cloth used for painting on","painting surface,board","A2"],
      ["choreography","noun","The sequence of steps in a dance composition","dance arrangement,dance design","A2"],
      ["compose","verb","To write or create a piece of music or art","create,write","A2"],
      ["concert","noun","A musical performance given in public","recital,show","B1"],
      ["costume","noun","A set of clothes worn by an actor or performer","outfit,attire","B1"],
      ["craft","noun","An activity involving skill in making things by hand","handicraft,art","B1"],
      ["creativity","noun","The use of imagination to create something new","inventiveness,originality","B1"],
      ["director","noun","A person who supervises the making of a film or play","filmmaker,producer","B1"],
      ["drama","noun","A play for theatre, radio, or television","play,theatrical work","B2"],
      ["exhibit","verb","To publicly display a work of art","display,show","B2"],
      ["gallery","noun","A room or building for displaying art","museum,exhibition space","B2"],
      ["harmony","noun","The combination of musical notes to form chords","consonance,accord","B2"],
      ["illustration","noun","A picture illustrating a book or explanation","drawing,image","B2"],
      ["lyrics","noun","The words of a song","words,text","B2"],
      ["masterpiece","noun","An outstanding work of art","magnum opus,great work","C1"],
      ["melody","noun","A sequence of musical notes forming a tune","tune,air","C1"],
      ["mural","noun","A large painting applied directly to a wall","wall painting,fresco","C1"],
      ["orchestra","noun","A large group of musicians playing together","ensemble,symphony orchestra","C1"],
      ["performance","noun","An act of presenting a play or piece of music","show,concert","C2"],
      ["portrait","noun","A painting or photograph of a person","likeness,image","A2"],
      ["pottery","noun","Objects made from baked clay","ceramics,earthenware","A2"],
      ["rehearsal","noun","A practice session for a performance","practice,run-through","A2"],
      ["rhythm","noun","A strong regular repeated pattern of sound","beat,tempo","A2"],
      ["sculpture","noun","A three-dimensional work of art","statue,carving","B1"],
      ["sketch","noun","A rough drawing representing the chief features","drawing,outline","B1"],
      ["symphony","noun","An elaborate musical composition for orchestra","orchestral work,opus","B1"],
      ["theater","noun","A building where plays are performed","playhouse,auditorium","B1"],
      ["venue","noun","The place where an event is held","location,site","B1"],
    ],
    psychology: [
      ["anxiety","noun","A feeling of worry and unease","nervousness,apprehension","A2"],
      ["attachment","noun","A strong emotional bond with another person","bond,connection","A2"],
      ["attitude","noun","A settled way of thinking or feeling about something","outlook,perspective","A2"],
      ["behaviour","noun","The way in which a person acts or conducts themselves","conduct,actions","A2"],
      ["cognitive","adj","Relating to the mental process of acquiring knowledge","mental,intellectual","B1"],
      ["confidence","noun","A feeling of self-assurance","self-assurance,self-belief","B1"],
      ["conscious","adj","Aware of and responding to one s surroundings","aware,alert","B1"],
      ["counselling","noun","Professional guidance on personal problems","therapy,advice","B1"],
      ["depression","noun","A mental condition marked by feelings of sadness","low mood,melancholy","B1"],
      ["emotion","noun","A strong feeling such as joy, anger, or sadness","feeling,sentiment","B2"],
      ["habit","noun","A regular tendency or practice","routine,custom","B2"],
      ["instinct","noun","An innate pattern of behaviour in response to stimuli","intuition,impulse","B2"],
      ["introvert","noun","A shy person who prefers solitary activities","loner,reserved person","B2"],
      ["memory","noun","The faculty by which the mind stores information","recall,recollection","B2"],
      ["mood","noun","A temporary state of mind or feeling","temperament,frame of mind","B2"],
      ["motivation","noun","The reason for acting in a particular way","drive,incentive","C1"],
      ["perception","noun","The ability to see, hear, or become aware of something","awareness,understanding","C1"],
      ["personality","noun","The combination of characteristics forming an individual","character,temperament","C1"],
      ["phobia","noun","An extreme irrational fear of something","fear,terror","C1"],
      ["self-esteem","noun","Confidence in one s own worth or abilities","self-respect,self-worth","C2"],
      ["stimulus","noun","A thing that evokes a specific reaction","trigger,prompt","A2"],
      ["subconscious","adj","Concerning the part of the mind not fully aware","unconscious,subliminal","A2"],
      ["temperament","noun","A person s nature affecting their behaviour","disposition,character","A2"],
      ["trauma","noun","A deeply distressing experience","shock,ordeal","A2"],
    ],
    language: [
      ["accent","noun","A distinctive way of pronouncing a language","pronunciation,intonation","A2"],
      ["alphabet","noun","A set of letters used in writing a language","script,letters","A2"],
      ["bilingual","adj","Able to speak two languages fluently","dual-language,multilingual","A2"],
      ["colloquial","adj","Used in ordinary conversation","informal,casual","A2"],
      ["consonant","noun","A speech sound that is not a vowel","non-vowel,letter","B1"],
      ["dialect","noun","A form of language spoken in a particular area","regional language,vernacular","B1"],
      ["dictionary","noun","A book listing words and their meanings","lexicon,wordbook","B1"],
      ["fluency","noun","The ability to speak a language easily and well","proficiency,command","B1"],
      ["grammar","noun","The rules governing the structure of a language","syntax,language rules","B1"],
      ["idiom","noun","A phrase whose meaning is different from its literal words","expression,saying","B2"],
      ["jargon","noun","Specialised terminology used by a profession","terminology,technical language","B2"],
      ["linguistics","noun","The scientific study of language","language study,philology","B2"],
      ["literal","adj","Taking words in their usual meaning without metaphor","exact,word-for-word","B2"],
      ["metaphor","noun","A figure of speech comparing unlike things","analogy,comparison","B2"],
      ["monolingual","adj","Speaking or using only one language","single-language,unilingual","B2"],
      ["noun","noun","A word that represents a person, place, or thing","name word,substantive","C1"],
      ["phrase","noun","A small group of words forming a unit","expression,clause","C1"],
      ["plural","adj","Denoting more than one","multiple,several","C1"],
      ["prefix","noun","A word element placed before a root word","beginning,affix","C1"],
      ["proverb","noun","A short well-known saying stating a general truth","adage,maxim","C2"],
      ["punctuation","noun","The marks used in writing to separate sentences","marks,notation","A2"],
      ["synonym","noun","A word having the same meaning as another","equivalent,alternative","A2"],
      ["syntax","noun","The arrangement of words to create sentences","grammar,sentence structure","A2"],
      ["vocabulary","noun","All the words known and used by a person","lexicon,word stock","A2"],
      ["vowel","noun","A speech sound made without closing the mouth","open sound,letter","B1"],
    ],
    globalization: [
      ["border","noun","The edge or boundary of a country","boundary,frontier","A2"],
      ["colonialism","noun","The practice of acquiring control over another country","imperialism,expansionism","A2"],
      ["cosmopolitan","adj","Familiar with and at ease in many countries","worldly,international","A2"],
      ["diplomacy","noun","The management of international relations","foreign affairs,negotiation","A2"],
      ["diversity","noun","The inclusion of different types of people","variety,multiculturalism","B1"],
      ["emigrate","verb","To leave one s own country to settle in another","relocate,move abroad","B1"],
      ["exploitation","noun","The use of something in an unfair way for profit","misuse,abuse","B1"],
      ["export","noun","A product sold to another country","foreign sale,shipped goods","B1"],
      ["humanitarian","adj","Concerned with human welfare","charitable,philanthropic","B1"],
      ["immigrate","verb","To come to live permanently in a foreign country","settle,relocate","B2"],
      ["inequality","noun","Unfair difference in opportunity or resources","disparity,imbalance","B2"],
      ["integrate","verb","To combine or bring together into a whole","merge,unify","B2"],
      ["international","adj","Existing between or involving different countries","global,worldwide","B2"],
      ["migration","noun","The movement of people to a new area or country","relocation,movement","B2"],
      ["multinational","adj","Operating in several countries","international,global","B2"],
      ["outsource","verb","To obtain goods or services from an outside supplier","contract out,delegate","C1"],
      ["pandemic","noun","A disease prevalent over a whole country or the world","epidemic,outbreak","C1"],
      ["refugee","noun","A person forced to leave their country","displaced person,asylum seeker","C1"],
      ["sanction","noun","A penalty imposed on a country by others","restriction,embargo","C1"],
      ["sovereignty","noun","Supreme power or authority of a state","independence,autonomy","C2"],
      ["tariff","noun","A tax on imported goods","duty,customs fee","A2"],
      ["terrorism","noun","The use of violence for political purposes","extremism,militancy","A2"],
      ["trade agreement","noun","A pact between countries about trade terms","commercial treaty,trade pact","A2"],
      ["visa","noun","An endorsement on a passport permitting entry","travel permit,entry authorisation","A2"],
    ],
  },
  collocations: {
    travel: [
      ["board a plane","To get onto an aircraft","get on a flight,embark on a plane","A2"],
      ["book a flight","To reserve a seat on an aircraft","reserve a ticket,arrange air travel","A2"],
      ["cancel a reservation","To withdraw a booking","void a booking,revoke a reservation","A2"],
      ["catch a train","To get onto a departing train in time","board a train,take a train","A2"],
      ["check in at the hotel","To register at a hotel on arrival","arrive at hotel,sign in at hotel","B1"],
      ["clear customs","To pass through the border control process","go through customs,pass immigration","B1"],
      ["declare goods","To state items being brought into a country","report items,list goods at customs","B1"],
      ["explore a city","To travel around a city to learn about it","tour a city,discover a place","B1"],
      ["go abroad","To travel to a foreign country","travel overseas,visit another country","B1"],
      ["go on holiday","To take a vacation trip","take a trip,go on vacation","B2"],
      ["hail a taxi","To signal for a taxi to stop","flag down a cab,call a taxi","B2"],
      ["miss a flight","To arrive too late to board an aircraft","lose a flight,fail to catch a plane","B2"],
      ["pack a suitcase","To fill a bag with things for a trip","prepare luggage,fill a bag","B2"],
      ["plan a trip","To organise the details of a journey","arrange a holiday,organise a tour","B2"],
      ["set off on a journey","To begin travelling","start a trip,depart on a journey","B2"],
      ["travel light","To take very little luggage when travelling","pack minimally,bring few bags","C1"],
    ],
    government: [
      ["call an election","To announce that a vote will take place","schedule an election,declare a vote","A2"],
      ["cast a vote","To formally submit a choice in an election","place a ballot,make a selection","A2"],
      ["change the law","To alter legislation","amend the law,revise legislation","A2"],
      ["debate an issue","To discuss a topic formally in parliament","argue a point,discuss a matter","A2"],
      ["enforce the law","To ensure that people obey legal rules","uphold the law,apply regulations","B1"],
      ["form a government","To establish an administration after an election","create a cabinet,build an administration","B1"],
      ["hold a referendum","To conduct a public vote on a specific issue","call a public vote,organise a plebiscite","B1"],
      ["impose sanctions","To apply penalties against a country","levy restrictions,enact sanctions","B1"],
      ["pass a law","To approve legislation through parliament","enact legislation,adopt a law","B1"],
      ["raise taxes","To increase the level of taxation","hike taxes,increase tax rates","B2"],
      ["run for office","To be a candidate in an election","stand for election,seek a position","B2"],
      ["sign a treaty","To formally agree to an international pact","ratify an agreement,endorse a treaty","B2"],
    ],
    crime: [
      ["commit a crime","To carry out an illegal act","break the law,perpetrate an offence","A2"],
      ["conduct an investigation","To carry out a formal inquiry into a crime","run an investigation,lead an inquiry","A2"],
      ["face charges","To be formally accused of a crime","be charged,stand accused","A2"],
      ["file a report","To submit a formal account of a crime","lodge a complaint,report an incident","A2"],
      ["give evidence","To provide testimony in a legal proceeding","testify,present proof","B1"],
      ["impose a fine","To order the payment of a monetary penalty","levy a penalty,issue a fine","B1"],
      ["plead guilty","To admit to committing a crime in court","confess,admit guilt","B1"],
      ["prevent crime","To stop illegal activities from occurring","deter crime,reduce offending","B1"],
      ["release on bail","To free an accused person pending trial","grant bail,let out on bond","B1"],
      ["report a theft","To inform the police about stolen property","notify police,file a theft report","B2"],
      ["serve a sentence","To spend time in prison as punishment","do time,be imprisoned","B2"],
      ["solve a case","To find the answer to a criminal investigation","crack a case,resolve a mystery","B2"],
    ],
    media: [
      ["break a story","To be the first to report news","scoop a story,publish first","A2"],
      ["broadcast live","To transmit a programme as it happens","go live,air in real time","A2"],
      ["check the news","To look at current events reports","read the news,watch the headlines","A2"],
      ["cover a story","To report on a news event","report an event,write about a story","A2"],
      ["go viral","To spread rapidly on the internet","become popular,trend online","B1"],
      ["make headlines","To be reported as important news","be front-page news,attract attention","B1"],
      ["post online","To publish content on the internet","share online,upload content","B1"],
      ["publish an article","To make a written piece publicly available","print a story,release an article","B1"],
      ["read the newspaper","To look at a printed news publication","peruse the paper,check the press","B1"],
      ["spread misinformation","To share false or inaccurate information","share fake news,disseminate lies","B2"],
      ["subscribe to a channel","To pay for regular access to media content","follow a channel,join a service","B2"],
      ["watch a documentary","To view a factual film","see a documentary,view a programme","B2"],
    ],
    communication: [
      ["break the ice","To make people feel more comfortable in a social situation","start a conversation,ease tension","A2"],
      ["come to an agreement","To reach a mutual decision","reach consensus,find common ground","A2"],
      ["deliver a speech","To give a formal talk to an audience","make a speech,address an audience","A2"],
      ["drop a hint","To suggest something indirectly","give a clue,imply something","A2"],
      ["express an opinion","To state what one thinks about something","share a view,voice a thought","B1"],
      ["get the message across","To communicate an idea successfully","convey the point,make oneself understood","B1"],
      ["give a presentation","To speak formally to a group using visual aids","present information,do a talk","B1"],
      ["have a conversation","To engage in spoken exchange with someone","chat,talk with someone","B1"],
      ["keep in touch","To maintain contact with someone","stay connected,remain in contact","B1"],
      ["make a phone call","To use a telephone to speak to someone","ring someone,call someone","B2"],
      ["raise a concern","To bring a worry to someone s attention","express worry,flag an issue","B2"],
      ["send a message","To transmit information to someone","text someone,write a note","B2"],
    ],
    sports: [
      ["beat a record","To surpass a previous best achievement","break a record,set a new record","A2"],
      ["blow the whistle","To signal the start or end of play","call time,signal a foul","A2"],
      ["compete in a tournament","To take part in a series of contests","enter a competition,play in a championship","A2"],
      ["keep fit","To maintain good physical condition","stay healthy,exercise regularly","A2"],
      ["lose a match","To be defeated in a game","suffer a defeat,be beaten","B1"],
      ["play a match","To participate in a competitive game","compete in a game,take part in a contest","B1"],
      ["score a goal","To put the ball into the net in football","net a goal,find the back of the net","B1"],
      ["set a record","To achieve the best ever result","establish a record,make history","B1"],
      ["take up a sport","To begin participating in a sport","start a sport,begin playing","B1"],
      ["train for a competition","To prepare physically for a contest","practise,get ready for an event","B2"],
      ["warm up","To prepare the body for exercise","stretch,do warm-up exercises","B2"],
      ["win a medal","To earn a prize in a competition","claim a medal,take a medal","B2"],
    ],
    food: [
      ["eat out","To have a meal in a restaurant","dine out,go to a restaurant","A2"],
      ["follow a diet","To eat according to a specific plan","be on a diet,stick to a meal plan","A2"],
      ["gain weight","To become heavier","put on weight,increase body mass","A2"],
      ["grab a bite","To eat something quickly","have a snack,eat quickly","A2"],
      ["have a balanced diet","To eat the right proportions of food groups","eat healthily,maintain good nutrition","B1"],
      ["lose your appetite","To stop feeling hungry","not feel like eating,have no hunger","B1"],
      ["make a reservation","To book a table at a restaurant","book a table,reserve a spot","B1"],
      ["order a meal","To request food in a restaurant","choose dishes,select from the menu","B1"],
      ["peel vegetables","To remove the skin from vegetables","prepare veg,skin vegetables","B1"],
      ["set the table","To arrange plates and cutlery for a meal","lay the table,prepare the table","B2"],
      ["skip a meal","To not eat at a usual mealtime","miss a meal,go without food","B2"],
      ["try local food","To eat dishes typical of a particular place","sample local cuisine,taste regional dishes","B2"],
    ],
    housing: [
      ["buy a property","To purchase a house or flat","acquire a home,invest in real estate","A2"],
      ["decorate a room","To add paint, wallpaper, or furnishings","do up a room,style a space","A2"],
      ["do the housework","To perform cleaning and tidying tasks at home","clean the house,tidy up","A2"],
      ["move house","To change one s place of residence","relocate,change address","A2"],
      ["pay rent","To give money to a landlord for property use","cover the rent,make a rental payment","B1"],
      ["put up shelves","To install flat boards on a wall for storage","mount shelves,fit shelving","B1"],
      ["renovate a building","To restore a structure to good condition","refurbish,do up a property","B1"],
      ["share a flat","To live in a rented property with others","have flatmates,co-rent","B1"],
      ["sign a lease","To formally agree to a rental contract","enter a tenancy,execute a lease","B1"],
      ["take out a mortgage","To borrow money to buy property","get a home loan,secure financing","B2"],
      ["turn off the lights","To switch off electrical lighting","switch off lights,put out the lights","B2"],
      ["wash the dishes","To clean plates and utensils after a meal","do the washing up,clean the crockery","B2"],
    ],
    transport: [
      ["buckle up","To fasten a seatbelt","fasten your belt,put on a seatbelt","A2"],
      ["change lanes","To move from one lane of traffic to another","switch lanes,move over","A2"],
      ["get a flat tyre","To have a tyre lose its air pressure","have a puncture,blow a tyre","A2"],
      ["get off at a stop","To leave a bus or train at a station","alight,exit at a stop","A2"],
      ["get stuck in traffic","To be unable to move due to congestion","be held up,sit in a jam","B1"],
      ["give way","To allow other traffic to go first","yield,let others pass","B1"],
      ["miss the bus","To arrive too late to catch a bus","be late for the bus,fail to catch the bus","B1"],
      ["obey traffic rules","To follow the laws governing road use","follow traffic regulations,respect road rules","B1"],
      ["park the car","To stop and leave a vehicle in a place","pull over,find a parking spot","B1"],
      ["pull over","To move to the side of the road and stop","stop the car,draw up","B2"],
      ["take public transport","To use buses, trains, or other shared services","use public transit,ride the bus","B2"],
      ["wait for the bus","To stand at a stop until the bus arrives","queue for the bus,expect the bus","B2"],
    ],
    employment: [
      ["apply for a position","To formally request a job","submit an application,seek employment","A2"],
      ["be made redundant","To lose a job because it is no longer needed","be laid off,lose a position","A2"],
      ["do a shift","To work a scheduled period","work a shift,put in hours","A2"],
      ["earn a salary","To receive regular payment for work","get paid,draw a wage","A2"],
      ["get a promotion","To advance to a higher position at work","move up,be promoted","B1"],
      ["get fired","To be dismissed from a job","lose a job,be sacked","B1"],
      ["go on strike","To refuse to work as a protest","walk out,take industrial action","B1"],
      ["hand in notice","To formally tell an employer you are leaving","give notice,resign","B1"],
      ["meet a deadline","To complete a task by the required time","finish on time,deliver punctually","B1"],
      ["take a day off","To not go to work for a day","have a day off,be absent from work","B2"],
      ["work from home","To do one s job at home rather than the office","telecommute,remote work","B2"],
      ["work overtime","To work beyond normal hours","do extra hours,put in overtime","B2"],
    ],
    family: [
      ["bring up a child","To raise and care for a child","raise a child,rear a child","A2"],
      ["celebrate an anniversary","To mark the date of a special event","observe an anniversary,commemorate a date","A2"],
      ["get along with","To have a good relationship with someone","be on good terms,get on with","A2"],
      ["get divorced","To legally end a marriage","split up,separate","A2"],
      ["get engaged","To agree to marry someone","become betrothed,propose marriage","B1"],
      ["get married","To enter into a legal marriage","tie the knot,wed","B1"],
      ["have a baby","To give birth to a child","become a parent,start a family","B1"],
      ["look after someone","To take care of a person","care for someone,tend to someone","B1"],
      ["name after someone","To give a child the same name as another person","call after,name in honour of","B1"],
      ["run in the family","To be a common characteristic among relatives","be hereditary,be a family trait","B2"],
      ["settle down","To establish a permanent home and lifestyle","put down roots,make a home","B2"],
      ["take after someone","To resemble a parent in appearance or character","look like,be similar to","B2"],
    ],
    arts: [
      ["attend a concert","To go to a live music performance","go to a gig,see a show","A2"],
      ["compose music","To write a musical piece","create music,write a song","A2"],
      ["curate an exhibition","To organise and present a display of art","put on a show,arrange an exhibit","A2"],
      ["direct a film","To supervise the making of a movie","make a film,produce a movie","A2"],
      ["draw a sketch","To make a quick rough drawing","do a drawing,make a sketch","B1"],
      ["perform on stage","To act or play music in front of an audience","appear on stage,give a performance","B1"],
      ["play an instrument","To produce music using a musical device","make music,perform on an instrument","B1"],
      ["put on a play","To produce and present a theatrical performance","stage a play,perform a drama","B1"],
      ["take photographs","To capture images with a camera","shoot photos,snap pictures","B1"],
      ["visit a gallery","To go to a place where art is displayed","go to a museum,see an exhibition","B2"],
      ["win an award","To receive a prize for achievement","earn a prize,receive recognition","B2"],
      ["write a novel","To compose a book-length work of fiction","author a book,pen a story","B2"],
    ],
    psychology: [
      ["build confidence","To develop greater self-assurance","boost self-esteem,grow in confidence","A2"],
      ["cope with stress","To deal with pressure effectively","manage stress,handle pressure","A2"],
      ["develop a habit","To form a regular practice over time","form a routine,establish a pattern","A2"],
      ["express emotions","To show or communicate feelings","share feelings,convey emotions","A2"],
      ["face a fear","To confront something that frightens you","overcome anxiety,tackle a phobia","B1"],
      ["form an opinion","To develop a view or judgement about something","make up your mind,reach a conclusion","B1"],
      ["lose concentration","To stop paying attention","get distracted,lose focus","B1"],
      ["make a decision","To reach a conclusion after consideration","decide,come to a choice","B1"],
      ["overcome a challenge","To successfully deal with a difficulty","surmount an obstacle,conquer a problem","B1"],
      ["raise self-esteem","To improve confidence in one s own worth","boost self-worth,increase confidence","B2"],
      ["seek professional help","To consult a qualified expert for guidance","see a therapist,get counselling","B2"],
      ["suffer from depression","To be affected by persistent sadness","experience depression,battle low mood","B2"],
    ],
    language: [
      ["coin a term","To invent a new word or phrase","create a word,introduce an expression","A2"],
      ["expand your vocabulary","To learn more words","build your lexicon,grow your word knowledge","A2"],
      ["have an accent","To speak with a distinctive pronunciation","speak with an accent,have a regional voice","A2"],
      ["learn a language","To acquire the ability to speak a new tongue","study a language,pick up a language","A2"],
      ["look up a word","To search for the meaning of a word","check the dictionary,find a definition","B1"],
      ["make a grammatical error","To use incorrect grammar","have a grammar mistake,use wrong syntax","B1"],
      ["master a language","To become highly proficient in a language","achieve fluency,become an expert speaker","B1"],
      ["pick up a language","To learn a language informally","acquire a language,learn naturally","B1"],
      ["practise pronunciation","To work on saying words correctly","drill sounds,rehearse speaking","B1"],
      ["speak fluently","To talk in a language easily and smoothly","be proficient,converse naturally","B2"],
      ["take a language course","To enrol in classes to learn a language","do a language class,study a language formally","B2"],
      ["translate a document","To convert written text into another language","render in another language,interpret a text","B2"],
    ],
    globalization: [
      ["break down barriers","To remove obstacles between groups","remove obstacles,eliminate divisions","A2"],
      ["bridge cultural gaps","To reduce differences between cultures","connect cultures,unite peoples","A2"],
      ["combat inequality","To fight against unfair differences","address disparity,tackle unfairness","A2"],
      ["embrace diversity","To accept and welcome differences","celebrate variety,welcome multiculturalism","A2"],
      ["expand overseas","To grow a business into foreign countries","go international,enter new markets","B1"],
      ["face competition","To deal with rivals in business","compete globally,handle rivalry","B1"],
      ["maintain sovereignty","To preserve a nation s independence","protect autonomy,uphold independence","B1"],
      ["open borders","To allow free movement across frontiers","liberalise immigration,permit free travel","B1"],
      ["outsource production","To move manufacturing to another country","offshore manufacturing,contract abroad","B1"],
      ["promote free trade","To encourage commerce without restrictions","support open markets,advocate trade liberalisation","B2"],
      ["protect local industries","To safeguard domestic businesses","support national companies,shield local firms","B2"],
      ["spread awareness","To increase knowledge about global issues","raise consciousness,inform people","B2"],
    ],
  },
};
