// Auto-generated vocab boost group 43
module.exports = {
  vocab: {
    environment: [
      ['mitigater','n','One who mitigates','reduce person','C1'],
      ['mitigator','n','One who mitigates','reduce agent','C1'],
      ['mitigatee','n','One who is mitigated','reduce recipient','C2'],
      ['mitigatable','adj','Capable of being mitigated','reduce,possible','C2'],
      ['mitigatible','adj','Able to be mitigated','reduce,feasible','C2'],
      ['mitigative','adj','Tending to mitigate','reduce,active','C1'],
      ['mitigating','adj','Currently mitigating','reduce,ongoing','C1'],
      ['mitigated','adj','Having been mitigated','reduce,completed','C1'],
      ['remitigate','v','To mitigate again','reduce again,repeat','C1'],
      ['unmitigate','v','To reverse mitigating','reverse,undo','C2'],
      ['overmitigate','v','To mitigate excessively','excess,too much','C2'],
      ['undermitigate','v','To mitigate insufficiently','insufficient,inadequate','C2'],
      ['mismitigate','v','To mitigate incorrectly','wrongly,incorrectly','C2'],
      ['premitigate','v','To mitigate beforehand','before,in advance','C2'],
      ['comitigate','v','To mitigate together','jointly,together','C2'],
      ['remitigatation','n','The act of mitigating again','re-reduce','C2'],
      ['overmitigatation','n','Excessive mitigating','excess reduce','C2'],
      ['sequesteration','n','The act of sequestering','capture process','C1'],
      ['sequesterment','n','The result of sequestering','capture outcome','C1'],
      ['sequesterance','n','The state of sequestering','capture state','C1'],
      ['sequesterence','n','The quality of sequestering','capture quality','C1'],
      ['sequesteral','n','An act of sequestering','capture event','C2'],
      ['sequesterer','n','One who sequesters','capture person','C1'],
      ['sequesteror','n','One who sequesters','capture agent','C1'],
      ['sequesteree','n','One who is sequesterd','capture recipient','C2'],
      ['sequesterable','adj','Capable of being sequesterd','capture,possible','C2'],
      ['sequesterible','adj','Able to be sequesterd','capture,feasible','C2'],
      ['sequesterive','adj','Tending to sequester','capture,active','C1'],
      ['sequestering','adj','Currently sequestering','capture,ongoing','C1'],
      ['sequestered','adj','Having been sequesterd','capture,completed','C1'],
      ['resequester','v','To sequester again','capture again,repeat','C1'],
      ['unsequester','v','To reverse sequestering','reverse,undo','C2'],
      ['oversequester','v','To sequester excessively','excess,too much','C2'],
      ['undersequester','v','To sequester insufficiently','insufficient,inadequate','C2'],
      ['missequester','v','To sequester incorrectly','wrongly,incorrectly','C2'],
      ['presequester','v','To sequester beforehand','before,in advance','C2'],
      ['cosequester','v','To sequester together','jointly,together','C2'],
      ['resequesteration','n','The act of sequestering again','re-capture','C2'],
      ['oversequesteration','n','Excessive sequestering','excess capture','C2'],
      ['remediatation','n','The act of remediating','restore process','C1'],
      ['remediatment','n','The result of remediating','restore outcome','C1'],
      ['remediatance','n','The state of remediating','restore state','C1'],
      ['remediatence','n','The quality of remediating','restore quality','C1'],
      ['remediatal','n','An act of remediating','restore event','C2'],
      ['remediater','n','One who remediates','restore person','C1'],
      ['remediator','n','One who remediates','restore agent','C1'],
      ['remediatee','n','One who is remediated','restore recipient','C2'],
      ['remediatable','adj','Capable of being remediated','restore,possible','C2'],
      ['remediatible','adj','Able to be remediated','restore,feasible','C2'],
      ['remediative','adj','Tending to remediate','restore,active','C1'],
      ['remediating','adj','Currently remediating','restore,ongoing','C1'],
      ['remediated','adj','Having been remediated','restore,completed','C1'],
      ['reremediate','v','To remediate again','restore again,repeat','C1'],
      ['unremediate','v','To reverse remediating','reverse,undo','C2'],
      ['overremediate','v','To remediate excessively','excess,too much','C2'],
      ['underremediate','v','To remediate insufficiently','insufficient,inadequate','C2'],
      ['misremediate','v','To remediate incorrectly','wrongly,incorrectly','C2'],
      ['preremediate','v','To remediate beforehand','before,in advance','C2'],
      ['coremediate','v','To remediate together','jointly,together','C2'],
      ['reremediatation','n','The act of remediating again','re-restore','C2'],
      ['overremediatation','n','Excessive remediating','excess restore','C2'],
      ['desalinate','v','To remove salt from seawater','purify,distil,treat','C1'],
      ['desalinatation','n','The act of desalinating','purify process','C1'],
      ['desalinatment','n','The result of desalinating','purify outcome','C1'],
      ['desalinatance','n','The state of desalinating','purify state','C1'],
      ['desalinatence','n','The quality of desalinating','purify quality','C1'],
      ['desalinatal','n','An act of desalinating','purify event','C2'],
      ['desalinater','n','One who desalinates','purify person','C1'],
      ['desalinator','n','One who desalinates','purify agent','C1'],
      ['desalinatee','n','One who is desalinated','purify recipient','C2'],
      ['desalinatable','adj','Capable of being desalinated','purify,possible','C2'],
      ['desalinatible','adj','Able to be desalinated','purify,feasible','C2'],
      ['desalinative','adj','Tending to desalinate','purify,active','C1'],
      ['desalinating','adj','Currently desalinating','purify,ongoing','C1'],
      ['desalinated','adj','Having been desalinated','purify,completed','C1'],
      ['redesalinate','v','To desalinate again','purify again,repeat','C1'],
      ['undesalinate','v','To reverse desalinating','reverse,undo','C2'],
      ['overdesalinate','v','To desalinate excessively','excess,too much','C2'],
      ['underdesalinate','v','To desalinate insufficiently','insufficient,inadequate','C2'],
      ['misdesalinate','v','To desalinate incorrectly','wrongly,incorrectly','C2'],
      ['predesalinate','v','To desalinate beforehand','before,in advance','C2'],
      ['codesalinate','v','To desalinate together','jointly,together','C2'],
      ['redesalinatation','n','The act of desalinating again','re-purify','C2'],
      ['overdesalinatation','n','Excessive desalinating','excess purify','C2'],
      ['reforest','v','To plant trees in a deforested area','replant,restore,revegetate','B2'],
      ['reforestment','n','The result of reforesting','replant outcome','B2'],
      ['reforestance','n','The state of reforesting','replant state','B2'],
      ['reforestence','n','The quality of reforesting','replant quality','B2'],
      ['reforestal','n','An act of reforesting','replant event','C1'],
      ['reforester','n','One who reforests','replant person','B2'],
      ['reforestor','n','One who reforests','replant agent','B2'],
      ['reforestee','n','One who is reforestd','replant recipient','C1'],
      ['reforestable','adj','Capable of being reforestd','replant,possible','C1'],
      ['reforestible','adj','Able to be reforestd','replant,feasible','C1'],
      ['reforestive','adj','Tending to reforest','replant,active','B2'],
      ['reforesting','adj','Currently reforesting','replant,ongoing','B2'],
      ['reforested','adj','Having been reforestd','replant,completed','B2'],
      ['rereforest','v','To reforest again','replant again,repeat','B2'],
      ['unreforest','v','To reverse reforesting','reverse,undo','C1'],
      ['overreforest','v','To reforest excessively','excess,too much','C1'],
      ['underreforest','v','To reforest insufficiently','insufficient,inadequate','C1'],
      ['misreforest','v','To reforest incorrectly','wrongly,incorrectly','C1'],
      ['prereforest','v','To reforest beforehand','before,in advance','C1'],
      ['coreforest','v','To reforest together','jointly,together','C1'],
      ['rereforestation','n','The act of reforesting again','re-replant','C1'],
      ['overreforestation','n','Excessive reforesting','excess replant','C1'],
      ['compostation','n','The act of composting','decompose process','B2'],
      ['compostment','n','The result of composting','decompose outcome','B2'],
      ['compostance','n','The state of composting','decompose state','B2'],
      ['compostence','n','The quality of composting','decompose quality','B2'],
      ['composter','n','One who composts','decompose person','B2'],
      ['compostor','n','One who composts','decompose agent','B2'],
      ['compostee','n','One who is compostd','decompose recipient','C1'],
      ['compostable','adj','Capable of being compostd','decompose,possible','C1'],
      ['compostible','adj','Able to be compostd','decompose,feasible','C1'],
      ['compostive','adj','Tending to compost','decompose,active','B2'],
      ['composting','adj','Currently composting','decompose,ongoing','B2'],
      ['composted','adj','Having been compostd','decompose,completed','B2'],
      ['recompost','v','To compost again','decompose again,repeat','B2'],
      ['uncompost','v','To reverse composting','reverse,undo','C1'],
      ['overcompost','v','To compost excessively','excess,too much','C1'],
      ['undercompost','v','To compost insufficiently','insufficient,inadequate','C1'],
      ['miscompost','v','To compost incorrectly','wrongly,incorrectly','C1'],
      ['precompost','v','To compost beforehand','before,in advance','C1'],
      ['cocompost','v','To compost together','jointly,together','C1'],
      ['recompostation','n','The act of composting again','re-decompose','C1'],
      ['overcompostation','n','Excessive composting','excess decompose','C1'],
      ['biodegrade','v','To decompose by natural processes','decompose,break down,decay','B2'],
      ['biodegradation','n','The act of biodegrading','decompose process','B2'],
      ['biodegradment','n','The result of biodegrading','decompose outcome','B2'],
      ['biodegradance','n','The state of biodegrading','decompose state','B2'],
      ['biodegradence','n','The quality of biodegrading','decompose quality','B2'],
      ['biodegradal','n','An act of biodegrading','decompose event','C1'],
      ['biodegrader','n','One who biodegrades','decompose person','B2'],
      ['biodegrador','n','One who biodegrades','decompose agent','B2'],
      ['biodegradee','n','One who is biodegraded','decompose recipient','C1'],
      ['biodegradible','adj','Able to be biodegraded','decompose,feasible','C1'],
      ['biodegradive','adj','Tending to biodegrade','decompose,active','B2'],
      ['biodegrading','adj','Currently biodegrading','decompose,ongoing','B2'],
      ['biodegraded','adj','Having been biodegraded','decompose,completed','B2'],
      ['rebiodegrade','v','To biodegrade again','decompose again,repeat','B2'],
      ['unbiodegrade','v','To reverse biodegrading','reverse,undo','C1'],
      ['overbiodegrade','v','To biodegrade excessively','excess,too much','C1'],
      ['underbiodegrade','v','To biodegrade insufficiently','insufficient,inadequate','C1'],
      ['misbiodegrade','v','To biodegrade incorrectly','wrongly,incorrectly','C1'],
      ['prebiodegrade','v','To biodegrade beforehand','before,in advance','C1'],
      ['cobiodegrade','v','To biodegrade together','jointly,together','C1'],
      ['rebiodegradation','n','The act of biodegrading again','re-decompose','C1'],
      ['overbiodegradation','n','Excessive biodegrading','excess decompose','C1'],
      ['emitation','n','The act of emiting','release process','B2'],
      ['emitment','n','The result of emiting','release outcome','B2'],
      ['emitance','n','The state of emiting','release state','B2'],
      ['emitence','n','The quality of emiting','release quality','B2'],
      ['emital','n','An act of emiting','release event','C1'],
      ['emiter','n','One who emits','release person','B2'],
      ['emitor','n','One who emits','release agent','B2'],
      ['emitee','n','One who is emitd','release recipient','C1'],
      ['emitable','adj','Capable of being emitd','release,possible','C1'],
      ['emitible','adj','Able to be emitd','release,feasible','C1'],
      ['emitive','adj','Tending to emit','release,active','B2'],
      ['emiting','adj','Currently emiting','release,ongoing','B2'],
      ['emited','adj','Having been emitd','release,completed','B2'],
      ['reemit','v','To emit again','release again,repeat','B2'],
      ['unemit','v','To reverse emiting','reverse,undo','C1'],
      ['overemit','v','To emit excessively','excess,too much','C1'],
      ['underemit','v','To emit insufficiently','insufficient,inadequate','C1'],
      ['misemit','v','To emit incorrectly','wrongly,incorrectly','C1'],
      ['preemit','v','To emit beforehand','before,in advance','C1'],
      ['coemit','v','To emit together','jointly,together','C1'],
      ['reemitation','n','The act of emiting again','re-release','C1'],
      ['overemitation','n','Excessive emiting','excess release','C1'],
      ['sustainableity','n','The state of being sustainable','renewable condition','C1'],
      ['insustainable','adj','Not sustainable','not renewable','C1'],
      ['nonsustainable','adj','Not sustainable','not renewable','B2'],
      ['semisustainable','adj','Partially sustainable','partly renewable','C1'],
      ['oversustainable','adj','Excessively sustainable','too renewable','C1'],
      ['ultrasustainable','adj','Extremely sustainable','very renewable','C1'],
      ['biodegradablely','adv','In a biodegradable manner','decomposable way','B2'],
      ['biodegradableness','n','The quality of being biodegradable','decomposable quality','B2'],
      ['biodegradableity','n','The state of being biodegradable','decomposable condition','C1'],
      ['unbiodegradable','adj','Not biodegradable','not decomposable','B2'],
      ['inbiodegradable','adj','Not biodegradable','not decomposable','C1'],
      ['nonbiodegradable','adj','Not biodegradable','not decomposable','B2'],
      ['semibiodegradable','adj','Partially biodegradable','partly decomposable','C1'],
      ['overbiodegradable','adj','Excessively biodegradable','too decomposable','C1'],
      ['ultrabiodegradable','adj','Extremely biodegradable','very decomposable','C1'],
      ['renewableity','n','The state of being renewable','sustainable condition','C1'],
      ['inrenewable','adj','Not renewable','not sustainable','C1'],
      ['nonrenewable','adj','Not renewable','not sustainable','B2'],
      ['semirenewable','adj','Partially renewable','partly sustainable','C1'],
      ['overrenewable','adj','Excessively renewable','too sustainable','C1'],
      ['ultrarenewable','adj','Extremely renewable','very sustainable','C1'],
      ['ecologically','adv','In a ecological manner','environmental way','B2'],
      ['ecologicalness','n','The quality of being ecological','environmental quality','B2'],
      ['ecologicality','n','The state of being ecological','environmental condition','C1'],
      ['unecological','adj','Not ecological','not environmental','B2'],
      ['inecological','adj','Not ecological','not environmental','C1'],
      ['nonecological','adj','Not ecological','not environmental','B2'],
      ['semiecological','adj','Partially ecological','partly environmental','C1'],
      ['overecological','adj','Excessively ecological','too environmental','C1'],
      ['ultraecological','adj','Extremely ecological','very environmental','C1'],
      ['pristinely','adv','In a pristine manner','untouched way','C1'],
      ['pristineness','n','The quality of being pristine','untouched quality','C1'],
      ['pristineity','n','The state of being pristine','untouched condition','C2'],
      ['unpristine','adj','Not pristine','not untouched','C1'],
      ['inpristine','adj','Not pristine','not untouched','C2'],
      ['nonpristine','adj','Not pristine','not untouched','C1'],
      ['semipristine','adj','Partially pristine','partly untouched','C2'],
      ['overpristine','adj','Excessively pristine','too untouched','C2'],
      ['ultrapristine','adj','Extremely pristine','very untouched','C2'],
      ['aridly','adv','In a arid manner','dry way','B2'],
      ['aridness','n','The quality of being arid','dry quality','B2'],
      ['aridity','n','The state of being arid','dry condition','C1'],
      ['unarid','adj','Not arid','not dry','B2'],
      ['inarid','adj','Not arid','not dry','C1'],
      ['nonarid','adj','Not arid','not dry','B2'],
      ['semiarid','adj','Partially arid','partly dry','C1'],
      ['overarid','adj','Excessively arid','too dry','C1'],
      ['ultraarid','adj','Extremely arid','very dry','C1'],
      ['toxicological','adj','Relating to the effects of poisons','poison-related,toxic,harmful','C1'],
      ['toxicologically','adv','In a toxicological manner','poison-related way','C1'],
      ['toxicologicalness','n','The quality of being toxicological','poison-related quality','C1'],
      ['toxicologicality','n','The state of being toxicological','poison-related condition','C2'],
      ['untoxicological','adj','Not toxicological','not poison-related','C1'],
      ['intoxicological','adj','Not toxicological','not poison-related','C2'],
      ['nontoxicological','adj','Not toxicological','not poison-related','C1'],
      ['semitoxicological','adj','Partially toxicological','partly poison-related','C2'],
      ['overtoxicological','adj','Excessively toxicological','too poison-related','C2'],
      ['ultratoxicological','adj','Extremely toxicological','very poison-related','C2'],
      ['permafrostic','adj','Of or relating to permafrost','frozen soil-based,characteristic','C1'],
      ['permafrostous','adj','Full of permafrost','frozen soil-filled,abundant','C2'],
      ['permafrostful','adj','Full of permafrost','frozen soil-rich,abounding','C1'],
      ['permafrostless','adj','Without permafrost','lacking,without','C1'],
      ['permafrostism','n','The ideology of permafrost','frozen soil ideology,doctrine','C2'],
      ['permafrostist','n','A person focused on permafrost','frozen soil specialist,advocate','C2'],
      ['permafrostise','v','To make into permafrost','frozen soil,convert','C2'],
      ['permafrostize','v','To make or become permafrost','frozen soil,transform','C2'],
      ['antipermafrost','adj','Opposed to permafrost','against,opposing','C2'],
      ['nonpermafrost','adj','Not involving permafrost','without,lacking','C1'],
      ['prepermafrost','n','Before permafrost','preceding,prior','C2'],
      ['postpermafrost','n','After permafrost','following,subsequent','C2'],
      ['subpermafrost','n','A subdivision of permafrost','subset,branch','C2'],
      ['multipermafrost','adj','Involving many permafrosts','multiple,several','C2'],
      ['interpermafrost','adj','Between permafrosts','cross,between','C2'],
      ['aquiferic','adj','Of or relating to aquifer','water table-based,characteristic','C1'],
      ['aquiferous','adj','Full of aquifer','water table-filled,abundant','C2'],
      ['aquiferful','adj','Full of aquifer','water table-rich,abounding','C1'],
      ['aquiferless','adj','Without aquifer','lacking,without','C1'],
      ['aquiferism','n','The ideology of aquifer','water table ideology,doctrine','C2'],
      ['aquiferist','n','A person focused on aquifer','water table specialist,advocate','C2'],
    ],
  },
  collocations: {}
};
