// Auto-generated vocab boost group 74
module.exports = {
  vocab: {
    sports: [
      ['predoping','n','Before doping','preceding,prior','C1'],
      ['postdoping','n','After doping','following,subsequent','C1'],
      ['subdoping','n','A subdivision of doping','subset,branch','C1'],
      ['multidoping','adj','Involving many dopings','multiple,several','C1'],
      ['interdoping','adj','Between dopings','cross,between','C1'],
      ['prowessal','adj','Relating to prowess','skill-related,pertaining to','C1'],
      ['prowessic','adj','Of or relating to prowess','skill-based,characteristic','C1'],
      ['prowessous','adj','Full of prowess','skill-filled,abundant','C2'],
      ['prowessful','adj','Full of prowess','skill-rich,abounding','C1'],
      ['prowessless','adj','Without prowess','lacking,without','C1'],
      ['prowessism','n','The ideology of prowess','skill ideology,doctrine','C2'],
      ['prowessist','n','A person focused on prowess','skill specialist,advocate','C2'],
      ['prowessise','v','To make into prowess','skill,convert','C2'],
      ['prowessize','v','To make or become prowess','skill,transform','C2'],
      ['antiprowess','adj','Opposed to prowess','against,opposing','C2'],
      ['nonprowess','adj','Not involving prowess','without,lacking','C1'],
      ['preprowess','n','Before prowess','preceding,prior','C2'],
      ['postprowess','n','After prowess','following,subsequent','C2'],
      ['subprowess','n','A subdivision of prowess','subset,branch','C2'],
      ['multiprowess','adj','Involving many prowesss','multiple,several','C2'],
      ['interprowess','adj','Between prowesss','cross,between','C2'],
      ['tenacity','n','The quality of persistent determination','persistence,determination,grit','C1'],
      ['tenacityal','adj','Relating to tenacity','persistence-related,pertaining to','C1'],
      ['tenacityic','adj','Of or relating to tenacity','persistence-based,characteristic','C1'],
      ['tenacityous','adj','Full of tenacity','persistence-filled,abundant','C2'],
      ['tenacityful','adj','Full of tenacity','persistence-rich,abounding','C1'],
      ['tenacityless','adj','Without tenacity','lacking,without','C1'],
      ['tenacityism','n','The ideology of tenacity','persistence ideology,doctrine','C2'],
      ['tenacityist','n','A person focused on tenacity','persistence specialist,advocate','C2'],
      ['tenacityise','v','To make into tenacity','persistence,convert','C2'],
      ['tenacityize','v','To make or become tenacity','persistence,transform','C2'],
      ['antitenacity','adj','Opposed to tenacity','against,opposing','C2'],
      ['nontenacity','adj','Not involving tenacity','without,lacking','C1'],
      ['pretenacity','n','Before tenacity','preceding,prior','C2'],
      ['posttenacity','n','After tenacity','following,subsequent','C2'],
      ['subtenacity','n','A subdivision of tenacity','subset,branch','C2'],
      ['multitenacity','adj','Involving many tenacitys','multiple,several','C2'],
      ['intertenacity','adj','Between tenacitys','cross,between','C2'],
      ['accoladeal','adj','Relating to accolade','honour-related,pertaining to','C1'],
      ['accoladeic','adj','Of or relating to accolade','honour-based,characteristic','C1'],
      ['accoladeous','adj','Full of accolade','honour-filled,abundant','C2'],
      ['accoladeful','adj','Full of accolade','honour-rich,abounding','C1'],
      ['accoladeless','adj','Without accolade','lacking,without','C1'],
      ['accoladeism','n','The ideology of accolade','honour ideology,doctrine','C2'],
      ['accoladeist','n','A person focused on accolade','honour specialist,advocate','C2'],
      ['accoladeise','v','To make into accolade','honour,convert','C2'],
      ['accoladeize','v','To make or become accolade','honour,transform','C2'],
      ['antiaccolade','adj','Opposed to accolade','against,opposing','C2'],
      ['nonaccolade','adj','Not involving accolade','without,lacking','C1'],
      ['preaccolade','n','Before accolade','preceding,prior','C2'],
      ['postaccolade','n','After accolade','following,subsequent','C2'],
      ['subaccolade','n','A subdivision of accolade','subset,branch','C2'],
      ['multiaccolade','adj','Involving many accolades','multiple,several','C2'],
      ['interaccolade','adj','Between accolades','cross,between','C2'],
      ['antipodean','adj','Relating to opposite sides of the earth','opposite,diametrically opposed','C2'],
      ['antipodeanly','adv','In a antipodean manner','opposite way','C2'],
      ['antipodeanness','n','The quality of being antipodean','opposite quality','C2'],
      ['antipodeanity','n','The state of being antipodean','opposite condition','C2'],
      ['unantipodean','adj','Not antipodean','not opposite','C2'],
      ['inantipodean','adj','Not antipodean','not opposite','C2'],
      ['nonantipodean','adj','Not antipodean','not opposite','C2'],
      ['semiantipodean','adj','Partially antipodean','partly opposite','C2'],
      ['overantipodean','adj','Excessively antipodean','too opposite','C2'],
      ['ultraantipodean','adj','Extremely antipodean','very opposite','C2'],
      ['pugilisticly','adv','In a pugilistic manner','boxing-related way','C2'],
      ['pugilisticness','n','The quality of being pugilistic','boxing-related quality','C2'],
      ['pugilisticity','n','The state of being pugilistic','boxing-related condition','C2'],
      ['unpugilistic','adj','Not pugilistic','not boxing-related','C2'],
      ['inpugilistic','adj','Not pugilistic','not boxing-related','C2'],
      ['nonpugilistic','adj','Not pugilistic','not boxing-related','C2'],
      ['semipugilistic','adj','Partially pugilistic','partly boxing-related','C2'],
      ['overpugilistic','adj','Excessively pugilistic','too boxing-related','C2'],
      ['ultrapugilistic','adj','Extremely pugilistic','very boxing-related','C2'],
      ['equestrian','adj','Relating to horse riding','horse-related,riding,mounted','C1'],
      ['equestrianly','adv','In a equestrian manner','horse-related way','C1'],
      ['equestrianness','n','The quality of being equestrian','horse-related quality','C1'],
      ['equestrianity','n','The state of being equestrian','horse-related condition','C2'],
      ['unequestrian','adj','Not equestrian','not horse-related','C1'],
      ['inequestrian','adj','Not equestrian','not horse-related','C2'],
      ['nonequestrian','adj','Not equestrian','not horse-related','C1'],
      ['semiequestrian','adj','Partially equestrian','partly horse-related','C2'],
      ['overequestrian','adj','Excessively equestrian','too horse-related','C2'],
      ['ultraequestrian','adj','Extremely equestrian','very horse-related','C2'],
      ['aquatic','adj','Relating to water sports','water-based,marine,swimming','B2'],
      ['aquaticly','adv','In a aquatic manner','water-based way','B2'],
      ['aquaticness','n','The quality of being aquatic','water-based quality','B2'],
      ['aquaticity','n','The state of being aquatic','water-based condition','C1'],
      ['unaquatic','adj','Not aquatic','not water-based','B2'],
      ['inaquatic','adj','Not aquatic','not water-based','C1'],
      ['nonaquatic','adj','Not aquatic','not water-based','B2'],
      ['semiaquatic','adj','Partially aquatic','partly water-based','C1'],
      ['overaquatic','adj','Excessively aquatic','too water-based','C1'],
      ['ultraaquatic','adj','Extremely aquatic','very water-based','C1'],
      ['arboreal','adj','Relating to trees and climbing','tree-based,climbing,forest','C1'],
      ['arboreally','adv','In a arboreal manner','tree-based way','C1'],
      ['arborealness','n','The quality of being arboreal','tree-based quality','C1'],
      ['arboreality','n','The state of being arboreal','tree-based condition','C2'],
      ['unarboreal','adj','Not arboreal','not tree-based','C1'],
      ['inarboreal','adj','Not arboreal','not tree-based','C2'],
      ['nonarboreal','adj','Not arboreal','not tree-based','C1'],
      ['semiarboreal','adj','Partially arboreal','partly tree-based','C2'],
      ['overarboreal','adj','Excessively arboreal','too tree-based','C2'],
      ['ultraarboreal','adj','Extremely arboreal','very tree-based','C2'],
      ['kinesthetic','adj','Relating to body movement awareness','movement-based,physical,tactile','C1'],
      ['kinestheticly','adv','In a kinesthetic manner','movement-based way','C1'],
      ['kinestheticness','n','The quality of being kinesthetic','movement-based quality','C1'],
      ['kinestheticity','n','The state of being kinesthetic','movement-based condition','C2'],
      ['unkinesthetic','adj','Not kinesthetic','not movement-based','C1'],
      ['inkinesthetic','adj','Not kinesthetic','not movement-based','C2'],
      ['nonkinesthetic','adj','Not kinesthetic','not movement-based','C1'],
      ['semikinesthetic','adj','Partially kinesthetic','partly movement-based','C2'],
      ['overkinesthetic','adj','Excessively kinesthetic','too movement-based','C2'],
      ['ultrakinesthetic','adj','Extremely kinesthetic','very movement-based','C2'],
      ['formidablely','adv','In a formidable manner','impressive way','C1'],
      ['formidableness','n','The quality of being formidable','impressive quality','C1'],
      ['formidableity','n','The state of being formidable','impressive condition','C2'],
      ['unformidable','adj','Not formidable','not impressive','C1'],
      ['informidable','adj','Not formidable','not impressive','C2'],
      ['nonformidable','adj','Not formidable','not impressive','C1'],
      ['semiformidable','adj','Partially formidable','partly impressive','C2'],
      ['overformidable','adj','Excessively formidable','too impressive','C2'],
      ['ultraformidable','adj','Extremely formidable','very impressive','C2'],
      ['unbeatenly','adv','In a unbeaten manner','undefeated way','B2'],
      ['unbeatenness','n','The quality of being unbeaten','undefeated quality','B2'],
      ['unbeatenity','n','The state of being unbeaten','undefeated condition','C1'],
      ['ununbeaten','adj','Not unbeaten','not undefeated','B2'],
      ['inunbeaten','adj','Not unbeaten','not undefeated','C1'],
      ['nonunbeaten','adj','Not unbeaten','not undefeated','B2'],
      ['semiunbeaten','adj','Partially unbeaten','partly undefeated','C1'],
      ['overunbeaten','adj','Excessively unbeaten','too undefeated','C1'],
      ['ultraunbeaten','adj','Extremely unbeaten','very undefeated','C1'],
      ['gruellingly','adv','In a gruelling manner','exhausting way','C1'],
      ['gruellingness','n','The quality of being gruelling','exhausting quality','C1'],
      ['gruellingity','n','The state of being gruelling','exhausting condition','C2'],
      ['ungruelling','adj','Not gruelling','not exhausting','C1'],
      ['ingruelling','adj','Not gruelling','not exhausting','C2'],
      ['nongruelling','adj','Not gruelling','not exhausting','C1'],
      ['semigruelling','adj','Partially gruelling','partly exhausting','C2'],
      ['overgruelling','adj','Excessively gruelling','too exhausting','C2'],
      ['ultragruelling','adj','Extremely gruelling','very exhausting','C2'],
    ],
    food: [
      ['ferment','v','To undergo chemical breakdown','brew,culture,ripen','B2'],
      ['fermentment','n','The result of fermenting','brew outcome','B2'],
      ['fermentance','n','The state of fermenting','brew state','B2'],
      ['fermentence','n','The quality of fermenting','brew quality','B2'],
      ['fermental','n','An act of fermenting','brew event','C1'],
      ['fermenter','n','One who ferments','brew person','B2'],
      ['fermentor','n','One who ferments','brew agent','B2'],
      ['fermentee','n','One who is fermentd','brew recipient','C1'],
      ['fermentable','adj','Capable of being fermentd','brew,possible','C1'],
      ['fermentible','adj','Able to be fermentd','brew,feasible','C1'],
      ['fermentive','adj','Tending to ferment','brew,active','B2'],
      ['fermenting','adj','Currently fermenting','brew,ongoing','B2'],
      ['fermented','adj','Having been fermentd','brew,completed','B2'],
      ['referment','v','To ferment again','brew again,repeat','B2'],
      ['unferment','v','To reverse fermenting','reverse,undo','C1'],
      ['overferment','v','To ferment excessively','excess,too much','C1'],
      ['underferment','v','To ferment insufficiently','insufficient,inadequate','C1'],
      ['misferment','v','To ferment incorrectly','wrongly,incorrectly','C1'],
      ['preferment','v','To ferment beforehand','before,in advance','C1'],
      ['coferment','v','To ferment together','jointly,together','C1'],
      ['refermentation','n','The act of fermenting again','re-brew','C1'],
      ['overfermentation','n','Excessive fermenting','excess brew','C1'],
      ['pasteurize','v','To heat to destroy bacteria','sterilize,heat-treat,sanitize','C1'],
      ['pasteurization','n','The act of pasteurizing','sterilize process','C1'],
      ['pasteurizment','n','The result of pasteurizing','sterilize outcome','C1'],
      ['pasteurizance','n','The state of pasteurizing','sterilize state','C1'],
      ['pasteurizence','n','The quality of pasteurizing','sterilize quality','C1'],
      ['pasteurizal','n','An act of pasteurizing','sterilize event','C2'],
      ['pasteurizer','n','One who pasteurizes','sterilize person','C1'],
      ['pasteurizor','n','One who pasteurizes','sterilize agent','C1'],
      ['pasteurizee','n','One who is pasteurized','sterilize recipient','C2'],
      ['pasteurizable','adj','Capable of being pasteurized','sterilize,possible','C2'],
      ['pasteurizible','adj','Able to be pasteurized','sterilize,feasible','C2'],
      ['pasteurizive','adj','Tending to pasteurize','sterilize,active','C1'],
      ['pasteurizing','adj','Currently pasteurizing','sterilize,ongoing','C1'],
      ['repasteurize','v','To pasteurize again','sterilize again,repeat','C1'],
      ['unpasteurize','v','To reverse pasteurizing','reverse,undo','C2'],
      ['overpasteurize','v','To pasteurize excessively','excess,too much','C2'],
      ['underpasteurize','v','To pasteurize insufficiently','insufficient,inadequate','C2'],
      ['mispasteurize','v','To pasteurize incorrectly','wrongly,incorrectly','C2'],
      ['prepasteurize','v','To pasteurize beforehand','before,in advance','C2'],
      ['copasteurize','v','To pasteurize together','jointly,together','C2'],
      ['repasteurization','n','The act of pasteurizing again','re-sterilize','C2'],
      ['overpasteurization','n','Excessive pasteurizing','excess sterilize','C2'],
      ['marinatment','n','The result of marinating','soak outcome','B2'],
      ['marinatance','n','The state of marinating','soak state','B2'],
      ['marinatence','n','The quality of marinating','soak quality','B2'],
      ['marinatal','n','An act of marinating','soak event','C1'],
      ['marinator','n','One who marinates','soak agent','B2'],
      ['marinatee','n','One who is marinated','soak recipient','C1'],
      ['marinatible','adj','Able to be marinated','soak,feasible','C1'],
      ['marinative','adj','Tending to marinate','soak,active','B2'],
      ['marinated','adj','Having been marinated','soak,completed','B2'],
      ['remarinate','v','To marinate again','soak again,repeat','B2'],
      ['unmarinate','v','To reverse marinating','reverse,undo','C1'],
      ['overmarinate','v','To marinate excessively','excess,too much','C1'],
      ['undermarinate','v','To marinate insufficiently','insufficient,inadequate','C1'],
      ['mismarinate','v','To marinate incorrectly','wrongly,incorrectly','C1'],
      ['premarinate','v','To marinate beforehand','before,in advance','C1'],
      ['comarinate','v','To marinate together','jointly,together','C1'],
      ['remarinatation','n','The act of marinating again','re-soak','C1'],
      ['overmarinatation','n','Excessive marinating','excess soak','C1'],
      ['adulterate','v','To make impure by adding substances','contaminate,dilute,debase','C1'],
      ['adulteratation','n','The act of adulterating','contaminate process','C1'],
      ['adulteratment','n','The result of adulterating','contaminate outcome','C1'],
      ['adulteratance','n','The state of adulterating','contaminate state','C1'],
      ['adulteratence','n','The quality of adulterating','contaminate quality','C1'],
      ['adulteratal','n','An act of adulterating','contaminate event','C2'],
      ['adulterater','n','One who adulterates','contaminate person','C1'],
      ['adulterator','n','One who adulterates','contaminate agent','C1'],
      ['adulteratee','n','One who is adulterated','contaminate recipient','C2'],
      ['adulteratable','adj','Capable of being adulterated','contaminate,possible','C2'],
      ['adulteratible','adj','Able to be adulterated','contaminate,feasible','C2'],
      ['adulterative','adj','Tending to adulterate','contaminate,active','C1'],
      ['adulterating','adj','Currently adulterating','contaminate,ongoing','C1'],
      ['adulterated','adj','Having been adulterated','contaminate,completed','C1'],
      ['readulterate','v','To adulterate again','contaminate again,repeat','C1'],
      ['unadulterate','v','To reverse adulterating','reverse,undo','C2'],
      ['overadulterate','v','To adulterate excessively','excess,too much','C2'],
      ['underadulterate','v','To adulterate insufficiently','insufficient,inadequate','C2'],
      ['misadulterate','v','To adulterate incorrectly','wrongly,incorrectly','C2'],
      ['preadulterate','v','To adulterate beforehand','before,in advance','C2'],
      ['coadulterate','v','To adulterate together','jointly,together','C2'],
      ['readulteratation','n','The act of adulterating again','re-contaminate','C2'],
      ['overadulteratation','n','Excessive adulterating','excess contaminate','C2'],
      ['fortify','v','To increase nutritional value','enrich,supplement,enhance','B2'],
      ['fortifyation','n','The act of fortifying','enrich process','B2'],
      ['fortifyment','n','The result of fortifying','enrich outcome','B2'],
      ['fortifyance','n','The state of fortifying','enrich state','B2'],
      ['fortifyence','n','The quality of fortifying','enrich quality','B2'],
      ['fortifyal','n','An act of fortifying','enrich event','C1'],
      ['fortifyer','n','One who fortifys','enrich person','B2'],
      ['fortifyor','n','One who fortifys','enrich agent','B2'],
      ['fortifyee','n','One who is fortifyd','enrich recipient','C1'],
      ['fortifyable','adj','Capable of being fortifyd','enrich,possible','C1'],
      ['fortifyible','adj','Able to be fortifyd','enrich,feasible','C1'],
      ['fortifyive','adj','Tending to fortify','enrich,active','B2'],
      ['fortifying','adj','Currently fortifying','enrich,ongoing','B2'],
      ['fortifyed','adj','Having been fortifyd','enrich,completed','B2'],
      ['refortify','v','To fortify again','enrich again,repeat','B2'],
      ['unfortify','v','To reverse fortifying','reverse,undo','C1'],
      ['overfortify','v','To fortify excessively','excess,too much','C1'],
      ['underfortify','v','To fortify insufficiently','insufficient,inadequate','C1'],
      ['misfortify','v','To fortify incorrectly','wrongly,incorrectly','C1'],
      ['prefortify','v','To fortify beforehand','before,in advance','C1'],
      ['cofortify','v','To fortify together','jointly,together','C1'],
      ['refortifyation','n','The act of fortifying again','re-enrich','C1'],
      ['overfortifyation','n','Excessive fortifying','excess enrich','C1'],
      ['dehydrate','v','To remove moisture from food','dry,desiccate,preserve','B2'],
      ['dehydratation','n','The act of dehydrating','dry process','B2'],
    ],
  },
  collocations: {}
};
