// Auto-generated vocab boost group 80
module.exports = {
  vocab: {
    transport: [
      ['fuselageic','adj','Of or relating to fuselage','body-based,characteristic','C1'],
      ['fuselageous','adj','Full of fuselage','body-filled,abundant','C2'],
      ['fuselageful','adj','Full of fuselage','body-rich,abounding','C1'],
      ['fuselageless','adj','Without fuselage','lacking,without','C1'],
      ['fuselageism','n','The ideology of fuselage','body ideology,doctrine','C2'],
      ['fuselageist','n','A person focused on fuselage','body specialist,advocate','C2'],
      ['fuselageise','v','To make into fuselage','body,convert','C2'],
      ['fuselageize','v','To make or become fuselage','body,transform','C2'],
      ['antifuselage','adj','Opposed to fuselage','against,opposing','C2'],
      ['nonfuselage','adj','Not involving fuselage','without,lacking','C1'],
      ['prefuselage','n','Before fuselage','preceding,prior','C2'],
      ['postfuselage','n','After fuselage','following,subsequent','C2'],
      ['subfuselage','n','A subdivision of fuselage','subset,branch','C2'],
      ['multifuselage','adj','Involving many fuselages','multiple,several','C2'],
      ['interfuselage','adj','Between fuselages','cross,between','C2'],
      ['turbocharge','v','To boost engine power','supercharge,boost,enhance','B2'],
      ['turbochargation','n','The act of turbocharging','supercharge process','B2'],
      ['turbochargment','n','The result of turbocharging','supercharge outcome','B2'],
      ['turbochargance','n','The state of turbocharging','supercharge state','B2'],
      ['turbochargence','n','The quality of turbocharging','supercharge quality','B2'],
      ['turbochargal','n','An act of turbocharging','supercharge event','C1'],
      ['turbocharger','n','One who turbocharges','supercharge person','B2'],
      ['turbochargor','n','One who turbocharges','supercharge agent','B2'],
      ['turbochargee','n','One who is turbocharged','supercharge recipient','C1'],
      ['turbochargable','adj','Capable of being turbocharged','supercharge,possible','C1'],
      ['turbochargible','adj','Able to be turbocharged','supercharge,feasible','C1'],
      ['turbochargive','adj','Tending to turbocharge','supercharge,active','B2'],
      ['turbocharging','adj','Currently turbocharging','supercharge,ongoing','B2'],
      ['turbocharged','adj','Having been turbocharged','supercharge,completed','B2'],
      ['returbocharge','v','To turbocharge again','supercharge again,repeat','B2'],
      ['unturbocharge','v','To reverse turbocharging','reverse,undo','C1'],
      ['overturbocharge','v','To turbocharge excessively','excess,too much','C1'],
      ['underturbocharge','v','To turbocharge insufficiently','insufficient,inadequate','C1'],
      ['misturbocharge','v','To turbocharge incorrectly','wrongly,incorrectly','C1'],
      ['preturbocharge','v','To turbocharge beforehand','before,in advance','C1'],
      ['coturbocharge','v','To turbocharge together','jointly,together','C1'],
      ['returbochargation','n','The act of turbocharging again','re-supercharge','C1'],
      ['overturbochargation','n','Excessive turbocharging','excess supercharge','C1'],
      ['derail','v','To cause to leave the tracks','go off track,crash,divert','B2'],
      ['derailation','n','The act of derailing','go off track process','B2'],
      ['derailance','n','The state of derailing','go off track state','B2'],
      ['derailence','n','The quality of derailing','go off track quality','B2'],
      ['derailal','n','An act of derailing','go off track event','C1'],
      ['derailer','n','One who derails','go off track person','B2'],
      ['derailor','n','One who derails','go off track agent','B2'],
      ['derailee','n','One who is deraild','go off track recipient','C1'],
      ['derailable','adj','Capable of being deraild','go off track,possible','C1'],
      ['derailible','adj','Able to be deraild','go off track,feasible','C1'],
      ['derailive','adj','Tending to derail','go off track,active','B2'],
      ['derailing','adj','Currently derailing','go off track,ongoing','B2'],
      ['derailed','adj','Having been deraild','go off track,completed','B2'],
      ['rederail','v','To derail again','go off track again,repeat','B2'],
      ['underail','v','To reverse derailing','reverse,undo','C1'],
      ['overderail','v','To derail excessively','excess,too much','C1'],
      ['underderail','v','To derail insufficiently','insufficient,inadequate','C1'],
      ['misderail','v','To derail incorrectly','wrongly,incorrectly','C1'],
      ['prederail','v','To derail beforehand','before,in advance','C1'],
      ['coderail','v','To derail together','jointly,together','C1'],
      ['rederailation','n','The act of derailing again','re-go off track','C1'],
      ['overderailation','n','Excessive derailing','excess go off track','C1'],
      ['retrofitation','n','The act of retrofiting','upgrade process','C1'],
      ['retrofitment','n','The result of retrofiting','upgrade outcome','C1'],
      ['retrofitance','n','The state of retrofiting','upgrade state','C1'],
      ['retrofitence','n','The quality of retrofiting','upgrade quality','C1'],
      ['retrofital','n','An act of retrofiting','upgrade event','C2'],
      ['retrofiter','n','One who retrofits','upgrade person','C1'],
      ['retrofitor','n','One who retrofits','upgrade agent','C1'],
      ['retrofitee','n','One who is retrofitd','upgrade recipient','C2'],
      ['retrofitable','adj','Capable of being retrofitd','upgrade,possible','C2'],
      ['retrofitible','adj','Able to be retrofitd','upgrade,feasible','C2'],
      ['retrofitive','adj','Tending to retrofit','upgrade,active','C1'],
      ['retrofiting','adj','Currently retrofiting','upgrade,ongoing','C1'],
      ['retrofited','adj','Having been retrofitd','upgrade,completed','C1'],
      ['reretrofit','v','To retrofit again','upgrade again,repeat','C1'],
      ['unretrofit','v','To reverse retrofiting','reverse,undo','C2'],
      ['overretrofit','v','To retrofit excessively','excess,too much','C2'],
      ['underretrofit','v','To retrofit insufficiently','insufficient,inadequate','C2'],
      ['misretrofit','v','To retrofit incorrectly','wrongly,incorrectly','C2'],
      ['preretrofit','v','To retrofit beforehand','before,in advance','C2'],
      ['coretrofit','v','To retrofit together','jointly,together','C2'],
      ['reretrofitation','n','The act of retrofiting again','re-upgrade','C2'],
      ['overretrofitation','n','Excessive retrofiting','excess upgrade','C2'],
      ['carpoolment','n','The result of carpooling','ride-share outcome','B2'],
      ['carpoolance','n','The state of carpooling','ride-share state','B2'],
      ['carpoolence','n','The quality of carpooling','ride-share quality','B2'],
      ['carpoolal','n','An act of carpooling','ride-share event','C1'],
      ['carpoolor','n','One who carpools','ride-share agent','B2'],
      ['carpoolee','n','One who is carpoold','ride-share recipient','C1'],
      ['carpoolible','adj','Able to be carpoold','ride-share,feasible','C1'],
      ['carpoolive','adj','Tending to carpool','ride-share,active','B2'],
      ['carpooled','adj','Having been carpoold','ride-share,completed','B2'],
      ['recarpool','v','To carpool again','ride-share again,repeat','B2'],
      ['uncarpool','v','To reverse carpooling','reverse,undo','C1'],
      ['overcarpool','v','To carpool excessively','excess,too much','C1'],
      ['undercarpool','v','To carpool insufficiently','insufficient,inadequate','C1'],
      ['miscarpool','v','To carpool incorrectly','wrongly,incorrectly','C1'],
      ['precarpool','v','To carpool beforehand','before,in advance','C1'],
      ['cocarpool','v','To carpool together','jointly,together','C1'],
      ['recarpoolation','n','The act of carpooling again','re-ride-share','C1'],
      ['overcarpoolation','n','Excessive carpooling','excess ride-share','C1'],
      ['congestion chargeal','adj','Relating to congestion charge','road toll-related,pertaining to','B2'],
      ['congestion chargeic','adj','Of or relating to congestion charge','road toll-based,characteristic','B2'],
      ['congestion chargeous','adj','Full of congestion charge','road toll-filled,abundant','C1'],
      ['congestion chargeful','adj','Full of congestion charge','road toll-rich,abounding','B2'],
      ['congestion chargeless','adj','Without congestion charge','lacking,without','B2'],
      ['congestion chargeism','n','The ideology of congestion charge','road toll ideology,doctrine','C1'],
      ['congestion chargeist','n','A person focused on congestion charge','road toll specialist,advocate','C1'],
      ['congestion chargeise','v','To make into congestion charge','road toll,convert','C1'],
      ['congestion chargeize','v','To make or become congestion charge','road toll,transform','C1'],
      ['anticongestion charge','adj','Opposed to congestion charge','against,opposing','C1'],
      ['noncongestion charge','adj','Not involving congestion charge','without,lacking','B2'],
      ['precongestion charge','n','Before congestion charge','preceding,prior','C1'],
      ['postcongestion charge','n','After congestion charge','following,subsequent','C1'],
      ['subcongestion charge','n','A subdivision of congestion charge','subset,branch','C1'],
      ['multicongestion charge','adj','Involving many congestion charges','multiple,several','C1'],
      ['intercongestion charge','adj','Between congestion charges','cross,between','C1'],
      ['carbon neutral','adj','Producing no net carbon emissions','zero-emission,climate-neutral','B2'],
      ['carbon neutrally','adv','In a carbon neutral manner','zero-emission way','B2'],
      ['carbon neutralness','n','The quality of being carbon neutral','zero-emission quality','B2'],
      ['uncarbon neutral','adj','Not carbon neutral','not zero-emission','B2'],
      ['incarbon neutral','adj','Not carbon neutral','not zero-emission','C1'],
      ['noncarbon neutral','adj','Not carbon neutral','not zero-emission','B2'],
      ['semicarbon neutral','adj','Partially carbon neutral','partly zero-emission','C1'],
      ['overcarbon neutral','adj','Excessively carbon neutral','too zero-emission','C1'],
      ['ultracarbon neutral','adj','Extremely carbon neutral','very zero-emission','C1'],
      ['velocityal','adj','Relating to velocity','speed-related,pertaining to','B2'],
      ['velocityic','adj','Of or relating to velocity','speed-based,characteristic','B2'],
      ['velocityous','adj','Full of velocity','speed-filled,abundant','C1'],
      ['velocityful','adj','Full of velocity','speed-rich,abounding','B2'],
      ['velocityless','adj','Without velocity','lacking,without','B2'],
      ['velocityism','n','The ideology of velocity','speed ideology,doctrine','C1'],
      ['velocityist','n','A person focused on velocity','speed specialist,advocate','C1'],
      ['velocityise','v','To make into velocity','speed,convert','C1'],
      ['velocityize','v','To make or become velocity','speed,transform','C1'],
      ['antivelocity','adj','Opposed to velocity','against,opposing','C1'],
      ['nonvelocity','adj','Not involving velocity','without,lacking','B2'],
      ['prevelocity','n','Before velocity','preceding,prior','C1'],
      ['postvelocity','n','After velocity','following,subsequent','C1'],
      ['subvelocity','n','A subdivision of velocity','subset,branch','C1'],
      ['multivelocity','adj','Involving many velocitys','multiple,several','C1'],
      ['intervelocity','adj','Between velocitys','cross,between','C1'],
      ['causeway','n','A raised road across water or marsh','bridge,overpass,viaduct','C1'],
      ['causewayal','adj','Relating to causeway','bridge-related,pertaining to','C1'],
      ['causewayic','adj','Of or relating to causeway','bridge-based,characteristic','C1'],
      ['causewayous','adj','Full of causeway','bridge-filled,abundant','C2'],
      ['causewayful','adj','Full of causeway','bridge-rich,abounding','C1'],
      ['causewayless','adj','Without causeway','lacking,without','C1'],
      ['causewayism','n','The ideology of causeway','bridge ideology,doctrine','C2'],
      ['causewayist','n','A person focused on causeway','bridge specialist,advocate','C2'],
      ['causewayise','v','To make into causeway','bridge,convert','C2'],
      ['causewayize','v','To make or become causeway','bridge,transform','C2'],
      ['anticauseway','adj','Opposed to causeway','against,opposing','C2'],
      ['noncauseway','adj','Not involving causeway','without,lacking','C1'],
      ['precauseway','n','Before causeway','preceding,prior','C2'],
      ['postcauseway','n','After causeway','following,subsequent','C2'],
      ['subcauseway','n','A subdivision of causeway','subset,branch','C2'],
      ['multicauseway','adj','Involving many causeways','multiple,several','C2'],
      ['intercauseway','adj','Between causeways','cross,between','C2'],
      ['terminusal','adj','Relating to terminus','terminal-related,pertaining to','B2'],
      ['terminusic','adj','Of or relating to terminus','terminal-based,characteristic','B2'],
      ['terminusous','adj','Full of terminus','terminal-filled,abundant','C1'],
      ['terminusful','adj','Full of terminus','terminal-rich,abounding','B2'],
      ['terminusless','adj','Without terminus','lacking,without','B2'],
      ['terminusism','n','The ideology of terminus','terminal ideology,doctrine','C1'],
      ['terminusist','n','A person focused on terminus','terminal specialist,advocate','C1'],
      ['terminusise','v','To make into terminus','terminal,convert','C1'],
      ['terminusize','v','To make or become terminus','terminal,transform','C1'],
      ['antiterminus','adj','Opposed to terminus','against,opposing','C1'],
      ['nonterminus','adj','Not involving terminus','without,lacking','B2'],
      ['preterminus','n','Before terminus','preceding,prior','C1'],
      ['postterminus','n','After terminus','following,subsequent','C1'],
      ['subterminus','n','A subdivision of terminus','subset,branch','C1'],
      ['multiterminus','adj','Involving many terminuss','multiple,several','C1'],
      ['interterminus','adj','Between terminuss','cross,between','C1'],
      ['roundaboutic','adj','Of or relating to roundabout','rotary-based,characteristic','B1'],
      ['roundaboutous','adj','Full of roundabout','rotary-filled,abundant','B2'],
      ['roundaboutful','adj','Full of roundabout','rotary-rich,abounding','B1'],
      ['roundaboutless','adj','Without roundabout','lacking,without','B1'],
      ['roundaboutism','n','The ideology of roundabout','rotary ideology,doctrine','B2'],
      ['roundaboutist','n','A person focused on roundabout','rotary specialist,advocate','B2'],
      ['roundaboutise','v','To make into roundabout','rotary,convert','B2'],
      ['roundaboutize','v','To make or become roundabout','rotary,transform','B2'],
      ['antiroundabout','adj','Opposed to roundabout','against,opposing','B2'],
      ['nonroundabout','adj','Not involving roundabout','without,lacking','B1'],
      ['preroundabout','n','Before roundabout','preceding,prior','B2'],
      ['postroundabout','n','After roundabout','following,subsequent','B2'],
      ['subroundabout','n','A subdivision of roundabout','subset,branch','B2'],
      ['multiroundabout','adj','Involving many roundabouts','multiple,several','B2'],
      ['interroundabout','adj','Between roundabouts','cross,between','B2'],
      ['overpassal','adj','Relating to overpass','flyover-related,pertaining to','B2'],
      ['overpassic','adj','Of or relating to overpass','flyover-based,characteristic','B2'],
      ['overpassous','adj','Full of overpass','flyover-filled,abundant','C1'],
      ['overpassful','adj','Full of overpass','flyover-rich,abounding','B2'],
      ['overpassless','adj','Without overpass','lacking,without','B2'],
      ['overpassism','n','The ideology of overpass','flyover ideology,doctrine','C1'],
      ['overpassist','n','A person focused on overpass','flyover specialist,advocate','C1'],
      ['overpassise','v','To make into overpass','flyover,convert','C1'],
      ['overpassize','v','To make or become overpass','flyover,transform','C1'],
      ['antioverpass','adj','Opposed to overpass','against,opposing','C1'],
      ['nonoverpass','adj','Not involving overpass','without,lacking','B2'],
      ['preoverpass','n','Before overpass','preceding,prior','C1'],
      ['postoverpass','n','After overpass','following,subsequent','C1'],
      ['suboverpass','n','A subdivision of overpass','subset,branch','C1'],
      ['multioverpass','adj','Involving many overpasss','multiple,several','C1'],
      ['interoverpass','adj','Between overpasss','cross,between','C1'],
      ['underpassal','adj','Relating to underpass','tunnel-related,pertaining to','B2'],
      ['underpassic','adj','Of or relating to underpass','tunnel-based,characteristic','B2'],
      ['underpassous','adj','Full of underpass','tunnel-filled,abundant','C1'],
      ['underpassful','adj','Full of underpass','tunnel-rich,abounding','B2'],
      ['underpassless','adj','Without underpass','lacking,without','B2'],
      ['underpassism','n','The ideology of underpass','tunnel ideology,doctrine','C1'],
      ['underpassist','n','A person focused on underpass','tunnel specialist,advocate','C1'],
      ['underpassise','v','To make into underpass','tunnel,convert','C1'],
      ['underpassize','v','To make or become underpass','tunnel,transform','C1'],
      ['antiunderpass','adj','Opposed to underpass','against,opposing','C1'],
      ['nonunderpass','adj','Not involving underpass','without,lacking','B2'],
      ['preunderpass','n','Before underpass','preceding,prior','C1'],
      ['postunderpass','n','After underpass','following,subsequent','C1'],
      ['subunderpass','n','A subdivision of underpass','subset,branch','C1'],
      ['multiunderpass','adj','Involving many underpasss','multiple,several','C1'],
      ['interunderpass','adj','Between underpasss','cross,between','C1'],
      ['bottleneckal','adj','Relating to bottleneck','chokepoint-related,pertaining to','B2'],
      ['bottleneckic','adj','Of or relating to bottleneck','chokepoint-based,characteristic','B2'],
      ['bottleneckous','adj','Full of bottleneck','chokepoint-filled,abundant','C1'],
      ['bottleneckful','adj','Full of bottleneck','chokepoint-rich,abounding','B2'],
      ['bottleneckless','adj','Without bottleneck','lacking,without','B2'],
      ['bottleneckism','n','The ideology of bottleneck','chokepoint ideology,doctrine','C1'],
      ['bottleneckist','n','A person focused on bottleneck','chokepoint specialist,advocate','C1'],
      ['bottleneckise','v','To make into bottleneck','chokepoint,convert','C1'],
      ['bottleneckize','v','To make or become bottleneck','chokepoint,transform','C1'],
      ['antibottleneck','adj','Opposed to bottleneck','against,opposing','C1'],
      ['nonbottleneck','adj','Not involving bottleneck','without,lacking','B2'],
      ['prebottleneck','n','Before bottleneck','preceding,prior','C1'],
      ['postbottleneck','n','After bottleneck','following,subsequent','C1'],
      ['subbottleneck','n','A subdivision of bottleneck','subset,branch','C1'],
      ['multibottleneck','adj','Involving many bottlenecks','multiple,several','C1'],
      ['interbottleneck','adj','Between bottlenecks','cross,between','C1'],
      ['gridlockedly','adv','In a gridlocked manner','jammed way','B2'],
      ['gridlockedness','n','The quality of being gridlocked','jammed quality','B2'],
      ['gridlockedity','n','The state of being gridlocked','jammed condition','C1'],
      ['ungridlocked','adj','Not gridlocked','not jammed','B2'],
      ['ingridlocked','adj','Not gridlocked','not jammed','C1'],
      ['nongridlocked','adj','Not gridlocked','not jammed','B2'],
      ['semigridlocked','adj','Partially gridlocked','partly jammed','C1'],
      ['overgridlocked','adj','Excessively gridlocked','too jammed','C1'],
      ['ultragridlocked','adj','Extremely gridlocked','very jammed','C1'],
      ['fuel-efficient','adj','Using little fuel to operate','economical,low-consumption,green','B2'],
      ['fuel-efficiently','adv','In a fuel-efficient manner','economical way','B2'],
      ['fuel-efficientness','n','The quality of being fuel-efficient','economical quality','B2'],
      ['fuel-efficientity','n','The state of being fuel-efficient','economical condition','C1'],
    ],
  },
  collocations: {}
};
