// Auto-generated vocab boost group 51
module.exports = {
  vocab: {
    society: [
      ['ultraheterogeneous','adj','Extremely heterogeneous','very mixed','C2'],
      ['demographical','adj','Relating to demographic','population data-related,pertaining to','B2'],
      ['demographicic','adj','Of or relating to demographic','population data-based,characteristic','B2'],
      ['demographicous','adj','Full of demographic','population data-filled,abundant','C1'],
      ['demographicful','adj','Full of demographic','population data-rich,abounding','B2'],
      ['demographicless','adj','Without demographic','lacking,without','B2'],
      ['demographicism','n','The ideology of demographic','population data ideology,doctrine','C1'],
      ['demographicist','n','A person focused on demographic','population data specialist,advocate','C1'],
      ['demographicise','v','To make into demographic','population data,convert','C1'],
      ['demographicize','v','To make or become demographic','population data,transform','C1'],
      ['antidemographic','adj','Opposed to demographic','against,opposing','C1'],
      ['nondemographic','adj','Not involving demographic','without,lacking','B2'],
      ['predemographic','n','Before demographic','preceding,prior','C1'],
      ['postdemographic','n','After demographic','following,subsequent','C1'],
      ['subdemographic','n','A subdivision of demographic','subset,branch','C1'],
      ['multidemographic','adj','Involving many demographics','multiple,several','C1'],
      ['interdemographic','adj','Between demographics','cross,between','C1'],
      ['diasporaic','adj','Of or relating to diaspora','exile-based,characteristic','C1'],
      ['diasporaous','adj','Full of diaspora','exile-filled,abundant','C2'],
      ['diasporaful','adj','Full of diaspora','exile-rich,abounding','C1'],
      ['diasporaless','adj','Without diaspora','lacking,without','C1'],
      ['diasporaism','n','The ideology of diaspora','exile ideology,doctrine','C2'],
      ['diasporaist','n','A person focused on diaspora','exile specialist,advocate','C2'],
      ['diasporaise','v','To make into diaspora','exile,convert','C2'],
      ['diasporaize','v','To make or become diaspora','exile,transform','C2'],
      ['antidiaspora','adj','Opposed to diaspora','against,opposing','C2'],
      ['nondiaspora','adj','Not involving diaspora','without,lacking','C1'],
      ['prediaspora','n','Before diaspora','preceding,prior','C2'],
      ['postdiaspora','n','After diaspora','following,subsequent','C2'],
      ['subdiaspora','n','A subdivision of diaspora','subset,branch','C2'],
      ['multidiaspora','adj','Involving many diasporas','multiple,several','C2'],
      ['interdiaspora','adj','Between diasporas','cross,between','C2'],
      ['proletariatal','adj','Relating to proletariat','workers-related,pertaining to','C1'],
      ['proletariatic','adj','Of or relating to proletariat','workers-based,characteristic','C1'],
      ['proletariatous','adj','Full of proletariat','workers-filled,abundant','C2'],
      ['proletariatful','adj','Full of proletariat','workers-rich,abounding','C1'],
      ['proletariatless','adj','Without proletariat','lacking,without','C1'],
      ['proletariatism','n','The ideology of proletariat','workers ideology,doctrine','C2'],
      ['proletariatist','n','A person focused on proletariat','workers specialist,advocate','C2'],
      ['proletariatise','v','To make into proletariat','workers,convert','C2'],
      ['proletariatize','v','To make or become proletariat','workers,transform','C2'],
      ['antiproletariat','adj','Opposed to proletariat','against,opposing','C2'],
      ['nonproletariat','adj','Not involving proletariat','without,lacking','C1'],
      ['preproletariat','n','Before proletariat','preceding,prior','C2'],
      ['postproletariat','n','After proletariat','following,subsequent','C2'],
      ['subproletariat','n','A subdivision of proletariat','subset,branch','C2'],
      ['multiproletariat','adj','Involving many proletariats','multiple,several','C2'],
      ['interproletariat','adj','Between proletariats','cross,between','C2'],
      ['bourgeoisie','n','The middle class','middle class,establishment,elite','C1'],
      ['bourgeoisieal','adj','Relating to bourgeoisie','middle class-related,pertaining to','C1'],
      ['bourgeoisieic','adj','Of or relating to bourgeoisie','middle class-based,characteristic','C1'],
      ['bourgeoisieous','adj','Full of bourgeoisie','middle class-filled,abundant','C2'],
      ['bourgeoisieful','adj','Full of bourgeoisie','middle class-rich,abounding','C1'],
      ['bourgeoisieless','adj','Without bourgeoisie','lacking,without','C1'],
      ['bourgeoisieism','n','The ideology of bourgeoisie','middle class ideology,doctrine','C2'],
      ['bourgeoisieist','n','A person focused on bourgeoisie','middle class specialist,advocate','C2'],
      ['bourgeoisieise','v','To make into bourgeoisie','middle class,convert','C2'],
      ['bourgeoisieize','v','To make or become bourgeoisie','middle class,transform','C2'],
      ['antibourgeoisie','adj','Opposed to bourgeoisie','against,opposing','C2'],
      ['nonbourgeoisie','adj','Not involving bourgeoisie','without,lacking','C1'],
      ['prebourgeoisie','n','Before bourgeoisie','preceding,prior','C2'],
      ['postbourgeoisie','n','After bourgeoisie','following,subsequent','C2'],
      ['subbourgeoisie','n','A subdivision of bourgeoisie','subset,branch','C2'],
      ['multibourgeoisie','adj','Involving many bourgeoisies','multiple,several','C2'],
      ['interbourgeoisie','adj','Between bourgeoisies','cross,between','C2'],
      ['intelligentsia','n','Intellectual or cultural elite','intellectuals,thinkers,scholars','C1'],
      ['intelligentsiaal','adj','Relating to intelligentsia','intellectuals-related,pertaining to','C1'],
      ['intelligentsiaic','adj','Of or relating to intelligentsia','intellectuals-based,characteristic','C1'],
      ['intelligentsiaous','adj','Full of intelligentsia','intellectuals-filled,abundant','C2'],
      ['intelligentsiaful','adj','Full of intelligentsia','intellectuals-rich,abounding','C1'],
      ['intelligentsialess','adj','Without intelligentsia','lacking,without','C1'],
      ['intelligentsiaism','n','The ideology of intelligentsia','intellectuals ideology,doctrine','C2'],
      ['intelligentsiaist','n','A person focused on intelligentsia','intellectuals specialist,advocate','C2'],
      ['intelligentsiaise','v','To make into intelligentsia','intellectuals,convert','C2'],
      ['intelligentsiaize','v','To make or become intelligentsia','intellectuals,transform','C2'],
      ['antiintelligentsia','adj','Opposed to intelligentsia','against,opposing','C2'],
      ['nonintelligentsia','adj','Not involving intelligentsia','without,lacking','C1'],
      ['preintelligentsia','n','Before intelligentsia','preceding,prior','C2'],
      ['postintelligentsia','n','After intelligentsia','following,subsequent','C2'],
      ['subintelligentsia','n','A subdivision of intelligentsia','subset,branch','C2'],
      ['multiintelligentsia','adj','Involving many intelligentsias','multiple,several','C2'],
      ['interintelligentsia','adj','Between intelligentsias','cross,between','C2'],
      ['bureaucracyic','adj','Of or relating to bureaucracy','administration-based,characteristic','B2'],
      ['bureaucracyous','adj','Full of bureaucracy','administration-filled,abundant','C1'],
      ['bureaucracyful','adj','Full of bureaucracy','administration-rich,abounding','B2'],
      ['bureaucracyless','adj','Without bureaucracy','lacking,without','B2'],
      ['bureaucracyism','n','The ideology of bureaucracy','administration ideology,doctrine','C1'],
      ['bureaucracyist','n','A person focused on bureaucracy','administration specialist,advocate','C1'],
      ['bureaucracyise','v','To make into bureaucracy','administration,convert','C1'],
      ['bureaucracyize','v','To make or become bureaucracy','administration,transform','C1'],
      ['antibureaucracy','adj','Opposed to bureaucracy','against,opposing','C1'],
      ['nonbureaucracy','adj','Not involving bureaucracy','without,lacking','B2'],
      ['prebureaucracy','n','Before bureaucracy','preceding,prior','C1'],
      ['postbureaucracy','n','After bureaucracy','following,subsequent','C1'],
      ['subbureaucracy','n','A subdivision of bureaucracy','subset,branch','C1'],
      ['multibureaucracy','adj','Involving many bureaucracys','multiple,several','C1'],
      ['interbureaucracy','adj','Between bureaucracys','cross,between','C1'],
      ['philanthropyic','adj','Of or relating to philanthropy','charity-based,characteristic','C1'],
      ['philanthropyous','adj','Full of philanthropy','charity-filled,abundant','C2'],
      ['philanthropyful','adj','Full of philanthropy','charity-rich,abounding','C1'],
      ['philanthropyless','adj','Without philanthropy','lacking,without','C1'],
      ['philanthropyism','n','The ideology of philanthropy','charity ideology,doctrine','C2'],
      ['philanthropyist','n','A person focused on philanthropy','charity specialist,advocate','C2'],
      ['philanthropyise','v','To make into philanthropy','charity,convert','C2'],
      ['philanthropyize','v','To make or become philanthropy','charity,transform','C2'],
      ['antiphilanthropy','adj','Opposed to philanthropy','against,opposing','C2'],
      ['nonphilanthropy','adj','Not involving philanthropy','without,lacking','C1'],
      ['prephilanthropy','n','Before philanthropy','preceding,prior','C2'],
      ['postphilanthropy','n','After philanthropy','following,subsequent','C2'],
      ['subphilanthropy','n','A subdivision of philanthropy','subset,branch','C2'],
      ['multiphilanthropy','adj','Involving many philanthropys','multiple,several','C2'],
      ['interphilanthropy','adj','Between philanthropys','cross,between','C2'],
      ['altruismic','adj','Of or relating to altruism','selflessness-based,characteristic','C1'],
      ['altruismous','adj','Full of altruism','selflessness-filled,abundant','C2'],
      ['altruismful','adj','Full of altruism','selflessness-rich,abounding','C1'],
      ['altruismless','adj','Without altruism','lacking,without','C1'],
      ['altruismism','n','The ideology of altruism','selflessness ideology,doctrine','C2'],
      ['altruismist','n','A person focused on altruism','selflessness specialist,advocate','C2'],
      ['altruismise','v','To make into altruism','selflessness,convert','C2'],
      ['altruismize','v','To make or become altruism','selflessness,transform','C2'],
      ['antialtruism','adj','Opposed to altruism','against,opposing','C2'],
      ['nonaltruism','adj','Not involving altruism','without,lacking','C1'],
      ['prealtruism','n','Before altruism','preceding,prior','C2'],
      ['postaltruism','n','After altruism','following,subsequent','C2'],
      ['subaltruism','n','A subdivision of altruism','subset,branch','C2'],
      ['multialtruism','adj','Involving many altruisms','multiple,several','C2'],
      ['interaltruism','adj','Between altruisms','cross,between','C2'],
      ['nepotismic','adj','Of or relating to nepotism','favouritism-based,characteristic','C1'],
      ['nepotismous','adj','Full of nepotism','favouritism-filled,abundant','C2'],
      ['nepotismful','adj','Full of nepotism','favouritism-rich,abounding','C1'],
      ['nepotismless','adj','Without nepotism','lacking,without','C1'],
      ['nepotismism','n','The ideology of nepotism','favouritism ideology,doctrine','C2'],
      ['nepotismist','n','A person focused on nepotism','favouritism specialist,advocate','C2'],
      ['nepotismise','v','To make into nepotism','favouritism,convert','C2'],
      ['nepotismize','v','To make or become nepotism','favouritism,transform','C2'],
      ['antinepotism','adj','Opposed to nepotism','against,opposing','C2'],
      ['nonnepotism','adj','Not involving nepotism','without,lacking','C1'],
      ['prenepotism','n','Before nepotism','preceding,prior','C2'],
      ['postnepotism','n','After nepotism','following,subsequent','C2'],
      ['subnepotism','n','A subdivision of nepotism','subset,branch','C2'],
      ['multinepotism','adj','Involving many nepotisms','multiple,several','C2'],
      ['internepotism','adj','Between nepotisms','cross,between','C2'],
      ['gentrificationic','adj','Of or relating to gentrification','urban renewal-based,characteristic','C1'],
      ['gentrificationous','adj','Full of gentrification','urban renewal-filled,abundant','C2'],
      ['gentrificationful','adj','Full of gentrification','urban renewal-rich,abounding','C1'],
      ['gentrificationless','adj','Without gentrification','lacking,without','C1'],
      ['gentrificationism','n','The ideology of gentrification','urban renewal ideology,doctrine','C2'],
      ['gentrificationist','n','A person focused on gentrification','urban renewal specialist,advocate','C2'],
      ['gentrificationise','v','To make into gentrification','urban renewal,convert','C2'],
      ['gentrificationize','v','To make or become gentrification','urban renewal,transform','C2'],
      ['antigentrification','adj','Opposed to gentrification','against,opposing','C2'],
      ['nongentrification','adj','Not involving gentrification','without,lacking','C1'],
      ['pregentrification','n','Before gentrification','preceding,prior','C2'],
      ['postgentrification','n','After gentrification','following,subsequent','C2'],
      ['subgentrification','n','A subdivision of gentrification','subset,branch','C2'],
      ['multigentrification','adj','Involving many gentrifications','multiple,several','C2'],
      ['intergentrification','adj','Between gentrifications','cross,between','C2'],
      ['urbanizational','adj','Relating to urbanization','city growth-related,pertaining to','B2'],
      ['urbanizationic','adj','Of or relating to urbanization','city growth-based,characteristic','B2'],
      ['urbanizationous','adj','Full of urbanization','city growth-filled,abundant','C1'],
      ['urbanizationful','adj','Full of urbanization','city growth-rich,abounding','B2'],
      ['urbanizationless','adj','Without urbanization','lacking,without','B2'],
      ['urbanizationism','n','The ideology of urbanization','city growth ideology,doctrine','C1'],
      ['urbanizationist','n','A person focused on urbanization','city growth specialist,advocate','C1'],
      ['urbanizationise','v','To make into urbanization','city growth,convert','C1'],
      ['urbanizationize','v','To make or become urbanization','city growth,transform','C1'],
      ['antiurbanization','adj','Opposed to urbanization','against,opposing','C1'],
      ['nonurbanization','adj','Not involving urbanization','without,lacking','B2'],
      ['preurbanization','n','Before urbanization','preceding,prior','C1'],
      ['posturbanization','n','After urbanization','following,subsequent','C1'],
      ['suburbanization','n','A subdivision of urbanization','subset,branch','C1'],
      ['multiurbanization','adj','Involving many urbanizations','multiple,several','C1'],
      ['interurbanization','adj','Between urbanizations','cross,between','C1'],
      ['devolutionic','adj','Of or relating to devolution','decentralization-based,characteristic','C1'],
      ['devolutionous','adj','Full of devolution','decentralization-filled,abundant','C2'],
      ['devolutionful','adj','Full of devolution','decentralization-rich,abounding','C1'],
      ['devolutionless','adj','Without devolution','lacking,without','C1'],
      ['devolutionism','n','The ideology of devolution','decentralization ideology,doctrine','C2'],
      ['devolutionist','n','A person focused on devolution','decentralization specialist,advocate','C2'],
      ['devolutionise','v','To make into devolution','decentralization,convert','C2'],
      ['devolutionize','v','To make or become devolution','decentralization,transform','C2'],
      ['antidevolution','adj','Opposed to devolution','against,opposing','C2'],
      ['nondevolution','adj','Not involving devolution','without,lacking','C1'],
      ['predevolution','n','Before devolution','preceding,prior','C2'],
      ['postdevolution','n','After devolution','following,subsequent','C2'],
      ['subdevolution','n','A subdivision of devolution','subset,branch','C2'],
      ['multidevolution','adj','Involving many devolutions','multiple,several','C2'],
      ['interdevolution','adj','Between devolutions','cross,between','C2'],
      ['social mobility','n','Ability to move between social classes','class movement,status change','B2'],
      ['social mobilityal','adj','Relating to social mobility','class movement-related,pertaining to','B2'],
      ['social mobilityic','adj','Of or relating to social mobility','class movement-based,characteristic','B2'],
      ['social mobilityous','adj','Full of social mobility','class movement-filled,abundant','C1'],
      ['social mobilityful','adj','Full of social mobility','class movement-rich,abounding','B2'],
      ['social mobilityless','adj','Without social mobility','lacking,without','B2'],
      ['social mobilityism','n','The ideology of social mobility','class movement ideology,doctrine','C1'],
      ['social mobilityist','n','A person focused on social mobility','class movement specialist,advocate','C1'],
      ['social mobilityise','v','To make into social mobility','class movement,convert','C1'],
      ['social mobilityize','v','To make or become social mobility','class movement,transform','C1'],
      ['antisocial mobility','adj','Opposed to social mobility','against,opposing','C1'],
      ['nonsocial mobility','adj','Not involving social mobility','without,lacking','B2'],
      ['presocial mobility','n','Before social mobility','preceding,prior','C1'],
      ['postsocial mobility','n','After social mobility','following,subsequent','C1'],
      ['subsocial mobility','n','A subdivision of social mobility','subset,branch','C1'],
      ['multisocial mobility','adj','Involving many social mobilitys','multiple,several','C1'],
      ['intersocial mobility','adj','Between social mobilitys','cross,between','C1'],
      ['civil liberties','n','Rights protecting individual freedom','freedoms,human rights,civil rights','B2'],
      ['civil libertiesal','adj','Relating to civil liberties','freedoms-related,pertaining to','B2'],
      ['civil libertiesic','adj','Of or relating to civil liberties','freedoms-based,characteristic','B2'],
      ['civil libertiesous','adj','Full of civil liberties','freedoms-filled,abundant','C1'],
      ['civil libertiesful','adj','Full of civil liberties','freedoms-rich,abounding','B2'],
      ['civil libertiesless','adj','Without civil liberties','lacking,without','B2'],
      ['civil libertiesism','n','The ideology of civil liberties','freedoms ideology,doctrine','C1'],
      ['civil libertiesist','n','A person focused on civil liberties','freedoms specialist,advocate','C1'],
      ['civil libertiesise','v','To make into civil liberties','freedoms,convert','C1'],
      ['civil libertiesize','v','To make or become civil liberties','freedoms,transform','C1'],
      ['anticivil liberties','adj','Opposed to civil liberties','against,opposing','C1'],
      ['noncivil liberties','adj','Not involving civil liberties','without,lacking','B2'],
      ['precivil liberties','n','Before civil liberties','preceding,prior','C1'],
      ['postcivil liberties','n','After civil liberties','following,subsequent','C1'],
      ['subcivil liberties','n','A subdivision of civil liberties','subset,branch','C1'],
      ['multicivil liberties','adj','Involving many civil libertiess','multiple,several','C1'],
      ['intercivil liberties','adj','Between civil libertiess','cross,between','C1'],
      ['welfare state','n','Government providing social services','social security,safety net','B2'],
      ['welfare stateal','adj','Relating to welfare state','social security-related,pertaining to','B2'],
      ['welfare stateic','adj','Of or relating to welfare state','social security-based,characteristic','B2'],
      ['welfare stateous','adj','Full of welfare state','social security-filled,abundant','C1'],
      ['welfare stateful','adj','Full of welfare state','social security-rich,abounding','B2'],
      ['welfare stateless','adj','Without welfare state','lacking,without','B2'],
      ['welfare stateism','n','The ideology of welfare state','social security ideology,doctrine','C1'],
      ['welfare stateist','n','A person focused on welfare state','social security specialist,advocate','C1'],
      ['welfare stateise','v','To make into welfare state','social security,convert','C1'],
      ['welfare stateize','v','To make or become welfare state','social security,transform','C1'],
      ['antiwelfare state','adj','Opposed to welfare state','against,opposing','C1'],
      ['nonwelfare state','adj','Not involving welfare state','without,lacking','B2'],
      ['prewelfare state','n','Before welfare state','preceding,prior','C1'],
      ['postwelfare state','n','After welfare state','following,subsequent','C1'],
      ['subwelfare state','n','A subdivision of welfare state','subset,branch','C1'],
      ['multiwelfare state','adj','Involving many welfare states','multiple,several','C1'],
      ['interwelfare state','adj','Between welfare states','cross,between','C1'],
      ['peer pressureal','adj','Relating to peer pressure','social pressure-related,pertaining to','B1'],
      ['peer pressureic','adj','Of or relating to peer pressure','social pressure-based,characteristic','B1'],
      ['peer pressureous','adj','Full of peer pressure','social pressure-filled,abundant','B2'],
      ['peer pressureful','adj','Full of peer pressure','social pressure-rich,abounding','B1'],
      ['peer pressureless','adj','Without peer pressure','lacking,without','B1'],
      ['peer pressureism','n','The ideology of peer pressure','social pressure ideology,doctrine','B2'],
      ['peer pressureist','n','A person focused on peer pressure','social pressure specialist,advocate','B2'],
      ['peer pressureise','v','To make into peer pressure','social pressure,convert','B2'],
      ['peer pressureize','v','To make or become peer pressure','social pressure,transform','B2'],
      ['antipeer pressure','adj','Opposed to peer pressure','against,opposing','B2'],
      ['nonpeer pressure','adj','Not involving peer pressure','without,lacking','B1'],
    ],
  },
  collocations: {}
};
