module.exports = {
  vocab: {
    health: [
    ['prescriptional','adj','Relating to prescription','medication order-related','B1'],
    ['vaccineal','adj','Relating to vaccine','immunisation-related','B1'],
    ['infectional','adj','Relating to infection','contamination-related','B1'],
    ['therapyal','adj','Relating to therapy','rehabilitation-related','B1'],
    ['allergyal','adj','Relating to allergy','sensitivity-related','B1'],
    ['nutritional','adj','Relating to nutrition','diet-related','B1'],
    ['chronicly','adv','In a chronic manner','long-term way','B2'],
    ['chronicness','n','The quality of being chronic','long-term quality','C1'],
    ['unchronic','adj','Not chronic','not long-term','B2'],
    ['acutely','adv','In a acute manner','severe way','B2'],
    ['acuteness','n','The quality of being acute','severe quality','C1'],
    ['unacute','adj','Not acute','not severe','B2'],
    ['contagiously','adv','In a contagious manner','infectious way','B2'],
    ['contagiousness','n','The quality of being contagious','infectious quality','C1'],
    ['uncontagious','adj','Not contagious','not infectious','B2'],
    ['rehabilitational','adj','Relating to rehabilitation','recovery-related','B2'],
    ['prognosisal','adj','Relating to prognosis','outlook-related','B2'],
    ['epidemical','adj','Relating to epidemic','outbreak-related','B2'],
    ['immunologyal','adj','Relating to immunology','immune science-related','B2'],
    ['metabolismal','adj','Relating to metabolism','body chemistry-related','B2'],
    ['holisticly','adv','In a holistic manner','comprehensive way','B2'],
    ['holisticness','n','The quality of being holistic','comprehensive quality','C1'],
    ['unholistic','adj','Not holistic','not comprehensive','B2'],
    ['palliatively','adv','In a palliative manner','soothing way','C1'],
    ['palliativeness','n','The quality of being palliative','soothing quality','C2'],
    ['unpalliative','adj','Not palliative','not soothing','C1'],
    ['pathologyal','adj','Relating to pathology','disease science-related','C1'],
    ['epidemiologyal','adj','Relating to epidemiology','disease tracking-related','C1'],
    ['aetiologyal','adj','Relating to aetiology','causation-related','C1'],
    ['comorbidityal','adj','Relating to comorbidity','co-occurring illness-related','C1'],
    ['iatrogenicly','adv','In a iatrogenic manner','treatment-induced way','C2'],
    ['iatrogenicness','n','The quality of being iatrogenic','treatment-induced quality','C2'],
    ['uniatrogenic','adj','Not iatrogenic','not treatment-induced','C2'],
    ['nosocomially','adv','In a nosocomial manner','hospital-acquired way','C2'],
    ['nosocomialness','n','The quality of being nosocomial','hospital-acquired quality','C2'],
    ['unnosocomial','adj','Not nosocomial','not hospital-acquired','C2'],
    ['idiopathicly','adv','In a idiopathic manner','unexplained way','C2'],
    ['idiopathicness','n','The quality of being idiopathic','unexplained quality','C2'],
    ['unidiopathic','adj','Not idiopathic','not unexplained','C2'],
    ['bandageal','adj','Relating to bandage','dressing-related','A2'],
    ['coughation','n','The act or process of coughing','hack process,splutter process,wheeze process','A2'],
    ['cougher','n','A person who coughs','hack person,splutter person,wheeze person','B1'],
    ['coughable','adj','Able to be coughd','hack,possible','B1'],
    ['coughing','n','The process of coughing something','hack activity','A2'],
    ['feveral','adj','Relating to fever','high temperature-related','A2'],
    ['pharmacyal','adj','Relating to pharmacy','chemist-related','A2'],
    ['ambulanceal','adj','Relating to ambulance','emergency vehicle-related','A2'],
    ['physiotherapyal','adj','Relating to physiotherapy','physical therapy-related','B1'],
    ['anaesthetical','adj','Relating to anaesthetic','numbing agent-related','B1'],
    ['cholesterolal','adj','Relating to cholesterol','blood fat-related','B1'],
    ['intravenously','adv','In a intravenous manner','IV way','B2'],
    ['intravenousness','n','The quality of being intravenous','IV quality','C1'],
    ['unintravenous','adj','Not intravenous','not IV','B2'],
    ['biopsyal','adj','Relating to biopsy','sample-related','B2'],
    ['triageal','adj','Relating to triage','sorting-related','B2'],
    ['oncologyal','adj','Relating to oncology','cancer science-related','C1'],
    ['haematologyal','adj','Relating to haematology','blood science-related','C1'],
    ['neuropathyal','adj','Relating to neuropathy','nerve damage-related','C1'],
    ['prophylaxisal','adj','Relating to prophylaxis','prevention-related','C1'],
    ['septicaemiaal','adj','Relating to septicaemia','blood poisoning-related','C1'],
    ['autoimmunely','adv','In a autoimmune manner','self-attacking way','B2'],
    ['autoimmuneness','n','The quality of being autoimmune','self-attacking quality','C1'],
    ['unautoimmune','adj','Not autoimmune','not self-attacking','B2'],
    ['benignly','adv','In a benign manner','non-malignant way','B2'],
    ['benignness','n','The quality of being benign','non-malignant quality','C1'],
    ['unbenign','adj','Not benign','not non-malignant','B2'],
    ['malignantly','adv','In a malignant manner','cancerous way','B2'],
    ['malignantness','n','The quality of being malignant','cancerous quality','C1'],
    ['unmalignant','adj','Not malignant','not cancerous','B2'],
    ['asymptomaticly','adv','In a asymptomatic manner','symptom-free way','C1'],
    ['asymptomaticness','n','The quality of being asymptomatic','symptom-free quality','C2'],
    ['unasymptomatic','adj','Not asymptomatic','not symptom-free','C1']
    ],
    environment: [
    ['sequestration','n','Capturing and storing carbon dioxide','carbon capture,CO2 storage','C1'],
    ['solar panel','n','A device converting sunlight to electricity','photovoltaic panel,sun panel','B1'],
    ['wind turbine','n','A machine generating electricity from wind','windmill,wind generator','B1'],
    ['keystone species','n','A species vital to its ecosystem','critical species,ecosystem anchor','B2'],
    ['rewilding','n','Restoring land to its natural state','ecological restoration,nature recovery','B2'],
    ['phytoremediation','n','Using plants to clean contaminated soil','plant cleanup,green remediation','C2'],
    ['ecocide','n','Large-scale destruction of the natural environment','environmental destruction,ecological crime','C1'],
    ['pollutional','adj','Relating to pollution','contamination-related','A2'],
    ['recyclation','n','The act or process of recycling','reuse process,repurpose process,reprocess process','A2'],
    ['recycler','n','A person who recycles','reuse person,repurpose person,reprocess person','B1'],
    ['recyclable','adj','Able to be recycled','reuse,possible','B1'],
    ['recycling','n','The process of recycling something','reuse activity','A2'],
    ['forestal','adj','Relating to forest','woodland-related','A2'],
    ['riveral','adj','Relating to river','stream-related','A2'],
    ['weatheral','adj','Relating to weather','climate-related','A2'],
    ['climateal','adj','Relating to climate','weather pattern-related','A2'],
    ['natureal','adj','Relating to nature','environment-related','A2'],
    ['plantal','adj','Relating to plant','flora-related','A2'],
    ['animalal','adj','Relating to animal','creature-related','A2'],
    ['wasteal','adj','Relating to waste','rubbish-related','A2'],
    ['conservational','adj','Relating to conservation','preservation-related','B1'],
    ['deforestational','adj','Relating to deforestation','logging-related','B1'],
    ['greenhouseal','adj','Relating to greenhouse','glasshouse-related','B1'],
    ['endangeredly','adv','In a endangered manner','threatened way','B1'],
    ['endangeredness','n','The quality of being endangered','threatened quality','B2'],
    ['unendangered','adj','Not endangered','not threatened','B1'],
    ['renewablely','adv','In a renewable manner','sustainable way','B1'],
    ['renewableness','n','The quality of being renewable','sustainable quality','B2'],
    ['unrenewable','adj','Not renewable','not sustainable','B1'],
    ['habitatal','adj','Relating to habitat','environment-related','B1'],
    ['erosional','adj','Relating to erosion','weathering-related','B1'],
    ['droughtal','adj','Relating to drought','dry spell-related','B1'],
    ['biodiversityal','adj','Relating to biodiversity','biological diversity-related','B2'],
    ['sustainabilityal','adj','Relating to sustainability','long-term viability-related','B2'],
    ['ecosystemal','adj','Relating to ecosystem','biome-related','B2'],
    ['emissionsal','adj','Relating to emissions','pollutants-related','B2'],
    ['desertificational','adj','Relating to desertification','land degradation-related','B2'],
    ['acidificational','adj','Relating to acidification','acid increase-related','B2'],
    ['reforestational','adj','Relating to reforestation','tree planting-related','B2'],
    ['permafrostal','adj','Relating to permafrost','frozen soil-related','B2'],
    ['microplastical','adj','Relating to microplastic','plastic debris-related','B2'],
    ['mitigational','adj','Relating to mitigation','reduction-related','B2'],
    ['anthropogenicly','adv','In a anthropogenic manner','human-made way','C1'],
    ['anthropogenicness','n','The quality of being anthropogenic','human-made quality','C2'],
    ['unanthropogenic','adj','Not anthropogenic','not human-made','C1'],
    ['bioremediational','adj','Relating to bioremediation','biological cleanup-related','C1'],
    ['sequestrational','adj','Relating to sequestration','carbon capture-related','C1'],
    ['albedoal','adj','Relating to albedo','reflectance-related','C2'],
    ['trophicly','adv','In a trophic manner','feeding-level way','C2'],
    ['trophicness','n','The quality of being trophic','feeding-level quality','C2'],
    ['untrophic','adj','Not trophic','not feeding-level','C2'],
    ['compostal','adj','Relating to compost','mulch-related','A2'],
    ['litteral','adj','Relating to litter','garbage-related','A2'],
    ['floodal','adj','Relating to flood','deluge-related','A2'],
    ['landfillal','adj','Relating to landfill','dump-related','B1'],
    ['smogal','adj','Relating to smog','haze-related','B1'],
    ['aquiferal','adj','Relating to aquifer','groundwater source-related','B2'],
    ['biomeal','adj','Relating to biome','ecological region-related','B2'],
    ['estuaryal','adj','Relating to estuary','river mouth-related','B2'],
    ['eutrophicational','adj','Relating to eutrophication','algal bloom-related','C1'],
    ['leachateal','adj','Relating to leachate','runoff-related','C1'],
    ['bioaccumulational','adj','Relating to bioaccumulation','toxin accumulation-related','C1'],
    ['rewildingal','adj','Relating to rewilding','ecological restoration-related','B2'],
    ['phytoremediational','adj','Relating to phytoremediation','plant cleanup-related','C2'],
    ['xeriscapingal','adj','Relating to xeriscaping','dry gardening-related','C2'],
    ['phenologyal','adj','Relating to phenology','nature timing-related','C2'],
    ['ecocideal','adj','Relating to ecocide','environmental destruction-related','C1']
    ],
    business: [
    ['marketing','n','Promoting and selling products','advertising,promotion,branding','B1'],
    ['amortise','v','To spread the cost over a period of time','depreciate,write off,allocate','C1'],
    ['disintermediate','v','To remove middlemen from a transaction','bypass,cut out,eliminate','C2']
    ],
  },
  collocations: {
  }
};
