module.exports = {
  vocab: {
    culture: [
    ['palimpsestal','adj','Relating to palimpsest','overwritten text-related','C2'],
    ['cosmogonyal','adj','Relating to cosmogony','creation myth-related','C2'],
    ['simulacrumal','adj','Relating to simulacrum','copy-related','C2'],
    ['zeitgeistal','adj','Relating to zeitgeist','spirit of the age-related','C1'],
    ['ethosal','adj','Relating to ethos','character-related','B2'],
    ['tableaual','adj','Relating to tableau','display-related','C1'],
    ['provenanceal','adj','Relating to provenance','source-related','C1'],
    ['kitschal','adj','Relating to kitsch','tackiness-related','C1']
    ],
    science: [
    ['measure','v','To determine the size or quantity','gauge,assess,quantify','A2'],
    ['empiricism','n','Knowledge based on observation and experiment','experimental method,evidence-based','B2'],
    ['quantum mechanics','n','Physics of subatomic particles','quantum physics,particle physics','C1'],
    ['epistemological','adj','Relating to the theory of knowledge','knowledge-theoretical,philosophical','C1'],
    ['ontological','adj','Relating to the nature of existence','existential,metaphysical,being-related','C2'],
    ['telescope','n','An instrument for viewing distant objects','spyglass,scope,optical tube','A2'],
    ['centrifuge','n','A machine separating substances by spinning','separator,spinner,rotator','B2'],
    ['spectrometer','n','A device measuring light wavelengths','spectrum analyser,light meter','B2'],
    ['chromatography','n','A technique for separating mixtures','separation method,analysis technique','C1'],
    ['stoichiometry','n','Calculating quantities in chemical reactions','reaction mathematics,chemical arithmetic','C1'],
    ['titration','n','A technique for determining concentration','volumetric analysis,quantitative test','C1'],
    ['isomer','n','A compound with the same formula but different structure','structural variant,molecular twin','C1'],
    ['valence','n','The combining power of an element','bonding capacity,chemical affinity','C1'],
    ['mutagenesis','n','The process of genetic mutation','gene alteration,DNA change','C2'],
    ['biosynthesis','n','The production of compounds by living organisms','biological creation,organic production','C1'],
    ['experimental','adj','Relating to experiment','trial-related','A2'],
    ['laboratoryal','adj','Relating to laboratory','lab-related','A2'],
    ['energyal','adj','Relating to energy','power-related','A2'],
    ['chemicalal','adj','Relating to chemical','compound-related','A2'],
    ['discoveration','n','The act or process of discovering','uncover process,detect process,identify process','A2'],
    ['discoverer','n','A person who discovers','uncover person,detect person,identify person','B1'],
    ['discoverable','adj','Able to be discoverd','uncover,possible','B1'],
    ['discovering','n','The process of discovering something','uncover activity','A2'],
    ['measuration','n','The act or process of measuring','gauge process,assess process,quantify process','A2'],
    ['measurer','n','A person who measures','gauge person,assess person,quantify person','B1'],
    ['measurable','adj','Able to be measured','gauge,possible','B1'],
    ['measuring','n','The process of measuring something','gauge activity','A2'],
    ['hypothesisal','adj','Relating to hypothesis','theory-related','B1'],
    ['variableal','adj','Relating to variable','factor-related','B1'],
    ['organismal','adj','Relating to organism','creature-related','B1'],
    ['moleculeal','adj','Relating to molecule','particle-related','B1'],
    ['cellal','adj','Relating to cell','biological unit-related','B1'],
    ['gravityal','adj','Relating to gravity','gravitational pull-related','B1'],
    ['evolutional','adj','Relating to evolution','adaptation-related','B1'],
    ['geneal','adj','Relating to gene','hereditary unit-related','B1'],
    ['photosynthesisal','adj','Relating to photosynthesis','light conversion-related','B2'],
    ['catalystal','adj','Relating to catalyst','accelerator-related','B2'],
    ['genomeal','adj','Relating to genome','genetic blueprint-related','B2'],
    ['entropyal','adj','Relating to entropy','randomness-related','B2'],
    ['isotopeal','adj','Relating to isotope','atomic variant-related','B2'],
    ['paradigmal','adj','Relating to paradigm','framework-related','B2'],
    ['empiricismal','adj','Relating to empiricism','experimental method-related','B2'],
    ['thermodynamicsal','adj','Relating to thermodynamics','heat science-related','C1'],
    ['epistemologically','adv','In a epistemological manner','knowledge-theoretical way','C1'],
    ['epistemologicalness','n','The quality of being epistemological','knowledge-theoretical quality','C2'],
    ['unepistemological','adj','Not epistemological','not knowledge-theoretical','C1'],
    ['falsifiabilityal','adj','Relating to falsifiability','testability-related','C1'],
    ['abiogenesisal','adj','Relating to abiogenesis','spontaneous generation-related','C2'],
    ['ontologically','adv','In a ontological manner','existential way','C2'],
    ['ontologicalness','n','The quality of being ontological','existential quality','C2'],
    ['unontological','adj','Not ontological','not existential','C2'],
    ['microscopeal','adj','Relating to microscope','magnifier-related','A2'],
    ['telescopeal','adj','Relating to telescope','spyglass-related','A2'],
    ['fossilal','adj','Relating to fossil','relic-related','B1'],
    ['nucleusal','adj','Relating to nucleus','core-related','B1'],
    ['specimenal','adj','Relating to specimen','sample-related','B1'],
    ['centrifugeal','adj','Relating to centrifuge','separator-related','B2'],
    ['spectrometeral','adj','Relating to spectrometer','spectrum analyser-related','B2'],
    ['allotropeal','adj','Relating to allotrope','variant-related','C1'],
    ['chromatographyal','adj','Relating to chromatography','separation method-related','C1'],
    ['stoichiometryal','adj','Relating to stoichiometry','reaction mathematics-related','C1'],
    ['reagental','adj','Relating to reagent','chemical-related','B2'],
    ['precipitateal','adj','Relating to precipitate','deposit-related','B2'],
    ['titrational','adj','Relating to titration','volumetric analysis-related','C1'],
    ['isomeral','adj','Relating to isomer','structural variant-related','C1'],
    ['valenceal','adj','Relating to valence','bonding capacity-related','C1'],
    ['mutagenesisal','adj','Relating to mutagenesis','gene alteration-related','C2'],
    ['epigeneticsal','adj','Relating to epigenetics','gene regulation-related','C1'],
    ['proteomicsal','adj','Relating to proteomics','protein science-related','C2'],
    ['phylogeneticsal','adj','Relating to phylogenetics','tree of life-related','C2'],
    ['biosynthesisal','adj','Relating to biosynthesis','biological creation-related','C1']
    ],
    crime: [
    ['thief','n','A person who steals','robber,burglar,criminal','A2'],
    ['deterrence','n','Discouraging crime through punishment','prevention,disincentive,dissuasion','B2'],
    ['tort','n','A wrongful act leading to civil liability','civil wrong,legal injury','C2'],
    ['plea bargain','n','Negotiating a lesser charge for a guilty plea','deal,negotiated sentence','C1'],
    ['mitigating circumstance','n','A factor reducing the severity of an offence','extenuating factor,lessening condition','C1'],
    ['litigate','v','To take a dispute to court','sue,prosecute,bring legal action','C1'],
    ['policeal','adj','Relating to police','law enforcement-related','A2'],
    ['thiefal','adj','Relating to thief','robber-related','A2'],
    ['stealation','n','The act or process of stealing','rob process,pilfer process,take process','A2'],
    ['stealer','n','A person who steals','rob person,pilfer person,take person','B1'],
    ['stealable','adj','Able to be steald','rob,possible','B1'],
    ['stealing','n','The process of stealing something','rob activity','A2'],
    ['prisonal','adj','Relating to prison','jail-related','A2'],
    ['lawal','adj','Relating to law','legislation-related','A2'],
    ['safely','adv','In a safe manner','secure way','A2'],
    ['safeness','n','The quality of being safe','secure quality','B1'],
    ['unsafe','adj','Not safe','not secure','A2'],
    ['judgeal','adj','Relating to judge','magistrate-related','B1'],
    ['trialal','adj','Relating to trial','hearing-related','B1'],
    ['evidenceal','adj','Relating to evidence','proof-related','B1'],
    ['witnessal','adj','Relating to witness','observer-related','B1'],
    ['sentenceal','adj','Relating to sentence','penalty-related','B1'],
    ['victimal','adj','Relating to victim','sufferer-related','B1'],
    ['suspectal','adj','Relating to suspect','accused-related','B1'],
    ['arrestation','n','The act or process of arresting','detain process,apprehend process,capture process','B1'],
    ['arrester','n','A person who arrests','detain person,apprehend person,capture person','B2'],
    ['arrestable','adj','Able to be arrestd','detain,possible','B2'],
    ['arresting','n','The process of arresting something','detain activity','B1'],
    ['fraudal','adj','Relating to fraud','scam-related','B2'],
    ['cybercrimeal','adj','Relating to cybercrime','hacking-related','B2'],
    ['prosecutional','adj','Relating to prosecution','legal proceeding-related','B2'],
    ['deterrenceal','adj','Relating to deterrence','prevention-related','B2'],
    ['recidivismal','adj','Relating to recidivism','repeat offending-related','B2'],
    ['forensicly','adv','In a forensic manner','investigative way','B2'],
    ['forensicness','n','The quality of being forensic','investigative quality','C1'],
    ['unforensic','adj','Not forensic','not investigative','B2'],
    ['jurisdictional','adj','Relating to jurisdiction','authority-related','C1'],
    ['jurisprudenceal','adj','Relating to jurisprudence','legal theory-related','C1'],
    ['extraditional','adj','Relating to extradition','handover-related','C1'],
    ['malfeasanceal','adj','Relating to malfeasance','misconduct-related','C2'],
    ['tortal','adj','Relating to tort','civil wrong-related','C2'],
    ['fineal','adj','Relating to fine','penalty-related','A2'],
    ['handcuffsal','adj','Relating to handcuffs','cuffs-related','A2'],
    ['burglaryal','adj','Relating to burglary','break-in-related','B1'],
    ['arsonal','adj','Relating to arson','fire-raising-related','B1'],
    ['vandalismal','adj','Relating to vandalism','defacement-related','B1'],
    ['accompliceal','adj','Relating to accomplice','partner-related','B2'],
    ['extortional','adj','Relating to extortion','blackmail-related','B2'],
    ['perjuryal','adj','Relating to perjury','false testimony-related','B2'],
    ['embezzlemental','adj','Relating to embezzlement','misappropriation-related','B2'],
    ['paroleal','adj','Relating to parole','conditional release-related','B2'],
    ['white-collarly','adv','In a white-collar manner','corporate way','B2'],
    ['white-collarness','n','The quality of being white-collar','corporate quality','C1'],
    ['unwhite-collar','adj','Not white-collar','not corporate','B2'],
    ['premeditatedly','adv','In a premeditated manner','deliberate way','B2'],
    ['premeditatedness','n','The quality of being premeditated','deliberate quality','C1'],
    ['unpremeditated','adj','Not premeditated','not deliberate','B2'],
    ['incarceratation','n','The act or process of incarcerating','jail process,lock up process,detain process','C1'],
    ['incarcerater','n','A person who incarcerates','jail person,lock up person,detain person','C2'],
    ['incarceratable','adj','Able to be incarcerated','jail,possible','C2'],
    ['incarcerating','n','The process of incarcerating something','jail activity','C1'],
    ['adjudicatation','n','The act or process of adjudicating','judge process,rule process,decide process','C1'],
    ['adjudicater','n','A person who adjudicates','judge person,rule person,decide person','C2']
    ],
  },
  collocations: {
  }
};
