// Auto-generated vocab boost group 75
module.exports = {
  vocab: {
    food: [
      ['dehydratment','n','The result of dehydrating','dry outcome','B2'],
      ['dehydratance','n','The state of dehydrating','dry state','B2'],
      ['dehydratence','n','The quality of dehydrating','dry quality','B2'],
      ['dehydratal','n','An act of dehydrating','dry event','C1'],
      ['dehydrater','n','One who dehydrates','dry person','B2'],
      ['dehydrator','n','One who dehydrates','dry agent','B2'],
      ['dehydratee','n','One who is dehydrated','dry recipient','C1'],
      ['dehydratable','adj','Capable of being dehydrated','dry,possible','C1'],
      ['dehydratible','adj','Able to be dehydrated','dry,feasible','C1'],
      ['dehydrative','adj','Tending to dehydrate','dry,active','B2'],
      ['dehydrating','adj','Currently dehydrating','dry,ongoing','B2'],
      ['dehydrated','adj','Having been dehydrated','dry,completed','B2'],
      ['redehydrate','v','To dehydrate again','dry again,repeat','B2'],
      ['undehydrate','v','To reverse dehydrating','reverse,undo','C1'],
      ['overdehydrate','v','To dehydrate excessively','excess,too much','C1'],
      ['underdehydrate','v','To dehydrate insufficiently','insufficient,inadequate','C1'],
      ['misdehydrate','v','To dehydrate incorrectly','wrongly,incorrectly','C1'],
      ['predehydrate','v','To dehydrate beforehand','before,in advance','C1'],
      ['codehydrate','v','To dehydrate together','jointly,together','C1'],
      ['redehydratation','n','The act of dehydrating again','re-dry','C1'],
      ['overdehydratation','n','Excessive dehydrating','excess dry','C1'],
      ['organicity','n','The state of being organic','natural condition','B2'],
      ['inorganic','adj','Not organic','not natural','B2'],
      ['nonorganic','adj','Not organic','not natural','B1'],
      ['semiorganic','adj','Partially organic','partly natural','B2'],
      ['overorganic','adj','Excessively organic','too natural','B2'],
      ['ultraorganic','adj','Extremely organic','very natural','B2'],
      ['genetically modified','adj','Having altered DNA','GM,engineered,biotech','B2'],
      ['genetically modifiedly','adv','In a genetically modified manner','GM way','B2'],
      ['genetically modifiedness','n','The quality of being genetically modified','GM quality','B2'],
      ['genetically modifiedity','n','The state of being genetically modified','GM condition','C1'],
      ['ungenetically modified','adj','Not genetically modified','not GM','B2'],
      ['ingenetically modified','adj','Not genetically modified','not GM','C1'],
      ['nongenetically modified','adj','Not genetically modified','not GM','B2'],
      ['semigenetically modified','adj','Partially genetically modified','partly GM','C1'],
      ['overgenetically modified','adj','Excessively genetically modified','too GM','C1'],
      ['ultragenetically modified','adj','Extremely genetically modified','very GM','C1'],
      ['perishablely','adv','In a perishable manner','spoilable way','B2'],
      ['perishableness','n','The quality of being perishable','spoilable quality','B2'],
      ['perishableity','n','The state of being perishable','spoilable condition','C1'],
      ['unperishable','adj','Not perishable','not spoilable','B2'],
      ['inperishable','adj','Not perishable','not spoilable','C1'],
      ['nonperishable','adj','Not perishable','not spoilable','B2'],
      ['semiperishable','adj','Partially perishable','partly spoilable','C1'],
      ['overperishable','adj','Excessively perishable','too spoilable','C1'],
      ['ultraperishable','adj','Extremely perishable','very spoilable','C1'],
      ['artisanality','n','The state of being artisanal','handmade condition','C1'],
      ['inartisanal','adj','Not artisanal','not handmade','C1'],
      ['nonartisanal','adj','Not artisanal','not handmade','B2'],
      ['semiartisanal','adj','Partially artisanal','partly handmade','C1'],
      ['overartisanal','adj','Excessively artisanal','too handmade','C1'],
      ['ultraartisanal','adj','Extremely artisanal','very handmade','C1'],
      ['calorieal','adj','Relating to calorie','energy unit-related,pertaining to','B1'],
      ['calorieic','adj','Of or relating to calorie','energy unit-based,characteristic','B1'],
      ['calorieous','adj','Full of calorie','energy unit-filled,abundant','B2'],
      ['calorieful','adj','Full of calorie','energy unit-rich,abounding','B1'],
      ['calorieless','adj','Without calorie','lacking,without','B1'],
      ['calorieism','n','The ideology of calorie','energy unit ideology,doctrine','B2'],
      ['calorieist','n','A person focused on calorie','energy unit specialist,advocate','B2'],
      ['calorieise','v','To make into calorie','energy unit,convert','B2'],
      ['calorieize','v','To make or become calorie','energy unit,transform','B2'],
      ['anticalorie','adj','Opposed to calorie','against,opposing','B2'],
      ['noncalorie','adj','Not involving calorie','without,lacking','B1'],
      ['precalorie','n','Before calorie','preceding,prior','B2'],
      ['postcalorie','n','After calorie','following,subsequent','B2'],
      ['subcalorie','n','A subdivision of calorie','subset,branch','B2'],
      ['multicalorie','adj','Involving many calories','multiple,several','B2'],
      ['intercalorie','adj','Between calories','cross,between','B2'],
      ['preservativeal','adj','Relating to preservative','additive-related,pertaining to','B2'],
      ['preservativeic','adj','Of or relating to preservative','additive-based,characteristic','B2'],
      ['preservativeous','adj','Full of preservative','additive-filled,abundant','C1'],
      ['preservativeful','adj','Full of preservative','additive-rich,abounding','B2'],
      ['preservativeless','adj','Without preservative','lacking,without','B2'],
      ['preservativeism','n','The ideology of preservative','additive ideology,doctrine','C1'],
      ['preservativeist','n','A person focused on preservative','additive specialist,advocate','C1'],
      ['preservativeise','v','To make into preservative','additive,convert','C1'],
      ['preservativeize','v','To make or become preservative','additive,transform','C1'],
      ['antipreservative','adj','Opposed to preservative','against,opposing','C1'],
      ['nonpreservative','adj','Not involving preservative','without,lacking','B2'],
      ['prepreservative','n','Before preservative','preceding,prior','C1'],
      ['postpreservative','n','After preservative','following,subsequent','C1'],
      ['subpreservative','n','A subdivision of preservative','subset,branch','C1'],
      ['multipreservative','adj','Involving many preservatives','multiple,several','C1'],
      ['interpreservative','adj','Between preservatives','cross,between','C1'],
      ['allergenal','adj','Relating to allergen','irritant-related,pertaining to','B2'],
      ['allergenic','adj','Of or relating to allergen','irritant-based,characteristic','B2'],
      ['allergenous','adj','Full of allergen','irritant-filled,abundant','C1'],
      ['allergenful','adj','Full of allergen','irritant-rich,abounding','B2'],
      ['allergenless','adj','Without allergen','lacking,without','B2'],
      ['allergenism','n','The ideology of allergen','irritant ideology,doctrine','C1'],
      ['allergenist','n','A person focused on allergen','irritant specialist,advocate','C1'],
      ['allergenise','v','To make into allergen','irritant,convert','C1'],
      ['allergenize','v','To make or become allergen','irritant,transform','C1'],
      ['antiallergen','adj','Opposed to allergen','against,opposing','C1'],
      ['nonallergen','adj','Not involving allergen','without,lacking','B2'],
      ['preallergen','n','Before allergen','preceding,prior','C1'],
      ['postallergen','n','After allergen','following,subsequent','C1'],
      ['suballergen','n','A subdivision of allergen','subset,branch','C1'],
      ['multiallergen','adj','Involving many allergens','multiple,several','C1'],
      ['interallergen','adj','Between allergens','cross,between','C1'],
      ['pesticideal','adj','Relating to pesticide','insecticide-related,pertaining to','B2'],
      ['pesticideic','adj','Of or relating to pesticide','insecticide-based,characteristic','B2'],
      ['pesticideous','adj','Full of pesticide','insecticide-filled,abundant','C1'],
      ['pesticideful','adj','Full of pesticide','insecticide-rich,abounding','B2'],
      ['pesticideless','adj','Without pesticide','lacking,without','B2'],
      ['pesticideism','n','The ideology of pesticide','insecticide ideology,doctrine','C1'],
      ['pesticideist','n','A person focused on pesticide','insecticide specialist,advocate','C1'],
      ['pesticideise','v','To make into pesticide','insecticide,convert','C1'],
      ['pesticideize','v','To make or become pesticide','insecticide,transform','C1'],
      ['antipesticide','adj','Opposed to pesticide','against,opposing','C1'],
      ['nonpesticide','adj','Not involving pesticide','without,lacking','B2'],
      ['prepesticide','n','Before pesticide','preceding,prior','C1'],
      ['postpesticide','n','After pesticide','following,subsequent','C1'],
      ['subpesticide','n','A subdivision of pesticide','subset,branch','C1'],
      ['multipesticide','adj','Involving many pesticides','multiple,several','C1'],
      ['interpesticide','adj','Between pesticides','cross,between','C1'],
      ['carcinogenal','adj','Relating to carcinogen','cancer-causing agent-related,pertaining to','C1'],
      ['carcinogenous','adj','Full of carcinogen','cancer-causing agent-filled,abundant','C2'],
      ['carcinogenful','adj','Full of carcinogen','cancer-causing agent-rich,abounding','C1'],
      ['carcinogenless','adj','Without carcinogen','lacking,without','C1'],
      ['carcinogenism','n','The ideology of carcinogen','cancer-causing agent ideology,doctrine','C2'],
      ['carcinogenist','n','A person focused on carcinogen','cancer-causing agent specialist,advocate','C2'],
      ['carcinogenise','v','To make into carcinogen','cancer-causing agent,convert','C2'],
      ['carcinogenize','v','To make or become carcinogen','cancer-causing agent,transform','C2'],
      ['anticarcinogen','adj','Opposed to carcinogen','against,opposing','C2'],
      ['noncarcinogen','adj','Not involving carcinogen','without,lacking','C1'],
      ['precarcinogen','n','Before carcinogen','preceding,prior','C2'],
      ['postcarcinogen','n','After carcinogen','following,subsequent','C2'],
      ['subcarcinogen','n','A subdivision of carcinogen','subset,branch','C2'],
      ['multicarcinogen','adj','Involving many carcinogens','multiple,several','C2'],
      ['intercarcinogen','adj','Between carcinogens','cross,between','C2'],
      ['glutenic','adj','Of or relating to gluten','wheat protein-based,characteristic','B2'],
      ['glutenous','adj','Full of gluten','wheat protein-filled,abundant','C1'],
      ['glutenful','adj','Full of gluten','wheat protein-rich,abounding','B2'],
      ['glutenless','adj','Without gluten','lacking,without','B2'],
      ['glutenism','n','The ideology of gluten','wheat protein ideology,doctrine','C1'],
      ['glutenist','n','A person focused on gluten','wheat protein specialist,advocate','C1'],
      ['glutenise','v','To make into gluten','wheat protein,convert','C1'],
      ['glutenize','v','To make or become gluten','wheat protein,transform','C1'],
      ['antigluten','adj','Opposed to gluten','against,opposing','C1'],
      ['nongluten','adj','Not involving gluten','without,lacking','B2'],
      ['pregluten','n','Before gluten','preceding,prior','C1'],
      ['postgluten','n','After gluten','following,subsequent','C1'],
      ['subgluten','n','A subdivision of gluten','subset,branch','C1'],
      ['multigluten','adj','Involving many glutens','multiple,several','C1'],
      ['intergluten','adj','Between glutens','cross,between','C1'],
      ['malnutritional','adj','Relating to malnutrition','undernutrition-related,pertaining to','B2'],
      ['malnutritionic','adj','Of or relating to malnutrition','undernutrition-based,characteristic','B2'],
      ['malnutritionous','adj','Full of malnutrition','undernutrition-filled,abundant','C1'],
      ['malnutritionful','adj','Full of malnutrition','undernutrition-rich,abounding','B2'],
      ['malnutritionless','adj','Without malnutrition','lacking,without','B2'],
      ['malnutritionism','n','The ideology of malnutrition','undernutrition ideology,doctrine','C1'],
      ['malnutritionist','n','A person focused on malnutrition','undernutrition specialist,advocate','C1'],
      ['malnutritionise','v','To make into malnutrition','undernutrition,convert','C1'],
      ['malnutritionize','v','To make or become malnutrition','undernutrition,transform','C1'],
      ['antimalnutrition','adj','Opposed to malnutrition','against,opposing','C1'],
      ['nonmalnutrition','adj','Not involving malnutrition','without,lacking','B2'],
      ['premalnutrition','n','Before malnutrition','preceding,prior','C1'],
      ['postmalnutrition','n','After malnutrition','following,subsequent','C1'],
      ['submalnutrition','n','A subdivision of malnutrition','subset,branch','C1'],
      ['multimalnutrition','adj','Involving many malnutritions','multiple,several','C1'],
      ['intermalnutrition','adj','Between malnutritions','cross,between','C1'],
      ['famineal','adj','Relating to famine','starvation-related,pertaining to','B2'],
      ['famineic','adj','Of or relating to famine','starvation-based,characteristic','B2'],
      ['famineous','adj','Full of famine','starvation-filled,abundant','C1'],
      ['famineful','adj','Full of famine','starvation-rich,abounding','B2'],
      ['famineless','adj','Without famine','lacking,without','B2'],
      ['famineism','n','The ideology of famine','starvation ideology,doctrine','C1'],
      ['famineist','n','A person focused on famine','starvation specialist,advocate','C1'],
      ['famineise','v','To make into famine','starvation,convert','C1'],
      ['famineize','v','To make or become famine','starvation,transform','C1'],
      ['antifamine','adj','Opposed to famine','against,opposing','C1'],
      ['nonfamine','adj','Not involving famine','without,lacking','B2'],
      ['prefamine','n','Before famine','preceding,prior','C1'],
      ['postfamine','n','After famine','following,subsequent','C1'],
      ['subfamine','n','A subdivision of famine','subset,branch','C1'],
      ['multifamine','adj','Involving many famines','multiple,several','C1'],
      ['interfamine','adj','Between famines','cross,between','C1'],
      ['gastronomyic','adj','Of or relating to gastronomy','cuisine-based,characteristic','C1'],
      ['gastronomyous','adj','Full of gastronomy','cuisine-filled,abundant','C2'],
      ['gastronomyful','adj','Full of gastronomy','cuisine-rich,abounding','C1'],
      ['gastronomyless','adj','Without gastronomy','lacking,without','C1'],
      ['gastronomyism','n','The ideology of gastronomy','cuisine ideology,doctrine','C2'],
      ['gastronomyist','n','A person focused on gastronomy','cuisine specialist,advocate','C2'],
      ['gastronomyise','v','To make into gastronomy','cuisine,convert','C2'],
      ['gastronomyize','v','To make or become gastronomy','cuisine,transform','C2'],
      ['antigastronomy','adj','Opposed to gastronomy','against,opposing','C2'],
      ['nongastronomy','adj','Not involving gastronomy','without,lacking','C1'],
      ['pregastronomy','n','Before gastronomy','preceding,prior','C2'],
      ['postgastronomy','n','After gastronomy','following,subsequent','C2'],
      ['subgastronomy','n','A subdivision of gastronomy','subset,branch','C2'],
      ['multigastronomy','adj','Involving many gastronomys','multiple,several','C2'],
      ['intergastronomy','adj','Between gastronomys','cross,between','C2'],
      ['subsistenceal','adj','Relating to subsistence','survival-related,pertaining to','B2'],
      ['subsistenceic','adj','Of or relating to subsistence','survival-based,characteristic','B2'],
      ['subsistenceous','adj','Full of subsistence','survival-filled,abundant','C1'],
      ['subsistenceful','adj','Full of subsistence','survival-rich,abounding','B2'],
      ['subsistenceless','adj','Without subsistence','lacking,without','B2'],
      ['subsistenceism','n','The ideology of subsistence','survival ideology,doctrine','C1'],
      ['subsistenceist','n','A person focused on subsistence','survival specialist,advocate','C1'],
      ['subsistenceise','v','To make into subsistence','survival,convert','C1'],
      ['subsistenceize','v','To make or become subsistence','survival,transform','C1'],
      ['antisubsistence','adj','Opposed to subsistence','against,opposing','C1'],
      ['nonsubsistence','adj','Not involving subsistence','without,lacking','B2'],
      ['presubsistence','n','Before subsistence','preceding,prior','C1'],
      ['postsubsistence','n','After subsistence','following,subsequent','C1'],
      ['subsubsistence','n','A subdivision of subsistence','subset,branch','C1'],
      ['multisubsistence','adj','Involving many subsistences','multiple,several','C1'],
      ['intersubsistence','adj','Between subsistences','cross,between','C1'],
      ['cuisineic','adj','Of or relating to cuisine','food-based,characteristic','B1'],
      ['cuisineous','adj','Full of cuisine','food-filled,abundant','B2'],
      ['cuisineful','adj','Full of cuisine','food-rich,abounding','B1'],
      ['cuisineless','adj','Without cuisine','lacking,without','B1'],
      ['cuisineism','n','The ideology of cuisine','food ideology,doctrine','B2'],
      ['cuisineist','n','A person focused on cuisine','food specialist,advocate','B2'],
      ['cuisineise','v','To make into cuisine','food,convert','B2'],
      ['cuisineize','v','To make or become cuisine','food,transform','B2'],
      ['anticuisine','adj','Opposed to cuisine','against,opposing','B2'],
      ['noncuisine','adj','Not involving cuisine','without,lacking','B1'],
      ['precuisine','n','Before cuisine','preceding,prior','B2'],
      ['postcuisine','n','After cuisine','following,subsequent','B2'],
      ['subcuisine','n','A subdivision of cuisine','subset,branch','B2'],
      ['multicuisine','adj','Involving many cuisines','multiple,several','B2'],
      ['intercuisine','adj','Between cuisines','cross,between','B2'],
      ['delicacyic','adj','Of or relating to delicacy','treat-based,characteristic','B2'],
      ['delicacyous','adj','Full of delicacy','treat-filled,abundant','C1'],
      ['delicacyful','adj','Full of delicacy','treat-rich,abounding','B2'],
      ['delicacyless','adj','Without delicacy','lacking,without','B2'],
      ['delicacyism','n','The ideology of delicacy','treat ideology,doctrine','C1'],
      ['delicacyist','n','A person focused on delicacy','treat specialist,advocate','C1'],
      ['delicacyise','v','To make into delicacy','treat,convert','C1'],
      ['delicacyize','v','To make or become delicacy','treat,transform','C1'],
      ['antidelicacy','adj','Opposed to delicacy','against,opposing','C1'],
      ['nondelicacy','adj','Not involving delicacy','without,lacking','B2'],
      ['predelicacy','n','Before delicacy','preceding,prior','C1'],
      ['postdelicacy','n','After delicacy','following,subsequent','C1'],
      ['subdelicacy','n','A subdivision of delicacy','subset,branch','C1'],
      ['multidelicacy','adj','Involving many delicacys','multiple,several','C1'],
      ['interdelicacy','adj','Between delicacys','cross,between','C1'],
      ['herbivore','n','An animal that eats only plants','plant-eater,vegetarian animal','B2'],
      ['herbivoreal','adj','Relating to herbivore','plant-eater-related,pertaining to','B2'],
      ['herbivoreic','adj','Of or relating to herbivore','plant-eater-based,characteristic','B2'],
      ['herbivoreous','adj','Full of herbivore','plant-eater-filled,abundant','C1'],
      ['herbivoreful','adj','Full of herbivore','plant-eater-rich,abounding','B2'],
      ['herbivoreless','adj','Without herbivore','lacking,without','B2'],
      ['herbivoreism','n','The ideology of herbivore','plant-eater ideology,doctrine','C1'],
      ['herbivoreist','n','A person focused on herbivore','plant-eater specialist,advocate','C1'],
      ['herbivoreise','v','To make into herbivore','plant-eater,convert','C1'],
      ['herbivoreize','v','To make or become herbivore','plant-eater,transform','C1'],
      ['antiherbivore','adj','Opposed to herbivore','against,opposing','C1'],
    ],
  },
  collocations: {}
};
