// Auto-generated vocab boost group 66
module.exports = {
  vocab: {
    government: [
      ['overveto','v','To veto excessively','excess,too much','C1'],
      ['underveto','v','To veto insufficiently','insufficient,inadequate','C1'],
      ['misveto','v','To veto incorrectly','wrongly,incorrectly','C1'],
      ['preveto','v','To veto beforehand','before,in advance','C1'],
      ['coveto','v','To veto together','jointly,together','C1'],
      ['revetoation','n','The act of vetoing again','re-reject','C1'],
      ['overvetoation','n','Excessive vetoing','excess reject','C1'],
      ['inauguratation','n','The act of inaugurating','install process','C1'],
      ['inauguratment','n','The result of inaugurating','install outcome','C1'],
      ['inauguratance','n','The state of inaugurating','install state','C1'],
      ['inauguratence','n','The quality of inaugurating','install quality','C1'],
      ['inauguratal','n','An act of inaugurating','install event','C2'],
      ['inaugurater','n','One who inaugurates','install person','C1'],
      ['inaugurator','n','One who inaugurates','install agent','C1'],
      ['inauguratee','n','One who is inaugurated','install recipient','C2'],
      ['inauguratable','adj','Capable of being inaugurated','install,possible','C2'],
      ['inauguratible','adj','Able to be inaugurated','install,feasible','C2'],
      ['inaugurative','adj','Tending to inaugurate','install,active','C1'],
      ['inaugurating','adj','Currently inaugurating','install,ongoing','C1'],
      ['inaugurated','adj','Having been inaugurated','install,completed','C1'],
      ['reinaugurate','v','To inaugurate again','install again,repeat','C1'],
      ['uninaugurate','v','To reverse inaugurating','reverse,undo','C2'],
      ['overinaugurate','v','To inaugurate excessively','excess,too much','C2'],
      ['underinaugurate','v','To inaugurate insufficiently','insufficient,inadequate','C2'],
      ['misinaugurate','v','To inaugurate incorrectly','wrongly,incorrectly','C2'],
      ['preinaugurate','v','To inaugurate beforehand','before,in advance','C2'],
      ['coinaugurate','v','To inaugurate together','jointly,together','C2'],
      ['reinauguratation','n','The act of inaugurating again','re-install','C2'],
      ['overinauguratation','n','Excessive inaugurating','excess install','C2'],
      ['impeachation','n','The act of impeaching','accuse process','C1'],
      ['impeachance','n','The state of impeaching','accuse state','C1'],
      ['impeachence','n','The quality of impeaching','accuse quality','C1'],
      ['impeachal','n','An act of impeaching','accuse event','C2'],
      ['impeacher','n','One who impeachs','accuse person','C1'],
      ['impeachor','n','One who impeachs','accuse agent','C1'],
      ['impeachee','n','One who is impeachd','accuse recipient','C2'],
      ['impeachable','adj','Capable of being impeachd','accuse,possible','C2'],
      ['impeachible','adj','Able to be impeachd','accuse,feasible','C2'],
      ['impeachive','adj','Tending to impeach','accuse,active','C1'],
      ['impeaching','adj','Currently impeaching','accuse,ongoing','C1'],
      ['impeached','adj','Having been impeachd','accuse,completed','C1'],
      ['reimpeach','v','To impeach again','accuse again,repeat','C1'],
      ['unimpeach','v','To reverse impeaching','reverse,undo','C2'],
      ['overimpeach','v','To impeach excessively','excess,too much','C2'],
      ['underimpeach','v','To impeach insufficiently','insufficient,inadequate','C2'],
      ['misimpeach','v','To impeach incorrectly','wrongly,incorrectly','C2'],
      ['preimpeach','v','To impeach beforehand','before,in advance','C2'],
      ['coimpeach','v','To impeach together','jointly,together','C2'],
      ['reimpeachation','n','The act of impeaching again','re-accuse','C2'],
      ['overimpeachation','n','Excessive impeaching','excess accuse','C2'],
      ['gerrymander','v','To manipulate electoral boundaries','manipulate,rig,distort','C2'],
      ['gerrymanderation','n','The act of gerrymandering','manipulate process','C2'],
      ['gerrymanderment','n','The result of gerrymandering','manipulate outcome','C2'],
      ['gerrymanderance','n','The state of gerrymandering','manipulate state','C2'],
      ['gerrymanderence','n','The quality of gerrymandering','manipulate quality','C2'],
      ['gerrymanderal','n','An act of gerrymandering','manipulate event','C2'],
      ['gerrymanderer','n','One who gerrymanders','manipulate person','C2'],
      ['gerrymanderor','n','One who gerrymanders','manipulate agent','C2'],
      ['gerrymanderee','n','One who is gerrymanderd','manipulate recipient','C2'],
      ['gerrymanderable','adj','Capable of being gerrymanderd','manipulate,possible','C2'],
      ['gerrymanderible','adj','Able to be gerrymanderd','manipulate,feasible','C2'],
      ['gerrymanderive','adj','Tending to gerrymander','manipulate,active','C2'],
      ['gerrymandered','adj','Having been gerrymanderd','manipulate,completed','C2'],
      ['regerrymander','v','To gerrymander again','manipulate again,repeat','C2'],
      ['ungerrymander','v','To reverse gerrymandering','reverse,undo','C2'],
      ['overgerrymander','v','To gerrymander excessively','excess,too much','C2'],
      ['undergerrymander','v','To gerrymander insufficiently','insufficient,inadequate','C2'],
      ['misgerrymander','v','To gerrymander incorrectly','wrongly,incorrectly','C2'],
      ['pregerrymander','v','To gerrymander beforehand','before,in advance','C2'],
      ['cogerrymander','v','To gerrymander together','jointly,together','C2'],
      ['regerrymanderation','n','The act of gerrymandering again','re-manipulate','C2'],
      ['overgerrymanderation','n','Excessive gerrymandering','excess manipulate','C2'],
      ['referendumic','adj','Of or relating to referendum','public vote-based,characteristic','B2'],
      ['referendumous','adj','Full of referendum','public vote-filled,abundant','C1'],
      ['referendumful','adj','Full of referendum','public vote-rich,abounding','B2'],
      ['referendumless','adj','Without referendum','lacking,without','B2'],
      ['referendumism','n','The ideology of referendum','public vote ideology,doctrine','C1'],
      ['referendumist','n','A person focused on referendum','public vote specialist,advocate','C1'],
      ['referendumise','v','To make into referendum','public vote,convert','C1'],
      ['referendumize','v','To make or become referendum','public vote,transform','C1'],
      ['antireferendum','adj','Opposed to referendum','against,opposing','C1'],
      ['nonreferendum','adj','Not involving referendum','without,lacking','B2'],
      ['prereferendum','n','Before referendum','preceding,prior','C1'],
      ['postreferendum','n','After referendum','following,subsequent','C1'],
      ['subreferendum','n','A subdivision of referendum','subset,branch','C1'],
      ['multireferendum','adj','Involving many referendums','multiple,several','C1'],
      ['interreferendum','adj','Between referendums','cross,between','C1'],
      ['constitutionic','adj','Of or relating to constitution','charter-based,characteristic','B2'],
      ['constitutionous','adj','Full of constitution','charter-filled,abundant','C1'],
      ['constitutionful','adj','Full of constitution','charter-rich,abounding','B2'],
      ['constitutionless','adj','Without constitution','lacking,without','B2'],
      ['constitutionism','n','The ideology of constitution','charter ideology,doctrine','C1'],
      ['constitutionist','n','A person focused on constitution','charter specialist,advocate','C1'],
      ['constitutionise','v','To make into constitution','charter,convert','C1'],
      ['constitutionize','v','To make or become constitution','charter,transform','C1'],
      ['anticonstitution','adj','Opposed to constitution','against,opposing','C1'],
      ['nonconstitution','adj','Not involving constitution','without,lacking','B2'],
      ['preconstitution','n','Before constitution','preceding,prior','C1'],
      ['postconstitution','n','After constitution','following,subsequent','C1'],
      ['subconstitution','n','A subdivision of constitution','subset,branch','C1'],
      ['multiconstitution','adj','Involving many constitutions','multiple,several','C1'],
      ['interconstitution','adj','Between constitutions','cross,between','C1'],
      ['sovereigntyic','adj','Of or relating to sovereignty','independence-based,characteristic','B2'],
      ['sovereigntyous','adj','Full of sovereignty','independence-filled,abundant','C1'],
      ['sovereigntyful','adj','Full of sovereignty','independence-rich,abounding','B2'],
      ['sovereigntyless','adj','Without sovereignty','lacking,without','B2'],
      ['sovereigntyism','n','The ideology of sovereignty','independence ideology,doctrine','C1'],
      ['sovereigntyist','n','A person focused on sovereignty','independence specialist,advocate','C1'],
      ['sovereigntyise','v','To make into sovereignty','independence,convert','C1'],
      ['sovereigntyize','v','To make or become sovereignty','independence,transform','C1'],
      ['antisovereignty','adj','Opposed to sovereignty','against,opposing','C1'],
      ['nonsovereignty','adj','Not involving sovereignty','without,lacking','B2'],
      ['presovereignty','n','Before sovereignty','preceding,prior','C1'],
      ['postsovereignty','n','After sovereignty','following,subsequent','C1'],
      ['subsovereignty','n','A subdivision of sovereignty','subset,branch','C1'],
      ['multisovereignty','adj','Involving many sovereigntys','multiple,several','C1'],
      ['intersovereignty','adj','Between sovereigntys','cross,between','C1'],
      ['diplomacyal','adj','Relating to diplomacy','foreign affairs-related,pertaining to','B2'],
      ['diplomacyic','adj','Of or relating to diplomacy','foreign affairs-based,characteristic','B2'],
      ['diplomacyous','adj','Full of diplomacy','foreign affairs-filled,abundant','C1'],
      ['diplomacyful','adj','Full of diplomacy','foreign affairs-rich,abounding','B2'],
      ['diplomacyless','adj','Without diplomacy','lacking,without','B2'],
      ['diplomacyism','n','The ideology of diplomacy','foreign affairs ideology,doctrine','C1'],
      ['diplomacyist','n','A person focused on diplomacy','foreign affairs specialist,advocate','C1'],
      ['diplomacyise','v','To make into diplomacy','foreign affairs,convert','C1'],
      ['diplomacyize','v','To make or become diplomacy','foreign affairs,transform','C1'],
      ['antidiplomacy','adj','Opposed to diplomacy','against,opposing','C1'],
      ['nondiplomacy','adj','Not involving diplomacy','without,lacking','B2'],
      ['prediplomacy','n','Before diplomacy','preceding,prior','C1'],
      ['postdiplomacy','n','After diplomacy','following,subsequent','C1'],
      ['subdiplomacy','n','A subdivision of diplomacy','subset,branch','C1'],
      ['multidiplomacy','adj','Involving many diplomacys','multiple,several','C1'],
      ['interdiplomacy','adj','Between diplomacys','cross,between','C1'],
      ['legislature','n','The body that makes laws','parliament,congress,assembly','B2'],
      ['legislatureal','adj','Relating to legislature','parliament-related,pertaining to','B2'],
      ['legislatureic','adj','Of or relating to legislature','parliament-based,characteristic','B2'],
      ['legislatureous','adj','Full of legislature','parliament-filled,abundant','C1'],
      ['legislatureful','adj','Full of legislature','parliament-rich,abounding','B2'],
      ['legislatureless','adj','Without legislature','lacking,without','B2'],
      ['legislatureism','n','The ideology of legislature','parliament ideology,doctrine','C1'],
      ['legislatureist','n','A person focused on legislature','parliament specialist,advocate','C1'],
      ['legislatureise','v','To make into legislature','parliament,convert','C1'],
      ['legislatureize','v','To make or become legislature','parliament,transform','C1'],
      ['antilegislature','adj','Opposed to legislature','against,opposing','C1'],
      ['nonlegislature','adj','Not involving legislature','without,lacking','B2'],
      ['prelegislature','n','Before legislature','preceding,prior','C1'],
      ['postlegislature','n','After legislature','following,subsequent','C1'],
      ['sublegislature','n','A subdivision of legislature','subset,branch','C1'],
      ['multilegislature','adj','Involving many legislatures','multiple,several','C1'],
      ['interlegislature','adj','Between legislatures','cross,between','C1'],
      ['autocracyic','adj','Of or relating to autocracy','dictatorship-based,characteristic','C1'],
      ['autocracyous','adj','Full of autocracy','dictatorship-filled,abundant','C2'],
      ['autocracyful','adj','Full of autocracy','dictatorship-rich,abounding','C1'],
      ['autocracyless','adj','Without autocracy','lacking,without','C1'],
      ['autocracyism','n','The ideology of autocracy','dictatorship ideology,doctrine','C2'],
      ['autocracyist','n','A person focused on autocracy','dictatorship specialist,advocate','C2'],
      ['autocracyise','v','To make into autocracy','dictatorship,convert','C2'],
      ['autocracyize','v','To make or become autocracy','dictatorship,transform','C2'],
      ['antiautocracy','adj','Opposed to autocracy','against,opposing','C2'],
      ['nonautocracy','adj','Not involving autocracy','without,lacking','C1'],
      ['preautocracy','n','Before autocracy','preceding,prior','C2'],
      ['postautocracy','n','After autocracy','following,subsequent','C2'],
      ['subautocracy','n','A subdivision of autocracy','subset,branch','C2'],
      ['multiautocracy','adj','Involving many autocracys','multiple,several','C2'],
      ['interautocracy','adj','Between autocracys','cross,between','C2'],
      ['oligarchyic','adj','Of or relating to oligarchy','elite rule-based,characteristic','C1'],
      ['oligarchyous','adj','Full of oligarchy','elite rule-filled,abundant','C2'],
      ['oligarchyful','adj','Full of oligarchy','elite rule-rich,abounding','C1'],
      ['oligarchyless','adj','Without oligarchy','lacking,without','C1'],
      ['oligarchyism','n','The ideology of oligarchy','elite rule ideology,doctrine','C2'],
      ['oligarchyist','n','A person focused on oligarchy','elite rule specialist,advocate','C2'],
      ['oligarchyise','v','To make into oligarchy','elite rule,convert','C2'],
      ['oligarchyize','v','To make or become oligarchy','elite rule,transform','C2'],
      ['antioligarchy','adj','Opposed to oligarchy','against,opposing','C2'],
      ['nonoligarchy','adj','Not involving oligarchy','without,lacking','C1'],
      ['preoligarchy','n','Before oligarchy','preceding,prior','C2'],
      ['postoligarchy','n','After oligarchy','following,subsequent','C2'],
      ['suboligarchy','n','A subdivision of oligarchy','subset,branch','C2'],
      ['multioligarchy','adj','Involving many oligarchys','multiple,several','C2'],
      ['interoligarchy','adj','Between oligarchys','cross,between','C2'],
      ['theocracyic','adj','Of or relating to theocracy','religious rule-based,characteristic','C1'],
      ['theocracyous','adj','Full of theocracy','religious rule-filled,abundant','C2'],
      ['theocracyful','adj','Full of theocracy','religious rule-rich,abounding','C1'],
      ['theocracyless','adj','Without theocracy','lacking,without','C1'],
      ['theocracyism','n','The ideology of theocracy','religious rule ideology,doctrine','C2'],
      ['theocracyist','n','A person focused on theocracy','religious rule specialist,advocate','C2'],
      ['theocracyise','v','To make into theocracy','religious rule,convert','C2'],
      ['theocracyize','v','To make or become theocracy','religious rule,transform','C2'],
      ['antitheocracy','adj','Opposed to theocracy','against,opposing','C2'],
      ['nontheocracy','adj','Not involving theocracy','without,lacking','C1'],
      ['pretheocracy','n','Before theocracy','preceding,prior','C2'],
      ['posttheocracy','n','After theocracy','following,subsequent','C2'],
      ['subtheocracy','n','A subdivision of theocracy','subset,branch','C2'],
      ['multitheocracy','adj','Involving many theocracys','multiple,several','C2'],
      ['intertheocracy','adj','Between theocracys','cross,between','C2'],
      ['meritocracyic','adj','Of or relating to meritocracy','talent-based rule-based,characteristic','C1'],
      ['meritocracyous','adj','Full of meritocracy','talent-based rule-filled,abundant','C2'],
      ['meritocracyful','adj','Full of meritocracy','talent-based rule-rich,abounding','C1'],
      ['meritocracyless','adj','Without meritocracy','lacking,without','C1'],
      ['meritocracyism','n','The ideology of meritocracy','talent-based rule ideology,doctrine','C2'],
      ['meritocracyist','n','A person focused on meritocracy','talent-based rule specialist,advocate','C2'],
      ['meritocracyise','v','To make into meritocracy','talent-based rule,convert','C2'],
      ['meritocracyize','v','To make or become meritocracy','talent-based rule,transform','C2'],
      ['antimeritocracy','adj','Opposed to meritocracy','against,opposing','C2'],
      ['nonmeritocracy','adj','Not involving meritocracy','without,lacking','C1'],
      ['premeritocracy','n','Before meritocracy','preceding,prior','C2'],
      ['postmeritocracy','n','After meritocracy','following,subsequent','C2'],
      ['submeritocracy','n','A subdivision of meritocracy','subset,branch','C2'],
      ['multimeritocracy','adj','Involving many meritocracys','multiple,several','C2'],
      ['intermeritocracy','adj','Between meritocracys','cross,between','C2'],
      ['bipartisanity','n','The state of being bipartisan','cross-party condition','C2'],
      ['inbipartisan','adj','Not bipartisan','not cross-party','C2'],
      ['nonbipartisan','adj','Not bipartisan','not cross-party','C1'],
      ['semibipartisan','adj','Partially bipartisan','partly cross-party','C2'],
      ['overbipartisan','adj','Excessively bipartisan','too cross-party','C2'],
      ['ultrabipartisan','adj','Extremely bipartisan','very cross-party','C2'],
      ['authoritarianly','adv','In a authoritarian manner','dictatorial way','B2'],
      ['authoritarianness','n','The quality of being authoritarian','dictatorial quality','B2'],
      ['authoritarianity','n','The state of being authoritarian','dictatorial condition','C1'],
      ['unauthoritarian','adj','Not authoritarian','not dictatorial','B2'],
      ['inauthoritarian','adj','Not authoritarian','not dictatorial','C1'],
      ['nonauthoritarian','adj','Not authoritarian','not dictatorial','B2'],
      ['semiauthoritarian','adj','Partially authoritarian','partly dictatorial','C1'],
      ['overauthoritarian','adj','Excessively authoritarian','too dictatorial','C1'],
      ['ultraauthoritarian','adj','Extremely authoritarian','very dictatorial','C1'],
      ['democraticly','adv','In a democratic manner','popular way','B2'],
      ['democraticness','n','The quality of being democratic','popular quality','B2'],
      ['democraticity','n','The state of being democratic','popular condition','C1'],
      ['undemocratic','adj','Not democratic','not popular','B2'],
      ['indemocratic','adj','Not democratic','not popular','C1'],
      ['nondemocratic','adj','Not democratic','not popular','B2'],
      ['semidemocratic','adj','Partially democratic','partly popular','C1'],
      ['overdemocratic','adj','Excessively democratic','too popular','C1'],
      ['ultrademocratic','adj','Extremely democratic','very popular','C1'],
      ['totalitarianity','n','The state of being totalitarian','absolute condition','C2'],
      ['intotalitarian','adj','Not totalitarian','not absolute','C2'],
      ['nontotalitarian','adj','Not totalitarian','not absolute','C1'],
      ['semitotalitarian','adj','Partially totalitarian','partly absolute','C2'],
      ['overtotalitarian','adj','Excessively totalitarian','too absolute','C2'],
      ['ultratotalitarian','adj','Extremely totalitarian','very absolute','C2'],
      ['autonomousity','n','The state of being autonomous','independent condition','C1'],
      ['inautonomous','adj','Not autonomous','not independent','C1'],
      ['nonautonomous','adj','Not autonomous','not independent','B2'],
      ['semiautonomous','adj','Partially autonomous','partly independent','C1'],
      ['overautonomous','adj','Excessively autonomous','too independent','C1'],
      ['ultraautonomous','adj','Extremely autonomous','very independent','C1'],
      ['incumbently','adv','In a incumbent manner','current way','C1'],
      ['incumbentness','n','The quality of being incumbent','current quality','C1'],
      ['incumbentity','n','The state of being incumbent','current condition','C2'],
      ['unincumbent','adj','Not incumbent','not current','C1'],
    ],
  },
  collocations: {}
};
