// Auto-generated vocab boost group 81
module.exports = {
  vocab: {
    transport: [
      ['unfuel-efficient','adj','Not fuel-efficient','not economical','B2'],
      ['infuel-efficient','adj','Not fuel-efficient','not economical','C1'],
      ['nonfuel-efficient','adj','Not fuel-efficient','not economical','B2'],
      ['semifuel-efficient','adj','Partially fuel-efficient','partly economical','C1'],
      ['overfuel-efficient','adj','Excessively fuel-efficient','too economical','C1'],
      ['ultrafuel-efficient','adj','Extremely fuel-efficient','very economical','C1'],
      ['zero-emission','adj','Producing no polluting exhaust','clean,electric,pollution-free','B2'],
      ['zero-emissionly','adv','In a zero-emission manner','clean way','B2'],
      ['zero-emissionness','n','The quality of being zero-emission','clean quality','B2'],
      ['zero-emissionity','n','The state of being zero-emission','clean condition','C1'],
      ['unzero-emission','adj','Not zero-emission','not clean','B2'],
      ['inzero-emission','adj','Not zero-emission','not clean','C1'],
      ['nonzero-emission','adj','Not zero-emission','not clean','B2'],
      ['semizero-emission','adj','Partially zero-emission','partly clean','C1'],
      ['overzero-emission','adj','Excessively zero-emission','too clean','C1'],
      ['ultrazero-emission','adj','Extremely zero-emission','very clean','C1'],
    ],
    employment: [
      ['recruitation','n','The act of recruiting','hire process','B1'],
      ['recruitance','n','The state of recruiting','hire state','B1'],
      ['recruitence','n','The quality of recruiting','hire quality','B1'],
      ['recruital','n','An act of recruiting','hire event','B2'],
      ['recruiter','n','One who recruits','hire person','B1'],
      ['recruitor','n','One who recruits','hire agent','B1'],
      ['recruitee','n','One who is recruitd','hire recipient','B2'],
      ['recruitable','adj','Capable of being recruitd','hire,possible','B2'],
      ['recruitible','adj','Able to be recruitd','hire,feasible','B2'],
      ['recruitive','adj','Tending to recruit','hire,active','B1'],
      ['recruiting','adj','Currently recruiting','hire,ongoing','B1'],
      ['recruited','adj','Having been recruitd','hire,completed','B1'],
      ['rerecruit','v','To recruit again','hire again,repeat','B1'],
      ['unrecruit','v','To reverse recruiting','reverse,undo','B2'],
      ['overrecruit','v','To recruit excessively','excess,too much','B2'],
      ['underrecruit','v','To recruit insufficiently','insufficient,inadequate','B2'],
      ['misrecruit','v','To recruit incorrectly','wrongly,incorrectly','B2'],
      ['prerecruit','v','To recruit beforehand','before,in advance','B2'],
      ['corecruit','v','To recruit together','jointly,together','B2'],
      ['rerecruitation','n','The act of recruiting again','re-hire','B2'],
      ['overrecruitation','n','Excessive recruiting','excess hire','B2'],
      ['appraisation','n','The act of appraising','evaluate process','B2'],
      ['appraisment','n','The result of appraising','evaluate outcome','B2'],
      ['appraisance','n','The state of appraising','evaluate state','B2'],
      ['appraisence','n','The quality of appraising','evaluate quality','B2'],
      ['appraiser','n','One who appraises','evaluate person','B2'],
      ['appraisor','n','One who appraises','evaluate agent','B2'],
      ['appraisee','n','One who is appraised','evaluate recipient','C1'],
      ['appraisable','adj','Capable of being appraised','evaluate,possible','C1'],
      ['appraisible','adj','Able to be appraised','evaluate,feasible','C1'],
      ['appraisive','adj','Tending to appraise','evaluate,active','B2'],
      ['appraising','adj','Currently appraising','evaluate,ongoing','B2'],
      ['appraised','adj','Having been appraised','evaluate,completed','B2'],
      ['reappraise','v','To appraise again','evaluate again,repeat','B2'],
      ['unappraise','v','To reverse appraising','reverse,undo','C1'],
      ['overappraise','v','To appraise excessively','excess,too much','C1'],
      ['underappraise','v','To appraise insufficiently','insufficient,inadequate','C1'],
      ['misappraise','v','To appraise incorrectly','wrongly,incorrectly','C1'],
      ['preappraise','v','To appraise beforehand','before,in advance','C1'],
      ['coappraise','v','To appraise together','jointly,together','C1'],
      ['reappraisation','n','The act of appraising again','re-evaluate','C1'],
      ['overappraisation','n','Excessive appraising','excess evaluate','C1'],
      ['delegatation','n','The act of delegating','assign process','B2'],
      ['delegatment','n','The result of delegating','assign outcome','B2'],
      ['delegatance','n','The state of delegating','assign state','B2'],
      ['delegatence','n','The quality of delegating','assign quality','B2'],
      ['delegatal','n','An act of delegating','assign event','C1'],
      ['delegater','n','One who delegates','assign person','B2'],
      ['delegator','n','One who delegates','assign agent','B2'],
      ['delegatee','n','One who is delegated','assign recipient','C1'],
      ['delegatable','adj','Capable of being delegated','assign,possible','C1'],
      ['delegatible','adj','Able to be delegated','assign,feasible','C1'],
      ['delegative','adj','Tending to delegate','assign,active','B2'],
      ['delegating','adj','Currently delegating','assign,ongoing','B2'],
      ['delegated','adj','Having been delegated','assign,completed','B2'],
      ['redelegate','v','To delegate again','assign again,repeat','B2'],
      ['undelegate','v','To reverse delegating','reverse,undo','C1'],
      ['overdelegate','v','To delegate excessively','excess,too much','C1'],
      ['underdelegate','v','To delegate insufficiently','insufficient,inadequate','C1'],
      ['misdelegate','v','To delegate incorrectly','wrongly,incorrectly','C1'],
      ['predelegate','v','To delegate beforehand','before,in advance','C1'],
      ['codelegate','v','To delegate together','jointly,together','C1'],
      ['redelegatation','n','The act of delegating again','re-assign','C1'],
      ['overdelegatation','n','Excessive delegating','excess assign','C1'],
      ['retrenchation','n','The act of retrenching','downsize process','C1'],
      ['retrenchance','n','The state of retrenching','downsize state','C1'],
      ['retrenchence','n','The quality of retrenching','downsize quality','C1'],
      ['retrenchal','n','An act of retrenching','downsize event','C2'],
      ['retrencher','n','One who retrenchs','downsize person','C1'],
      ['retrenchor','n','One who retrenchs','downsize agent','C1'],
      ['retrenchee','n','One who is retrenchd','downsize recipient','C2'],
      ['retrenchable','adj','Capable of being retrenchd','downsize,possible','C2'],
      ['retrenchible','adj','Able to be retrenchd','downsize,feasible','C2'],
      ['retrenchive','adj','Tending to retrench','downsize,active','C1'],
      ['retrenching','adj','Currently retrenching','downsize,ongoing','C1'],
      ['retrenched','adj','Having been retrenchd','downsize,completed','C1'],
      ['reretrench','v','To retrench again','downsize again,repeat','C1'],
      ['unretrench','v','To reverse retrenching','reverse,undo','C2'],
      ['overretrench','v','To retrench excessively','excess,too much','C2'],
      ['underretrench','v','To retrench insufficiently','insufficient,inadequate','C2'],
      ['misretrench','v','To retrench incorrectly','wrongly,incorrectly','C2'],
      ['preretrench','v','To retrench beforehand','before,in advance','C2'],
      ['coretrench','v','To retrench together','jointly,together','C2'],
      ['reretrenchation','n','The act of retrenching again','re-downsize','C2'],
      ['overretrenchation','n','Excessive retrenching','excess downsize','C2'],
      ['unionize','v','To organize workers into a union','organize,syndicate,collectivize','C1'],
      ['unionization','n','The act of unionizing','organize process','C1'],
      ['unionizment','n','The result of unionizing','organize outcome','C1'],
      ['unionizance','n','The state of unionizing','organize state','C1'],
      ['unionizence','n','The quality of unionizing','organize quality','C1'],
      ['unionizal','n','An act of unionizing','organize event','C2'],
      ['unionizer','n','One who unionizes','organize person','C1'],
      ['unionizor','n','One who unionizes','organize agent','C1'],
      ['unionizee','n','One who is unionized','organize recipient','C2'],
      ['unionizable','adj','Capable of being unionized','organize,possible','C2'],
      ['unionizible','adj','Able to be unionized','organize,feasible','C2'],
      ['unionizive','adj','Tending to unionize','organize,active','C1'],
      ['unionizing','adj','Currently unionizing','organize,ongoing','C1'],
      ['unionized','adj','Having been unionized','organize,completed','C1'],
      ['reunionize','v','To unionize again','organize again,repeat','C1'],
      ['ununionize','v','To reverse unionizing','reverse,undo','C2'],
      ['overunionize','v','To unionize excessively','excess,too much','C2'],
      ['underunionize','v','To unionize insufficiently','insufficient,inadequate','C2'],
      ['misunionize','v','To unionize incorrectly','wrongly,incorrectly','C2'],
      ['preunionize','v','To unionize beforehand','before,in advance','C2'],
      ['counionize','v','To unionize together','jointly,together','C2'],
      ['reunionization','n','The act of unionizing again','re-organize','C2'],
      ['overunionization','n','Excessive unionizing','excess organize','C2'],
      ['remuneratation','n','The act of remunerating','compensate process','C1'],
      ['remuneratment','n','The result of remunerating','compensate outcome','C1'],
      ['remuneratance','n','The state of remunerating','compensate state','C1'],
      ['remuneratence','n','The quality of remunerating','compensate quality','C1'],
      ['remuneratal','n','An act of remunerating','compensate event','C2'],
      ['remunerater','n','One who remunerates','compensate person','C1'],
      ['remunerator','n','One who remunerates','compensate agent','C1'],
      ['remuneratee','n','One who is remunerated','compensate recipient','C2'],
      ['remuneratable','adj','Capable of being remunerated','compensate,possible','C2'],
      ['remuneratible','adj','Able to be remunerated','compensate,feasible','C2'],
      ['remunerative','adj','Tending to remunerate','compensate,active','C1'],
      ['remunerating','adj','Currently remunerating','compensate,ongoing','C1'],
      ['remunerated','adj','Having been remunerated','compensate,completed','C1'],
      ['reremunerate','v','To remunerate again','compensate again,repeat','C1'],
      ['unremunerate','v','To reverse remunerating','reverse,undo','C2'],
      ['overremunerate','v','To remunerate excessively','excess,too much','C2'],
      ['underremunerate','v','To remunerate insufficiently','insufficient,inadequate','C2'],
      ['misremunerate','v','To remunerate incorrectly','wrongly,incorrectly','C2'],
      ['preremunerate','v','To remunerate beforehand','before,in advance','C2'],
      ['coremunerate','v','To remunerate together','jointly,together','C2'],
      ['reremuneratation','n','The act of remunerating again','re-compensate','C2'],
      ['overremuneratation','n','Excessive remunerating','excess compensate','C2'],
      ['stipulatation','n','The act of stipulating','specify process','B2'],
      ['stipulatment','n','The result of stipulating','specify outcome','B2'],
      ['stipulatance','n','The state of stipulating','specify state','B2'],
      ['stipulatence','n','The quality of stipulating','specify quality','B2'],
      ['stipulatal','n','An act of stipulating','specify event','C1'],
      ['stipulater','n','One who stipulates','specify person','B2'],
      ['stipulator','n','One who stipulates','specify agent','B2'],
      ['stipulatee','n','One who is stipulated','specify recipient','C1'],
      ['stipulatable','adj','Capable of being stipulated','specify,possible','C1'],
      ['stipulatible','adj','Able to be stipulated','specify,feasible','C1'],
      ['stipulative','adj','Tending to stipulate','specify,active','B2'],
      ['stipulating','adj','Currently stipulating','specify,ongoing','B2'],
      ['stipulated','adj','Having been stipulated','specify,completed','B2'],
      ['restipulate','v','To stipulate again','specify again,repeat','B2'],
      ['unstipulate','v','To reverse stipulating','reverse,undo','C1'],
      ['overstipulate','v','To stipulate excessively','excess,too much','C1'],
      ['understipulate','v','To stipulate insufficiently','insufficient,inadequate','C1'],
      ['misstipulate','v','To stipulate incorrectly','wrongly,incorrectly','C1'],
      ['prestipulate','v','To stipulate beforehand','before,in advance','C1'],
      ['costipulate','v','To stipulate together','jointly,together','C1'],
      ['restipulatation','n','The act of stipulating again','re-specify','C1'],
      ['overstipulatation','n','Excessive stipulating','excess specify','C1'],
      ['probationary','adj','Relating to a trial period of employment','trial,provisional,conditional','B2'],
      ['probationarily','adv','In a probationary manner','trial way','B2'],
      ['probationarness','n','The quality of being probationary','trial quality','B2'],
      ['probationarity','n','The state of being probationary','trial condition','C1'],
      ['unprobationary','adj','Not probationary','not trial','B2'],
      ['inprobationary','adj','Not probationary','not trial','C1'],
      ['nonprobationary','adj','Not probationary','not trial','B2'],
      ['semiprobationary','adj','Partially probationary','partly trial','C1'],
      ['overprobationary','adj','Excessively probationary','too trial','C1'],
      ['ultraprobationary','adj','Extremely probationary','very trial','C1'],
      ['redundantly','adv','In a redundant manner','surplus way','B2'],
      ['redundantness','n','The quality of being redundant','surplus quality','B2'],
      ['redundantity','n','The state of being redundant','surplus condition','C1'],
      ['unredundant','adj','Not redundant','not surplus','B2'],
      ['inredundant','adj','Not redundant','not surplus','C1'],
      ['nonredundant','adj','Not redundant','not surplus','B2'],
      ['semiredundant','adj','Partially redundant','partly surplus','C1'],
      ['overredundant','adj','Excessively redundant','too surplus','C1'],
      ['ultraredundant','adj','Extremely redundant','very surplus','C1'],
      ['vocationality','n','The state of being vocational','occupational condition','C1'],
      ['invocational','adj','Not vocational','not occupational','C1'],
      ['nonvocational','adj','Not vocational','not occupational','B2'],
      ['semivocational','adj','Partially vocational','partly occupational','C1'],
      ['overvocational','adj','Excessively vocational','too occupational','C1'],
      ['ultravocational','adj','Extremely vocational','very occupational','C1'],
      ['portfolio career','n','Working in multiple jobs simultaneously','multi-job,diverse employment','C1'],
      ['portfolio careeral','adj','Relating to portfolio career','multi-job-related,pertaining to','C1'],
      ['portfolio careeric','adj','Of or relating to portfolio career','multi-job-based,characteristic','C1'],
      ['portfolio careerous','adj','Full of portfolio career','multi-job-filled,abundant','C2'],
      ['portfolio careerful','adj','Full of portfolio career','multi-job-rich,abounding','C1'],
      ['portfolio careerless','adj','Without portfolio career','lacking,without','C1'],
      ['portfolio careerism','n','The ideology of portfolio career','multi-job ideology,doctrine','C2'],
      ['portfolio careerist','n','A person focused on portfolio career','multi-job specialist,advocate','C2'],
      ['portfolio careerise','v','To make into portfolio career','multi-job,convert','C2'],
      ['portfolio careerize','v','To make or become portfolio career','multi-job,transform','C2'],
      ['antiportfolio career','adj','Opposed to portfolio career','against,opposing','C2'],
      ['nonportfolio career','adj','Not involving portfolio career','without,lacking','C1'],
      ['preportfolio career','n','Before portfolio career','preceding,prior','C2'],
      ['postportfolio career','n','After portfolio career','following,subsequent','C2'],
      ['subportfolio career','n','A subdivision of portfolio career','subset,branch','C2'],
      ['multiportfolio career','adj','Involving many portfolio careers','multiple,several','C2'],
      ['interportfolio career','adj','Between portfolio careers','cross,between','C2'],
      ['absenteeismic','adj','Of or relating to absenteeism','truancy-based,characteristic','B2'],
      ['absenteeismous','adj','Full of absenteeism','truancy-filled,abundant','C1'],
      ['absenteeismful','adj','Full of absenteeism','truancy-rich,abounding','B2'],
      ['absenteeismless','adj','Without absenteeism','lacking,without','B2'],
      ['absenteeismism','n','The ideology of absenteeism','truancy ideology,doctrine','C1'],
      ['absenteeismist','n','A person focused on absenteeism','truancy specialist,advocate','C1'],
      ['absenteeismise','v','To make into absenteeism','truancy,convert','C1'],
      ['absenteeismize','v','To make or become absenteeism','truancy,transform','C1'],
      ['antiabsenteeism','adj','Opposed to absenteeism','against,opposing','C1'],
      ['nonabsenteeism','adj','Not involving absenteeism','without,lacking','B2'],
      ['preabsenteeism','n','Before absenteeism','preceding,prior','C1'],
      ['postabsenteeism','n','After absenteeism','following,subsequent','C1'],
      ['subabsenteeism','n','A subdivision of absenteeism','subset,branch','C1'],
      ['multiabsenteeism','adj','Involving many absenteeisms','multiple,several','C1'],
      ['interabsenteeism','adj','Between absenteeisms','cross,between','C1'],
      ['redundancyic','adj','Of or relating to redundancy','layoff-based,characteristic','B2'],
      ['redundancyous','adj','Full of redundancy','layoff-filled,abundant','C1'],
      ['redundancyful','adj','Full of redundancy','layoff-rich,abounding','B2'],
      ['redundancyless','adj','Without redundancy','lacking,without','B2'],
      ['redundancyism','n','The ideology of redundancy','layoff ideology,doctrine','C1'],
      ['redundancyist','n','A person focused on redundancy','layoff specialist,advocate','C1'],
      ['redundancyise','v','To make into redundancy','layoff,convert','C1'],
      ['redundancyize','v','To make or become redundancy','layoff,transform','C1'],
      ['antiredundancy','adj','Opposed to redundancy','against,opposing','C1'],
      ['nonredundancy','adj','Not involving redundancy','without,lacking','B2'],
      ['preredundancy','n','Before redundancy','preceding,prior','C1'],
      ['postredundancy','n','After redundancy','following,subsequent','C1'],
      ['subredundancy','n','A subdivision of redundancy','subset,branch','C1'],
      ['multiredundancy','adj','Involving many redundancys','multiple,several','C1'],
      ['interredundancy','adj','Between redundancys','cross,between','C1'],
      ['apprenticeshipal','adj','Relating to apprenticeship','training-related,pertaining to','B2'],
      ['apprenticeshipic','adj','Of or relating to apprenticeship','training-based,characteristic','B2'],
      ['apprenticeshipous','adj','Full of apprenticeship','training-filled,abundant','C1'],
      ['apprenticeshipful','adj','Full of apprenticeship','training-rich,abounding','B2'],
      ['apprenticeshipless','adj','Without apprenticeship','lacking,without','B2'],
      ['apprenticeshipism','n','The ideology of apprenticeship','training ideology,doctrine','C1'],
      ['apprenticeshipist','n','A person focused on apprenticeship','training specialist,advocate','C1'],
      ['apprenticeshipise','v','To make into apprenticeship','training,convert','C1'],
      ['apprenticeshipize','v','To make or become apprenticeship','training,transform','C1'],
      ['antiapprenticeship','adj','Opposed to apprenticeship','against,opposing','C1'],
    ],
  },
  collocations: {}
};
