// Auto-generated vocab boost group 78
module.exports = {
  vocab: {
    housing: [
      ['overdetached','adj','Excessively detached','too separate','B2'],
      ['ultradetached','adj','Extremely detached','very separate','B2'],
      ['landlordic','adj','Of or relating to landlord','property owner-based,characteristic','B1'],
      ['landlordous','adj','Full of landlord','property owner-filled,abundant','B2'],
      ['landlordful','adj','Full of landlord','property owner-rich,abounding','B1'],
      ['landlordless','adj','Without landlord','lacking,without','B1'],
      ['landlordism','n','The ideology of landlord','property owner ideology,doctrine','B2'],
      ['landlordist','n','A person focused on landlord','property owner specialist,advocate','B2'],
      ['landlordise','v','To make into landlord','property owner,convert','B2'],
      ['landlordize','v','To make or become landlord','property owner,transform','B2'],
      ['antilandlord','adj','Opposed to landlord','against,opposing','B2'],
      ['nonlandlord','adj','Not involving landlord','without,lacking','B1'],
      ['prelandlord','n','Before landlord','preceding,prior','B2'],
      ['postlandlord','n','After landlord','following,subsequent','B2'],
      ['sublandlord','n','A subdivision of landlord','subset,branch','B2'],
      ['multilandlord','adj','Involving many landlords','multiple,several','B2'],
      ['interlandlord','adj','Between landlords','cross,between','B2'],
      ['blueprintal','adj','Relating to blueprint','plan-related,pertaining to','B2'],
      ['blueprintic','adj','Of or relating to blueprint','plan-based,characteristic','B2'],
      ['blueprintous','adj','Full of blueprint','plan-filled,abundant','C1'],
      ['blueprintful','adj','Full of blueprint','plan-rich,abounding','B2'],
      ['blueprintless','adj','Without blueprint','lacking,without','B2'],
      ['blueprintism','n','The ideology of blueprint','plan ideology,doctrine','C1'],
      ['blueprintist','n','A person focused on blueprint','plan specialist,advocate','C1'],
      ['blueprintise','v','To make into blueprint','plan,convert','C1'],
      ['blueprintize','v','To make or become blueprint','plan,transform','C1'],
      ['antiblueprint','adj','Opposed to blueprint','against,opposing','C1'],
      ['nonblueprint','adj','Not involving blueprint','without,lacking','B2'],
      ['preblueprint','n','Before blueprint','preceding,prior','C1'],
      ['postblueprint','n','After blueprint','following,subsequent','C1'],
      ['subblueprint','n','A subdivision of blueprint','subset,branch','C1'],
      ['multiblueprint','adj','Involving many blueprints','multiple,several','C1'],
      ['interblueprint','adj','Between blueprints','cross,between','C1'],
      ['squatal','adj','Relating to squat','illegal occupation-related,pertaining to','C1'],
      ['squatic','adj','Of or relating to squat','illegal occupation-based,characteristic','C1'],
      ['squatous','adj','Full of squat','illegal occupation-filled,abundant','C2'],
      ['squatful','adj','Full of squat','illegal occupation-rich,abounding','C1'],
      ['squatless','adj','Without squat','lacking,without','C1'],
      ['squatism','n','The ideology of squat','illegal occupation ideology,doctrine','C2'],
      ['squatist','n','A person focused on squat','illegal occupation specialist,advocate','C2'],
      ['squatise','v','To make into squat','illegal occupation,convert','C2'],
      ['squatize','v','To make or become squat','illegal occupation,transform','C2'],
      ['antisquat','adj','Opposed to squat','against,opposing','C2'],
      ['nonsquat','adj','Not involving squat','without,lacking','C1'],
      ['presquat','n','Before squat','preceding,prior','C2'],
      ['postsquat','n','After squat','following,subsequent','C2'],
      ['subsquat','n','A subdivision of squat','subset,branch','C2'],
      ['multisquat','adj','Involving many squats','multiple,several','C2'],
      ['intersquat','adj','Between squats','cross,between','C2'],
      ['evictional','adj','Relating to eviction','removal-related,pertaining to','B2'],
      ['evictionic','adj','Of or relating to eviction','removal-based,characteristic','B2'],
      ['evictionous','adj','Full of eviction','removal-filled,abundant','C1'],
      ['evictionful','adj','Full of eviction','removal-rich,abounding','B2'],
      ['evictionless','adj','Without eviction','lacking,without','B2'],
      ['evictionism','n','The ideology of eviction','removal ideology,doctrine','C1'],
      ['evictionist','n','A person focused on eviction','removal specialist,advocate','C1'],
      ['evictionise','v','To make into eviction','removal,convert','C1'],
      ['evictionize','v','To make or become eviction','removal,transform','C1'],
      ['antieviction','adj','Opposed to eviction','against,opposing','C1'],
      ['noneviction','adj','Not involving eviction','without,lacking','B2'],
      ['preeviction','n','Before eviction','preceding,prior','C1'],
      ['posteviction','n','After eviction','following,subsequent','C1'],
      ['subeviction','n','A subdivision of eviction','subset,branch','C1'],
      ['multieviction','adj','Involving many evictions','multiple,several','C1'],
      ['intereviction','adj','Between evictions','cross,between','C1'],
      ['condominiumal','adj','Relating to condominium','condo-related,pertaining to','B2'],
      ['condominiumic','adj','Of or relating to condominium','condo-based,characteristic','B2'],
      ['condominiumous','adj','Full of condominium','condo-filled,abundant','C1'],
      ['condominiumful','adj','Full of condominium','condo-rich,abounding','B2'],
      ['condominiumless','adj','Without condominium','lacking,without','B2'],
      ['condominiumism','n','The ideology of condominium','condo ideology,doctrine','C1'],
      ['condominiumist','n','A person focused on condominium','condo specialist,advocate','C1'],
      ['condominiumise','v','To make into condominium','condo,convert','C1'],
      ['condominiumize','v','To make or become condominium','condo,transform','C1'],
      ['anticondominium','adj','Opposed to condominium','against,opposing','C1'],
      ['noncondominium','adj','Not involving condominium','without,lacking','B2'],
      ['precondominium','n','Before condominium','preceding,prior','C1'],
      ['postcondominium','n','After condominium','following,subsequent','C1'],
      ['subcondominium','n','A subdivision of condominium','subset,branch','C1'],
      ['multicondominium','adj','Involving many condominiums','multiple,several','C1'],
      ['intercondominium','adj','Between condominiums','cross,between','C1'],
      ['skyscraper','n','A very tall building','tower,high-rise,tall building','B1'],
      ['skyscraperal','adj','Relating to skyscraper','tower-related,pertaining to','B1'],
      ['skyscraperic','adj','Of or relating to skyscraper','tower-based,characteristic','B1'],
      ['skyscraperous','adj','Full of skyscraper','tower-filled,abundant','B2'],
      ['skyscraperful','adj','Full of skyscraper','tower-rich,abounding','B1'],
      ['skyscraperless','adj','Without skyscraper','lacking,without','B1'],
      ['skyscraperism','n','The ideology of skyscraper','tower ideology,doctrine','B2'],
      ['skyscraperist','n','A person focused on skyscraper','tower specialist,advocate','B2'],
      ['skyscraperise','v','To make into skyscraper','tower,convert','B2'],
      ['skyscraperize','v','To make or become skyscraper','tower,transform','B2'],
      ['antiskyscraper','adj','Opposed to skyscraper','against,opposing','B2'],
      ['nonskyscraper','adj','Not involving skyscraper','without,lacking','B1'],
      ['preskyscraper','n','Before skyscraper','preceding,prior','B2'],
      ['postskyscraper','n','After skyscraper','following,subsequent','B2'],
      ['subskyscraper','n','A subdivision of skyscraper','subset,branch','B2'],
      ['multiskyscraper','adj','Involving many skyscrapers','multiple,several','B2'],
      ['interskyscraper','adj','Between skyscrapers','cross,between','B2'],
      ['dormitory','n','A large room with many beds','hall of residence,student housing','B1'],
      ['dormitoryal','adj','Relating to dormitory','hall of residence-related,pertaining to','B1'],
      ['dormitoryic','adj','Of or relating to dormitory','hall of residence-based,characteristic','B1'],
      ['dormitoryous','adj','Full of dormitory','hall of residence-filled,abundant','B2'],
      ['dormitoryful','adj','Full of dormitory','hall of residence-rich,abounding','B1'],
      ['dormitoryless','adj','Without dormitory','lacking,without','B1'],
      ['dormitoryism','n','The ideology of dormitory','hall of residence ideology,doctrine','B2'],
      ['dormitoryist','n','A person focused on dormitory','hall of residence specialist,advocate','B2'],
      ['dormitoryise','v','To make into dormitory','hall of residence,convert','B2'],
      ['dormitoryize','v','To make or become dormitory','hall of residence,transform','B2'],
      ['antidormitory','adj','Opposed to dormitory','against,opposing','B2'],
      ['nondormitory','adj','Not involving dormitory','without,lacking','B1'],
      ['predormitory','n','Before dormitory','preceding,prior','B2'],
      ['postdormitory','n','After dormitory','following,subsequent','B2'],
      ['subdormitory','n','A subdivision of dormitory','subset,branch','B2'],
      ['multidormitory','adj','Involving many dormitorys','multiple,several','B2'],
      ['interdormitory','adj','Between dormitorys','cross,between','B2'],
      ['penthouseal','adj','Relating to penthouse','luxury flat-related,pertaining to','B2'],
      ['penthouseic','adj','Of or relating to penthouse','luxury flat-based,characteristic','B2'],
      ['penthouseous','adj','Full of penthouse','luxury flat-filled,abundant','C1'],
      ['penthouseful','adj','Full of penthouse','luxury flat-rich,abounding','B2'],
      ['penthouseless','adj','Without penthouse','lacking,without','B2'],
      ['penthouseism','n','The ideology of penthouse','luxury flat ideology,doctrine','C1'],
      ['penthouseist','n','A person focused on penthouse','luxury flat specialist,advocate','C1'],
      ['penthouseise','v','To make into penthouse','luxury flat,convert','C1'],
      ['penthouseize','v','To make or become penthouse','luxury flat,transform','C1'],
      ['antipenthouse','adj','Opposed to penthouse','against,opposing','C1'],
      ['nonpenthouse','adj','Not involving penthouse','without,lacking','B2'],
      ['prepenthouse','n','Before penthouse','preceding,prior','C1'],
      ['postpenthouse','n','After penthouse','following,subsequent','C1'],
      ['subpenthouse','n','A subdivision of penthouse','subset,branch','C1'],
      ['multipenthouse','adj','Involving many penthouses','multiple,several','C1'],
      ['interpenthouse','adj','Between penthouses','cross,between','C1'],
      ['shantytown','n','A settlement of improvised dwellings','slum,informal settlement,squatter camp','B2'],
      ['shantytownal','adj','Relating to shantytown','slum-related,pertaining to','B2'],
      ['shantytownic','adj','Of or relating to shantytown','slum-based,characteristic','B2'],
      ['shantytownous','adj','Full of shantytown','slum-filled,abundant','C1'],
      ['shantytownful','adj','Full of shantytown','slum-rich,abounding','B2'],
      ['shantytownless','adj','Without shantytown','lacking,without','B2'],
      ['shantytownism','n','The ideology of shantytown','slum ideology,doctrine','C1'],
      ['shantytownist','n','A person focused on shantytown','slum specialist,advocate','C1'],
      ['shantytownise','v','To make into shantytown','slum,convert','C1'],
      ['shantytownize','v','To make or become shantytown','slum,transform','C1'],
      ['antishantytown','adj','Opposed to shantytown','against,opposing','C1'],
      ['nonshantytown','adj','Not involving shantytown','without,lacking','B2'],
      ['preshantytown','n','Before shantytown','preceding,prior','C1'],
      ['postshantytown','n','After shantytown','following,subsequent','C1'],
      ['subshantytown','n','A subdivision of shantytown','subset,branch','C1'],
      ['multishantytown','adj','Involving many shantytowns','multiple,several','C1'],
      ['intershantytown','adj','Between shantytowns','cross,between','C1'],
      ['brownfieldic','adj','Of or relating to brownfield','redevelopment site-based,characteristic','C1'],
      ['brownfieldous','adj','Full of brownfield','redevelopment site-filled,abundant','C2'],
      ['brownfieldful','adj','Full of brownfield','redevelopment site-rich,abounding','C1'],
      ['brownfieldless','adj','Without brownfield','lacking,without','C1'],
      ['brownfieldism','n','The ideology of brownfield','redevelopment site ideology,doctrine','C2'],
      ['brownfieldist','n','A person focused on brownfield','redevelopment site specialist,advocate','C2'],
      ['brownfieldise','v','To make into brownfield','redevelopment site,convert','C2'],
      ['brownfieldize','v','To make or become brownfield','redevelopment site,transform','C2'],
      ['antibrownfield','adj','Opposed to brownfield','against,opposing','C2'],
      ['nonbrownfield','adj','Not involving brownfield','without,lacking','C1'],
      ['prebrownfield','n','Before brownfield','preceding,prior','C2'],
      ['postbrownfield','n','After brownfield','following,subsequent','C2'],
      ['subbrownfield','n','A subdivision of brownfield','subset,branch','C2'],
      ['multibrownfield','adj','Involving many brownfields','multiple,several','C2'],
      ['interbrownfield','adj','Between brownfields','cross,between','C2'],
      ['greenfield','n','Undeveloped land for new building','virgin land,undeveloped site','C1'],
      ['greenfieldal','adj','Relating to greenfield','virgin land-related,pertaining to','C1'],
      ['greenfieldic','adj','Of or relating to greenfield','virgin land-based,characteristic','C1'],
      ['greenfieldous','adj','Full of greenfield','virgin land-filled,abundant','C2'],
      ['greenfieldful','adj','Full of greenfield','virgin land-rich,abounding','C1'],
      ['greenfieldless','adj','Without greenfield','lacking,without','C1'],
      ['greenfieldism','n','The ideology of greenfield','virgin land ideology,doctrine','C2'],
      ['greenfieldist','n','A person focused on greenfield','virgin land specialist,advocate','C2'],
      ['greenfieldise','v','To make into greenfield','virgin land,convert','C2'],
      ['greenfieldize','v','To make or become greenfield','virgin land,transform','C2'],
      ['antigreenfield','adj','Opposed to greenfield','against,opposing','C2'],
      ['nongreenfield','adj','Not involving greenfield','without,lacking','C1'],
      ['pregreenfield','n','Before greenfield','preceding,prior','C2'],
      ['postgreenfield','n','After greenfield','following,subsequent','C2'],
      ['subgreenfield','n','A subdivision of greenfield','subset,branch','C2'],
      ['multigreenfield','adj','Involving many greenfields','multiple,several','C2'],
      ['intergreenfield','adj','Between greenfields','cross,between','C2'],
      ['cohabitational','adj','Relating to cohabitation','living together-related,pertaining to','B2'],
      ['cohabitationic','adj','Of or relating to cohabitation','living together-based,characteristic','B2'],
      ['cohabitationous','adj','Full of cohabitation','living together-filled,abundant','C1'],
      ['cohabitationful','adj','Full of cohabitation','living together-rich,abounding','B2'],
      ['cohabitationless','adj','Without cohabitation','lacking,without','B2'],
      ['cohabitationism','n','The ideology of cohabitation','living together ideology,doctrine','C1'],
      ['cohabitationist','n','A person focused on cohabitation','living together specialist,advocate','C1'],
      ['cohabitationise','v','To make into cohabitation','living together,convert','C1'],
      ['cohabitationize','v','To make or become cohabitation','living together,transform','C1'],
      ['anticohabitation','adj','Opposed to cohabitation','against,opposing','C1'],
      ['noncohabitation','adj','Not involving cohabitation','without,lacking','B2'],
      ['precohabitation','n','Before cohabitation','preceding,prior','C1'],
      ['postcohabitation','n','After cohabitation','following,subsequent','C1'],
      ['subcohabitation','n','A subdivision of cohabitation','subset,branch','C1'],
      ['multicohabitation','adj','Involving many cohabitations','multiple,several','C1'],
      ['intercohabitation','adj','Between cohabitations','cross,between','C1'],
      ['foreclosureal','adj','Relating to foreclosure','repossession-related,pertaining to','C1'],
      ['foreclosureic','adj','Of or relating to foreclosure','repossession-based,characteristic','C1'],
      ['foreclosureous','adj','Full of foreclosure','repossession-filled,abundant','C2'],
      ['foreclosureful','adj','Full of foreclosure','repossession-rich,abounding','C1'],
      ['foreclosureless','adj','Without foreclosure','lacking,without','C1'],
      ['foreclosureism','n','The ideology of foreclosure','repossession ideology,doctrine','C2'],
      ['foreclosureist','n','A person focused on foreclosure','repossession specialist,advocate','C2'],
      ['foreclosureise','v','To make into foreclosure','repossession,convert','C2'],
      ['foreclosureize','v','To make or become foreclosure','repossession,transform','C2'],
      ['antiforeclosure','adj','Opposed to foreclosure','against,opposing','C2'],
      ['nonforeclosure','adj','Not involving foreclosure','without,lacking','C1'],
      ['preforeclosure','n','Before foreclosure','preceding,prior','C2'],
      ['postforeclosure','n','After foreclosure','following,subsequent','C2'],
      ['subforeclosure','n','A subdivision of foreclosure','subset,branch','C2'],
      ['multiforeclosure','adj','Involving many foreclosures','multiple,several','C2'],
      ['interforeclosure','adj','Between foreclosures','cross,between','C2'],
      ['subsidenceal','adj','Relating to subsidence','sinking-related,pertaining to','C1'],
      ['subsidenceic','adj','Of or relating to subsidence','sinking-based,characteristic','C1'],
      ['subsidenceous','adj','Full of subsidence','sinking-filled,abundant','C2'],
      ['subsidenceful','adj','Full of subsidence','sinking-rich,abounding','C1'],
      ['subsidenceless','adj','Without subsidence','lacking,without','C1'],
      ['subsidenceism','n','The ideology of subsidence','sinking ideology,doctrine','C2'],
      ['subsidenceist','n','A person focused on subsidence','sinking specialist,advocate','C2'],
      ['subsidenceise','v','To make into subsidence','sinking,convert','C2'],
      ['subsidenceize','v','To make or become subsidence','sinking,transform','C2'],
      ['antisubsidence','adj','Opposed to subsidence','against,opposing','C2'],
      ['nonsubsidence','adj','Not involving subsidence','without,lacking','C1'],
      ['presubsidence','n','Before subsidence','preceding,prior','C2'],
      ['postsubsidence','n','After subsidence','following,subsequent','C2'],
      ['subsubsidence','n','A subdivision of subsidence','subset,branch','C2'],
      ['multisubsidence','adj','Involving many subsidences','multiple,several','C2'],
      ['intersubsidence','adj','Between subsidences','cross,between','C2'],
      ['sprawl','n','Uncontrolled expansion of urban areas','spread,expansion,growth','B2'],
      ['sprawlal','adj','Relating to sprawl','spread-related,pertaining to','B2'],
      ['sprawlic','adj','Of or relating to sprawl','spread-based,characteristic','B2'],
      ['sprawlous','adj','Full of sprawl','spread-filled,abundant','C1'],
      ['sprawlful','adj','Full of sprawl','spread-rich,abounding','B2'],
      ['sprawlless','adj','Without sprawl','lacking,without','B2'],
      ['sprawlism','n','The ideology of sprawl','spread ideology,doctrine','C1'],
      ['sprawlist','n','A person focused on sprawl','spread specialist,advocate','C1'],
      ['sprawlise','v','To make into sprawl','spread,convert','C1'],
      ['sprawlize','v','To make or become sprawl','spread,transform','C1'],
      ['antisprawl','adj','Opposed to sprawl','against,opposing','C1'],
      ['nonsprawl','adj','Not involving sprawl','without,lacking','B2'],
      ['presprawl','n','Before sprawl','preceding,prior','C1'],
      ['postsprawl','n','After sprawl','following,subsequent','C1'],
      ['subsprawl','n','A subdivision of sprawl','subset,branch','C1'],
      ['multisprawl','adj','Involving many sprawls','multiple,several','C1'],
      ['intersprawl','adj','Between sprawls','cross,between','C1'],
      ['modularity','n','The state of being modular','prefabricated condition','C1'],
      ['inmodular','adj','Not modular','not prefabricated','C1'],
      ['nonmodular','adj','Not modular','not prefabricated','B2'],
      ['semimodular','adj','Partially modular','partly prefabricated','C1'],
      ['overmodular','adj','Excessively modular','too prefabricated','C1'],
    ],
  },
  collocations: {}
};
