// Auto-generated vocab boost group 69
module.exports = {
  vocab: {
    psychology: [
      ['multiempathy','adj','Involving many empathys','multiple,several','C1'],
      ['interempathy','adj','Between empathys','cross,between','C1'],
      ['stimulusic','adj','Of or relating to stimulus','trigger-based,characteristic','B2'],
      ['stimulusous','adj','Full of stimulus','trigger-filled,abundant','C1'],
      ['stimulusful','adj','Full of stimulus','trigger-rich,abounding','B2'],
      ['stimulusless','adj','Without stimulus','lacking,without','B2'],
      ['stimulusism','n','The ideology of stimulus','trigger ideology,doctrine','C1'],
      ['stimulusist','n','A person focused on stimulus','trigger specialist,advocate','C1'],
      ['stimulusise','v','To make into stimulus','trigger,convert','C1'],
      ['stimulusize','v','To make or become stimulus','trigger,transform','C1'],
      ['antistimulus','adj','Opposed to stimulus','against,opposing','C1'],
      ['nonstimulus','adj','Not involving stimulus','without,lacking','B2'],
      ['prestimulus','n','Before stimulus','preceding,prior','C1'],
      ['poststimulus','n','After stimulus','following,subsequent','C1'],
      ['substimulus','n','A subdivision of stimulus','subset,branch','C1'],
      ['multistimulus','adj','Involving many stimuluss','multiple,several','C1'],
      ['interstimulus','adj','Between stimuluss','cross,between','C1'],
      ['psychosomaticly','adv','In a psychosomatic manner','mind-body way','C1'],
      ['psychosomaticness','n','The quality of being psychosomatic','mind-body quality','C1'],
      ['psychosomaticity','n','The state of being psychosomatic','mind-body condition','C2'],
      ['unpsychosomatic','adj','Not psychosomatic','not mind-body','C1'],
      ['inpsychosomatic','adj','Not psychosomatic','not mind-body','C2'],
      ['nonpsychosomatic','adj','Not psychosomatic','not mind-body','C1'],
      ['semipsychosomatic','adj','Partially psychosomatic','partly mind-body','C2'],
      ['overpsychosomatic','adj','Excessively psychosomatic','too mind-body','C2'],
      ['ultrapsychosomatic','adj','Extremely psychosomatic','very mind-body','C2'],
      ['subconsciousity','n','The state of being subconscious','unconscious condition','C1'],
      ['insubconscious','adj','Not subconscious','not unconscious','C1'],
      ['nonsubconscious','adj','Not subconscious','not unconscious','B2'],
      ['semisubconscious','adj','Partially subconscious','partly unconscious','C1'],
      ['oversubconscious','adj','Excessively subconscious','too unconscious','C1'],
      ['ultrasubconscious','adj','Extremely subconscious','very unconscious','C1'],
      ['cognitiveity','n','The state of being cognitive','intellectual condition','C1'],
      ['incognitive','adj','Not cognitive','not intellectual','C1'],
      ['noncognitive','adj','Not cognitive','not intellectual','B2'],
      ['semicognitive','adj','Partially cognitive','partly intellectual','C1'],
      ['overcognitive','adj','Excessively cognitive','too intellectual','C1'],
      ['ultracognitive','adj','Extremely cognitive','very intellectual','C1'],
      ['behaviourally','adv','In a behavioural manner','conduct-related way','B2'],
      ['behaviouralness','n','The quality of being behavioural','conduct-related quality','B2'],
      ['behaviourality','n','The state of being behavioural','conduct-related condition','C1'],
      ['unbehavioural','adj','Not behavioural','not conduct-related','B2'],
      ['inbehavioural','adj','Not behavioural','not conduct-related','C1'],
      ['nonbehavioural','adj','Not behavioural','not conduct-related','B2'],
      ['semibehavioural','adj','Partially behavioural','partly conduct-related','C1'],
      ['overbehavioural','adj','Excessively behavioural','too conduct-related','C1'],
      ['ultrabehavioural','adj','Extremely behavioural','very conduct-related','C1'],
      ['altruisticly','adv','In a altruistic manner','selfless way','C1'],
      ['altruisticness','n','The quality of being altruistic','selfless quality','C1'],
      ['altruisticity','n','The state of being altruistic','selfless condition','C2'],
      ['unaltruistic','adj','Not altruistic','not selfless','C1'],
      ['inaltruistic','adj','Not altruistic','not selfless','C2'],
      ['nonaltruistic','adj','Not altruistic','not selfless','C1'],
      ['semialtruistic','adj','Partially altruistic','partly selfless','C2'],
      ['overaltruistic','adj','Excessively altruistic','too selfless','C2'],
      ['ultraaltruistic','adj','Extremely altruistic','very selfless','C2'],
      ['narcissistic','adj','Having excessive self-admiration','self-centred,vain,egotistical','C1'],
      ['narcissisticly','adv','In a narcissistic manner','self-centred way','C1'],
      ['narcissisticness','n','The quality of being narcissistic','self-centred quality','C1'],
      ['narcissisticity','n','The state of being narcissistic','self-centred condition','C2'],
      ['unnarcissistic','adj','Not narcissistic','not self-centred','C1'],
      ['innarcissistic','adj','Not narcissistic','not self-centred','C2'],
      ['nonnarcissistic','adj','Not narcissistic','not self-centred','C1'],
      ['seminarcissistic','adj','Partially narcissistic','partly self-centred','C2'],
      ['overnarcissistic','adj','Excessively narcissistic','too self-centred','C2'],
      ['ultranarcissistic','adj','Extremely narcissistic','very self-centred','C2'],
      ['compulsively','adv','In a compulsive manner','obsessive way','B2'],
      ['compulsiveness','n','The quality of being compulsive','obsessive quality','B2'],
      ['compulsiveity','n','The state of being compulsive','obsessive condition','C1'],
      ['uncompulsive','adj','Not compulsive','not obsessive','B2'],
      ['incompulsive','adj','Not compulsive','not obsessive','C1'],
      ['noncompulsive','adj','Not compulsive','not obsessive','B2'],
      ['semicompulsive','adj','Partially compulsive','partly obsessive','C1'],
      ['overcompulsive','adj','Excessively compulsive','too obsessive','C1'],
      ['ultracompulsive','adj','Extremely compulsive','very obsessive','C1'],
      ['catharsisic','adj','Of or relating to catharsis','release-based,characteristic','C1'],
      ['catharsisous','adj','Full of catharsis','release-filled,abundant','C2'],
      ['catharsisful','adj','Full of catharsis','release-rich,abounding','C1'],
      ['catharsisless','adj','Without catharsis','lacking,without','C1'],
      ['catharsisism','n','The ideology of catharsis','release ideology,doctrine','C2'],
      ['catharsisist','n','A person focused on catharsis','release specialist,advocate','C2'],
      ['catharsisise','v','To make into catharsis','release,convert','C2'],
      ['catharsisize','v','To make or become catharsis','release,transform','C2'],
      ['anticatharsis','adj','Opposed to catharsis','against,opposing','C2'],
      ['noncatharsis','adj','Not involving catharsis','without,lacking','C1'],
      ['precatharsis','n','Before catharsis','preceding,prior','C2'],
      ['postcatharsis','n','After catharsis','following,subsequent','C2'],
      ['subcatharsis','n','A subdivision of catharsis','subset,branch','C2'],
      ['multicatharsis','adj','Involving many catharsiss','multiple,several','C2'],
      ['intercatharsis','adj','Between catharsiss','cross,between','C2'],
      ['placeboal','adj','Relating to placebo','sugar pill-related,pertaining to','B2'],
      ['placeboic','adj','Of or relating to placebo','sugar pill-based,characteristic','B2'],
      ['placeboous','adj','Full of placebo','sugar pill-filled,abundant','C1'],
      ['placeboful','adj','Full of placebo','sugar pill-rich,abounding','B2'],
      ['placeboless','adj','Without placebo','lacking,without','B2'],
      ['placeboism','n','The ideology of placebo','sugar pill ideology,doctrine','C1'],
      ['placeboist','n','A person focused on placebo','sugar pill specialist,advocate','C1'],
      ['placeboise','v','To make into placebo','sugar pill,convert','C1'],
      ['placeboize','v','To make or become placebo','sugar pill,transform','C1'],
      ['antiplacebo','adj','Opposed to placebo','against,opposing','C1'],
      ['nonplacebo','adj','Not involving placebo','without,lacking','B2'],
      ['preplacebo','n','Before placebo','preceding,prior','C1'],
      ['postplacebo','n','After placebo','following,subsequent','C1'],
      ['subplacebo','n','A subdivision of placebo','subset,branch','C1'],
      ['multiplacebo','adj','Involving many placebos','multiple,several','C1'],
      ['interplacebo','adj','Between placebos','cross,between','C1'],
      ['conditioningic','adj','Of or relating to conditioning','training-based,characteristic','B2'],
      ['conditioningous','adj','Full of conditioning','training-filled,abundant','C1'],
      ['conditioningful','adj','Full of conditioning','training-rich,abounding','B2'],
      ['conditioningless','adj','Without conditioning','lacking,without','B2'],
      ['conditioningism','n','The ideology of conditioning','training ideology,doctrine','C1'],
      ['conditioningist','n','A person focused on conditioning','training specialist,advocate','C1'],
      ['conditioningise','v','To make into conditioning','training,convert','C1'],
      ['conditioningize','v','To make or become conditioning','training,transform','C1'],
      ['anticonditioning','adj','Opposed to conditioning','against,opposing','C1'],
      ['nonconditioning','adj','Not involving conditioning','without,lacking','B2'],
      ['preconditioning','n','Before conditioning','preceding,prior','C1'],
      ['postconditioning','n','After conditioning','following,subsequent','C1'],
      ['subconditioning','n','A subdivision of conditioning','subset,branch','C1'],
      ['multiconditioning','adj','Involving many conditionings','multiple,several','C1'],
      ['interconditioning','adj','Between conditionings','cross,between','C1'],
      ['inhibition','n','A feeling preventing natural behaviour','restraint,reserve,self-consciousness','B2'],
      ['inhibitional','adj','Relating to inhibition','restraint-related,pertaining to','B2'],
      ['inhibitionic','adj','Of or relating to inhibition','restraint-based,characteristic','B2'],
      ['inhibitionous','adj','Full of inhibition','restraint-filled,abundant','C1'],
      ['inhibitionful','adj','Full of inhibition','restraint-rich,abounding','B2'],
      ['inhibitionless','adj','Without inhibition','lacking,without','B2'],
      ['inhibitionism','n','The ideology of inhibition','restraint ideology,doctrine','C1'],
      ['inhibitionist','n','A person focused on inhibition','restraint specialist,advocate','C1'],
      ['inhibitionise','v','To make into inhibition','restraint,convert','C1'],
      ['inhibitionize','v','To make or become inhibition','restraint,transform','C1'],
      ['antiinhibition','adj','Opposed to inhibition','against,opposing','C1'],
      ['noninhibition','adj','Not involving inhibition','without,lacking','B2'],
      ['preinhibition','n','Before inhibition','preceding,prior','C1'],
      ['postinhibition','n','After inhibition','following,subsequent','C1'],
      ['subinhibition','n','A subdivision of inhibition','subset,branch','C1'],
      ['multiinhibition','adj','Involving many inhibitions','multiple,several','C1'],
      ['interinhibition','adj','Between inhibitions','cross,between','C1'],
      ['regressional','adj','Relating to regression','relapse-related,pertaining to','C1'],
      ['regressionic','adj','Of or relating to regression','relapse-based,characteristic','C1'],
      ['regressionous','adj','Full of regression','relapse-filled,abundant','C2'],
      ['regressionful','adj','Full of regression','relapse-rich,abounding','C1'],
      ['regressionless','adj','Without regression','lacking,without','C1'],
      ['regressionism','n','The ideology of regression','relapse ideology,doctrine','C2'],
      ['regressionist','n','A person focused on regression','relapse specialist,advocate','C2'],
      ['regressionise','v','To make into regression','relapse,convert','C2'],
      ['regressionize','v','To make or become regression','relapse,transform','C2'],
      ['antiregression','adj','Opposed to regression','against,opposing','C2'],
      ['nonregression','adj','Not involving regression','without,lacking','C1'],
      ['preregression','n','Before regression','preceding,prior','C2'],
      ['postregression','n','After regression','following,subsequent','C2'],
      ['subregression','n','A subdivision of regression','subset,branch','C2'],
      ['multiregression','adj','Involving many regressions','multiple,several','C2'],
      ['interregression','adj','Between regressions','cross,between','C2'],
      ['transferenceic','adj','Of or relating to transference','projection-based,characteristic','C1'],
      ['transferenceous','adj','Full of transference','projection-filled,abundant','C2'],
      ['transferenceful','adj','Full of transference','projection-rich,abounding','C1'],
      ['transferenceless','adj','Without transference','lacking,without','C1'],
      ['transferenceism','n','The ideology of transference','projection ideology,doctrine','C2'],
      ['transferenceist','n','A person focused on transference','projection specialist,advocate','C2'],
      ['transferenceise','v','To make into transference','projection,convert','C2'],
      ['transferenceize','v','To make or become transference','projection,transform','C2'],
      ['antitransference','adj','Opposed to transference','against,opposing','C2'],
      ['nontransference','adj','Not involving transference','without,lacking','C1'],
      ['pretransference','n','Before transference','preceding,prior','C2'],
      ['posttransference','n','After transference','following,subsequent','C2'],
      ['subtransference','n','A subdivision of transference','subset,branch','C2'],
      ['multitransference','adj','Involving many transferences','multiple,several','C2'],
      ['intertransference','adj','Between transferences','cross,between','C2'],
      ['predisposition','n','A tendency to a condition','inclination,susceptibility,proneness','C1'],
      ['predispositional','adj','Relating to predisposition','inclination-related,pertaining to','C1'],
      ['predispositionic','adj','Of or relating to predisposition','inclination-based,characteristic','C1'],
      ['predispositionous','adj','Full of predisposition','inclination-filled,abundant','C2'],
      ['predispositionful','adj','Full of predisposition','inclination-rich,abounding','C1'],
      ['predispositionless','adj','Without predisposition','lacking,without','C1'],
      ['predispositionism','n','The ideology of predisposition','inclination ideology,doctrine','C2'],
      ['predispositionist','n','A person focused on predisposition','inclination specialist,advocate','C2'],
      ['predispositionise','v','To make into predisposition','inclination,convert','C2'],
      ['predispositionize','v','To make or become predisposition','inclination,transform','C2'],
      ['antipredisposition','adj','Opposed to predisposition','against,opposing','C2'],
      ['nonpredisposition','adj','Not involving predisposition','without,lacking','C1'],
      ['prepredisposition','n','Before predisposition','preceding,prior','C2'],
      ['postpredisposition','n','After predisposition','following,subsequent','C2'],
      ['subpredisposition','n','A subdivision of predisposition','subset,branch','C2'],
      ['multipredisposition','adj','Involving many predispositions','multiple,several','C2'],
      ['interpredisposition','adj','Between predispositions','cross,between','C2'],
      ['neuroplasticityic','adj','Of or relating to neuroplasticity','brain adaptability-based,characteristic','C1'],
      ['neuroplasticityous','adj','Full of neuroplasticity','brain adaptability-filled,abundant','C2'],
      ['neuroplasticityful','adj','Full of neuroplasticity','brain adaptability-rich,abounding','C1'],
      ['neuroplasticityless','adj','Without neuroplasticity','lacking,without','C1'],
      ['neuroplasticityism','n','The ideology of neuroplasticity','brain adaptability ideology,doctrine','C2'],
      ['neuroplasticityist','n','A person focused on neuroplasticity','brain adaptability specialist,advocate','C2'],
      ['neuroplasticityise','v','To make into neuroplasticity','brain adaptability,convert','C2'],
      ['neuroplasticityize','v','To make or become neuroplasticity','brain adaptability,transform','C2'],
      ['antineuroplasticity','adj','Opposed to neuroplasticity','against,opposing','C2'],
      ['nonneuroplasticity','adj','Not involving neuroplasticity','without,lacking','C1'],
      ['preneuroplasticity','n','Before neuroplasticity','preceding,prior','C2'],
      ['postneuroplasticity','n','After neuroplasticity','following,subsequent','C2'],
      ['subneuroplasticity','n','A subdivision of neuroplasticity','subset,branch','C2'],
      ['multineuroplasticity','adj','Involving many neuroplasticitys','multiple,several','C2'],
      ['interneuroplasticity','adj','Between neuroplasticitys','cross,between','C2'],
      ['psychometric','adj','Relating to psychological measurement','test-based,assessment-related','C1'],
      ['psychometricly','adv','In a psychometric manner','test-based way','C1'],
      ['psychometricness','n','The quality of being psychometric','test-based quality','C1'],
      ['psychometricity','n','The state of being psychometric','test-based condition','C2'],
      ['unpsychometric','adj','Not psychometric','not test-based','C1'],
      ['inpsychometric','adj','Not psychometric','not test-based','C2'],
      ['nonpsychometric','adj','Not psychometric','not test-based','C1'],
      ['semipsychometric','adj','Partially psychometric','partly test-based','C2'],
      ['overpsychometric','adj','Excessively psychometric','too test-based','C2'],
      ['ultrapsychometric','adj','Extremely psychometric','very test-based','C2'],
      ['extrovertedly','adv','In a extroverted manner','outgoing way','B2'],
      ['extrovertedness','n','The quality of being extroverted','outgoing quality','B2'],
      ['extrovertedity','n','The state of being extroverted','outgoing condition','C1'],
      ['unextroverted','adj','Not extroverted','not outgoing','B2'],
      ['inextroverted','adj','Not extroverted','not outgoing','C1'],
      ['nonextroverted','adj','Not extroverted','not outgoing','B2'],
      ['semiextroverted','adj','Partially extroverted','partly outgoing','C1'],
      ['overextroverted','adj','Excessively extroverted','too outgoing','C1'],
      ['ultraextroverted','adj','Extremely extroverted','very outgoing','C1'],
      ['introvertedly','adv','In a introverted manner','reserved way','B2'],
      ['introvertedness','n','The quality of being introverted','reserved quality','B2'],
      ['introvertedity','n','The state of being introverted','reserved condition','C1'],
      ['unintroverted','adj','Not introverted','not reserved','B2'],
      ['inintroverted','adj','Not introverted','not reserved','C1'],
      ['nonintroverted','adj','Not introverted','not reserved','B2'],
      ['semiintroverted','adj','Partially introverted','partly reserved','C1'],
      ['overintroverted','adj','Excessively introverted','too reserved','C1'],
      ['ultraintroverted','adj','Extremely introverted','very reserved','C1'],
      ['obsessive','adj','Preoccupied with something to excess','fixated,consumed,preoccupied','B2'],
      ['obsessively','adv','In a obsessive manner','fixated way','B2'],
      ['obsessiveness','n','The quality of being obsessive','fixated quality','B2'],
      ['obsessiveity','n','The state of being obsessive','fixated condition','C1'],
      ['unobsessive','adj','Not obsessive','not fixated','B2'],
      ['inobsessive','adj','Not obsessive','not fixated','C1'],
      ['nonobsessive','adj','Not obsessive','not fixated','B2'],
      ['semiobsessive','adj','Partially obsessive','partly fixated','C1'],
      ['overobsessive','adj','Excessively obsessive','too fixated','C1'],
      ['ultraobsessive','adj','Extremely obsessive','very fixated','C1'],
      ['agoraphobiaal','adj','Relating to agoraphobia','space anxiety-related,pertaining to','C1'],
      ['agoraphobiaic','adj','Of or relating to agoraphobia','space anxiety-based,characteristic','C1'],
      ['agoraphobiaous','adj','Full of agoraphobia','space anxiety-filled,abundant','C2'],
      ['agoraphobiaful','adj','Full of agoraphobia','space anxiety-rich,abounding','C1'],
      ['agoraphobialess','adj','Without agoraphobia','lacking,without','C1'],
      ['agoraphobiaism','n','The ideology of agoraphobia','space anxiety ideology,doctrine','C2'],
      ['agoraphobiaist','n','A person focused on agoraphobia','space anxiety specialist,advocate','C2'],
      ['agoraphobiaise','v','To make into agoraphobia','space anxiety,convert','C2'],
      ['agoraphobiaize','v','To make or become agoraphobia','space anxiety,transform','C2'],
      ['antiagoraphobia','adj','Opposed to agoraphobia','against,opposing','C2'],
      ['nonagoraphobia','adj','Not involving agoraphobia','without,lacking','C1'],
    ],
  },
  collocations: {}
};
