// Auto-generated vocab boost group 67
module.exports = {
  vocab: {
    government: [
      ['inincumbent','adj','Not incumbent','not current','C2'],
      ['nonincumbent','adj','Not incumbent','not current','C1'],
      ['semiincumbent','adj','Partially incumbent','partly current','C2'],
      ['overincumbent','adj','Excessively incumbent','too current','C2'],
      ['ultraincumbent','adj','Extremely incumbent','very current','C2'],
      ['filibusteration','n','The act of filibustering','delay process','C2'],
      ['filibusterment','n','The result of filibustering','delay outcome','C2'],
      ['filibusterance','n','The state of filibustering','delay state','C2'],
      ['filibusterence','n','The quality of filibustering','delay quality','C2'],
      ['filibusterer','n','One who filibusters','delay person','C2'],
      ['filibusteror','n','One who filibusters','delay agent','C2'],
      ['filibusteree','n','One who is filibusterd','delay recipient','C2'],
      ['filibusterable','adj','Capable of being filibusterd','delay,possible','C2'],
      ['filibusterible','adj','Able to be filibusterd','delay,feasible','C2'],
      ['filibusterive','adj','Tending to filibuster','delay,active','C2'],
      ['filibustering','adj','Currently filibustering','delay,ongoing','C2'],
      ['filibustered','adj','Having been filibusterd','delay,completed','C2'],
      ['refilibuster','v','To filibuster again','delay again,repeat','C2'],
      ['unfilibuster','v','To reverse filibustering','reverse,undo','C2'],
      ['overfilibuster','v','To filibuster excessively','excess,too much','C2'],
      ['underfilibuster','v','To filibuster insufficiently','insufficient,inadequate','C2'],
      ['misfilibuster','v','To filibuster incorrectly','wrongly,incorrectly','C2'],
      ['prefilibuster','v','To filibuster beforehand','before,in advance','C2'],
      ['cofilibuster','v','To filibuster together','jointly,together','C2'],
      ['refilibusteration','n','The act of filibustering again','re-delay','C2'],
      ['overfilibusteration','n','Excessive filibustering','excess delay','C2'],
      ['lobbyment','n','The result of lobbying','campaign outcome','B2'],
      ['lobbyance','n','The state of lobbying','campaign state','B2'],
      ['lobbyence','n','The quality of lobbying','campaign quality','B2'],
      ['lobbyal','n','An act of lobbying','campaign event','C1'],
      ['lobbyor','n','One who lobbys','campaign agent','B2'],
      ['lobbyee','n','One who is lobbyd','campaign recipient','C1'],
      ['lobbyible','adj','Able to be lobbyd','campaign,feasible','C1'],
      ['lobbyive','adj','Tending to lobby','campaign,active','B2'],
      ['lobbyed','adj','Having been lobbyd','campaign,completed','B2'],
      ['relobby','v','To lobby again','campaign again,repeat','B2'],
      ['unlobby','v','To reverse lobbying','reverse,undo','C1'],
      ['overlobby','v','To lobby excessively','excess,too much','C1'],
      ['underlobby','v','To lobby insufficiently','insufficient,inadequate','C1'],
      ['mislobby','v','To lobby incorrectly','wrongly,incorrectly','C1'],
      ['prelobby','v','To lobby beforehand','before,in advance','C1'],
      ['colobby','v','To lobby together','jointly,together','C1'],
      ['relobbyation','n','The act of lobbying again','re-campaign','C1'],
      ['overlobbyation','n','Excessive lobbying','excess campaign','C1'],
      ['sanctionation','n','The act of sanctioning','penalize process','B2'],
      ['sanctionment','n','The result of sanctioning','penalize outcome','B2'],
      ['sanctionance','n','The state of sanctioning','penalize state','B2'],
      ['sanctionence','n','The quality of sanctioning','penalize quality','B2'],
      ['sanctioner','n','One who sanctions','penalize person','B2'],
      ['sanctionor','n','One who sanctions','penalize agent','B2'],
      ['sanctionee','n','One who is sanctiond','penalize recipient','C1'],
      ['sanctionable','adj','Capable of being sanctiond','penalize,possible','C1'],
      ['sanctionible','adj','Able to be sanctiond','penalize,feasible','C1'],
      ['sanctionive','adj','Tending to sanction','penalize,active','B2'],
      ['sanctioning','adj','Currently sanctioning','penalize,ongoing','B2'],
      ['sanctioned','adj','Having been sanctiond','penalize,completed','B2'],
      ['resanction','v','To sanction again','penalize again,repeat','B2'],
      ['unsanction','v','To reverse sanctioning','reverse,undo','C1'],
      ['oversanction','v','To sanction excessively','excess,too much','C1'],
      ['undersanction','v','To sanction insufficiently','insufficient,inadequate','C1'],
      ['missanction','v','To sanction incorrectly','wrongly,incorrectly','C1'],
      ['presanction','v','To sanction beforehand','before,in advance','C1'],
      ['cosanction','v','To sanction together','jointly,together','C1'],
      ['resanctionation','n','The act of sanctioning again','re-penalize','C1'],
      ['oversanctionation','n','Excessive sanctioning','excess penalize','C1'],
      ['mandateic','adj','Of or relating to mandate','authorization-based,characteristic','B2'],
      ['mandateous','adj','Full of mandate','authorization-filled,abundant','C1'],
      ['mandateful','adj','Full of mandate','authorization-rich,abounding','B2'],
      ['mandateless','adj','Without mandate','lacking,without','B2'],
      ['mandateism','n','The ideology of mandate','authorization ideology,doctrine','C1'],
      ['mandateist','n','A person focused on mandate','authorization specialist,advocate','C1'],
      ['mandateise','v','To make into mandate','authorization,convert','C1'],
      ['mandateize','v','To make or become mandate','authorization,transform','C1'],
      ['antimandate','adj','Opposed to mandate','against,opposing','C1'],
      ['nonmandate','adj','Not involving mandate','without,lacking','B2'],
      ['premandate','n','Before mandate','preceding,prior','C1'],
      ['postmandate','n','After mandate','following,subsequent','C1'],
      ['submandate','n','A subdivision of mandate','subset,branch','C1'],
      ['multimandate','adj','Involving many mandates','multiple,several','C1'],
      ['intermandate','adj','Between mandates','cross,between','C1'],
      ['coalitional','adj','Relating to coalition','alliance-related,pertaining to','B2'],
      ['coalitionic','adj','Of or relating to coalition','alliance-based,characteristic','B2'],
      ['coalitionous','adj','Full of coalition','alliance-filled,abundant','C1'],
      ['coalitionful','adj','Full of coalition','alliance-rich,abounding','B2'],
      ['coalitionless','adj','Without coalition','lacking,without','B2'],
      ['coalitionism','n','The ideology of coalition','alliance ideology,doctrine','C1'],
      ['coalitionist','n','A person focused on coalition','alliance specialist,advocate','C1'],
      ['coalitionise','v','To make into coalition','alliance,convert','C1'],
      ['coalitionize','v','To make or become coalition','alliance,transform','C1'],
      ['anticoalition','adj','Opposed to coalition','against,opposing','C1'],
      ['noncoalition','adj','Not involving coalition','without,lacking','B2'],
      ['precoalition','n','Before coalition','preceding,prior','C1'],
      ['postcoalition','n','After coalition','following,subsequent','C1'],
      ['subcoalition','n','A subdivision of coalition','subset,branch','C1'],
      ['multicoalition','adj','Involving many coalitions','multiple,several','C1'],
      ['intercoalition','adj','Between coalitions','cross,between','C1'],
      ['amnestyal','adj','Relating to amnesty','pardon-related,pertaining to','C1'],
      ['amnestyic','adj','Of or relating to amnesty','pardon-based,characteristic','C1'],
      ['amnestyous','adj','Full of amnesty','pardon-filled,abundant','C2'],
      ['amnestyful','adj','Full of amnesty','pardon-rich,abounding','C1'],
      ['amnestyless','adj','Without amnesty','lacking,without','C1'],
      ['amnestyism','n','The ideology of amnesty','pardon ideology,doctrine','C2'],
      ['amnestyist','n','A person focused on amnesty','pardon specialist,advocate','C2'],
      ['amnestyise','v','To make into amnesty','pardon,convert','C2'],
      ['amnestyize','v','To make or become amnesty','pardon,transform','C2'],
      ['antiamnesty','adj','Opposed to amnesty','against,opposing','C2'],
      ['nonamnesty','adj','Not involving amnesty','without,lacking','C1'],
      ['preamnesty','n','Before amnesty','preceding,prior','C2'],
      ['postamnesty','n','After amnesty','following,subsequent','C2'],
      ['subamnesty','n','A subdivision of amnesty','subset,branch','C2'],
      ['multiamnesty','adj','Involving many amnestys','multiple,several','C2'],
      ['interamnesty','adj','Between amnestys','cross,between','C2'],
      ['doctrineal','adj','Relating to doctrine','policy-related,pertaining to','B2'],
      ['doctrineic','adj','Of or relating to doctrine','policy-based,characteristic','B2'],
      ['doctrineous','adj','Full of doctrine','policy-filled,abundant','C1'],
      ['doctrineful','adj','Full of doctrine','policy-rich,abounding','B2'],
      ['doctrineless','adj','Without doctrine','lacking,without','B2'],
      ['doctrineism','n','The ideology of doctrine','policy ideology,doctrine','C1'],
      ['doctrineist','n','A person focused on doctrine','policy specialist,advocate','C1'],
      ['doctrineise','v','To make into doctrine','policy,convert','C1'],
      ['doctrineize','v','To make or become doctrine','policy,transform','C1'],
      ['antidoctrine','adj','Opposed to doctrine','against,opposing','C1'],
      ['nondoctrine','adj','Not involving doctrine','without,lacking','B2'],
      ['predoctrine','n','Before doctrine','preceding,prior','C1'],
      ['postdoctrine','n','After doctrine','following,subsequent','C1'],
      ['subdoctrine','n','A subdivision of doctrine','subset,branch','C1'],
      ['multidoctrine','adj','Involving many doctrines','multiple,several','C1'],
      ['interdoctrine','adj','Between doctrines','cross,between','C1'],
      ['constituencyal','adj','Relating to constituency','electorate-related,pertaining to','B2'],
      ['constituencyic','adj','Of or relating to constituency','electorate-based,characteristic','B2'],
      ['constituencyous','adj','Full of constituency','electorate-filled,abundant','C1'],
      ['constituencyful','adj','Full of constituency','electorate-rich,abounding','B2'],
      ['constituencyless','adj','Without constituency','lacking,without','B2'],
      ['constituencyism','n','The ideology of constituency','electorate ideology,doctrine','C1'],
      ['constituencyist','n','A person focused on constituency','electorate specialist,advocate','C1'],
      ['constituencyise','v','To make into constituency','electorate,convert','C1'],
      ['constituencyize','v','To make or become constituency','electorate,transform','C1'],
      ['anticonstituency','adj','Opposed to constituency','against,opposing','C1'],
      ['nonconstituency','adj','Not involving constituency','without,lacking','B2'],
      ['preconstituency','n','Before constituency','preceding,prior','C1'],
      ['postconstituency','n','After constituency','following,subsequent','C1'],
      ['subconstituency','n','A subdivision of constituency','subset,branch','C1'],
      ['multiconstituency','adj','Involving many constituencys','multiple,several','C1'],
      ['interconstituency','adj','Between constituencys','cross,between','C1'],
      ['geopolitical','adj','Relating to politics and geography','political-geographic,strategic','C1'],
      ['geopolitically','adv','In a geopolitical manner','political-geographic way','C1'],
      ['geopoliticalness','n','The quality of being geopolitical','political-geographic quality','C1'],
      ['geopoliticality','n','The state of being geopolitical','political-geographic condition','C2'],
      ['ungeopolitical','adj','Not geopolitical','not political-geographic','C1'],
      ['ingeopolitical','adj','Not geopolitical','not political-geographic','C2'],
      ['nongeopolitical','adj','Not geopolitical','not political-geographic','C1'],
      ['semigeopolitical','adj','Partially geopolitical','partly political-geographic','C2'],
      ['overgeopolitical','adj','Excessively geopolitical','too political-geographic','C2'],
      ['ultrageopolitical','adj','Extremely geopolitical','very political-geographic','C2'],
      ['technocratic','adj','Governed by technical experts','expert-led,specialist,merit-based','C1'],
      ['technocraticly','adv','In a technocratic manner','expert-led way','C1'],
      ['technocraticness','n','The quality of being technocratic','expert-led quality','C1'],
      ['technocraticity','n','The state of being technocratic','expert-led condition','C2'],
      ['untechnocratic','adj','Not technocratic','not expert-led','C1'],
      ['intechnocratic','adj','Not technocratic','not expert-led','C2'],
      ['nontechnocratic','adj','Not technocratic','not expert-led','C1'],
      ['semitechnocratic','adj','Partially technocratic','partly expert-led','C2'],
      ['overtechnocratic','adj','Excessively technocratic','too expert-led','C2'],
      ['ultratechnocratic','adj','Extremely technocratic','very expert-led','C2'],
      ['plenipotentiaryal','adj','Relating to plenipotentiary','ambassador-related,pertaining to','C2'],
      ['plenipotentiaryic','adj','Of or relating to plenipotentiary','ambassador-based,characteristic','C2'],
      ['plenipotentiaryous','adj','Full of plenipotentiary','ambassador-filled,abundant','C2'],
      ['plenipotentiaryful','adj','Full of plenipotentiary','ambassador-rich,abounding','C2'],
      ['plenipotentiaryless','adj','Without plenipotentiary','lacking,without','C2'],
      ['plenipotentiaryism','n','The ideology of plenipotentiary','ambassador ideology,doctrine','C2'],
      ['plenipotentiaryist','n','A person focused on plenipotentiary','ambassador specialist,advocate','C2'],
      ['plenipotentiaryise','v','To make into plenipotentiary','ambassador,convert','C2'],
      ['plenipotentiaryize','v','To make or become plenipotentiary','ambassador,transform','C2'],
      ['antiplenipotentiary','adj','Opposed to plenipotentiary','against,opposing','C2'],
      ['nonplenipotentiary','adj','Not involving plenipotentiary','without,lacking','C2'],
      ['preplenipotentiary','n','Before plenipotentiary','preceding,prior','C2'],
      ['postplenipotentiary','n','After plenipotentiary','following,subsequent','C2'],
      ['subplenipotentiary','n','A subdivision of plenipotentiary','subset,branch','C2'],
      ['multiplenipotentiary','adj','Involving many plenipotentiarys','multiple,several','C2'],
      ['interplenipotentiary','adj','Between plenipotentiarys','cross,between','C2'],
      ['hegemonyic','adj','Of or relating to hegemony','dominance-based,characteristic','C2'],
      ['hegemonyous','adj','Full of hegemony','dominance-filled,abundant','C2'],
      ['hegemonyful','adj','Full of hegemony','dominance-rich,abounding','C2'],
      ['hegemonyless','adj','Without hegemony','lacking,without','C2'],
      ['hegemonyism','n','The ideology of hegemony','dominance ideology,doctrine','C2'],
      ['hegemonyist','n','A person focused on hegemony','dominance specialist,advocate','C2'],
      ['hegemonyise','v','To make into hegemony','dominance,convert','C2'],
      ['hegemonyize','v','To make or become hegemony','dominance,transform','C2'],
      ['antihegemony','adj','Opposed to hegemony','against,opposing','C2'],
      ['nonhegemony','adj','Not involving hegemony','without,lacking','C2'],
      ['prehegemony','n','Before hegemony','preceding,prior','C2'],
      ['posthegemony','n','After hegemony','following,subsequent','C2'],
      ['subhegemony','n','A subdivision of hegemony','subset,branch','C2'],
      ['multihegemony','adj','Involving many hegemonys','multiple,several','C2'],
      ['interhegemony','adj','Between hegemonys','cross,between','C2'],
      ['kleptocracyic','adj','Of or relating to kleptocracy','corrupt government-based,characteristic','C2'],
      ['kleptocracyous','adj','Full of kleptocracy','corrupt government-filled,abundant','C2'],
      ['kleptocracyful','adj','Full of kleptocracy','corrupt government-rich,abounding','C2'],
      ['kleptocracyless','adj','Without kleptocracy','lacking,without','C2'],
      ['kleptocracyism','n','The ideology of kleptocracy','corrupt government ideology,doctrine','C2'],
      ['kleptocracyist','n','A person focused on kleptocracy','corrupt government specialist,advocate','C2'],
      ['kleptocracyise','v','To make into kleptocracy','corrupt government,convert','C2'],
      ['kleptocracyize','v','To make or become kleptocracy','corrupt government,transform','C2'],
      ['antikleptocracy','adj','Opposed to kleptocracy','against,opposing','C2'],
      ['nonkleptocracy','adj','Not involving kleptocracy','without,lacking','C2'],
      ['prekleptocracy','n','Before kleptocracy','preceding,prior','C2'],
      ['postkleptocracy','n','After kleptocracy','following,subsequent','C2'],
      ['subkleptocracy','n','A subdivision of kleptocracy','subset,branch','C2'],
      ['multikleptocracy','adj','Involving many kleptocracys','multiple,several','C2'],
      ['interkleptocracy','adj','Between kleptocracys','cross,between','C2'],
      ['suffrageal','adj','Relating to suffrage','voting right-related,pertaining to','C1'],
      ['suffrageic','adj','Of or relating to suffrage','voting right-based,characteristic','C1'],
      ['suffrageous','adj','Full of suffrage','voting right-filled,abundant','C2'],
      ['suffrageful','adj','Full of suffrage','voting right-rich,abounding','C1'],
      ['suffrageless','adj','Without suffrage','lacking,without','C1'],
      ['suffrageism','n','The ideology of suffrage','voting right ideology,doctrine','C2'],
      ['suffrageist','n','A person focused on suffrage','voting right specialist,advocate','C2'],
      ['suffrageise','v','To make into suffrage','voting right,convert','C2'],
      ['suffrageize','v','To make or become suffrage','voting right,transform','C2'],
      ['antisuffrage','adj','Opposed to suffrage','against,opposing','C2'],
      ['nonsuffrage','adj','Not involving suffrage','without,lacking','C1'],
      ['presuffrage','n','Before suffrage','preceding,prior','C2'],
      ['postsuffrage','n','After suffrage','following,subsequent','C2'],
      ['subsuffrage','n','A subdivision of suffrage','subset,branch','C2'],
      ['multisuffrage','adj','Involving many suffrages','multiple,several','C2'],
      ['intersuffrage','adj','Between suffrages','cross,between','C2'],
    ],
    psychology: [
      ['motivatation','n','The act of motivating','inspire process','B1'],
      ['motivatment','n','The result of motivating','inspire outcome','B1'],
      ['motivatance','n','The state of motivating','inspire state','B1'],
      ['motivatence','n','The quality of motivating','inspire quality','B1'],
      ['motivatal','n','An act of motivating','inspire event','B2'],
      ['motivater','n','One who motivates','inspire person','B1'],
      ['motivator','n','One who motivates','inspire agent','B1'],
      ['motivatee','n','One who is motivated','inspire recipient','B2'],
      ['motivatable','adj','Capable of being motivated','inspire,possible','B2'],
      ['motivatible','adj','Able to be motivated','inspire,feasible','B2'],
      ['motivative','adj','Tending to motivate','inspire,active','B1'],
      ['motivating','adj','Currently motivating','inspire,ongoing','B1'],
      ['motivated','adj','Having been motivated','inspire,completed','B1'],
      ['remotivate','v','To motivate again','inspire again,repeat','B1'],
      ['unmotivate','v','To reverse motivating','reverse,undo','B2'],
      ['overmotivate','v','To motivate excessively','excess,too much','B2'],
      ['undermotivate','v','To motivate insufficiently','insufficient,inadequate','B2'],
      ['mismotivate','v','To motivate incorrectly','wrongly,incorrectly','B2'],
      ['premotivate','v','To motivate beforehand','before,in advance','B2'],
      ['comotivate','v','To motivate together','jointly,together','B2'],
      ['remotivatation','n','The act of motivating again','re-inspire','B2'],
      ['overmotivatation','n','Excessive motivating','excess inspire','B2'],
      ['perceivation','n','The act of perceiving','notice process','B2'],
      ['perceivment','n','The result of perceiving','notice outcome','B2'],
    ],
  },
  collocations: {}
};
