module.exports = {
  vocab: {
    education: [
    ['memorise','v','To commit something to memory','learn,remember,retain','A2'],
    ['count','v','To determine the total number of items','tally,enumerate,calculate','A2'],
    ['copy','v','To reproduce text or images','duplicate,replicate,reproduce','A2'],
    ['repeat','v','To say or do something again','reiterate,echo,recite','A2'],
    ['recite','v','To say aloud from memory','declaim,narrate,deliver','B1'],
    ['achievement','n','Something accomplished through effort','accomplishment,attainment,success','B1'],
    ['preschool','n','Education for children before formal schooling','nursery,kindergarten,pre-primary','A2'],
    ['baccalaureate','n','A university degree or school-leaving exam','bachelor degree,school diploma','B2'],
    ['expulsion','n','The act of forcing a student to leave school','dismissal,removal,ejection','B2'],
    ['scholastic','adj','Relating to schools and education','academic,educational,scholarly','B2'],
    ['flipped classroom','n','Students learn at home and do work in class','inverted learning,reverse teaching','B2'],
    ['meritocratic','adj','Based on talent and effort','ability-based,talent-driven,skill-rewarding','C1'],
    ['viva voce','n','An oral examination','oral exam,spoken test,defence','C1'],
    ['tutoral','adj','Relating to tutor','instructor-related','A2'],
    ['memorisation','n','The act or process of memorising','learn process,remember process,retain process','A2'],
    ['memoriser','n','A person who memorises','learn person,remember person,retain person','B1'],
    ['memorisable','adj','Able to be memorised','learn,possible','B1'],
    ['memorising','n','The process of memorising something','learn activity','A2'],
    ['spellation','n','The act or process of spelling','write process,letter process,articulate process','A2'],
    ['speller','n','A person who spells','write person,letter person,articulate person','B1'],
    ['spellable','adj','Able to be spelld','write,possible','B1'],
    ['spelling','n','The process of spelling something','write activity','A2'],
    ['countation','n','The act or process of counting','tally process,enumerate process,calculate process','A2'],
    ['counter','n','A person who counts','tally person,enumerate person,calculate person','B1'],
    ['countable','adj','Able to be countd','tally,possible','B1'],
    ['counting','n','The process of counting something','tally activity','A2'],
    ['drawation','n','The act or process of drawing','sketch process,illustrate process,depict process','A2'],
    ['drawer','n','A person who draws','sketch person,illustrate person,depict person','B1'],
    ['drawable','adj','Able to be drawd','sketch,possible','B1'],
    ['drawing','n','The process of drawing something','sketch activity','A2'],
    ['copyation','n','The act or process of copying','duplicate process,replicate process,reproduce process','A2'],
    ['copyer','n','A person who copys','duplicate person,replicate person,reproduce person','B1'],
    ['copyable','adj','Able to be copyd','duplicate,possible','B1'],
    ['copying','n','The process of copying something','duplicate activity','A2'],
    ['repeatation','n','The act or process of repeating','reiterate process,echo process,recite process','A2'],
    ['repeater','n','A person who repeats','reiterate person,echo person,recite person','B1'],
    ['repeatable','adj','Able to be repeatd','reiterate,possible','B1'],
    ['repeating','n','The process of repeating something','reiterate activity','A2'],
    ['recitation','n','The act or process of reciting','declaim process,narrate process,deliver process','B1'],
    ['reciter','n','A person who recites','declaim person,narrate person,deliver person','B2'],
    ['recitable','adj','Able to be recited','declaim,possible','B2'],
    ['reciting','n','The process of reciting something','declaim activity','B1'],
    ['curriculumal','adj','Relating to curriculum','syllabus-related','B1'],
    ['scholarshipal','adj','Relating to scholarship','grant-related','B1'],
    ['semesteral','adj','Relating to semester','term-related','B1'],
    ['assignmental','adj','Relating to assignment','homework-related','B1'],
    ['tutorialal','adj','Relating to tutorial','seminar-related','B1'],
    ['feedbackal','adj','Relating to feedback','response-related','B1'],
    ['motivational','adj','Relating to motivation','drive-related','B1'],
    ['concentrational','adj','Relating to concentration','focus-related','B1'],
    ['revisional','adj','Relating to revision','review-related','B1'],
    ['disciplineal','adj','Relating to discipline','control-related','B1'],
    ['qualificational','adj','Relating to qualification','credential-related','B1'],
    ['achievemental','adj','Relating to achievement','accomplishment-related','B1'],
    ['pedagogyal','adj','Relating to pedagogy','instruction-related','B2'],
    ['cognitively','adv','In a cognitive manner','intellectual way','B2'],
    ['cognitiveness','n','The quality of being cognitive','intellectual quality','C1'],
    ['uncognitive','adj','Not cognitive','not intellectual','B2'],
    ['formatively','adv','In a formative manner','developmental way','B2'],
    ['formativeness','n','The quality of being formative','developmental quality','C1'],
    ['unformative','adj','Not formative','not developmental','B2'],
    ['vocationally','adv','In a vocational manner','occupational way','B2'],
    ['vocationalness','n','The quality of being vocational','occupational quality','C1'],
    ['unvocational','adj','Not vocational','not occupational','B2'],
    ['extracurricularly','adv','In a extracurricular manner','additional way','B2'],
    ['extracurricularness','n','The quality of being extracurricular','additional quality','C1'],
    ['unextracurricular','adj','Not extracurricular','not additional','B2'],
    ['remedially','adv','In a remedial manner','corrective way','B2'],
    ['remedialness','n','The quality of being remedial','corrective quality','C1'],
    ['unremedial','adj','Not remedial','not corrective','B2'],
    ['proficiencyal','adj','Relating to proficiency','expertise-related','B2'],
    ['literacyal','adj','Relating to literacy','reading ability-related','B2'],
    ['numeracyal','adj','Relating to numeracy','mathematical ability-related','B2'],
    ['plagiarismal','adj','Relating to plagiarism','copying-related','B2'],
    ['accreditational','adj','Relating to accreditation','certification-related','B2'],
    ['symposiumal','adj','Relating to symposium','conference-related','B2'],
    ['dissertational','adj','Relating to dissertation','thesis-related','B2'],
    ['sabbaticalal','adj','Relating to sabbatical','leave-related','C1'],
    ['pedagogueal','adj','Relating to pedagogue','educator-related','C1'],
    ['didacticly','adv','In a didactic manner','educational way','C1'],
    ['didacticness','n','The quality of being didactic','educational quality','C2'],
    ['undidactic','adj','Not didactic','not educational','C1'],
    ['autodidactal','adj','Relating to autodidact','self-learner-related','C1'],
    ['epistemologyal','adj','Relating to epistemology','philosophy of knowledge-related','C1'],
    ['heuristicly','adv','In a heuristic manner','exploratory way','C1'],
    ['heuristicness','n','The quality of being heuristic','exploratory quality','C2'],
    ['unheuristic','adj','Not heuristic','not exploratory','C1'],
    ['empirically','adv','In a empirical manner','experimental way','C1'],
    ['empiricalness','n','The quality of being empirical','experimental quality','C2'],
    ['unempirical','adj','Not empirical','not experimental','C1'],
    ['hermeneuticsal','adj','Relating to hermeneutics','interpretation-related','C2'],
    ['andragogyal','adj','Relating to andragogy','adult education-related','C2'],
    ['metacognitional','adj','Relating to metacognition','self-reflection-related','C2'],
    ['Socraticly','adv','In a Socratic manner','dialectical way','C2'],
    ['Socraticness','n','The quality of being Socratic','dialectical quality','C2'],
    ['unSocratic','adj','Not Socratic','not dialectical','C2'],
    ['peripateticly','adv','In a peripatetic manner','itinerant way','C2'],
    ['peripateticness','n','The quality of being peripatetic','itinerant quality','C2'],
    ['unperipatetic','adj','Not peripatetic','not itinerant','C2'],
    ['preschoolal','adj','Relating to preschool','nursery-related','A2'],
    ['postgraduateal','adj','Relating to postgraduate','graduate student-related','B1'],
    ['alumnusal','adj','Relating to alumnus','graduate-related','B2'],
    ['tenureal','adj','Relating to tenure','permanence-related','C1'],
    ['valedictorianal','adj','Relating to valedictorian','top student-related','C1'],
    ['absenteeismal','adj','Relating to absenteeism','truancy-related','B2'],
    ['baccalaureateal','adj','Relating to baccalaureate','bachelor degree-related','B2'],
    ['expulsional','adj','Relating to expulsion','dismissal-related','B2'],
    ['matriculatation','n','The act or process of matriculating','register process,sign up process,enrol process','C1'],
    ['matriculater','n','A person who matriculates','register person,sign up person,enrol person','C2'],
    ['matriculatable','adj','Able to be matriculated','register,possible','C2'],
    ['matriculating','n','The process of matriculating something','register activity','C1'],
    ['inculcatation','n','The act or process of inculcating','impress process,instil process,teach firmly process','C1'],
    ['inculcater','n','A person who inculcates','impress person,instil person,teach firmly person','C2'],
    ['inculcatable','adj','Able to be inculcated','impress,possible','C2'],
    ['inculcating','n','The process of inculcating something','impress activity','C1'],
    ['pedagogically','adv','In a pedagogical manner','educational way','B2'],
    ['pedagogicalness','n','The quality of being pedagogical','educational quality','C1'],
    ['unpedagogical','adj','Not pedagogical','not educational','B2'],
    ['scholasticly','adv','In a scholastic manner','academic way','B2'],
    ['scholasticness','n','The quality of being scholastic','academic quality','C1'],
    ['unscholastic','adj','Not scholastic','not academic','B2'],
    ['catechismal','adj','Relating to catechism','doctrine-related','C2'],
    ['syllabusal','adj','Relating to syllabus','curriculum-related','B1'],
    ['truancyal','adj','Relating to truancy','absence-related','B2'],
    ['meritocraticly','adv','In a meritocratic manner','ability-based way','C1'],
    ['meritocraticness','n','The quality of being meritocratic','ability-based quality','C2'],
    ['unmeritocratic','adj','Not meritocratic','not ability-based','C1']
    ],
    technology: [
    ['mouse','n','A device for controlling a cursor','pointer,clicker,input device','A2'],
    ['speaker','n','A device that produces sound','loudspeaker,audio device,amplifier','A2'],
    ['headphones','n','A device worn over the ears for listening','earphones,headset,earbuds','A2'],
    ['optimise','v','To make something as effective as possible','improve,enhance,streamline','B2'],
    ['virtualise','v','To create a virtual version of something','simulate,emulate,abstract','B2'],
    ['containerise','v','To package software in isolated units','encapsulate,bundle,isolate','C1'],
    ['microservice','n','A small independent software component','module,service unit,component','C1'],
    ['homomorphic','adj','Allowing computation on encrypted data','privacy-preserving,secure,encrypted','C2'],
    ['neuromorphic','adj','Mimicking the structure of the brain','brain-inspired,cognitive,neural','C2'],
    ['quantum','adj','Relating to quantum mechanical phenomena','subatomic,probabilistic,superposition','C2'],
    ['wifi','n','Wireless internet connectivity','wireless,broadband,internet','A2'],
    ['selfie','n','A photograph taken of oneself','self-portrait,self-photo','A2'],
    ['hashtag','n','A word preceded by a hash sign on social media','tag,label,keyword','B1'],
    ['avatar','n','A digital representation of a person','profile image,digital character','B1'],
    ['captcha','n','A test to distinguish humans from bots','verification,human test','B2']
    ],
  },
  collocations: {
  }
};
