module.exports = {
  vocab: {
    technology: [
    ['codec','n','Software encoding or decoding data','encoder,compressor,format converter','B2'],
    ['dongle','n','A small device connecting to a computer','adapter,plug-in,connector','B2'],
    ['geolocation','n','Identifying the real-world location of a device','GPS tracking,position finding','B2'],
    ['haptic','adj','Relating to touch-based feedback','tactile,touch-sensitive,sensory','C1'],
    ['ubiquitous computing','n','Technology embedded in everyday objects','pervasive tech,ambient computing','C1'],
    ['luddism','n','Opposition to new technology','technophobia,machine resistance','C2'],
    ['transhumanism','n','Using technology to enhance human abilities','human augmentation,bio-enhancement','C2'],
    ['screenal','adj','Relating to screen','display-related','A2'],
    ['keyboardal','adj','Relating to keyboard','input device-related','A2'],
    ['mouseal','adj','Relating to mouse','pointer-related','A2'],
    ['printeral','adj','Relating to printer','output device-related','A2'],
    ['cameraal','adj','Relating to camera','photo device-related','A2'],
    ['batteryal','adj','Relating to battery','cell-related','A2'],
    ['chargeral','adj','Relating to charger','adapter-related','A2'],
    ['tabletal','adj','Relating to tablet','iPad-related','A2'],
    ['speakeral','adj','Relating to speaker','loudspeaker-related','A2'],
    ['headphonesal','adj','Relating to headphones','earphones-related','A2'],
    ['networkal','adj','Relating to network','web-related','B1'],
    ['softwareal','adj','Relating to software','application-related','B1'],
    ['hardwareal','adj','Relating to hardware','equipment-related','B1'],
    ['databaseal','adj','Relating to database','data store-related','B1'],
    ['serveral','adj','Relating to server','host-related','B1'],
    ['bandwidthal','adj','Relating to bandwidth','data rate-related','B1'],
    ['firewallal','adj','Relating to firewall','security barrier-related','B1'],
    ['routeral','adj','Relating to router','gateway-related','B1'],
    ['browseral','adj','Relating to browser','web browser-related','B1'],
    ['encryptional','adj','Relating to encryption','coding-related','B1'],
    ['algorithmal','adj','Relating to algorithm','procedure-related','B2'],
    ['interfaceal','adj','Relating to interface','connection-related','B2'],
    ['prototypeal','adj','Relating to prototype','model-related','B2'],
    ['open-sourcely','adv','In a open-source manner','free way','B2'],
    ['open-sourceness','n','The quality of being open-source','free quality','C1'],
    ['unopen-source','adj','Not open-source','not free','B2'],
    ['scalablely','adv','In a scalable manner','expandable way','B2'],
    ['scalableness','n','The quality of being scalable','expandable quality','C1'],
    ['unscalable','adj','Not scalable','not expandable','B2'],
    ['modularly','adv','In a modular manner','component-based way','B2'],
    ['modularness','n','The quality of being modular','component-based quality','C1'],
    ['unmodular','adj','Not modular','not component-based','B2'],
    ['deployation','n','The act or process of deploying','launch process,release process,implement process','B2'],
    ['deployer','n','A person who deploys','launch person,release person,implement person','C1'],
    ['deployable','adj','Able to be deployd','launch,possible','C1'],
    ['deploying','n','The process of deploying something','launch activity','B2'],
    ['iteratation','n','The act or process of iterating','refine process,cycle process,revise process','B2'],
    ['iterater','n','A person who iterates','refine person,cycle person,revise person','C1'],
    ['iteratable','adj','Able to be iterated','refine,possible','C1'],
    ['iterating','n','The process of iterating something','refine activity','B2'],
    ['debugation','n','The act or process of debuging','troubleshoot process,fix process,repair process','B2'],
    ['debuger','n','A person who debugs','troubleshoot person,fix person,repair person','C1'],
    ['debugable','adj','Able to be debugd','troubleshoot,possible','C1'],
    ['debuging','n','The process of debuging something','troubleshoot activity','B2'],
    ['optimisation','n','The act or process of optimising','improve process,enhance process,streamline process','B2'],
    ['optimiser','n','A person who optimises','improve person,enhance person,streamline person','C1'],
    ['optimisable','adj','Able to be optimised','improve,possible','C1'],
    ['optimising','n','The process of optimising something','improve activity','B2'],
    ['virtualisation','n','The act or process of virtualising','simulate process,emulate process,abstract process','B2'],
    ['virtualiser','n','A person who virtualises','simulate person,emulate person,abstract person','C1'],
    ['virtualisable','adj','Able to be virtualised','simulate,possible','C1'],
    ['virtualising','n','The process of virtualising something','simulate activity','B2'],
    ['integratation','n','The act or process of integrating','merge process,unify process,incorporate process','B2'],
    ['integrater','n','A person who integrates','merge person,unify person,incorporate person','C1'],
    ['integratable','adj','Able to be integrated','merge,possible','C1'],
    ['integrating','n','The process of integrating something','merge activity','B2'],
    ['authenticatation','n','The act or process of authenticating','verify process,validate process,confirm process','B2'],
    ['authenticater','n','A person who authenticates','verify person,validate person,confirm person','C1'],
    ['authenticatable','adj','Able to be authenticated','verify,possible','C1'],
    ['authenticating','n','The process of authenticating something','verify activity','B2'],
    ['containerisation','n','The act or process of containerising','encapsulate process,bundle process,isolate process','C1'],
    ['containeriser','n','A person who containerises','encapsulate person,bundle person,isolate person','C2'],
    ['containerisable','adj','Able to be containerised','encapsulate,possible','C2'],
    ['containerising','n','The process of containerising something','encapsulate activity','C1'],
    ['microserviceal','adj','Relating to microservice','module-related','C1'],
    ['orchestratation','n','The act or process of orchestrating','manage process,coordinate process,arrange process','C1'],
    ['orchestrater','n','A person who orchestrates','manage person,coordinate person,arrange person','C2'],
    ['orchestratable','adj','Able to be orchestrated','manage,possible','C2'],
    ['orchestrating','n','The process of orchestrating something','manage activity','C1'],
    ['telemetryal','adj','Relating to telemetry','monitoring-related','C1'],
    ['idempotently','adv','In a idempotent manner','consistent way','C1'],
    ['idempotentness','n','The quality of being idempotent','consistent quality','C2'],
    ['unidempotent','adj','Not idempotent','not consistent','C1'],
    ['asynchronously','adv','In a asynchronous manner','non-blocking way','C1'],
    ['asynchronousness','n','The quality of being asynchronous','non-blocking quality','C2'],
    ['unasynchronous','adj','Not asynchronous','not non-blocking','C1'],
    ['deterministicly','adv','In a deterministic manner','predictable way','C1'],
    ['deterministicness','n','The quality of being deterministic','predictable quality','C2'],
    ['undeterministic','adj','Not deterministic','not predictable','C1'],
    ['homomorphicly','adv','In a homomorphic manner','privacy-preserving way','C2'],
    ['homomorphicness','n','The quality of being homomorphic','privacy-preserving quality','C2'],
    ['unhomomorphic','adj','Not homomorphic','not privacy-preserving','C2'],
    ['neuromorphicly','adv','In a neuromorphic manner','brain-inspired way','C2'],
    ['neuromorphicness','n','The quality of being neuromorphic','brain-inspired quality','C2'],
    ['unneuromorphic','adj','Not neuromorphic','not brain-inspired','C2'],
    ['quantumly','adv','In a quantum manner','subatomic way','C2'],
    ['quantumness','n','The quality of being quantum','subatomic quality','C2'],
    ['unquantum','adj','Not quantum','not subatomic','C2'],
    ['gadgetal','adj','Relating to gadget','device-related','A2'],
    ['wifial','adj','Relating to wifi','wireless-related','A2'],
    ['selfieal','adj','Relating to selfie','self-portrait-related','A2'],
    ['streamingal','adj','Relating to streaming','live play-related','B1'],
    ['hashtagal','adj','Relating to hashtag','tag-related','B1'],
    ['pixelal','adj','Relating to pixel','dot-related','B1'],
    ['avataral','adj','Relating to avatar','profile image-related','B1'],
    ['captchaal','adj','Relating to captcha','verification-related','B2'],
    ['codecal','adj','Relating to codec','encoder-related','B2'],
    ['dongleal','adj','Relating to dongle','adapter-related','B2'],
    ['firmwareal','adj','Relating to firmware','embedded software-related','B2'],
    ['metadataal','adj','Relating to metadata','data description-related','B2'],
    ['geolocational','adj','Relating to geolocation','GPS tracking-related','B2'],
    ['hapticly','adv','In a haptic manner','tactile way','C1'],
    ['hapticness','n','The quality of being haptic','tactile quality','C2'],
    ['unhaptic','adj','Not haptic','not tactile','C1'],
    ['telematicsal','adj','Relating to telematics','remote data-related','C1'],
    ['nanotechnologyal','adj','Relating to nanotechnology','nanotech-related','C1'],
    ['technocracyal','adj','Relating to technocracy','expert rule-related','C2'],
    ['luddismal','adj','Relating to luddism','technophobia-related','C2'],
    ['transhumanismal','adj','Relating to transhumanism','human augmentation-related','C2']
    ],
    health: [
    ['intravenous','adj','Administered through a vein','IV,venous,injected','B2'],
    ['biopsy','n','Removing tissue for examination','sample,tissue test,specimen','B2'],
    ['oncology','n','The study of cancer','cancer science,tumour medicine','C1'],
    ['haematology','n','The study of blood diseases','blood science,blood medicine','C1'],
    ['neuropathy','n','Damage to peripheral nerves','nerve damage,neural disorder','C1'],
    ['medicineal','adj','Relating to medicine','drug-related','A2'],
    ['hospitalal','adj','Relating to hospital','clinic-related','A2'],
    ['doctoral','adj','Relating to doctor','physician-related','A2'],
    ['nurseal','adj','Relating to nurse','carer-related','A2'],
    ['patiental','adj','Relating to patient','sick person-related','A2'],
    ['sickly','adv','In a sick manner','ill way','A2'],
    ['sickness','n','The quality of being sick','ill quality','B1'],
    ['unsick','adj','Not sick','not ill','A2'],
    ['healthily','adv','In a healthy manner','fit way','A2'],
    ['healthyness','n','The quality of being healthy','fit quality','B1'],
    ['unhealthy','adj','Not healthy','not fit','A2'],
    ['exerciseal','adj','Relating to exercise','workout-related','A2'],
    ['dietal','adj','Relating to diet','nutrition-related','A2'],
    ['painal','adj','Relating to pain','ache-related','A2'],
    ['symptomal','adj','Relating to symptom','indicator-related','B1'],
    ['diagnosation','n','The act or process of diagnosing','identify process,determine process,detect process','B1'],
    ['diagnoser','n','A person who diagnoses','identify person,determine person,detect person','B2'],
    ['diagnosable','adj','Able to be diagnosed','identify,possible','B2'],
    ['diagnosing','n','The process of diagnosing something','identify activity','B1'],
    ['treatmental','adj','Relating to treatment','therapy-related','B1'],
    ['surgeryal','adj','Relating to surgery','operation-related','B1']
    ],
  },
  collocations: {
  }
};
