module.exports = {
  vocab: {
    business: [
    ['liabilities','n','Debts owed by a company','obligations,debts,financial duties','B2'],
    ['bootstrapping','n','Starting a business with minimal funding','self-funding,lean startup','C1'],
    ['divestiture','n','Selling off a business asset or subsidiary','sell-off,disposal,asset sale','C1'],
    ['promissory note','n','A written promise to pay a sum','IOU,debt note,payment promise','C1'],
    ['disruptive innovation','n','Innovation creating a new market','game-changer,market disruption','B2'],
    ['unicorn startup','n','A private company valued over one billion','billion-dollar startup,mega venture','C1'],
    ['companyal','adj','Relating to company','firm-related','A2'],
    ['officeal','adj','Relating to office','workplace-related','A2'],
    ['manageral','adj','Relating to manager','supervisor-related','A2'],
    ['customeral','adj','Relating to customer','client-related','A2'],
    ['meetingal','adj','Relating to meeting','conference-related','A2'],
    ['priceal','adj','Relating to price','cost-related','A2'],
    ['profital','adj','Relating to profit','earnings-related','A2'],
    ['sellation','n','The act or process of selling','market process,trade process,retail process','A2'],
    ['seller','n','A person who sells','market person,trade person,retail person','B1'],
    ['sellable','adj','Able to be selld','market,possible','B1'],
    ['selling','n','The process of selling something','market activity','A2'],
    ['buyation','n','The act or process of buying','purchase process,acquire process,procure process','A2'],
    ['buyer','n','A person who buys','purchase person,acquire person,procure person','B1'],
    ['buyable','adj','Able to be buyd','purchase,possible','B1'],
    ['buying','n','The process of buying something','purchase activity','A2'],
    ['workation','n','The act or process of working','labour process,operate process,function process','A2'],
    ['workable','adj','Able to be workd','labour,possible','B1'],
    ['working','n','The process of working something','labour activity','A2'],
    ['strategyal','adj','Relating to strategy','plan-related','B1'],
    ['revenueal','adj','Relating to revenue','income-related','B1'],
    ['investmental','adj','Relating to investment','expenditure-related','B1'],
    ['contractal','adj','Relating to contract','agreement-related','B1'],
    ['negotiatation','n','The act or process of negotiating','bargain process,discuss process,mediate process','B1'],
    ['negotiater','n','A person who negotiates','bargain person,discuss person,mediate person','B2'],
    ['negotiatable','adj','Able to be negotiated','bargain,possible','B2'],
    ['negotiating','n','The process of negotiating something','bargain activity','B1'],
    ['budgetal','adj','Relating to budget','financial plan-related','B1'],
    ['stakeholderal','adj','Relating to stakeholder','investor-related','B1'],
    ['entrepreneural','adj','Relating to entrepreneur','founder-related','B1'],
    ['marketingal','adj','Relating to marketing','advertising-related','B1'],
    ['mergeral','adj','Relating to merger','acquisition-related','B2'],
    ['franchiseal','adj','Relating to franchise','licence-related','B2'],
    ['diversifyation','n','The act or process of diversifying','branch out process,expand process,broaden process','B2'],
    ['diversifyer','n','A person who diversifys','branch out person,expand person,broaden person','C1'],
    ['diversifyable','adj','Able to be diversifyd','branch out,possible','C1'],
    ['diversifying','n','The process of diversifying something','branch out activity','B2'],
    ['outsourcation','n','The act or process of outsourcing','delegate process,subcontract process,farm out process','B2'],
    ['outsourcer','n','A person who outsources','delegate person,subcontract person,farm out person','C1'],
    ['outsourcable','adj','Able to be outsourced','delegate,possible','C1'],
    ['restructuration','n','The act or process of restructuring','reorganise process,reform process,overhaul process','B2'],
    ['restructurer','n','A person who restructures','reorganise person,reform person,overhaul person','C1'],
    ['restructurable','adj','Able to be restructured','reorganise,possible','C1'],
    ['restructuring','n','The process of restructuring something','reorganise activity','B2'],
    ['leveragation','n','The act or process of leveraging','exploit process,utilise process,capitalise on process','B2'],
    ['leverager','n','A person who leverages','exploit person,utilise person,capitalise on person','C1'],
    ['leveragable','adj','Able to be leveraged','exploit,possible','C1'],
    ['leveraging','n','The process of leveraging something','exploit activity','B2'],
    ['scalabilityal','adj','Relating to scalability','growth capacity-related','B2'],
    ['benchmarkal','adj','Relating to benchmark','standard-related','B2'],
    ['synergyal','adj','Relating to synergy','cooperation-related','C1'],
    ['conglomerateal','adj','Relating to conglomerate','multinational-related','C1'],
    ['fiduciarily','adv','In a fiduciary manner','trustee way','C1'],
    ['fiduciaryness','n','The quality of being fiduciary','trustee quality','C2'],
    ['unfiduciary','adj','Not fiduciary','not trustee','C1'],
    ['amortisation','n','The act or process of amortising','depreciate process,write off process,allocate process','C1'],
    ['amortiser','n','A person who amortises','depreciate person,write off person,allocate person','C2'],
    ['amortisable','adj','Able to be amortised','depreciate,possible','C2'],
    ['amortising','n','The process of amortising something','depreciate activity','C1'],
    ['disintermediatation','n','The act or process of disintermediating','bypass process,cut out process,eliminate process','C2'],
    ['disintermediater','n','A person who disintermediates','bypass person,cut out person,eliminate person','C2'],
    ['disintermediatable','adj','Able to be disintermediated','bypass,possible','C2'],
    ['disintermediating','n','The process of disintermediating something','bypass activity','C2'],
    ['oligopolyal','adj','Relating to oligopoly','restricted market-related','C2'],
    ['receiptal','adj','Relating to receipt','proof of purchase-related','A2'],
    ['invoiceal','adj','Relating to invoice','bill-related','B1'],
    ['agendaal','adj','Relating to agenda','schedule-related','B1'],
    ['deadlineal','adj','Relating to deadline','due date-related','B1'],
    ['brandingal','adj','Relating to branding','brand identity-related','B1'],
    ['turnoveral','adj','Relating to turnover','revenue-related','B2'],
    ['liquidityal','adj','Relating to liquidity','cash flow-related','B2'],
    ['depreciational','adj','Relating to depreciation','decline-related','B2'],
    ['collateralal','adj','Relating to collateral','guarantee-related','B2'],
    ['equityal','adj','Relating to equity','ownership stake-related','B2'],
    ['liabilitiesal','adj','Relating to liabilities','obligations-related','B2'],
    ['acquisitional','adj','Relating to acquisition','buyout-related','B2'],
    ['arbitrageal','adj','Relating to arbitrage','price exploitation-related','C1'],
    ['bootstrappingal','adj','Relating to bootstrapping','self-funding-related','C1'],
    ['divestitureal','adj','Relating to divestiture','sell-off-related','C1'],
    ['indemnityal','adj','Relating to indemnity','insurance-related','C1'],
    ['receivershipal','adj','Relating to receivership','insolvency management-related','C1']
    ],
    economy: [
    ['devaluation','n','A reduction in the value of a currency','depreciation,decline,weakening','B2'],
    ['macroeconomic','adj','Relating to the economy as a whole','national,aggregate,broad-scale','C1'],
    ['microeconomic','adj','Relating to individual economic behaviour','individual,firm-level,household','C1'],
    ['hedge fund','n','An investment fund using complex strategies','alternative fund,speculative fund','B2'],
    ['derivatives','n','Financial instruments based on underlying assets','futures,options,financial contracts','C1'],
    ['oligopsony','n','A market with few buyers','buyer monopoly,limited demand market','C2'],
    ['multiplier effect','n','Increased spending producing greater income','economic ripple,spending cascade','C1'],
    ['opportunity cost','n','The loss of potential gain from alternatives','trade-off,foregone benefit','B2'],
    ['laissez-faire','adj','Minimal government intervention in the economy','free market,hands-off,non-interventionist','B2'],
    ['moneyal','adj','Relating to money','currency-related','A2'],
    ['bankal','adj','Relating to bank','financial institution-related','A2'],
    ['taxal','adj','Relating to tax','levy-related','A2'],
    ['savation','n','The act or process of saving','deposit process,put aside process,store process','A2'],
    ['saver','n','A person who saves','deposit person,put aside person,store person','B1'],
    ['savable','adj','Able to be saved','deposit,possible','B1'],
    ['saving','n','The process of saving something','deposit activity','A2'],
    ['spendation','n','The act or process of spending','pay process,purchase process,expend process','A2'],
    ['spender','n','A person who spends','pay person,purchase person,expend person','B1'],
    ['spendable','adj','Able to be spendd','pay,possible','B1'],
    ['spending','n','The process of spending something','pay activity','A2'],
    ['cheaply','adv','In a cheap manner','inexpensive way','A2'],
    ['cheapness','n','The quality of being cheap','inexpensive quality','B1'],
    ['uncheap','adj','Not cheap','not inexpensive','A2'],
    ['expensively','adv','In a expensive manner','costly way','A2'],
    ['expensiveness','n','The quality of being expensive','costly quality','B1'],
    ['unexpensive','adj','Not expensive','not costly','A2'],
    ['payation','n','The act or process of paying','compensate process,remunerate process,settle process','A2'],
    ['payer','n','A person who pays','compensate person,remunerate person,settle person','B1'],
    ['payable','adj','Able to be payd','compensate,possible','B1'],
    ['paying','n','The process of paying something','compensate activity','A2'],
    ['inflational','adj','Relating to inflation','price rise-related','B1'],
    ['recessional','adj','Relating to recession','downturn-related','B1'],
    ['unemploymental','adj','Relating to unemployment','joblessness-related','B1'],
    ['exportal','adj','Relating to export','shipment-related','B1'],
    ['importal','adj','Relating to import','foreign goods-related','B1'],
    ['subsidyal','adj','Relating to subsidy','grant-related','B1'],
    ['tariffal','adj','Relating to tariff','import duty-related','B1'],
    ['fiscally','adv','In a fiscal manner','financial way','B2'],
    ['fiscalness','n','The quality of being fiscal','financial quality','C1'],
    ['unfiscal','adj','Not fiscal','not financial','B2'],
    ['monetarily','adv','In a monetary manner','financial way','B2'],
    ['monetaryness','n','The quality of being monetary','financial quality','C1'],
    ['unmonetary','adj','Not monetary','not financial','B2'],
    ['deficital','adj','Relating to deficit','shortfall-related','B2'],
    ['surplusal','adj','Relating to surplus','excess-related','B2'],
    ['austerityal','adj','Relating to austerity','cutbacks-related','B2'],
    ['stimulusal','adj','Relating to stimulus','incentive-related','B2'],
    ['devaluational','adj','Relating to devaluation','depreciation-related','B2'],
    ['privatisational','adj','Relating to privatisation','denationalisation-related','B2'],
    ['protectionismal','adj','Relating to protectionism','trade barriers-related','B2'],
    ['macroeconomicly','adv','In a macroeconomic manner','national way','C1'],
    ['macroeconomicness','n','The quality of being macroeconomic','national quality','C2'],
    ['unmacroeconomic','adj','Not macroeconomic','not national','C1'],
    ['microeconomicly','adv','In a microeconomic manner','individual way','C1'],
    ['microeconomicness','n','The quality of being microeconomic','individual quality','C2'],
    ['unmicroeconomic','adj','Not microeconomic','not individual','C1']
    ],
  },
  collocations: {
  }
};
