module.exports = {
  vocab: {
    crime: [
    ['adjudicatable','adj','Able to be adjudicated','judge,possible','C2'],
    ['adjudicating','n','The process of adjudicating something','judge activity','C1'],
    ['exoneratation','n','The act or process of exonerating','acquit process,clear process,absolve process','C1'],
    ['exonerater','n','A person who exonerates','acquit person,clear person,absolve person','C2'],
    ['exoneratable','adj','Able to be exonerated','acquit,possible','C2'],
    ['exonerating','n','The process of exonerating something','acquit activity','C1'],
    ['litigatation','n','The act or process of litigating','sue process,prosecute process,bring legal action process','C1'],
    ['litigater','n','A person who litigates','sue person,prosecute person,bring legal action person','C2'],
    ['litigatable','adj','Able to be litigated','sue,possible','C2'],
    ['litigating','n','The process of litigating something','sue activity','C1'],
    ['expungation','n','The act or process of expunging','delete process,remove process,wipe clean process','C2'],
    ['expunger','n','A person who expunges','delete person,remove person,wipe clean person','C2'],
    ['expungable','adj','Able to be expunged','delete,possible','C2'],
    ['expunging','n','The process of expunging something','delete activity','C2']
    ],
    media: [
    ['media literacy','n','The ability to critically analyse media','critical thinking,media awareness','B2'],
    ['framing','n','Presenting information from a particular angle','spin,perspective,narrative','C1'],
    ['semiotics','n','The study of signs and symbols','sign theory,symbolism,meaning study','C2'],
    ['influencer','n','A person with social media following','content creator,online personality','B1'],
    ['op-ed','n','An opinion article in a newspaper','opinion piece,editorial column','B2'],
    ['astroturfing','n','Fake grassroots campaign to influence opinion','manufactured support,fake movement','C2'],
    ['churnalism','n','Journalism based on press releases not research','lazy reporting,PR journalism','C2'],
    ['narrowcasting','n','Targeting media at a specific audience','niche broadcasting,targeted content','C1'],
    ['digital footprint','n','The trail of data left by online activity','online presence,digital trace','B2'],
    ['doomscrolling','n','Compulsively reading negative news online','anxiety browsing,negative scrolling','B2'],
    ['deepfake','n','AI-generated fake video or audio','synthetic media,AI forgery','B2'],
    ['virality','n','The tendency for content to spread rapidly online','shareability,online contagion','C1'],
    ['newspaperal','adj','Relating to newspaper','paper-related','A2'],
    ['televisional','adj','Relating to television','TV-related','A2'],
    ['radioal','adj','Relating to radio','wireless-related','A2'],
    ['newsal','adj','Relating to news','reports-related','A2'],
    ['magazineal','adj','Relating to magazine','journal-related','A2'],
    ['advertisemental','adj','Relating to advertisement','ad-related','A2'],
    ['journalistal','adj','Relating to journalist','reporter-related','B1'],
    ['broadcastal','adj','Relating to broadcast','transmission-related','B1'],
    ['headlineal','adj','Relating to headline','title-related','B1'],
    ['editorialal','adj','Relating to editorial','opinion piece-related','B1'],
    ['censorshipal','adj','Relating to censorship','restriction-related','B1'],
    ['propagandaal','adj','Relating to propaganda','misinformation-related','B1'],
    ['biasal','adj','Relating to bias','partiality-related','B2'],
    ['tabloidal','adj','Relating to tabloid','scandal sheet-related','B2'],
    ['broadsheetal','adj','Relating to broadsheet','quality press-related','B2'],
    ['sensationalismal','adj','Relating to sensationalism','exaggeration-related','B2'],
    ['objectivityal','adj','Relating to objectivity','impartiality-related','B2'],
    ['disinformational','adj','Relating to disinformation','fake news-related','B2'],
    ['framingal','adj','Relating to framing','spin-related','C1'],
    ['gatekeepingal','adj','Relating to gatekeeping','filtering-related','C1'],
    ['semioticsal','adj','Relating to semiotics','sign theory-related','C2'],
    ['hegemonicly','adv','In a hegemonic manner','controlling way','C2'],
    ['hegemonicness','n','The quality of being hegemonic','controlling quality','C2'],
    ['unhegemonic','adj','Not hegemonic','not controlling','C2'],
    ['podcastal','adj','Relating to podcast','audio show-related','B1'],
    ['influenceral','adj','Relating to influencer','content creator-related','B1'],
    ['clickbaital','adj','Relating to clickbait','misleading headline-related','B2'],
    ['paywallal','adj','Relating to paywall','subscription wall-related','B2'],
    ['infographical','adj','Relating to infographic','data graphic-related','B2'],
    ['syndicational','adj','Relating to syndication','redistribution-related','C1'],
    ['muckrakingal','adj','Relating to muckraking','exposé-related','C1'],
    ['astroturfingal','adj','Relating to astroturfing','manufactured support-related','C2'],
    ['churnalismal','adj','Relating to churnalism','lazy reporting-related','C2'],
    ['narrowcastingal','adj','Relating to narrowcasting','niche broadcasting-related','C1'],
    ['doomscrollingal','adj','Relating to doomscrolling','anxiety browsing-related','B2'],
    ['deepfakeal','adj','Relating to deepfake','synthetic media-related','B2'],
    ['misinformational','adj','Relating to misinformation','inaccuracy-related','B1'],
    ['viralityal','adj','Relating to virality','shareability-related','C1'],
    ['infotainmental','adj','Relating to infotainment','news entertainment-related','B2']
    ],
    communication: [
    ['misunderstanding','n','A failure to understand correctly','confusion,mix-up,misinterpretation','B1'],
    ['elocution','n','The skill of clear speaking','diction,pronunciation,articulation','C1'],
    ['phatic','adj','Serving to establish social contact','small-talk,conversational,social','C2'],
    ['tone of voice','n','The quality of sound when speaking','intonation,vocal quality,timbre','B1'],
    ['soliloquy','n','Speaking ones thoughts aloud when alone','monologue,self-talk,inner speech','C1'],
    ['perlocutionary','adj','Relating to the effect of speech on listeners','persuasive,impactful,resultant','C2'],
    ['illocutionary','adj','Relating to the intended force of an utterance','purposive,intentional,speech-act','C2'],
    ['metalanguage','n','Language used to describe language','meta-speech,linguistic terminology','C2'],
    ['prosody','n','Patterns of rhythm and sound in speech','intonation,stress pattern,cadence','C1'],
    ['deixis','n','Words whose meaning depends on context','contextual reference,indexical terms','C2'],
    ['semaphore','n','A system of signalling using flags','flag signals,visual communication','B2'],
    ['telegraphic','adj','Using minimal words to convey meaning','concise,abbreviated,terse','C1'],
    ['speakation','n','The act or process of speaking','talk process,say process,express process','A2'],
    ['speakable','adj','Able to be speakd','talk,possible','B1'],
    ['speaking','n','The process of speaking something','talk activity','A2'],
    ['listenation','n','The act or process of listening','hear process,attend process,tune in process','A2'],
    ['listener','n','A person who listens','hear person,attend person,tune in person','B1'],
    ['listenable','adj','Able to be listend','hear,possible','B1'],
    ['listening','n','The process of listening something','hear activity','A2'],
    ['messageal','adj','Relating to message','note-related','A2'],
    ['letteral','adj','Relating to letter','note-related','A2'],
    ['conversational','adj','Relating to conversation','talk-related','A2'],
    ['phoneal','adj','Relating to phone','telephone-related','A2'],
    ['emailal','adj','Relating to email','electronic mail-related','A2'],
    ['presentational','adj','Relating to presentation','speech-related','B1'],
    ['debateal','adj','Relating to debate','argument-related','B1'],
    ['persuadation','n','The act or process of persuading','convince process,influence process,sway process','B1'],
    ['persuader','n','A person who persuades','convince person,influence person,sway person','B2'],
    ['persuadable','adj','Able to be persuaded','convince,possible','B2'],
    ['persuading','n','The process of persuading something','convince activity','B1'],
    ['fluently','adv','In a fluent manner','articulate way','B1'],
    ['fluentness','n','The quality of being fluent','articulate quality','B2'],
    ['unfluent','adj','Not fluent','not articulate','B1'],
    ['misunderstandingal','adj','Relating to misunderstanding','confusion-related','B1'],
    ['articulately','adv','In a articulate manner','eloquent way','B2'],
    ['articulateness','n','The quality of being articulate','eloquent quality','C1'],
    ['unarticulate','adj','Not articulate','not eloquent','B2'],
    ['ambiguityal','adj','Relating to ambiguity','vagueness-related','B2'],
    ['nuanceal','adj','Relating to nuance','subtlety-related','B2'],
    ['pragmaticsal','adj','Relating to pragmatics','contextual meaning-related','B2'],
    ['discourseal','adj','Relating to discourse','dialogue-related','B2'],
    ['euphemismal','adj','Relating to euphemism','understatement-related','C1'],
    ['hyperboleal','adj','Relating to hyperbole','overstatement-related','C1'],
    ['colloquially','adv','In a colloquial manner','informal way','C1'],
    ['colloquialness','n','The quality of being colloquial','informal quality','C2'],
    ['uncolloquial','adj','Not colloquial','not informal','C1'],
    ['elocutional','adj','Relating to elocution','diction-related','C1'],
    ['malapropismal','adj','Relating to malapropism','word confusion-related','C2'],
    ['phaticly','adv','In a phatic manner','small-talk way','C2'],
    ['phaticness','n','The quality of being phatic','small-talk quality','C2'],
    ['unphatic','adj','Not phatic','not small-talk','C2'],
    ['gestureal','adj','Relating to gesture','signal-related','A2'],
    ['whisperation','n','The act or process of whispering','murmur process,breathe process,mutter process','A2'],
    ['whisperer','n','A person who whispers','murmur person,breathe person,mutter person','B1'],
    ['whisperable','adj','Able to be whisperd','murmur,possible','B1'],
    ['whispering','n','The process of whispering something','murmur activity','A2'],
    ['accental','adj','Relating to accent','pronunciation-related','A2'],
    ['slangal','adj','Relating to slang','jargon-related','B1'],
    ['jargonal','adj','Relating to jargon','terminology-related','B1'],
    ['paraphrasation','n','The act or process of paraphrasing','rephrase process,reword process,restate process','B2'],
    ['paraphraser','n','A person who paraphrases','rephrase person,reword person,restate person','C1'],
    ['paraphrasable','adj','Able to be paraphrased','rephrase,possible','C1'],
    ['paraphrasing','n','The process of paraphrasing something','rephrase activity','B2'],
    ['interlocutoral','adj','Relating to interlocutor','speaker-related','C1'],
    ['soliloquyal','adj','Relating to soliloquy','monologue-related','C1'],
    ['circumlocutional','adj','Relating to circumlocution','wordiness-related','C1'],
    ['perlocutionarily','adv','In a perlocutionary manner','persuasive way','C2'],
    ['perlocutionaryness','n','The quality of being perlocutionary','persuasive quality','C2'],
    ['unperlocutionary','adj','Not perlocutionary','not persuasive','C2'],
    ['illocutionarily','adv','In a illocutionary manner','purposive way','C2'],
    ['illocutionaryness','n','The quality of being illocutionary','purposive quality','C2'],
    ['unillocutionary','adj','Not illocutionary','not purposive','C2'],
    ['metalanguageal','adj','Relating to metalanguage','meta-speech-related','C2'],
    ['prosodyal','adj','Relating to prosody','intonation-related','C1'],
    ['deixisal','adj','Relating to deixis','contextual reference-related','C2'],
    ['registeral','adj','Relating to register','style-related','B2'],
    ['pidginal','adj','Relating to pidgin','trade language-related','C1']
    ],
  },
  collocations: {
  }
};
