// Auto-generated vocab boost group 60
module.exports = {
  vocab: {
    media: [
      ['coverageous','adj','Full of coverage','reporting-filled,abundant','C1'],
      ['coverageful','adj','Full of coverage','reporting-rich,abounding','B2'],
      ['coverageless','adj','Without coverage','lacking,without','B2'],
      ['coverageism','n','The ideology of coverage','reporting ideology,doctrine','C1'],
      ['coverageist','n','A person focused on coverage','reporting specialist,advocate','C1'],
      ['coverageise','v','To make into coverage','reporting,convert','C1'],
      ['coverageize','v','To make or become coverage','reporting,transform','C1'],
      ['anticoverage','adj','Opposed to coverage','against,opposing','C1'],
      ['noncoverage','adj','Not involving coverage','without,lacking','B2'],
      ['precoverage','n','Before coverage','preceding,prior','C1'],
      ['postcoverage','n','After coverage','following,subsequent','C1'],
      ['subcoverage','n','A subdivision of coverage','subset,branch','C1'],
      ['multicoverage','adj','Involving many coverages','multiple,several','C1'],
      ['intercoverage','adj','Between coverages','cross,between','C1'],
      ['disinformationic','adj','Of or relating to disinformation','fake news-based,characteristic','B2'],
      ['disinformationous','adj','Full of disinformation','fake news-filled,abundant','C1'],
      ['disinformationful','adj','Full of disinformation','fake news-rich,abounding','B2'],
      ['disinformationless','adj','Without disinformation','lacking,without','B2'],
      ['disinformationism','n','The ideology of disinformation','fake news ideology,doctrine','C1'],
      ['disinformationist','n','A person focused on disinformation','fake news specialist,advocate','C1'],
      ['disinformationise','v','To make into disinformation','fake news,convert','C1'],
      ['disinformationize','v','To make or become disinformation','fake news,transform','C1'],
      ['antidisinformation','adj','Opposed to disinformation','against,opposing','C1'],
      ['nondisinformation','adj','Not involving disinformation','without,lacking','B2'],
      ['predisinformation','n','Before disinformation','preceding,prior','C1'],
      ['postdisinformation','n','After disinformation','following,subsequent','C1'],
      ['subdisinformation','n','A subdivision of disinformation','subset,branch','C1'],
      ['multidisinformation','adj','Involving many disinformations','multiple,several','C1'],
      ['interdisinformation','adj','Between disinformations','cross,between','C1'],
      ['objectivityic','adj','Of or relating to objectivity','impartiality-based,characteristic','B2'],
      ['objectivityous','adj','Full of objectivity','impartiality-filled,abundant','C1'],
      ['objectivityful','adj','Full of objectivity','impartiality-rich,abounding','B2'],
      ['objectivityless','adj','Without objectivity','lacking,without','B2'],
      ['objectivityism','n','The ideology of objectivity','impartiality ideology,doctrine','C1'],
      ['objectivityist','n','A person focused on objectivity','impartiality specialist,advocate','C1'],
      ['objectivityise','v','To make into objectivity','impartiality,convert','C1'],
      ['objectivityize','v','To make or become objectivity','impartiality,transform','C1'],
      ['antiobjectivity','adj','Opposed to objectivity','against,opposing','C1'],
      ['nonobjectivity','adj','Not involving objectivity','without,lacking','B2'],
      ['preobjectivity','n','Before objectivity','preceding,prior','C1'],
      ['postobjectivity','n','After objectivity','following,subsequent','C1'],
      ['subobjectivity','n','A subdivision of objectivity','subset,branch','C1'],
      ['multiobjectivity','adj','Involving many objectivitys','multiple,several','C1'],
      ['interobjectivity','adj','Between objectivitys','cross,between','C1'],
      ['paparazzial','adj','Relating to paparazzi','press photographers-related,pertaining to','B2'],
      ['paparazziic','adj','Of or relating to paparazzi','press photographers-based,characteristic','B2'],
      ['paparazzious','adj','Full of paparazzi','press photographers-filled,abundant','C1'],
      ['paparazziful','adj','Full of paparazzi','press photographers-rich,abounding','B2'],
      ['paparazziless','adj','Without paparazzi','lacking,without','B2'],
      ['paparazziism','n','The ideology of paparazzi','press photographers ideology,doctrine','C1'],
      ['paparazziist','n','A person focused on paparazzi','press photographers specialist,advocate','C1'],
      ['paparazziise','v','To make into paparazzi','press photographers,convert','C1'],
      ['paparazziize','v','To make or become paparazzi','press photographers,transform','C1'],
      ['antipaparazzi','adj','Opposed to paparazzi','against,opposing','C1'],
      ['nonpaparazzi','adj','Not involving paparazzi','without,lacking','B2'],
      ['prepaparazzi','n','Before paparazzi','preceding,prior','C1'],
      ['postpaparazzi','n','After paparazzi','following,subsequent','C1'],
      ['subpaparazzi','n','A subdivision of paparazzi','subset,branch','C1'],
      ['multipaparazzi','adj','Involving many paparazzis','multiple,several','C1'],
      ['interpaparazzi','adj','Between paparazzis','cross,between','C1'],
      ['infographicic','adj','Of or relating to infographic','data visualization-based,characteristic','B2'],
      ['infographicous','adj','Full of infographic','data visualization-filled,abundant','C1'],
      ['infographicful','adj','Full of infographic','data visualization-rich,abounding','B2'],
      ['infographicless','adj','Without infographic','lacking,without','B2'],
      ['infographicism','n','The ideology of infographic','data visualization ideology,doctrine','C1'],
      ['infographicist','n','A person focused on infographic','data visualization specialist,advocate','C1'],
      ['infographicise','v','To make into infographic','data visualization,convert','C1'],
      ['infographicize','v','To make or become infographic','data visualization,transform','C1'],
      ['antiinfographic','adj','Opposed to infographic','against,opposing','C1'],
      ['noninfographic','adj','Not involving infographic','without,lacking','B2'],
      ['preinfographic','n','Before infographic','preceding,prior','C1'],
      ['postinfographic','n','After infographic','following,subsequent','C1'],
      ['subinfographic','n','A subdivision of infographic','subset,branch','C1'],
      ['multiinfographic','adj','Involving many infographics','multiple,several','C1'],
      ['interinfographic','adj','Between infographics','cross,between','C1'],
      ['podcastic','adj','Of or relating to podcast','audio show-based,characteristic','B1'],
      ['podcastous','adj','Full of podcast','audio show-filled,abundant','B2'],
      ['podcastful','adj','Full of podcast','audio show-rich,abounding','B1'],
      ['podcastless','adj','Without podcast','lacking,without','B1'],
      ['podcastism','n','The ideology of podcast','audio show ideology,doctrine','B2'],
      ['podcastist','n','A person focused on podcast','audio show specialist,advocate','B2'],
      ['podcastise','v','To make into podcast','audio show,convert','B2'],
      ['podcastize','v','To make or become podcast','audio show,transform','B2'],
      ['antipodcast','adj','Opposed to podcast','against,opposing','B2'],
      ['nonpodcast','adj','Not involving podcast','without,lacking','B1'],
      ['prepodcast','n','Before podcast','preceding,prior','B2'],
      ['postpodcast','n','After podcast','following,subsequent','B2'],
      ['subpodcast','n','A subdivision of podcast','subset,branch','B2'],
      ['multipodcast','adj','Involving many podcasts','multiple,several','B2'],
      ['interpodcast','adj','Between podcasts','cross,between','B2'],
      ['partisanly','adv','In a partisan manner','biased way','C1'],
      ['partisanness','n','The quality of being partisan','biased quality','C1'],
      ['partisanity','n','The state of being partisan','biased condition','C2'],
      ['unpartisan','adj','Not partisan','not biased','C1'],
      ['inpartisan','adj','Not partisan','not biased','C2'],
      ['nonpartisan','adj','Not partisan','not biased','C1'],
      ['semipartisan','adj','Partially partisan','partly biased','C2'],
      ['overpartisan','adj','Excessively partisan','too biased','C2'],
      ['ultrapartisan','adj','Extremely partisan','very biased','C2'],
      ['inflammatorily','adv','In a inflammatory manner','provocative way','C1'],
      ['inflammatorness','n','The quality of being inflammatory','provocative quality','C1'],
      ['inflammatority','n','The state of being inflammatory','provocative condition','C2'],
      ['uninflammatory','adj','Not inflammatory','not provocative','C1'],
      ['ininflammatory','adj','Not inflammatory','not provocative','C2'],
      ['noninflammatory','adj','Not inflammatory','not provocative','C1'],
      ['semiinflammatory','adj','Partially inflammatory','partly provocative','C2'],
      ['overinflammatory','adj','Excessively inflammatory','too provocative','C2'],
      ['ultrainflammatory','adj','Extremely inflammatory','very provocative','C2'],
      ['mainstreamly','adv','In a mainstream manner','popular way','B2'],
      ['mainstreamness','n','The quality of being mainstream','popular quality','B2'],
      ['mainstreamity','n','The state of being mainstream','popular condition','C1'],
      ['unmainstream','adj','Not mainstream','not popular','B2'],
      ['inmainstream','adj','Not mainstream','not popular','C1'],
      ['nonmainstream','adj','Not mainstream','not popular','B2'],
      ['semimainstream','adj','Partially mainstream','partly popular','C1'],
      ['overmainstream','adj','Excessively mainstream','too popular','C1'],
      ['ultramainstream','adj','Extremely mainstream','very popular','C1'],
      ['virally','adv','In a viral manner','trending way','B2'],
      ['viralness','n','The quality of being viral','trending quality','B2'],
      ['unviral','adj','Not viral','not trending','B2'],
      ['inviral','adj','Not viral','not trending','C1'],
      ['nonviral','adj','Not viral','not trending','B2'],
      ['semiviral','adj','Partially viral','partly trending','C1'],
      ['overviral','adj','Excessively viral','too trending','C1'],
      ['ultraviral','adj','Extremely viral','very trending','C1'],
      ['defamatory','adj','Damaging to a persons reputation','slanderous,libellous,injurious','C1'],
      ['defamatorily','adv','In a defamatory manner','slanderous way','C1'],
      ['defamatorness','n','The quality of being defamatory','slanderous quality','C1'],
      ['defamatority','n','The state of being defamatory','slanderous condition','C2'],
      ['undefamatory','adj','Not defamatory','not slanderous','C1'],
      ['indefamatory','adj','Not defamatory','not slanderous','C2'],
      ['nondefamatory','adj','Not defamatory','not slanderous','C1'],
      ['semidefamatory','adj','Partially defamatory','partly slanderous','C2'],
      ['overdefamatory','adj','Excessively defamatory','too slanderous','C2'],
      ['ultradefamatory','adj','Extremely defamatory','very slanderous','C2'],
      ['investigatively','adv','In a investigative manner','probing way','B2'],
      ['investigativeness','n','The quality of being investigative','probing quality','B2'],
      ['investigativeity','n','The state of being investigative','probing condition','C1'],
      ['uninvestigative','adj','Not investigative','not probing','B2'],
      ['ininvestigative','adj','Not investigative','not probing','C1'],
      ['noninvestigative','adj','Not investigative','not probing','B2'],
      ['semiinvestigative','adj','Partially investigative','partly probing','C1'],
      ['overinvestigative','adj','Excessively investigative','too probing','C1'],
      ['ultrainvestigative','adj','Extremely investigative','very probing','C1'],
      ['freelanceity','n','The state of being freelance','independent condition','C1'],
      ['infreelance','adj','Not freelance','not independent','C1'],
      ['nonfreelance','adj','Not freelance','not independent','B2'],
      ['semifreelance','adj','Partially freelance','partly independent','C1'],
      ['overfreelance','adj','Excessively freelance','too independent','C1'],
      ['ultrafreelance','adj','Extremely freelance','very independent','C1'],
      ['unbiasedly','adv','In a unbiased manner','impartial way','B2'],
      ['unbiasedness','n','The quality of being unbiased','impartial quality','B2'],
      ['unbiasedity','n','The state of being unbiased','impartial condition','C1'],
      ['ununbiased','adj','Not unbiased','not impartial','B2'],
      ['inunbiased','adj','Not unbiased','not impartial','C1'],
      ['nonunbiased','adj','Not unbiased','not impartial','B2'],
      ['semiunbiased','adj','Partially unbiased','partly impartial','C1'],
      ['overunbiased','adj','Excessively unbiased','too impartial','C1'],
      ['ultraunbiased','adj','Extremely unbiased','very impartial','C1'],
      ['fabricatation','n','The act of fabricating','falsify process','B2'],
      ['fabricatment','n','The result of fabricating','falsify outcome','B2'],
      ['fabricatance','n','The state of fabricating','falsify state','B2'],
      ['fabricatence','n','The quality of fabricating','falsify quality','B2'],
      ['fabricatal','n','An act of fabricating','falsify event','C1'],
      ['fabricater','n','One who fabricates','falsify person','B2'],
      ['fabricator','n','One who fabricates','falsify agent','B2'],
      ['fabricatee','n','One who is fabricated','falsify recipient','C1'],
      ['fabricatable','adj','Capable of being fabricated','falsify,possible','C1'],
      ['fabricatible','adj','Able to be fabricated','falsify,feasible','C1'],
      ['fabricative','adj','Tending to fabricate','falsify,active','B2'],
      ['fabricating','adj','Currently fabricating','falsify,ongoing','B2'],
      ['fabricated','adj','Having been fabricated','falsify,completed','B2'],
      ['refabricate','v','To fabricate again','falsify again,repeat','B2'],
      ['unfabricate','v','To reverse fabricating','reverse,undo','C1'],
      ['overfabricate','v','To fabricate excessively','excess,too much','C1'],
      ['underfabricate','v','To fabricate insufficiently','insufficient,inadequate','C1'],
      ['misfabricate','v','To fabricate incorrectly','wrongly,incorrectly','C1'],
      ['cofabricate','v','To fabricate together','jointly,together','C1'],
      ['refabricatation','n','The act of fabricating again','re-falsify','C1'],
      ['overfabricatation','n','Excessive fabricating','excess falsify','C1'],
      ['plagiarize','v','To copy work without attribution','copy,steal,appropriate','B2'],
      ['plagiarization','n','The act of plagiarizing','copy process','B2'],
      ['plagiarizment','n','The result of plagiarizing','copy outcome','B2'],
      ['plagiarizance','n','The state of plagiarizing','copy state','B2'],
      ['plagiarizence','n','The quality of plagiarizing','copy quality','B2'],
      ['plagiarizal','n','An act of plagiarizing','copy event','C1'],
      ['plagiarizer','n','One who plagiarizes','copy person','B2'],
      ['plagiarizor','n','One who plagiarizes','copy agent','B2'],
      ['plagiarizee','n','One who is plagiarized','copy recipient','C1'],
      ['plagiarizable','adj','Capable of being plagiarized','copy,possible','C1'],
      ['plagiarizible','adj','Able to be plagiarized','copy,feasible','C1'],
      ['plagiarizive','adj','Tending to plagiarize','copy,active','B2'],
      ['plagiarizing','adj','Currently plagiarizing','copy,ongoing','B2'],
      ['plagiarized','adj','Having been plagiarized','copy,completed','B2'],
      ['replagiarize','v','To plagiarize again','copy again,repeat','B2'],
      ['unplagiarize','v','To reverse plagiarizing','reverse,undo','C1'],
      ['overplagiarize','v','To plagiarize excessively','excess,too much','C1'],
      ['underplagiarize','v','To plagiarize insufficiently','insufficient,inadequate','C1'],
      ['misplagiarize','v','To plagiarize incorrectly','wrongly,incorrectly','C1'],
      ['preplagiarize','v','To plagiarize beforehand','before,in advance','C1'],
      ['coplagiarize','v','To plagiarize together','jointly,together','C1'],
      ['replagiarization','n','The act of plagiarizing again','re-copy','C1'],
      ['overplagiarization','n','Excessive plagiarizing','excess copy','C1'],
      ['anonymize','v','To remove identifying information','conceal,de-identify,mask','C1'],
      ['anonymization','n','The act of anonymizing','conceal process','C1'],
      ['anonymizment','n','The result of anonymizing','conceal outcome','C1'],
      ['anonymizance','n','The state of anonymizing','conceal state','C1'],
      ['anonymizence','n','The quality of anonymizing','conceal quality','C1'],
      ['anonymizal','n','An act of anonymizing','conceal event','C2'],
      ['anonymizer','n','One who anonymizes','conceal person','C1'],
      ['anonymizor','n','One who anonymizes','conceal agent','C1'],
      ['anonymizee','n','One who is anonymized','conceal recipient','C2'],
      ['anonymizable','adj','Capable of being anonymized','conceal,possible','C2'],
      ['anonymizible','adj','Able to be anonymized','conceal,feasible','C2'],
      ['anonymizive','adj','Tending to anonymize','conceal,active','C1'],
      ['anonymizing','adj','Currently anonymizing','conceal,ongoing','C1'],
      ['anonymized','adj','Having been anonymized','conceal,completed','C1'],
      ['reanonymize','v','To anonymize again','conceal again,repeat','C1'],
      ['unanonymize','v','To reverse anonymizing','reverse,undo','C2'],
      ['overanonymize','v','To anonymize excessively','excess,too much','C2'],
      ['underanonymize','v','To anonymize insufficiently','insufficient,inadequate','C2'],
      ['misanonymize','v','To anonymize incorrectly','wrongly,incorrectly','C2'],
      ['preanonymize','v','To anonymize beforehand','before,in advance','C2'],
      ['coanonymize','v','To anonymize together','jointly,together','C2'],
      ['reanonymization','n','The act of anonymizing again','re-conceal','C2'],
      ['overanonymization','n','Excessive anonymizing','excess conceal','C2'],
      ['curate','v','To select and organize content','select,compile,organize','B2'],
      ['curatation','n','The act of curating','select process','B2'],
      ['curatment','n','The result of curating','select outcome','B2'],
      ['curatance','n','The state of curating','select state','B2'],
      ['curatence','n','The quality of curating','select quality','B2'],
      ['curatal','n','An act of curating','select event','C1'],
      ['curater','n','One who curates','select person','B2'],
      ['curatee','n','One who is curated','select recipient','C1'],
      ['curatable','adj','Capable of being curated','select,possible','C1'],
      ['curatible','adj','Able to be curated','select,feasible','C1'],
      ['curative','adj','Tending to curate','select,active','B2'],
      ['curating','adj','Currently curating','select,ongoing','B2'],
      ['curated','adj','Having been curated','select,completed','B2'],
      ['recurate','v','To curate again','select again,repeat','B2'],
      ['uncurate','v','To reverse curating','reverse,undo','C1'],
      ['overcurate','v','To curate excessively','excess,too much','C1'],
      ['undercurate','v','To curate insufficiently','insufficient,inadequate','C1'],
      ['miscurate','v','To curate incorrectly','wrongly,incorrectly','C1'],
      ['precurate','v','To curate beforehand','before,in advance','C1'],
      ['cocurate','v','To curate together','jointly,together','C1'],
      ['recuratation','n','The act of curating again','re-select','C1'],
      ['overcuratation','n','Excessive curating','excess select','C1'],
      ['amplify','v','To increase the reach of a message','boost,magnify,intensify','B2'],
      ['amplifyation','n','The act of amplifying','boost process','B2'],
    ],
  },
  collocations: {}
};
