// Auto-generated vocab boost group 85
module.exports = {
  vocab: {
    family: [
      ['monogamyal','adj','Relating to monogamy','single marriage-related,pertaining to','C1'],
      ['monogamyic','adj','Of or relating to monogamy','single marriage-based,characteristic','C1'],
      ['monogamyous','adj','Full of monogamy','single marriage-filled,abundant','C2'],
      ['monogamyful','adj','Full of monogamy','single marriage-rich,abounding','C1'],
      ['monogamyless','adj','Without monogamy','lacking,without','C1'],
      ['monogamyism','n','The ideology of monogamy','single marriage ideology,doctrine','C2'],
      ['monogamyist','n','A person focused on monogamy','single marriage specialist,advocate','C2'],
      ['monogamyise','v','To make into monogamy','single marriage,convert','C2'],
      ['monogamyize','v','To make or become monogamy','single marriage,transform','C2'],
      ['antimonogamy','adj','Opposed to monogamy','against,opposing','C2'],
      ['nonmonogamy','adj','Not involving monogamy','without,lacking','C1'],
      ['premonogamy','n','Before monogamy','preceding,prior','C2'],
      ['postmonogamy','n','After monogamy','following,subsequent','C2'],
      ['submonogamy','n','A subdivision of monogamy','subset,branch','C2'],
      ['multimonogamy','adj','Involving many monogamys','multiple,several','C2'],
      ['intermonogamy','adj','Between monogamys','cross,between','C2'],
      ['polygamyic','adj','Of or relating to polygamy','multiple marriage-based,characteristic','C1'],
      ['polygamyous','adj','Full of polygamy','multiple marriage-filled,abundant','C2'],
      ['polygamyful','adj','Full of polygamy','multiple marriage-rich,abounding','C1'],
      ['polygamyless','adj','Without polygamy','lacking,without','C1'],
      ['polygamyism','n','The ideology of polygamy','multiple marriage ideology,doctrine','C2'],
      ['polygamyist','n','A person focused on polygamy','multiple marriage specialist,advocate','C2'],
      ['polygamyise','v','To make into polygamy','multiple marriage,convert','C2'],
      ['polygamyize','v','To make or become polygamy','multiple marriage,transform','C2'],
      ['antipolygamy','adj','Opposed to polygamy','against,opposing','C2'],
      ['nonpolygamy','adj','Not involving polygamy','without,lacking','C1'],
      ['prepolygamy','n','Before polygamy','preceding,prior','C2'],
      ['postpolygamy','n','After polygamy','following,subsequent','C2'],
      ['subpolygamy','n','A subdivision of polygamy','subset,branch','C2'],
      ['multipolygamy','adj','Involving many polygamys','multiple,several','C2'],
      ['interpolygamy','adj','Between polygamys','cross,between','C2'],
    ],
    history: [
      ['colonize','v','To establish control over a territory','settle,occupy,conquer','B2'],
      ['colonization','n','The act of colonizing','settle process','B2'],
      ['colonizment','n','The result of colonizing','settle outcome','B2'],
      ['colonizance','n','The state of colonizing','settle state','B2'],
      ['colonizence','n','The quality of colonizing','settle quality','B2'],
      ['colonizal','n','An act of colonizing','settle event','C1'],
      ['colonizer','n','One who colonizes','settle person','B2'],
      ['colonizor','n','One who colonizes','settle agent','B2'],
      ['colonizee','n','One who is colonized','settle recipient','C1'],
      ['colonizable','adj','Capable of being colonized','settle,possible','C1'],
      ['colonizible','adj','Able to be colonized','settle,feasible','C1'],
      ['colonizive','adj','Tending to colonize','settle,active','B2'],
      ['colonizing','adj','Currently colonizing','settle,ongoing','B2'],
      ['colonized','adj','Having been colonized','settle,completed','B2'],
      ['recolonize','v','To colonize again','settle again,repeat','B2'],
      ['uncolonize','v','To reverse colonizing','reverse,undo','C1'],
      ['overcolonize','v','To colonize excessively','excess,too much','C1'],
      ['undercolonize','v','To colonize insufficiently','insufficient,inadequate','C1'],
      ['miscolonize','v','To colonize incorrectly','wrongly,incorrectly','C1'],
      ['precolonize','v','To colonize beforehand','before,in advance','C1'],
      ['cocolonize','v','To colonize together','jointly,together','C1'],
      ['recolonization','n','The act of colonizing again','re-settle','C1'],
      ['overcolonization','n','Excessive colonizing','excess settle','C1'],
      ['annexment','n','The result of annexing','take over outcome','C1'],
      ['annexance','n','The state of annexing','take over state','C1'],
      ['annexence','n','The quality of annexing','take over quality','C1'],
      ['annexal','n','An act of annexing','take over event','C2'],
      ['annexer','n','One who annexs','take over person','C1'],
      ['annexor','n','One who annexs','take over agent','C1'],
      ['annexee','n','One who is annexd','take over recipient','C2'],
      ['annexable','adj','Capable of being annexd','take over,possible','C2'],
      ['annexible','adj','Able to be annexd','take over,feasible','C2'],
      ['annexive','adj','Tending to annex','take over,active','C1'],
      ['annexing','adj','Currently annexing','take over,ongoing','C1'],
      ['annexed','adj','Having been annexd','take over,completed','C1'],
      ['reannex','v','To annex again','take over again,repeat','C1'],
      ['unannex','v','To reverse annexing','reverse,undo','C2'],
      ['overannex','v','To annex excessively','excess,too much','C2'],
      ['underannex','v','To annex insufficiently','insufficient,inadequate','C2'],
      ['misannex','v','To annex incorrectly','wrongly,incorrectly','C2'],
      ['preannex','v','To annex beforehand','before,in advance','C2'],
      ['coannex','v','To annex together','jointly,together','C2'],
      ['reannexation','n','The act of annexing again','re-take over','C2'],
      ['overannexation','n','Excessive annexing','excess take over','C2'],
      ['chroniclation','n','The act of chronicling','document process','C1'],
      ['chroniclment','n','The result of chronicling','document outcome','C1'],
      ['chroniclance','n','The state of chronicling','document state','C1'],
      ['chroniclence','n','The quality of chronicling','document quality','C1'],
      ['chroniclal','n','An act of chronicling','document event','C2'],
      ['chronicler','n','One who chronicles','document person','C1'],
      ['chroniclor','n','One who chronicles','document agent','C1'],
      ['chroniclee','n','One who is chronicled','document recipient','C2'],
      ['chroniclable','adj','Capable of being chronicled','document,possible','C2'],
      ['chroniclible','adj','Able to be chronicled','document,feasible','C2'],
      ['chroniclive','adj','Tending to chronicle','document,active','C1'],
      ['chronicling','adj','Currently chronicling','document,ongoing','C1'],
      ['chronicled','adj','Having been chronicled','document,completed','C1'],
      ['rechronicle','v','To chronicle again','document again,repeat','C1'],
      ['unchronicle','v','To reverse chronicling','reverse,undo','C2'],
      ['overchronicle','v','To chronicle excessively','excess,too much','C2'],
      ['underchronicle','v','To chronicle insufficiently','insufficient,inadequate','C2'],
      ['mischronicle','v','To chronicle incorrectly','wrongly,incorrectly','C2'],
      ['prechronicle','v','To chronicle beforehand','before,in advance','C2'],
      ['cochronicle','v','To chronicle together','jointly,together','C2'],
      ['rechroniclation','n','The act of chronicling again','re-document','C2'],
      ['overchroniclation','n','Excessive chronicling','excess document','C2'],
      ['excavatation','n','The act of excavating','unearth process','B2'],
      ['excavatment','n','The result of excavating','unearth outcome','B2'],
      ['excavatance','n','The state of excavating','unearth state','B2'],
      ['excavatence','n','The quality of excavating','unearth quality','B2'],
      ['excavatal','n','An act of excavating','unearth event','C1'],
      ['excavater','n','One who excavates','unearth person','B2'],
      ['excavator','n','One who excavates','unearth agent','B2'],
      ['excavatee','n','One who is excavated','unearth recipient','C1'],
      ['excavatable','adj','Capable of being excavated','unearth,possible','C1'],
      ['excavatible','adj','Able to be excavated','unearth,feasible','C1'],
      ['excavative','adj','Tending to excavate','unearth,active','B2'],
      ['excavating','adj','Currently excavating','unearth,ongoing','B2'],
      ['excavated','adj','Having been excavated','unearth,completed','B2'],
      ['reexcavate','v','To excavate again','unearth again,repeat','B2'],
      ['unexcavate','v','To reverse excavating','reverse,undo','C1'],
      ['overexcavate','v','To excavate excessively','excess,too much','C1'],
      ['underexcavate','v','To excavate insufficiently','insufficient,inadequate','C1'],
      ['misexcavate','v','To excavate incorrectly','wrongly,incorrectly','C1'],
      ['preexcavate','v','To excavate beforehand','before,in advance','C1'],
      ['coexcavate','v','To excavate together','jointly,together','C1'],
      ['reexcavatation','n','The act of excavating again','re-unearth','C1'],
      ['overexcavatation','n','Excessive excavating','excess unearth','C1'],
      ['abdicatation','n','The act of abdicating','step down process','C1'],
      ['abdicatment','n','The result of abdicating','step down outcome','C1'],
      ['abdicatance','n','The state of abdicating','step down state','C1'],
      ['abdicatence','n','The quality of abdicating','step down quality','C1'],
      ['abdicatal','n','An act of abdicating','step down event','C2'],
      ['abdicater','n','One who abdicates','step down person','C1'],
      ['abdicator','n','One who abdicates','step down agent','C1'],
      ['abdicatee','n','One who is abdicated','step down recipient','C2'],
      ['abdicatable','adj','Capable of being abdicated','step down,possible','C2'],
      ['abdicatible','adj','Able to be abdicated','step down,feasible','C2'],
      ['abdicative','adj','Tending to abdicate','step down,active','C1'],
      ['abdicating','adj','Currently abdicating','step down,ongoing','C1'],
      ['abdicated','adj','Having been abdicated','step down,completed','C1'],
      ['reabdicate','v','To abdicate again','step down again,repeat','C1'],
      ['unabdicate','v','To reverse abdicating','reverse,undo','C2'],
      ['overabdicate','v','To abdicate excessively','excess,too much','C2'],
      ['underabdicate','v','To abdicate insufficiently','insufficient,inadequate','C2'],
      ['misabdicate','v','To abdicate incorrectly','wrongly,incorrectly','C2'],
      ['preabdicate','v','To abdicate beforehand','before,in advance','C2'],
      ['coabdicate','v','To abdicate together','jointly,together','C2'],
      ['reabdicatation','n','The act of abdicating again','re-step down','C2'],
      ['overabdicatation','n','Excessive abdicating','excess step down','C2'],
      ['persecutation','n','The act of persecuting','oppress process','B2'],
      ['persecutment','n','The result of persecuting','oppress outcome','B2'],
      ['persecutance','n','The state of persecuting','oppress state','B2'],
      ['persecutence','n','The quality of persecuting','oppress quality','B2'],
      ['persecutal','n','An act of persecuting','oppress event','C1'],
      ['persecuter','n','One who persecutes','oppress person','B2'],
      ['persecutor','n','One who persecutes','oppress agent','B2'],
      ['persecutee','n','One who is persecuted','oppress recipient','C1'],
      ['persecutable','adj','Capable of being persecuted','oppress,possible','C1'],
      ['persecutible','adj','Able to be persecuted','oppress,feasible','C1'],
      ['persecutive','adj','Tending to persecute','oppress,active','B2'],
      ['persecuting','adj','Currently persecuting','oppress,ongoing','B2'],
      ['persecuted','adj','Having been persecuted','oppress,completed','B2'],
      ['repersecute','v','To persecute again','oppress again,repeat','B2'],
      ['unpersecute','v','To reverse persecuting','reverse,undo','C1'],
      ['overpersecute','v','To persecute excessively','excess,too much','C1'],
      ['underpersecute','v','To persecute insufficiently','insufficient,inadequate','C1'],
      ['mispersecute','v','To persecute incorrectly','wrongly,incorrectly','C1'],
      ['prepersecute','v','To persecute beforehand','before,in advance','C1'],
      ['copersecute','v','To persecute together','jointly,together','C1'],
      ['repersecutation','n','The act of persecuting again','re-oppress','C1'],
      ['overpersecutation','n','Excessive persecuting','excess oppress','C1'],
      ['feudally','adv','In a feudal manner','medieval way','C1'],
      ['feudalness','n','The quality of being feudal','medieval quality','C1'],
      ['feudality','n','The state of being feudal','medieval condition','C2'],
      ['unfeudal','adj','Not feudal','not medieval','C1'],
      ['infeudal','adj','Not feudal','not medieval','C2'],
      ['nonfeudal','adj','Not feudal','not medieval','C1'],
      ['semifeudal','adj','Partially feudal','partly medieval','C2'],
      ['overfeudal','adj','Excessively feudal','too medieval','C2'],
      ['ultrafeudal','adj','Extremely feudal','very medieval','C2'],
      ['prehistoricly','adv','In a prehistoric manner','ancient way','B2'],
      ['prehistoricness','n','The quality of being prehistoric','ancient quality','B2'],
      ['prehistoricity','n','The state of being prehistoric','ancient condition','C1'],
      ['unprehistoric','adj','Not prehistoric','not ancient','B2'],
      ['inprehistoric','adj','Not prehistoric','not ancient','C1'],
      ['nonprehistoric','adj','Not prehistoric','not ancient','B2'],
      ['semiprehistoric','adj','Partially prehistoric','partly ancient','C1'],
      ['overprehistoric','adj','Excessively prehistoric','too ancient','C1'],
      ['ultraprehistoric','adj','Extremely prehistoric','very ancient','C1'],
      ['medievality','n','The state of being medieval','middle age condition','C1'],
      ['inmedieval','adj','Not medieval','not middle age','C1'],
      ['nonmedieval','adj','Not medieval','not middle age','B2'],
      ['semimedieval','adj','Partially medieval','partly middle age','C1'],
      ['overmedieval','adj','Excessively medieval','too middle age','C1'],
      ['ultramedieval','adj','Extremely medieval','very middle age','C1'],
      ['antiquarianly','adv','In a antiquarian manner','historical way','C1'],
      ['antiquarianness','n','The quality of being antiquarian','historical quality','C1'],
      ['antiquarianity','n','The state of being antiquarian','historical condition','C2'],
      ['unantiquarian','adj','Not antiquarian','not historical','C1'],
      ['inantiquarian','adj','Not antiquarian','not historical','C2'],
      ['nonantiquarian','adj','Not antiquarian','not historical','C1'],
      ['semiantiquarian','adj','Partially antiquarian','partly historical','C2'],
      ['overantiquarian','adj','Excessively antiquarian','too historical','C2'],
      ['ultraantiquarian','adj','Extremely antiquarian','very historical','C2'],
      ['civilizational','adj','Relating to civilization','society-related,pertaining to','B2'],
      ['civilizationic','adj','Of or relating to civilization','society-based,characteristic','B2'],
      ['civilizationous','adj','Full of civilization','society-filled,abundant','C1'],
      ['civilizationful','adj','Full of civilization','society-rich,abounding','B2'],
      ['civilizationless','adj','Without civilization','lacking,without','B2'],
      ['civilizationism','n','The ideology of civilization','society ideology,doctrine','C1'],
      ['civilizationist','n','A person focused on civilization','society specialist,advocate','C1'],
      ['civilizationise','v','To make into civilization','society,convert','C1'],
      ['civilizationize','v','To make or become civilization','society,transform','C1'],
      ['anticivilization','adj','Opposed to civilization','against,opposing','C1'],
      ['noncivilization','adj','Not involving civilization','without,lacking','B2'],
      ['precivilization','n','Before civilization','preceding,prior','C1'],
      ['postcivilization','n','After civilization','following,subsequent','C1'],
      ['subcivilization','n','A subdivision of civilization','subset,branch','C1'],
      ['multicivilization','adj','Involving many civilizations','multiple,several','C1'],
      ['intercivilization','adj','Between civilizations','cross,between','C1'],
      ['dynastyic','adj','Of or relating to dynasty','royal line-based,characteristic','B2'],
      ['dynastyous','adj','Full of dynasty','royal line-filled,abundant','C1'],
      ['dynastyful','adj','Full of dynasty','royal line-rich,abounding','B2'],
      ['dynastyless','adj','Without dynasty','lacking,without','B2'],
      ['dynastyism','n','The ideology of dynasty','royal line ideology,doctrine','C1'],
      ['dynastyist','n','A person focused on dynasty','royal line specialist,advocate','C1'],
      ['dynastyise','v','To make into dynasty','royal line,convert','C1'],
      ['dynastyize','v','To make or become dynasty','royal line,transform','C1'],
      ['antidynasty','adj','Opposed to dynasty','against,opposing','C1'],
      ['nondynasty','adj','Not involving dynasty','without,lacking','B2'],
      ['predynasty','n','Before dynasty','preceding,prior','C1'],
      ['postdynasty','n','After dynasty','following,subsequent','C1'],
      ['subdynasty','n','A subdivision of dynasty','subset,branch','C1'],
      ['multidynasty','adj','Involving many dynastys','multiple,several','C1'],
      ['interdynasty','adj','Between dynastys','cross,between','C1'],
      ['revolutionic','adj','Of or relating to revolution','uprising-based,characteristic','B2'],
      ['revolutionous','adj','Full of revolution','uprising-filled,abundant','C1'],
      ['revolutionful','adj','Full of revolution','uprising-rich,abounding','B2'],
      ['revolutionless','adj','Without revolution','lacking,without','B2'],
      ['revolutionism','n','The ideology of revolution','uprising ideology,doctrine','C1'],
      ['revolutionist','n','A person focused on revolution','uprising specialist,advocate','C1'],
      ['revolutionise','v','To make into revolution','uprising,convert','C1'],
      ['revolutionize','v','To make or become revolution','uprising,transform','C1'],
      ['antirevolution','adj','Opposed to revolution','against,opposing','C1'],
      ['nonrevolution','adj','Not involving revolution','without,lacking','B2'],
      ['prerevolution','n','Before revolution','preceding,prior','C1'],
      ['postrevolution','n','After revolution','following,subsequent','C1'],
      ['subrevolution','n','A subdivision of revolution','subset,branch','C1'],
      ['multirevolution','adj','Involving many revolutions','multiple,several','C1'],
      ['interrevolution','adj','Between revolutions','cross,between','C1'],
      ['imperialismic','adj','Of or relating to imperialism','colonialism-based,characteristic','B2'],
      ['imperialismous','adj','Full of imperialism','colonialism-filled,abundant','C1'],
      ['imperialismful','adj','Full of imperialism','colonialism-rich,abounding','B2'],
      ['imperialismless','adj','Without imperialism','lacking,without','B2'],
      ['imperialismism','n','The ideology of imperialism','colonialism ideology,doctrine','C1'],
      ['imperialismist','n','A person focused on imperialism','colonialism specialist,advocate','C1'],
      ['imperialismise','v','To make into imperialism','colonialism,convert','C1'],
      ['imperialismize','v','To make or become imperialism','colonialism,transform','C1'],
    ],
  },
  collocations: {}
};
