// Auto-generated vocab boost group 62
module.exports = {
  vocab: {
    communication: [
      ['discourseism','n','The ideology of discourse','discussion ideology,doctrine','C1'],
      ['discourseist','n','A person focused on discourse','discussion specialist,advocate','C1'],
      ['discourseise','v','To make into discourse','discussion,convert','C1'],
      ['discourseize','v','To make or become discourse','discussion,transform','C1'],
      ['antidiscourse','adj','Opposed to discourse','against,opposing','C1'],
      ['nondiscourse','adj','Not involving discourse','without,lacking','B2'],
      ['prediscourse','n','Before discourse','preceding,prior','C1'],
      ['postdiscourse','n','After discourse','following,subsequent','C1'],
      ['subdiscourse','n','A subdivision of discourse','subset,branch','C1'],
      ['multidiscourse','adj','Involving many discourses','multiple,several','C1'],
      ['interdiscourse','adj','Between discourses','cross,between','C1'],
      ['euphemismic','adj','Of or relating to euphemism','polite term-based,characteristic','C1'],
      ['euphemismous','adj','Full of euphemism','polite term-filled,abundant','C2'],
      ['euphemismful','adj','Full of euphemism','polite term-rich,abounding','C1'],
      ['euphemismless','adj','Without euphemism','lacking,without','C1'],
      ['euphemismism','n','The ideology of euphemism','polite term ideology,doctrine','C2'],
      ['euphemismist','n','A person focused on euphemism','polite term specialist,advocate','C2'],
      ['euphemismise','v','To make into euphemism','polite term,convert','C2'],
      ['euphemismize','v','To make or become euphemism','polite term,transform','C2'],
      ['antieuphemism','adj','Opposed to euphemism','against,opposing','C2'],
      ['noneuphemism','adj','Not involving euphemism','without,lacking','C1'],
      ['preeuphemism','n','Before euphemism','preceding,prior','C2'],
      ['posteuphemism','n','After euphemism','following,subsequent','C2'],
      ['subeuphemism','n','A subdivision of euphemism','subset,branch','C2'],
      ['multieuphemism','adj','Involving many euphemisms','multiple,several','C2'],
      ['intereuphemism','adj','Between euphemisms','cross,between','C2'],
      ['colloquialismic','adj','Of or relating to colloquialism','slang-based,characteristic','C1'],
      ['colloquialismous','adj','Full of colloquialism','slang-filled,abundant','C2'],
      ['colloquialismful','adj','Full of colloquialism','slang-rich,abounding','C1'],
      ['colloquialismless','adj','Without colloquialism','lacking,without','C1'],
      ['colloquialismism','n','The ideology of colloquialism','slang ideology,doctrine','C2'],
      ['colloquialismist','n','A person focused on colloquialism','slang specialist,advocate','C2'],
      ['colloquialismise','v','To make into colloquialism','slang,convert','C2'],
      ['colloquialismize','v','To make or become colloquialism','slang,transform','C2'],
      ['anticolloquialism','adj','Opposed to colloquialism','against,opposing','C2'],
      ['noncolloquialism','adj','Not involving colloquialism','without,lacking','C1'],
      ['precolloquialism','n','Before colloquialism','preceding,prior','C2'],
      ['postcolloquialism','n','After colloquialism','following,subsequent','C2'],
      ['subcolloquialism','n','A subdivision of colloquialism','subset,branch','C2'],
      ['multicolloquialism','adj','Involving many colloquialisms','multiple,several','C2'],
      ['intercolloquialism','adj','Between colloquialisms','cross,between','C2'],
      ['jargonic','adj','Of or relating to jargon','terminology-based,characteristic','B2'],
      ['jargonous','adj','Full of jargon','terminology-filled,abundant','C1'],
      ['jargonful','adj','Full of jargon','terminology-rich,abounding','B2'],
      ['jargonless','adj','Without jargon','lacking,without','B2'],
      ['jargonism','n','The ideology of jargon','terminology ideology,doctrine','C1'],
      ['jargonist','n','A person focused on jargon','terminology specialist,advocate','C1'],
      ['jargonise','v','To make into jargon','terminology,convert','C1'],
      ['jargonize','v','To make or become jargon','terminology,transform','C1'],
      ['antijargon','adj','Opposed to jargon','against,opposing','C1'],
      ['nonjargon','adj','Not involving jargon','without,lacking','B2'],
      ['prejargon','n','Before jargon','preceding,prior','C1'],
      ['postjargon','n','After jargon','following,subsequent','C1'],
      ['subjargon','n','A subdivision of jargon','subset,branch','C1'],
      ['multijargon','adj','Involving many jargons','multiple,several','C1'],
      ['interjargon','adj','Between jargons','cross,between','C1'],
      ['vernacularic','adj','Of or relating to vernacular','dialect-based,characteristic','C1'],
      ['vernacularous','adj','Full of vernacular','dialect-filled,abundant','C2'],
      ['vernacularful','adj','Full of vernacular','dialect-rich,abounding','C1'],
      ['vernacularless','adj','Without vernacular','lacking,without','C1'],
      ['vernacularism','n','The ideology of vernacular','dialect ideology,doctrine','C2'],
      ['vernacularist','n','A person focused on vernacular','dialect specialist,advocate','C2'],
      ['vernacularise','v','To make into vernacular','dialect,convert','C2'],
      ['vernacularize','v','To make or become vernacular','dialect,transform','C2'],
      ['antivernacular','adj','Opposed to vernacular','against,opposing','C2'],
      ['prevernacular','n','Before vernacular','preceding,prior','C2'],
      ['postvernacular','n','After vernacular','following,subsequent','C2'],
      ['subvernacular','n','A subdivision of vernacular','subset,branch','C2'],
      ['multivernacular','adj','Involving many vernaculars','multiple,several','C2'],
      ['intervernacular','adj','Between vernaculars','cross,between','C2'],
      ['ambiguityic','adj','Of or relating to ambiguity','vagueness-based,characteristic','B2'],
      ['ambiguityous','adj','Full of ambiguity','vagueness-filled,abundant','C1'],
      ['ambiguityful','adj','Full of ambiguity','vagueness-rich,abounding','B2'],
      ['ambiguityless','adj','Without ambiguity','lacking,without','B2'],
      ['ambiguityism','n','The ideology of ambiguity','vagueness ideology,doctrine','C1'],
      ['ambiguityist','n','A person focused on ambiguity','vagueness specialist,advocate','C1'],
      ['ambiguityise','v','To make into ambiguity','vagueness,convert','C1'],
      ['ambiguityize','v','To make or become ambiguity','vagueness,transform','C1'],
      ['antiambiguity','adj','Opposed to ambiguity','against,opposing','C1'],
      ['nonambiguity','adj','Not involving ambiguity','without,lacking','B2'],
      ['preambiguity','n','Before ambiguity','preceding,prior','C1'],
      ['postambiguity','n','After ambiguity','following,subsequent','C1'],
      ['subambiguity','n','A subdivision of ambiguity','subset,branch','C1'],
      ['multiambiguity','adj','Involving many ambiguitys','multiple,several','C1'],
      ['interambiguity','adj','Between ambiguitys','cross,between','C1'],
      ['nuanceic','adj','Of or relating to nuance','subtlety-based,characteristic','B2'],
      ['nuanceous','adj','Full of nuance','subtlety-filled,abundant','C1'],
      ['nuanceful','adj','Full of nuance','subtlety-rich,abounding','B2'],
      ['nuanceless','adj','Without nuance','lacking,without','B2'],
      ['nuanceism','n','The ideology of nuance','subtlety ideology,doctrine','C1'],
      ['nuanceist','n','A person focused on nuance','subtlety specialist,advocate','C1'],
      ['nuanceise','v','To make into nuance','subtlety,convert','C1'],
      ['nuanceize','v','To make or become nuance','subtlety,transform','C1'],
      ['antinuance','adj','Opposed to nuance','against,opposing','C1'],
      ['nonnuance','adj','Not involving nuance','without,lacking','B2'],
      ['prenuance','n','Before nuance','preceding,prior','C1'],
      ['postnuance','n','After nuance','following,subsequent','C1'],
      ['subnuance','n','A subdivision of nuance','subset,branch','C1'],
      ['multinuance','adj','Involving many nuances','multiple,several','C1'],
      ['internuance','adj','Between nuances','cross,between','C1'],
      ['eloquence','n','Fluent and persuasive speaking','articulacy,expressiveness,rhetoric','C1'],
      ['eloquenceal','adj','Relating to eloquence','articulacy-related,pertaining to','C1'],
      ['eloquenceic','adj','Of or relating to eloquence','articulacy-based,characteristic','C1'],
      ['eloquenceous','adj','Full of eloquence','articulacy-filled,abundant','C2'],
      ['eloquenceful','adj','Full of eloquence','articulacy-rich,abounding','C1'],
      ['eloquenceless','adj','Without eloquence','lacking,without','C1'],
      ['eloquenceism','n','The ideology of eloquence','articulacy ideology,doctrine','C2'],
      ['eloquenceist','n','A person focused on eloquence','articulacy specialist,advocate','C2'],
      ['eloquenceise','v','To make into eloquence','articulacy,convert','C2'],
      ['eloquenceize','v','To make or become eloquence','articulacy,transform','C2'],
      ['antieloquence','adj','Opposed to eloquence','against,opposing','C2'],
      ['noneloquence','adj','Not involving eloquence','without,lacking','C1'],
      ['preeloquence','n','Before eloquence','preceding,prior','C2'],
      ['posteloquence','n','After eloquence','following,subsequent','C2'],
      ['subeloquence','n','A subdivision of eloquence','subset,branch','C2'],
      ['multieloquence','adj','Involving many eloquences','multiple,several','C2'],
      ['intereloquence','adj','Between eloquences','cross,between','C2'],
      ['semanticsic','adj','Of or relating to semantics','meaning-based,characteristic','C1'],
      ['semanticsous','adj','Full of semantics','meaning-filled,abundant','C2'],
      ['semanticsful','adj','Full of semantics','meaning-rich,abounding','C1'],
      ['semanticsless','adj','Without semantics','lacking,without','C1'],
      ['semanticsism','n','The ideology of semantics','meaning ideology,doctrine','C2'],
      ['semanticsist','n','A person focused on semantics','meaning specialist,advocate','C2'],
      ['semanticsise','v','To make into semantics','meaning,convert','C2'],
      ['semanticsize','v','To make or become semantics','meaning,transform','C2'],
      ['antisemantics','adj','Opposed to semantics','against,opposing','C2'],
      ['nonsemantics','adj','Not involving semantics','without,lacking','C1'],
      ['presemantics','n','Before semantics','preceding,prior','C2'],
      ['postsemantics','n','After semantics','following,subsequent','C2'],
      ['subsemantics','n','A subdivision of semantics','subset,branch','C2'],
      ['multisemantics','adj','Involving many semanticss','multiple,several','C2'],
      ['intersemantics','adj','Between semanticss','cross,between','C2'],
      ['pragmaticsic','adj','Of or relating to pragmatics','contextual meaning-based,characteristic','C1'],
      ['pragmaticsous','adj','Full of pragmatics','contextual meaning-filled,abundant','C2'],
      ['pragmaticsful','adj','Full of pragmatics','contextual meaning-rich,abounding','C1'],
      ['pragmaticsless','adj','Without pragmatics','lacking,without','C1'],
      ['pragmaticsism','n','The ideology of pragmatics','contextual meaning ideology,doctrine','C2'],
      ['pragmaticsist','n','A person focused on pragmatics','contextual meaning specialist,advocate','C2'],
      ['pragmaticsise','v','To make into pragmatics','contextual meaning,convert','C2'],
      ['pragmaticsize','v','To make or become pragmatics','contextual meaning,transform','C2'],
      ['antipragmatics','adj','Opposed to pragmatics','against,opposing','C2'],
      ['nonpragmatics','adj','Not involving pragmatics','without,lacking','C1'],
      ['prepragmatics','n','Before pragmatics','preceding,prior','C2'],
      ['postpragmatics','n','After pragmatics','following,subsequent','C2'],
      ['subpragmatics','n','A subdivision of pragmatics','subset,branch','C2'],
      ['multipragmatics','adj','Involving many pragmaticss','multiple,several','C2'],
      ['interpragmatics','adj','Between pragmaticss','cross,between','C2'],
      ['nonverbally','adv','In a nonverbal manner','wordless way','B2'],
      ['nonverbalness','n','The quality of being nonverbal','wordless quality','B2'],
      ['nonverbality','n','The state of being nonverbal','wordless condition','C1'],
      ['unnonverbal','adj','Not nonverbal','not wordless','B2'],
      ['innonverbal','adj','Not nonverbal','not wordless','C1'],
      ['nonnonverbal','adj','Not nonverbal','not wordless','B2'],
      ['seminonverbal','adj','Partially nonverbal','partly wordless','C1'],
      ['overnonverbal','adj','Excessively nonverbal','too wordless','C1'],
      ['ultranonverbal','adj','Extremely nonverbal','very wordless','C1'],
      ['conciliatory','adj','Intended to placate or pacify','peaceable,appeasing,soothing','C1'],
      ['conciliatorily','adv','In a conciliatory manner','peaceable way','C1'],
      ['conciliatorness','n','The quality of being conciliatory','peaceable quality','C1'],
      ['conciliatority','n','The state of being conciliatory','peaceable condition','C2'],
      ['unconciliatory','adj','Not conciliatory','not peaceable','C1'],
      ['inconciliatory','adj','Not conciliatory','not peaceable','C2'],
      ['nonconciliatory','adj','Not conciliatory','not peaceable','C1'],
      ['semiconciliatory','adj','Partially conciliatory','partly peaceable','C2'],
      ['overconciliatory','adj','Excessively conciliatory','too peaceable','C2'],
      ['ultraconciliatory','adj','Extremely conciliatory','very peaceable','C2'],
      ['assertively','adv','In a assertive manner','confident way','B2'],
      ['assertiveity','n','The state of being assertive','confident condition','C1'],
      ['unassertive','adj','Not assertive','not confident','B2'],
      ['inassertive','adj','Not assertive','not confident','C1'],
      ['nonassertive','adj','Not assertive','not confident','B2'],
      ['semiassertive','adj','Partially assertive','partly confident','C1'],
      ['overassertive','adj','Excessively assertive','too confident','C1'],
      ['ultraassertive','adj','Extremely assertive','very confident','C1'],
      ['empatheticly','adv','In a empathetic manner','understanding way','B2'],
      ['empatheticness','n','The quality of being empathetic','understanding quality','B2'],
      ['empatheticity','n','The state of being empathetic','understanding condition','C1'],
      ['unempathetic','adj','Not empathetic','not understanding','B2'],
      ['inempathetic','adj','Not empathetic','not understanding','C1'],
      ['nonempathetic','adj','Not empathetic','not understanding','B2'],
      ['semiempathetic','adj','Partially empathetic','partly understanding','C1'],
      ['overempathetic','adj','Excessively empathetic','too understanding','C1'],
      ['ultraempathetic','adj','Extremely empathetic','very understanding','C1'],
      ['succinctly','adv','In a succinct manner','concise way','C1'],
      ['succinctness','n','The quality of being succinct','concise quality','C1'],
      ['succinctity','n','The state of being succinct','concise condition','C2'],
      ['unsuccinct','adj','Not succinct','not concise','C1'],
      ['insuccinct','adj','Not succinct','not concise','C2'],
      ['nonsuccinct','adj','Not succinct','not concise','C1'],
      ['semisuccinct','adj','Partially succinct','partly concise','C2'],
      ['oversuccinct','adj','Excessively succinct','too concise','C2'],
      ['ultrasuccinct','adj','Extremely succinct','very concise','C2'],
      ['verbosely','adv','In a verbose manner','wordy way','C1'],
      ['verboseness','n','The quality of being verbose','wordy quality','C1'],
      ['verboseity','n','The state of being verbose','wordy condition','C2'],
      ['unverbose','adj','Not verbose','not wordy','C1'],
      ['inverbose','adj','Not verbose','not wordy','C2'],
      ['nonverbose','adj','Not verbose','not wordy','C1'],
      ['semiverbose','adj','Partially verbose','partly wordy','C2'],
      ['oververbose','adj','Excessively verbose','too wordy','C2'],
      ['ultraverbose','adj','Extremely verbose','very wordy','C2'],
      ['elocutionic','adj','Of or relating to elocution','diction-based,characteristic','C1'],
      ['elocutionous','adj','Full of elocution','diction-filled,abundant','C2'],
      ['elocutionful','adj','Full of elocution','diction-rich,abounding','C1'],
      ['elocutionless','adj','Without elocution','lacking,without','C1'],
      ['elocutionism','n','The ideology of elocution','diction ideology,doctrine','C2'],
      ['elocutionist','n','A person focused on elocution','diction specialist,advocate','C2'],
      ['elocutionise','v','To make into elocution','diction,convert','C2'],
      ['elocutionize','v','To make or become elocution','diction,transform','C2'],
      ['antielocution','adj','Opposed to elocution','against,opposing','C2'],
      ['nonelocution','adj','Not involving elocution','without,lacking','C1'],
      ['preelocution','n','Before elocution','preceding,prior','C2'],
      ['postelocution','n','After elocution','following,subsequent','C2'],
      ['subelocution','n','A subdivision of elocution','subset,branch','C2'],
      ['multielocution','adj','Involving many elocutions','multiple,several','C2'],
      ['interelocution','adj','Between elocutions','cross,between','C2'],
      ['interlocutoric','adj','Of or relating to interlocutor','speaker-based,characteristic','C2'],
      ['interlocutorous','adj','Full of interlocutor','speaker-filled,abundant','C2'],
      ['interlocutorful','adj','Full of interlocutor','speaker-rich,abounding','C2'],
      ['interlocutorless','adj','Without interlocutor','lacking,without','C2'],
      ['interlocutorism','n','The ideology of interlocutor','speaker ideology,doctrine','C2'],
      ['interlocutorist','n','A person focused on interlocutor','speaker specialist,advocate','C2'],
      ['interlocutorise','v','To make into interlocutor','speaker,convert','C2'],
      ['interlocutorize','v','To make or become interlocutor','speaker,transform','C2'],
      ['antiinterlocutor','adj','Opposed to interlocutor','against,opposing','C2'],
      ['noninterlocutor','adj','Not involving interlocutor','without,lacking','C2'],
      ['preinterlocutor','n','Before interlocutor','preceding,prior','C2'],
      ['postinterlocutor','n','After interlocutor','following,subsequent','C2'],
      ['subinterlocutor','n','A subdivision of interlocutor','subset,branch','C2'],
      ['multiinterlocutor','adj','Involving many interlocutors','multiple,several','C2'],
      ['interinterlocutor','adj','Between interlocutors','cross,between','C2'],
      ['monologueal','adj','Relating to monologue','soliloquy-related,pertaining to','B2'],
      ['monologueic','adj','Of or relating to monologue','soliloquy-based,characteristic','B2'],
      ['monologueous','adj','Full of monologue','soliloquy-filled,abundant','C1'],
      ['monologueful','adj','Full of monologue','soliloquy-rich,abounding','B2'],
      ['monologueless','adj','Without monologue','lacking,without','B2'],
      ['monologueism','n','The ideology of monologue','soliloquy ideology,doctrine','C1'],
      ['monologueist','n','A person focused on monologue','soliloquy specialist,advocate','C1'],
      ['monologueise','v','To make into monologue','soliloquy,convert','C1'],
      ['monologueize','v','To make or become monologue','soliloquy,transform','C1'],
      ['antimonologue','adj','Opposed to monologue','against,opposing','C1'],
      ['nonmonologue','adj','Not involving monologue','without,lacking','B2'],
      ['premonologue','n','Before monologue','preceding,prior','C1'],
      ['postmonologue','n','After monologue','following,subsequent','C1'],
      ['submonologue','n','A subdivision of monologue','subset,branch','C1'],
      ['multimonologue','adj','Involving many monologues','multiple,several','C1'],
      ['intermonologue','adj','Between monologues','cross,between','C1'],
      ['diatribeal','adj','Relating to diatribe','tirade-related,pertaining to','C2'],
      ['diatribeic','adj','Of or relating to diatribe','tirade-based,characteristic','C2'],
      ['diatribeous','adj','Full of diatribe','tirade-filled,abundant','C2'],
    ],
  },
  collocations: {}
};
