// Auto-generated vocab boost group 87
module.exports = {
  vocab: {
    history: [
      ['subarmistice','n','A subdivision of armistice','subset,branch','C2'],
      ['multiarmistice','adj','Involving many armistices','multiple,several','C2'],
      ['interarmistice','adj','Between armistices','cross,between','C2'],
      ['oligarch','n','A ruler in a small governing group','elite ruler,powerful leader','C1'],
      ['oligarchal','adj','Relating to oligarch','elite ruler-related,pertaining to','C1'],
      ['oligarchic','adj','Of or relating to oligarch','elite ruler-based,characteristic','C1'],
      ['oligarchous','adj','Full of oligarch','elite ruler-filled,abundant','C2'],
      ['oligarchful','adj','Full of oligarch','elite ruler-rich,abounding','C1'],
      ['oligarchless','adj','Without oligarch','lacking,without','C1'],
      ['oligarchism','n','The ideology of oligarch','elite ruler ideology,doctrine','C2'],
      ['oligarchist','n','A person focused on oligarch','elite ruler specialist,advocate','C2'],
      ['oligarchise','v','To make into oligarch','elite ruler,convert','C2'],
      ['oligarchize','v','To make or become oligarch','elite ruler,transform','C2'],
      ['antioligarch','adj','Opposed to oligarch','against,opposing','C2'],
      ['nonoligarch','adj','Not involving oligarch','without,lacking','C1'],
      ['preoligarch','n','Before oligarch','preceding,prior','C2'],
      ['postoligarch','n','After oligarch','following,subsequent','C2'],
      ['suboligarch','n','A subdivision of oligarch','subset,branch','C2'],
      ['multioligarch','adj','Involving many oligarchs','multiple,several','C2'],
      ['interoligarch','adj','Between oligarchs','cross,between','C2'],
      ['serf','n','A labourer bound to work on land','peasant,bondsman,slave','C1'],
      ['serfal','adj','Relating to serf','peasant-related,pertaining to','C1'],
      ['serfic','adj','Of or relating to serf','peasant-based,characteristic','C1'],
      ['serfous','adj','Full of serf','peasant-filled,abundant','C2'],
      ['serfful','adj','Full of serf','peasant-rich,abounding','C1'],
      ['serfless','adj','Without serf','lacking,without','C1'],
      ['serfism','n','The ideology of serf','peasant ideology,doctrine','C2'],
      ['serfist','n','A person focused on serf','peasant specialist,advocate','C2'],
      ['serfise','v','To make into serf','peasant,convert','C2'],
      ['serfize','v','To make or become serf','peasant,transform','C2'],
      ['antiserf','adj','Opposed to serf','against,opposing','C2'],
      ['nonserf','adj','Not involving serf','without,lacking','C1'],
      ['preserf','n','Before serf','preceding,prior','C2'],
      ['postserf','n','After serf','following,subsequent','C2'],
      ['subserf','n','A subdivision of serf','subset,branch','C2'],
      ['multiserf','adj','Involving many serfs','multiple,several','C2'],
      ['interserf','adj','Between serfs','cross,between','C2'],
      ['antiquityal','adj','Relating to antiquity','ancient times-related,pertaining to','B2'],
      ['antiquityic','adj','Of or relating to antiquity','ancient times-based,characteristic','B2'],
      ['antiquityous','adj','Full of antiquity','ancient times-filled,abundant','C1'],
      ['antiquityful','adj','Full of antiquity','ancient times-rich,abounding','B2'],
      ['antiquityless','adj','Without antiquity','lacking,without','B2'],
      ['antiquityism','n','The ideology of antiquity','ancient times ideology,doctrine','C1'],
      ['antiquityist','n','A person focused on antiquity','ancient times specialist,advocate','C1'],
      ['antiquityise','v','To make into antiquity','ancient times,convert','C1'],
      ['antiquityize','v','To make or become antiquity','ancient times,transform','C1'],
      ['antiantiquity','adj','Opposed to antiquity','against,opposing','C1'],
      ['nonantiquity','adj','Not involving antiquity','without,lacking','B2'],
      ['preantiquity','n','Before antiquity','preceding,prior','C1'],
      ['postantiquity','n','After antiquity','following,subsequent','C1'],
      ['subantiquity','n','A subdivision of antiquity','subset,branch','C1'],
      ['multiantiquity','adj','Involving many antiquitys','multiple,several','C1'],
      ['interantiquity','adj','Between antiquitys','cross,between','C1'],
    ],
    language: [
      ['conjugate','v','To give different forms of a verb','inflect,decline,modify','C1'],
      ['conjugatation','n','The act of conjugating','inflect process','C1'],
      ['conjugatment','n','The result of conjugating','inflect outcome','C1'],
      ['conjugatance','n','The state of conjugating','inflect state','C1'],
      ['conjugatence','n','The quality of conjugating','inflect quality','C1'],
      ['conjugatal','n','An act of conjugating','inflect event','C2'],
      ['conjugater','n','One who conjugates','inflect person','C1'],
      ['conjugator','n','One who conjugates','inflect agent','C1'],
      ['conjugatee','n','One who is conjugated','inflect recipient','C2'],
      ['conjugatable','adj','Capable of being conjugated','inflect,possible','C2'],
      ['conjugatible','adj','Able to be conjugated','inflect,feasible','C2'],
      ['conjugative','adj','Tending to conjugate','inflect,active','C1'],
      ['conjugating','adj','Currently conjugating','inflect,ongoing','C1'],
      ['conjugated','adj','Having been conjugated','inflect,completed','C1'],
      ['reconjugate','v','To conjugate again','inflect again,repeat','C1'],
      ['unconjugate','v','To reverse conjugating','reverse,undo','C2'],
      ['overconjugate','v','To conjugate excessively','excess,too much','C2'],
      ['underconjugate','v','To conjugate insufficiently','insufficient,inadequate','C2'],
      ['misconjugate','v','To conjugate incorrectly','wrongly,incorrectly','C2'],
      ['preconjugate','v','To conjugate beforehand','before,in advance','C2'],
      ['coconjugate','v','To conjugate together','jointly,together','C2'],
      ['reconjugatation','n','The act of conjugating again','re-inflect','C2'],
      ['overconjugatation','n','Excessive conjugating','excess inflect','C2'],
      ['transliteratation','n','The act of transliterating','transcribe process','C1'],
      ['transliteratment','n','The result of transliterating','transcribe outcome','C1'],
      ['transliteratance','n','The state of transliterating','transcribe state','C1'],
      ['transliteratence','n','The quality of transliterating','transcribe quality','C1'],
      ['transliteratal','n','An act of transliterating','transcribe event','C2'],
      ['transliterater','n','One who transliterates','transcribe person','C1'],
      ['transliterator','n','One who transliterates','transcribe agent','C1'],
      ['transliteratee','n','One who is transliterated','transcribe recipient','C2'],
      ['transliteratable','adj','Capable of being transliterated','transcribe,possible','C2'],
      ['transliteratible','adj','Able to be transliterated','transcribe,feasible','C2'],
      ['transliterative','adj','Tending to transliterate','transcribe,active','C1'],
      ['transliterating','adj','Currently transliterating','transcribe,ongoing','C1'],
      ['transliterated','adj','Having been transliterated','transcribe,completed','C1'],
      ['retransliterate','v','To transliterate again','transcribe again,repeat','C1'],
      ['untransliterate','v','To reverse transliterating','reverse,undo','C2'],
      ['overtransliterate','v','To transliterate excessively','excess,too much','C2'],
      ['undertransliterate','v','To transliterate insufficiently','insufficient,inadequate','C2'],
      ['mistransliterate','v','To transliterate incorrectly','wrongly,incorrectly','C2'],
      ['pretransliterate','v','To transliterate beforehand','before,in advance','C2'],
      ['cotransliterate','v','To transliterate together','jointly,together','C2'],
      ['retransliteratation','n','The act of transliterating again','re-transcribe','C2'],
      ['overtransliteratation','n','Excessive transliterating','excess transcribe','C2'],
      ['disambiguatation','n','The act of disambiguating','clarify process','C1'],
      ['disambiguatment','n','The result of disambiguating','clarify outcome','C1'],
      ['disambiguatance','n','The state of disambiguating','clarify state','C1'],
      ['disambiguatence','n','The quality of disambiguating','clarify quality','C1'],
      ['disambiguatal','n','An act of disambiguating','clarify event','C2'],
      ['disambiguater','n','One who disambiguates','clarify person','C1'],
      ['disambiguator','n','One who disambiguates','clarify agent','C1'],
      ['disambiguatee','n','One who is disambiguated','clarify recipient','C2'],
      ['disambiguatable','adj','Capable of being disambiguated','clarify,possible','C2'],
      ['disambiguatible','adj','Able to be disambiguated','clarify,feasible','C2'],
      ['disambiguative','adj','Tending to disambiguate','clarify,active','C1'],
      ['disambiguating','adj','Currently disambiguating','clarify,ongoing','C1'],
      ['disambiguated','adj','Having been disambiguated','clarify,completed','C1'],
      ['redisambiguate','v','To disambiguate again','clarify again,repeat','C1'],
      ['undisambiguate','v','To reverse disambiguating','reverse,undo','C2'],
      ['overdisambiguate','v','To disambiguate excessively','excess,too much','C2'],
      ['underdisambiguate','v','To disambiguate insufficiently','insufficient,inadequate','C2'],
      ['misdisambiguate','v','To disambiguate incorrectly','wrongly,incorrectly','C2'],
      ['predisambiguate','v','To disambiguate beforehand','before,in advance','C2'],
      ['codisambiguate','v','To disambiguate together','jointly,together','C2'],
      ['redisambiguatation','n','The act of disambiguating again','re-clarify','C2'],
      ['overdisambiguatation','n','Excessive disambiguating','excess clarify','C2'],
      ['bilinguality','n','The state of being bilingual','dual-language condition','C1'],
      ['inbilingual','adj','Not bilingual','not dual-language','C1'],
      ['nonbilingual','adj','Not bilingual','not dual-language','B2'],
      ['semibilingual','adj','Partially bilingual','partly dual-language','C1'],
      ['overbilingual','adj','Excessively bilingual','too dual-language','C1'],
      ['ultrabilingual','adj','Extremely bilingual','very dual-language','C1'],
      ['multilingually','adv','In a multilingual manner','polyglot way','B2'],
      ['multilingualness','n','The quality of being multilingual','polyglot quality','B2'],
      ['multilinguality','n','The state of being multilingual','polyglot condition','C1'],
      ['unmultilingual','adj','Not multilingual','not polyglot','B2'],
      ['inmultilingual','adj','Not multilingual','not polyglot','C1'],
      ['nonmultilingual','adj','Not multilingual','not polyglot','B2'],
      ['semimultilingual','adj','Partially multilingual','partly polyglot','C1'],
      ['overmultilingual','adj','Excessively multilingual','too polyglot','C1'],
      ['ultramultilingual','adj','Extremely multilingual','very polyglot','C1'],
      ['monolingually','adv','In a monolingual manner','single-language way','B2'],
      ['monolingualness','n','The quality of being monolingual','single-language quality','B2'],
      ['monolinguality','n','The state of being monolingual','single-language condition','C1'],
      ['unmonolingual','adj','Not monolingual','not single-language','B2'],
      ['inmonolingual','adj','Not monolingual','not single-language','C1'],
      ['nonmonolingual','adj','Not monolingual','not single-language','B2'],
      ['semimonolingual','adj','Partially monolingual','partly single-language','C1'],
      ['overmonolingual','adj','Excessively monolingual','too single-language','C1'],
      ['ultramonolingual','adj','Extremely monolingual','very single-language','C1'],
      ['idiomaticly','adv','In a idiomatic manner','natural way','B2'],
      ['idiomaticness','n','The quality of being idiomatic','natural quality','B2'],
      ['idiomaticity','n','The state of being idiomatic','natural condition','C1'],
      ['unidiomatic','adj','Not idiomatic','not natural','B2'],
      ['inidiomatic','adj','Not idiomatic','not natural','C1'],
      ['nonidiomatic','adj','Not idiomatic','not natural','B2'],
      ['semiidiomatic','adj','Partially idiomatic','partly natural','C1'],
      ['overidiomatic','adj','Excessively idiomatic','too natural','C1'],
      ['ultraidiomatic','adj','Extremely idiomatic','very natural','C1'],
      ['phonetic','adj','Relating to speech sounds','sound-based,pronunciation-based','B2'],
      ['phoneticly','adv','In a phonetic manner','sound-based way','B2'],
      ['phoneticness','n','The quality of being phonetic','sound-based quality','B2'],
      ['phoneticity','n','The state of being phonetic','sound-based condition','C1'],
      ['unphonetic','adj','Not phonetic','not sound-based','B2'],
      ['inphonetic','adj','Not phonetic','not sound-based','C1'],
      ['nonphonetic','adj','Not phonetic','not sound-based','B2'],
      ['semiphonetic','adj','Partially phonetic','partly sound-based','C1'],
      ['overphonetic','adj','Excessively phonetic','too sound-based','C1'],
      ['ultraphonetic','adj','Extremely phonetic','very sound-based','C1'],
      ['syntacticly','adv','In a syntactic manner','grammatical way','C1'],
      ['syntacticness','n','The quality of being syntactic','grammatical quality','C1'],
      ['syntacticity','n','The state of being syntactic','grammatical condition','C2'],
      ['unsyntactic','adj','Not syntactic','not grammatical','C1'],
      ['insyntactic','adj','Not syntactic','not grammatical','C2'],
      ['nonsyntactic','adj','Not syntactic','not grammatical','C1'],
      ['semisyntactic','adj','Partially syntactic','partly grammatical','C2'],
      ['oversyntactic','adj','Excessively syntactic','too grammatical','C2'],
      ['ultrasyntactic','adj','Extremely syntactic','very grammatical','C2'],
      ['lexically','adv','In a lexical manner','word-based way','C1'],
      ['lexicalness','n','The quality of being lexical','word-based quality','C1'],
      ['lexicality','n','The state of being lexical','word-based condition','C2'],
      ['unlexical','adj','Not lexical','not word-based','C1'],
      ['inlexical','adj','Not lexical','not word-based','C2'],
      ['nonlexical','adj','Not lexical','not word-based','C1'],
      ['semilexical','adj','Partially lexical','partly word-based','C2'],
      ['overlexical','adj','Excessively lexical','too word-based','C2'],
      ['ultralexical','adj','Extremely lexical','very word-based','C2'],
      ['morphological','adj','Relating to word forms','word-form,structural','C1'],
      ['morphologically','adv','In a morphological manner','word-form way','C1'],
      ['morphologicalness','n','The quality of being morphological','word-form quality','C1'],
      ['morphologicality','n','The state of being morphological','word-form condition','C2'],
      ['unmorphological','adj','Not morphological','not word-form','C1'],
      ['inmorphological','adj','Not morphological','not word-form','C2'],
      ['nonmorphological','adj','Not morphological','not word-form','C1'],
      ['semimorphological','adj','Partially morphological','partly word-form','C2'],
      ['overmorphological','adj','Excessively morphological','too word-form','C2'],
      ['ultramorphological','adj','Extremely morphological','very word-form','C2'],
      ['etymologyic','adj','Of or relating to etymology','word history-based,characteristic','C1'],
      ['etymologyous','adj','Full of etymology','word history-filled,abundant','C2'],
      ['etymologyful','adj','Full of etymology','word history-rich,abounding','C1'],
      ['etymologyless','adj','Without etymology','lacking,without','C1'],
      ['etymologyism','n','The ideology of etymology','word history ideology,doctrine','C2'],
      ['etymologyist','n','A person focused on etymology','word history specialist,advocate','C2'],
      ['etymologyise','v','To make into etymology','word history,convert','C2'],
      ['etymologyize','v','To make or become etymology','word history,transform','C2'],
      ['antietymology','adj','Opposed to etymology','against,opposing','C2'],
      ['nonetymology','adj','Not involving etymology','without,lacking','C1'],
      ['preetymology','n','Before etymology','preceding,prior','C2'],
      ['postetymology','n','After etymology','following,subsequent','C2'],
      ['subetymology','n','A subdivision of etymology','subset,branch','C2'],
      ['multietymology','adj','Involving many etymologys','multiple,several','C2'],
      ['interetymology','adj','Between etymologys','cross,between','C2'],
      ['linguisticsal','adj','Relating to linguistics','language science-related,pertaining to','B2'],
      ['linguisticsic','adj','Of or relating to linguistics','language science-based,characteristic','B2'],
      ['linguisticsous','adj','Full of linguistics','language science-filled,abundant','C1'],
      ['linguisticsful','adj','Full of linguistics','language science-rich,abounding','B2'],
      ['linguisticsless','adj','Without linguistics','lacking,without','B2'],
      ['linguisticsism','n','The ideology of linguistics','language science ideology,doctrine','C1'],
      ['linguisticsist','n','A person focused on linguistics','language science specialist,advocate','C1'],
      ['linguisticsise','v','To make into linguistics','language science,convert','C1'],
      ['linguisticsize','v','To make or become linguistics','language science,transform','C1'],
      ['antilinguistics','adj','Opposed to linguistics','against,opposing','C1'],
      ['nonlinguistics','adj','Not involving linguistics','without,lacking','B2'],
      ['prelinguistics','n','Before linguistics','preceding,prior','C1'],
      ['postlinguistics','n','After linguistics','following,subsequent','C1'],
      ['sublinguistics','n','A subdivision of linguistics','subset,branch','C1'],
      ['multilinguistics','adj','Involving many linguisticss','multiple,several','C1'],
      ['interlinguistics','adj','Between linguisticss','cross,between','C1'],
      ['dialectous','adj','Full of dialect','variety-filled,abundant','C1'],
      ['dialectful','adj','Full of dialect','variety-rich,abounding','B2'],
      ['dialectless','adj','Without dialect','lacking,without','B2'],
      ['dialectism','n','The ideology of dialect','variety ideology,doctrine','C1'],
      ['dialectist','n','A person focused on dialect','variety specialist,advocate','C1'],
      ['dialectise','v','To make into dialect','variety,convert','C1'],
      ['dialectize','v','To make or become dialect','variety,transform','C1'],
      ['antidialect','adj','Opposed to dialect','against,opposing','C1'],
      ['nondialect','adj','Not involving dialect','without,lacking','B2'],
      ['predialect','n','Before dialect','preceding,prior','C1'],
      ['postdialect','n','After dialect','following,subsequent','C1'],
      ['subdialect','n','A subdivision of dialect','subset,branch','C1'],
      ['multidialect','adj','Involving many dialects','multiple,several','C1'],
      ['interdialect','adj','Between dialects','cross,between','C1'],
      ['pidginic','adj','Of or relating to pidgin','trade language-based,characteristic','C1'],
      ['pidginous','adj','Full of pidgin','trade language-filled,abundant','C2'],
      ['pidginful','adj','Full of pidgin','trade language-rich,abounding','C1'],
      ['pidginless','adj','Without pidgin','lacking,without','C1'],
      ['pidginism','n','The ideology of pidgin','trade language ideology,doctrine','C2'],
      ['pidginist','n','A person focused on pidgin','trade language specialist,advocate','C2'],
      ['pidginise','v','To make into pidgin','trade language,convert','C2'],
      ['pidginize','v','To make or become pidgin','trade language,transform','C2'],
      ['antipidgin','adj','Opposed to pidgin','against,opposing','C2'],
      ['nonpidgin','adj','Not involving pidgin','without,lacking','C1'],
      ['prepidgin','n','Before pidgin','preceding,prior','C2'],
      ['postpidgin','n','After pidgin','following,subsequent','C2'],
      ['subpidgin','n','A subdivision of pidgin','subset,branch','C2'],
      ['multipidgin','adj','Involving many pidgins','multiple,several','C2'],
    ],
  },
  collocations: {}
};
