// Auto-generated vocab boost group 77
module.exports = {
  vocab: {
    housing: [
      ['preinsulate','v','To insulate beforehand','before,in advance','C1'],
      ['coinsulate','v','To insulate together','jointly,together','C1'],
      ['reinsulatation','n','The act of insulating again','re-protect','C1'],
      ['overinsulatation','n','Excessive insulating','excess protect','C1'],
      ['sublet','v','To rent property to another person','re-rent,sublease,underlet','B2'],
      ['subletation','n','The act of subleting','re-rent process','B2'],
      ['subletment','n','The result of subleting','re-rent outcome','B2'],
      ['subletance','n','The state of subleting','re-rent state','B2'],
      ['subletence','n','The quality of subleting','re-rent quality','B2'],
      ['subletal','n','An act of subleting','re-rent event','C1'],
      ['subleter','n','One who sublets','re-rent person','B2'],
      ['subletor','n','One who sublets','re-rent agent','B2'],
      ['subletee','n','One who is subletd','re-rent recipient','C1'],
      ['subletable','adj','Capable of being subletd','re-rent,possible','C1'],
      ['subletible','adj','Able to be subletd','re-rent,feasible','C1'],
      ['subletive','adj','Tending to sublet','re-rent,active','B2'],
      ['subleting','adj','Currently subleting','re-rent,ongoing','B2'],
      ['subleted','adj','Having been subletd','re-rent,completed','B2'],
      ['resublet','v','To sublet again','re-rent again,repeat','B2'],
      ['unsublet','v','To reverse subleting','reverse,undo','C1'],
      ['oversublet','v','To sublet excessively','excess,too much','C1'],
      ['undersublet','v','To sublet insufficiently','insufficient,inadequate','C1'],
      ['missublet','v','To sublet incorrectly','wrongly,incorrectly','C1'],
      ['presublet','v','To sublet beforehand','before,in advance','C1'],
      ['cosublet','v','To sublet together','jointly,together','C1'],
      ['resubletation','n','The act of subleting again','re-re-rent','C1'],
      ['oversubletation','n','Excessive subleting','excess re-rent','C1'],
      ['gentrifyment','n','The result of gentrifying','upgrade outcome','C1'],
      ['gentrifyance','n','The state of gentrifying','upgrade state','C1'],
      ['gentrifyence','n','The quality of gentrifying','upgrade quality','C1'],
      ['gentrifyal','n','An act of gentrifying','upgrade event','C2'],
      ['gentrifyor','n','One who gentrifys','upgrade agent','C1'],
      ['gentrifyee','n','One who is gentrifyd','upgrade recipient','C2'],
      ['gentrifyible','adj','Able to be gentrifyd','upgrade,feasible','C2'],
      ['gentrifyive','adj','Tending to gentrify','upgrade,active','C1'],
      ['gentrifyed','adj','Having been gentrifyd','upgrade,completed','C1'],
      ['regentrify','v','To gentrify again','upgrade again,repeat','C1'],
      ['ungentrify','v','To reverse gentrifying','reverse,undo','C2'],
      ['overgentrify','v','To gentrify excessively','excess,too much','C2'],
      ['undergentrify','v','To gentrify insufficiently','insufficient,inadequate','C2'],
      ['misgentrify','v','To gentrify incorrectly','wrongly,incorrectly','C2'],
      ['pregentrify','v','To gentrify beforehand','before,in advance','C2'],
      ['cogentrify','v','To gentrify together','jointly,together','C2'],
      ['regentrifyation','n','The act of gentrifying again','re-upgrade','C2'],
      ['overgentrifyation','n','Excessive gentrifying','excess upgrade','C2'],
      ['furnishation','n','The act of furnishing','equip process','B1'],
      ['furnishment','n','The result of furnishing','equip outcome','B1'],
      ['furnishance','n','The state of furnishing','equip state','B1'],
      ['furnishence','n','The quality of furnishing','equip quality','B1'],
      ['furnishal','n','An act of furnishing','equip event','B2'],
      ['furnisher','n','One who furnishs','equip person','B1'],
      ['furnishor','n','One who furnishs','equip agent','B1'],
      ['furnishee','n','One who is furnishd','equip recipient','B2'],
      ['furnishable','adj','Capable of being furnishd','equip,possible','B2'],
      ['furnishible','adj','Able to be furnishd','equip,feasible','B2'],
      ['furnishive','adj','Tending to furnish','equip,active','B1'],
      ['furnishing','adj','Currently furnishing','equip,ongoing','B1'],
      ['refurnish','v','To furnish again','equip again,repeat','B1'],
      ['unfurnish','v','To reverse furnishing','reverse,undo','B2'],
      ['overfurnish','v','To furnish excessively','excess,too much','B2'],
      ['underfurnish','v','To furnish insufficiently','insufficient,inadequate','B2'],
      ['misfurnish','v','To furnish incorrectly','wrongly,incorrectly','B2'],
      ['prefurnish','v','To furnish beforehand','before,in advance','B2'],
      ['cofurnish','v','To furnish together','jointly,together','B2'],
      ['refurnishation','n','The act of furnishing again','re-equip','B2'],
      ['overfurnishation','n','Excessive furnishing','excess equip','B2'],
      ['mortgageic','adj','Of or relating to mortgage','home loan-based,characteristic','B2'],
      ['mortgageous','adj','Full of mortgage','home loan-filled,abundant','C1'],
      ['mortgageful','adj','Full of mortgage','home loan-rich,abounding','B2'],
      ['mortgageless','adj','Without mortgage','lacking,without','B2'],
      ['mortgageism','n','The ideology of mortgage','home loan ideology,doctrine','C1'],
      ['mortgageist','n','A person focused on mortgage','home loan specialist,advocate','C1'],
      ['mortgageise','v','To make into mortgage','home loan,convert','C1'],
      ['mortgageize','v','To make or become mortgage','home loan,transform','C1'],
      ['antimortgage','adj','Opposed to mortgage','against,opposing','C1'],
      ['nonmortgage','adj','Not involving mortgage','without,lacking','B2'],
      ['premortgage','n','Before mortgage','preceding,prior','C1'],
      ['postmortgage','n','After mortgage','following,subsequent','C1'],
      ['submortgage','n','A subdivision of mortgage','subset,branch','C1'],
      ['multimortgage','adj','Involving many mortgages','multiple,several','C1'],
      ['intermortgage','adj','Between mortgages','cross,between','C1'],
      ['tenancyal','adj','Relating to tenancy','lease-related,pertaining to','B2'],
      ['tenancyic','adj','Of or relating to tenancy','lease-based,characteristic','B2'],
      ['tenancyous','adj','Full of tenancy','lease-filled,abundant','C1'],
      ['tenancyful','adj','Full of tenancy','lease-rich,abounding','B2'],
      ['tenancyless','adj','Without tenancy','lacking,without','B2'],
      ['tenancyism','n','The ideology of tenancy','lease ideology,doctrine','C1'],
      ['tenancyist','n','A person focused on tenancy','lease specialist,advocate','C1'],
      ['tenancyise','v','To make into tenancy','lease,convert','C1'],
      ['tenancyize','v','To make or become tenancy','lease,transform','C1'],
      ['antitenancy','adj','Opposed to tenancy','against,opposing','C1'],
      ['nontenancy','adj','Not involving tenancy','without,lacking','B2'],
      ['pretenancy','n','Before tenancy','preceding,prior','C1'],
      ['posttenancy','n','After tenancy','following,subsequent','C1'],
      ['subtenancy','n','A subdivision of tenancy','subset,branch','C1'],
      ['multitenancy','adj','Involving many tenancys','multiple,several','C1'],
      ['intertenancy','adj','Between tenancys','cross,between','C1'],
      ['refurbishmental','adj','Relating to refurbishment','renovation-related,pertaining to','B2'],
      ['refurbishmentic','adj','Of or relating to refurbishment','renovation-based,characteristic','B2'],
      ['refurbishmentous','adj','Full of refurbishment','renovation-filled,abundant','C1'],
      ['refurbishmentful','adj','Full of refurbishment','renovation-rich,abounding','B2'],
      ['refurbishmentless','adj','Without refurbishment','lacking,without','B2'],
      ['refurbishmentism','n','The ideology of refurbishment','renovation ideology,doctrine','C1'],
      ['refurbishmentist','n','A person focused on refurbishment','renovation specialist,advocate','C1'],
      ['refurbishmentise','v','To make into refurbishment','renovation,convert','C1'],
      ['refurbishmentize','v','To make or become refurbishment','renovation,transform','C1'],
      ['antirefurbishment','adj','Opposed to refurbishment','against,opposing','C1'],
      ['nonrefurbishment','adj','Not involving refurbishment','without,lacking','B2'],
      ['prerefurbishment','n','Before refurbishment','preceding,prior','C1'],
      ['postrefurbishment','n','After refurbishment','following,subsequent','C1'],
      ['subrefurbishment','n','A subdivision of refurbishment','subset,branch','C1'],
      ['multirefurbishment','adj','Involving many refurbishments','multiple,several','C1'],
      ['interrefurbishment','adj','Between refurbishments','cross,between','C1'],
      ['suburbic','adj','Of or relating to suburb','outskirts-based,characteristic','B1'],
      ['suburbous','adj','Full of suburb','outskirts-filled,abundant','B2'],
      ['suburbful','adj','Full of suburb','outskirts-rich,abounding','B1'],
      ['suburbless','adj','Without suburb','lacking,without','B1'],
      ['suburbism','n','The ideology of suburb','outskirts ideology,doctrine','B2'],
      ['suburbist','n','A person focused on suburb','outskirts specialist,advocate','B2'],
      ['suburbise','v','To make into suburb','outskirts,convert','B2'],
      ['suburbize','v','To make or become suburb','outskirts,transform','B2'],
      ['antisuburb','adj','Opposed to suburb','against,opposing','B2'],
      ['nonsuburb','adj','Not involving suburb','without,lacking','B1'],
      ['presuburb','n','Before suburb','preceding,prior','B2'],
      ['postsuburb','n','After suburb','following,subsequent','B2'],
      ['subsuburb','n','A subdivision of suburb','subset,branch','B2'],
      ['multisuburb','adj','Involving many suburbs','multiple,several','B2'],
      ['intersuburb','adj','Between suburbs','cross,between','B2'],
      ['infrastructureic','adj','Of or relating to infrastructure','facilities-based,characteristic','B2'],
      ['infrastructureous','adj','Full of infrastructure','facilities-filled,abundant','C1'],
      ['infrastructureful','adj','Full of infrastructure','facilities-rich,abounding','B2'],
      ['infrastructureless','adj','Without infrastructure','lacking,without','B2'],
      ['infrastructureism','n','The ideology of infrastructure','facilities ideology,doctrine','C1'],
      ['infrastructureist','n','A person focused on infrastructure','facilities specialist,advocate','C1'],
      ['infrastructureise','v','To make into infrastructure','facilities,convert','C1'],
      ['infrastructureize','v','To make or become infrastructure','facilities,transform','C1'],
      ['antiinfrastructure','adj','Opposed to infrastructure','against,opposing','C1'],
      ['noninfrastructure','adj','Not involving infrastructure','without,lacking','B2'],
      ['preinfrastructure','n','Before infrastructure','preceding,prior','C1'],
      ['postinfrastructure','n','After infrastructure','following,subsequent','C1'],
      ['subinfrastructure','n','A subdivision of infrastructure','subset,branch','C1'],
      ['multiinfrastructure','adj','Involving many infrastructures','multiple,several','C1'],
      ['interinfrastructure','adj','Between infrastructures','cross,between','C1'],
      ['amenityal','adj','Relating to amenity','facility-related,pertaining to','B2'],
      ['amenityic','adj','Of or relating to amenity','facility-based,characteristic','B2'],
      ['amenityous','adj','Full of amenity','facility-filled,abundant','C1'],
      ['amenityful','adj','Full of amenity','facility-rich,abounding','B2'],
      ['amenityless','adj','Without amenity','lacking,without','B2'],
      ['amenityism','n','The ideology of amenity','facility ideology,doctrine','C1'],
      ['amenityist','n','A person focused on amenity','facility specialist,advocate','C1'],
      ['amenityise','v','To make into amenity','facility,convert','C1'],
      ['amenityize','v','To make or become amenity','facility,transform','C1'],
      ['antiamenity','adj','Opposed to amenity','against,opposing','C1'],
      ['nonamenity','adj','Not involving amenity','without,lacking','B2'],
      ['preamenity','n','Before amenity','preceding,prior','C1'],
      ['postamenity','n','After amenity','following,subsequent','C1'],
      ['subamenity','n','A subdivision of amenity','subset,branch','C1'],
      ['multiamenity','adj','Involving many amenitys','multiple,several','C1'],
      ['interamenity','adj','Between amenitys','cross,between','C1'],
      ['zoningic','adj','Of or relating to zoning','land use planning-based,characteristic','C1'],
      ['zoningous','adj','Full of zoning','land use planning-filled,abundant','C2'],
      ['zoningful','adj','Full of zoning','land use planning-rich,abounding','C1'],
      ['zoningless','adj','Without zoning','lacking,without','C1'],
      ['zoningism','n','The ideology of zoning','land use planning ideology,doctrine','C2'],
      ['zoningist','n','A person focused on zoning','land use planning specialist,advocate','C2'],
      ['zoningise','v','To make into zoning','land use planning,convert','C2'],
      ['zoningize','v','To make or become zoning','land use planning,transform','C2'],
      ['antizoning','adj','Opposed to zoning','against,opposing','C2'],
      ['nonzoning','adj','Not involving zoning','without,lacking','C1'],
      ['prezoning','n','Before zoning','preceding,prior','C2'],
      ['postzoning','n','After zoning','following,subsequent','C2'],
      ['subzoning','n','A subdivision of zoning','subset,branch','C2'],
      ['multizoning','adj','Involving many zonings','multiple,several','C2'],
      ['interzoning','adj','Between zonings','cross,between','C2'],
      ['prefabricatation','n','The act of prefabricating','pre-build process','C1'],
      ['prefabricatment','n','The result of prefabricating','pre-build outcome','C1'],
      ['prefabricatance','n','The state of prefabricating','pre-build state','C1'],
      ['prefabricatence','n','The quality of prefabricating','pre-build quality','C1'],
      ['prefabricatal','n','An act of prefabricating','pre-build event','C2'],
      ['prefabricater','n','One who prefabricates','pre-build person','C1'],
      ['prefabricator','n','One who prefabricates','pre-build agent','C1'],
      ['prefabricatee','n','One who is prefabricated','pre-build recipient','C2'],
      ['prefabricatable','adj','Capable of being prefabricated','pre-build,possible','C2'],
      ['prefabricatible','adj','Able to be prefabricated','pre-build,feasible','C2'],
      ['prefabricative','adj','Tending to prefabricate','pre-build,active','C1'],
      ['prefabricating','adj','Currently prefabricating','pre-build,ongoing','C1'],
      ['reprefabricate','v','To prefabricate again','pre-build again,repeat','C1'],
      ['unprefabricate','v','To reverse prefabricating','reverse,undo','C2'],
      ['overprefabricate','v','To prefabricate excessively','excess,too much','C2'],
      ['underprefabricate','v','To prefabricate insufficiently','insufficient,inadequate','C2'],
      ['misprefabricate','v','To prefabricate incorrectly','wrongly,incorrectly','C2'],
      ['preprefabricate','v','To prefabricate beforehand','before,in advance','C2'],
      ['coprefabricate','v','To prefabricate together','jointly,together','C2'],
      ['reprefabricatation','n','The act of prefabricating again','re-pre-build','C2'],
      ['overprefabricatation','n','Excessive prefabricating','excess pre-build','C2'],
      ['dilapidatedly','adv','In a dilapidated manner','rundown way','B2'],
      ['dilapidatedness','n','The quality of being dilapidated','rundown quality','B2'],
      ['dilapidatedity','n','The state of being dilapidated','rundown condition','C1'],
      ['undilapidated','adj','Not dilapidated','not rundown','B2'],
      ['indilapidated','adj','Not dilapidated','not rundown','C1'],
      ['nondilapidated','adj','Not dilapidated','not rundown','B2'],
      ['semidilapidated','adj','Partially dilapidated','partly rundown','C1'],
      ['overdilapidated','adj','Excessively dilapidated','too rundown','C1'],
      ['ultradilapidated','adj','Extremely dilapidated','very rundown','C1'],
      ['inhabitable','adj','Suitable for living in','liveable,habitable,occupiable','B2'],
      ['inhabitablely','adv','In a inhabitable manner','liveable way','B2'],
      ['inhabitableness','n','The quality of being inhabitable','liveable quality','B2'],
      ['inhabitableity','n','The state of being inhabitable','liveable condition','C1'],
      ['ininhabitable','adj','Not inhabitable','not liveable','C1'],
      ['noninhabitable','adj','Not inhabitable','not liveable','B2'],
      ['semiinhabitable','adj','Partially inhabitable','partly liveable','C1'],
      ['overinhabitable','adj','Excessively inhabitable','too liveable','C1'],
      ['ultrainhabitable','adj','Extremely inhabitable','very liveable','C1'],
      ['derelictly','adv','In a derelict manner','abandoned way','C1'],
      ['derelictness','n','The quality of being derelict','abandoned quality','C1'],
      ['derelictity','n','The state of being derelict','abandoned condition','C2'],
      ['underelict','adj','Not derelict','not abandoned','C1'],
      ['inderelict','adj','Not derelict','not abandoned','C2'],
      ['nonderelict','adj','Not derelict','not abandoned','C1'],
      ['semiderelict','adj','Partially derelict','partly abandoned','C2'],
      ['overderelict','adj','Excessively derelict','too abandoned','C2'],
      ['ultraderelict','adj','Extremely derelict','very abandoned','C2'],
      ['residentially','adv','In a residential manner','living way','B2'],
      ['residentialness','n','The quality of being residential','living quality','B2'],
      ['residentiality','n','The state of being residential','living condition','C1'],
      ['unresidential','adj','Not residential','not living','B2'],
      ['inresidential','adj','Not residential','not living','C1'],
      ['nonresidential','adj','Not residential','not living','B2'],
      ['semiresidential','adj','Partially residential','partly living','C1'],
      ['overresidential','adj','Excessively residential','too living','C1'],
      ['ultraresidential','adj','Extremely residential','very living','C1'],
      ['affordableity','n','The state of being affordable','inexpensive condition','B2'],
      ['inaffordable','adj','Not affordable','not inexpensive','B2'],
      ['nonaffordable','adj','Not affordable','not inexpensive','B1'],
      ['semiaffordable','adj','Partially affordable','partly inexpensive','B2'],
      ['overaffordable','adj','Excessively affordable','too inexpensive','B2'],
      ['ultraaffordable','adj','Extremely affordable','very inexpensive','B2'],
      ['communally','adv','In a communal manner','shared way','B2'],
      ['communalness','n','The quality of being communal','shared quality','B2'],
      ['communality','n','The state of being communal','shared condition','C1'],
      ['uncommunal','adj','Not communal','not shared','B2'],
      ['incommunal','adj','Not communal','not shared','C1'],
      ['noncommunal','adj','Not communal','not shared','B2'],
      ['semicommunal','adj','Partially communal','partly shared','C1'],
      ['overcommunal','adj','Excessively communal','too shared','C1'],
      ['ultracommunal','adj','Extremely communal','very shared','C1'],
      ['detachedity','n','The state of being detached','separate condition','B2'],
      ['indetached','adj','Not detached','not separate','B2'],
      ['nondetached','adj','Not detached','not separate','B1'],
      ['semidetached','adj','Partially detached','partly separate','B2'],
    ],
  },
  collocations: {}
};
