// Auto-generated vocab boost group 47
module.exports = {
  vocab: {
    business: [
      ['subdividend','n','A subdivision of dividend','subset,branch','C1'],
      ['multidividend','adj','Involving many dividends','multiple,several','C1'],
      ['interdividend','adj','Between dividends','cross,between','C1'],
      ['equityic','adj','Of or relating to equity','shares-based,characteristic','B2'],
      ['equityous','adj','Full of equity','shares-filled,abundant','C1'],
      ['equityful','adj','Full of equity','shares-rich,abounding','B2'],
      ['equityless','adj','Without equity','lacking,without','B2'],
      ['equityism','n','The ideology of equity','shares ideology,doctrine','C1'],
      ['equityist','n','A person focused on equity','shares specialist,advocate','C1'],
      ['equityise','v','To make into equity','shares,convert','C1'],
      ['equityize','v','To make or become equity','shares,transform','C1'],
      ['antiequity','adj','Opposed to equity','against,opposing','C1'],
      ['nonequity','adj','Not involving equity','without,lacking','B2'],
      ['preequity','n','Before equity','preceding,prior','C1'],
      ['postequity','n','After equity','following,subsequent','C1'],
      ['subequity','n','A subdivision of equity','subset,branch','C1'],
      ['multiequity','adj','Involving many equitys','multiple,several','C1'],
      ['interequity','adj','Between equitys','cross,between','C1'],
      ['liabilityal','adj','Relating to liability','debt-related,pertaining to','B2'],
      ['liabilityic','adj','Of or relating to liability','debt-based,characteristic','B2'],
      ['liabilityous','adj','Full of liability','debt-filled,abundant','C1'],
      ['liabilityful','adj','Full of liability','debt-rich,abounding','B2'],
      ['liabilityless','adj','Without liability','lacking,without','B2'],
      ['liabilityism','n','The ideology of liability','debt ideology,doctrine','C1'],
      ['liabilityist','n','A person focused on liability','debt specialist,advocate','C1'],
      ['liabilityise','v','To make into liability','debt,convert','C1'],
      ['liabilityize','v','To make or become liability','debt,transform','C1'],
      ['antiliability','adj','Opposed to liability','against,opposing','C1'],
      ['nonliability','adj','Not involving liability','without,lacking','B2'],
      ['preliability','n','Before liability','preceding,prior','C1'],
      ['postliability','n','After liability','following,subsequent','C1'],
      ['subliability','n','A subdivision of liability','subset,branch','C1'],
      ['multiliability','adj','Involving many liabilitys','multiple,several','C1'],
      ['interliability','adj','Between liabilitys','cross,between','C1'],
      ['revenueic','adj','Of or relating to revenue','income-based,characteristic','B2'],
      ['revenueous','adj','Full of revenue','income-filled,abundant','C1'],
      ['revenueful','adj','Full of revenue','income-rich,abounding','B2'],
      ['revenueless','adj','Without revenue','lacking,without','B2'],
      ['revenueism','n','The ideology of revenue','income ideology,doctrine','C1'],
      ['revenueist','n','A person focused on revenue','income specialist,advocate','C1'],
      ['revenueise','v','To make into revenue','income,convert','C1'],
      ['revenueize','v','To make or become revenue','income,transform','C1'],
      ['antirevenue','adj','Opposed to revenue','against,opposing','C1'],
      ['nonrevenue','adj','Not involving revenue','without,lacking','B2'],
      ['prerevenue','n','Before revenue','preceding,prior','C1'],
      ['postrevenue','n','After revenue','following,subsequent','C1'],
      ['subrevenue','n','A subdivision of revenue','subset,branch','C1'],
      ['multirevenue','adj','Involving many revenues','multiple,several','C1'],
      ['interrevenue','adj','Between revenues','cross,between','C1'],
      ['overheads','n','Ongoing costs of running a business','expenses,running costs,fixed costs','B2'],
      ['overheadsal','adj','Relating to overheads','expenses-related,pertaining to','B2'],
      ['overheadsic','adj','Of or relating to overheads','expenses-based,characteristic','B2'],
      ['overheadsous','adj','Full of overheads','expenses-filled,abundant','C1'],
      ['overheadsful','adj','Full of overheads','expenses-rich,abounding','B2'],
      ['overheadsless','adj','Without overheads','lacking,without','B2'],
      ['overheadsism','n','The ideology of overheads','expenses ideology,doctrine','C1'],
      ['overheadsist','n','A person focused on overheads','expenses specialist,advocate','C1'],
      ['overheadsise','v','To make into overheads','expenses,convert','C1'],
      ['overheadsize','v','To make or become overheads','expenses,transform','C1'],
      ['antioverheads','adj','Opposed to overheads','against,opposing','C1'],
      ['nonoverheads','adj','Not involving overheads','without,lacking','B2'],
      ['preoverheads','n','Before overheads','preceding,prior','C1'],
      ['postoverheads','n','After overheads','following,subsequent','C1'],
      ['suboverheads','n','A subdivision of overheads','subset,branch','C1'],
      ['multioverheads','adj','Involving many overheadss','multiple,several','C1'],
      ['interoverheads','adj','Between overheadss','cross,between','C1'],
      ['turnoveric','adj','Of or relating to turnover','sales-based,characteristic','B2'],
      ['turnoverous','adj','Full of turnover','sales-filled,abundant','C1'],
      ['turnoverful','adj','Full of turnover','sales-rich,abounding','B2'],
      ['turnoverless','adj','Without turnover','lacking,without','B2'],
      ['turnoverism','n','The ideology of turnover','sales ideology,doctrine','C1'],
      ['turnoverist','n','A person focused on turnover','sales specialist,advocate','C1'],
      ['turnoverise','v','To make into turnover','sales,convert','C1'],
      ['turnoverize','v','To make or become turnover','sales,transform','C1'],
      ['antiturnover','adj','Opposed to turnover','against,opposing','C1'],
      ['nonturnover','adj','Not involving turnover','without,lacking','B2'],
      ['preturnover','n','Before turnover','preceding,prior','C1'],
      ['postturnover','n','After turnover','following,subsequent','C1'],
      ['subturnover','n','A subdivision of turnover','subset,branch','C1'],
      ['multiturnover','adj','Involving many turnovers','multiple,several','C1'],
      ['interturnover','adj','Between turnovers','cross,between','C1'],
      ['insolvency','n','The state of being unable to pay debts','bankruptcy,failure,ruin','C1'],
      ['insolvencyal','adj','Relating to insolvency','bankruptcy-related,pertaining to','C1'],
      ['insolvencyic','adj','Of or relating to insolvency','bankruptcy-based,characteristic','C1'],
      ['insolvencyous','adj','Full of insolvency','bankruptcy-filled,abundant','C2'],
      ['insolvencyful','adj','Full of insolvency','bankruptcy-rich,abounding','C1'],
      ['insolvencyless','adj','Without insolvency','lacking,without','C1'],
      ['insolvencyism','n','The ideology of insolvency','bankruptcy ideology,doctrine','C2'],
      ['insolvencyist','n','A person focused on insolvency','bankruptcy specialist,advocate','C2'],
      ['insolvencyise','v','To make into insolvency','bankruptcy,convert','C2'],
      ['insolvencyize','v','To make or become insolvency','bankruptcy,transform','C2'],
      ['antiinsolvency','adj','Opposed to insolvency','against,opposing','C2'],
      ['noninsolvency','adj','Not involving insolvency','without,lacking','C1'],
      ['preinsolvency','n','Before insolvency','preceding,prior','C2'],
      ['postinsolvency','n','After insolvency','following,subsequent','C2'],
      ['subinsolvency','n','A subdivision of insolvency','subset,branch','C2'],
      ['multiinsolvency','adj','Involving many insolvencys','multiple,several','C2'],
      ['interinsolvency','adj','Between insolvencys','cross,between','C2'],
      ['acquisitionic','adj','Of or relating to acquisition','purchase-based,characteristic','B2'],
      ['acquisitionous','adj','Full of acquisition','purchase-filled,abundant','C1'],
      ['acquisitionful','adj','Full of acquisition','purchase-rich,abounding','B2'],
      ['acquisitionless','adj','Without acquisition','lacking,without','B2'],
      ['acquisitionism','n','The ideology of acquisition','purchase ideology,doctrine','C1'],
      ['acquisitionist','n','A person focused on acquisition','purchase specialist,advocate','C1'],
      ['acquisitionise','v','To make into acquisition','purchase,convert','C1'],
      ['acquisitionize','v','To make or become acquisition','purchase,transform','C1'],
      ['antiacquisition','adj','Opposed to acquisition','against,opposing','C1'],
      ['nonacquisition','adj','Not involving acquisition','without,lacking','B2'],
      ['preacquisition','n','Before acquisition','preceding,prior','C1'],
      ['postacquisition','n','After acquisition','following,subsequent','C1'],
      ['subacquisition','n','A subdivision of acquisition','subset,branch','C1'],
      ['multiacquisition','adj','Involving many acquisitions','multiple,several','C1'],
      ['interacquisition','adj','Between acquisitions','cross,between','C1'],
      ['portfolioal','adj','Relating to portfolio','collection-related,pertaining to','B2'],
      ['portfolioic','adj','Of or relating to portfolio','collection-based,characteristic','B2'],
      ['portfolioous','adj','Full of portfolio','collection-filled,abundant','C1'],
      ['portfolioful','adj','Full of portfolio','collection-rich,abounding','B2'],
      ['portfolioless','adj','Without portfolio','lacking,without','B2'],
      ['portfolioism','n','The ideology of portfolio','collection ideology,doctrine','C1'],
      ['portfolioist','n','A person focused on portfolio','collection specialist,advocate','C1'],
      ['portfolioise','v','To make into portfolio','collection,convert','C1'],
      ['portfolioize','v','To make or become portfolio','collection,transform','C1'],
      ['antiportfolio','adj','Opposed to portfolio','against,opposing','C1'],
      ['nonportfolio','adj','Not involving portfolio','without,lacking','B2'],
      ['preportfolio','n','Before portfolio','preceding,prior','C1'],
      ['postportfolio','n','After portfolio','following,subsequent','C1'],
      ['subportfolio','n','A subdivision of portfolio','subset,branch','C1'],
      ['multiportfolio','adj','Involving many portfolios','multiple,several','C1'],
      ['interportfolio','adj','Between portfolios','cross,between','C1'],
      ['joint venture','n','A business arrangement between partners','partnership,collaboration,alliance','B2'],
      ['joint ventureal','adj','Relating to joint venture','partnership-related,pertaining to','B2'],
      ['joint ventureic','adj','Of or relating to joint venture','partnership-based,characteristic','B2'],
      ['joint ventureous','adj','Full of joint venture','partnership-filled,abundant','C1'],
      ['joint ventureful','adj','Full of joint venture','partnership-rich,abounding','B2'],
      ['joint ventureless','adj','Without joint venture','lacking,without','B2'],
      ['joint ventureism','n','The ideology of joint venture','partnership ideology,doctrine','C1'],
      ['joint ventureist','n','A person focused on joint venture','partnership specialist,advocate','C1'],
      ['joint ventureise','v','To make into joint venture','partnership,convert','C1'],
      ['joint ventureize','v','To make or become joint venture','partnership,transform','C1'],
      ['antijoint venture','adj','Opposed to joint venture','against,opposing','C1'],
      ['nonjoint venture','adj','Not involving joint venture','without,lacking','B2'],
      ['prejoint venture','n','Before joint venture','preceding,prior','C1'],
      ['postjoint venture','n','After joint venture','following,subsequent','C1'],
      ['subjoint venture','n','A subdivision of joint venture','subset,branch','C1'],
      ['multijoint venture','adj','Involving many joint ventures','multiple,several','C1'],
      ['interjoint venture','adj','Between joint ventures','cross,between','C1'],
      ['fiscal year','n','A yearly period for financial reporting','financial year,accounting period','B2'],
      ['fiscal yearal','adj','Relating to fiscal year','financial year-related,pertaining to','B2'],
      ['fiscal yearic','adj','Of or relating to fiscal year','financial year-based,characteristic','B2'],
      ['fiscal yearous','adj','Full of fiscal year','financial year-filled,abundant','C1'],
      ['fiscal yearful','adj','Full of fiscal year','financial year-rich,abounding','B2'],
      ['fiscal yearless','adj','Without fiscal year','lacking,without','B2'],
      ['fiscal yearism','n','The ideology of fiscal year','financial year ideology,doctrine','C1'],
      ['fiscal yearist','n','A person focused on fiscal year','financial year specialist,advocate','C1'],
      ['fiscal yearise','v','To make into fiscal year','financial year,convert','C1'],
      ['fiscal yearize','v','To make or become fiscal year','financial year,transform','C1'],
      ['antifiscal year','adj','Opposed to fiscal year','against,opposing','C1'],
      ['nonfiscal year','adj','Not involving fiscal year','without,lacking','B2'],
      ['prefiscal year','n','Before fiscal year','preceding,prior','C1'],
      ['postfiscal year','n','After fiscal year','following,subsequent','C1'],
      ['subfiscal year','n','A subdivision of fiscal year','subset,branch','C1'],
      ['multifiscal year','adj','Involving many fiscal years','multiple,several','C1'],
      ['interfiscal year','adj','Between fiscal years','cross,between','C1'],
      ['due diligenceal','adj','Relating to due diligence','research-related,pertaining to','C1'],
      ['due diligenceic','adj','Of or relating to due diligence','research-based,characteristic','C1'],
      ['due diligenceous','adj','Full of due diligence','research-filled,abundant','C2'],
      ['due diligenceful','adj','Full of due diligence','research-rich,abounding','C1'],
      ['due diligenceless','adj','Without due diligence','lacking,without','C1'],
      ['due diligenceism','n','The ideology of due diligence','research ideology,doctrine','C2'],
      ['due diligenceist','n','A person focused on due diligence','research specialist,advocate','C2'],
      ['due diligenceise','v','To make into due diligence','research,convert','C2'],
      ['due diligenceize','v','To make or become due diligence','research,transform','C2'],
      ['antidue diligence','adj','Opposed to due diligence','against,opposing','C2'],
      ['nondue diligence','adj','Not involving due diligence','without,lacking','C1'],
      ['predue diligence','n','Before due diligence','preceding,prior','C2'],
      ['postdue diligence','n','After due diligence','following,subsequent','C2'],
      ['subdue diligence','n','A subdivision of due diligence','subset,branch','C2'],
      ['multidue diligence','adj','Involving many due diligences','multiple,several','C2'],
      ['interdue diligence','adj','Between due diligences','cross,between','C2'],
    ],
    economy: [
      ['fluctuatation','n','The act of fluctuating','vary process','B2'],
      ['fluctuatment','n','The result of fluctuating','vary outcome','B2'],
      ['fluctuatance','n','The state of fluctuating','vary state','B2'],
      ['fluctuatence','n','The quality of fluctuating','vary quality','B2'],
      ['fluctuatal','n','An act of fluctuating','vary event','C1'],
      ['fluctuater','n','One who fluctuates','vary person','B2'],
      ['fluctuator','n','One who fluctuates','vary agent','B2'],
      ['fluctuatee','n','One who is fluctuated','vary recipient','C1'],
      ['fluctuatable','adj','Capable of being fluctuated','vary,possible','C1'],
      ['fluctuatible','adj','Able to be fluctuated','vary,feasible','C1'],
      ['fluctuative','adj','Tending to fluctuate','vary,active','B2'],
      ['fluctuating','adj','Currently fluctuating','vary,ongoing','B2'],
      ['fluctuated','adj','Having been fluctuated','vary,completed','B2'],
      ['refluctuate','v','To fluctuate again','vary again,repeat','B2'],
      ['unfluctuate','v','To reverse fluctuating','reverse,undo','C1'],
      ['overfluctuate','v','To fluctuate excessively','excess,too much','C1'],
      ['underfluctuate','v','To fluctuate insufficiently','insufficient,inadequate','C1'],
      ['misfluctuate','v','To fluctuate incorrectly','wrongly,incorrectly','C1'],
      ['prefluctuate','v','To fluctuate beforehand','before,in advance','C1'],
      ['cofluctuate','v','To fluctuate together','jointly,together','C1'],
      ['refluctuatation','n','The act of fluctuating again','re-vary','C1'],
      ['overfluctuatation','n','Excessive fluctuating','excess vary','C1'],
      ['stagnatation','n','The act of stagnating','plateau process','B2'],
      ['stagnatment','n','The result of stagnating','plateau outcome','B2'],
      ['stagnatance','n','The state of stagnating','plateau state','B2'],
      ['stagnatence','n','The quality of stagnating','plateau quality','B2'],
      ['stagnatal','n','An act of stagnating','plateau event','C1'],
      ['stagnater','n','One who stagnates','plateau person','B2'],
      ['stagnator','n','One who stagnates','plateau agent','B2'],
      ['stagnatee','n','One who is stagnated','plateau recipient','C1'],
      ['stagnatable','adj','Capable of being stagnated','plateau,possible','C1'],
      ['stagnatible','adj','Able to be stagnated','plateau,feasible','C1'],
      ['stagnative','adj','Tending to stagnate','plateau,active','B2'],
      ['stagnating','adj','Currently stagnating','plateau,ongoing','B2'],
      ['stagnated','adj','Having been stagnated','plateau,completed','B2'],
      ['restagnate','v','To stagnate again','plateau again,repeat','B2'],
      ['unstagnate','v','To reverse stagnating','reverse,undo','C1'],
      ['overstagnate','v','To stagnate excessively','excess,too much','C1'],
      ['understagnate','v','To stagnate insufficiently','insufficient,inadequate','C1'],
      ['misstagnate','v','To stagnate incorrectly','wrongly,incorrectly','C1'],
      ['prestagnate','v','To stagnate beforehand','before,in advance','C1'],
      ['costagnate','v','To stagnate together','jointly,together','C1'],
      ['restagnatation','n','The act of stagnating again','re-plateau','C1'],
      ['overstagnatation','n','Excessive stagnating','excess plateau','C1'],
      ['appreciate','v','To increase in value over time','increase,rise,gain','B2'],
      ['appreciatation','n','The act of appreciating','increase process','B2'],
      ['appreciatment','n','The result of appreciating','increase outcome','B2'],
      ['appreciatance','n','The state of appreciating','increase state','B2'],
      ['appreciatence','n','The quality of appreciating','increase quality','B2'],
      ['appreciatal','n','An act of appreciating','increase event','C1'],
      ['appreciater','n','One who appreciates','increase person','B2'],
      ['appreciator','n','One who appreciates','increase agent','B2'],
      ['appreciatee','n','One who is appreciated','increase recipient','C1'],
      ['appreciatable','adj','Capable of being appreciated','increase,possible','C1'],
      ['appreciatible','adj','Able to be appreciated','increase,feasible','C1'],
      ['appreciative','adj','Tending to appreciate','increase,active','B2'],
      ['appreciating','adj','Currently appreciating','increase,ongoing','B2'],
      ['appreciated','adj','Having been appreciated','increase,completed','B2'],
      ['reappreciate','v','To appreciate again','increase again,repeat','B2'],
      ['unappreciate','v','To reverse appreciating','reverse,undo','C1'],
      ['overappreciate','v','To appreciate excessively','excess,too much','C1'],
      ['underappreciate','v','To appreciate insufficiently','insufficient,inadequate','C1'],
      ['misappreciate','v','To appreciate incorrectly','wrongly,incorrectly','C1'],
      ['preappreciate','v','To appreciate beforehand','before,in advance','C1'],
      ['coappreciate','v','To appreciate together','jointly,together','C1'],
      ['reappreciatation','n','The act of appreciating again','re-increase','C1'],
      ['overappreciatation','n','Excessive appreciating','excess increase','C1'],
      ['deflate','v','To reduce the general price level','decrease,reduce,lower','C1'],
      ['deflatation','n','The act of deflating','decrease process','C1'],
      ['deflatment','n','The result of deflating','decrease outcome','C1'],
      ['deflatance','n','The state of deflating','decrease state','C1'],
    ],
  },
  collocations: {}
};
