'use strict';
module.exports = {
  vocab: {
    education: [
      ["assignment","noun","A task or piece of work given to a student","task,homework","A2"],
      ["booklet","noun","A small thin book with a paper cover","pamphlet,brochure","A2"],
      ["certificate","noun","An official document proving a qualification","diploma,credential","A2"],
      ["classroom","noun","A room in a school where lessons take place","schoolroom,lecture hall","A2"],
      ["compulsory","adj","Required by law or a rule; obligatory","mandatory,required","B1"],
      ["concentrate","verb","To focus all attention on a particular activity","focus,attend","B1"],
      ["coursework","noun","Work done during a course of study","assignments,projects","B1"],
      ["curriculum","noun","The subjects comprising a course of study","syllabus,programme","B1"],
      ["deadline","noun","The latest time by which something should be completed","due date,time limit","B1"],
      ["diploma","noun","A certificate awarded on completion of a course","degree,qualification","B2"],
      ["dropout","noun","A person who has abandoned a course of study","quitter,leaver","B2"],
      ["enrollment","noun","The act of registering as a student","registration,admission","B2"],
      ["essay","noun","A short piece of writing on a particular subject","composition,paper","B2"],
      ["examination","noun","A formal test of knowledge or ability","test,exam","B2"],
      ["faculty","noun","The teaching staff of a university or college","staff,professors","B2"],
      ["feedback","noun","Information about reactions to performance","response,evaluation","C1"],
      ["graduation","noun","The ceremony of receiving an academic degree","commencement,convocation","C1"],
      ["handout","noun","A printed sheet of information distributed free","leaflet,printout","C1"],
      ["homework","noun","Schoolwork assigned to be done outside class","assignment,coursework","C1"],
      ["instructor","noun","A person who teaches a subject or skill","teacher,trainer","C2"],
      ["kindergarten","noun","A school for young children before primary school","preschool,nursery","A2"],
      ["laboratory","noun","A room equipped for scientific experiments","lab,workshop","A2"],
      ["lecture","noun","A talk given to a group of students","presentation,talk","A2"],
      ["literacy","noun","The ability to read and write","reading ability,education","A2"],
      ["mentor","noun","An experienced person who advises a less experienced one","guide,advisor","B1"],
      ["module","noun","A unit forming part of a course of study","unit,section","B1"],
      ["notebook","noun","A small book for writing notes in","journal,notepad","B1"],
      ["optional","adj","Available to be chosen but not obligatory","voluntary,elective","B1"],
      ["placement","noun","The action of putting someone in a position","assignment,posting","B1"],
      ["postgraduate","noun","A student engaged in a course of study after graduating","graduate student,masters student","B2"],
      ["primary","adj","Of first importance or relating to early education","elementary,basic","B2"],
      ["qualification","noun","A pass of an examination or official requirement","credential,certification","B2"],
      ["questionnaire","noun","A set of questions for gathering information","survey,form","B2"],
      ["revision","noun","The process of reviewing material for an exam","review,study","B2"],
      ["scholarship","noun","A grant of money for a student to study","bursary,fellowship","B2"],
      ["semester","noun","A half-year term in a school or university","term,session","C1"],
      ["seminar","noun","A class at university for discussion and training","workshop,tutorial","C1"],
      ["student","noun","A person who is studying at a school or university","learner,pupil","C1"],
      ["supervisor","noun","A person who oversees a student or worker","overseer,manager","C1"],
      ["syllabus","noun","The subjects in a course of study","curriculum,outline","C2"],
      ["textbook","noun","A book used as a standard work for study","manual,coursebook","A2"],
      ["thesis","noun","A long essay involving personal research","dissertation,paper","A2"],
      ["timetable","noun","A schedule showing times of classes or events","schedule,roster","A2"],
      ["tuition","noun","Teaching or the fee charged for instruction","instruction,fees","A2"],
      ["tutorial","noun","A session of intensive teaching for a small group","class,lesson","B1"],
      ["undergraduate","noun","A university student who has not yet taken a first degree","student,fresher","B1"],
      ["university","noun","An institution of higher education","college,academy","B1"],
      ["vocabulary","noun","The body of words used in a particular language","lexicon,terminology","B1"],
      ["workshop","noun","A meeting for discussion and practical work","seminar,class","B1"],
      ["yearbook","noun","An annual publication of student achievements","annual,record","B2"],
    ],
    technology: [
      ["algorithm","noun","A set of rules for solving a problem in computing","procedure,formula","A2"],
      ["application","noun","A computer program designed for a specific purpose","app,software","A2"],
      ["bandwidth","noun","The capacity for data transfer in a network","capacity,throughput","A2"],
      ["battery","noun","A device that stores electrical energy","cell,power pack","A2"],
      ["bluetooth","noun","A wireless technology for exchanging data over short distances","wireless,connectivity","B1"],
      ["bookmark","noun","A saved link to a web page for easy access","favourite,shortcut","B1"],
      ["browser","noun","A program used to access websites on the internet","web browser,navigator","B1"],
      ["charger","noun","A device used to recharge a battery","adapter,power supply","B1"],
      ["click","verb","To press a button on a computer mouse","tap,select","B1"],
      ["compatible","adj","Able to exist or work together without conflict","harmonious,consistent","B2"],
      ["cybersecurity","noun","The practice of protecting systems from digital attacks","information security,cyber defence","B2"],
      ["database","noun","A structured collection of data stored electronically","data store,repository","B2"],
      ["debug","verb","To identify and remove errors from computer programs","troubleshoot,fix","B2"],
      ["device","noun","A piece of equipment made for a particular purpose","gadget,apparatus","B2"],
      ["download","verb","To copy data from one computer system to another","transfer,save","B2"],
      ["email","noun","Messages distributed by electronic means","electronic mail,message","C1"],
      ["encrypt","verb","To convert data into a coded form for security","encode,cipher","C1"],
      ["firewall","noun","A security system that monitors network traffic","security barrier,filter","C1"],
      ["gadget","noun","A small mechanical or electronic device","device,tool","C1"],
      ["hardware","noun","The physical components of a computer system","equipment,machinery","C2"],
      ["install","verb","To set up a program or system for use","set up,configure","A2"],
      ["interface","noun","A point where two systems meet and interact","connection,link","A2"],
      ["keyboard","noun","A panel of keys for operating a computer","input device,keypad","A2"],
      ["laptop","noun","A portable computer small enough to use on your lap","notebook,portable computer","A2"],
      ["malware","noun","Software designed to disrupt or damage a computer","virus,spyware","B1"],
      ["monitor","noun","A display screen for a computer","screen,display","B1"],
      ["network","noun","A group of interconnected computers","system,grid","B1"],
      ["offline","adj","Not connected to the internet","disconnected,unplugged","B1"],
      ["online","adj","Connected to or available through the internet","connected,web-based","B1"],
      ["password","noun","A secret word or phrase for authentication","passcode,PIN","B2"],
      ["pixel","noun","The smallest unit of a digital image","dot,point","B2"],
      ["plugin","noun","A software component that adds a feature to a program","extension,add-on","B2"],
      ["portable","adj","Easy to carry or move","mobile,lightweight","B2"],
      ["printer","noun","A device that produces text or images on paper","output device,copier","B2"],
      ["programming","noun","The process of writing computer programs","coding,development","B2"],
      ["router","noun","A device that forwards data between computer networks","gateway,switch","C1"],
      ["scanner","noun","A device that reads and digitises documents","reader,digitiser","C1"],
      ["screenshot","noun","An image of the display on a screen","screen capture,snapshot","C1"],
      ["server","noun","A computer that provides data to other computers","host,mainframe","C1"],
      ["smartphone","noun","A mobile phone with advanced computing capability","mobile phone,cell phone","C2"],
      ["software","noun","Programs and operating information used by a computer","programs,applications","A2"],
      ["spam","noun","Unwanted or unsolicited electronic messages","junk mail,bulk mail","A2"],
      ["streaming","noun","Transmitting media continuously over the internet","broadcasting,live feed","A2"],
      ["tablet","noun","A flat portable computer operated by touchscreen","pad,slate","A2"],
      ["upgrade","verb","To raise to a higher standard or version","improve,update","B1"],
      ["upload","verb","To transfer data to a larger computer system","send,transmit","B1"],
      ["username","noun","An identification used to access a computer system","login,user ID","B1"],
      ["virus","noun","A piece of code that can replicate and damage a system","malware,bug","B1"],
      ["webpage","noun","A document accessible via the internet","site,page","B1"],
      ["wireless","adj","Using radio waves rather than wires for connection","cordless,WiFi","B2"],
    ],
    health: [
      ["allergy","noun","A damaging immune response to a substance","sensitivity,intolerance","A2"],
      ["ambulance","noun","A vehicle for transporting sick or injured people","emergency vehicle,paramedic van","A2"],
      ["antibiotic","noun","A medicine that inhibits the growth of bacteria","antimicrobial,medicine","A2"],
      ["appetite","noun","A natural desire to satisfy a bodily need for food","hunger,craving","A2"],
      ["bandage","noun","A strip of material used to bind a wound","dressing,wrap","B1"],
      ["blood pressure","noun","The pressure of blood against the walls of arteries","BP,arterial pressure","B1"],
      ["calorie","noun","A unit of energy in food","energy unit,kcal","B1"],
      ["checkup","noun","A thorough medical examination","examination,health check","B1"],
      ["cholesterol","noun","A fatty substance found in blood and body cells","lipid,fat","B1"],
      ["clinic","noun","A place where outpatients receive medical treatment","medical centre,surgery","B2"],
      ["cough","noun","An expulsion of air from the lungs with a sound","hack,bark","B2"],
      ["cure","noun","A substance or treatment that ends a disease","remedy,treatment","B2"],
      ["dentist","noun","A person qualified to treat teeth disorders","dental surgeon,orthodontist","B2"],
      ["diagnosis","noun","The identification of an illness by examination","identification,assessment","B2"],
      ["diet","noun","The food that a person habitually eats","nutrition,food intake","B2"],
      ["disease","noun","A disorder of structure or function in the body","illness,sickness","C1"],
      ["dizzy","adj","Having a sensation of spinning and losing balance","lightheaded,giddy","C1"],
      ["dosage","noun","The size or frequency of a dose of medicine","dose,amount","C1"],
      ["emergency","noun","A serious and unexpected situation requiring action","crisis,urgent situation","C1"],
      ["exercise","noun","Physical activity to sustain health and fitness","workout,training","C2"],
      ["fatigue","noun","Extreme tiredness resulting from effort or illness","exhaustion,weariness","A2"],
      ["fever","noun","An abnormally high body temperature","high temperature,pyrexia","A2"],
      ["flu","noun","A common viral infection causing fever and body aches","influenza,grippe","A2"],
      ["headache","noun","A continuous pain in the head","migraine,cephalalgia","A2"],
      ["hospital","noun","An institution providing medical treatment","medical centre,infirmary","B1"],
      ["hygiene","noun","Conditions or practices conducive to health","cleanliness,sanitation","B1"],
      ["immune","adj","Resistant to a particular infection or toxin","resistant,protected","B1"],
      ["infection","noun","The process of being invaded by harmful organisms","contamination,contagion","B1"],
      ["injury","noun","Physical damage to the body","wound,harm","B1"],
      ["insomnia","noun","Habitual sleeplessness or inability to sleep","sleeplessness,wakefulness","B2"],
      ["medication","noun","A substance used for medical treatment","medicine,drug","B2"],
      ["nurse","noun","A person trained to care for the sick","caregiver,healthcare worker","B2"],
      ["obesity","noun","The condition of being very overweight","corpulence,excess weight","B2"],
      ["operation","noun","A surgical procedure performed on a patient","surgery,procedure","B2"],
      ["optician","noun","A person qualified to prescribe glasses","eye specialist,optometrist","B2"],
      ["painkiller","noun","A drug or medicine for relieving pain","analgesic,pain reliever","C1"],
      ["patient","noun","A person receiving medical treatment","sick person,case","C1"],
      ["pharmacy","noun","A shop where medicinal drugs are dispensed","chemist,drugstore","C1"],
      ["prescription","noun","A doctor s instruction for medicine","script,medical order","C1"],
      ["protein","noun","A nutrient essential for body growth and repair","amino acids,macronutrient","C2"],
      ["recovery","noun","The process of returning to a normal state of health","recuperation,healing","A2"],
      ["remedy","noun","A medicine or treatment for a disease","cure,treatment","A2"],
      ["specialist","noun","A doctor concentrating on a specific area of medicine","consultant,expert","A2"],
      ["stress","noun","A state of mental or emotional strain","pressure,tension","A2"],
      ["surgeon","noun","A doctor who performs operations","operating doctor,surgical specialist","B1"],
      ["symptom","noun","A physical sign indicating a condition or disease","indication,sign","B1"],
      ["therapy","noun","Treatment intended to relieve or heal a disorder","treatment,rehabilitation","B1"],
      ["vaccine","noun","A substance used to stimulate immunity to disease","immunisation,inoculation","B1"],
      ["vitamin","noun","An organic compound essential for normal nutrition","nutrient,supplement","B1"],
      ["ward","noun","A room in a hospital for patients","department,unit","B2"],
    ],
    environment: [
      ["atmosphere","noun","The envelope of gases surrounding the earth","air,sky","A2"],
      ["biodiversity","noun","The variety of plant and animal life in a habitat","biological diversity,variety of life","A2"],
      ["carbon","noun","A chemical element present in all organic compounds","element,C","A2"],
      ["catastrophe","noun","An event causing great damage or suffering","disaster,calamity","A2"],
      ["climate","noun","The weather conditions prevailing in an area","weather pattern,conditions","B1"],
      ["compost","noun","Decayed organic material used as a fertiliser","mulch,humus","B1"],
      ["conservation","noun","The protection of natural resources","preservation,protection","B1"],
      ["contaminate","verb","To make something impure by exposure to pollutants","pollute,taint","B1"],
      ["coral","noun","A hard stony substance formed by marine organisms","reef,marine formation","B1"],
      ["crop","noun","A plant cultivated on a large scale for food","harvest,produce","B2"],
      ["deforestation","noun","The clearing of trees from forested areas","tree felling,logging","B2"],
      ["dispose","verb","To get rid of something by throwing away","discard,remove","B2"],
      ["drought","noun","A prolonged period of abnormally low rainfall","dry spell,water shortage","B2"],
      ["earthquake","noun","A sudden violent shaking of the ground","tremor,seismic event","B2"],
      ["ecology","noun","The branch of biology concerning organisms and environment","environmental science,ecosystem study","B2"],
      ["emission","noun","The production and discharge of gas or radiation","discharge,output","C1"],
      ["endangered","adj","Seriously at risk of extinction","threatened,at risk","C1"],
      ["erosion","noun","The gradual wearing away of rock or soil","wearing away,degradation","C1"],
      ["extinct","adj","No longer existing as a living species","died out,vanished","C1"],
      ["fertiliser","noun","A substance added to soil to increase fertility","manure,plant food","C2"],
      ["flood","noun","An overflow of a large amount of water","deluge,inundation","A2"],
      ["fossil","noun","The remains of a prehistoric organism preserved in rock","remnant,relic","A2"],
      ["glacier","noun","A slowly moving mass of ice","ice sheet,ice field","A2"],
      ["greenhouse","noun","A glass building for growing plants in warmth","glasshouse,hothouse","A2"],
      ["habitat","noun","The natural home of an animal or plant","environment,ecosystem","B1"],
      ["hurricane","noun","A storm with violent wind and heavy rain","typhoon,cyclone","B1"],
      ["irrigation","noun","The supply of water to land for crop cultivation","watering,sprinkling","B1"],
      ["landfill","noun","A site for disposing of waste materials by burial","dump,tip","B1"],
      ["landscape","noun","The visible features of an area of land","scenery,terrain","B1"],
      ["mineral","noun","A solid inorganic substance found in nature","ore,rock","B2"],
      ["natural","adj","Existing in or derived from nature","organic,wild","B2"],
      ["ozone","noun","A form of oxygen that forms a protective layer","O3,atmospheric gas","B2"],
      ["pesticide","noun","A substance used to destroy pests","insecticide,herbicide","B2"],
      ["plantation","noun","An estate on which crops are cultivated","farm,estate","B2"],
      ["pollution","noun","The presence of harmful substances in the environment","contamination,impurity","B2"],
      ["rainforest","noun","A dense tropical forest with high rainfall","jungle,tropical forest","C1"],
      ["recycle","verb","To convert waste into reusable material","reuse,reprocess","C1"],
      ["renewable","adj","Capable of being replaced by natural processes","sustainable,replenishable","C1"],
      ["reservoir","noun","A large natural or artificial lake for water storage","tank,basin","C1"],
      ["resource","noun","A supply of material that can be drawn on","asset,supply","C2"],
      ["solar","adj","Relating to or determined by the sun","sun-powered,sunlight-based","A2"],
      ["species","noun","A group of similar organisms that can interbreed","type,kind","A2"],
      ["sustainable","adj","Able to be maintained at a certain rate or level","viable,maintainable","A2"],
      ["temperature","noun","The degree of heat in a body or environment","heat,warmth","A2"],
      ["tornado","noun","A violent rotating column of air","twister,whirlwind","B1"],
      ["toxic","adj","Poisonous; causing harm to living organisms","poisonous,harmful","B1"],
      ["tsunami","noun","A long high sea wave caused by an earthquake","tidal wave,seismic wave","B1"],
      ["vegetation","noun","Plants considered collectively","plant life,flora","B1"],
      ["volcanic","adj","Relating to or produced by a volcano","igneous,eruptive","B1"],
      ["wildlife","noun","Wild animals collectively","fauna,wild creatures","B2"],
    ],
    business: [
      ["accountant","noun","A person whose job is to keep financial records","bookkeeper,auditor","A2"],
      ["advertisement","noun","A notice promoting a product or service","ad,commercial","A2"],
      ["agenda","noun","A list of items to be discussed at a meeting","schedule,programme","A2"],
      ["bankrupt","adj","Unable to pay outstanding debts","insolvent,broke","A2"],
      ["bargain","noun","A thing bought or sold for less than the usual price","deal,discount","B1"],
      ["billboard","noun","A large outdoor board for displaying advertisements","hoarding,signboard","B1"],
      ["bonus","noun","An extra payment given to an employee","reward,incentive","B1"],
      ["brand","noun","A type of product made by a particular company","trademark,label","B1"],
      ["budget","noun","An estimate of income and expenditure for a period","financial plan,spending plan","B1"],
      ["client","noun","A person using the services of a professional","customer,patron","B2"],
      ["colleague","noun","A person with whom one works","co-worker,associate","B2"],
      ["commission","noun","A fee paid to an agent for a transaction","percentage,fee","B2"],
      ["competitor","noun","A person or company competing with another","rival,opponent","B2"],
      ["complaint","noun","An expression of dissatisfaction","grievance,objection","B2"],
      ["consumer","noun","A person who purchases goods and services","buyer,customer","B2"],
      ["contract","noun","A written agreement enforceable by law","agreement,deal","C1"],
      ["corporation","noun","A large company or group of companies","company,firm","C1"],
      ["deadline","noun","The latest time by which something must be completed","due date,cutoff","C1"],
      ["demand","noun","The desire of consumers for a product or service","need,requirement","C1"],
      ["discount","noun","A deduction from the usual cost of something","reduction,markdown","C2"],
      ["dividend","noun","A payment made to shareholders from company profits","payout,distribution","A2"],
      ["employee","noun","A person employed for wages or salary","worker,staff member","A2"],
      ["employer","noun","A person or company that employs people","company,boss","A2"],
      ["entrepreneur","noun","A person who sets up and runs a business","businessperson,founder","A2"],
      ["estimate","noun","An approximate calculation of cost or value","assessment,quotation","B1"],
      ["export","verb","To send goods to another country for sale","ship abroad,sell overseas","B1"],
      ["franchise","noun","An authorisation to sell a company s goods in an area","licence,dealership","B1"],
      ["headquarter","noun","The main offices of an organisation","head office,main office","B1"],
      ["import","verb","To bring goods into a country from abroad","bring in,purchase abroad","B1"],
      ["income","noun","Money received for work or investments","earnings,revenue","B2"],
      ["insurance","noun","An arrangement for compensation in case of loss","cover,protection","B2"],
      ["inventory","noun","A complete list of items or goods in stock","stock,catalogue","B2"],
      ["invoice","noun","A list of goods sent or services with a sum owed","bill,account","B2"],
      ["launch","verb","To introduce a new product to the public","release,debut","B2"],
      ["liability","noun","A thing for which someone is responsible","obligation,debt","B2"],
      ["loan","noun","A thing that is borrowed, especially money","advance,credit","C1"],
      ["manufacture","verb","To make goods on a large scale using machinery","produce,fabricate","C1"],
      ["market","noun","An area or arena in which commercial dealings occur","marketplace,trade","C1"],
      ["merger","noun","A combination of two companies into one","amalgamation,union","C1"],
      ["negotiate","verb","To try to reach an agreement through discussion","bargain,discuss terms","C2"],
      ["outlet","noun","A shop or store selling goods of a particular brand","store,retail point","A2"],
      ["partnership","noun","An association of two or more people as partners","alliance,collaboration","A2"],
      ["profit","noun","A financial gain from business transactions","earnings,return","A2"],
      ["promote","verb","To further the progress of something","advance,boost","A2"],
      ["receipt","noun","A written acknowledgment of payment","proof of purchase,slip","B1"],
      ["retail","noun","The sale of goods to the public in small quantities","selling,commerce","B1"],
      ["revenue","noun","Income generated from normal business operations","income,earnings","B1"],
      ["salary","noun","A fixed regular payment for employment","wages,pay","B1"],
      ["shareholder","noun","An owner of shares in a company","investor,stockholder","B1"],
      ["turnover","noun","The amount of money taken by a business in a period","revenue,sales volume","B2"],
    ],
    economy: [
      ["affordable","adj","Inexpensive and within financial reach","cheap,reasonable","A2"],
      ["asset","noun","A useful or valuable thing or person","resource,property","A2"],
      ["auction","noun","A public sale where goods are sold to the highest bidder","sale,bidding","A2"],
      ["boom","noun","A period of great economic prosperity","upturn,growth","A2"],
      ["capital","noun","Wealth owned or used in business by a person or company","funds,assets","B1"],
      ["commodity","noun","A raw material or agricultural product that can be traded","goods,product","B1"],
      ["currency","noun","A system of money in general use in a country","money,legal tender","B1"],
      ["debt","noun","Something owed, especially money","liability,obligation","B1"],
      ["deficit","noun","The amount by which spending exceeds income","shortfall,loss","B1"],
      ["depression","noun","A severe and prolonged downturn in the economy","slump,recession","B2"],
      ["exchange","noun","The giving of one thing and receiving another","trade,swap","B2"],
      ["expenditure","noun","The action of spending funds","spending,outlay","B2"],
      ["fiscal","adj","Relating to government revenue and taxation","financial,monetary","B2"],
      ["GDP","noun","The total value of goods and services produced in a country","gross domestic product,national output","B2"],
      ["globalisation","noun","The process of international integration","internationalisation,worldwide spread","B2"],
      ["incentive","noun","Something that motivates action","motivation,stimulus","C1"],
      ["inflation","noun","A general increase in prices over time","price rise,cost increase","C1"],
      ["interest","noun","Money paid for borrowing or earned on savings","return,yield","C1"],
      ["invest","verb","To put money into financial schemes for profit","fund,finance","C1"],
      ["investor","noun","A person who puts money into an enterprise","backer,financier","C2"],
      ["luxury","noun","Something expensive and not strictly necessary","extravagance,indulgence","A2"],
      ["monetary","adj","Relating to money or currency","financial,fiscal","A2"],
      ["mortgage","noun","A loan secured on property","home loan,property loan","A2"],
      ["poverty","noun","The state of being extremely poor","destitution,hardship","A2"],
      ["prosperity","noun","The state of being financially successful","wealth,affluence","B1"],
      ["recession","noun","A period of temporary economic decline","downturn,slump","B1"],
      ["savings","noun","Money set aside for future use","reserves,nest egg","B1"],
      ["stock","noun","The goods available for sale or shares in a company","inventory,shares","B1"],
      ["subsidy","noun","Money granted by a government to assist an industry","grant,aid","B1"],
      ["surplus","noun","An amount of something greater than what is needed","excess,remainder","B2"],
      ["tariff","noun","A tax on imports or exports","duty,levy","B2"],
      ["taxation","noun","The levying of taxes on citizens and businesses","tax,duty","B2"],
      ["trade","noun","The buying and selling of goods and services","commerce,business","B2"],
      ["unemployment","noun","The state of being without a paid job","joblessness,worklessness","B2"],
      ["wage","noun","A regular payment for work based on time or output","pay,earnings","B2"],
      ["wealth","noun","An abundance of valuable possessions or money","riches,fortune","C1"],
    ],
    society: [
      ["adolescent","noun","A young person developing into an adult","teenager,youth","A2"],
      ["charity","noun","An organisation set up to help those in need","nonprofit,foundation","A2"],
      ["citizen","noun","A legally recognised member of a state","resident,national","A2"],
      ["community","noun","A group of people living in the same area","neighbourhood,society","A2"],
      ["conform","verb","To comply with rules or standards","comply,follow","B1"],
      ["custom","noun","A traditional and widely accepted practice","tradition,convention","B1"],
      ["democracy","noun","A system of government by the whole population","self-government,republic","B1"],
      ["discrimination","noun","Unjust treatment based on category of person","prejudice,bias","B1"],
      ["diversity","noun","The state of being diverse in character","variety,multiformity","B1"],
      ["elderly","adj","Old or ageing","aged,senior","B2"],
      ["equality","noun","The state of being equal in status and rights","fairness,parity","B2"],
      ["ethnic","adj","Relating to a group sharing cultural traditions","racial,cultural","B2"],
      ["generation","noun","All the people born around the same time","age group,cohort","B2"],
      ["homeless","adj","Without a place to live","displaced,unsheltered","B2"],
      ["identity","noun","The characteristics determining who someone is","individuality,selfhood","B2"],
      ["immigrant","noun","A person who comes to live permanently in a foreign country","migrant,settler","C1"],
      ["inequality","noun","Difference in size, degree, or circumstances","disparity,imbalance","C1"],
      ["integrate","verb","To combine or be combined to form a whole","merge,unify","C1"],
      ["minority","noun","A smaller group within a community","subgroup,lesser group","C1"],
      ["neighbourhood","noun","A district or community within a town or city","area,locality","C2"],
      ["norm","noun","A standard or pattern regarded as typical","standard,convention","A2"],
      ["orphan","noun","A child whose parents are dead","parentless child,ward","A2"],
      ["pension","noun","A regular payment to retired people","retirement benefit,annuity","A2"],
      ["poverty","noun","The state of being extremely poor","destitution,privation","A2"],
      ["prejudice","noun","Preconceived opinion not based on reason","bias,discrimination","B1"],
      ["privilege","noun","A special right or advantage for a particular group","advantage,benefit","B1"],
      ["protest","noun","A statement of objection to something","demonstration,rally","B1"],
      ["refugee","noun","A person forced to leave their country due to danger","asylum seeker,displaced person","B1"],
      ["religion","noun","A system of faith and worship","faith,belief","B1"],
      ["retire","verb","To leave work permanently due to age","stop working,withdraw","B2"],
      ["rural","adj","Relating to the countryside","country,pastoral","B2"],
      ["shelter","noun","A place providing protection from bad weather or danger","refuge,haven","B2"],
      ["tradition","noun","A custom passed down through generations","custom,practice","B2"],
      ["urban","adj","Relating to a town or city","city,metropolitan","B2"],
      ["volunteer","noun","A person who freely offers to do something","helper,unpaid worker","B2"],
      ["welfare","noun","Statutory procedures for the basic well-being of citizens","social security,public aid","C1"],
    ],
  },
  collocations: {
    education: [
      ["attend a lecture","To be present at a formal talk at university","go to a lecture,sit in on a lecture","A2"],
      ["complete an assignment","To finish a task given by a teacher","finish homework,do coursework","A2"],
      ["drop out of school","To leave school before finishing","quit school,abandon studies","A2"],
      ["earn a degree","To receive an academic qualification","obtain a degree,get a qualification","A2"],
      ["enrol in a course","To register for a programme of study","sign up for a class,register for a course","B1"],
      ["fail an exam","To not achieve a passing grade in a test","flunk a test,not pass an exam","B1"],
      ["gain knowledge","To acquire information through study","acquire knowledge,learn new things","B1"],
      ["get a scholarship","To receive financial aid for study","win a bursary,obtain funding","B1"],
      ["hand in homework","To submit school assignments","submit work,turn in an assignment","B1"],
      ["learn by heart","To memorise something completely","memorise,commit to memory","B2"],
      ["make progress","To advance or improve in ability","improve,move forward","B2"],
      ["meet a deadline","To complete something by the required time","finish on time,submit punctually","B2"],
      ["miss a class","To not attend a scheduled lesson","skip a lesson,be absent from class","B2"],
      ["pass an exam","To achieve a passing grade in a test","succeed in a test,clear an exam","B2"],
      ["pay tuition fees","To pay for educational instruction","cover school costs,pay for education","B2"],
      ["raise standards","To improve the quality of education","improve quality,enhance standards","C1"],
      ["read extensively","To read widely across many sources","read broadly,study widely","C1"],
      ["revise for an exam","To review material before a test","study for a test,prepare for an exam","C1"],
      ["sit an exam","To take a formal test","take a test,do an examination","C1"],
      ["take notes","To write down important points","write notes,record information","C2"],
      ["write an essay","To compose a piece of academic writing","draft a paper,compose an essay","A2"],
    ],
    technology: [
      ["access the internet","To connect to and use the world wide web","go online,get online","A2"],
      ["back up data","To make a copy of data for security","save a copy,create a backup","A2"],
      ["browse the web","To look at websites on the internet","surf the internet,search online","A2"],
      ["charge a battery","To restore electrical energy to a battery","recharge,power up","A2"],
      ["click a link","To select a hyperlink on a webpage","follow a link,open a link","B1"],
      ["crash unexpectedly","To stop working suddenly without warning","break down,freeze up","B1"],
      ["create a password","To make a secret code for access","set a password,choose a passcode","B1"],
      ["delete a file","To remove a digital document permanently","erase a file,remove a document","B1"],
      ["download software","To copy programs from the internet","install an app,get a program","B1"],
      ["install updates","To add new versions of software","update software,apply patches","B2"],
      ["log in to an account","To enter credentials to access a system","sign in,authenticate","B2"],
      ["run a program","To execute a software application","launch software,start an application","B2"],
      ["save a document","To store a file on a computer","store a file,keep a document","B2"],
      ["scroll down","To move content on a screen downward","move down,navigate down","B2"],
      ["search online","To look for information on the internet","google,look up online","B2"],
      ["send an email","To transmit an electronic message","write an email,dispatch a message","C1"],
      ["share a file","To give others access to a digital document","distribute a file,send a document","C1"],
      ["shut down","To turn off a computer completely","power off,switch off","C1"],
      ["stream a video","To watch video content live over the internet","watch online,play a video","C1"],
      ["update an app","To install the latest version of an application","upgrade software,refresh an app","C2"],
      ["upload a photo","To transfer an image to the internet","post a picture,share an image","A2"],
    ],
    health: [
      ["boost your immunity","To strengthen the body s defence system","improve immunity,strengthen defences","A2"],
      ["break a bone","To fracture a part of the skeleton","fracture a bone,crack a bone","A2"],
      ["catch a cold","To become infected with a common virus","get a cold,come down with a cold","A2"],
      ["check blood pressure","To measure the force of blood in arteries","monitor BP,take blood pressure","A2"],
      ["do exercise","To engage in physical activity for health","work out,keep fit","B1"],
      ["feel dizzy","To experience a spinning sensation","feel lightheaded,feel faint","B1"],
      ["get vaccinated","To receive a vaccine for disease prevention","have an injection,be immunised","B1"],
      ["have a checkup","To undergo a routine medical examination","get examined,see a doctor","B1"],
      ["have surgery","To undergo a medical operation","have an operation,go under the knife","B1"],
      ["lose weight","To reduce body mass","slim down,shed pounds","B2"],
      ["make an appointment","To arrange a time to see a doctor","book a consultation,schedule a visit","B2"],
      ["prescribe medication","To authorise medicine for a patient","write a prescription,order medicine","B2"],
      ["recover from illness","To return to health after being sick","get better,heal from sickness","B2"],
      ["reduce stress","To lower mental or emotional strain","relieve tension,manage pressure","B2"],
      ["run a fever","To have a body temperature above normal","have a temperature,be feverish","B2"],
      ["seek treatment","To look for medical care","get medical help,consult a doctor","C1"],
      ["suffer from allergies","To be affected by allergic reactions","have allergies,experience allergic symptoms","C1"],
      ["take medicine","To consume a drug for treatment","have medication,swallow pills","C1"],
      ["take a rest","To relax and recover energy","have a break,lie down","C1"],
      ["treat a patient","To provide medical care to someone","care for someone,attend to a patient","C2"],
      ["undergo therapy","To receive treatment for a condition","have treatment,participate in rehabilitation","A2"],
    ],
    environment: [
      ["ban plastic bags","To prohibit the use of disposable plastic bags","outlaw plastic bags,eliminate plastic bags","A2"],
      ["become extinct","To cease to exist as a species","die out,vanish completely","A2"],
      ["burn fossil fuels","To use coal, oil, or gas for energy","consume fossil fuels,use nonrenewable energy","A2"],
      ["cause pollution","To create harmful substances in the environment","produce contamination,generate waste","A2"],
      ["clean up waste","To remove rubbish from an area","collect litter,dispose of rubbish","B1"],
      ["combat climate change","To take action against global warming","fight global warming,address climate issues","B1"],
      ["conserve energy","To use energy efficiently and avoid waste","save power,reduce consumption","B1"],
      ["cut emissions","To reduce the output of harmful gases","lower pollution,decrease carbon output","B1"],
      ["damage the ecosystem","To harm the natural environment","harm wildlife,destroy habitats","B1"],
      ["dispose of waste","To get rid of rubbish properly","throw away trash,manage waste","B2"],
      ["face extinction","To be at risk of dying out as a species","be endangered,risk disappearing","B2"],
      ["generate electricity","To produce electrical power","make power,create energy","B2"],
      ["install solar panels","To set up devices that convert sunlight to energy","use solar energy,put up solar cells","B2"],
      ["plant trees","To place young trees in the ground to grow","reforest,do tree planting","B2"],
      ["protect wildlife","To safeguard wild animals and their habitats","conserve nature,preserve animal life","B2"],
      ["raise awareness","To increase public knowledge of an issue","educate people,inform the public","C1"],
      ["recycle materials","To process used items for new products","reuse materials,reprocess waste","C1"],
      ["reduce carbon footprint","To decrease the amount of carbon dioxide produced","lower emissions,minimise environmental impact","C1"],
      ["save water","To use water carefully and avoid waste","conserve water,reduce water usage","C1"],
      ["tackle deforestation","To address the problem of forest destruction","combat logging,fight tree loss","C2"],
      ["use renewable energy","To employ energy from sustainable sources","go green,harness clean energy","A2"],
    ],
    business: [
      ["apply for a job","To formally request employment","submit an application,seek a position","A2"],
      ["attend a meeting","To be present at a formal discussion","go to a meeting,join a conference","A2"],
      ["boost sales","To increase the amount of goods sold","increase revenue,grow sales","A2"],
      ["build a reputation","To develop a good public image over time","establish credibility,earn respect","A2"],
      ["close a deal","To finalise a business agreement","seal an agreement,complete a transaction","B1"],
      ["cut costs","To reduce expenses","lower spending,reduce expenditure","B1"],
      ["deliver a presentation","To give a formal talk to an audience","give a speech,present information","B1"],
      ["expand a business","To make a company larger or broader","grow a company,scale up operations","B1"],
      ["file a complaint","To formally report dissatisfaction","lodge a grievance,register a complaint","B1"],
      ["hire employees","To recruit workers for a company","employ staff,take on workers","B2"],
      ["increase productivity","To improve the rate of output","boost efficiency,enhance output","B2"],
      ["launch a product","To introduce a new item to the market","release a product,debut an item","B2"],
      ["make a profit","To earn more money than is spent","generate income,turn a profit","B2"],
      ["manage a team","To oversee and direct a group of workers","lead a team,supervise staff","B2"],
      ["meet a target","To achieve a planned goal","reach a goal,hit an objective","B2"],
      ["negotiate a contract","To discuss terms of a formal agreement","discuss a deal,work out terms","C1"],
      ["place an order","To request goods from a supplier","make a purchase,order stock","C1"],
      ["provide a service","To offer assistance or work to customers","deliver a service,supply help","C1"],
      ["receive feedback","To get opinions about work or performance","get reviews,obtain evaluations","C1"],
      ["run a business","To operate and manage a company","manage a company,own a business","C2"],
      ["sign a contract","To formally agree to terms in writing","execute an agreement,finalise a deal","A2"],
    ],
    economy: [
      ["attract investment","To encourage people to put money into something","draw investors,bring in capital","A2"],
      ["balance the budget","To ensure income matches expenditure","equalise spending,manage finances","A2"],
      ["boost the economy","To stimulate economic growth","grow the economy,improve economic conditions","A2"],
      ["create jobs","To generate employment opportunities","provide work,open positions","A2"],
      ["cut interest rates","To reduce the cost of borrowing money","lower rates,decrease borrowing costs","B1"],
      ["earn a living","To make enough money to support oneself","make a living,support oneself","B1"],
      ["face a recession","To experience an economic downturn","undergo a slump,endure a downturn","B1"],
      ["generate revenue","To produce income from business activities","earn income,make money","B1"],
      ["impose a tariff","To set a tax on imported goods","levy a duty,charge import tax","B1"],
      ["increase taxes","To raise the amount of tax levied","raise taxation,hike taxes","B2"],
      ["open a bank account","To establish a new account at a financial institution","set up an account,start banking","B2"],
      ["pay off debts","To repay money that is owed","settle debts,clear obligations","B2"],
      ["reduce inflation","To lower the rate of price increases","control prices,curb inflation","B2"],
      ["save money","To keep money for future use","put aside funds,build savings","B2"],
      ["spend wisely","To use money carefully and effectively","budget well,manage spending","B2"],
      ["stimulate growth","To encourage economic expansion","promote development,drive growth","C1"],
    ],
    society: [
      ["address inequality","To take action on unfair differences","tackle disparity,fight unfairness","A2"],
      ["break the law","To commit an illegal act","violate the law,commit a crime","A2"],
      ["bridge the gap","To reduce the difference between two groups","narrow the divide,close the distance","A2"],
      ["build communities","To create strong social groups","develop neighbourhoods,strengthen social bonds","A2"],
      ["care for the elderly","To look after older people","support seniors,tend to the aged","B1"],
      ["combat discrimination","To fight against unfair treatment","oppose prejudice,challenge bias","B1"],
      ["donate to charity","To give money or goods to a good cause","contribute to a cause,give to the needy","B1"],
      ["exercise rights","To make use of legal entitlements","use freedoms,claim rights","B1"],
      ["follow traditions","To observe customs passed down through generations","keep customs,maintain practices","B1"],
      ["integrate into society","To become part of a social group","assimilate,blend in","B2"],
      ["obey the law","To follow legal rules and regulations","comply with rules,respect the law","B2"],
      ["overcome obstacles","To successfully deal with difficulties","surmount challenges,conquer barriers","B2"],
      ["pay taxes","To contribute money to the government","file taxes,meet tax obligations","B2"],
      ["promote equality","To encourage equal treatment for all","advance fairness,support equal rights","B2"],
      ["raise awareness","To make people more informed about an issue","increase understanding,educate the public","B2"],
      ["respect diversity","To accept and value differences among people","embrace differences,appreciate variety","C1"],
    ],
  },
};
