// Auto-generated vocab boost group 39
module.exports = {
  vocab: {
    technology: [
      ['repositoryize','v','To make or become repository','storage,transform','C1'],
      ['antirepository','adj','Opposed to repository','against,opposing','C1'],
      ['nonrepository','adj','Not involving repository','without,lacking','B2'],
      ['prerepository','n','Before repository','preceding,prior','C1'],
      ['postrepository','n','After repository','following,subsequent','C1'],
      ['subrepository','n','A subdivision of repository','subset,branch','C1'],
      ['multirepository','adj','Involving many repositorys','multiple,several','C1'],
      ['interrepository','adj','Between repositorys','cross,between','C1'],
      ['virtualization','n','The act of virtualizing','emulate process','C1'],
      ['virtualizment','n','The result of virtualizing','emulate outcome','C1'],
      ['virtualizance','n','The state of virtualizing','emulate state','C1'],
      ['virtualizence','n','The quality of virtualizing','emulate quality','C1'],
      ['virtualizal','n','An act of virtualizing','emulate event','C2'],
      ['virtualizer','n','One who virtualizes','emulate person','C1'],
      ['virtualizor','n','One who virtualizes','emulate agent','C1'],
      ['virtualizee','n','One who is virtualized','emulate recipient','C2'],
      ['virtualizable','adj','Capable of being virtualized','emulate,possible','C2'],
      ['virtualizible','adj','Able to be virtualized','emulate,feasible','C2'],
      ['virtualizive','adj','Tending to virtualize','emulate,active','C1'],
      ['virtualizing','adj','Currently virtualizing','emulate,ongoing','C1'],
      ['virtualized','adj','Having been virtualized','emulate,completed','C1'],
      ['revirtualize','v','To virtualize again','emulate again,repeat','C1'],
      ['unvirtualize','v','To reverse virtualizing','reverse,undo','C2'],
      ['overvirtualize','v','To virtualize excessively','excess,too much','C2'],
      ['undervirtualize','v','To virtualize insufficiently','insufficient,inadequate','C2'],
      ['misvirtualize','v','To virtualize incorrectly','wrongly,incorrectly','C2'],
      ['previrtualize','v','To virtualize beforehand','before,in advance','C2'],
      ['covirtualize','v','To virtualize together','jointly,together','C2'],
      ['revirtualization','n','The act of virtualizing again','re-emulate','C2'],
      ['overvirtualization','n','Excessive virtualizing','excess emulate','C2'],
      ['tokenize','v','To convert data into representative tokens','encode,segment,parse','C1'],
      ['tokenization','n','The act of tokenizing','encode process','C1'],
      ['tokenizment','n','The result of tokenizing','encode outcome','C1'],
      ['tokenizance','n','The state of tokenizing','encode state','C1'],
      ['tokenizence','n','The quality of tokenizing','encode quality','C1'],
      ['tokenizal','n','An act of tokenizing','encode event','C2'],
      ['tokenizer','n','One who tokenizes','encode person','C1'],
      ['tokenizor','n','One who tokenizes','encode agent','C1'],
      ['tokenizee','n','One who is tokenized','encode recipient','C2'],
      ['tokenizable','adj','Capable of being tokenized','encode,possible','C2'],
      ['tokenizible','adj','Able to be tokenized','encode,feasible','C2'],
      ['tokenizive','adj','Tending to tokenize','encode,active','C1'],
      ['tokenizing','adj','Currently tokenizing','encode,ongoing','C1'],
      ['tokenized','adj','Having been tokenized','encode,completed','C1'],
      ['retokenize','v','To tokenize again','encode again,repeat','C1'],
      ['untokenize','v','To reverse tokenizing','reverse,undo','C2'],
      ['overtokenize','v','To tokenize excessively','excess,too much','C2'],
      ['undertokenize','v','To tokenize insufficiently','insufficient,inadequate','C2'],
      ['mistokenize','v','To tokenize incorrectly','wrongly,incorrectly','C2'],
      ['pretokenize','v','To tokenize beforehand','before,in advance','C2'],
      ['cotokenize','v','To tokenize together','jointly,together','C2'],
      ['retokenization','n','The act of tokenizing again','re-encode','C2'],
      ['overtokenization','n','Excessive tokenizing','excess encode','C2'],
      ['parallelize','v','To execute multiple tasks simultaneously','distribute,multithread,concurrent','C1'],
      ['parallelization','n','The act of parallelizing','distribute process','C1'],
      ['parallelizment','n','The result of parallelizing','distribute outcome','C1'],
      ['parallelizance','n','The state of parallelizing','distribute state','C1'],
      ['parallelizence','n','The quality of parallelizing','distribute quality','C1'],
      ['parallelizal','n','An act of parallelizing','distribute event','C2'],
      ['parallelizer','n','One who parallelizes','distribute person','C1'],
      ['parallelizor','n','One who parallelizes','distribute agent','C1'],
      ['parallelizee','n','One who is parallelized','distribute recipient','C2'],
      ['parallelizable','adj','Capable of being parallelized','distribute,possible','C2'],
      ['parallelizible','adj','Able to be parallelized','distribute,feasible','C2'],
      ['parallelizive','adj','Tending to parallelize','distribute,active','C1'],
      ['parallelizing','adj','Currently parallelizing','distribute,ongoing','C1'],
      ['parallelized','adj','Having been parallelized','distribute,completed','C1'],
      ['reparallelize','v','To parallelize again','distribute again,repeat','C1'],
      ['unparallelize','v','To reverse parallelizing','reverse,undo','C2'],
      ['overparallelize','v','To parallelize excessively','excess,too much','C2'],
      ['underparallelize','v','To parallelize insufficiently','insufficient,inadequate','C2'],
      ['misparallelize','v','To parallelize incorrectly','wrongly,incorrectly','C2'],
      ['preparallelize','v','To parallelize beforehand','before,in advance','C2'],
      ['coparallelize','v','To parallelize together','jointly,together','C2'],
      ['reparallelization','n','The act of parallelizing again','re-distribute','C2'],
      ['overparallelization','n','Excessive parallelizing','excess distribute','C2'],
      ['instantiate','v','To create an instance of something','create,generate,realize','C1'],
      ['instantiatation','n','The act of instantiating','create process','C1'],
      ['instantiatment','n','The result of instantiating','create outcome','C1'],
      ['instantiatance','n','The state of instantiating','create state','C1'],
      ['instantiatence','n','The quality of instantiating','create quality','C1'],
      ['instantiatal','n','An act of instantiating','create event','C2'],
      ['instantiater','n','One who instantiates','create person','C1'],
      ['instantiator','n','One who instantiates','create agent','C1'],
      ['instantiatee','n','One who is instantiated','create recipient','C2'],
      ['instantiatable','adj','Capable of being instantiated','create,possible','C2'],
      ['instantiatible','adj','Able to be instantiated','create,feasible','C2'],
      ['instantiative','adj','Tending to instantiate','create,active','C1'],
      ['instantiating','adj','Currently instantiating','create,ongoing','C1'],
      ['instantiated','adj','Having been instantiated','create,completed','C1'],
      ['reinstantiate','v','To instantiate again','create again,repeat','C1'],
      ['uninstantiate','v','To reverse instantiating','reverse,undo','C2'],
      ['overinstantiate','v','To instantiate excessively','excess,too much','C2'],
      ['underinstantiate','v','To instantiate insufficiently','insufficient,inadequate','C2'],
      ['misinstantiate','v','To instantiate incorrectly','wrongly,incorrectly','C2'],
      ['preinstantiate','v','To instantiate beforehand','before,in advance','C2'],
      ['coinstantiate','v','To instantiate together','jointly,together','C2'],
      ['reinstantiatation','n','The act of instantiating again','re-create','C2'],
      ['overinstantiatation','n','Excessive instantiating','excess create','C2'],
      ['deprecate','v','To mark something as no longer recommended','retire,phase out,discontinue','C1'],
      ['deprecatation','n','The act of deprecating','retire process','C1'],
      ['deprecatment','n','The result of deprecating','retire outcome','C1'],
      ['deprecatance','n','The state of deprecating','retire state','C1'],
      ['deprecatence','n','The quality of deprecating','retire quality','C1'],
      ['deprecatal','n','An act of deprecating','retire event','C2'],
      ['deprecater','n','One who deprecates','retire person','C1'],
      ['deprecator','n','One who deprecates','retire agent','C1'],
      ['deprecatee','n','One who is deprecated','retire recipient','C2'],
      ['deprecatable','adj','Capable of being deprecated','retire,possible','C2'],
      ['deprecatible','adj','Able to be deprecated','retire,feasible','C2'],
      ['deprecative','adj','Tending to deprecate','retire,active','C1'],
      ['deprecating','adj','Currently deprecating','retire,ongoing','C1'],
      ['redeprecate','v','To deprecate again','retire again,repeat','C1'],
      ['undeprecate','v','To reverse deprecating','reverse,undo','C2'],
      ['overdeprecate','v','To deprecate excessively','excess,too much','C2'],
      ['underdeprecate','v','To deprecate insufficiently','insufficient,inadequate','C2'],
      ['misdeprecate','v','To deprecate incorrectly','wrongly,incorrectly','C2'],
      ['predeprecate','v','To deprecate beforehand','before,in advance','C2'],
      ['codeprecate','v','To deprecate together','jointly,together','C2'],
      ['redeprecatation','n','The act of deprecating again','re-retire','C2'],
      ['overdeprecatation','n','Excessive deprecating','excess retire','C2'],
      ['refactor','v','To restructure code without changing behaviour','restructure,reorganize,clean up','C1'],
      ['refactoration','n','The act of refactoring','restructure process','C1'],
      ['refactorment','n','The result of refactoring','restructure outcome','C1'],
      ['refactorance','n','The state of refactoring','restructure state','C1'],
      ['refactorence','n','The quality of refactoring','restructure quality','C1'],
      ['refactoral','n','An act of refactoring','restructure event','C2'],
      ['refactorer','n','One who refactors','restructure person','C1'],
      ['refactoror','n','One who refactors','restructure agent','C1'],
      ['refactoree','n','One who is refactord','restructure recipient','C2'],
      ['refactorable','adj','Capable of being refactord','restructure,possible','C2'],
      ['refactorible','adj','Able to be refactord','restructure,feasible','C2'],
      ['refactorive','adj','Tending to refactor','restructure,active','C1'],
      ['refactoring','adj','Currently refactoring','restructure,ongoing','C1'],
      ['refactored','adj','Having been refactord','restructure,completed','C1'],
      ['rerefactor','v','To refactor again','restructure again,repeat','C1'],
      ['unrefactor','v','To reverse refactoring','reverse,undo','C2'],
      ['overrefactor','v','To refactor excessively','excess,too much','C2'],
      ['underrefactor','v','To refactor insufficiently','insufficient,inadequate','C2'],
      ['misrefactor','v','To refactor incorrectly','wrongly,incorrectly','C2'],
      ['prerefactor','v','To refactor beforehand','before,in advance','C2'],
      ['corefactor','v','To refactor together','jointly,together','C2'],
      ['rerefactoration','n','The act of refactoring again','re-restructure','C2'],
      ['overrefactoration','n','Excessive refactoring','excess restructure','C2'],
      ['serialize','v','To convert data to a sequential format','encode,format,convert','C1'],
      ['serialization','n','The act of serializing','encode process','C1'],
      ['serializment','n','The result of serializing','encode outcome','C1'],
      ['serializance','n','The state of serializing','encode state','C1'],
      ['serializence','n','The quality of serializing','encode quality','C1'],
      ['serializal','n','An act of serializing','encode event','C2'],
      ['serializer','n','One who serializes','encode person','C1'],
      ['serializor','n','One who serializes','encode agent','C1'],
      ['serializee','n','One who is serialized','encode recipient','C2'],
      ['serializable','adj','Capable of being serialized','encode,possible','C2'],
      ['serializible','adj','Able to be serialized','encode,feasible','C2'],
      ['serializive','adj','Tending to serialize','encode,active','C1'],
      ['serializing','adj','Currently serializing','encode,ongoing','C1'],
      ['serialized','adj','Having been serialized','encode,completed','C1'],
      ['reserialize','v','To serialize again','encode again,repeat','C1'],
      ['unserialize','v','To reverse serializing','reverse,undo','C2'],
      ['overserialize','v','To serialize excessively','excess,too much','C2'],
      ['underserialize','v','To serialize insufficiently','insufficient,inadequate','C2'],
      ['misserialize','v','To serialize incorrectly','wrongly,incorrectly','C2'],
      ['preserialize','v','To serialize beforehand','before,in advance','C2'],
      ['coserialize','v','To serialize together','jointly,together','C2'],
      ['reserialization','n','The act of serializing again','re-encode','C2'],
      ['overserialization','n','Excessive serializing','excess encode','C2'],
      ['authenticatment','n','The result of authenticating','verify outcome','B2'],
      ['authenticatance','n','The state of authenticating','verify state','B2'],
      ['authenticatence','n','The quality of authenticating','verify quality','B2'],
      ['authenticatal','n','An act of authenticating','verify event','C1'],
      ['authenticator','n','One who authenticates','verify agent','B2'],
      ['authenticatee','n','One who is authenticated','verify recipient','C1'],
      ['authenticatible','adj','Able to be authenticated','verify,feasible','C1'],
      ['authenticative','adj','Tending to authenticate','verify,active','B2'],
      ['authenticated','adj','Having been authenticated','verify,completed','B2'],
      ['reauthenticate','v','To authenticate again','verify again,repeat','B2'],
      ['unauthenticate','v','To reverse authenticating','reverse,undo','C1'],
      ['overauthenticate','v','To authenticate excessively','excess,too much','C1'],
      ['underauthenticate','v','To authenticate insufficiently','insufficient,inadequate','C1'],
      ['misauthenticate','v','To authenticate incorrectly','wrongly,incorrectly','C1'],
      ['preauthenticate','v','To authenticate beforehand','before,in advance','C1'],
      ['coauthenticate','v','To authenticate together','jointly,together','C1'],
      ['reauthenticatation','n','The act of authenticating again','re-verify','C1'],
      ['overauthenticatation','n','Excessive authenticating','excess verify','C1'],
      ['obfuscatation','n','The act of obfuscating','obscure process','C1'],
      ['obfuscatment','n','The result of obfuscating','obscure outcome','C1'],
      ['obfuscatance','n','The state of obfuscating','obscure state','C1'],
      ['obfuscatence','n','The quality of obfuscating','obscure quality','C1'],
      ['obfuscatal','n','An act of obfuscating','obscure event','C2'],
      ['obfuscater','n','One who obfuscates','obscure person','C1'],
      ['obfuscator','n','One who obfuscates','obscure agent','C1'],
      ['obfuscatee','n','One who is obfuscated','obscure recipient','C2'],
      ['obfuscatable','adj','Capable of being obfuscated','obscure,possible','C2'],
      ['obfuscatible','adj','Able to be obfuscated','obscure,feasible','C2'],
      ['obfuscative','adj','Tending to obfuscate','obscure,active','C1'],
      ['obfuscating','adj','Currently obfuscating','obscure,ongoing','C1'],
      ['obfuscated','adj','Having been obfuscated','obscure,completed','C1'],
      ['reobfuscate','v','To obfuscate again','obscure again,repeat','C1'],
      ['unobfuscate','v','To reverse obfuscating','reverse,undo','C2'],
      ['overobfuscate','v','To obfuscate excessively','excess,too much','C2'],
      ['underobfuscate','v','To obfuscate insufficiently','insufficient,inadequate','C2'],
      ['misobfuscate','v','To obfuscate incorrectly','wrongly,incorrectly','C2'],
      ['preobfuscate','v','To obfuscate beforehand','before,in advance','C2'],
      ['coobfuscate','v','To obfuscate together','jointly,together','C2'],
      ['reobfuscatation','n','The act of obfuscating again','re-obscure','C2'],
      ['overobfuscatation','n','Excessive obfuscating','excess obscure','C2'],
      ['concatenatation','n','The act of concatenating','join process','C1'],
      ['concatenatment','n','The result of concatenating','join outcome','C1'],
      ['concatenatance','n','The state of concatenating','join state','C1'],
      ['concatenatence','n','The quality of concatenating','join quality','C1'],
      ['concatenatal','n','An act of concatenating','join event','C2'],
      ['concatenater','n','One who concatenates','join person','C1'],
      ['concatenator','n','One who concatenates','join agent','C1'],
      ['concatenatee','n','One who is concatenated','join recipient','C2'],
      ['concatenatable','adj','Capable of being concatenated','join,possible','C2'],
      ['concatenatible','adj','Able to be concatenated','join,feasible','C2'],
      ['concatenative','adj','Tending to concatenate','join,active','C1'],
      ['concatenating','adj','Currently concatenating','join,ongoing','C1'],
      ['concatenated','adj','Having been concatenated','join,completed','C1'],
      ['reconcatenate','v','To concatenate again','join again,repeat','C1'],
      ['unconcatenate','v','To reverse concatenating','reverse,undo','C2'],
      ['overconcatenate','v','To concatenate excessively','excess,too much','C2'],
      ['underconcatenate','v','To concatenate insufficiently','insufficient,inadequate','C2'],
      ['misconcatenate','v','To concatenate incorrectly','wrongly,incorrectly','C2'],
      ['preconcatenate','v','To concatenate beforehand','before,in advance','C2'],
      ['coconcatenate','v','To concatenate together','jointly,together','C2'],
      ['reconcatenatation','n','The act of concatenating again','re-join','C2'],
      ['overconcatenatation','n','Excessive concatenating','excess join','C2'],
    ],
    health: [
      ['diagnosment','n','The result of diagnosing','identify outcome','B1'],
      ['diagnosance','n','The state of diagnosing','identify state','B1'],
      ['diagnosence','n','The quality of diagnosing','identify quality','B1'],
      ['diagnosal','n','An act of diagnosing','identify event','B2'],
      ['diagnosor','n','One who diagnoses','identify agent','B1'],
      ['diagnosee','n','One who is diagnosed','identify recipient','B2'],
      ['diagnosible','adj','Able to be diagnosed','identify,feasible','B2'],
      ['diagnosive','adj','Tending to diagnose','identify,active','B1'],
      ['diagnosed','adj','Having been diagnosed','identify,completed','B1'],
      ['rediagnose','v','To diagnose again','identify again,repeat','B1'],
      ['undiagnose','v','To reverse diagnosing','reverse,undo','B2'],
      ['overdiagnose','v','To diagnose excessively','excess,too much','B2'],
      ['underdiagnose','v','To diagnose insufficiently','insufficient,inadequate','B2'],
      ['misdiagnose','v','To diagnose incorrectly','wrongly,incorrectly','B2'],
      ['prediagnose','v','To diagnose beforehand','before,in advance','B2'],
      ['codiagnose','v','To diagnose together','jointly,together','B2'],
      ['rediagnosation','n','The act of diagnosing again','re-identify','B2'],
      ['overdiagnosation','n','Excessive diagnosing','excess identify','B2'],
      ['prescribation','n','The act of prescribing','recommend process','B2'],
      ['prescribment','n','The result of prescribing','recommend outcome','B2'],
      ['prescribance','n','The state of prescribing','recommend state','B2'],
    ],
  },
  collocations: {}
};
