module.exports = {
  vocab: {
    psychology: [
    ['happyness','n','The quality of being happy','joyful quality','B1'],
    ['unhappy','adj','Not happy','not joyful','A2'],
    ['sadly','adv','In a sad manner','unhappy way','A2'],
    ['sadness','n','The quality of being sad','unhappy quality','B1'],
    ['unsad','adj','Not sad','not unhappy','A2'],
    ['angrily','adv','In a angry manner','furious way','A2'],
    ['angryness','n','The quality of being angry','furious quality','B1'],
    ['unangry','adj','Not angry','not furious','A2'],
    ['afraidly','adv','In a afraid manner','scared way','A2'],
    ['afraidness','n','The quality of being afraid','scared quality','B1'],
    ['unafraid','adj','Not afraid','not scared','A2'],
    ['thinkation','n','The act or process of thinking','reflect process,ponder process,contemplate process','A2'],
    ['thinker','n','A person who thinks','reflect person,ponder person,contemplate person','B1'],
    ['thinkable','adj','Able to be thinkd','reflect,possible','B1'],
    ['thinking','n','The process of thinking something','reflect activity','A2'],
    ['feelation','n','The act or process of feeling','sense process,perceive process,experience process','A2'],
    ['feeler','n','A person who feels','sense person,perceive person,experience person','B1'],
    ['feelable','adj','Able to be feeld','sense,possible','B1'],
    ['behavioural','adj','Relating to behaviour','conduct-related','B1'],
    ['personalityal','adj','Relating to personality','character-related','B1'],
    ['emotional','adj','Relating to emotion','feeling-related','B1'],
    ['memoryal','adj','Relating to memory','recall-related','B1'],
    ['stressal','adj','Relating to stress','pressure-related','B1'],
    ['anxietyal','adj','Relating to anxiety','worry-related','B1'],
    ['confidenceal','adj','Relating to confidence','self-belief-related','B1'],
    ['subconsciously','adv','In a subconscious manner','unconscious way','B2'],
    ['subconsciousness','n','The quality of being subconscious','unconscious quality','C1'],
    ['unsubconscious','adj','Not subconscious','not unconscious','B2'],
    ['resilienceal','adj','Relating to resilience','toughness-related','B2'],
    ['empathyal','adj','Relating to empathy','compassion-related','B2'],
    ['conditioningal','adj','Relating to conditioning','training-related','B2'],
    ['neuroplasticityal','adj','Relating to neuroplasticity','brain adaptability-related','B2'],
    ['psychoanalysisal','adj','Relating to psychoanalysis','therapy-related','C1'],
    ['heuristical','adj','Relating to heuristic','rule of thumb-related','C1'],
    ['alexithymiaal','adj','Relating to alexithymia','emotional blindness-related','C2'],
    ['anhedoniaal','adj','Relating to anhedonia','pleasure deficit-related','C2'],
    ['dreamal','adj','Relating to dream','vision-related','A2'],
    ['habital','adj','Relating to habit','routine-related','A2'],
    ['moodal','adj','Relating to mood','emotion-related','A2'],
    ['phobiaal','adj','Relating to phobia','terror-related','B1'],
    ['addictional','adj','Relating to addiction','dependency-related','B1'],
    ['introvertal','adj','Relating to introvert','loner-related','B1'],
    ['extrovertal','adj','Relating to extrovert','outgoing person-related','B1'],
    ['traumaal','adj','Relating to trauma','shock-related','B2'],
    ['narcissismal','adj','Relating to narcissism','self-love-related','B2'],
    ['psychopathal','adj','Relating to psychopath','sociopath-related','B2'],
    ['catharsisal','adj','Relating to catharsis','emotional release-related','C1'],
    ['sublimational','adj','Relating to sublimation','redirection-related','C1'],
    ['transferenceal','adj','Relating to transference','emotional projection-related','C1'],
    ['primingal','adj','Relating to priming','influence-related','C1'],
    ['limbicly','adv','In a limbic manner','emotion-controlling way','C1'],
    ['limbicness','n','The quality of being limbic','emotion-controlling quality','C2'],
    ['unlimbic','adj','Not limbic','not emotion-controlling','C1'],
    ['somatoformly','adv','In a somatoform manner','psychogenic way','C2'],
    ['somatoformness','n','The quality of being somatoform','psychogenic quality','C2'],
    ['unsomatoform','adj','Not somatoform','not psychogenic','C2'],
    ['thanatophobiaal','adj','Relating to thanatophobia','death anxiety-related','C2'],
    ['confabulational','adj','Relating to confabulation','false memory-related','C2'],
    ['projectively','adv','In a projective manner','interpretive way','C1'],
    ['projectiveness','n','The quality of being projective','interpretive quality','C2'],
    ['unprojective','adj','Not projective','not interpretive','C1'],
    ['desensitisational','adj','Relating to desensitisation','habituation-related','B2']
    ],
    arts: [
    ['painting','n','A picture made with paint','artwork,canvas,portrait','A2'],
    ['minimalism','n','An art style using simple forms','simplicity,reduction,bare essentials','B2'],
    ['trompe-l-oeil','n','Art creating an illusion of three dimensions','optical illusion,visual trick','C2'],
    ['pointillism','n','Painting using small dots of colour','dot painting,divisionism','C1'],
    ['wabi-sabi','n','Japanese aesthetic of imperfect beauty','imperfection beauty,natural beauty','C2'],
    ['gouache','n','A type of opaque watercolour paint','body colour,opaque paint','C1'],
    ['lithography','n','A printing process using stone or metal','stone printing,planographic printing','C1'],
    ['paintingal','adj','Relating to painting','artwork-related','A2'],
    ['sculptureal','adj','Relating to sculpture','statue-related','A2'],
    ['theatreal','adj','Relating to theatre','playhouse-related','A2'],
    ['filmal','adj','Relating to film','movie-related','A2'],
    ['singation','n','The act or process of singing','chant process,vocalise process,croon process','A2'],
    ['singable','adj','Able to be singd','chant,possible','B1'],
    ['singing','n','The process of singing something','chant activity','A2'],
    ['photographal','adj','Relating to photograph','photo-related','A2'],
    ['galleryal','adj','Relating to gallery','exhibition space-related','B1'],
    ['exhibitional','adj','Relating to exhibition','show-related','B1'],
    ['composeral','adj','Relating to composer','musician-related','B1'],
    ['masterpieceal','adj','Relating to masterpiece','magnum opus-related','B1'],
    ['abstractly','adv','In a abstract manner','non-figurative way','B1'],
    ['abstractness','n','The quality of being abstract','non-figurative quality','B2'],
    ['unabstract','adj','Not abstract','not non-figurative','B1'],
    ['contemporarily','adv','In a contemporary manner','modern way','B1'],
    ['contemporaryness','n','The quality of being contemporary','modern quality','B2'],
    ['uncontemporary','adj','Not contemporary','not modern','B1'],
    ['aestheticsal','adj','Relating to aesthetics','beauty theory-related','B2'],
    ['avant-gardely','adv','In a avant-garde manner','innovative way','B2'],
    ['avant-gardeness','n','The quality of being avant-garde','innovative quality','C1'],
    ['unavant-garde','adj','Not avant-garde','not innovative','B2'],
    ['genreal','adj','Relating to genre','type-related','B2'],
    ['patronal','adj','Relating to patron','sponsor-related','B2'],
    ['curatoral','adj','Relating to curator','custodian-related','B2'],
    ['renaissanceal','adj','Relating to renaissance','rebirth-related','B2'],
    ['minimalismal','adj','Relating to minimalism','simplicity-related','B2'],
    ['chiaroscuroal','adj','Relating to chiaroscuro','light-dark-related','C1'],
    ['pasticheal','adj','Relating to pastiche','imitation-related','C1'],
    ['verisimilitudeal','adj','Relating to verisimilitude','realism-related','C1'],
    ['sfumatoal','adj','Relating to sfumato','hazy blending-related','C2'],
    ['sketchal','adj','Relating to sketch','draft-related','A2'],
    ['museumal','adj','Relating to museum','gallery-related','A2'],
    ['concertal','adj','Relating to concert','gig-related','A2'],
    ['portraital','adj','Relating to portrait','likeness-related','B1'],
    ['landscapeal','adj','Relating to landscape','countryside view-related','B1'],
    ['rehearsalal','adj','Relating to rehearsal','practice-related','B1'],
    ['choreographyal','adj','Relating to choreography','dance composition-related','B2'],
    ['frescoal','adj','Relating to fresco','wall painting-related','B2'],
    ['baroquely','adv','In a baroque manner','elaborate way','B2'],
    ['baroqueness','n','The quality of being baroque','elaborate quality','C1'],
    ['unbaroque','adj','Not baroque','not elaborate','B2'],
    ['surrealismal','adj','Relating to surrealism','dream art-related','B2'],
    ['impressionismal','adj','Relating to impressionism','light painting-related','B2'],
    ['pointillismal','adj','Relating to pointillism','dot painting-related','C1'],
    ['iconographyal','adj','Relating to iconography','symbol analysis-related','C1'],
    ['ekphrasisal','adj','Relating to ekphrasis','art description-related','C2'],
    ['polyptychal','adj','Relating to polyptych','multi-panel artwork-related','C2'],
    ['gouacheal','adj','Relating to gouache','body colour-related','C1'],
    ['lithographyal','adj','Relating to lithography','stone printing-related','C1'],
    ['patinaal','adj','Relating to patina','ageing-related','C1']
    ],
    sports: [
    ['tactic','n','A planned approach to win a game','strategy,manoeuvre,plan','B1'],
    ['physiology','n','The study of how the body functions','body science,biological function','B2'],
    ['periodisation','n','Structured training in cycles','training phases,planned progression','C1'],
    ['ergometer','n','A device measuring physical exertion','rowing machine,exercise measurer','C1'],
    ['isometric','adj','Exercise without joint movement','static,stationary,holding','C1'],
    ['velodrome','n','A track for bicycle racing','cycling arena,bike track','C1'],
    ['parkour','n','Moving through urban spaces acrobatically','free running,urban gymnastics','B2'],
    ['bouldering','n','Climbing without ropes on low rocks','rock climbing,wall climbing','B2'],
    ['heptathlon','n','An athletic contest of seven events','seven-event contest,multi-sport','C1'],
    ['peloton','n','The main group of cyclists in a race','pack,bunch,group','C1'],
    ['teamal','adj','Relating to team','squad-related','A2'],
    ['matchal','adj','Relating to match','game-related','A2'],
    ['wination','n','The act or process of wining','triumph process,succeed process,prevail process','A2'],
    ['winer','n','A person who wins','triumph person,succeed person,prevail person','B1'],
    ['winable','adj','Able to be wind','triumph,possible','B1'],
    ['wining','n','The process of wining something','triumph activity','A2'],
    ['losation','n','The act or process of losing','be defeated process,fall process,fail process','A2'],
    ['loser','n','A person who loses','be defeated person,fall person,fail person','B1'],
    ['losable','adj','Able to be losed','be defeated,possible','B1'],
    ['losing','n','The process of losing something','be defeated activity','A2'],
    ['scoreal','adj','Relating to score','result-related','A2'],
    ['practication','n','The act or process of practicing','train process,drill process,exercise process','A2']
    ],
  },
  collocations: {
  }
};
