// Auto-generated vocab boost group 65
module.exports = {
  vocab: {
    travel: [
      ['hospitablely','adv','In a hospitable manner','welcoming way','B2'],
      ['hospitableness','n','The quality of being hospitable','welcoming quality','B2'],
      ['hospitableity','n','The state of being hospitable','welcoming condition','C1'],
      ['unhospitable','adj','Not hospitable','not welcoming','B2'],
      ['inhospitable','adj','Not hospitable','not welcoming','C1'],
      ['nonhospitable','adj','Not hospitable','not welcoming','B2'],
      ['semihospitable','adj','Partially hospitable','partly welcoming','C1'],
      ['overhospitable','adj','Excessively hospitable','too welcoming','C1'],
      ['ultrahospitable','adj','Extremely hospitable','very welcoming','C1'],
      ['intercontinental','adj','Connecting or between continents','cross-continental,transcontinental','B2'],
      ['intercontinentally','adv','In a intercontinental manner','cross-continental way','B2'],
      ['intercontinentalness','n','The quality of being intercontinental','cross-continental quality','B2'],
      ['intercontinentality','n','The state of being intercontinental','cross-continental condition','C1'],
      ['unintercontinental','adj','Not intercontinental','not cross-continental','B2'],
      ['inintercontinental','adj','Not intercontinental','not cross-continental','C1'],
      ['nonintercontinental','adj','Not intercontinental','not cross-continental','B2'],
      ['semiintercontinental','adj','Partially intercontinental','partly cross-continental','C1'],
      ['overintercontinental','adj','Excessively intercontinental','too cross-continental','C1'],
      ['ultraintercontinental','adj','Extremely intercontinental','very cross-continental','C1'],
      ['transatlantic','adj','Crossing the Atlantic Ocean','overseas,cross-ocean,international','B2'],
      ['transatlanticly','adv','In a transatlantic manner','overseas way','B2'],
      ['transatlanticness','n','The quality of being transatlantic','overseas quality','B2'],
      ['transatlanticity','n','The state of being transatlantic','overseas condition','C1'],
      ['untransatlantic','adj','Not transatlantic','not overseas','B2'],
      ['intransatlantic','adj','Not transatlantic','not overseas','C1'],
      ['nontransatlantic','adj','Not transatlantic','not overseas','B2'],
      ['semitransatlantic','adj','Partially transatlantic','partly overseas','C1'],
      ['overtransatlantic','adj','Excessively transatlantic','too overseas','C1'],
      ['ultratransatlantic','adj','Extremely transatlantic','very overseas','C1'],
      ['terrestrial','adj','Relating to the earth or land','land-based,earthly,ground','C1'],
      ['terrestrially','adv','In a terrestrial manner','land-based way','C1'],
      ['terrestrialness','n','The quality of being terrestrial','land-based quality','C1'],
      ['terrestriality','n','The state of being terrestrial','land-based condition','C2'],
      ['unterrestrial','adj','Not terrestrial','not land-based','C1'],
      ['interrestrial','adj','Not terrestrial','not land-based','C2'],
      ['nonterrestrial','adj','Not terrestrial','not land-based','C1'],
      ['semiterrestrial','adj','Partially terrestrial','partly land-based','C2'],
      ['overterrestrial','adj','Excessively terrestrial','too land-based','C2'],
      ['ultraterrestrial','adj','Extremely terrestrial','very land-based','C2'],
      ['nautical','adj','Relating to sailors or navigation','maritime,marine,seafaring','C1'],
      ['nautically','adv','In a nautical manner','maritime way','C1'],
      ['nauticalness','n','The quality of being nautical','maritime quality','C1'],
      ['nauticality','n','The state of being nautical','maritime condition','C2'],
      ['unnautical','adj','Not nautical','not maritime','C1'],
      ['innautical','adj','Not nautical','not maritime','C2'],
      ['nonnautical','adj','Not nautical','not maritime','C1'],
      ['seminautical','adj','Partially nautical','partly maritime','C2'],
      ['overnautical','adj','Excessively nautical','too maritime','C2'],
      ['ultranautical','adj','Extremely nautical','very maritime','C2'],
      ['peripateticity','n','The state of being peripatetic','wandering condition','C2'],
      ['inperipatetic','adj','Not peripatetic','not wandering','C2'],
      ['nonperipatetic','adj','Not peripatetic','not wandering','C1'],
      ['semiperipatetic','adj','Partially peripatetic','partly wandering','C2'],
      ['overperipatetic','adj','Excessively peripatetic','too wandering','C2'],
      ['ultraperipatetic','adj','Extremely peripatetic','very wandering','C2'],
      ['intrepidly','adv','In a intrepid manner','brave way','C1'],
      ['intrepidness','n','The quality of being intrepid','brave quality','C1'],
      ['intrepidity','n','The state of being intrepid','brave condition','C2'],
      ['unintrepid','adj','Not intrepid','not brave','C1'],
      ['inintrepid','adj','Not intrepid','not brave','C2'],
      ['nonintrepid','adj','Not intrepid','not brave','C1'],
      ['semiintrepid','adj','Partially intrepid','partly brave','C2'],
      ['overintrepid','adj','Excessively intrepid','too brave','C2'],
      ['ultraintrepid','adj','Extremely intrepid','very brave','C2'],
      ['sightseeingal','adj','Relating to sightseeing','touring-related,pertaining to','B1'],
      ['sightseeingic','adj','Of or relating to sightseeing','touring-based,characteristic','B1'],
      ['sightseeingous','adj','Full of sightseeing','touring-filled,abundant','B2'],
      ['sightseeingful','adj','Full of sightseeing','touring-rich,abounding','B1'],
      ['sightseeingless','adj','Without sightseeing','lacking,without','B1'],
      ['sightseeingism','n','The ideology of sightseeing','touring ideology,doctrine','B2'],
      ['sightseeingist','n','A person focused on sightseeing','touring specialist,advocate','B2'],
      ['sightseeingise','v','To make into sightseeing','touring,convert','B2'],
      ['sightseeingize','v','To make or become sightseeing','touring,transform','B2'],
      ['antisightseeing','adj','Opposed to sightseeing','against,opposing','B2'],
      ['nonsightseeing','adj','Not involving sightseeing','without,lacking','B1'],
      ['presightseeing','n','Before sightseeing','preceding,prior','B2'],
      ['postsightseeing','n','After sightseeing','following,subsequent','B2'],
      ['subsightseeing','n','A subdivision of sightseeing','subset,branch','B2'],
      ['multisightseeing','adj','Involving many sightseeings','multiple,several','B2'],
      ['intersightseeing','adj','Between sightseeings','cross,between','B2'],
      ['layoveric','adj','Of or relating to layover','stopover-based,characteristic','B2'],
      ['layoverous','adj','Full of layover','stopover-filled,abundant','C1'],
      ['layoverful','adj','Full of layover','stopover-rich,abounding','B2'],
      ['layoverless','adj','Without layover','lacking,without','B2'],
      ['layoverism','n','The ideology of layover','stopover ideology,doctrine','C1'],
      ['layoverist','n','A person focused on layover','stopover specialist,advocate','C1'],
      ['layoverise','v','To make into layover','stopover,convert','C1'],
      ['layoverize','v','To make or become layover','stopover,transform','C1'],
      ['antilayover','adj','Opposed to layover','against,opposing','C1'],
      ['nonlayover','adj','Not involving layover','without,lacking','B2'],
      ['prelayover','n','Before layover','preceding,prior','C1'],
      ['postlayover','n','After layover','following,subsequent','C1'],
      ['sublayover','n','A subdivision of layover','subset,branch','C1'],
      ['multilayover','adj','Involving many layovers','multiple,several','C1'],
      ['interlayover','adj','Between layovers','cross,between','C1'],
      ['visaic','adj','Of or relating to visa','entry permit-based,characteristic','B1'],
      ['visaous','adj','Full of visa','entry permit-filled,abundant','B2'],
      ['visaful','adj','Full of visa','entry permit-rich,abounding','B1'],
      ['visaless','adj','Without visa','lacking,without','B1'],
      ['visaism','n','The ideology of visa','entry permit ideology,doctrine','B2'],
      ['visaist','n','A person focused on visa','entry permit specialist,advocate','B2'],
      ['visaise','v','To make into visa','entry permit,convert','B2'],
      ['visaize','v','To make or become visa','entry permit,transform','B2'],
      ['antivisa','adj','Opposed to visa','against,opposing','B2'],
      ['nonvisa','adj','Not involving visa','without,lacking','B1'],
      ['previsa','n','Before visa','preceding,prior','B2'],
      ['postvisa','n','After visa','following,subsequent','B2'],
      ['subvisa','n','A subdivision of visa','subset,branch','B2'],
      ['multivisa','adj','Involving many visas','multiple,several','B2'],
      ['intervisa','adj','Between visas','cross,between','B2'],
      ['documentation','n','Official papers needed for travel','papers,credentials,records','B2'],
      ['documentational','adj','Relating to documentation','papers-related,pertaining to','B2'],
      ['documentationic','adj','Of or relating to documentation','papers-based,characteristic','B2'],
      ['documentationous','adj','Full of documentation','papers-filled,abundant','C1'],
      ['documentationful','adj','Full of documentation','papers-rich,abounding','B2'],
      ['documentationless','adj','Without documentation','lacking,without','B2'],
      ['documentationism','n','The ideology of documentation','papers ideology,doctrine','C1'],
      ['documentationist','n','A person focused on documentation','papers specialist,advocate','C1'],
      ['documentationise','v','To make into documentation','papers,convert','C1'],
      ['documentationize','v','To make or become documentation','papers,transform','C1'],
      ['antidocumentation','adj','Opposed to documentation','against,opposing','C1'],
      ['nondocumentation','adj','Not involving documentation','without,lacking','B2'],
      ['predocumentation','n','Before documentation','preceding,prior','C1'],
      ['postdocumentation','n','After documentation','following,subsequent','C1'],
      ['subdocumentation','n','A subdivision of documentation','subset,branch','C1'],
      ['multidocumentation','adj','Involving many documentations','multiple,several','C1'],
      ['interdocumentation','adj','Between documentations','cross,between','C1'],
      ['accommodationic','adj','Of or relating to accommodation','lodging-based,characteristic','B1'],
      ['accommodationous','adj','Full of accommodation','lodging-filled,abundant','B2'],
      ['accommodationful','adj','Full of accommodation','lodging-rich,abounding','B1'],
      ['accommodationless','adj','Without accommodation','lacking,without','B1'],
      ['accommodationism','n','The ideology of accommodation','lodging ideology,doctrine','B2'],
      ['accommodationist','n','A person focused on accommodation','lodging specialist,advocate','B2'],
      ['accommodationise','v','To make into accommodation','lodging,convert','B2'],
      ['accommodationize','v','To make or become accommodation','lodging,transform','B2'],
      ['antiaccommodation','adj','Opposed to accommodation','against,opposing','B2'],
      ['nonaccommodation','adj','Not involving accommodation','without,lacking','B1'],
      ['preaccommodation','n','Before accommodation','preceding,prior','B2'],
      ['postaccommodation','n','After accommodation','following,subsequent','B2'],
      ['subaccommodation','n','A subdivision of accommodation','subset,branch','B2'],
      ['multiaccommodation','adj','Involving many accommodations','multiple,several','B2'],
      ['interaccommodation','adj','Between accommodations','cross,between','B2'],
      ['departure lounge','n','An area for passengers before boarding','waiting area,gate area,terminal','B1'],
      ['departure loungeal','adj','Relating to departure lounge','waiting area-related,pertaining to','B1'],
      ['departure loungeic','adj','Of or relating to departure lounge','waiting area-based,characteristic','B1'],
      ['departure loungeous','adj','Full of departure lounge','waiting area-filled,abundant','B2'],
      ['departure loungeful','adj','Full of departure lounge','waiting area-rich,abounding','B1'],
      ['departure loungeless','adj','Without departure lounge','lacking,without','B1'],
      ['departure loungeism','n','The ideology of departure lounge','waiting area ideology,doctrine','B2'],
      ['departure loungeist','n','A person focused on departure lounge','waiting area specialist,advocate','B2'],
      ['departure loungeise','v','To make into departure lounge','waiting area,convert','B2'],
      ['departure loungeize','v','To make or become departure lounge','waiting area,transform','B2'],
      ['antideparture lounge','adj','Opposed to departure lounge','against,opposing','B2'],
      ['nondeparture lounge','adj','Not involving departure lounge','without,lacking','B1'],
      ['predeparture lounge','n','Before departure lounge','preceding,prior','B2'],
      ['postdeparture lounge','n','After departure lounge','following,subsequent','B2'],
      ['subdeparture lounge','n','A subdivision of departure lounge','subset,branch','B2'],
      ['multideparture lounge','adj','Involving many departure lounges','multiple,several','B2'],
      ['interdeparture lounge','adj','Between departure lounges','cross,between','B2'],
      ['jet lagal','adj','Relating to jet lag','time zone fatigue-related,pertaining to','B1'],
      ['jet lagic','adj','Of or relating to jet lag','time zone fatigue-based,characteristic','B1'],
      ['jet lagous','adj','Full of jet lag','time zone fatigue-filled,abundant','B2'],
      ['jet lagful','adj','Full of jet lag','time zone fatigue-rich,abounding','B1'],
      ['jet lagless','adj','Without jet lag','lacking,without','B1'],
      ['jet lagism','n','The ideology of jet lag','time zone fatigue ideology,doctrine','B2'],
      ['jet lagist','n','A person focused on jet lag','time zone fatigue specialist,advocate','B2'],
      ['jet lagise','v','To make into jet lag','time zone fatigue,convert','B2'],
      ['jet lagize','v','To make or become jet lag','time zone fatigue,transform','B2'],
      ['antijet lag','adj','Opposed to jet lag','against,opposing','B2'],
      ['nonjet lag','adj','Not involving jet lag','without,lacking','B1'],
      ['prejet lag','n','Before jet lag','preceding,prior','B2'],
      ['postjet lag','n','After jet lag','following,subsequent','B2'],
      ['subjet lag','n','A subdivision of jet lag','subset,branch','B2'],
      ['multijet lag','adj','Involving many jet lags','multiple,several','B2'],
      ['interjet lag','adj','Between jet lags','cross,between','B2'],
      ['charter flight','n','A flight hired for a specific group','private flight,hired aircraft','B2'],
      ['charter flightal','adj','Relating to charter flight','private flight-related,pertaining to','B2'],
      ['charter flightic','adj','Of or relating to charter flight','private flight-based,characteristic','B2'],
      ['charter flightous','adj','Full of charter flight','private flight-filled,abundant','C1'],
      ['charter flightful','adj','Full of charter flight','private flight-rich,abounding','B2'],
      ['charter flightless','adj','Without charter flight','lacking,without','B2'],
      ['charter flightism','n','The ideology of charter flight','private flight ideology,doctrine','C1'],
      ['charter flightist','n','A person focused on charter flight','private flight specialist,advocate','C1'],
      ['charter flightise','v','To make into charter flight','private flight,convert','C1'],
      ['charter flightize','v','To make or become charter flight','private flight,transform','C1'],
      ['anticharter flight','adj','Opposed to charter flight','against,opposing','C1'],
      ['noncharter flight','adj','Not involving charter flight','without,lacking','B2'],
      ['precharter flight','n','Before charter flight','preceding,prior','C1'],
      ['postcharter flight','n','After charter flight','following,subsequent','C1'],
      ['subcharter flight','n','A subdivision of charter flight','subset,branch','C1'],
      ['multicharter flight','adj','Involving many charter flights','multiple,several','C1'],
      ['intercharter flight','adj','Between charter flights','cross,between','C1'],
    ],
    government: [
      ['legislatation','n','The act of legislating','enact process','B2'],
      ['legislatment','n','The result of legislating','enact outcome','B2'],
      ['legislatance','n','The state of legislating','enact state','B2'],
      ['legislatence','n','The quality of legislating','enact quality','B2'],
      ['legislatal','n','An act of legislating','enact event','C1'],
      ['legislater','n','One who legislates','enact person','B2'],
      ['legislator','n','One who legislates','enact agent','B2'],
      ['legislatee','n','One who is legislated','enact recipient','C1'],
      ['legislatable','adj','Capable of being legislated','enact,possible','C1'],
      ['legislatible','adj','Able to be legislated','enact,feasible','C1'],
      ['legislative','adj','Tending to legislate','enact,active','B2'],
      ['legislating','adj','Currently legislating','enact,ongoing','B2'],
      ['legislated','adj','Having been legislated','enact,completed','B2'],
      ['relegislate','v','To legislate again','enact again,repeat','B2'],
      ['unlegislate','v','To reverse legislating','reverse,undo','C1'],
      ['overlegislate','v','To legislate excessively','excess,too much','C1'],
      ['underlegislate','v','To legislate insufficiently','insufficient,inadequate','C1'],
      ['mislegislate','v','To legislate incorrectly','wrongly,incorrectly','C1'],
      ['prelegislate','v','To legislate beforehand','before,in advance','C1'],
      ['colegislate','v','To legislate together','jointly,together','C1'],
      ['relegislatation','n','The act of legislating again','re-enact','C1'],
      ['overlegislatation','n','Excessive legislating','excess enact','C1'],
      ['ratifyation','n','The act of ratifying','approve process','C1'],
      ['ratifyment','n','The result of ratifying','approve outcome','C1'],
      ['ratifyance','n','The state of ratifying','approve state','C1'],
      ['ratifyence','n','The quality of ratifying','approve quality','C1'],
      ['ratifyal','n','An act of ratifying','approve event','C2'],
      ['ratifyer','n','One who ratifys','approve person','C1'],
      ['ratifyor','n','One who ratifys','approve agent','C1'],
      ['ratifyee','n','One who is ratifyd','approve recipient','C2'],
      ['ratifyable','adj','Capable of being ratifyd','approve,possible','C2'],
      ['ratifyible','adj','Able to be ratifyd','approve,feasible','C2'],
      ['ratifyive','adj','Tending to ratify','approve,active','C1'],
      ['ratifying','adj','Currently ratifying','approve,ongoing','C1'],
      ['ratifyed','adj','Having been ratifyd','approve,completed','C1'],
      ['reratify','v','To ratify again','approve again,repeat','C1'],
      ['unratify','v','To reverse ratifying','reverse,undo','C2'],
      ['overratify','v','To ratify excessively','excess,too much','C2'],
      ['underratify','v','To ratify insufficiently','insufficient,inadequate','C2'],
      ['misratify','v','To ratify incorrectly','wrongly,incorrectly','C2'],
      ['preratify','v','To ratify beforehand','before,in advance','C2'],
      ['coratify','v','To ratify together','jointly,together','C2'],
      ['reratifyation','n','The act of ratifying again','re-approve','C2'],
      ['overratifyation','n','Excessive ratifying','excess approve','C2'],
      ['vetoation','n','The act of vetoing','reject process','B2'],
      ['vetoment','n','The result of vetoing','reject outcome','B2'],
      ['vetoance','n','The state of vetoing','reject state','B2'],
      ['vetoence','n','The quality of vetoing','reject quality','B2'],
      ['vetoer','n','One who vetos','reject person','B2'],
      ['vetoor','n','One who vetos','reject agent','B2'],
      ['vetoee','n','One who is vetod','reject recipient','C1'],
      ['vetoable','adj','Capable of being vetod','reject,possible','C1'],
      ['vetoible','adj','Able to be vetod','reject,feasible','C1'],
      ['vetoive','adj','Tending to veto','reject,active','B2'],
      ['vetoing','adj','Currently vetoing','reject,ongoing','B2'],
      ['vetoed','adj','Having been vetod','reject,completed','B2'],
      ['reveto','v','To veto again','reject again,repeat','B2'],
      ['unveto','v','To reverse vetoing','reverse,undo','C1'],
    ],
  },
  collocations: {}
};
