// Auto-generated vocab boost group 54
module.exports = {
  vocab: {
    culture: [
      ['bohemianness','n','The quality of being bohemian','artistic quality','C1'],
      ['bohemianity','n','The state of being bohemian','artistic condition','C2'],
      ['unbohemian','adj','Not bohemian','not artistic','C1'],
      ['inbohemian','adj','Not bohemian','not artistic','C2'],
      ['nonbohemian','adj','Not bohemian','not artistic','C1'],
      ['semibohemian','adj','Partially bohemian','partly artistic','C2'],
      ['overbohemian','adj','Excessively bohemian','too artistic','C2'],
      ['ultrabohemian','adj','Extremely bohemian','very artistic','C2'],
      ['matrilineal','adj','Tracing descent through the mother','maternal,mother-based','C2'],
      ['matrilineally','adv','In a matrilineal manner','maternal way','C2'],
      ['matrilinealness','n','The quality of being matrilineal','maternal quality','C2'],
      ['matrilineality','n','The state of being matrilineal','maternal condition','C2'],
      ['unmatrilineal','adj','Not matrilineal','not maternal','C2'],
      ['inmatrilineal','adj','Not matrilineal','not maternal','C2'],
      ['nonmatrilineal','adj','Not matrilineal','not maternal','C2'],
      ['semimatrilineal','adj','Partially matrilineal','partly maternal','C2'],
      ['overmatrilineal','adj','Excessively matrilineal','too maternal','C2'],
      ['ultramatrilineal','adj','Extremely matrilineal','very maternal','C2'],
      ['patrilineality','n','The state of being patrilineal','paternal condition','C2'],
      ['inpatrilineal','adj','Not patrilineal','not paternal','C2'],
      ['nonpatrilineal','adj','Not patrilineal','not paternal','C2'],
      ['semipatrilineal','adj','Partially patrilineal','partly paternal','C2'],
      ['overpatrilineal','adj','Excessively patrilineal','too paternal','C2'],
      ['ultrapatrilineal','adj','Extremely patrilineal','very paternal','C2'],
      ['syncreticly','adv','In a syncretic manner','blended way','C2'],
      ['syncreticness','n','The quality of being syncretic','blended quality','C2'],
      ['syncreticity','n','The state of being syncretic','blended condition','C2'],
      ['unsyncretic','adj','Not syncretic','not blended','C2'],
      ['insyncretic','adj','Not syncretic','not blended','C2'],
      ['nonsyncretic','adj','Not syncretic','not blended','C2'],
      ['semisyncretic','adj','Partially syncretic','partly blended','C2'],
      ['oversyncretic','adj','Excessively syncretic','too blended','C2'],
      ['ultrasyncretic','adj','Extremely syncretic','very blended','C2'],
      ['ethnographicly','adv','In a ethnographic manner','cultural way','C1'],
      ['ethnographicness','n','The quality of being ethnographic','cultural quality','C1'],
      ['ethnographicity','n','The state of being ethnographic','cultural condition','C2'],
      ['unethnographic','adj','Not ethnographic','not cultural','C1'],
      ['inethnographic','adj','Not ethnographic','not cultural','C2'],
      ['nonethnographic','adj','Not ethnographic','not cultural','C1'],
      ['semiethnographic','adj','Partially ethnographic','partly cultural','C2'],
      ['overethnographic','adj','Excessively ethnographic','too cultural','C2'],
      ['ultraethnographic','adj','Extremely ethnographic','very cultural','C2'],
      ['totemic','adj','Relating to a spiritual emblem','symbolic,emblematic,sacred','C2'],
      ['totemicly','adv','In a totemic manner','symbolic way','C2'],
      ['totemicness','n','The quality of being totemic','symbolic quality','C2'],
      ['totemicity','n','The state of being totemic','symbolic condition','C2'],
      ['untotemic','adj','Not totemic','not symbolic','C2'],
      ['intotemic','adj','Not totemic','not symbolic','C2'],
      ['nontotemic','adj','Not totemic','not symbolic','C2'],
      ['semitotemic','adj','Partially totemic','partly symbolic','C2'],
      ['overtotemic','adj','Excessively totemic','too symbolic','C2'],
      ['ultratotemic','adj','Extremely totemic','very symbolic','C2'],
      ['aestheticly','adv','In a aesthetic manner','artistic way','B2'],
      ['aestheticness','n','The quality of being aesthetic','artistic quality','B2'],
      ['aestheticity','n','The state of being aesthetic','artistic condition','C1'],
      ['unaesthetic','adj','Not aesthetic','not artistic','B2'],
      ['inaesthetic','adj','Not aesthetic','not artistic','C1'],
      ['nonaesthetic','adj','Not aesthetic','not artistic','B2'],
      ['semiaesthetic','adj','Partially aesthetic','partly artistic','C1'],
      ['overaesthetic','adj','Excessively aesthetic','too artistic','C1'],
      ['ultraaesthetic','adj','Extremely aesthetic','very artistic','C1'],
      ['philharmonic','adj','Devoted to music','musical,orchestral,harmonic','C1'],
      ['philharmonicly','adv','In a philharmonic manner','musical way','C1'],
      ['philharmonicness','n','The quality of being philharmonic','musical quality','C1'],
      ['philharmonicity','n','The state of being philharmonic','musical condition','C2'],
      ['unphilharmonic','adj','Not philharmonic','not musical','C1'],
      ['inphilharmonic','adj','Not philharmonic','not musical','C2'],
      ['nonphilharmonic','adj','Not philharmonic','not musical','C1'],
      ['semiphilharmonic','adj','Partially philharmonic','partly musical','C2'],
      ['overphilharmonic','adj','Excessively philharmonic','too musical','C2'],
      ['ultraphilharmonic','adj','Extremely philharmonic','very musical','C2'],
      ['nomadicly','adv','In a nomadic manner','wandering way','B2'],
      ['nomadicness','n','The quality of being nomadic','wandering quality','B2'],
      ['nomadicity','n','The state of being nomadic','wandering condition','C1'],
      ['unnomadic','adj','Not nomadic','not wandering','B2'],
      ['innomadic','adj','Not nomadic','not wandering','C1'],
      ['nonnomadic','adj','Not nomadic','not wandering','B2'],
      ['seminomadic','adj','Partially nomadic','partly wandering','C1'],
      ['overnomadic','adj','Excessively nomadic','too wandering','C1'],
      ['ultranomadic','adj','Extremely nomadic','very wandering','C1'],
      ['pastoral','adj','Relating to rural life','rural,countryside,bucolic','C1'],
      ['pastorally','adv','In a pastoral manner','rural way','C1'],
      ['pastoralness','n','The quality of being pastoral','rural quality','C1'],
      ['pastorality','n','The state of being pastoral','rural condition','C2'],
      ['unpastoral','adj','Not pastoral','not rural','C1'],
      ['inpastoral','adj','Not pastoral','not rural','C2'],
      ['nonpastoral','adj','Not pastoral','not rural','C1'],
      ['semipastoral','adj','Partially pastoral','partly rural','C2'],
      ['overpastoral','adj','Excessively pastoral','too rural','C2'],
      ['ultrapastoral','adj','Extremely pastoral','very rural','C2'],
      ['avant-gardeity','n','The state of being avant-garde','innovative condition','C2'],
      ['inavant-garde','adj','Not avant-garde','not innovative','C2'],
      ['nonavant-garde','adj','Not avant-garde','not innovative','C1'],
      ['semiavant-garde','adj','Partially avant-garde','partly innovative','C2'],
      ['overavant-garde','adj','Excessively avant-garde','too innovative','C2'],
      ['ultraavant-garde','adj','Extremely avant-garde','very innovative','C2'],
      ['hegemonicity','n','The state of being hegemonic','dominant condition','C2'],
      ['inhegemonic','adj','Not hegemonic','not dominant','C2'],
      ['nonhegemonic','adj','Not hegemonic','not dominant','C2'],
      ['semihegemonic','adj','Partially hegemonic','partly dominant','C2'],
      ['overhegemonic','adj','Excessively hegemonic','too dominant','C2'],
      ['ultrahegemonic','adj','Extremely hegemonic','very dominant','C2'],
      ['heterodox','adj','Not conforming to accepted beliefs','unorthodox,nonconformist,dissenting','C2'],
      ['heterodoxly','adv','In a heterodox manner','unorthodox way','C2'],
      ['heterodoxness','n','The quality of being heterodox','unorthodox quality','C2'],
      ['heterodoxity','n','The state of being heterodox','unorthodox condition','C2'],
      ['unheterodox','adj','Not heterodox','not unorthodox','C2'],
      ['inheterodox','adj','Not heterodox','not unorthodox','C2'],
      ['nonheterodox','adj','Not heterodox','not unorthodox','C2'],
      ['semiheterodox','adj','Partially heterodox','partly unorthodox','C2'],
      ['overheterodox','adj','Excessively heterodox','too unorthodox','C2'],
      ['ultraheterodox','adj','Extremely heterodox','very unorthodox','C2'],
    ],
    science: [
      ['hypothesize','v','To propose a theory or explanation','theorize,speculate,postulate','B2'],
      ['hypothesization','n','The act of hypothesizing','theorize process','B2'],
      ['hypothesizment','n','The result of hypothesizing','theorize outcome','B2'],
      ['hypothesizance','n','The state of hypothesizing','theorize state','B2'],
      ['hypothesizence','n','The quality of hypothesizing','theorize quality','B2'],
      ['hypothesizal','n','An act of hypothesizing','theorize event','C1'],
      ['hypothesizer','n','One who hypothesizes','theorize person','B2'],
      ['hypothesizor','n','One who hypothesizes','theorize agent','B2'],
      ['hypothesizee','n','One who is hypothesized','theorize recipient','C1'],
      ['hypothesizable','adj','Capable of being hypothesized','theorize,possible','C1'],
      ['hypothesizible','adj','Able to be hypothesized','theorize,feasible','C1'],
      ['hypothesizive','adj','Tending to hypothesize','theorize,active','B2'],
      ['hypothesizing','adj','Currently hypothesizing','theorize,ongoing','B2'],
      ['hypothesized','adj','Having been hypothesized','theorize,completed','B2'],
      ['rehypothesize','v','To hypothesize again','theorize again,repeat','B2'],
      ['unhypothesize','v','To reverse hypothesizing','reverse,undo','C1'],
      ['overhypothesize','v','To hypothesize excessively','excess,too much','C1'],
      ['underhypothesize','v','To hypothesize insufficiently','insufficient,inadequate','C1'],
      ['mishypothesize','v','To hypothesize incorrectly','wrongly,incorrectly','C1'],
      ['prehypothesize','v','To hypothesize beforehand','before,in advance','C1'],
      ['cohypothesize','v','To hypothesize together','jointly,together','C1'],
      ['rehypothesization','n','The act of hypothesizing again','re-theorize','C1'],
      ['overhypothesization','n','Excessive hypothesizing','excess theorize','C1'],
      ['quantify','v','To express or measure as a quantity','measure,calculate,count','B2'],
      ['quantifyation','n','The act of quantifying','measure process','B2'],
      ['quantifyment','n','The result of quantifying','measure outcome','B2'],
      ['quantifyance','n','The state of quantifying','measure state','B2'],
      ['quantifyence','n','The quality of quantifying','measure quality','B2'],
      ['quantifyal','n','An act of quantifying','measure event','C1'],
      ['quantifyer','n','One who quantifys','measure person','B2'],
      ['quantifyor','n','One who quantifys','measure agent','B2'],
      ['quantifyee','n','One who is quantifyd','measure recipient','C1'],
      ['quantifyable','adj','Capable of being quantifyd','measure,possible','C1'],
      ['quantifyible','adj','Able to be quantifyd','measure,feasible','C1'],
      ['quantifyive','adj','Tending to quantify','measure,active','B2'],
      ['quantifying','adj','Currently quantifying','measure,ongoing','B2'],
      ['quantifyed','adj','Having been quantifyd','measure,completed','B2'],
      ['requantify','v','To quantify again','measure again,repeat','B2'],
      ['unquantify','v','To reverse quantifying','reverse,undo','C1'],
      ['overquantify','v','To quantify excessively','excess,too much','C1'],
      ['underquantify','v','To quantify insufficiently','insufficient,inadequate','C1'],
      ['misquantify','v','To quantify incorrectly','wrongly,incorrectly','C1'],
      ['prequantify','v','To quantify beforehand','before,in advance','C1'],
      ['coquantify','v','To quantify together','jointly,together','C1'],
      ['requantifyation','n','The act of quantifying again','re-measure','C1'],
      ['overquantifyation','n','Excessive quantifying','excess measure','C1'],
      ['replicate','v','To reproduce or duplicate','copy,duplicate,reproduce','B2'],
      ['replicatation','n','The act of replicating','copy process','B2'],
      ['replicatment','n','The result of replicating','copy outcome','B2'],
      ['replicatance','n','The state of replicating','copy state','B2'],
      ['replicatence','n','The quality of replicating','copy quality','B2'],
      ['replicatal','n','An act of replicating','copy event','C1'],
      ['replicater','n','One who replicates','copy person','B2'],
      ['replicator','n','One who replicates','copy agent','B2'],
      ['replicatee','n','One who is replicated','copy recipient','C1'],
      ['replicatable','adj','Capable of being replicated','copy,possible','C1'],
      ['replicatible','adj','Able to be replicated','copy,feasible','C1'],
      ['replicative','adj','Tending to replicate','copy,active','B2'],
      ['replicating','adj','Currently replicating','copy,ongoing','B2'],
      ['replicated','adj','Having been replicated','copy,completed','B2'],
      ['rereplicate','v','To replicate again','copy again,repeat','B2'],
      ['unreplicate','v','To reverse replicating','reverse,undo','C1'],
      ['overreplicate','v','To replicate excessively','excess,too much','C1'],
      ['underreplicate','v','To replicate insufficiently','insufficient,inadequate','C1'],
      ['misreplicate','v','To replicate incorrectly','wrongly,incorrectly','C1'],
      ['prereplicate','v','To replicate beforehand','before,in advance','C1'],
      ['coreplicate','v','To replicate together','jointly,together','C1'],
      ['rereplicatation','n','The act of replicating again','re-copy','C1'],
      ['overreplicatation','n','Excessive replicating','excess copy','C1'],
      ['correlate','v','To have a mutual relationship','relate,connect,associate','B2'],
      ['correlatation','n','The act of correlating','relate process','B2'],
      ['correlatment','n','The result of correlating','relate outcome','B2'],
      ['correlatance','n','The state of correlating','relate state','B2'],
      ['correlatence','n','The quality of correlating','relate quality','B2'],
      ['correlatal','n','An act of correlating','relate event','C1'],
      ['correlater','n','One who correlates','relate person','B2'],
      ['correlator','n','One who correlates','relate agent','B2'],
      ['correlatee','n','One who is correlated','relate recipient','C1'],
      ['correlatable','adj','Capable of being correlated','relate,possible','C1'],
      ['correlatible','adj','Able to be correlated','relate,feasible','C1'],
      ['correlative','adj','Tending to correlate','relate,active','B2'],
      ['correlating','adj','Currently correlating','relate,ongoing','B2'],
      ['correlated','adj','Having been correlated','relate,completed','B2'],
      ['recorrelate','v','To correlate again','relate again,repeat','B2'],
      ['uncorrelate','v','To reverse correlating','reverse,undo','C1'],
      ['overcorrelate','v','To correlate excessively','excess,too much','C1'],
      ['undercorrelate','v','To correlate insufficiently','insufficient,inadequate','C1'],
      ['miscorrelate','v','To correlate incorrectly','wrongly,incorrectly','C1'],
      ['precorrelate','v','To correlate beforehand','before,in advance','C1'],
      ['cocorrelate','v','To correlate together','jointly,together','C1'],
      ['recorrelatation','n','The act of correlating again','re-relate','C1'],
      ['overcorrelatation','n','Excessive correlating','excess relate','C1'],
      ['oxidize','v','To combine with oxygen','rust,corrode,decay','C1'],
      ['oxidization','n','The act of oxidizing','rust process','C1'],
      ['oxidizment','n','The result of oxidizing','rust outcome','C1'],
      ['oxidizance','n','The state of oxidizing','rust state','C1'],
      ['oxidizence','n','The quality of oxidizing','rust quality','C1'],
      ['oxidizal','n','An act of oxidizing','rust event','C2'],
      ['oxidizer','n','One who oxidizes','rust person','C1'],
      ['oxidizor','n','One who oxidizes','rust agent','C1'],
      ['oxidizee','n','One who is oxidized','rust recipient','C2'],
      ['oxidizable','adj','Capable of being oxidized','rust,possible','C2'],
      ['oxidizible','adj','Able to be oxidized','rust,feasible','C2'],
      ['oxidizive','adj','Tending to oxidize','rust,active','C1'],
      ['oxidizing','adj','Currently oxidizing','rust,ongoing','C1'],
      ['oxidized','adj','Having been oxidized','rust,completed','C1'],
      ['reoxidize','v','To oxidize again','rust again,repeat','C1'],
      ['unoxidize','v','To reverse oxidizing','reverse,undo','C2'],
      ['overoxidize','v','To oxidize excessively','excess,too much','C2'],
      ['underoxidize','v','To oxidize insufficiently','insufficient,inadequate','C2'],
      ['misoxidize','v','To oxidize incorrectly','wrongly,incorrectly','C2'],
      ['preoxidize','v','To oxidize beforehand','before,in advance','C2'],
      ['cooxidize','v','To oxidize together','jointly,together','C2'],
      ['reoxidization','n','The act of oxidizing again','re-rust','C2'],
      ['overoxidization','n','Excessive oxidizing','excess rust','C2'],
      ['crystallize','v','To form into crystals','solidify,harden,coalesce','C1'],
      ['crystallization','n','The act of crystallizing','solidify process','C1'],
      ['crystallizment','n','The result of crystallizing','solidify outcome','C1'],
      ['crystallizance','n','The state of crystallizing','solidify state','C1'],
      ['crystallizence','n','The quality of crystallizing','solidify quality','C1'],
      ['crystallizal','n','An act of crystallizing','solidify event','C2'],
      ['crystallizer','n','One who crystallizes','solidify person','C1'],
      ['crystallizor','n','One who crystallizes','solidify agent','C1'],
      ['crystallizee','n','One who is crystallized','solidify recipient','C2'],
      ['crystallizable','adj','Capable of being crystallized','solidify,possible','C2'],
      ['crystallizible','adj','Able to be crystallized','solidify,feasible','C2'],
      ['crystallizive','adj','Tending to crystallize','solidify,active','C1'],
      ['crystallizing','adj','Currently crystallizing','solidify,ongoing','C1'],
      ['crystallized','adj','Having been crystallized','solidify,completed','C1'],
      ['recrystallize','v','To crystallize again','solidify again,repeat','C1'],
      ['uncrystallize','v','To reverse crystallizing','reverse,undo','C2'],
      ['overcrystallize','v','To crystallize excessively','excess,too much','C2'],
      ['undercrystallize','v','To crystallize insufficiently','insufficient,inadequate','C2'],
      ['miscrystallize','v','To crystallize incorrectly','wrongly,incorrectly','C2'],
      ['precrystallize','v','To crystallize beforehand','before,in advance','C2'],
      ['cocrystallize','v','To crystallize together','jointly,together','C2'],
      ['recrystallization','n','The act of crystallizing again','re-solidify','C2'],
      ['overcrystallization','n','Excessive crystallizing','excess solidify','C2'],
    ],
  },
  collocations: {}
};
