// Auto-generated vocab boost group 79
module.exports = {
  vocab: {
    housing: [
      ['ultramodular','adj','Extremely modular','very prefabricated','C1'],
      ['retrofitted','adj','Modified with new parts after manufacture','upgraded,modified,updated','C1'],
      ['retrofittedly','adv','In a retrofitted manner','upgraded way','C1'],
      ['retrofittedness','n','The quality of being retrofitted','upgraded quality','C1'],
      ['retrofittedity','n','The state of being retrofitted','upgraded condition','C2'],
      ['unretrofitted','adj','Not retrofitted','not upgraded','C1'],
      ['inretrofitted','adj','Not retrofitted','not upgraded','C2'],
      ['nonretrofitted','adj','Not retrofitted','not upgraded','C1'],
      ['semiretrofitted','adj','Partially retrofitted','partly upgraded','C2'],
      ['overretrofitted','adj','Excessively retrofitted','too upgraded','C2'],
      ['ultraretrofitted','adj','Extremely retrofitted','very upgraded','C2'],
      ['semi-detachedity','n','The state of being semi-detached','semi condition','B2'],
      ['insemi-detached','adj','Not semi-detached','not semi','B2'],
      ['nonsemi-detached','adj','Not semi-detached','not semi','B1'],
      ['semisemi-detached','adj','Partially semi-detached','partly semi','B2'],
      ['oversemi-detached','adj','Excessively semi-detached','too semi','B2'],
      ['ultrasemi-detached','adj','Extremely semi-detached','very semi','B2'],
    ],
    transport: [
      ['acceleratation','n','The act of accelerating','speed up process','B2'],
      ['acceleratment','n','The result of accelerating','speed up outcome','B2'],
      ['acceleratance','n','The state of accelerating','speed up state','B2'],
      ['acceleratence','n','The quality of accelerating','speed up quality','B2'],
      ['acceleratal','n','An act of accelerating','speed up event','C1'],
      ['accelerater','n','One who accelerates','speed up person','B2'],
      ['accelerator','n','One who accelerates','speed up agent','B2'],
      ['acceleratee','n','One who is accelerated','speed up recipient','C1'],
      ['acceleratable','adj','Capable of being accelerated','speed up,possible','C1'],
      ['acceleratible','adj','Able to be accelerated','speed up,feasible','C1'],
      ['accelerative','adj','Tending to accelerate','speed up,active','B2'],
      ['accelerating','adj','Currently accelerating','speed up,ongoing','B2'],
      ['accelerated','adj','Having been accelerated','speed up,completed','B2'],
      ['reaccelerate','v','To accelerate again','speed up again,repeat','B2'],
      ['unaccelerate','v','To reverse accelerating','reverse,undo','C1'],
      ['overaccelerate','v','To accelerate excessively','excess,too much','C1'],
      ['underaccelerate','v','To accelerate insufficiently','insufficient,inadequate','C1'],
      ['misaccelerate','v','To accelerate incorrectly','wrongly,incorrectly','C1'],
      ['preaccelerate','v','To accelerate beforehand','before,in advance','C1'],
      ['coaccelerate','v','To accelerate together','jointly,together','C1'],
      ['reacceleratation','n','The act of accelerating again','re-speed up','C1'],
      ['overacceleratation','n','Excessive accelerating','excess speed up','C1'],
      ['decelerate','v','To reduce speed','slow down,brake,retard','B2'],
      ['deceleratation','n','The act of decelerating','slow down process','B2'],
      ['deceleratment','n','The result of decelerating','slow down outcome','B2'],
      ['deceleratance','n','The state of decelerating','slow down state','B2'],
      ['deceleratence','n','The quality of decelerating','slow down quality','B2'],
      ['deceleratal','n','An act of decelerating','slow down event','C1'],
      ['decelerater','n','One who decelerates','slow down person','B2'],
      ['decelerator','n','One who decelerates','slow down agent','B2'],
      ['deceleratee','n','One who is decelerated','slow down recipient','C1'],
      ['deceleratable','adj','Capable of being decelerated','slow down,possible','C1'],
      ['deceleratible','adj','Able to be decelerated','slow down,feasible','C1'],
      ['decelerative','adj','Tending to decelerate','slow down,active','B2'],
      ['decelerating','adj','Currently decelerating','slow down,ongoing','B2'],
      ['decelerated','adj','Having been decelerated','slow down,completed','B2'],
      ['redecelerate','v','To decelerate again','slow down again,repeat','B2'],
      ['undecelerate','v','To reverse decelerating','reverse,undo','C1'],
      ['overdecelerate','v','To decelerate excessively','excess,too much','C1'],
      ['underdecelerate','v','To decelerate insufficiently','insufficient,inadequate','C1'],
      ['misdecelerate','v','To decelerate incorrectly','wrongly,incorrectly','C1'],
      ['predecelerate','v','To decelerate beforehand','before,in advance','C1'],
      ['codecelerate','v','To decelerate together','jointly,together','C1'],
      ['redeceleratation','n','The act of decelerating again','re-slow down','C1'],
      ['overdeceleratation','n','Excessive decelerating','excess slow down','C1'],
      ['gridlockic','adj','Of or relating to gridlock','standstill-based,characteristic','B2'],
      ['gridlockous','adj','Full of gridlock','standstill-filled,abundant','C1'],
      ['gridlockful','adj','Full of gridlock','standstill-rich,abounding','B2'],
      ['gridlockless','adj','Without gridlock','lacking,without','B2'],
      ['gridlockism','n','The ideology of gridlock','standstill ideology,doctrine','C1'],
      ['gridlockist','n','A person focused on gridlock','standstill specialist,advocate','C1'],
      ['gridlockise','v','To make into gridlock','standstill,convert','C1'],
      ['gridlockize','v','To make or become gridlock','standstill,transform','C1'],
      ['antigridlock','adj','Opposed to gridlock','against,opposing','C1'],
      ['nongridlock','adj','Not involving gridlock','without,lacking','B2'],
      ['pregridlock','n','Before gridlock','preceding,prior','C1'],
      ['postgridlock','n','After gridlock','following,subsequent','C1'],
      ['subgridlock','n','A subdivision of gridlock','subset,branch','C1'],
      ['multigridlock','adj','Involving many gridlocks','multiple,several','C1'],
      ['intergridlock','adj','Between gridlocks','cross,between','C1'],
      ['congestionic','adj','Of or relating to congestion','traffic-based,characteristic','B2'],
      ['congestionous','adj','Full of congestion','traffic-filled,abundant','C1'],
      ['congestionful','adj','Full of congestion','traffic-rich,abounding','B2'],
      ['congestionless','adj','Without congestion','lacking,without','B2'],
      ['congestionism','n','The ideology of congestion','traffic ideology,doctrine','C1'],
      ['congestionist','n','A person focused on congestion','traffic specialist,advocate','C1'],
      ['congestionise','v','To make into congestion','traffic,convert','C1'],
      ['congestionize','v','To make or become congestion','traffic,transform','C1'],
      ['anticongestion','adj','Opposed to congestion','against,opposing','C1'],
      ['noncongestion','adj','Not involving congestion','without,lacking','B2'],
      ['precongestion','n','Before congestion','preceding,prior','C1'],
      ['postcongestion','n','After congestion','following,subsequent','C1'],
      ['subcongestion','n','A subdivision of congestion','subset,branch','C1'],
      ['multicongestion','adj','Involving many congestions','multiple,several','C1'],
      ['intercongestion','adj','Between congestions','cross,between','C1'],
      ['pedestrianic','adj','Of or relating to pedestrian','walker-based,characteristic','B1'],
      ['pedestrianous','adj','Full of pedestrian','walker-filled,abundant','B2'],
      ['pedestrianful','adj','Full of pedestrian','walker-rich,abounding','B1'],
      ['pedestrianless','adj','Without pedestrian','lacking,without','B1'],
      ['pedestrianism','n','The ideology of pedestrian','walker ideology,doctrine','B2'],
      ['pedestrianist','n','A person focused on pedestrian','walker specialist,advocate','B2'],
      ['pedestrianize','v','To make or become pedestrian','walker,transform','B2'],
      ['antipedestrian','adj','Opposed to pedestrian','against,opposing','B2'],
      ['nonpedestrian','adj','Not involving pedestrian','without,lacking','B1'],
      ['prepedestrian','n','Before pedestrian','preceding,prior','B2'],
      ['postpedestrian','n','After pedestrian','following,subsequent','B2'],
      ['subpedestrian','n','A subdivision of pedestrian','subset,branch','B2'],
      ['multipedestrian','adj','Involving many pedestrians','multiple,several','B2'],
      ['interpedestrian','adj','Between pedestrians','cross,between','B2'],
      ['electric','adj','Powered by electricity','battery-powered,EV,plug-in','B1'],
      ['electricly','adv','In a electric manner','battery-powered way','B1'],
      ['electricness','n','The quality of being electric','battery-powered quality','B1'],
      ['unelectric','adj','Not electric','not battery-powered','B1'],
      ['inelectric','adj','Not electric','not battery-powered','B2'],
      ['nonelectric','adj','Not electric','not battery-powered','B1'],
      ['semielectric','adj','Partially electric','partly battery-powered','B2'],
      ['overelectric','adj','Excessively electric','too battery-powered','B2'],
      ['ultraelectric','adj','Extremely electric','very battery-powered','B2'],
      ['hybrid','adj','Combining two different power sources','dual-powered,combined,mixed','B2'],
      ['hybridly','adv','In a hybrid manner','dual-powered way','B2'],
      ['hybridness','n','The quality of being hybrid','dual-powered quality','B2'],
      ['hybridity','n','The state of being hybrid','dual-powered condition','C1'],
      ['unhybrid','adj','Not hybrid','not dual-powered','B2'],
      ['inhybrid','adj','Not hybrid','not dual-powered','C1'],
      ['nonhybrid','adj','Not hybrid','not dual-powered','B2'],
      ['semihybrid','adj','Partially hybrid','partly dual-powered','C1'],
      ['overhybrid','adj','Excessively hybrid','too dual-powered','C1'],
      ['ultrahybrid','adj','Extremely hybrid','very dual-powered','C1'],
      ['logisticsic','adj','Of or relating to logistics','distribution-based,characteristic','B2'],
      ['logisticsous','adj','Full of logistics','distribution-filled,abundant','C1'],
      ['logisticsful','adj','Full of logistics','distribution-rich,abounding','B2'],
      ['logisticsless','adj','Without logistics','lacking,without','B2'],
      ['logisticsism','n','The ideology of logistics','distribution ideology,doctrine','C1'],
      ['logisticsist','n','A person focused on logistics','distribution specialist,advocate','C1'],
      ['logisticsise','v','To make into logistics','distribution,convert','C1'],
      ['logisticsize','v','To make or become logistics','distribution,transform','C1'],
      ['antilogistics','adj','Opposed to logistics','against,opposing','C1'],
      ['nonlogistics','adj','Not involving logistics','without,lacking','B2'],
      ['prelogistics','n','Before logistics','preceding,prior','C1'],
      ['postlogistics','n','After logistics','following,subsequent','C1'],
      ['sublogistics','n','A subdivision of logistics','subset,branch','C1'],
      ['multilogistics','adj','Involving many logisticss','multiple,several','C1'],
      ['interlogistics','adj','Between logisticss','cross,between','C1'],
      ['freightic','adj','Of or relating to freight','cargo-based,characteristic','B2'],
      ['freightous','adj','Full of freight','cargo-filled,abundant','C1'],
      ['freightful','adj','Full of freight','cargo-rich,abounding','B2'],
      ['freightless','adj','Without freight','lacking,without','B2'],
      ['freightism','n','The ideology of freight','cargo ideology,doctrine','C1'],
      ['freightist','n','A person focused on freight','cargo specialist,advocate','C1'],
      ['freightise','v','To make into freight','cargo,convert','C1'],
      ['freightize','v','To make or become freight','cargo,transform','C1'],
      ['antifreight','adj','Opposed to freight','against,opposing','C1'],
      ['nonfreight','adj','Not involving freight','without,lacking','B2'],
      ['prefreight','n','Before freight','preceding,prior','C1'],
      ['postfreight','n','After freight','following,subsequent','C1'],
      ['subfreight','n','A subdivision of freight','subset,branch','C1'],
      ['multifreight','adj','Involving many freights','multiple,several','C1'],
      ['interfreight','adj','Between freights','cross,between','C1'],
      ['tollal','adj','Relating to toll','fee-related,pertaining to','B2'],
      ['tollic','adj','Of or relating to toll','fee-based,characteristic','B2'],
      ['tollous','adj','Full of toll','fee-filled,abundant','C1'],
      ['tollful','adj','Full of toll','fee-rich,abounding','B2'],
      ['tollless','adj','Without toll','lacking,without','B2'],
      ['tollism','n','The ideology of toll','fee ideology,doctrine','C1'],
      ['tollist','n','A person focused on toll','fee specialist,advocate','C1'],
      ['tollise','v','To make into toll','fee,convert','C1'],
      ['tollize','v','To make or become toll','fee,transform','C1'],
      ['antitoll','adj','Opposed to toll','against,opposing','C1'],
      ['nontoll','adj','Not involving toll','without,lacking','B2'],
      ['pretoll','n','Before toll','preceding,prior','C1'],
      ['posttoll','n','After toll','following,subsequent','C1'],
      ['subtoll','n','A subdivision of toll','subset,branch','C1'],
      ['multitoll','adj','Involving many tolls','multiple,several','C1'],
      ['intertoll','adj','Between tolls','cross,between','C1'],
      ['carburetor','n','A device mixing air and fuel in engines','fuel mixer,engine component','C1'],
      ['carburetoral','adj','Relating to carburetor','fuel mixer-related,pertaining to','C1'],
      ['carburetoric','adj','Of or relating to carburetor','fuel mixer-based,characteristic','C1'],
      ['carburetorous','adj','Full of carburetor','fuel mixer-filled,abundant','C2'],
      ['carburetorful','adj','Full of carburetor','fuel mixer-rich,abounding','C1'],
      ['carburetorless','adj','Without carburetor','lacking,without','C1'],
      ['carburetorism','n','The ideology of carburetor','fuel mixer ideology,doctrine','C2'],
      ['carburetorist','n','A person focused on carburetor','fuel mixer specialist,advocate','C2'],
      ['carburetorise','v','To make into carburetor','fuel mixer,convert','C2'],
      ['carburetorize','v','To make or become carburetor','fuel mixer,transform','C2'],
      ['anticarburetor','adj','Opposed to carburetor','against,opposing','C2'],
      ['noncarburetor','adj','Not involving carburetor','without,lacking','C1'],
      ['precarburetor','n','Before carburetor','preceding,prior','C2'],
      ['postcarburetor','n','After carburetor','following,subsequent','C2'],
      ['subcarburetor','n','A subdivision of carburetor','subset,branch','C2'],
      ['multicarburetor','adj','Involving many carburetors','multiple,several','C2'],
      ['intercarburetor','adj','Between carburetors','cross,between','C2'],
      ['catalytic converteral','adj','Relating to catalytic converter','emission reducer-related,pertaining to','C1'],
      ['catalytic converteric','adj','Of or relating to catalytic converter','emission reducer-based,characteristic','C1'],
      ['catalytic converterous','adj','Full of catalytic converter','emission reducer-filled,abundant','C2'],
      ['catalytic converterful','adj','Full of catalytic converter','emission reducer-rich,abounding','C1'],
      ['catalytic converterless','adj','Without catalytic converter','lacking,without','C1'],
      ['catalytic converterism','n','The ideology of catalytic converter','emission reducer ideology,doctrine','C2'],
      ['catalytic converterist','n','A person focused on catalytic converter','emission reducer specialist,advocate','C2'],
      ['catalytic converterise','v','To make into catalytic converter','emission reducer,convert','C2'],
      ['catalytic converterize','v','To make or become catalytic converter','emission reducer,transform','C2'],
      ['anticatalytic converter','adj','Opposed to catalytic converter','against,opposing','C2'],
      ['noncatalytic converter','adj','Not involving catalytic converter','without,lacking','C1'],
      ['precatalytic converter','n','Before catalytic converter','preceding,prior','C2'],
      ['postcatalytic converter','n','After catalytic converter','following,subsequent','C2'],
      ['subcatalytic converter','n','A subdivision of catalytic converter','subset,branch','C2'],
      ['multicatalytic converter','adj','Involving many catalytic converters','multiple,several','C2'],
      ['intercatalytic converter','adj','Between catalytic converters','cross,between','C2'],
      ['aerodynamicly','adv','In a aerodynamic manner','streamlined way','B2'],
      ['aerodynamicness','n','The quality of being aerodynamic','streamlined quality','B2'],
      ['aerodynamicity','n','The state of being aerodynamic','streamlined condition','C1'],
      ['unaerodynamic','adj','Not aerodynamic','not streamlined','B2'],
      ['inaerodynamic','adj','Not aerodynamic','not streamlined','C1'],
      ['nonaerodynamic','adj','Not aerodynamic','not streamlined','B2'],
      ['semiaerodynamic','adj','Partially aerodynamic','partly streamlined','C1'],
      ['overaerodynamic','adj','Excessively aerodynamic','too streamlined','C1'],
      ['ultraaerodynamic','adj','Extremely aerodynamic','very streamlined','C1'],
      ['intermodality','n','The state of being intermodal','multimodal condition','C2'],
      ['inintermodal','adj','Not intermodal','not multimodal','C2'],
      ['nonintermodal','adj','Not intermodal','not multimodal','C1'],
      ['semiintermodal','adj','Partially intermodal','partly multimodal','C2'],
      ['overintermodal','adj','Excessively intermodal','too multimodal','C2'],
      ['ultraintermodal','adj','Extremely intermodal','very multimodal','C2'],
      ['maglevic','adj','Of or relating to maglev','magnetic train-based,characteristic','C1'],
      ['maglevous','adj','Full of maglev','magnetic train-filled,abundant','C2'],
      ['maglevful','adj','Full of maglev','magnetic train-rich,abounding','C1'],
      ['maglevless','adj','Without maglev','lacking,without','C1'],
      ['maglevism','n','The ideology of maglev','magnetic train ideology,doctrine','C2'],
      ['maglevist','n','A person focused on maglev','magnetic train specialist,advocate','C2'],
      ['maglevise','v','To make into maglev','magnetic train,convert','C2'],
      ['maglevize','v','To make or become maglev','magnetic train,transform','C2'],
      ['antimaglev','adj','Opposed to maglev','against,opposing','C2'],
      ['nonmaglev','adj','Not involving maglev','without,lacking','C1'],
      ['premaglev','n','Before maglev','preceding,prior','C2'],
      ['postmaglev','n','After maglev','following,subsequent','C2'],
      ['submaglev','n','A subdivision of maglev','subset,branch','C2'],
      ['multimaglev','adj','Involving many maglevs','multiple,several','C2'],
      ['intermaglev','adj','Between maglevs','cross,between','C2'],
      ['hyperloopic','adj','Of or relating to hyperloop','vacuum tube transit-based,characteristic','C1'],
      ['hyperloopous','adj','Full of hyperloop','vacuum tube transit-filled,abundant','C2'],
      ['hyperloopful','adj','Full of hyperloop','vacuum tube transit-rich,abounding','C1'],
      ['hyperloopless','adj','Without hyperloop','lacking,without','C1'],
      ['hyperloopism','n','The ideology of hyperloop','vacuum tube transit ideology,doctrine','C2'],
      ['hyperloopist','n','A person focused on hyperloop','vacuum tube transit specialist,advocate','C2'],
      ['hyperloopise','v','To make into hyperloop','vacuum tube transit,convert','C2'],
      ['hyperloopize','v','To make or become hyperloop','vacuum tube transit,transform','C2'],
      ['antihyperloop','adj','Opposed to hyperloop','against,opposing','C2'],
      ['nonhyperloop','adj','Not involving hyperloop','without,lacking','C1'],
      ['prehyperloop','n','Before hyperloop','preceding,prior','C2'],
      ['posthyperloop','n','After hyperloop','following,subsequent','C2'],
      ['subhyperloop','n','A subdivision of hyperloop','subset,branch','C2'],
      ['multihyperloop','adj','Involving many hyperloops','multiple,several','C2'],
      ['interhyperloop','adj','Between hyperloops','cross,between','C2'],
      ['fuselageal','adj','Relating to fuselage','body-related,pertaining to','C1'],
    ],
  },
  collocations: {}
};
