// Auto-generated vocab boost group 72
module.exports = {
  vocab: {
    arts: [
      ['sfumatoous','adj','Full of sfumato','blending-filled,abundant','C2'],
      ['sfumatoful','adj','Full of sfumato','blending-rich,abounding','C2'],
      ['sfumatoless','adj','Without sfumato','lacking,without','C2'],
      ['sfumatoism','n','The ideology of sfumato','blending ideology,doctrine','C2'],
      ['sfumatoist','n','A person focused on sfumato','blending specialist,advocate','C2'],
      ['sfumatoise','v','To make into sfumato','blending,convert','C2'],
      ['sfumatoize','v','To make or become sfumato','blending,transform','C2'],
      ['antisfumato','adj','Opposed to sfumato','against,opposing','C2'],
      ['nonsfumato','adj','Not involving sfumato','without,lacking','C2'],
      ['presfumato','n','Before sfumato','preceding,prior','C2'],
      ['postsfumato','n','After sfumato','following,subsequent','C2'],
      ['subsfumato','n','A subdivision of sfumato','subset,branch','C2'],
      ['multisfumato','adj','Involving many sfumatos','multiple,several','C2'],
      ['intersfumato','adj','Between sfumatos','cross,between','C2'],
      ['kitschic','adj','Of or relating to kitsch','tackiness-based,characteristic','C1'],
      ['kitschous','adj','Full of kitsch','tackiness-filled,abundant','C2'],
      ['kitschful','adj','Full of kitsch','tackiness-rich,abounding','C1'],
      ['kitschless','adj','Without kitsch','lacking,without','C1'],
      ['kitschism','n','The ideology of kitsch','tackiness ideology,doctrine','C2'],
      ['kitschist','n','A person focused on kitsch','tackiness specialist,advocate','C2'],
      ['kitschise','v','To make into kitsch','tackiness,convert','C2'],
      ['kitschize','v','To make or become kitsch','tackiness,transform','C2'],
      ['antikitsch','adj','Opposed to kitsch','against,opposing','C2'],
      ['nonkitsch','adj','Not involving kitsch','without,lacking','C1'],
      ['prekitsch','n','Before kitsch','preceding,prior','C2'],
      ['postkitsch','n','After kitsch','following,subsequent','C2'],
      ['subkitsch','n','A subdivision of kitsch','subset,branch','C2'],
      ['multikitsch','adj','Involving many kitschs','multiple,several','C2'],
      ['interkitsch','adj','Between kitschs','cross,between','C2'],
      ['baroqueity','n','The state of being baroque','elaborate condition','C2'],
      ['inbaroque','adj','Not baroque','not elaborate','C2'],
      ['nonbaroque','adj','Not baroque','not elaborate','C1'],
      ['semibaroque','adj','Partially baroque','partly elaborate','C2'],
      ['overbaroque','adj','Excessively baroque','too elaborate','C2'],
      ['ultrabaroque','adj','Extremely baroque','very elaborate','C2'],
      ['eclecticly','adv','In a eclectic manner','varied way','C1'],
      ['eclecticness','n','The quality of being eclectic','varied quality','C1'],
      ['eclecticity','n','The state of being eclectic','varied condition','C2'],
      ['uneclectic','adj','Not eclectic','not varied','C1'],
      ['ineclectic','adj','Not eclectic','not varied','C2'],
      ['noneclectic','adj','Not eclectic','not varied','C1'],
      ['semieclectic','adj','Partially eclectic','partly varied','C2'],
      ['overeclectic','adj','Excessively eclectic','too varied','C2'],
      ['ultraeclectic','adj','Extremely eclectic','very varied','C2'],
      ['ephemerally','adv','In a ephemeral manner','transient way','C1'],
      ['ephemeralness','n','The quality of being ephemeral','transient quality','C1'],
      ['ephemerality','n','The state of being ephemeral','transient condition','C2'],
      ['unephemeral','adj','Not ephemeral','not transient','C1'],
      ['inephemeral','adj','Not ephemeral','not transient','C2'],
      ['nonephemeral','adj','Not ephemeral','not transient','C1'],
      ['semiephemeral','adj','Partially ephemeral','partly transient','C2'],
      ['overephemeral','adj','Excessively ephemeral','too transient','C2'],
      ['ultraephemeral','adj','Extremely ephemeral','very transient','C2'],
      ['evocatively','adv','In a evocative manner','suggestive way','B2'],
      ['evocativeness','n','The quality of being evocative','suggestive quality','B2'],
      ['evocativeity','n','The state of being evocative','suggestive condition','C1'],
      ['unevocative','adj','Not evocative','not suggestive','B2'],
      ['inevocative','adj','Not evocative','not suggestive','C1'],
      ['nonevocative','adj','Not evocative','not suggestive','B2'],
      ['semievocative','adj','Partially evocative','partly suggestive','C1'],
      ['overevocative','adj','Excessively evocative','too suggestive','C1'],
      ['ultraevocative','adj','Extremely evocative','very suggestive','C1'],
      ['iconoclastous','adj','Full of iconoclast','rebel-filled,abundant','C2'],
      ['iconoclastful','adj','Full of iconoclast','rebel-rich,abounding','C2'],
      ['iconoclastless','adj','Without iconoclast','lacking,without','C2'],
      ['iconoclastism','n','The ideology of iconoclast','rebel ideology,doctrine','C2'],
      ['iconoclastist','n','A person focused on iconoclast','rebel specialist,advocate','C2'],
      ['iconoclastise','v','To make into iconoclast','rebel,convert','C2'],
      ['iconoclastize','v','To make or become iconoclast','rebel,transform','C2'],
      ['antiiconoclast','adj','Opposed to iconoclast','against,opposing','C2'],
      ['noniconoclast','adj','Not involving iconoclast','without,lacking','C2'],
      ['preiconoclast','n','Before iconoclast','preceding,prior','C2'],
      ['posticonoclast','n','After iconoclast','following,subsequent','C2'],
      ['subiconoclast','n','A subdivision of iconoclast','subset,branch','C2'],
      ['multiiconoclast','adj','Involving many iconoclasts','multiple,several','C2'],
      ['intericonoclast','adj','Between iconoclasts','cross,between','C2'],
      ['aesthete','n','A person appreciating beauty in art','art lover,connoisseur,devotee','C2'],
      ['aestheteal','adj','Relating to aesthete','art lover-related,pertaining to','C2'],
      ['aestheteic','adj','Of or relating to aesthete','art lover-based,characteristic','C2'],
      ['aestheteous','adj','Full of aesthete','art lover-filled,abundant','C2'],
      ['aestheteful','adj','Full of aesthete','art lover-rich,abounding','C2'],
      ['aestheteless','adj','Without aesthete','lacking,without','C2'],
      ['aestheteism','n','The ideology of aesthete','art lover ideology,doctrine','C2'],
      ['aestheteist','n','A person focused on aesthete','art lover specialist,advocate','C2'],
      ['aestheteise','v','To make into aesthete','art lover,convert','C2'],
      ['aestheteize','v','To make or become aesthete','art lover,transform','C2'],
      ['antiaesthete','adj','Opposed to aesthete','against,opposing','C2'],
      ['nonaesthete','adj','Not involving aesthete','without,lacking','C2'],
      ['preaesthete','n','Before aesthete','preceding,prior','C2'],
      ['postaesthete','n','After aesthete','following,subsequent','C2'],
      ['subaesthete','n','A subdivision of aesthete','subset,branch','C2'],
      ['multiaesthete','adj','Involving many aesthetes','multiple,several','C2'],
      ['interaesthete','adj','Between aesthetes','cross,between','C2'],
      ['philistine','n','A person hostile to culture and arts','barbarian,ignoramus,lowbrow','C2'],
      ['philistineal','adj','Relating to philistine','barbarian-related,pertaining to','C2'],
      ['philistineic','adj','Of or relating to philistine','barbarian-based,characteristic','C2'],
      ['philistineous','adj','Full of philistine','barbarian-filled,abundant','C2'],
      ['philistineful','adj','Full of philistine','barbarian-rich,abounding','C2'],
      ['philistineless','adj','Without philistine','lacking,without','C2'],
      ['philistineism','n','The ideology of philistine','barbarian ideology,doctrine','C2'],
      ['philistineist','n','A person focused on philistine','barbarian specialist,advocate','C2'],
      ['philistineise','v','To make into philistine','barbarian,convert','C2'],
      ['philistineize','v','To make or become philistine','barbarian,transform','C2'],
      ['antiphilistine','adj','Opposed to philistine','against,opposing','C2'],
      ['nonphilistine','adj','Not involving philistine','without,lacking','C2'],
      ['prephilistine','n','Before philistine','preceding,prior','C2'],
      ['postphilistine','n','After philistine','following,subsequent','C2'],
      ['subphilistine','n','A subdivision of philistine','subset,branch','C2'],
      ['multiphilistine','adj','Involving many philistines','multiple,several','C2'],
      ['interphilistine','adj','Between philistines','cross,between','C2'],
      ['renaissanceic','adj','Of or relating to renaissance','rebirth-based,characteristic','B2'],
      ['renaissanceous','adj','Full of renaissance','rebirth-filled,abundant','C1'],
      ['renaissanceful','adj','Full of renaissance','rebirth-rich,abounding','B2'],
      ['renaissanceless','adj','Without renaissance','lacking,without','B2'],
      ['renaissanceism','n','The ideology of renaissance','rebirth ideology,doctrine','C1'],
      ['renaissanceist','n','A person focused on renaissance','rebirth specialist,advocate','C1'],
      ['renaissanceise','v','To make into renaissance','rebirth,convert','C1'],
      ['renaissanceize','v','To make or become renaissance','rebirth,transform','C1'],
      ['antirenaissance','adj','Opposed to renaissance','against,opposing','C1'],
      ['nonrenaissance','adj','Not involving renaissance','without,lacking','B2'],
      ['prerenaissance','n','Before renaissance','preceding,prior','C1'],
      ['postrenaissance','n','After renaissance','following,subsequent','C1'],
      ['subrenaissance','n','A subdivision of renaissance','subset,branch','C1'],
      ['multirenaissance','adj','Involving many renaissances','multiple,several','C1'],
      ['interrenaissance','adj','Between renaissances','cross,between','C1'],
      ['opus','n','A musical composition','work,composition,piece','C1'],
      ['opusal','adj','Relating to opus','work-related,pertaining to','C1'],
      ['opusic','adj','Of or relating to opus','work-based,characteristic','C1'],
      ['opusous','adj','Full of opus','work-filled,abundant','C2'],
      ['opusful','adj','Full of opus','work-rich,abounding','C1'],
      ['opusless','adj','Without opus','lacking,without','C1'],
      ['opusism','n','The ideology of opus','work ideology,doctrine','C2'],
      ['opusist','n','A person focused on opus','work specialist,advocate','C2'],
      ['opusise','v','To make into opus','work,convert','C2'],
      ['opusize','v','To make or become opus','work,transform','C2'],
      ['antiopus','adj','Opposed to opus','against,opposing','C2'],
      ['nonopus','adj','Not involving opus','without,lacking','C1'],
      ['preopus','n','Before opus','preceding,prior','C2'],
      ['postopus','n','After opus','following,subsequent','C2'],
      ['subopus','n','A subdivision of opus','subset,branch','C2'],
      ['multiopus','adj','Involving many opuss','multiple,several','C2'],
      ['interopus','adj','Between opuss','cross,between','C2'],
    ],
    sports: [
      ['competation','n','The act of competing','contend process','B1'],
      ['competment','n','The result of competing','contend outcome','B1'],
      ['competance','n','The state of competing','contend state','B1'],
      ['competence','n','The quality of competing','contend quality','B1'],
      ['competal','n','An act of competing','contend event','B2'],
      ['competer','n','One who competes','contend person','B1'],
      ['competor','n','One who competes','contend agent','B1'],
      ['competee','n','One who is competed','contend recipient','B2'],
      ['competable','adj','Capable of being competed','contend,possible','B2'],
      ['competible','adj','Able to be competed','contend,feasible','B2'],
      ['competive','adj','Tending to compete','contend,active','B1'],
      ['competing','adj','Currently competing','contend,ongoing','B1'],
      ['competed','adj','Having been competed','contend,completed','B1'],
      ['recompete','v','To compete again','contend again,repeat','B1'],
      ['uncompete','v','To reverse competing','reverse,undo','B2'],
      ['overcompete','v','To compete excessively','excess,too much','B2'],
      ['undercompete','v','To compete insufficiently','insufficient,inadequate','B2'],
      ['miscompete','v','To compete incorrectly','wrongly,incorrectly','B2'],
      ['precompete','v','To compete beforehand','before,in advance','B2'],
      ['cocompete','v','To compete together','jointly,together','B2'],
      ['recompetation','n','The act of competing again','re-contend','B2'],
      ['overcompetation','n','Excessive competing','excess contend','B2'],
      ['persevere','v','To continue despite difficulty','persist,endure,keep going','B2'],
      ['perseveration','n','The act of persevering','persist process','B2'],
      ['perseverment','n','The result of persevering','persist outcome','B2'],
      ['perseverance','n','The state of persevering','persist state','B2'],
      ['perseverence','n','The quality of persevering','persist quality','B2'],
      ['perseveral','n','An act of persevering','persist event','C1'],
      ['perseverer','n','One who perseveres','persist person','B2'],
      ['perseveror','n','One who perseveres','persist agent','B2'],
      ['perseveree','n','One who is persevered','persist recipient','C1'],
      ['perseverable','adj','Capable of being persevered','persist,possible','C1'],
      ['perseverible','adj','Able to be persevered','persist,feasible','C1'],
      ['perseverive','adj','Tending to persevere','persist,active','B2'],
      ['persevering','adj','Currently persevering','persist,ongoing','B2'],
      ['persevered','adj','Having been persevered','persist,completed','B2'],
      ['repersevere','v','To persevere again','persist again,repeat','B2'],
      ['unpersevere','v','To reverse persevering','reverse,undo','C1'],
      ['overpersevere','v','To persevere excessively','excess,too much','C1'],
      ['underpersevere','v','To persevere insufficiently','insufficient,inadequate','C1'],
      ['mispersevere','v','To persevere incorrectly','wrongly,incorrectly','C1'],
      ['prepersevere','v','To persevere beforehand','before,in advance','C1'],
      ['copersevere','v','To persevere together','jointly,together','C1'],
      ['reperseveration','n','The act of persevering again','re-persist','C1'],
      ['overperseveration','n','Excessive persevering','excess persist','C1'],
      ['disqualifyation','n','The act of disqualifying','ban process','B2'],
      ['disqualifyment','n','The result of disqualifying','ban outcome','B2'],
      ['disqualifyance','n','The state of disqualifying','ban state','B2'],
      ['disqualifyence','n','The quality of disqualifying','ban quality','B2'],
      ['disqualifyal','n','An act of disqualifying','ban event','C1'],
      ['disqualifyer','n','One who disqualifys','ban person','B2'],
      ['disqualifyor','n','One who disqualifys','ban agent','B2'],
      ['disqualifyee','n','One who is disqualifyd','ban recipient','C1'],
      ['disqualifyable','adj','Capable of being disqualifyd','ban,possible','C1'],
      ['disqualifyible','adj','Able to be disqualifyd','ban,feasible','C1'],
      ['disqualifyive','adj','Tending to disqualify','ban,active','B2'],
      ['disqualifying','adj','Currently disqualifying','ban,ongoing','B2'],
      ['disqualifyed','adj','Having been disqualifyd','ban,completed','B2'],
      ['redisqualify','v','To disqualify again','ban again,repeat','B2'],
      ['undisqualify','v','To reverse disqualifying','reverse,undo','C1'],
      ['overdisqualify','v','To disqualify excessively','excess,too much','C1'],
      ['underdisqualify','v','To disqualify insufficiently','insufficient,inadequate','C1'],
      ['misdisqualify','v','To disqualify incorrectly','wrongly,incorrectly','C1'],
      ['predisqualify','v','To disqualify beforehand','before,in advance','C1'],
      ['codisqualify','v','To disqualify together','jointly,together','C1'],
      ['redisqualifyation','n','The act of disqualifying again','re-ban','C1'],
      ['overdisqualifyation','n','Excessive disqualifying','excess ban','C1'],
      ['strategization','n','The act of strategizing','plan process','B2'],
      ['strategizment','n','The result of strategizing','plan outcome','B2'],
      ['strategizance','n','The state of strategizing','plan state','B2'],
      ['strategizence','n','The quality of strategizing','plan quality','B2'],
      ['strategizal','n','An act of strategizing','plan event','C1'],
      ['strategizer','n','One who strategizes','plan person','B2'],
      ['strategizor','n','One who strategizes','plan agent','B2'],
      ['strategizee','n','One who is strategized','plan recipient','C1'],
      ['strategizable','adj','Capable of being strategized','plan,possible','C1'],
      ['strategizible','adj','Able to be strategized','plan,feasible','C1'],
      ['strategizive','adj','Tending to strategize','plan,active','B2'],
      ['strategizing','adj','Currently strategizing','plan,ongoing','B2'],
      ['strategized','adj','Having been strategized','plan,completed','B2'],
      ['restrategize','v','To strategize again','plan again,repeat','B2'],
      ['unstrategize','v','To reverse strategizing','reverse,undo','C1'],
      ['overstrategize','v','To strategize excessively','excess,too much','C1'],
      ['understrategize','v','To strategize insufficiently','insufficient,inadequate','C1'],
      ['misstrategize','v','To strategize incorrectly','wrongly,incorrectly','C1'],
      ['prestrategize','v','To strategize beforehand','before,in advance','C1'],
      ['costrategize','v','To strategize together','jointly,together','C1'],
      ['restrategization','n','The act of strategizing again','re-plan','C1'],
      ['overstrategization','n','Excessive strategizing','excess plan','C1'],
      ['dope','v','To use prohibited performance drugs','drug,cheat,enhance illegally','B2'],
      ['dopation','n','The act of doping','drug process','B2'],
      ['dopment','n','The result of doping','drug outcome','B2'],
      ['dopance','n','The state of doping','drug state','B2'],
      ['dopence','n','The quality of doping','drug quality','B2'],
      ['dopal','n','An act of doping','drug event','C1'],
      ['doper','n','One who dopes','drug person','B2'],
      ['dopor','n','One who dopes','drug agent','B2'],
      ['dopee','n','One who is doped','drug recipient','C1'],
      ['dopable','adj','Capable of being doped','drug,possible','C1'],
      ['dopible','adj','Able to be doped','drug,feasible','C1'],
      ['dopive','adj','Tending to dope','drug,active','B2'],
      ['doped','adj','Having been doped','drug,completed','B2'],
      ['redope','v','To dope again','drug again,repeat','B2'],
      ['undope','v','To reverse doping','reverse,undo','C1'],
      ['overdope','v','To dope excessively','excess,too much','C1'],
      ['underdope','v','To dope insufficiently','insufficient,inadequate','C1'],
      ['misdope','v','To dope incorrectly','wrongly,incorrectly','C1'],
      ['predope','v','To dope beforehand','before,in advance','C1'],
    ],
  },
  collocations: {}
};
