module.exports = {
  vocab: {
    history: [
    ['iconoclastal','adj','Relating to iconoclast','rebel-related','C1'],
    ['historiographicly','adv','In a historiographic manner','history-writing way','C2'],
    ['historiographicness','n','The quality of being historiographic','history-writing quality','C2'],
    ['unhistoriographic','adj','Not historiographic','not history-writing','C2'],
    ['paxal','adj','Relating to pax','peace era-related','C2'],
    ['annalsal','adj','Relating to annals','chronicles-related','C1'],
    ['epigraphyal','adj','Relating to epigraphy','inscription study-related','C2']
    ],
    language: [
    ['polysynthetic','adj','Having complex words expressing whole sentences','incorporating,multi-morphemic','C2'],
    ['suffix','n','A word part added to the end','ending,back attachment','B1'],
    ['onomatopoeia','n','A word imitating a natural sound','sound word,echoic word','B2'],
    ['palindrome','n','A word reading the same backwards','reversible word,mirror word','B2'],
    ['subjunctive','n','A verb mood expressing wishes or hypotheticals','conditional,wish form','C1'],
    ['gerund','n','A verb form functioning as a noun','verbal noun,-ing form','B2'],
    ['infinitive','n','The base form of a verb','root form,to-form,base verb','B1'],
    ['conjugation','n','The variation of verb forms','verb forms,inflection,declension','B2'],
    ['declension','n','The variation of noun forms','case system,inflection,noun forms','C1'],
    ['anacoluthon','n','A sentence with an inconsistent grammatical structure','broken syntax,grammatical shift','C2'],
    ['hapax legomenon','n','A word occurring only once in a text','unique word,single occurrence','C2'],
    ['wordal','adj','Relating to word','term-related','A2'],
    ['grammaral','adj','Relating to grammar','syntax-related','A2'],
    ['pronouncation','n','The act or process of pronouncing','articulate process,enunciate process,say process','A2'],
    ['pronouncer','n','A person who pronounces','articulate person,enunciate person,say person','B1'],
    ['pronouncable','adj','Able to be pronounced','articulate,possible','B1'],
    ['pronouncing','n','The process of pronouncing something','articulate activity','A2'],
    ['translatation','n','The act or process of translating','interpret process,convert process,render process','A2'],
    ['translater','n','A person who translates','interpret person,convert person,render person','B1'],
    ['translatable','adj','Able to be translated','interpret,possible','B1'],
    ['translating','n','The process of translating something','interpret activity','A2'],
    ['alphabetal','adj','Relating to alphabet','letters-related','A2'],
    ['vocabularyal','adj','Relating to vocabulary','lexicon-related','B1'],
    ['dialectal','adj','Relating to dialect','vernacular-related','B1'],
    ['idiomal','adj','Relating to idiom','expression-related','B1'],
    ['bilingually','adv','In a bilingual manner','dual-language way','B1'],
    ['bilingualness','n','The quality of being bilingual','dual-language quality','B2'],
    ['unbilingual','adj','Not bilingual','not dual-language','B1'],
    ['synonymal','adj','Relating to synonym','equivalent-related','B1'],
    ['antonymal','adj','Relating to antonym','opposite-related','B1'],
    ['syntaxal','adj','Relating to syntax','sentence structure-related','B2'],
    ['morphologyal','adj','Relating to morphology','word formation-related','B2'],
    ['phoneticsal','adj','Relating to phonetics','sound science-related','B2'],
    ['semanticsal','adj','Relating to semantics','meaning study-related','B2'],
    ['etymologyal','adj','Relating to etymology','word history-related','B2'],
    ['sociolinguisticsal','adj','Relating to sociolinguistics','language-society link-related','C1'],
    ['creoleal','adj','Relating to creole','mixed language-related','C1'],
    ['agglutinatively','adv','In a agglutinative manner','combining way','C2'],
    ['agglutinativeness','n','The quality of being agglutinative','combining quality','C2'],
    ['unagglutinative','adj','Not agglutinative','not combining','C2'],
    ['polysyntheticly','adv','In a polysynthetic manner','incorporating way','C2'],
    ['polysyntheticness','n','The quality of being polysynthetic','incorporating quality','C2'],
    ['unpolysynthetic','adj','Not polysynthetic','not incorporating','C2'],
    ['vowelal','adj','Relating to vowel','open sound-related','A2'],
    ['consonantal','adj','Relating to consonant','closed sound-related','A2'],
    ['prefixal','adj','Relating to prefix','beginning-related','B1'],
    ['suffixal','adj','Relating to suffix','ending-related','B1'],
    ['metaphoral','adj','Relating to metaphor','comparison-related','B1'],
    ['simileal','adj','Relating to simile','comparison-related','B1'],
    ['colloquialismal','adj','Relating to colloquialism','slang-related','B2'],
    ['neologismal','adj','Relating to neologism','new word-related','C1'],
    ['onomatopoeiaal','adj','Relating to onomatopoeia','sound word-related','B2'],
    ['palindromeal','adj','Relating to palindrome','reversible word-related','B2'],
    ['portmanteaual','adj','Relating to portmanteau','blend-related','C1'],
    ['cognateal','adj','Relating to cognate','related word-related','C1'],
    ['diphthongal','adj','Relating to diphthong','double vowel-related','C1'],
    ['subjunctiveal','adj','Relating to subjunctive','conditional-related','C1'],
    ['gerundal','adj','Relating to gerund','verbal noun-related','B2'],
    ['infinitiveal','adj','Relating to infinitive','root form-related','B1'],
    ['conjugational','adj','Relating to conjugation','verb forms-related','B2'],
    ['declensional','adj','Relating to declension','case system-related','C1'],
    ['anacoluthonal','adj','Relating to anacoluthon','broken syntax-related','C2']
    ],
    globalization: [
    ['neo-colonialism','n','Indirect control over developing nations','modern imperialism,economic control','C1'],
    ['Westphalian','adj','Relating to nation-state sovereignty','sovereignty-based,nation-centred','C2'],
    ['parochial','adj','Having a narrow outlook','insular,provincial,narrow-minded','C1'],
    ['deterritorialise','v','To weaken the connection between culture and place','delocalize,unroot,displace','C2'],
    ['glocal','adj','Both global and local in scope','globally local,hybrid,blended','C2'],
    ['offshoring','n','Moving business operations to another country','relocation,foreign outsourcing','B2'],
    ['soft power','n','Influence through culture rather than force','cultural influence,diplomatic power','C1'],
    ['hard power','n','Influence through military or economic force','coercive power,military strength','C1'],
    ['Bretton Woods','n','The post-WW2 financial system agreement','monetary order,international finance system','C2'],
    ['neoliberal','adj','Favouring free-market capitalism','free-market,deregulatory,pro-business','C1'],
    ['tradeal','adj','Relating to trade','commerce-related','A2'],
    ['foreignly','adv','In a foreign manner','international way','A2'],
    ['foreignness','n','The quality of being foreign','international quality','B1'],
    ['unforeign','adj','Not foreign','not international','A2'],
    ['cultureal','adj','Relating to culture','traditions-related','A2'],
    ['connectation','n','The act or process of connecting','link process,unite process,bridge process','A2'],
    ['connecter','n','A person who connects','link person,unite person,bridge person','B1'],
    ['connectable','adj','Able to be connectd','link,possible','B1'],
    ['connecting','n','The process of connecting something','link activity','A2'],
    ['worldal','adj','Relating to world','globe-related','A2'],
    ['internationally','adv','In a international manner','global way','B1'],
    ['internationalness','n','The quality of being international','global quality','B2'],
    ['uninternational','adj','Not international','not global','B1'],
    ['exportation','n','The act or process of exporting','ship process,sell abroad process,trade process','B1'],
    ['exporter','n','A person who exports','ship person,sell abroad person,trade person','B2'],
    ['exportable','adj','Able to be exportd','ship,possible','B2'],
    ['exporting','n','The process of exporting something','ship activity','B1'],
    ['importation','n','The act or process of importing','buy from abroad process,receive process,ship in process','B1'],
    ['importer','n','A person who imports','buy from abroad person,receive person,ship in person','B2'],
    ['importable','adj','Able to be importd','buy from abroad,possible','B2'],
    ['importing','n','The process of importing something','buy from abroad activity','B1'],
    ['multinationally','adv','In a multinational manner','global way','B1'],
    ['multinationalness','n','The quality of being multinational','global quality','B2'],
    ['unmultinational','adj','Not multinational','not global','B1'],
    ['immigrational','adj','Relating to immigration','migration-related','B1'],
    ['outsourcingal','adj','Relating to outsourcing','offshoring-related','B1'],
    ['liberaliser','n','A person who liberalises','deregulate person,open up person,free person','C1'],
    ['liberalisable','adj','Able to be liberalised','deregulate,possible','C1'],
    ['liberalising','n','The process of liberalising something','deregulate activity','B2'],
    ['homogenisational','adj','Relating to homogenisation','standardisation-related','B2'],
    ['rapprochemental','adj','Relating to rapprochement','reconciliation-related','C1'],
    ['Westphalianly','adv','In a Westphalian manner','sovereignty-based way','C2'],
    ['Westphalianness','n','The quality of being Westphalian','sovereignty-based quality','C2'],
    ['unWestphalian','adj','Not Westphalian','not sovereignty-based','C2'],
    ['borderal','adj','Relating to border','frontier-related','A2'],
    ['remittanceal','adj','Relating to remittance','transfer-related','B2'],
    ['embargoal','adj','Relating to embargo','trade ban-related','B2'],
    ['transnationally','adv','In a transnational manner','cross-border way','B2'],
    ['transnationalness','n','The quality of being transnational','cross-border quality','C1'],
    ['untransnational','adj','Not transnational','not cross-border','B2'],
    ['parochially','adv','In a parochial manner','insular way','C1'],
    ['parochialness','n','The quality of being parochial','insular quality','C2'],
    ['unparochial','adj','Not parochial','not insular','C1'],
    ['ethnocentricly','adv','In a ethnocentric manner','culture-biased way','C1'],
    ['ethnocentricness','n','The quality of being ethnocentric','culture-biased quality','C2'],
    ['unethnocentric','adj','Not ethnocentric','not culture-biased','C1'],
    ['deterritorialisation','n','The act or process of deterritorialising','delocalize process,unroot process,displace process','C2'],
    ['deterritorialiser','n','A person who deterritorialises','delocalize person,unroot person,displace person','C2'],
    ['deterritorialisable','adj','Able to be deterritorialised','delocalize,possible','C2'],
    ['deterritorialising','n','The process of deterritorialising something','delocalize activity','C2'],
    ['glocally','adv','In a glocal manner','globally local way','C2'],
    ['glocalness','n','The quality of being glocal','globally local quality','C2'],
    ['unglocal','adj','Not glocal','not globally local','C2'],
    ['offshoringal','adj','Relating to offshoring','relocation-related','B2'],
    ['bilaterally','adv','In a bilateral manner','two-sided way','B2'],
    ['bilateralness','n','The quality of being bilateral','two-sided quality','C1'],
    ['unbilateral','adj','Not bilateral','not two-sided','B2'],
    ['multilaterally','adv','In a multilateral manner','many-sided way','B2'],
    ['multilateralness','n','The quality of being multilateral','many-sided quality','C1'],
    ['unmultilateral','adj','Not multilateral','not many-sided','B2'],
    ['neoliberally','adv','In a neoliberal manner','free-market way','C1'],
    ['neoliberalness','n','The quality of being neoliberal','free-market quality','C2'],
    ['unneoliberal','adj','Not neoliberal','not free-market','C1']
    ],
  },
  collocations: {
  }
};
