// Auto-generated vocab boost group 48
module.exports = {
  vocab: {
    economy: [
      ['deflatence','n','The quality of deflating','decrease quality','C1'],
      ['deflatal','n','An act of deflating','decrease event','C2'],
      ['deflater','n','One who deflates','decrease person','C1'],
      ['deflator','n','One who deflates','decrease agent','C1'],
      ['deflatee','n','One who is deflated','decrease recipient','C2'],
      ['deflatable','adj','Capable of being deflated','decrease,possible','C2'],
      ['deflatible','adj','Able to be deflated','decrease,feasible','C2'],
      ['deflative','adj','Tending to deflate','decrease,active','C1'],
      ['deflating','adj','Currently deflating','decrease,ongoing','C1'],
      ['deflated','adj','Having been deflated','decrease,completed','C1'],
      ['redeflate','v','To deflate again','decrease again,repeat','C1'],
      ['undeflate','v','To reverse deflating','reverse,undo','C2'],
      ['overdeflate','v','To deflate excessively','excess,too much','C2'],
      ['underdeflate','v','To deflate insufficiently','insufficient,inadequate','C2'],
      ['misdeflate','v','To deflate incorrectly','wrongly,incorrectly','C2'],
      ['predeflate','v','To deflate beforehand','before,in advance','C2'],
      ['codeflate','v','To deflate together','jointly,together','C2'],
      ['redeflatation','n','The act of deflating again','re-decrease','C2'],
      ['overdeflatation','n','Excessive deflating','excess decrease','C2'],
      ['deregulate','v','To remove government regulations','liberalize,free,open up','C1'],
      ['deregulatation','n','The act of deregulating','liberalize process','C1'],
      ['deregulatment','n','The result of deregulating','liberalize outcome','C1'],
      ['deregulatance','n','The state of deregulating','liberalize state','C1'],
      ['deregulatence','n','The quality of deregulating','liberalize quality','C1'],
      ['deregulatal','n','An act of deregulating','liberalize event','C2'],
      ['deregulater','n','One who deregulates','liberalize person','C1'],
      ['deregulator','n','One who deregulates','liberalize agent','C1'],
      ['deregulatee','n','One who is deregulated','liberalize recipient','C2'],
      ['deregulatable','adj','Capable of being deregulated','liberalize,possible','C2'],
      ['deregulatible','adj','Able to be deregulated','liberalize,feasible','C2'],
      ['deregulative','adj','Tending to deregulate','liberalize,active','C1'],
      ['deregulating','adj','Currently deregulating','liberalize,ongoing','C1'],
      ['deregulated','adj','Having been deregulated','liberalize,completed','C1'],
      ['rederegulate','v','To deregulate again','liberalize again,repeat','C1'],
      ['underegulate','v','To reverse deregulating','reverse,undo','C2'],
      ['overderegulate','v','To deregulate excessively','excess,too much','C2'],
      ['underderegulate','v','To deregulate insufficiently','insufficient,inadequate','C2'],
      ['misderegulate','v','To deregulate incorrectly','wrongly,incorrectly','C2'],
      ['prederegulate','v','To deregulate beforehand','before,in advance','C2'],
      ['coderegulate','v','To deregulate together','jointly,together','C2'],
      ['rederegulatation','n','The act of deregulating again','re-liberalize','C2'],
      ['overderegulatation','n','Excessive deregulating','excess liberalize','C2'],
      ['liberalize','v','To remove restrictions on trade','open up,deregulate,free','B2'],
      ['liberalizment','n','The result of liberalizing','open up outcome','B2'],
      ['liberalizance','n','The state of liberalizing','open up state','B2'],
      ['liberalizence','n','The quality of liberalizing','open up quality','B2'],
      ['liberalizal','n','An act of liberalizing','open up event','C1'],
      ['liberalizer','n','One who liberalizes','open up person','B2'],
      ['liberalizor','n','One who liberalizes','open up agent','B2'],
      ['liberalizee','n','One who is liberalized','open up recipient','C1'],
      ['liberalizable','adj','Capable of being liberalized','open up,possible','C1'],
      ['liberalizible','adj','Able to be liberalized','open up,feasible','C1'],
      ['liberalizive','adj','Tending to liberalize','open up,active','B2'],
      ['liberalizing','adj','Currently liberalizing','open up,ongoing','B2'],
      ['liberalized','adj','Having been liberalized','open up,completed','B2'],
      ['reliberalize','v','To liberalize again','open up again,repeat','B2'],
      ['unliberalize','v','To reverse liberalizing','reverse,undo','C1'],
      ['overliberalize','v','To liberalize excessively','excess,too much','C1'],
      ['underliberalize','v','To liberalize insufficiently','insufficient,inadequate','C1'],
      ['misliberalize','v','To liberalize incorrectly','wrongly,incorrectly','C1'],
      ['preliberalize','v','To liberalize beforehand','before,in advance','C1'],
      ['coliberalize','v','To liberalize together','jointly,together','C1'],
      ['reliberalization','n','The act of liberalizing again','re-open up','C1'],
      ['overliberalization','n','Excessive liberalizing','excess open up','C1'],
      ['nationalizment','n','The result of nationalizing','socialize outcome','C1'],
      ['nationalizance','n','The state of nationalizing','socialize state','C1'],
      ['nationalizence','n','The quality of nationalizing','socialize quality','C1'],
      ['nationalizal','n','An act of nationalizing','socialize event','C2'],
      ['nationalizer','n','One who nationalizes','socialize person','C1'],
      ['nationalizor','n','One who nationalizes','socialize agent','C1'],
      ['nationalizee','n','One who is nationalized','socialize recipient','C2'],
      ['nationalizable','adj','Capable of being nationalized','socialize,possible','C2'],
      ['nationalizible','adj','Able to be nationalized','socialize,feasible','C2'],
      ['nationalizive','adj','Tending to nationalize','socialize,active','C1'],
      ['nationalizing','adj','Currently nationalizing','socialize,ongoing','C1'],
      ['nationalized','adj','Having been nationalized','socialize,completed','C1'],
      ['renationalize','v','To nationalize again','socialize again,repeat','C1'],
      ['unnationalize','v','To reverse nationalizing','reverse,undo','C2'],
      ['overnationalize','v','To nationalize excessively','excess,too much','C2'],
      ['undernationalize','v','To nationalize insufficiently','insufficient,inadequate','C2'],
      ['misnationalize','v','To nationalize incorrectly','wrongly,incorrectly','C2'],
      ['prenationalize','v','To nationalize beforehand','before,in advance','C2'],
      ['conationalize','v','To nationalize together','jointly,together','C2'],
      ['renationalization','n','The act of nationalizing again','re-socialize','C2'],
      ['overnationalization','n','Excessive nationalizing','excess socialize','C2'],
      ['privatizment','n','The result of privatizing','sell off outcome','B2'],
      ['privatizance','n','The state of privatizing','sell off state','B2'],
      ['privatizence','n','The quality of privatizing','sell off quality','B2'],
      ['privatizal','n','An act of privatizing','sell off event','C1'],
      ['privatizer','n','One who privatizes','sell off person','B2'],
      ['privatizor','n','One who privatizes','sell off agent','B2'],
      ['privatizee','n','One who is privatized','sell off recipient','C1'],
      ['privatizable','adj','Capable of being privatized','sell off,possible','C1'],
      ['privatizible','adj','Able to be privatized','sell off,feasible','C1'],
      ['privatizive','adj','Tending to privatize','sell off,active','B2'],
      ['privatizing','adj','Currently privatizing','sell off,ongoing','B2'],
      ['privatized','adj','Having been privatized','sell off,completed','B2'],
      ['reprivatize','v','To privatize again','sell off again,repeat','B2'],
      ['unprivatize','v','To reverse privatizing','reverse,undo','C1'],
      ['overprivatize','v','To privatize excessively','excess,too much','C1'],
      ['underprivatize','v','To privatize insufficiently','insufficient,inadequate','C1'],
      ['misprivatize','v','To privatize incorrectly','wrongly,incorrectly','C1'],
      ['preprivatize','v','To privatize beforehand','before,in advance','C1'],
      ['coprivatize','v','To privatize together','jointly,together','C1'],
      ['reprivatization','n','The act of privatizing again','re-sell off','C1'],
      ['overprivatization','n','Excessive privatizing','excess sell off','C1'],
      ['hyperinflate','v','To inflate at an extremely high rate','spiral,skyrocket,surge','C1'],
      ['hyperinflatation','n','The act of hyperinflating','spiral process','C1'],
      ['hyperinflatment','n','The result of hyperinflating','spiral outcome','C1'],
      ['hyperinflatance','n','The state of hyperinflating','spiral state','C1'],
      ['hyperinflatence','n','The quality of hyperinflating','spiral quality','C1'],
      ['hyperinflatal','n','An act of hyperinflating','spiral event','C2'],
      ['hyperinflater','n','One who hyperinflates','spiral person','C1'],
      ['hyperinflator','n','One who hyperinflates','spiral agent','C1'],
      ['hyperinflatee','n','One who is hyperinflated','spiral recipient','C2'],
      ['hyperinflatable','adj','Capable of being hyperinflated','spiral,possible','C2'],
      ['hyperinflatible','adj','Able to be hyperinflated','spiral,feasible','C2'],
      ['hyperinflative','adj','Tending to hyperinflate','spiral,active','C1'],
      ['hyperinflating','adj','Currently hyperinflating','spiral,ongoing','C1'],
      ['hyperinflated','adj','Having been hyperinflated','spiral,completed','C1'],
      ['rehyperinflate','v','To hyperinflate again','spiral again,repeat','C1'],
      ['unhyperinflate','v','To reverse hyperinflating','reverse,undo','C2'],
      ['overhyperinflate','v','To hyperinflate excessively','excess,too much','C2'],
      ['underhyperinflate','v','To hyperinflate insufficiently','insufficient,inadequate','C2'],
      ['mishyperinflate','v','To hyperinflate incorrectly','wrongly,incorrectly','C2'],
      ['prehyperinflate','v','To hyperinflate beforehand','before,in advance','C2'],
      ['cohyperinflate','v','To hyperinflate together','jointly,together','C2'],
      ['rehyperinflatation','n','The act of hyperinflating again','re-spiral','C2'],
      ['overhyperinflatation','n','Excessive hyperinflating','excess spiral','C2'],
      ['monetize','v','To convert into a source of income','commercialize,profit from,capitalize','B2'],
      ['monetization','n','The act of monetizing','commercialize process','B2'],
      ['monetizment','n','The result of monetizing','commercialize outcome','B2'],
      ['monetizance','n','The state of monetizing','commercialize state','B2'],
      ['monetizence','n','The quality of monetizing','commercialize quality','B2'],
      ['monetizal','n','An act of monetizing','commercialize event','C1'],
      ['monetizer','n','One who monetizes','commercialize person','B2'],
      ['monetizor','n','One who monetizes','commercialize agent','B2'],
      ['monetizee','n','One who is monetized','commercialize recipient','C1'],
      ['monetizable','adj','Capable of being monetized','commercialize,possible','C1'],
      ['monetizible','adj','Able to be monetized','commercialize,feasible','C1'],
      ['monetizive','adj','Tending to monetize','commercialize,active','B2'],
      ['monetizing','adj','Currently monetizing','commercialize,ongoing','B2'],
      ['monetized','adj','Having been monetized','commercialize,completed','B2'],
      ['remonetize','v','To monetize again','commercialize again,repeat','B2'],
      ['unmonetize','v','To reverse monetizing','reverse,undo','C1'],
      ['overmonetize','v','To monetize excessively','excess,too much','C1'],
      ['undermonetize','v','To monetize insufficiently','insufficient,inadequate','C1'],
      ['mismonetize','v','To monetize incorrectly','wrongly,incorrectly','C1'],
      ['premonetize','v','To monetize beforehand','before,in advance','C1'],
      ['comonetize','v','To monetize together','jointly,together','C1'],
      ['remonetization','n','The act of monetizing again','re-commercialize','C1'],
      ['overmonetization','n','Excessive monetizing','excess commercialize','C1'],
      ['recapitalizment','n','The result of recapitalizing','refinance outcome','C1'],
      ['recapitalizance','n','The state of recapitalizing','refinance state','C1'],
      ['recapitalizence','n','The quality of recapitalizing','refinance quality','C1'],
      ['recapitalizal','n','An act of recapitalizing','refinance event','C2'],
      ['recapitalizer','n','One who recapitalizes','refinance person','C1'],
      ['recapitalizor','n','One who recapitalizes','refinance agent','C1'],
      ['recapitalizee','n','One who is recapitalized','refinance recipient','C2'],
      ['recapitalizable','adj','Capable of being recapitalized','refinance,possible','C2'],
      ['recapitalizible','adj','Able to be recapitalized','refinance,feasible','C2'],
      ['recapitalizive','adj','Tending to recapitalize','refinance,active','C1'],
      ['recapitalizing','adj','Currently recapitalizing','refinance,ongoing','C1'],
      ['recapitalized','adj','Having been recapitalized','refinance,completed','C1'],
      ['rerecapitalize','v','To recapitalize again','refinance again,repeat','C1'],
      ['unrecapitalize','v','To reverse recapitalizing','reverse,undo','C2'],
      ['overrecapitalize','v','To recapitalize excessively','excess,too much','C2'],
      ['underrecapitalize','v','To recapitalize insufficiently','insufficient,inadequate','C2'],
      ['misrecapitalize','v','To recapitalize incorrectly','wrongly,incorrectly','C2'],
      ['prerecapitalize','v','To recapitalize beforehand','before,in advance','C2'],
      ['corecapitalize','v','To recapitalize together','jointly,together','C2'],
      ['rerecapitalization','n','The act of recapitalizing again','re-refinance','C2'],
      ['overrecapitalization','n','Excessive recapitalizing','excess refinance','C2'],
      ['inflationarily','adv','In a inflationary manner','price-rising way','B2'],
      ['inflationarness','n','The quality of being inflationary','price-rising quality','B2'],
      ['inflationarity','n','The state of being inflationary','price-rising condition','C1'],
      ['uninflationary','adj','Not inflationary','not price-rising','B2'],
      ['ininflationary','adj','Not inflationary','not price-rising','C1'],
      ['noninflationary','adj','Not inflationary','not price-rising','B2'],
      ['semiinflationary','adj','Partially inflationary','partly price-rising','C1'],
      ['overinflationary','adj','Excessively inflationary','too price-rising','C1'],
      ['ultrainflationary','adj','Extremely inflationary','very price-rising','C1'],
      ['deflationarness','n','The quality of being deflationary','price-falling quality','C1'],
      ['deflationarity','n','The state of being deflationary','price-falling condition','C2'],
      ['indeflationary','adj','Not deflationary','not price-falling','C2'],
      ['nondeflationary','adj','Not deflationary','not price-falling','C1'],
      ['semideflationary','adj','Partially deflationary','partly price-falling','C2'],
      ['overdeflationary','adj','Excessively deflationary','too price-falling','C2'],
      ['ultradeflationary','adj','Extremely deflationary','very price-falling','C2'],
      ['recessionarily','adv','In a recessionary manner','contractionary way','C1'],
      ['recessionarness','n','The quality of being recessionary','contractionary quality','C1'],
      ['recessionarity','n','The state of being recessionary','contractionary condition','C2'],
      ['unrecessionary','adj','Not recessionary','not contractionary','C1'],
      ['inrecessionary','adj','Not recessionary','not contractionary','C2'],
      ['nonrecessionary','adj','Not recessionary','not contractionary','C1'],
      ['semirecessionary','adj','Partially recessionary','partly contractionary','C2'],
      ['overrecessionary','adj','Excessively recessionary','too contractionary','C2'],
      ['ultrarecessionary','adj','Extremely recessionary','very contractionary','C2'],
      ['fiscality','n','The state of being fiscal','financial condition','C1'],
      ['infiscal','adj','Not fiscal','not financial','C1'],
      ['nonfiscal','adj','Not fiscal','not financial','B2'],
      ['semifiscal','adj','Partially fiscal','partly financial','C1'],
      ['overfiscal','adj','Excessively fiscal','too financial','C1'],
      ['ultrafiscal','adj','Extremely fiscal','very financial','C1'],
      ['monetarness','n','The quality of being monetary','financial quality','B2'],
      ['monetarity','n','The state of being monetary','financial condition','C1'],
      ['inmonetary','adj','Not monetary','not financial','C1'],
      ['nonmonetary','adj','Not monetary','not financial','B2'],
      ['semimonetary','adj','Partially monetary','partly financial','C1'],
      ['overmonetary','adj','Excessively monetary','too financial','C1'],
      ['ultramonetary','adj','Extremely monetary','very financial','C1'],
      ['macroeconomicity','n','The state of being macroeconomic','national condition','C1'],
      ['inmacroeconomic','adj','Not macroeconomic','not national','C1'],
      ['nonmacroeconomic','adj','Not macroeconomic','not national','B2'],
      ['semimacroeconomic','adj','Partially macroeconomic','partly national','C1'],
      ['overmacroeconomic','adj','Excessively macroeconomic','too national','C1'],
      ['ultramacroeconomic','adj','Extremely macroeconomic','very national','C1'],
      ['microeconomicity','n','The state of being microeconomic','individual condition','C2'],
      ['inmicroeconomic','adj','Not microeconomic','not individual','C2'],
      ['nonmicroeconomic','adj','Not microeconomic','not individual','C1'],
      ['semimicroeconomic','adj','Partially microeconomic','partly individual','C2'],
      ['overmicroeconomic','adj','Excessively microeconomic','too individual','C2'],
      ['ultramicroeconomic','adj','Extremely microeconomic','very individual','C2'],
      ['recessionic','adj','Of or relating to recession','downturn-based,characteristic','B2'],
      ['recessionous','adj','Full of recession','downturn-filled,abundant','C1'],
      ['recessionful','adj','Full of recession','downturn-rich,abounding','B2'],
      ['recessionless','adj','Without recession','lacking,without','B2'],
      ['recessionism','n','The ideology of recession','downturn ideology,doctrine','C1'],
      ['recessionist','n','A person focused on recession','downturn specialist,advocate','C1'],
      ['recessionise','v','To make into recession','downturn,convert','C1'],
      ['recessionize','v','To make or become recession','downturn,transform','C1'],
      ['antirecession','adj','Opposed to recession','against,opposing','C1'],
      ['nonrecession','adj','Not involving recession','without,lacking','B2'],
      ['prerecession','n','Before recession','preceding,prior','C1'],
      ['postrecession','n','After recession','following,subsequent','C1'],
      ['subrecession','n','A subdivision of recession','subset,branch','C1'],
      ['multirecession','adj','Involving many recessions','multiple,several','C1'],
      ['interrecession','adj','Between recessions','cross,between','C1'],
      ['inflationic','adj','Of or relating to inflation','price rise-based,characteristic','B2'],
      ['inflationous','adj','Full of inflation','price rise-filled,abundant','C1'],
      ['inflationful','adj','Full of inflation','price rise-rich,abounding','B2'],
      ['inflationless','adj','Without inflation','lacking,without','B2'],
      ['inflationism','n','The ideology of inflation','price rise ideology,doctrine','C1'],
      ['inflationist','n','A person focused on inflation','price rise specialist,advocate','C1'],
      ['inflationise','v','To make into inflation','price rise,convert','C1'],
      ['inflationize','v','To make or become inflation','price rise,transform','C1'],
      ['antiinflation','adj','Opposed to inflation','against,opposing','C1'],
      ['noninflation','adj','Not involving inflation','without,lacking','B2'],
      ['preinflation','n','Before inflation','preceding,prior','C1'],
      ['postinflation','n','After inflation','following,subsequent','C1'],
    ],
  },
  collocations: {}
};
