// Auto-generated vocab boost group 37
module.exports = {
  vocab: {
    education: [
      ['multibenchmark','adj','Involving many benchmarks','multiple,several','C1'],
      ['interbenchmark','adj','Between benchmarks','cross,between','C1'],
    ],
    technology: [
      ['automatation','n','The act of automating','mechanize process','B2'],
      ['automatment','n','The result of automating','mechanize outcome','B2'],
      ['automatance','n','The state of automating','mechanize state','B2'],
      ['automatence','n','The quality of automating','mechanize quality','B2'],
      ['automatal','n','An act of automating','mechanize event','C1'],
      ['automater','n','One who automates','mechanize person','B2'],
      ['automator','n','One who automates','mechanize agent','B2'],
      ['automatee','n','One who is automated','mechanize recipient','C1'],
      ['automatable','adj','Capable of being automated','mechanize,possible','C1'],
      ['automatible','adj','Able to be automated','mechanize,feasible','C1'],
      ['automative','adj','Tending to automate','mechanize,active','B2'],
      ['automating','adj','Currently automating','mechanize,ongoing','B2'],
      ['automated','adj','Having been automated','mechanize,completed','B2'],
      ['reautomate','v','To automate again','mechanize again,repeat','B2'],
      ['unautomate','v','To reverse automating','reverse,undo','C1'],
      ['overautomate','v','To automate excessively','excess,too much','C1'],
      ['underautomate','v','To automate insufficiently','insufficient,inadequate','C1'],
      ['misautomate','v','To automate incorrectly','wrongly,incorrectly','C1'],
      ['preautomate','v','To automate beforehand','before,in advance','C1'],
      ['coautomate','v','To automate together','jointly,together','C1'],
      ['reautomatation','n','The act of automating again','re-mechanize','C1'],
      ['overautomatation','n','Excessive automating','excess mechanize','C1'],
      ['digitize','v','To convert data to digital format','convert,encode,scan','B2'],
      ['digitization','n','The act of digitizing','convert process','B2'],
      ['digitizment','n','The result of digitizing','convert outcome','B2'],
      ['digitizance','n','The state of digitizing','convert state','B2'],
      ['digitizence','n','The quality of digitizing','convert quality','B2'],
      ['digitizal','n','An act of digitizing','convert event','C1'],
      ['digitizer','n','One who digitizes','convert person','B2'],
      ['digitizor','n','One who digitizes','convert agent','B2'],
      ['digitizee','n','One who is digitized','convert recipient','C1'],
      ['digitizable','adj','Capable of being digitized','convert,possible','C1'],
      ['digitizible','adj','Able to be digitized','convert,feasible','C1'],
      ['digitizive','adj','Tending to digitize','convert,active','B2'],
      ['digitizing','adj','Currently digitizing','convert,ongoing','B2'],
      ['digitized','adj','Having been digitized','convert,completed','B2'],
      ['redigitize','v','To digitize again','convert again,repeat','B2'],
      ['undigitize','v','To reverse digitizing','reverse,undo','C1'],
      ['overdigitize','v','To digitize excessively','excess,too much','C1'],
      ['underdigitize','v','To digitize insufficiently','insufficient,inadequate','C1'],
      ['misdigitize','v','To digitize incorrectly','wrongly,incorrectly','C1'],
      ['predigitize','v','To digitize beforehand','before,in advance','C1'],
      ['codigitize','v','To digitize together','jointly,together','C1'],
      ['redigitization','n','The act of digitizing again','re-convert','C1'],
      ['overdigitization','n','Excessive digitizing','excess convert','C1'],
      ['encryptation','n','The act of encrypting','encode process','B2'],
      ['encryptment','n','The result of encrypting','encode outcome','B2'],
      ['encryptance','n','The state of encrypting','encode state','B2'],
      ['encryptence','n','The quality of encrypting','encode quality','B2'],
      ['encryptal','n','An act of encrypting','encode event','C1'],
      ['encrypter','n','One who encrypts','encode person','B2'],
      ['encryptor','n','One who encrypts','encode agent','B2'],
      ['encryptee','n','One who is encryptd','encode recipient','C1'],
      ['encryptable','adj','Capable of being encryptd','encode,possible','C1'],
      ['encryptible','adj','Able to be encryptd','encode,feasible','C1'],
      ['encryptive','adj','Tending to encrypt','encode,active','B2'],
      ['encrypting','adj','Currently encrypting','encode,ongoing','B2'],
      ['encrypted','adj','Having been encryptd','encode,completed','B2'],
      ['reencrypt','v','To encrypt again','encode again,repeat','B2'],
      ['unencrypt','v','To reverse encrypting','reverse,undo','C1'],
      ['overencrypt','v','To encrypt excessively','excess,too much','C1'],
      ['underencrypt','v','To encrypt insufficiently','insufficient,inadequate','C1'],
      ['misencrypt','v','To encrypt incorrectly','wrongly,incorrectly','C1'],
      ['preencrypt','v','To encrypt beforehand','before,in advance','C1'],
      ['coencrypt','v','To encrypt together','jointly,together','C1'],
      ['reencryptation','n','The act of encrypting again','re-encode','C1'],
      ['overencryptation','n','Excessive encrypting','excess encode','C1'],
      ['optimization','n','The act of optimizing','improve process','B2'],
      ['optimizment','n','The result of optimizing','improve outcome','B2'],
      ['optimizance','n','The state of optimizing','improve state','B2'],
      ['optimizence','n','The quality of optimizing','improve quality','B2'],
      ['optimizal','n','An act of optimizing','improve event','C1'],
      ['optimizer','n','One who optimizes','improve person','B2'],
      ['optimizor','n','One who optimizes','improve agent','B2'],
      ['optimizee','n','One who is optimized','improve recipient','C1'],
      ['optimizable','adj','Capable of being optimized','improve,possible','C1'],
      ['optimizible','adj','Able to be optimized','improve,feasible','C1'],
      ['optimizive','adj','Tending to optimize','improve,active','B2'],
      ['optimizing','adj','Currently optimizing','improve,ongoing','B2'],
      ['optimized','adj','Having been optimized','improve,completed','B2'],
      ['reoptimize','v','To optimize again','improve again,repeat','B2'],
      ['unoptimize','v','To reverse optimizing','reverse,undo','C1'],
      ['overoptimize','v','To optimize excessively','excess,too much','C1'],
      ['underoptimize','v','To optimize insufficiently','insufficient,inadequate','C1'],
      ['misoptimize','v','To optimize incorrectly','wrongly,incorrectly','C1'],
      ['preoptimize','v','To optimize beforehand','before,in advance','C1'],
      ['cooptimize','v','To optimize together','jointly,together','C1'],
      ['reoptimization','n','The act of optimizing again','re-improve','C1'],
      ['overoptimization','n','Excessive optimizing','excess improve','C1'],
      ['calibratation','n','The act of calibrating','adjust process','C1'],
      ['calibratment','n','The result of calibrating','adjust outcome','C1'],
      ['calibratance','n','The state of calibrating','adjust state','C1'],
      ['calibratence','n','The quality of calibrating','adjust quality','C1'],
      ['calibratal','n','An act of calibrating','adjust event','C2'],
      ['calibrater','n','One who calibrates','adjust person','C1'],
      ['calibrator','n','One who calibrates','adjust agent','C1'],
      ['calibratee','n','One who is calibrated','adjust recipient','C2'],
      ['calibratable','adj','Capable of being calibrated','adjust,possible','C2'],
      ['calibratible','adj','Able to be calibrated','adjust,feasible','C2'],
      ['calibrative','adj','Tending to calibrate','adjust,active','C1'],
      ['calibrating','adj','Currently calibrating','adjust,ongoing','C1'],
      ['calibrated','adj','Having been calibrated','adjust,completed','C1'],
      ['recalibrate','v','To calibrate again','adjust again,repeat','C1'],
      ['uncalibrate','v','To reverse calibrating','reverse,undo','C2'],
      ['overcalibrate','v','To calibrate excessively','excess,too much','C2'],
      ['undercalibrate','v','To calibrate insufficiently','insufficient,inadequate','C2'],
      ['miscalibrate','v','To calibrate incorrectly','wrongly,incorrectly','C2'],
      ['precalibrate','v','To calibrate beforehand','before,in advance','C2'],
      ['cocalibrate','v','To calibrate together','jointly,together','C2'],
      ['recalibratation','n','The act of calibrating again','re-adjust','C2'],
      ['overcalibratation','n','Excessive calibrating','excess adjust','C2'],
      ['configure','v','To arrange or set up a system','set up,arrange,customize','B2'],
      ['configuration','n','The act of configuring','set up process','B2'],
      ['configurment','n','The result of configuring','set up outcome','B2'],
      ['configurance','n','The state of configuring','set up state','B2'],
      ['configurence','n','The quality of configuring','set up quality','B2'],
      ['configural','n','An act of configuring','set up event','C1'],
      ['configurer','n','One who configures','set up person','B2'],
      ['configuror','n','One who configures','set up agent','B2'],
      ['configuree','n','One who is configured','set up recipient','C1'],
      ['configurable','adj','Capable of being configured','set up,possible','C1'],
      ['configurible','adj','Able to be configured','set up,feasible','C1'],
      ['configurive','adj','Tending to configure','set up,active','B2'],
      ['configuring','adj','Currently configuring','set up,ongoing','B2'],
      ['configured','adj','Having been configured','set up,completed','B2'],
      ['reconfigure','v','To configure again','set up again,repeat','B2'],
      ['unconfigure','v','To reverse configuring','reverse,undo','C1'],
      ['overconfigure','v','To configure excessively','excess,too much','C1'],
      ['underconfigure','v','To configure insufficiently','insufficient,inadequate','C1'],
      ['misconfigure','v','To configure incorrectly','wrongly,incorrectly','C1'],
      ['preconfigure','v','To configure beforehand','before,in advance','C1'],
      ['coconfigure','v','To configure together','jointly,together','C1'],
      ['reconfiguration','n','The act of configuring again','re-set up','C1'],
      ['overconfiguration','n','Excessive configuring','excess set up','C1'],
      ['debugment','n','The result of debuging','fix outcome','B2'],
      ['debugance','n','The state of debuging','fix state','B2'],
      ['debugence','n','The quality of debuging','fix quality','B2'],
      ['debugal','n','An act of debuging','fix event','C1'],
      ['debugor','n','One who debugs','fix agent','B2'],
      ['debugee','n','One who is debugd','fix recipient','C1'],
      ['debugible','adj','Able to be debugd','fix,feasible','C1'],
      ['debugive','adj','Tending to debug','fix,active','B2'],
      ['debuged','adj','Having been debugd','fix,completed','B2'],
      ['redebug','v','To debug again','fix again,repeat','B2'],
      ['undebug','v','To reverse debuging','reverse,undo','C1'],
      ['overdebug','v','To debug excessively','excess,too much','C1'],
      ['underdebug','v','To debug insufficiently','insufficient,inadequate','C1'],
      ['misdebug','v','To debug incorrectly','wrongly,incorrectly','C1'],
      ['predebug','v','To debug beforehand','before,in advance','C1'],
      ['codebug','v','To debug together','jointly,together','C1'],
      ['redebugation','n','The act of debuging again','re-fix','C1'],
      ['overdebugation','n','Excessive debuging','excess fix','C1'],
      ['integratment','n','The result of integrating','merge outcome','B2'],
      ['integratance','n','The state of integrating','merge state','B2'],
      ['integratence','n','The quality of integrating','merge quality','B2'],
      ['integratal','n','An act of integrating','merge event','C1'],
      ['integrator','n','One who integrates','merge agent','B2'],
      ['integratee','n','One who is integrated','merge recipient','C1'],
      ['integratible','adj','Able to be integrated','merge,feasible','C1'],
      ['integrative','adj','Tending to integrate','merge,active','B2'],
      ['integrated','adj','Having been integrated','merge,completed','B2'],
      ['reintegrate','v','To integrate again','merge again,repeat','B2'],
      ['unintegrate','v','To reverse integrating','reverse,undo','C1'],
      ['overintegrate','v','To integrate excessively','excess,too much','C1'],
      ['underintegrate','v','To integrate insufficiently','insufficient,inadequate','C1'],
      ['misintegrate','v','To integrate incorrectly','wrongly,incorrectly','C1'],
      ['preintegrate','v','To integrate beforehand','before,in advance','C1'],
      ['cointegrate','v','To integrate together','jointly,together','C1'],
      ['reintegratation','n','The act of integrating again','re-merge','C1'],
      ['overintegratation','n','Excessive integrating','excess merge','C1'],
      ['simulatation','n','The act of simulating','model process','B2'],
      ['simulatment','n','The result of simulating','model outcome','B2'],
      ['simulatance','n','The state of simulating','model state','B2'],
      ['simulatence','n','The quality of simulating','model quality','B2'],
      ['simulatal','n','An act of simulating','model event','C1'],
      ['simulater','n','One who simulates','model person','B2'],
      ['simulator','n','One who simulates','model agent','B2'],
      ['simulatee','n','One who is simulated','model recipient','C1'],
      ['simulatable','adj','Capable of being simulated','model,possible','C1'],
      ['simulatible','adj','Able to be simulated','model,feasible','C1'],
      ['simulative','adj','Tending to simulate','model,active','B2'],
      ['simulating','adj','Currently simulating','model,ongoing','B2'],
      ['simulated','adj','Having been simulated','model,completed','B2'],
      ['resimulate','v','To simulate again','model again,repeat','B2'],
      ['unsimulate','v','To reverse simulating','reverse,undo','C1'],
      ['oversimulate','v','To simulate excessively','excess,too much','C1'],
      ['undersimulate','v','To simulate insufficiently','insufficient,inadequate','C1'],
      ['missimulate','v','To simulate incorrectly','wrongly,incorrectly','C1'],
      ['presimulate','v','To simulate beforehand','before,in advance','C1'],
      ['cosimulate','v','To simulate together','jointly,together','C1'],
      ['resimulatation','n','The act of simulating again','re-model','C1'],
      ['oversimulatation','n','Excessive simulating','excess model','C1'],
      ['iteratment','n','The result of iterating','repeat outcome','C1'],
      ['iteratance','n','The state of iterating','repeat state','C1'],
      ['iteratence','n','The quality of iterating','repeat quality','C1'],
      ['iteratal','n','An act of iterating','repeat event','C2'],
      ['iterator','n','One who iterates','repeat agent','C1'],
      ['iteratee','n','One who is iterated','repeat recipient','C2'],
      ['iteratible','adj','Able to be iterated','repeat,feasible','C2'],
      ['iterative','adj','Tending to iterate','repeat,active','C1'],
      ['iterated','adj','Having been iterated','repeat,completed','C1'],
      ['uniterate','v','To reverse iterating','reverse,undo','C2'],
      ['overiterate','v','To iterate excessively','excess,too much','C2'],
      ['underiterate','v','To iterate insufficiently','insufficient,inadequate','C2'],
      ['misiterate','v','To iterate incorrectly','wrongly,incorrectly','C2'],
      ['preiterate','v','To iterate beforehand','before,in advance','C2'],
      ['coiterate','v','To iterate together','jointly,together','C2'],
      ['reiteratation','n','The act of iterating again','re-repeat','C2'],
      ['overiteratation','n','Excessive iterating','excess repeat','C2'],
      ['reconfigurment','n','The result of reconfiguring','rearrange outcome','B2'],
      ['reconfigurance','n','The state of reconfiguring','rearrange state','B2'],
      ['reconfigurence','n','The quality of reconfiguring','rearrange quality','B2'],
      ['reconfigural','n','An act of reconfiguring','rearrange event','C1'],
      ['reconfigurer','n','One who reconfigures','rearrange person','B2'],
      ['reconfiguror','n','One who reconfigures','rearrange agent','B2'],
      ['reconfiguree','n','One who is reconfigured','rearrange recipient','C1'],
      ['reconfigurable','adj','Capable of being reconfigured','rearrange,possible','C1'],
      ['reconfigurible','adj','Able to be reconfigured','rearrange,feasible','C1'],
      ['reconfigurive','adj','Tending to reconfigure','rearrange,active','B2'],
      ['reconfiguring','adj','Currently reconfiguring','rearrange,ongoing','B2'],
      ['reconfigured','adj','Having been reconfigured','rearrange,completed','B2'],
      ['rereconfigure','v','To reconfigure again','rearrange again,repeat','B2'],
      ['unreconfigure','v','To reverse reconfiguring','reverse,undo','C1'],
      ['overreconfigure','v','To reconfigure excessively','excess,too much','C1'],
      ['underreconfigure','v','To reconfigure insufficiently','insufficient,inadequate','C1'],
      ['misreconfigure','v','To reconfigure incorrectly','wrongly,incorrectly','C1'],
      ['prereconfigure','v','To reconfigure beforehand','before,in advance','C1'],
      ['coreconfigure','v','To reconfigure together','jointly,together','C1'],
      ['rereconfiguration','n','The act of reconfiguring again','re-rearrange','C1'],
      ['overreconfiguration','n','Excessive reconfiguring','excess rearrange','C1'],
      ['troubleshoot','v','To identify and solve problems','diagnose,fix,resolve','B2'],
      ['troubleshootation','n','The act of troubleshooting','diagnose process','B2'],
      ['troubleshootment','n','The result of troubleshooting','diagnose outcome','B2'],
      ['troubleshootance','n','The state of troubleshooting','diagnose state','B2'],
      ['troubleshootence','n','The quality of troubleshooting','diagnose quality','B2'],
      ['troubleshootal','n','An act of troubleshooting','diagnose event','C1'],
      ['troubleshooter','n','One who troubleshoots','diagnose person','B2'],
      ['troubleshootor','n','One who troubleshoots','diagnose agent','B2'],
      ['troubleshootee','n','One who is troubleshootd','diagnose recipient','C1'],
      ['troubleshootable','adj','Capable of being troubleshootd','diagnose,possible','C1'],
      ['troubleshootible','adj','Able to be troubleshootd','diagnose,feasible','C1'],
      ['troubleshootive','adj','Tending to troubleshoot','diagnose,active','B2'],
      ['troubleshooting','adj','Currently troubleshooting','diagnose,ongoing','B2'],
      ['troubleshooted','adj','Having been troubleshootd','diagnose,completed','B2'],
      ['retroubleshoot','v','To troubleshoot again','diagnose again,repeat','B2'],
      ['untroubleshoot','v','To reverse troubleshooting','reverse,undo','C1'],
      ['overtroubleshoot','v','To troubleshoot excessively','excess,too much','C1'],
      ['undertroubleshoot','v','To troubleshoot insufficiently','insufficient,inadequate','C1'],
    ],
  },
  collocations: {}
};
