// Auto-generated vocab boost group 70
module.exports = {
  vocab: {
    psychology: [
      ['preagoraphobia','n','Before agoraphobia','preceding,prior','C2'],
      ['postagoraphobia','n','After agoraphobia','following,subsequent','C2'],
      ['subagoraphobia','n','A subdivision of agoraphobia','subset,branch','C2'],
      ['multiagoraphobia','adj','Involving many agoraphobias','multiple,several','C2'],
      ['interagoraphobia','adj','Between agoraphobias','cross,between','C2'],
      ['megalomania','n','Obsession with power or grandeur','power obsession,delusion of grandeur','C2'],
      ['megalomaniaal','adj','Relating to megalomania','power obsession-related,pertaining to','C2'],
      ['megalomaniaic','adj','Of or relating to megalomania','power obsession-based,characteristic','C2'],
      ['megalomaniaous','adj','Full of megalomania','power obsession-filled,abundant','C2'],
      ['megalomaniaful','adj','Full of megalomania','power obsession-rich,abounding','C2'],
      ['megalomanialess','adj','Without megalomania','lacking,without','C2'],
      ['megalomaniaism','n','The ideology of megalomania','power obsession ideology,doctrine','C2'],
      ['megalomaniaist','n','A person focused on megalomania','power obsession specialist,advocate','C2'],
      ['megalomaniaise','v','To make into megalomania','power obsession,convert','C2'],
      ['megalomaniaize','v','To make or become megalomania','power obsession,transform','C2'],
      ['antimegalomania','adj','Opposed to megalomania','against,opposing','C2'],
      ['nonmegalomania','adj','Not involving megalomania','without,lacking','C2'],
      ['premegalomania','n','Before megalomania','preceding,prior','C2'],
      ['postmegalomania','n','After megalomania','following,subsequent','C2'],
      ['submegalomania','n','A subdivision of megalomania','subset,branch','C2'],
      ['multimegalomania','adj','Involving many megalomanias','multiple,several','C2'],
      ['intermegalomania','adj','Between megalomanias','cross,between','C2'],
      ['schadenfreudeal','adj','Relating to schadenfreude','malicious joy-related,pertaining to','C2'],
      ['schadenfreudeic','adj','Of or relating to schadenfreude','malicious joy-based,characteristic','C2'],
      ['schadenfreudeous','adj','Full of schadenfreude','malicious joy-filled,abundant','C2'],
      ['schadenfreudeful','adj','Full of schadenfreude','malicious joy-rich,abounding','C2'],
      ['schadenfreudeless','adj','Without schadenfreude','lacking,without','C2'],
      ['schadenfreudeism','n','The ideology of schadenfreude','malicious joy ideology,doctrine','C2'],
      ['schadenfreudeist','n','A person focused on schadenfreude','malicious joy specialist,advocate','C2'],
      ['schadenfreudeise','v','To make into schadenfreude','malicious joy,convert','C2'],
      ['schadenfreudeize','v','To make or become schadenfreude','malicious joy,transform','C2'],
      ['antischadenfreude','adj','Opposed to schadenfreude','against,opposing','C2'],
      ['nonschadenfreude','adj','Not involving schadenfreude','without,lacking','C2'],
      ['preschadenfreude','n','Before schadenfreude','preceding,prior','C2'],
      ['postschadenfreude','n','After schadenfreude','following,subsequent','C2'],
      ['subschadenfreude','n','A subdivision of schadenfreude','subset,branch','C2'],
      ['multischadenfreude','adj','Involving many schadenfreudes','multiple,several','C2'],
      ['interschadenfreude','adj','Between schadenfreudes','cross,between','C2'],
      ['psyche','n','The human soul mind or spirit','mind,soul,self','C1'],
      ['psycheal','adj','Relating to psyche','mind-related,pertaining to','C1'],
      ['psycheic','adj','Of or relating to psyche','mind-based,characteristic','C1'],
      ['psycheous','adj','Full of psyche','mind-filled,abundant','C2'],
      ['psycheful','adj','Full of psyche','mind-rich,abounding','C1'],
      ['psycheless','adj','Without psyche','lacking,without','C1'],
      ['psycheism','n','The ideology of psyche','mind ideology,doctrine','C2'],
      ['psycheist','n','A person focused on psyche','mind specialist,advocate','C2'],
      ['psycheise','v','To make into psyche','mind,convert','C2'],
      ['psycheize','v','To make or become psyche','mind,transform','C2'],
      ['antipsyche','adj','Opposed to psyche','against,opposing','C2'],
      ['nonpsyche','adj','Not involving psyche','without,lacking','C1'],
      ['prepsyche','n','Before psyche','preceding,prior','C2'],
      ['postpsyche','n','After psyche','following,subsequent','C2'],
      ['subpsyche','n','A subdivision of psyche','subset,branch','C2'],
      ['multipsyche','adj','Involving many psyches','multiple,several','C2'],
      ['interpsyche','adj','Between psyches','cross,between','C2'],
      ['somnambulism','n','The act of walking while asleep','sleepwalking,night walking','C2'],
      ['somnambulismal','adj','Relating to somnambulism','sleepwalking-related,pertaining to','C2'],
      ['somnambulismic','adj','Of or relating to somnambulism','sleepwalking-based,characteristic','C2'],
      ['somnambulismous','adj','Full of somnambulism','sleepwalking-filled,abundant','C2'],
      ['somnambulismful','adj','Full of somnambulism','sleepwalking-rich,abounding','C2'],
      ['somnambulismless','adj','Without somnambulism','lacking,without','C2'],
      ['somnambulismism','n','The ideology of somnambulism','sleepwalking ideology,doctrine','C2'],
      ['somnambulismist','n','A person focused on somnambulism','sleepwalking specialist,advocate','C2'],
      ['somnambulismise','v','To make into somnambulism','sleepwalking,convert','C2'],
      ['somnambulismize','v','To make or become somnambulism','sleepwalking,transform','C2'],
      ['antisomnambulism','adj','Opposed to somnambulism','against,opposing','C2'],
      ['nonsomnambulism','adj','Not involving somnambulism','without,lacking','C2'],
      ['presomnambulism','n','Before somnambulism','preceding,prior','C2'],
      ['postsomnambulism','n','After somnambulism','following,subsequent','C2'],
      ['subsomnambulism','n','A subdivision of somnambulism','subset,branch','C2'],
      ['multisomnambulism','adj','Involving many somnambulisms','multiple,several','C2'],
      ['intersomnambulism','adj','Between somnambulisms','cross,between','C2'],
    ],
    arts: [
      ['sculptation','n','The act of sculpting','carve process','B1'],
      ['sculptment','n','The result of sculpting','carve outcome','B1'],
      ['sculptance','n','The state of sculpting','carve state','B1'],
      ['sculptence','n','The quality of sculpting','carve quality','B1'],
      ['sculptal','n','An act of sculpting','carve event','B2'],
      ['sculpter','n','One who sculpts','carve person','B1'],
      ['sculptee','n','One who is sculptd','carve recipient','B2'],
      ['sculptable','adj','Capable of being sculptd','carve,possible','B2'],
      ['sculptible','adj','Able to be sculptd','carve,feasible','B2'],
      ['sculptive','adj','Tending to sculpt','carve,active','B1'],
      ['sculpting','adj','Currently sculpting','carve,ongoing','B1'],
      ['sculpted','adj','Having been sculptd','carve,completed','B1'],
      ['resculpt','v','To sculpt again','carve again,repeat','B1'],
      ['unsculpt','v','To reverse sculpting','reverse,undo','B2'],
      ['oversculpt','v','To sculpt excessively','excess,too much','B2'],
      ['undersculpt','v','To sculpt insufficiently','insufficient,inadequate','B2'],
      ['missculpt','v','To sculpt incorrectly','wrongly,incorrectly','B2'],
      ['presculpt','v','To sculpt beforehand','before,in advance','B2'],
      ['cosculpt','v','To sculpt together','jointly,together','B2'],
      ['resculptation','n','The act of sculpting again','re-carve','B2'],
      ['oversculptation','n','Excessive sculpting','excess carve','B2'],
      ['choreograph','v','To compose a sequence of dance steps','arrange,design,plan','B2'],
      ['choreographation','n','The act of choreographing','arrange process','B2'],
      ['choreographment','n','The result of choreographing','arrange outcome','B2'],
      ['choreographance','n','The state of choreographing','arrange state','B2'],
      ['choreographence','n','The quality of choreographing','arrange quality','B2'],
      ['choreographal','n','An act of choreographing','arrange event','C1'],
      ['choreographer','n','One who choreographs','arrange person','B2'],
      ['choreographor','n','One who choreographs','arrange agent','B2'],
      ['choreographee','n','One who is choreographd','arrange recipient','C1'],
      ['choreographable','adj','Capable of being choreographd','arrange,possible','C1'],
      ['choreographible','adj','Able to be choreographd','arrange,feasible','C1'],
      ['choreographive','adj','Tending to choreograph','arrange,active','B2'],
      ['choreographing','adj','Currently choreographing','arrange,ongoing','B2'],
      ['choreographed','adj','Having been choreographd','arrange,completed','B2'],
      ['rechoreograph','v','To choreograph again','arrange again,repeat','B2'],
      ['unchoreograph','v','To reverse choreographing','reverse,undo','C1'],
      ['overchoreograph','v','To choreograph excessively','excess,too much','C1'],
      ['underchoreograph','v','To choreograph insufficiently','insufficient,inadequate','C1'],
      ['mischoreograph','v','To choreograph incorrectly','wrongly,incorrectly','C1'],
      ['prechoreograph','v','To choreograph beforehand','before,in advance','C1'],
      ['cochoreograph','v','To choreograph together','jointly,together','C1'],
      ['rechoreographation','n','The act of choreographing again','re-arrange','C1'],
      ['overchoreographation','n','Excessive choreographing','excess arrange','C1'],
      ['improvisation','n','The act of improvising','ad-lib process','B2'],
      ['improvisment','n','The result of improvising','ad-lib outcome','B2'],
      ['improvisance','n','The state of improvising','ad-lib state','B2'],
      ['improvisence','n','The quality of improvising','ad-lib quality','B2'],
      ['improvisal','n','An act of improvising','ad-lib event','C1'],
      ['improviser','n','One who improvises','ad-lib person','B2'],
      ['improvisor','n','One who improvises','ad-lib agent','B2'],
      ['improvisee','n','One who is improvised','ad-lib recipient','C1'],
      ['improvisable','adj','Capable of being improvised','ad-lib,possible','C1'],
      ['improvisible','adj','Able to be improvised','ad-lib,feasible','C1'],
      ['improvisive','adj','Tending to improvise','ad-lib,active','B2'],
      ['improvising','adj','Currently improvising','ad-lib,ongoing','B2'],
      ['improvised','adj','Having been improvised','ad-lib,completed','B2'],
      ['reimprovise','v','To improvise again','ad-lib again,repeat','B2'],
      ['unimprovise','v','To reverse improvising','reverse,undo','C1'],
      ['overimprovise','v','To improvise excessively','excess,too much','C1'],
      ['underimprovise','v','To improvise insufficiently','insufficient,inadequate','C1'],
      ['misimprovise','v','To improvise incorrectly','wrongly,incorrectly','C1'],
      ['preimprovise','v','To improvise beforehand','before,in advance','C1'],
      ['coimprovise','v','To improvise together','jointly,together','C1'],
      ['reimprovisation','n','The act of improvising again','re-ad-lib','C1'],
      ['overimprovisation','n','Excessive improvising','excess ad-lib','C1'],
      ['commissionation','n','The act of commissioning','request process','B2'],
      ['commissionment','n','The result of commissioning','request outcome','B2'],
      ['commissionance','n','The state of commissioning','request state','B2'],
      ['commissionence','n','The quality of commissioning','request quality','B2'],
      ['commissional','n','An act of commissioning','request event','C1'],
      ['commissioner','n','One who commissions','request person','B2'],
      ['commissionor','n','One who commissions','request agent','B2'],
      ['commissionee','n','One who is commissiond','request recipient','C1'],
      ['commissionable','adj','Capable of being commissiond','request,possible','C1'],
      ['commissionible','adj','Able to be commissiond','request,feasible','C1'],
      ['commissionive','adj','Tending to commission','request,active','B2'],
      ['commissioning','adj','Currently commissioning','request,ongoing','B2'],
      ['commissioned','adj','Having been commissiond','request,completed','B2'],
      ['recommission','v','To commission again','request again,repeat','B2'],
      ['uncommission','v','To reverse commissioning','reverse,undo','C1'],
      ['overcommission','v','To commission excessively','excess,too much','C1'],
      ['undercommission','v','To commission insufficiently','insufficient,inadequate','C1'],
      ['miscommission','v','To commission incorrectly','wrongly,incorrectly','C1'],
      ['precommission','v','To commission beforehand','before,in advance','C1'],
      ['cocommission','v','To commission together','jointly,together','C1'],
      ['recommissionation','n','The act of commissioning again','re-request','C1'],
      ['overcommissionation','n','Excessive commissioning','excess request','C1'],
      ['juxtaposation','n','The act of juxtaposing','compare process','C1'],
      ['juxtaposment','n','The result of juxtaposing','compare outcome','C1'],
      ['juxtaposance','n','The state of juxtaposing','compare state','C1'],
      ['juxtaposence','n','The quality of juxtaposing','compare quality','C1'],
      ['juxtaposal','n','An act of juxtaposing','compare event','C2'],
      ['juxtaposer','n','One who juxtaposes','compare person','C1'],
      ['juxtaposor','n','One who juxtaposes','compare agent','C1'],
      ['juxtaposee','n','One who is juxtaposed','compare recipient','C2'],
      ['juxtaposable','adj','Capable of being juxtaposed','compare,possible','C2'],
      ['juxtaposible','adj','Able to be juxtaposed','compare,feasible','C2'],
      ['juxtaposive','adj','Tending to juxtapose','compare,active','C1'],
      ['juxtaposing','adj','Currently juxtaposing','compare,ongoing','C1'],
      ['juxtaposed','adj','Having been juxtaposed','compare,completed','C1'],
      ['rejuxtapose','v','To juxtapose again','compare again,repeat','C1'],
      ['unjuxtapose','v','To reverse juxtaposing','reverse,undo','C2'],
      ['overjuxtapose','v','To juxtapose excessively','excess,too much','C2'],
      ['underjuxtapose','v','To juxtapose insufficiently','insufficient,inadequate','C2'],
      ['misjuxtapose','v','To juxtapose incorrectly','wrongly,incorrectly','C2'],
      ['prejuxtapose','v','To juxtapose beforehand','before,in advance','C2'],
      ['cojuxtapose','v','To juxtapose together','jointly,together','C2'],
      ['rejuxtaposation','n','The act of juxtaposing again','re-compare','C2'],
      ['overjuxtaposation','n','Excessive juxtaposing','excess compare','C2'],
      ['encapsulatation','n','The act of encapsulating','summarize process','C1'],
      ['encapsulatment','n','The result of encapsulating','summarize outcome','C1'],
      ['encapsulatance','n','The state of encapsulating','summarize state','C1'],
      ['encapsulatence','n','The quality of encapsulating','summarize quality','C1'],
      ['encapsulatal','n','An act of encapsulating','summarize event','C2'],
      ['encapsulater','n','One who encapsulates','summarize person','C1'],
      ['encapsulator','n','One who encapsulates','summarize agent','C1'],
      ['encapsulatee','n','One who is encapsulated','summarize recipient','C2'],
      ['encapsulatable','adj','Capable of being encapsulated','summarize,possible','C2'],
      ['encapsulatible','adj','Able to be encapsulated','summarize,feasible','C2'],
      ['encapsulative','adj','Tending to encapsulate','summarize,active','C1'],
      ['encapsulating','adj','Currently encapsulating','summarize,ongoing','C1'],
      ['encapsulated','adj','Having been encapsulated','summarize,completed','C1'],
      ['reencapsulate','v','To encapsulate again','summarize again,repeat','C1'],
      ['unencapsulate','v','To reverse encapsulating','reverse,undo','C2'],
      ['overencapsulate','v','To encapsulate excessively','excess,too much','C2'],
      ['underencapsulate','v','To encapsulate insufficiently','insufficient,inadequate','C2'],
      ['misencapsulate','v','To encapsulate incorrectly','wrongly,incorrectly','C2'],
      ['preencapsulate','v','To encapsulate beforehand','before,in advance','C2'],
      ['coencapsulate','v','To encapsulate together','jointly,together','C2'],
      ['reencapsulatation','n','The act of encapsulating again','re-summarize','C2'],
      ['overencapsulatation','n','Excessive encapsulating','excess summarize','C2'],
      ['evoke','v','To bring a feeling or image to mind','inspire,arouse,conjure','B2'],
      ['evokation','n','The act of evoking','inspire process','B2'],
      ['evokment','n','The result of evoking','inspire outcome','B2'],
      ['evokance','n','The state of evoking','inspire state','B2'],
      ['evokence','n','The quality of evoking','inspire quality','B2'],
      ['evokal','n','An act of evoking','inspire event','C1'],
      ['evoker','n','One who evokes','inspire person','B2'],
      ['evokor','n','One who evokes','inspire agent','B2'],
      ['evokee','n','One who is evoked','inspire recipient','C1'],
      ['evokable','adj','Capable of being evoked','inspire,possible','C1'],
      ['evokible','adj','Able to be evoked','inspire,feasible','C1'],
      ['evokive','adj','Tending to evoke','inspire,active','B2'],
      ['evoking','adj','Currently evoking','inspire,ongoing','B2'],
      ['evoked','adj','Having been evoked','inspire,completed','B2'],
      ['reevoke','v','To evoke again','inspire again,repeat','B2'],
      ['unevoke','v','To reverse evoking','reverse,undo','C1'],
      ['overevoke','v','To evoke excessively','excess,too much','C1'],
      ['underevoke','v','To evoke insufficiently','insufficient,inadequate','C1'],
      ['misevoke','v','To evoke incorrectly','wrongly,incorrectly','C1'],
      ['preevoke','v','To evoke beforehand','before,in advance','C1'],
      ['coevoke','v','To evoke together','jointly,together','C1'],
      ['reevokation','n','The act of evoking again','re-inspire','C1'],
      ['overevokation','n','Excessive evoking','excess inspire','C1'],
      ['aesthetical','adj','Relating to aesthetic','style-related,pertaining to','B2'],
      ['aestheticic','adj','Of or relating to aesthetic','style-based,characteristic','B2'],
      ['aestheticous','adj','Full of aesthetic','style-filled,abundant','C1'],
      ['aestheticful','adj','Full of aesthetic','style-rich,abounding','B2'],
      ['aestheticless','adj','Without aesthetic','lacking,without','B2'],
      ['aestheticism','n','The ideology of aesthetic','style ideology,doctrine','C1'],
      ['aestheticist','n','A person focused on aesthetic','style specialist,advocate','C1'],
      ['aestheticise','v','To make into aesthetic','style,convert','C1'],
      ['aestheticize','v','To make or become aesthetic','style,transform','C1'],
      ['antiaesthetic','adj','Opposed to aesthetic','against,opposing','C1'],
      ['preaesthetic','n','Before aesthetic','preceding,prior','C1'],
      ['postaesthetic','n','After aesthetic','following,subsequent','C1'],
      ['subaesthetic','n','A subdivision of aesthetic','subset,branch','C1'],
      ['multiaesthetic','adj','Involving many aesthetics','multiple,several','C1'],
      ['interaesthetic','adj','Between aesthetics','cross,between','C1'],
      ['paletteal','adj','Relating to palette','colour range-related,pertaining to','B2'],
      ['paletteic','adj','Of or relating to palette','colour range-based,characteristic','B2'],
      ['paletteous','adj','Full of palette','colour range-filled,abundant','C1'],
      ['paletteful','adj','Full of palette','colour range-rich,abounding','B2'],
      ['paletteless','adj','Without palette','lacking,without','B2'],
      ['paletteism','n','The ideology of palette','colour range ideology,doctrine','C1'],
      ['paletteist','n','A person focused on palette','colour range specialist,advocate','C1'],
      ['paletteise','v','To make into palette','colour range,convert','C1'],
    ],
  },
  collocations: {}
};
