// Auto-generated vocab boost group 41
module.exports = {
  vocab: {
    health: [
      ['anaesthetizive','adj','Tending to anaesthetize','numb,active','C1'],
      ['anaesthetizing','adj','Currently anaesthetizing','numb,ongoing','C1'],
      ['anaesthetized','adj','Having been anaesthetized','numb,completed','C1'],
      ['reanaesthetize','v','To anaesthetize again','numb again,repeat','C1'],
      ['unanaesthetize','v','To reverse anaesthetizing','reverse,undo','C2'],
      ['overanaesthetize','v','To anaesthetize excessively','excess,too much','C2'],
      ['underanaesthetize','v','To anaesthetize insufficiently','insufficient,inadequate','C2'],
      ['misanaesthetize','v','To anaesthetize incorrectly','wrongly,incorrectly','C2'],
      ['preanaesthetize','v','To anaesthetize beforehand','before,in advance','C2'],
      ['coanaesthetize','v','To anaesthetize together','jointly,together','C2'],
      ['reanaesthetization','n','The act of anaesthetizing again','re-numb','C2'],
      ['overanaesthetization','n','Excessive anaesthetizing','excess numb','C2'],
      ['decontaminate','v','To remove dangerous substances','cleanse,purify,sanitize','C1'],
      ['decontaminatation','n','The act of decontaminating','cleanse process','C1'],
      ['decontaminatment','n','The result of decontaminating','cleanse outcome','C1'],
      ['decontaminatance','n','The state of decontaminating','cleanse state','C1'],
      ['decontaminatence','n','The quality of decontaminating','cleanse quality','C1'],
      ['decontaminatal','n','An act of decontaminating','cleanse event','C2'],
      ['decontaminater','n','One who decontaminates','cleanse person','C1'],
      ['decontaminator','n','One who decontaminates','cleanse agent','C1'],
      ['decontaminatee','n','One who is decontaminated','cleanse recipient','C2'],
      ['decontaminatable','adj','Capable of being decontaminated','cleanse,possible','C2'],
      ['decontaminatible','adj','Able to be decontaminated','cleanse,feasible','C2'],
      ['decontaminative','adj','Tending to decontaminate','cleanse,active','C1'],
      ['decontaminating','adj','Currently decontaminating','cleanse,ongoing','C1'],
      ['decontaminated','adj','Having been decontaminated','cleanse,completed','C1'],
      ['redecontaminate','v','To decontaminate again','cleanse again,repeat','C1'],
      ['undecontaminate','v','To reverse decontaminating','reverse,undo','C2'],
      ['overdecontaminate','v','To decontaminate excessively','excess,too much','C2'],
      ['underdecontaminate','v','To decontaminate insufficiently','insufficient,inadequate','C2'],
      ['misdecontaminate','v','To decontaminate incorrectly','wrongly,incorrectly','C2'],
      ['predecontaminate','v','To decontaminate beforehand','before,in advance','C2'],
      ['codecontaminate','v','To decontaminate together','jointly,together','C2'],
      ['redecontaminatation','n','The act of decontaminating again','re-cleanse','C2'],
      ['overdecontaminatation','n','Excessive decontaminating','excess cleanse','C2'],
      ['quarantination','n','The act of quarantining','isolate process','B2'],
      ['quarantinment','n','The result of quarantining','isolate outcome','B2'],
      ['quarantinance','n','The state of quarantining','isolate state','B2'],
      ['quarantinence','n','The quality of quarantining','isolate quality','B2'],
      ['quarantinal','n','An act of quarantining','isolate event','C1'],
      ['quarantiner','n','One who quarantines','isolate person','B2'],
      ['quarantinor','n','One who quarantines','isolate agent','B2'],
      ['quarantinee','n','One who is quarantined','isolate recipient','C1'],
      ['quarantinable','adj','Capable of being quarantined','isolate,possible','C1'],
      ['quarantinible','adj','Able to be quarantined','isolate,feasible','C1'],
      ['quarantinive','adj','Tending to quarantine','isolate,active','B2'],
      ['quarantining','adj','Currently quarantining','isolate,ongoing','B2'],
      ['quarantined','adj','Having been quarantined','isolate,completed','B2'],
      ['requarantine','v','To quarantine again','isolate again,repeat','B2'],
      ['unquarantine','v','To reverse quarantining','reverse,undo','C1'],
      ['overquarantine','v','To quarantine excessively','excess,too much','C1'],
      ['underquarantine','v','To quarantine insufficiently','insufficient,inadequate','C1'],
      ['misquarantine','v','To quarantine incorrectly','wrongly,incorrectly','C1'],
      ['prequarantine','v','To quarantine beforehand','before,in advance','C1'],
      ['coquarantine','v','To quarantine together','jointly,together','C1'],
      ['requarantination','n','The act of quarantining again','re-isolate','C1'],
      ['overquarantination','n','Excessive quarantining','excess isolate','C1'],
      ['therapeuticly','adv','In a therapeutic manner','healing way','B2'],
      ['therapeuticness','n','The quality of being therapeutic','healing quality','B2'],
      ['therapeuticity','n','The state of being therapeutic','healing condition','C1'],
      ['untherapeutic','adj','Not therapeutic','not healing','B2'],
      ['intherapeutic','adj','Not therapeutic','not healing','C1'],
      ['nontherapeutic','adj','Not therapeutic','not healing','B2'],
      ['semitherapeutic','adj','Partially therapeutic','partly healing','C1'],
      ['overtherapeutic','adj','Excessively therapeutic','too healing','C1'],
      ['ultratherapeutic','adj','Extremely therapeutic','very healing','C1'],
      ['palliativeity','n','The state of being palliative','soothing condition','C2'],
      ['inpalliative','adj','Not palliative','not soothing','C2'],
      ['nonpalliative','adj','Not palliative','not soothing','C1'],
      ['semipalliative','adj','Partially palliative','partly soothing','C2'],
      ['overpalliative','adj','Excessively palliative','too soothing','C2'],
      ['ultrapalliative','adj','Extremely palliative','very soothing','C2'],
      ['pathologically','adv','In a pathological manner','diseased way','C1'],
      ['pathologicalness','n','The quality of being pathological','diseased quality','C1'],
      ['pathologicality','n','The state of being pathological','diseased condition','C2'],
      ['unpathological','adj','Not pathological','not diseased','C1'],
      ['inpathological','adj','Not pathological','not diseased','C2'],
      ['nonpathological','adj','Not pathological','not diseased','C1'],
      ['semipathological','adj','Partially pathological','partly diseased','C2'],
      ['overpathological','adj','Excessively pathological','too diseased','C2'],
      ['ultrapathological','adj','Extremely pathological','very diseased','C2'],
      ['congenitally','adv','In a congenital manner','innate way','C1'],
      ['congenitalness','n','The quality of being congenital','innate quality','C1'],
      ['congenitality','n','The state of being congenital','innate condition','C2'],
      ['uncongenital','adj','Not congenital','not innate','C1'],
      ['incongenital','adj','Not congenital','not innate','C2'],
      ['noncongenital','adj','Not congenital','not innate','C1'],
      ['semicongenital','adj','Partially congenital','partly innate','C2'],
      ['overcongenital','adj','Excessively congenital','too innate','C2'],
      ['ultracongenital','adj','Extremely congenital','very innate','C2'],
      ['chronicity','n','The state of being chronic','ongoing condition','C1'],
      ['inchronic','adj','Not chronic','not ongoing','C1'],
      ['nonchronic','adj','Not chronic','not ongoing','B2'],
      ['semichronic','adj','Partially chronic','partly ongoing','C1'],
      ['overchronic','adj','Excessively chronic','too ongoing','C1'],
      ['ultrachronic','adj','Extremely chronic','very ongoing','C1'],
      ['acuteity','n','The state of being acute','severe condition','C1'],
      ['inacute','adj','Not acute','not severe','C1'],
      ['nonacute','adj','Not acute','not severe','B2'],
      ['semiacute','adj','Partially acute','partly severe','C1'],
      ['overacute','adj','Excessively acute','too severe','C1'],
      ['ultraacute','adj','Extremely acute','very severe','C1'],
      ['benignity','n','The state of being benign','harmless condition','C1'],
      ['inbenign','adj','Not benign','not harmless','C1'],
      ['nonbenign','adj','Not benign','not harmless','B2'],
      ['semibenign','adj','Partially benign','partly harmless','C1'],
      ['overbenign','adj','Excessively benign','too harmless','C1'],
      ['ultrabenign','adj','Extremely benign','very harmless','C1'],
      ['malignantity','n','The state of being malignant','harmful condition','C2'],
      ['inmalignant','adj','Not malignant','not harmful','C2'],
      ['nonmalignant','adj','Not malignant','not harmful','C1'],
      ['semimalignant','adj','Partially malignant','partly harmful','C2'],
      ['overmalignant','adj','Excessively malignant','too harmful','C2'],
      ['ultramalignant','adj','Extremely malignant','very harmful','C2'],
      ['sedentarily','adv','In a sedentary manner','inactive way','B2'],
      ['sedentarness','n','The quality of being sedentary','inactive quality','B2'],
      ['sedentarity','n','The state of being sedentary','inactive condition','C1'],
      ['unsedentary','adj','Not sedentary','not inactive','B2'],
      ['insedentary','adj','Not sedentary','not inactive','C1'],
      ['nonsedentary','adj','Not sedentary','not inactive','B2'],
      ['semisedentary','adj','Partially sedentary','partly inactive','C1'],
      ['oversedentary','adj','Excessively sedentary','too inactive','C1'],
      ['ultrasedentary','adj','Extremely sedentary','very inactive','C1'],
      ['epidemiological','adj','Relating to the study of disease spread','disease-related,public health','C1'],
      ['epidemiologically','adv','In a epidemiological manner','disease-related way','C1'],
      ['epidemiologicalness','n','The quality of being epidemiological','disease-related quality','C1'],
      ['epidemiologicality','n','The state of being epidemiological','disease-related condition','C2'],
      ['unepidemiological','adj','Not epidemiological','not disease-related','C1'],
      ['inepidemiological','adj','Not epidemiological','not disease-related','C2'],
      ['nonepidemiological','adj','Not epidemiological','not disease-related','C1'],
      ['semiepidemiological','adj','Partially epidemiological','partly disease-related','C2'],
      ['overepidemiological','adj','Excessively epidemiological','too disease-related','C2'],
      ['ultraepidemiological','adj','Extremely epidemiological','very disease-related','C2'],
      ['prognosisic','adj','Of or relating to prognosis','forecast-based,characteristic','C1'],
      ['prognosisous','adj','Full of prognosis','forecast-filled,abundant','C2'],
      ['prognosisful','adj','Full of prognosis','forecast-rich,abounding','C1'],
      ['prognosisless','adj','Without prognosis','lacking,without','C1'],
      ['prognosisism','n','The ideology of prognosis','forecast ideology,doctrine','C2'],
      ['prognosisist','n','A person focused on prognosis','forecast specialist,advocate','C2'],
      ['prognosisise','v','To make into prognosis','forecast,convert','C2'],
      ['prognosisize','v','To make or become prognosis','forecast,transform','C2'],
      ['antiprognosis','adj','Opposed to prognosis','against,opposing','C2'],
      ['nonprognosis','adj','Not involving prognosis','without,lacking','C1'],
      ['preprognosis','n','Before prognosis','preceding,prior','C2'],
      ['postprognosis','n','After prognosis','following,subsequent','C2'],
      ['subprognosis','n','A subdivision of prognosis','subset,branch','C2'],
      ['multiprognosis','adj','Involving many prognosiss','multiple,several','C2'],
      ['interprognosis','adj','Between prognosiss','cross,between','C2'],
      ['syndrome','n','A group of symptoms occurring together','condition,disorder,complex','B2'],
      ['syndromeal','adj','Relating to syndrome','condition-related,pertaining to','B2'],
      ['syndromeic','adj','Of or relating to syndrome','condition-based,characteristic','B2'],
      ['syndromeous','adj','Full of syndrome','condition-filled,abundant','C1'],
      ['syndromeful','adj','Full of syndrome','condition-rich,abounding','B2'],
      ['syndromeless','adj','Without syndrome','lacking,without','B2'],
      ['syndromeism','n','The ideology of syndrome','condition ideology,doctrine','C1'],
      ['syndromeist','n','A person focused on syndrome','condition specialist,advocate','C1'],
      ['syndromeise','v','To make into syndrome','condition,convert','C1'],
      ['syndromeize','v','To make or become syndrome','condition,transform','C1'],
      ['antisyndrome','adj','Opposed to syndrome','against,opposing','C1'],
      ['nonsyndrome','adj','Not involving syndrome','without,lacking','B2'],
      ['presyndrome','n','Before syndrome','preceding,prior','C1'],
      ['postsyndrome','n','After syndrome','following,subsequent','C1'],
      ['subsyndrome','n','A subdivision of syndrome','subset,branch','C1'],
      ['multisyndrome','adj','Involving many syndromes','multiple,several','C1'],
      ['intersyndrome','adj','Between syndromes','cross,between','C1'],
      ['ailmental','adj','Relating to ailment','illness-related,pertaining to','B2'],
      ['ailmentic','adj','Of or relating to ailment','illness-based,characteristic','B2'],
      ['ailmentous','adj','Full of ailment','illness-filled,abundant','C1'],
      ['ailmentful','adj','Full of ailment','illness-rich,abounding','B2'],
      ['ailmentless','adj','Without ailment','lacking,without','B2'],
      ['ailmentism','n','The ideology of ailment','illness ideology,doctrine','C1'],
      ['ailmentist','n','A person focused on ailment','illness specialist,advocate','C1'],
      ['ailmentise','v','To make into ailment','illness,convert','C1'],
      ['ailmentize','v','To make or become ailment','illness,transform','C1'],
      ['antiailment','adj','Opposed to ailment','against,opposing','C1'],
      ['nonailment','adj','Not involving ailment','without,lacking','B2'],
      ['preailment','n','Before ailment','preceding,prior','C1'],
      ['postailment','n','After ailment','following,subsequent','C1'],
      ['subailment','n','A subdivision of ailment','subset,branch','C1'],
      ['multiailment','adj','Involving many ailments','multiple,several','C1'],
      ['interailment','adj','Between ailments','cross,between','C1'],
      ['epidemicic','adj','Of or relating to epidemic','outbreak-based,characteristic','B2'],
      ['epidemicous','adj','Full of epidemic','outbreak-filled,abundant','C1'],
      ['epidemicful','adj','Full of epidemic','outbreak-rich,abounding','B2'],
      ['epidemicless','adj','Without epidemic','lacking,without','B2'],
      ['epidemicism','n','The ideology of epidemic','outbreak ideology,doctrine','C1'],
      ['epidemicist','n','A person focused on epidemic','outbreak specialist,advocate','C1'],
      ['epidemicise','v','To make into epidemic','outbreak,convert','C1'],
      ['epidemicize','v','To make or become epidemic','outbreak,transform','C1'],
      ['antiepidemic','adj','Opposed to epidemic','against,opposing','C1'],
      ['nonepidemic','adj','Not involving epidemic','without,lacking','B2'],
      ['preepidemic','n','Before epidemic','preceding,prior','C1'],
      ['postepidemic','n','After epidemic','following,subsequent','C1'],
      ['subepidemic','n','A subdivision of epidemic','subset,branch','C1'],
      ['multiepidemic','adj','Involving many epidemics','multiple,several','C1'],
      ['interepidemic','adj','Between epidemics','cross,between','C1'],
      ['pathogenal','adj','Relating to pathogen','germ-related,pertaining to','C1'],
      ['pathogenic','adj','Of or relating to pathogen','germ-based,characteristic','C1'],
      ['pathogenous','adj','Full of pathogen','germ-filled,abundant','C2'],
      ['pathogenful','adj','Full of pathogen','germ-rich,abounding','C1'],
      ['pathogenless','adj','Without pathogen','lacking,without','C1'],
      ['pathogenism','n','The ideology of pathogen','germ ideology,doctrine','C2'],
      ['pathogenist','n','A person focused on pathogen','germ specialist,advocate','C2'],
      ['pathogenise','v','To make into pathogen','germ,convert','C2'],
      ['pathogenize','v','To make or become pathogen','germ,transform','C2'],
      ['antipathogen','adj','Opposed to pathogen','against,opposing','C2'],
      ['nonpathogen','adj','Not involving pathogen','without,lacking','C1'],
      ['prepathogen','n','Before pathogen','preceding,prior','C2'],
      ['postpathogen','n','After pathogen','following,subsequent','C2'],
      ['subpathogen','n','A subdivision of pathogen','subset,branch','C2'],
      ['multipathogen','adj','Involving many pathogens','multiple,several','C2'],
      ['interpathogen','adj','Between pathogens','cross,between','C2'],
      ['antibody','n','A protein that fights infection','immune protein,defence agent','B2'],
      ['antibodyal','adj','Relating to antibody','immune protein-related,pertaining to','B2'],
      ['antibodyic','adj','Of or relating to antibody','immune protein-based,characteristic','B2'],
      ['antibodyous','adj','Full of antibody','immune protein-filled,abundant','C1'],
      ['antibodyful','adj','Full of antibody','immune protein-rich,abounding','B2'],
      ['antibodyless','adj','Without antibody','lacking,without','B2'],
      ['antibodyism','n','The ideology of antibody','immune protein ideology,doctrine','C1'],
      ['antibodyist','n','A person focused on antibody','immune protein specialist,advocate','C1'],
      ['antibodyise','v','To make into antibody','immune protein,convert','C1'],
      ['antibodyize','v','To make or become antibody','immune protein,transform','C1'],
      ['antiantibody','adj','Opposed to antibody','against,opposing','C1'],
      ['nonantibody','adj','Not involving antibody','without,lacking','B2'],
      ['preantibody','n','Before antibody','preceding,prior','C1'],
      ['postantibody','n','After antibody','following,subsequent','C1'],
      ['subantibody','n','A subdivision of antibody','subset,branch','C1'],
      ['multiantibody','adj','Involving many antibodys','multiple,several','C1'],
      ['interantibody','adj','Between antibodys','cross,between','C1'],
      ['metabolismic','adj','Of or relating to metabolism','body chemistry-based,characteristic','B2'],
      ['metabolismous','adj','Full of metabolism','body chemistry-filled,abundant','C1'],
      ['metabolismful','adj','Full of metabolism','body chemistry-rich,abounding','B2'],
      ['metabolismless','adj','Without metabolism','lacking,without','B2'],
      ['metabolismism','n','The ideology of metabolism','body chemistry ideology,doctrine','C1'],
      ['metabolismist','n','A person focused on metabolism','body chemistry specialist,advocate','C1'],
      ['metabolismise','v','To make into metabolism','body chemistry,convert','C1'],
      ['metabolismize','v','To make or become metabolism','body chemistry,transform','C1'],
      ['antimetabolism','adj','Opposed to metabolism','against,opposing','C1'],
      ['nonmetabolism','adj','Not involving metabolism','without,lacking','B2'],
      ['premetabolism','n','Before metabolism','preceding,prior','C1'],
      ['postmetabolism','n','After metabolism','following,subsequent','C1'],
      ['submetabolism','n','A subdivision of metabolism','subset,branch','C1'],
      ['multimetabolism','adj','Involving many metabolisms','multiple,several','C1'],
      ['intermetabolism','adj','Between metabolisms','cross,between','C1'],
      ['inflammation','n','Swelling and redness in body tissue','swelling,irritation,redness','B2'],
      ['inflammational','adj','Relating to inflammation','swelling-related,pertaining to','B2'],
      ['inflammationic','adj','Of or relating to inflammation','swelling-based,characteristic','B2'],
      ['inflammationous','adj','Full of inflammation','swelling-filled,abundant','C1'],
      ['inflammationful','adj','Full of inflammation','swelling-rich,abounding','B2'],
      ['inflammationless','adj','Without inflammation','lacking,without','B2'],
    ],
  },
  collocations: {}
};
