// Auto-generated vocab boost group 53
module.exports = {
  vocab: {
    culture: [
      ['unvenerate','v','To reverse venerating','reverse,undo','C2'],
      ['overvenerate','v','To venerate excessively','excess,too much','C2'],
      ['undervenerate','v','To venerate insufficiently','insufficient,inadequate','C2'],
      ['misvenerate','v','To venerate incorrectly','wrongly,incorrectly','C2'],
      ['prevenerate','v','To venerate beforehand','before,in advance','C2'],
      ['covenerate','v','To venerate together','jointly,together','C2'],
      ['reveneratation','n','The act of venerating again','re-revere','C2'],
      ['overveneratation','n','Excessive venerating','excess revere','C2'],
      ['epitomize','v','To be a perfect example of','represent,embody,exemplify','C1'],
      ['epitomization','n','The act of epitomizing','represent process','C1'],
      ['epitomizment','n','The result of epitomizing','represent outcome','C1'],
      ['epitomizance','n','The state of epitomizing','represent state','C1'],
      ['epitomizence','n','The quality of epitomizing','represent quality','C1'],
      ['epitomizal','n','An act of epitomizing','represent event','C2'],
      ['epitomizer','n','One who epitomizes','represent person','C1'],
      ['epitomizor','n','One who epitomizes','represent agent','C1'],
      ['epitomizee','n','One who is epitomized','represent recipient','C2'],
      ['epitomizable','adj','Capable of being epitomized','represent,possible','C2'],
      ['epitomizible','adj','Able to be epitomized','represent,feasible','C2'],
      ['epitomizive','adj','Tending to epitomize','represent,active','C1'],
      ['epitomizing','adj','Currently epitomizing','represent,ongoing','C1'],
      ['epitomized','adj','Having been epitomized','represent,completed','C1'],
      ['reepitomize','v','To epitomize again','represent again,repeat','C1'],
      ['unepitomize','v','To reverse epitomizing','reverse,undo','C2'],
      ['overepitomize','v','To epitomize excessively','excess,too much','C2'],
      ['underepitomize','v','To epitomize insufficiently','insufficient,inadequate','C2'],
      ['misepitomize','v','To epitomize incorrectly','wrongly,incorrectly','C2'],
      ['preepitomize','v','To epitomize beforehand','before,in advance','C2'],
      ['coepitomize','v','To epitomize together','jointly,together','C2'],
      ['reepitomization','n','The act of epitomizing again','re-represent','C2'],
      ['overepitomization','n','Excessive epitomizing','excess represent','C2'],
      ['multiculturally','adv','In a multicultural manner','diverse way','B2'],
      ['multiculturalness','n','The quality of being multicultural','diverse quality','B2'],
      ['multiculturality','n','The state of being multicultural','diverse condition','C1'],
      ['unmulticultural','adj','Not multicultural','not diverse','B2'],
      ['inmulticultural','adj','Not multicultural','not diverse','C1'],
      ['nonmulticultural','adj','Not multicultural','not diverse','B2'],
      ['semimulticultural','adj','Partially multicultural','partly diverse','C1'],
      ['overmulticultural','adj','Excessively multicultural','too diverse','C1'],
      ['ultramulticultural','adj','Extremely multicultural','very diverse','C1'],
      ['indigenousity','n','The state of being indigenous','native condition','C1'],
      ['inindigenous','adj','Not indigenous','not native','C1'],
      ['nonindigenous','adj','Not indigenous','not native','B2'],
      ['semiindigenous','adj','Partially indigenous','partly native','C1'],
      ['overindigenous','adj','Excessively indigenous','too native','C1'],
      ['ultraindigenous','adj','Extremely indigenous','very native','C1'],
      ['vernacularly','adv','In a vernacular manner','local way','C1'],
      ['vernacularness','n','The quality of being vernacular','local quality','C1'],
      ['vernacularity','n','The state of being vernacular','local condition','C2'],
      ['unvernacular','adj','Not vernacular','not local','C1'],
      ['invernacular','adj','Not vernacular','not local','C2'],
      ['nonvernacular','adj','Not vernacular','not local','C1'],
      ['semivernacular','adj','Partially vernacular','partly local','C2'],
      ['oververnacular','adj','Excessively vernacular','too local','C2'],
      ['ultravernacular','adj','Extremely vernacular','very local','C2'],
      ['archaic','adj','Very old or old-fashioned','ancient,antiquated,outmoded','C1'],
      ['archaicly','adv','In a archaic manner','ancient way','C1'],
      ['archaicness','n','The quality of being archaic','ancient quality','C1'],
      ['archaicity','n','The state of being archaic','ancient condition','C2'],
      ['unarchaic','adj','Not archaic','not ancient','C1'],
      ['inarchaic','adj','Not archaic','not ancient','C2'],
      ['nonarchaic','adj','Not archaic','not ancient','C1'],
      ['semiarchaic','adj','Partially archaic','partly ancient','C2'],
      ['overarchaic','adj','Excessively archaic','too ancient','C2'],
      ['ultraarchaic','adj','Extremely archaic','very ancient','C2'],
      ['secularly','adv','In a secular manner','non-religious way','B2'],
      ['secularness','n','The quality of being secular','non-religious quality','B2'],
      ['secularity','n','The state of being secular','non-religious condition','C1'],
      ['unsecular','adj','Not secular','not non-religious','B2'],
      ['insecular','adj','Not secular','not non-religious','C1'],
      ['nonsecular','adj','Not secular','not non-religious','B2'],
      ['semisecular','adj','Partially secular','partly non-religious','C1'],
      ['oversecular','adj','Excessively secular','too non-religious','C1'],
      ['ultrasecular','adj','Extremely secular','very non-religious','C1'],
      ['anthropological','adj','Relating to the study of human cultures','cultural,ethnographic,social','C1'],
      ['anthropologically','adv','In a anthropological manner','cultural way','C1'],
      ['anthropologicalness','n','The quality of being anthropological','cultural quality','C1'],
      ['anthropologicality','n','The state of being anthropological','cultural condition','C2'],
      ['unanthropological','adj','Not anthropological','not cultural','C1'],
      ['inanthropological','adj','Not anthropological','not cultural','C2'],
      ['nonanthropological','adj','Not anthropological','not cultural','C1'],
      ['semianthropological','adj','Partially anthropological','partly cultural','C2'],
      ['overanthropological','adj','Excessively anthropological','too cultural','C2'],
      ['ultraanthropological','adj','Extremely anthropological','very cultural','C2'],
      ['folkloreic','adj','Of or relating to folklore','legends-based,characteristic','B2'],
      ['folkloreous','adj','Full of folklore','legends-filled,abundant','C1'],
      ['folkloreful','adj','Full of folklore','legends-rich,abounding','B2'],
      ['folkloreless','adj','Without folklore','lacking,without','B2'],
      ['folkloreism','n','The ideology of folklore','legends ideology,doctrine','C1'],
      ['folkloreist','n','A person focused on folklore','legends specialist,advocate','C1'],
      ['folkloreise','v','To make into folklore','legends,convert','C1'],
      ['folkloreize','v','To make or become folklore','legends,transform','C1'],
      ['antifolklore','adj','Opposed to folklore','against,opposing','C1'],
      ['nonfolklore','adj','Not involving folklore','without,lacking','B2'],
      ['prefolklore','n','Before folklore','preceding,prior','C1'],
      ['postfolklore','n','After folklore','following,subsequent','C1'],
      ['subfolklore','n','A subdivision of folklore','subset,branch','C1'],
      ['multifolklore','adj','Involving many folklores','multiple,several','C1'],
      ['interfolklore','adj','Between folklores','cross,between','C1'],
      ['heritageic','adj','Of or relating to heritage','tradition-based,characteristic','B2'],
      ['heritageous','adj','Full of heritage','tradition-filled,abundant','C1'],
      ['heritageful','adj','Full of heritage','tradition-rich,abounding','B2'],
      ['heritageless','adj','Without heritage','lacking,without','B2'],
      ['heritageism','n','The ideology of heritage','tradition ideology,doctrine','C1'],
      ['heritageist','n','A person focused on heritage','tradition specialist,advocate','C1'],
      ['heritageise','v','To make into heritage','tradition,convert','C1'],
      ['heritageize','v','To make or become heritage','tradition,transform','C1'],
      ['antiheritage','adj','Opposed to heritage','against,opposing','C1'],
      ['nonheritage','adj','Not involving heritage','without,lacking','B2'],
      ['preheritage','n','Before heritage','preceding,prior','C1'],
      ['postheritage','n','After heritage','following,subsequent','C1'],
      ['subheritage','n','A subdivision of heritage','subset,branch','C1'],
      ['multiheritage','adj','Involving many heritages','multiple,several','C1'],
      ['interheritage','adj','Between heritages','cross,between','C1'],
      ['artefactic','adj','Of or relating to artefact','relic-based,characteristic','B2'],
      ['artefactous','adj','Full of artefact','relic-filled,abundant','C1'],
      ['artefactful','adj','Full of artefact','relic-rich,abounding','B2'],
      ['artefactless','adj','Without artefact','lacking,without','B2'],
      ['artefactism','n','The ideology of artefact','relic ideology,doctrine','C1'],
      ['artefactist','n','A person focused on artefact','relic specialist,advocate','C1'],
      ['artefactise','v','To make into artefact','relic,convert','C1'],
      ['artefactize','v','To make or become artefact','relic,transform','C1'],
      ['antiartefact','adj','Opposed to artefact','against,opposing','C1'],
      ['nonartefact','adj','Not involving artefact','without,lacking','B2'],
      ['preartefact','n','Before artefact','preceding,prior','C1'],
      ['postartefact','n','After artefact','following,subsequent','C1'],
      ['subartefact','n','A subdivision of artefact','subset,branch','C1'],
      ['multiartefact','adj','Involving many artefacts','multiple,several','C1'],
      ['interartefact','adj','Between artefacts','cross,between','C1'],
      ['tabooic','adj','Of or relating to taboo','ban-based,characteristic','B2'],
      ['tabooous','adj','Full of taboo','ban-filled,abundant','C1'],
      ['tabooful','adj','Full of taboo','ban-rich,abounding','B2'],
      ['tabooless','adj','Without taboo','lacking,without','B2'],
      ['tabooism','n','The ideology of taboo','ban ideology,doctrine','C1'],
      ['tabooist','n','A person focused on taboo','ban specialist,advocate','C1'],
      ['tabooise','v','To make into taboo','ban,convert','C1'],
      ['tabooize','v','To make or become taboo','ban,transform','C1'],
      ['antitaboo','adj','Opposed to taboo','against,opposing','C1'],
      ['nontaboo','adj','Not involving taboo','without,lacking','B2'],
      ['pretaboo','n','Before taboo','preceding,prior','C1'],
      ['posttaboo','n','After taboo','following,subsequent','C1'],
      ['subtaboo','n','A subdivision of taboo','subset,branch','C1'],
      ['multitaboo','adj','Involving many taboos','multiple,several','C1'],
      ['intertaboo','adj','Between taboos','cross,between','C1'],
      ['ritualic','adj','Of or relating to ritual','ceremony-based,characteristic','B2'],
      ['ritualous','adj','Full of ritual','ceremony-filled,abundant','C1'],
      ['ritualful','adj','Full of ritual','ceremony-rich,abounding','B2'],
      ['ritualless','adj','Without ritual','lacking,without','B2'],
      ['ritualism','n','The ideology of ritual','ceremony ideology,doctrine','C1'],
      ['ritualist','n','A person focused on ritual','ceremony specialist,advocate','C1'],
      ['ritualise','v','To make into ritual','ceremony,convert','C1'],
      ['antiritual','adj','Opposed to ritual','against,opposing','C1'],
      ['nonritual','adj','Not involving ritual','without,lacking','B2'],
      ['preritual','n','Before ritual','preceding,prior','C1'],
      ['postritual','n','After ritual','following,subsequent','C1'],
      ['subritual','n','A subdivision of ritual','subset,branch','C1'],
      ['multiritual','adj','Involving many rituals','multiple,several','C1'],
      ['interritual','adj','Between rituals','cross,between','C1'],
      ['assimilationic','adj','Of or relating to assimilation','integration-based,characteristic','B2'],
      ['assimilationous','adj','Full of assimilation','integration-filled,abundant','C1'],
      ['assimilationful','adj','Full of assimilation','integration-rich,abounding','B2'],
      ['assimilationless','adj','Without assimilation','lacking,without','B2'],
      ['assimilationism','n','The ideology of assimilation','integration ideology,doctrine','C1'],
      ['assimilationist','n','A person focused on assimilation','integration specialist,advocate','C1'],
      ['assimilationise','v','To make into assimilation','integration,convert','C1'],
      ['assimilationize','v','To make or become assimilation','integration,transform','C1'],
      ['antiassimilation','adj','Opposed to assimilation','against,opposing','C1'],
      ['nonassimilation','adj','Not involving assimilation','without,lacking','B2'],
      ['preassimilation','n','Before assimilation','preceding,prior','C1'],
      ['postassimilation','n','After assimilation','following,subsequent','C1'],
      ['subassimilation','n','A subdivision of assimilation','subset,branch','C1'],
      ['multiassimilation','adj','Involving many assimilations','multiple,several','C1'],
      ['interassimilation','adj','Between assimilations','cross,between','C1'],
      ['ethnocentrismic','adj','Of or relating to ethnocentrism','cultural bias-based,characteristic','C1'],
      ['ethnocentrismous','adj','Full of ethnocentrism','cultural bias-filled,abundant','C2'],
      ['ethnocentrismful','adj','Full of ethnocentrism','cultural bias-rich,abounding','C1'],
      ['ethnocentrismless','adj','Without ethnocentrism','lacking,without','C1'],
      ['ethnocentrismism','n','The ideology of ethnocentrism','cultural bias ideology,doctrine','C2'],
      ['ethnocentrismist','n','A person focused on ethnocentrism','cultural bias specialist,advocate','C2'],
      ['ethnocentrismise','v','To make into ethnocentrism','cultural bias,convert','C2'],
      ['ethnocentrismize','v','To make or become ethnocentrism','cultural bias,transform','C2'],
      ['antiethnocentrism','adj','Opposed to ethnocentrism','against,opposing','C2'],
      ['nonethnocentrism','adj','Not involving ethnocentrism','without,lacking','C1'],
      ['preethnocentrism','n','Before ethnocentrism','preceding,prior','C2'],
      ['postethnocentrism','n','After ethnocentrism','following,subsequent','C2'],
      ['subethnocentrism','n','A subdivision of ethnocentrism','subset,branch','C2'],
      ['multiethnocentrism','adj','Involving many ethnocentrisms','multiple,several','C2'],
      ['interethnocentrism','adj','Between ethnocentrisms','cross,between','C2'],
      ['patrimonyal','adj','Relating to patrimony','heritage-related,pertaining to','C1'],
      ['patrimonyic','adj','Of or relating to patrimony','heritage-based,characteristic','C1'],
      ['patrimonyous','adj','Full of patrimony','heritage-filled,abundant','C2'],
      ['patrimonyful','adj','Full of patrimony','heritage-rich,abounding','C1'],
      ['patrimonyless','adj','Without patrimony','lacking,without','C1'],
      ['patrimonyism','n','The ideology of patrimony','heritage ideology,doctrine','C2'],
      ['patrimonyist','n','A person focused on patrimony','heritage specialist,advocate','C2'],
      ['patrimonyise','v','To make into patrimony','heritage,convert','C2'],
      ['patrimonyize','v','To make or become patrimony','heritage,transform','C2'],
      ['antipatrimony','adj','Opposed to patrimony','against,opposing','C2'],
      ['nonpatrimony','adj','Not involving patrimony','without,lacking','C1'],
      ['prepatrimony','n','Before patrimony','preceding,prior','C2'],
      ['postpatrimony','n','After patrimony','following,subsequent','C2'],
      ['subpatrimony','n','A subdivision of patrimony','subset,branch','C2'],
      ['multipatrimony','adj','Involving many patrimonys','multiple,several','C2'],
      ['interpatrimony','adj','Between patrimonys','cross,between','C2'],
      ['iconographyic','adj','Of or relating to iconography','imagery-based,characteristic','C1'],
      ['iconographyous','adj','Full of iconography','imagery-filled,abundant','C2'],
      ['iconographyful','adj','Full of iconography','imagery-rich,abounding','C1'],
      ['iconographyless','adj','Without iconography','lacking,without','C1'],
      ['iconographyism','n','The ideology of iconography','imagery ideology,doctrine','C2'],
      ['iconographyist','n','A person focused on iconography','imagery specialist,advocate','C2'],
      ['iconographyise','v','To make into iconography','imagery,convert','C2'],
      ['iconographyize','v','To make or become iconography','imagery,transform','C2'],
      ['antiiconography','adj','Opposed to iconography','against,opposing','C2'],
      ['noniconography','adj','Not involving iconography','without,lacking','C1'],
      ['preiconography','n','Before iconography','preceding,prior','C2'],
      ['posticonography','n','After iconography','following,subsequent','C2'],
      ['subiconography','n','A subdivision of iconography','subset,branch','C2'],
      ['multiiconography','adj','Involving many iconographys','multiple,several','C2'],
      ['intericonography','adj','Between iconographys','cross,between','C2'],
      ['sacrilege','n','Violation of something sacred','blasphemy,desecration,profanity','C1'],
      ['sacrilegeal','adj','Relating to sacrilege','blasphemy-related,pertaining to','C1'],
      ['sacrilegeic','adj','Of or relating to sacrilege','blasphemy-based,characteristic','C1'],
      ['sacrilegeous','adj','Full of sacrilege','blasphemy-filled,abundant','C2'],
      ['sacrilegeful','adj','Full of sacrilege','blasphemy-rich,abounding','C1'],
      ['sacrilegeless','adj','Without sacrilege','lacking,without','C1'],
      ['sacrilegeism','n','The ideology of sacrilege','blasphemy ideology,doctrine','C2'],
      ['sacrilegeist','n','A person focused on sacrilege','blasphemy specialist,advocate','C2'],
      ['sacrilegeise','v','To make into sacrilege','blasphemy,convert','C2'],
      ['sacrilegeize','v','To make or become sacrilege','blasphemy,transform','C2'],
      ['antisacrilege','adj','Opposed to sacrilege','against,opposing','C2'],
      ['nonsacrilege','adj','Not involving sacrilege','without,lacking','C1'],
      ['presacrilege','n','Before sacrilege','preceding,prior','C2'],
      ['postsacrilege','n','After sacrilege','following,subsequent','C2'],
      ['subsacrilege','n','A subdivision of sacrilege','subset,branch','C2'],
      ['multisacrilege','adj','Involving many sacrileges','multiple,several','C2'],
      ['intersacrilege','adj','Between sacrileges','cross,between','C2'],
      ['cosmopolitanity','n','The state of being cosmopolitan','worldly condition','C1'],
      ['incosmopolitan','adj','Not cosmopolitan','not worldly','C1'],
      ['noncosmopolitan','adj','Not cosmopolitan','not worldly','B2'],
      ['semicosmopolitan','adj','Partially cosmopolitan','partly worldly','C1'],
      ['overcosmopolitan','adj','Excessively cosmopolitan','too worldly','C1'],
      ['ultracosmopolitan','adj','Extremely cosmopolitan','very worldly','C1'],
      ['parochiality','n','The state of being parochial','narrow-minded condition','C2'],
      ['inparochial','adj','Not parochial','not narrow-minded','C2'],
      ['nonparochial','adj','Not parochial','not narrow-minded','C1'],
      ['semiparochial','adj','Partially parochial','partly narrow-minded','C2'],
      ['overparochial','adj','Excessively parochial','too narrow-minded','C2'],
      ['ultraparochial','adj','Extremely parochial','very narrow-minded','C2'],
      ['bohemian','adj','Socially unconventional','artistic,free-spirited,alternative','C1'],
      ['bohemianly','adv','In a bohemian manner','artistic way','C1'],
    ],
  },
  collocations: {}
};
