// Auto-generated vocab boost group 73
module.exports = {
  vocab: {
    sports: [
      ['codope','v','To dope together','jointly,together','C1'],
      ['redopation','n','The act of doping again','re-drug','C1'],
      ['overdopation','n','Excessive doping','excess drug','C1'],
      ['sportsmanshipic','adj','Of or relating to sportsmanship','fair play-based,characteristic','B2'],
      ['sportsmanshipous','adj','Full of sportsmanship','fair play-filled,abundant','C1'],
      ['sportsmanshipful','adj','Full of sportsmanship','fair play-rich,abounding','B2'],
      ['sportsmanshipless','adj','Without sportsmanship','lacking,without','B2'],
      ['sportsmanshipism','n','The ideology of sportsmanship','fair play ideology,doctrine','C1'],
      ['sportsmanshipist','n','A person focused on sportsmanship','fair play specialist,advocate','C1'],
      ['sportsmanshipise','v','To make into sportsmanship','fair play,convert','C1'],
      ['sportsmanshipize','v','To make or become sportsmanship','fair play,transform','C1'],
      ['antisportsmanship','adj','Opposed to sportsmanship','against,opposing','C1'],
      ['nonsportsmanship','adj','Not involving sportsmanship','without,lacking','B2'],
      ['presportsmanship','n','Before sportsmanship','preceding,prior','C1'],
      ['postsportsmanship','n','After sportsmanship','following,subsequent','C1'],
      ['subsportsmanship','n','A subdivision of sportsmanship','subset,branch','C1'],
      ['multisportsmanship','adj','Involving many sportsmanships','multiple,several','C1'],
      ['intersportsmanship','adj','Between sportsmanships','cross,between','C1'],
      ['staminaic','adj','Of or relating to stamina','endurance-based,characteristic','B2'],
      ['staminaous','adj','Full of stamina','endurance-filled,abundant','C1'],
      ['staminaful','adj','Full of stamina','endurance-rich,abounding','B2'],
      ['staminaless','adj','Without stamina','lacking,without','B2'],
      ['staminaism','n','The ideology of stamina','endurance ideology,doctrine','C1'],
      ['staminaist','n','A person focused on stamina','endurance specialist,advocate','C1'],
      ['staminaise','v','To make into stamina','endurance,convert','C1'],
      ['staminaize','v','To make or become stamina','endurance,transform','C1'],
      ['antistamina','adj','Opposed to stamina','against,opposing','C1'],
      ['nonstamina','adj','Not involving stamina','without,lacking','B2'],
      ['prestamina','n','Before stamina','preceding,prior','C1'],
      ['poststamina','n','After stamina','following,subsequent','C1'],
      ['substamina','n','A subdivision of stamina','subset,branch','C1'],
      ['multistamina','adj','Involving many staminas','multiple,several','C1'],
      ['interstamina','adj','Between staminas','cross,between','C1'],
      ['tournamentic','adj','Of or relating to tournament','championship-based,characteristic','B1'],
      ['tournamentous','adj','Full of tournament','championship-filled,abundant','B2'],
      ['tournamentful','adj','Full of tournament','championship-rich,abounding','B1'],
      ['tournamentless','adj','Without tournament','lacking,without','B1'],
      ['tournamentism','n','The ideology of tournament','championship ideology,doctrine','B2'],
      ['tournamentist','n','A person focused on tournament','championship specialist,advocate','B2'],
      ['tournamentise','v','To make into tournament','championship,convert','B2'],
      ['tournamentize','v','To make or become tournament','championship,transform','B2'],
      ['antitournament','adj','Opposed to tournament','against,opposing','B2'],
      ['nontournament','adj','Not involving tournament','without,lacking','B1'],
      ['pretournament','n','Before tournament','preceding,prior','B2'],
      ['posttournament','n','After tournament','following,subsequent','B2'],
      ['subtournament','n','A subdivision of tournament','subset,branch','B2'],
      ['multitournament','adj','Involving many tournaments','multiple,several','B2'],
      ['intertournament','adj','Between tournaments','cross,between','B2'],
      ['decathlonic','adj','Of or relating to decathlon','multisport event-based,characteristic','C1'],
      ['decathlonous','adj','Full of decathlon','multisport event-filled,abundant','C2'],
      ['decathlonful','adj','Full of decathlon','multisport event-rich,abounding','C1'],
      ['decathlonless','adj','Without decathlon','lacking,without','C1'],
      ['decathlonism','n','The ideology of decathlon','multisport event ideology,doctrine','C2'],
      ['decathlonist','n','A person focused on decathlon','multisport event specialist,advocate','C2'],
      ['decathlonise','v','To make into decathlon','multisport event,convert','C2'],
      ['decathlonize','v','To make or become decathlon','multisport event,transform','C2'],
      ['antidecathlon','adj','Opposed to decathlon','against,opposing','C2'],
      ['nondecathlon','adj','Not involving decathlon','without,lacking','C1'],
      ['predecathlon','n','Before decathlon','preceding,prior','C2'],
      ['postdecathlon','n','After decathlon','following,subsequent','C2'],
      ['subdecathlon','n','A subdivision of decathlon','subset,branch','C2'],
      ['multidecathlon','adj','Involving many decathlons','multiple,several','C2'],
      ['interdecathlon','adj','Between decathlons','cross,between','C2'],
      ['podium','n','A platform for winners at events','platform,stand,stage','B2'],
      ['podiumal','adj','Relating to podium','platform-related,pertaining to','B2'],
      ['podiumic','adj','Of or relating to podium','platform-based,characteristic','B2'],
      ['podiumous','adj','Full of podium','platform-filled,abundant','C1'],
      ['podiumful','adj','Full of podium','platform-rich,abounding','B2'],
      ['podiumless','adj','Without podium','lacking,without','B2'],
      ['podiumism','n','The ideology of podium','platform ideology,doctrine','C1'],
      ['podiumist','n','A person focused on podium','platform specialist,advocate','C1'],
      ['podiumise','v','To make into podium','platform,convert','C1'],
      ['podiumize','v','To make or become podium','platform,transform','C1'],
      ['antipodium','adj','Opposed to podium','against,opposing','C1'],
      ['nonpodium','adj','Not involving podium','without,lacking','B2'],
      ['prepodium','n','Before podium','preceding,prior','C1'],
      ['postpodium','n','After podium','following,subsequent','C1'],
      ['subpodium','n','A subdivision of podium','subset,branch','C1'],
      ['multipodium','adj','Involving many podiums','multiple,several','C1'],
      ['interpodium','adj','Between podiums','cross,between','C1'],
      ['enduranceal','adj','Relating to endurance','stamina-related,pertaining to','B2'],
      ['enduranceic','adj','Of or relating to endurance','stamina-based,characteristic','B2'],
      ['enduranceous','adj','Full of endurance','stamina-filled,abundant','C1'],
      ['enduranceful','adj','Full of endurance','stamina-rich,abounding','B2'],
      ['enduranceless','adj','Without endurance','lacking,without','B2'],
      ['enduranceism','n','The ideology of endurance','stamina ideology,doctrine','C1'],
      ['enduranceist','n','A person focused on endurance','stamina specialist,advocate','C1'],
      ['enduranceise','v','To make into endurance','stamina,convert','C1'],
      ['enduranceize','v','To make or become endurance','stamina,transform','C1'],
      ['antiendurance','adj','Opposed to endurance','against,opposing','C1'],
      ['nonendurance','adj','Not involving endurance','without,lacking','B2'],
      ['preendurance','n','Before endurance','preceding,prior','C1'],
      ['postendurance','n','After endurance','following,subsequent','C1'],
      ['subendurance','n','A subdivision of endurance','subset,branch','C1'],
      ['multiendurance','adj','Involving many endurances','multiple,several','C1'],
      ['interendurance','adj','Between endurances','cross,between','C1'],
      ['agilityal','adj','Relating to agility','nimbleness-related,pertaining to','B2'],
      ['agilityic','adj','Of or relating to agility','nimbleness-based,characteristic','B2'],
      ['agilityous','adj','Full of agility','nimbleness-filled,abundant','C1'],
      ['agilityful','adj','Full of agility','nimbleness-rich,abounding','B2'],
      ['agilityless','adj','Without agility','lacking,without','B2'],
      ['agilityism','n','The ideology of agility','nimbleness ideology,doctrine','C1'],
      ['agilityist','n','A person focused on agility','nimbleness specialist,advocate','C1'],
      ['agilityise','v','To make into agility','nimbleness,convert','C1'],
      ['agilityize','v','To make or become agility','nimbleness,transform','C1'],
      ['antiagility','adj','Opposed to agility','against,opposing','C1'],
      ['nonagility','adj','Not involving agility','without,lacking','B2'],
      ['preagility','n','Before agility','preceding,prior','C1'],
      ['postagility','n','After agility','following,subsequent','C1'],
      ['subagility','n','A subdivision of agility','subset,branch','C1'],
      ['multiagility','adj','Involving many agilitys','multiple,several','C1'],
      ['interagility','adj','Between agilitys','cross,between','C1'],
      ['dexterityal','adj','Relating to dexterity','nimbleness-related,pertaining to','C1'],
      ['dexterityic','adj','Of or relating to dexterity','nimbleness-based,characteristic','C1'],
      ['dexterityous','adj','Full of dexterity','nimbleness-filled,abundant','C2'],
      ['dexterityful','adj','Full of dexterity','nimbleness-rich,abounding','C1'],
      ['dexterityless','adj','Without dexterity','lacking,without','C1'],
      ['dexterityism','n','The ideology of dexterity','nimbleness ideology,doctrine','C2'],
      ['dexterityist','n','A person focused on dexterity','nimbleness specialist,advocate','C2'],
      ['dexterityise','v','To make into dexterity','nimbleness,convert','C2'],
      ['dexterityize','v','To make or become dexterity','nimbleness,transform','C2'],
      ['antidexterity','adj','Opposed to dexterity','against,opposing','C2'],
      ['nondexterity','adj','Not involving dexterity','without,lacking','C1'],
      ['predexterity','n','Before dexterity','preceding,prior','C2'],
      ['postdexterity','n','After dexterity','following,subsequent','C2'],
      ['subdexterity','n','A subdivision of dexterity','subset,branch','C2'],
      ['multidexterity','adj','Involving many dexteritys','multiple,several','C2'],
      ['interdexterity','adj','Between dexteritys','cross,between','C2'],
      ['cardiovascularly','adv','In a cardiovascular manner','heart-related way','B2'],
      ['cardiovascularness','n','The quality of being cardiovascular','heart-related quality','B2'],
      ['cardiovascularity','n','The state of being cardiovascular','heart-related condition','C1'],
      ['uncardiovascular','adj','Not cardiovascular','not heart-related','B2'],
      ['incardiovascular','adj','Not cardiovascular','not heart-related','C1'],
      ['noncardiovascular','adj','Not cardiovascular','not heart-related','B2'],
      ['semicardiovascular','adj','Partially cardiovascular','partly heart-related','C1'],
      ['overcardiovascular','adj','Excessively cardiovascular','too heart-related','C1'],
      ['ultracardiovascular','adj','Extremely cardiovascular','very heart-related','C1'],
      ['aerobicly','adv','In a aerobic manner','oxygen-based way','B2'],
      ['aerobicness','n','The quality of being aerobic','oxygen-based quality','B2'],
      ['aerobicity','n','The state of being aerobic','oxygen-based condition','C1'],
      ['unaerobic','adj','Not aerobic','not oxygen-based','B2'],
      ['inaerobic','adj','Not aerobic','not oxygen-based','C1'],
      ['nonaerobic','adj','Not aerobic','not oxygen-based','B2'],
      ['semiaerobic','adj','Partially aerobic','partly oxygen-based','C1'],
      ['overaerobic','adj','Excessively aerobic','too oxygen-based','C1'],
      ['ultraaerobic','adj','Extremely aerobic','very oxygen-based','C1'],
      ['anaerobicity','n','The state of being anaerobic','high-intensity condition','C2'],
      ['inanaerobic','adj','Not anaerobic','not high-intensity','C2'],
      ['nonanaerobic','adj','Not anaerobic','not high-intensity','C1'],
      ['semianaerobic','adj','Partially anaerobic','partly high-intensity','C2'],
      ['overanaerobic','adj','Excessively anaerobic','too high-intensity','C2'],
      ['ultraanaerobic','adj','Extremely anaerobic','very high-intensity','C2'],
      ['rehabilitatively','adv','In a rehabilitative manner','restorative way','C1'],
      ['rehabilitativeness','n','The quality of being rehabilitative','restorative quality','C1'],
      ['rehabilitativeity','n','The state of being rehabilitative','restorative condition','C2'],
      ['unrehabilitative','adj','Not rehabilitative','not restorative','C1'],
      ['inrehabilitative','adj','Not rehabilitative','not restorative','C2'],
      ['nonrehabilitative','adj','Not rehabilitative','not restorative','C1'],
      ['semirehabilitative','adj','Partially rehabilitative','partly restorative','C2'],
      ['overrehabilitative','adj','Excessively rehabilitative','too restorative','C2'],
      ['ultrarehabilitative','adj','Extremely rehabilitative','very restorative','C2'],
      ['competitively','adv','In a competitive manner','ambitious way','B1'],
      ['competitiveness','n','The quality of being competitive','ambitious quality','B1'],
      ['competitiveity','n','The state of being competitive','ambitious condition','B2'],
      ['uncompetitive','adj','Not competitive','not ambitious','B1'],
      ['incompetitive','adj','Not competitive','not ambitious','B2'],
      ['noncompetitive','adj','Not competitive','not ambitious','B1'],
      ['semicompetitive','adj','Partially competitive','partly ambitious','B2'],
      ['overcompetitive','adj','Excessively competitive','too ambitious','B2'],
      ['ultracompetitive','adj','Extremely competitive','very ambitious','B2'],
      ['sportsmanlike','adj','Behaving fairly and generously','fair,honourable,gracious','B2'],
      ['sportsmanlikely','adv','In a sportsmanlike manner','fair way','B2'],
      ['sportsmanlikeness','n','The quality of being sportsmanlike','fair quality','B2'],
      ['sportsmanlikeity','n','The state of being sportsmanlike','fair condition','C1'],
      ['unsportsmanlike','adj','Not sportsmanlike','not fair','B2'],
      ['insportsmanlike','adj','Not sportsmanlike','not fair','C1'],
      ['nonsportsmanlike','adj','Not sportsmanlike','not fair','B2'],
      ['semisportsmanlike','adj','Partially sportsmanlike','partly fair','C1'],
      ['oversportsmanlike','adj','Excessively sportsmanlike','too fair','C1'],
      ['ultrasportsmanlike','adj','Extremely sportsmanlike','very fair','C1'],
      ['calisthenicsic','adj','Of or relating to calisthenics','bodyweight exercises-based,characteristic','C1'],
      ['calisthenicsous','adj','Full of calisthenics','bodyweight exercises-filled,abundant','C2'],
      ['calisthenicsful','adj','Full of calisthenics','bodyweight exercises-rich,abounding','C1'],
      ['calisthenicsless','adj','Without calisthenics','lacking,without','C1'],
      ['calisthenicsism','n','The ideology of calisthenics','bodyweight exercises ideology,doctrine','C2'],
      ['calisthenicsist','n','A person focused on calisthenics','bodyweight exercises specialist,advocate','C2'],
      ['calisthenicsise','v','To make into calisthenics','bodyweight exercises,convert','C2'],
      ['calisthenicsize','v','To make or become calisthenics','bodyweight exercises,transform','C2'],
      ['anticalisthenics','adj','Opposed to calisthenics','against,opposing','C2'],
      ['noncalisthenics','adj','Not involving calisthenics','without,lacking','C1'],
      ['precalisthenics','n','Before calisthenics','preceding,prior','C2'],
      ['postcalisthenics','n','After calisthenics','following,subsequent','C2'],
      ['subcalisthenics','n','A subdivision of calisthenics','subset,branch','C2'],
      ['multicalisthenics','adj','Involving many calisthenicss','multiple,several','C2'],
      ['intercalisthenics','adj','Between calisthenicss','cross,between','C2'],
      ['physiotherapyic','adj','Of or relating to physiotherapy','physical therapy-based,characteristic','B2'],
      ['physiotherapyous','adj','Full of physiotherapy','physical therapy-filled,abundant','C1'],
      ['physiotherapyful','adj','Full of physiotherapy','physical therapy-rich,abounding','B2'],
      ['physiotherapyless','adj','Without physiotherapy','lacking,without','B2'],
      ['physiotherapyism','n','The ideology of physiotherapy','physical therapy ideology,doctrine','C1'],
      ['physiotherapyist','n','A person focused on physiotherapy','physical therapy specialist,advocate','C1'],
      ['physiotherapyise','v','To make into physiotherapy','physical therapy,convert','C1'],
      ['physiotherapyize','v','To make or become physiotherapy','physical therapy,transform','C1'],
      ['antiphysiotherapy','adj','Opposed to physiotherapy','against,opposing','C1'],
      ['nonphysiotherapy','adj','Not involving physiotherapy','without,lacking','B2'],
      ['prephysiotherapy','n','Before physiotherapy','preceding,prior','C1'],
      ['postphysiotherapy','n','After physiotherapy','following,subsequent','C1'],
      ['subphysiotherapy','n','A subdivision of physiotherapy','subset,branch','C1'],
      ['multiphysiotherapy','adj','Involving many physiotherapys','multiple,several','C1'],
      ['interphysiotherapy','adj','Between physiotherapys','cross,between','C1'],
      ['biomechanicsic','adj','Of or relating to biomechanics','movement science-based,characteristic','C1'],
      ['biomechanicsous','adj','Full of biomechanics','movement science-filled,abundant','C2'],
      ['biomechanicsful','adj','Full of biomechanics','movement science-rich,abounding','C1'],
      ['biomechanicsless','adj','Without biomechanics','lacking,without','C1'],
      ['biomechanicsism','n','The ideology of biomechanics','movement science ideology,doctrine','C2'],
      ['biomechanicsist','n','A person focused on biomechanics','movement science specialist,advocate','C2'],
      ['biomechanicsise','v','To make into biomechanics','movement science,convert','C2'],
      ['biomechanicsize','v','To make or become biomechanics','movement science,transform','C2'],
      ['antibiomechanics','adj','Opposed to biomechanics','against,opposing','C2'],
      ['nonbiomechanics','adj','Not involving biomechanics','without,lacking','C1'],
      ['prebiomechanics','n','Before biomechanics','preceding,prior','C2'],
      ['postbiomechanics','n','After biomechanics','following,subsequent','C2'],
      ['subbiomechanics','n','A subdivision of biomechanics','subset,branch','C2'],
      ['multibiomechanics','adj','Involving many biomechanicss','multiple,several','C2'],
      ['interbiomechanics','adj','Between biomechanicss','cross,between','C2'],
      ['plyometricsic','adj','Of or relating to plyometrics','jump training-based,characteristic','C1'],
      ['plyometricsous','adj','Full of plyometrics','jump training-filled,abundant','C2'],
      ['plyometricsful','adj','Full of plyometrics','jump training-rich,abounding','C1'],
      ['plyometricsless','adj','Without plyometrics','lacking,without','C1'],
      ['plyometricsism','n','The ideology of plyometrics','jump training ideology,doctrine','C2'],
      ['plyometricsist','n','A person focused on plyometrics','jump training specialist,advocate','C2'],
      ['plyometricsise','v','To make into plyometrics','jump training,convert','C2'],
      ['plyometricsize','v','To make or become plyometrics','jump training,transform','C2'],
      ['antiplyometrics','adj','Opposed to plyometrics','against,opposing','C2'],
      ['nonplyometrics','adj','Not involving plyometrics','without,lacking','C1'],
      ['preplyometrics','n','Before plyometrics','preceding,prior','C2'],
      ['postplyometrics','n','After plyometrics','following,subsequent','C2'],
      ['subplyometrics','n','A subdivision of plyometrics','subset,branch','C2'],
      ['multiplyometrics','adj','Involving many plyometricss','multiple,several','C2'],
      ['interplyometrics','adj','Between plyometricss','cross,between','C2'],
      ['dopingic','adj','Of or relating to doping','cheating-based,characteristic','B2'],
      ['dopingous','adj','Full of doping','cheating-filled,abundant','C1'],
      ['dopingful','adj','Full of doping','cheating-rich,abounding','B2'],
      ['dopingless','adj','Without doping','lacking,without','B2'],
      ['dopingism','n','The ideology of doping','cheating ideology,doctrine','C1'],
      ['dopingist','n','A person focused on doping','cheating specialist,advocate','C1'],
      ['dopingise','v','To make into doping','cheating,convert','C1'],
      ['dopingize','v','To make or become doping','cheating,transform','C1'],
      ['antidoping','adj','Opposed to doping','against,opposing','C1'],
      ['nondoping','adj','Not involving doping','without,lacking','B2'],
    ],
  },
  collocations: {}
};
