// Auto-generated vocab boost group 71
module.exports = {
  vocab: {
    arts: [
      ['paletteize','v','To make or become palette','colour range,transform','C1'],
      ['antipalette','adj','Opposed to palette','against,opposing','C1'],
      ['nonpalette','adj','Not involving palette','without,lacking','B2'],
      ['prepalette','n','Before palette','preceding,prior','C1'],
      ['postpalette','n','After palette','following,subsequent','C1'],
      ['subpalette','n','A subdivision of palette','subset,branch','C1'],
      ['multipalette','adj','Involving many palettes','multiple,several','C1'],
      ['interpalette','adj','Between palettes','cross,between','C1'],
      ['virtuosoal','adj','Relating to virtuoso','master-related,pertaining to','C1'],
      ['virtuosoic','adj','Of or relating to virtuoso','master-based,characteristic','C1'],
      ['virtuosoous','adj','Full of virtuoso','master-filled,abundant','C2'],
      ['virtuosoful','adj','Full of virtuoso','master-rich,abounding','C1'],
      ['virtuosoless','adj','Without virtuoso','lacking,without','C1'],
      ['virtuosoism','n','The ideology of virtuoso','master ideology,doctrine','C2'],
      ['virtuosoist','n','A person focused on virtuoso','master specialist,advocate','C2'],
      ['virtuosoise','v','To make into virtuoso','master,convert','C2'],
      ['virtuosoize','v','To make or become virtuoso','master,transform','C2'],
      ['antivirtuoso','adj','Opposed to virtuoso','against,opposing','C2'],
      ['nonvirtuoso','adj','Not involving virtuoso','without,lacking','C1'],
      ['previrtuoso','n','Before virtuoso','preceding,prior','C2'],
      ['postvirtuoso','n','After virtuoso','following,subsequent','C2'],
      ['subvirtuoso','n','A subdivision of virtuoso','subset,branch','C2'],
      ['multivirtuoso','adj','Involving many virtuosos','multiple,several','C2'],
      ['intervirtuoso','adj','Between virtuosos','cross,between','C2'],
      ['masterpieceic','adj','Of or relating to masterpiece','magnum opus-based,characteristic','B2'],
      ['masterpieceous','adj','Full of masterpiece','magnum opus-filled,abundant','C1'],
      ['masterpieceful','adj','Full of masterpiece','magnum opus-rich,abounding','B2'],
      ['masterpieceless','adj','Without masterpiece','lacking,without','B2'],
      ['masterpieceism','n','The ideology of masterpiece','magnum opus ideology,doctrine','C1'],
      ['masterpieceist','n','A person focused on masterpiece','magnum opus specialist,advocate','C1'],
      ['masterpieceise','v','To make into masterpiece','magnum opus,convert','C1'],
      ['masterpieceize','v','To make or become masterpiece','magnum opus,transform','C1'],
      ['antimasterpiece','adj','Opposed to masterpiece','against,opposing','C1'],
      ['nonmasterpiece','adj','Not involving masterpiece','without,lacking','B2'],
      ['premasterpiece','n','Before masterpiece','preceding,prior','C1'],
      ['postmasterpiece','n','After masterpiece','following,subsequent','C1'],
      ['submasterpiece','n','A subdivision of masterpiece','subset,branch','C1'],
      ['multimasterpiece','adj','Involving many masterpieces','multiple,several','C1'],
      ['intermasterpiece','adj','Between masterpieces','cross,between','C1'],
      ['retrospectiveal','adj','Relating to retrospective','review-related,pertaining to','B2'],
      ['retrospectiveic','adj','Of or relating to retrospective','review-based,characteristic','B2'],
      ['retrospectiveous','adj','Full of retrospective','review-filled,abundant','C1'],
      ['retrospectiveful','adj','Full of retrospective','review-rich,abounding','B2'],
      ['retrospectiveless','adj','Without retrospective','lacking,without','B2'],
      ['retrospectiveism','n','The ideology of retrospective','review ideology,doctrine','C1'],
      ['retrospectiveist','n','A person focused on retrospective','review specialist,advocate','C1'],
      ['retrospectiveise','v','To make into retrospective','review,convert','C1'],
      ['retrospectiveize','v','To make or become retrospective','review,transform','C1'],
      ['antiretrospective','adj','Opposed to retrospective','against,opposing','C1'],
      ['nonretrospective','adj','Not involving retrospective','without,lacking','B2'],
      ['preretrospective','n','Before retrospective','preceding,prior','C1'],
      ['postretrospective','n','After retrospective','following,subsequent','C1'],
      ['subretrospective','n','A subdivision of retrospective','subset,branch','C1'],
      ['multiretrospective','adj','Involving many retrospectives','multiple,several','C1'],
      ['interretrospective','adj','Between retrospectives','cross,between','C1'],
      ['muralal','adj','Relating to mural','wall painting-related,pertaining to','B2'],
      ['muralic','adj','Of or relating to mural','wall painting-based,characteristic','B2'],
      ['muralous','adj','Full of mural','wall painting-filled,abundant','C1'],
      ['muralful','adj','Full of mural','wall painting-rich,abounding','B2'],
      ['muralless','adj','Without mural','lacking,without','B2'],
      ['muralism','n','The ideology of mural','wall painting ideology,doctrine','C1'],
      ['muralist','n','A person focused on mural','wall painting specialist,advocate','C1'],
      ['muralise','v','To make into mural','wall painting,convert','C1'],
      ['muralize','v','To make or become mural','wall painting,transform','C1'],
      ['antimural','adj','Opposed to mural','against,opposing','C1'],
      ['nonmural','adj','Not involving mural','without,lacking','B2'],
      ['premural','n','Before mural','preceding,prior','C1'],
      ['postmural','n','After mural','following,subsequent','C1'],
      ['submural','n','A subdivision of mural','subset,branch','C1'],
      ['multimural','adj','Involving many murals','multiple,several','C1'],
      ['intermural','adj','Between murals','cross,between','C1'],
      ['installational','adj','Relating to installation','display-related,pertaining to','B2'],
      ['installationic','adj','Of or relating to installation','display-based,characteristic','B2'],
      ['installationous','adj','Full of installation','display-filled,abundant','C1'],
      ['installationful','adj','Full of installation','display-rich,abounding','B2'],
      ['installationless','adj','Without installation','lacking,without','B2'],
      ['installationism','n','The ideology of installation','display ideology,doctrine','C1'],
      ['installationist','n','A person focused on installation','display specialist,advocate','C1'],
      ['installationise','v','To make into installation','display,convert','C1'],
      ['installationize','v','To make or become installation','display,transform','C1'],
      ['antiinstallation','adj','Opposed to installation','against,opposing','C1'],
      ['noninstallation','adj','Not involving installation','without,lacking','B2'],
      ['preinstallation','n','Before installation','preceding,prior','C1'],
      ['postinstallation','n','After installation','following,subsequent','C1'],
      ['subinstallation','n','A subdivision of installation','subset,branch','C1'],
      ['multiinstallation','adj','Involving many installations','multiple,several','C1'],
      ['interinstallation','adj','Between installations','cross,between','C1'],
      ['motifal','adj','Relating to motif','theme-related,pertaining to','B2'],
      ['motific','adj','Of or relating to motif','theme-based,characteristic','B2'],
      ['motifous','adj','Full of motif','theme-filled,abundant','C1'],
      ['motifful','adj','Full of motif','theme-rich,abounding','B2'],
      ['motifless','adj','Without motif','lacking,without','B2'],
      ['motifism','n','The ideology of motif','theme ideology,doctrine','C1'],
      ['motifist','n','A person focused on motif','theme specialist,advocate','C1'],
      ['motifise','v','To make into motif','theme,convert','C1'],
      ['motifize','v','To make or become motif','theme,transform','C1'],
      ['antimotif','adj','Opposed to motif','against,opposing','C1'],
      ['nonmotif','adj','Not involving motif','without,lacking','B2'],
      ['premotif','n','Before motif','preceding,prior','C1'],
      ['postmotif','n','After motif','following,subsequent','C1'],
      ['submotif','n','A subdivision of motif','subset,branch','C1'],
      ['multimotif','adj','Involving many motifs','multiple,several','C1'],
      ['intermotif','adj','Between motifs','cross,between','C1'],
      ['allegoryal','adj','Relating to allegory','fable-related,pertaining to','C1'],
      ['allegoryic','adj','Of or relating to allegory','fable-based,characteristic','C1'],
      ['allegoryous','adj','Full of allegory','fable-filled,abundant','C2'],
      ['allegoryful','adj','Full of allegory','fable-rich,abounding','C1'],
      ['allegoryless','adj','Without allegory','lacking,without','C1'],
      ['allegoryism','n','The ideology of allegory','fable ideology,doctrine','C2'],
      ['allegoryist','n','A person focused on allegory','fable specialist,advocate','C2'],
      ['allegoryise','v','To make into allegory','fable,convert','C2'],
      ['allegoryize','v','To make or become allegory','fable,transform','C2'],
      ['antiallegory','adj','Opposed to allegory','against,opposing','C2'],
      ['nonallegory','adj','Not involving allegory','without,lacking','C1'],
      ['preallegory','n','Before allegory','preceding,prior','C2'],
      ['postallegory','n','After allegory','following,subsequent','C2'],
      ['suballegory','n','A subdivision of allegory','subset,branch','C2'],
      ['multiallegory','adj','Involving many allegorys','multiple,several','C2'],
      ['interallegory','adj','Between allegorys','cross,between','C2'],
      ['surrealist','adj','Relating to dreamlike art','dreamlike,fantastical,bizarre','B2'],
      ['surrealistly','adv','In a surrealist manner','dreamlike way','B2'],
      ['surrealistness','n','The quality of being surrealist','dreamlike quality','B2'],
      ['surrealistity','n','The state of being surrealist','dreamlike condition','C1'],
      ['unsurrealist','adj','Not surrealist','not dreamlike','B2'],
      ['insurrealist','adj','Not surrealist','not dreamlike','C1'],
      ['nonsurrealist','adj','Not surrealist','not dreamlike','B2'],
      ['semisurrealist','adj','Partially surrealist','partly dreamlike','C1'],
      ['oversurrealist','adj','Excessively surrealist','too dreamlike','C1'],
      ['ultrasurrealist','adj','Extremely surrealist','very dreamlike','C1'],
      ['minimalistly','adv','In a minimalist manner','simple way','B2'],
      ['minimalistness','n','The quality of being minimalist','simple quality','B2'],
      ['minimalistity','n','The state of being minimalist','simple condition','C1'],
      ['unminimalist','adj','Not minimalist','not simple','B2'],
      ['inminimalist','adj','Not minimalist','not simple','C1'],
      ['nonminimalist','adj','Not minimalist','not simple','B2'],
      ['semiminimalist','adj','Partially minimalist','partly simple','C1'],
      ['overminimalist','adj','Excessively minimalist','too simple','C1'],
      ['ultraminimalist','adj','Extremely minimalist','very simple','C1'],
      ['expressionist','adj','Conveying emotional experience in art','emotional,subjective,dramatic','B2'],
      ['expressionistly','adv','In a expressionist manner','emotional way','B2'],
      ['expressionistness','n','The quality of being expressionist','emotional quality','B2'],
      ['expressionistity','n','The state of being expressionist','emotional condition','C1'],
      ['unexpressionist','adj','Not expressionist','not emotional','B2'],
      ['inexpressionist','adj','Not expressionist','not emotional','C1'],
      ['nonexpressionist','adj','Not expressionist','not emotional','B2'],
      ['semiexpressionist','adj','Partially expressionist','partly emotional','C1'],
      ['overexpressionist','adj','Excessively expressionist','too emotional','C1'],
      ['ultraexpressionist','adj','Extremely expressionist','very emotional','C1'],
      ['figuratively','adv','In a figurative manner','representational way','B2'],
      ['figurativeness','n','The quality of being figurative','representational quality','B2'],
      ['figurativeity','n','The state of being figurative','representational condition','C1'],
      ['unfigurative','adj','Not figurative','not representational','B2'],
      ['infigurative','adj','Not figurative','not representational','C1'],
      ['nonfigurative','adj','Not figurative','not representational','B2'],
      ['semifigurative','adj','Partially figurative','partly representational','C1'],
      ['overfigurative','adj','Excessively figurative','too representational','C1'],
      ['ultrafigurative','adj','Extremely figurative','very representational','C1'],
      ['abstractity','n','The state of being abstract','non-representational condition','C1'],
      ['inabstract','adj','Not abstract','not non-representational','C1'],
      ['nonabstract','adj','Not abstract','not non-representational','B2'],
      ['semiabstract','adj','Partially abstract','partly non-representational','C1'],
      ['overabstract','adj','Excessively abstract','too non-representational','C1'],
      ['ultraabstract','adj','Extremely abstract','very non-representational','C1'],
      ['contemporarness','n','The quality of being contemporary','modern quality','B2'],
      ['contemporarity','n','The state of being contemporary','modern condition','C1'],
      ['incontemporary','adj','Not contemporary','not modern','C1'],
      ['noncontemporary','adj','Not contemporary','not modern','B2'],
      ['semicontemporary','adj','Partially contemporary','partly modern','C1'],
      ['overcontemporary','adj','Excessively contemporary','too modern','C1'],
      ['ultracontemporary','adj','Extremely contemporary','very modern','C1'],
      ['provocatively','adv','In a provocative manner','challenging way','B2'],
      ['provocativeness','n','The quality of being provocative','challenging quality','B2'],
      ['provocativeity','n','The state of being provocative','challenging condition','C1'],
      ['unprovocative','adj','Not provocative','not challenging','B2'],
      ['inprovocative','adj','Not provocative','not challenging','C1'],
      ['nonprovocative','adj','Not provocative','not challenging','B2'],
      ['semiprovocative','adj','Partially provocative','partly challenging','C1'],
      ['overprovocative','adj','Excessively provocative','too challenging','C1'],
      ['ultraprovocative','adj','Extremely provocative','very challenging','C1'],
      ['ornately','adv','In a ornate manner','elaborate way','C1'],
      ['ornateness','n','The quality of being ornate','elaborate quality','C1'],
      ['ornateity','n','The state of being ornate','elaborate condition','C2'],
      ['unornate','adj','Not ornate','not elaborate','C1'],
      ['inornate','adj','Not ornate','not elaborate','C2'],
      ['nonornate','adj','Not ornate','not elaborate','C1'],
      ['semiornate','adj','Partially ornate','partly elaborate','C2'],
      ['overornate','adj','Excessively ornate','too elaborate','C2'],
      ['ultraornate','adj','Extremely ornate','very elaborate','C2'],
      ['tableauic','adj','Of or relating to tableau','scene-based,characteristic','C1'],
      ['tableauous','adj','Full of tableau','scene-filled,abundant','C2'],
      ['tableauful','adj','Full of tableau','scene-rich,abounding','C1'],
      ['tableauless','adj','Without tableau','lacking,without','C1'],
      ['tableauism','n','The ideology of tableau','scene ideology,doctrine','C2'],
      ['tableauist','n','A person focused on tableau','scene specialist,advocate','C2'],
      ['tableauise','v','To make into tableau','scene,convert','C2'],
      ['tableauize','v','To make or become tableau','scene,transform','C2'],
      ['antitableau','adj','Opposed to tableau','against,opposing','C2'],
      ['nontableau','adj','Not involving tableau','without,lacking','C1'],
      ['pretableau','n','Before tableau','preceding,prior','C2'],
      ['posttableau','n','After tableau','following,subsequent','C2'],
      ['subtableau','n','A subdivision of tableau','subset,branch','C2'],
      ['multitableau','adj','Involving many tableaus','multiple,several','C2'],
      ['intertableau','adj','Between tableaus','cross,between','C2'],
      ['patinaic','adj','Of or relating to patina','sheen-based,characteristic','C1'],
      ['patinaous','adj','Full of patina','sheen-filled,abundant','C2'],
      ['patinaful','adj','Full of patina','sheen-rich,abounding','C1'],
      ['patinaless','adj','Without patina','lacking,without','C1'],
      ['patinaism','n','The ideology of patina','sheen ideology,doctrine','C2'],
      ['patinaist','n','A person focused on patina','sheen specialist,advocate','C2'],
      ['patinaise','v','To make into patina','sheen,convert','C2'],
      ['patinaize','v','To make or become patina','sheen,transform','C2'],
      ['antipatina','adj','Opposed to patina','against,opposing','C2'],
      ['nonpatina','adj','Not involving patina','without,lacking','C1'],
      ['prepatina','n','Before patina','preceding,prior','C2'],
      ['postpatina','n','After patina','following,subsequent','C2'],
      ['subpatina','n','A subdivision of patina','subset,branch','C2'],
      ['multipatina','adj','Involving many patinas','multiple,several','C2'],
      ['interpatina','adj','Between patinas','cross,between','C2'],
      ['chiaroscuroic','adj','Of or relating to chiaroscuro','light-dark contrast-based,characteristic','C2'],
      ['chiaroscuroous','adj','Full of chiaroscuro','light-dark contrast-filled,abundant','C2'],
      ['chiaroscuroful','adj','Full of chiaroscuro','light-dark contrast-rich,abounding','C2'],
      ['chiaroscuroless','adj','Without chiaroscuro','lacking,without','C2'],
      ['chiaroscuroism','n','The ideology of chiaroscuro','light-dark contrast ideology,doctrine','C2'],
      ['chiaroscuroist','n','A person focused on chiaroscuro','light-dark contrast specialist,advocate','C2'],
      ['chiaroscuroise','v','To make into chiaroscuro','light-dark contrast,convert','C2'],
      ['chiaroscuroize','v','To make or become chiaroscuro','light-dark contrast,transform','C2'],
      ['antichiaroscuro','adj','Opposed to chiaroscuro','against,opposing','C2'],
      ['nonchiaroscuro','adj','Not involving chiaroscuro','without,lacking','C2'],
      ['prechiaroscuro','n','Before chiaroscuro','preceding,prior','C2'],
      ['postchiaroscuro','n','After chiaroscuro','following,subsequent','C2'],
      ['subchiaroscuro','n','A subdivision of chiaroscuro','subset,branch','C2'],
      ['multichiaroscuro','adj','Involving many chiaroscuros','multiple,several','C2'],
      ['interchiaroscuro','adj','Between chiaroscuros','cross,between','C2'],
      ['trompe-l-oeilal','adj','Relating to trompe-l-oeil','optical illusion-related,pertaining to','C2'],
      ['trompe-l-oeilic','adj','Of or relating to trompe-l-oeil','optical illusion-based,characteristic','C2'],
      ['trompe-l-oeilous','adj','Full of trompe-l-oeil','optical illusion-filled,abundant','C2'],
      ['trompe-l-oeilful','adj','Full of trompe-l-oeil','optical illusion-rich,abounding','C2'],
      ['trompe-l-oeilless','adj','Without trompe-l-oeil','lacking,without','C2'],
      ['trompe-l-oeilism','n','The ideology of trompe-l-oeil','optical illusion ideology,doctrine','C2'],
      ['trompe-l-oeilist','n','A person focused on trompe-l-oeil','optical illusion specialist,advocate','C2'],
      ['trompe-l-oeilise','v','To make into trompe-l-oeil','optical illusion,convert','C2'],
      ['trompe-l-oeilize','v','To make or become trompe-l-oeil','optical illusion,transform','C2'],
      ['antitrompe-l-oeil','adj','Opposed to trompe-l-oeil','against,opposing','C2'],
      ['nontrompe-l-oeil','adj','Not involving trompe-l-oeil','without,lacking','C2'],
      ['pretrompe-l-oeil','n','Before trompe-l-oeil','preceding,prior','C2'],
      ['posttrompe-l-oeil','n','After trompe-l-oeil','following,subsequent','C2'],
      ['subtrompe-l-oeil','n','A subdivision of trompe-l-oeil','subset,branch','C2'],
      ['multitrompe-l-oeil','adj','Involving many trompe-l-oeils','multiple,several','C2'],
      ['intertrompe-l-oeil','adj','Between trompe-l-oeils','cross,between','C2'],
      ['sfumatoic','adj','Of or relating to sfumato','blending-based,characteristic','C2'],
    ],
  },
  collocations: {}
};
