// Auto-generated vocab boost group 40
module.exports = {
  vocab: {
    health: [
      ['prescribence','n','The quality of prescribing','recommend quality','B2'],
      ['prescribal','n','An act of prescribing','recommend event','C1'],
      ['prescriber','n','One who prescribes','recommend person','B2'],
      ['prescribor','n','One who prescribes','recommend agent','B2'],
      ['prescribee','n','One who is prescribed','recommend recipient','C1'],
      ['prescribable','adj','Capable of being prescribed','recommend,possible','C1'],
      ['prescribible','adj','Able to be prescribed','recommend,feasible','C1'],
      ['prescribive','adj','Tending to prescribe','recommend,active','B2'],
      ['prescribing','adj','Currently prescribing','recommend,ongoing','B2'],
      ['prescribed','adj','Having been prescribed','recommend,completed','B2'],
      ['represcribe','v','To prescribe again','recommend again,repeat','B2'],
      ['unprescribe','v','To reverse prescribing','reverse,undo','C1'],
      ['overprescribe','v','To prescribe excessively','excess,too much','C1'],
      ['underprescribe','v','To prescribe insufficiently','insufficient,inadequate','C1'],
      ['misprescribe','v','To prescribe incorrectly','wrongly,incorrectly','C1'],
      ['preprescribe','v','To prescribe beforehand','before,in advance','C1'],
      ['coprescribe','v','To prescribe together','jointly,together','C1'],
      ['represcribation','n','The act of prescribing again','re-recommend','C1'],
      ['overprescribation','n','Excessive prescribing','excess recommend','C1'],
      ['rehabilitatation','n','The act of rehabilitating','restore process','B2'],
      ['rehabilitatment','n','The result of rehabilitating','restore outcome','B2'],
      ['rehabilitatance','n','The state of rehabilitating','restore state','B2'],
      ['rehabilitatence','n','The quality of rehabilitating','restore quality','B2'],
      ['rehabilitatal','n','An act of rehabilitating','restore event','C1'],
      ['rehabilitater','n','One who rehabilitates','restore person','B2'],
      ['rehabilitator','n','One who rehabilitates','restore agent','B2'],
      ['rehabilitatee','n','One who is rehabilitated','restore recipient','C1'],
      ['rehabilitatable','adj','Capable of being rehabilitated','restore,possible','C1'],
      ['rehabilitatible','adj','Able to be rehabilitated','restore,feasible','C1'],
      ['rehabilitative','adj','Tending to rehabilitate','restore,active','B2'],
      ['rehabilitating','adj','Currently rehabilitating','restore,ongoing','B2'],
      ['rehabilitated','adj','Having been rehabilitated','restore,completed','B2'],
      ['rerehabilitate','v','To rehabilitate again','restore again,repeat','B2'],
      ['unrehabilitate','v','To reverse rehabilitating','reverse,undo','C1'],
      ['overrehabilitate','v','To rehabilitate excessively','excess,too much','C1'],
      ['underrehabilitate','v','To rehabilitate insufficiently','insufficient,inadequate','C1'],
      ['misrehabilitate','v','To rehabilitate incorrectly','wrongly,incorrectly','C1'],
      ['prerehabilitate','v','To rehabilitate beforehand','before,in advance','C1'],
      ['corehabilitate','v','To rehabilitate together','jointly,together','C1'],
      ['rerehabilitatation','n','The act of rehabilitating again','re-restore','C1'],
      ['overrehabilitatation','n','Excessive rehabilitating','excess restore','C1'],
      ['immunization','n','The act of immunizing','vaccinate process','B2'],
      ['immunizment','n','The result of immunizing','vaccinate outcome','B2'],
      ['immunizance','n','The state of immunizing','vaccinate state','B2'],
      ['immunizence','n','The quality of immunizing','vaccinate quality','B2'],
      ['immunizal','n','An act of immunizing','vaccinate event','C1'],
      ['immunizer','n','One who immunizes','vaccinate person','B2'],
      ['immunizor','n','One who immunizes','vaccinate agent','B2'],
      ['immunizee','n','One who is immunized','vaccinate recipient','C1'],
      ['immunizable','adj','Capable of being immunized','vaccinate,possible','C1'],
      ['immunizible','adj','Able to be immunized','vaccinate,feasible','C1'],
      ['immunizive','adj','Tending to immunize','vaccinate,active','B2'],
      ['immunizing','adj','Currently immunizing','vaccinate,ongoing','B2'],
      ['immunized','adj','Having been immunized','vaccinate,completed','B2'],
      ['reimmunize','v','To immunize again','vaccinate again,repeat','B2'],
      ['unimmunize','v','To reverse immunizing','reverse,undo','C1'],
      ['overimmunize','v','To immunize excessively','excess,too much','C1'],
      ['underimmunize','v','To immunize insufficiently','insufficient,inadequate','C1'],
      ['misimmunize','v','To immunize incorrectly','wrongly,incorrectly','C1'],
      ['preimmunize','v','To immunize beforehand','before,in advance','C1'],
      ['coimmunize','v','To immunize together','jointly,together','C1'],
      ['reimmunization','n','The act of immunizing again','re-vaccinate','C1'],
      ['overimmunization','n','Excessive immunizing','excess vaccinate','C1'],
      ['alleviatation','n','The act of alleviating','relieve process','B2'],
      ['alleviatment','n','The result of alleviating','relieve outcome','B2'],
      ['alleviatance','n','The state of alleviating','relieve state','B2'],
      ['alleviatence','n','The quality of alleviating','relieve quality','B2'],
      ['alleviatal','n','An act of alleviating','relieve event','C1'],
      ['alleviater','n','One who alleviates','relieve person','B2'],
      ['alleviator','n','One who alleviates','relieve agent','B2'],
      ['alleviatee','n','One who is alleviated','relieve recipient','C1'],
      ['alleviatable','adj','Capable of being alleviated','relieve,possible','C1'],
      ['alleviatible','adj','Able to be alleviated','relieve,feasible','C1'],
      ['alleviative','adj','Tending to alleviate','relieve,active','B2'],
      ['alleviating','adj','Currently alleviating','relieve,ongoing','B2'],
      ['alleviated','adj','Having been alleviated','relieve,completed','B2'],
      ['realleviate','v','To alleviate again','relieve again,repeat','B2'],
      ['unalleviate','v','To reverse alleviating','reverse,undo','C1'],
      ['overalleviate','v','To alleviate excessively','excess,too much','C1'],
      ['underalleviate','v','To alleviate insufficiently','insufficient,inadequate','C1'],
      ['misalleviate','v','To alleviate incorrectly','wrongly,incorrectly','C1'],
      ['prealleviate','v','To alleviate beforehand','before,in advance','C1'],
      ['coalleviate','v','To alleviate together','jointly,together','C1'],
      ['realleviatation','n','The act of alleviating again','re-relieve','C1'],
      ['overalleviatation','n','Excessive alleviating','excess relieve','C1'],
      ['deterioratation','n','The act of deteriorating','worsen process','B2'],
      ['deterioratment','n','The result of deteriorating','worsen outcome','B2'],
      ['deterioratance','n','The state of deteriorating','worsen state','B2'],
      ['deterioratence','n','The quality of deteriorating','worsen quality','B2'],
      ['deterioratal','n','An act of deteriorating','worsen event','C1'],
      ['deteriorater','n','One who deteriorates','worsen person','B2'],
      ['deteriorator','n','One who deteriorates','worsen agent','B2'],
      ['deterioratee','n','One who is deteriorated','worsen recipient','C1'],
      ['deterioratable','adj','Capable of being deteriorated','worsen,possible','C1'],
      ['deterioratible','adj','Able to be deteriorated','worsen,feasible','C1'],
      ['deteriorative','adj','Tending to deteriorate','worsen,active','B2'],
      ['deteriorating','adj','Currently deteriorating','worsen,ongoing','B2'],
      ['deteriorated','adj','Having been deteriorated','worsen,completed','B2'],
      ['redeteriorate','v','To deteriorate again','worsen again,repeat','B2'],
      ['undeteriorate','v','To reverse deteriorating','reverse,undo','C1'],
      ['overdeteriorate','v','To deteriorate excessively','excess,too much','C1'],
      ['underdeteriorate','v','To deteriorate insufficiently','insufficient,inadequate','C1'],
      ['misdeteriorate','v','To deteriorate incorrectly','wrongly,incorrectly','C1'],
      ['predeteriorate','v','To deteriorate beforehand','before,in advance','C1'],
      ['codeteriorate','v','To deteriorate together','jointly,together','C1'],
      ['redeterioratation','n','The act of deteriorating again','re-worsen','C1'],
      ['overdeterioratation','n','Excessive deteriorating','excess worsen','C1'],
      ['recuperate','v','To recover from illness or exertion','recover,heal,convalesce','C1'],
      ['recuperatation','n','The act of recuperating','recover process','C1'],
      ['recuperatment','n','The result of recuperating','recover outcome','C1'],
      ['recuperatance','n','The state of recuperating','recover state','C1'],
      ['recuperatence','n','The quality of recuperating','recover quality','C1'],
      ['recuperatal','n','An act of recuperating','recover event','C2'],
      ['recuperater','n','One who recuperates','recover person','C1'],
      ['recuperator','n','One who recuperates','recover agent','C1'],
      ['recuperatee','n','One who is recuperated','recover recipient','C2'],
      ['recuperatable','adj','Capable of being recuperated','recover,possible','C2'],
      ['recuperatible','adj','Able to be recuperated','recover,feasible','C2'],
      ['recuperative','adj','Tending to recuperate','recover,active','C1'],
      ['recuperating','adj','Currently recuperating','recover,ongoing','C1'],
      ['recuperated','adj','Having been recuperated','recover,completed','C1'],
      ['rerecuperate','v','To recuperate again','recover again,repeat','C1'],
      ['unrecuperate','v','To reverse recuperating','reverse,undo','C2'],
      ['overrecuperate','v','To recuperate excessively','excess,too much','C2'],
      ['underrecuperate','v','To recuperate insufficiently','insufficient,inadequate','C2'],
      ['misrecuperate','v','To recuperate incorrectly','wrongly,incorrectly','C2'],
      ['prerecuperate','v','To recuperate beforehand','before,in advance','C2'],
      ['corecuperate','v','To recuperate together','jointly,together','C2'],
      ['rerecuperatation','n','The act of recuperating again','re-recover','C2'],
      ['overrecuperatation','n','Excessive recuperating','excess recover','C2'],
      ['resuscitatation','n','The act of resuscitating','revive process','C1'],
      ['resuscitatment','n','The result of resuscitating','revive outcome','C1'],
      ['resuscitatance','n','The state of resuscitating','revive state','C1'],
      ['resuscitatence','n','The quality of resuscitating','revive quality','C1'],
      ['resuscitatal','n','An act of resuscitating','revive event','C2'],
      ['resuscitater','n','One who resuscitates','revive person','C1'],
      ['resuscitator','n','One who resuscitates','revive agent','C1'],
      ['resuscitatee','n','One who is resuscitated','revive recipient','C2'],
      ['resuscitatable','adj','Capable of being resuscitated','revive,possible','C2'],
      ['resuscitatible','adj','Able to be resuscitated','revive,feasible','C2'],
      ['resuscitative','adj','Tending to resuscitate','revive,active','C1'],
      ['resuscitating','adj','Currently resuscitating','revive,ongoing','C1'],
      ['resuscitated','adj','Having been resuscitated','revive,completed','C1'],
      ['reresuscitate','v','To resuscitate again','revive again,repeat','C1'],
      ['unresuscitate','v','To reverse resuscitating','reverse,undo','C2'],
      ['overresuscitate','v','To resuscitate excessively','excess,too much','C2'],
      ['underresuscitate','v','To resuscitate insufficiently','insufficient,inadequate','C2'],
      ['misresuscitate','v','To resuscitate incorrectly','wrongly,incorrectly','C2'],
      ['preresuscitate','v','To resuscitate beforehand','before,in advance','C2'],
      ['coresuscitate','v','To resuscitate together','jointly,together','C2'],
      ['reresuscitatation','n','The act of resuscitating again','re-revive','C2'],
      ['overresuscitatation','n','Excessive resuscitating','excess revive','C2'],
      ['exacerbatation','n','The act of exacerbating','worsen process','C1'],
      ['exacerbatment','n','The result of exacerbating','worsen outcome','C1'],
      ['exacerbatance','n','The state of exacerbating','worsen state','C1'],
      ['exacerbatence','n','The quality of exacerbating','worsen quality','C1'],
      ['exacerbatal','n','An act of exacerbating','worsen event','C2'],
      ['exacerbater','n','One who exacerbates','worsen person','C1'],
      ['exacerbator','n','One who exacerbates','worsen agent','C1'],
      ['exacerbatee','n','One who is exacerbated','worsen recipient','C2'],
      ['exacerbatable','adj','Capable of being exacerbated','worsen,possible','C2'],
      ['exacerbatible','adj','Able to be exacerbated','worsen,feasible','C2'],
      ['exacerbative','adj','Tending to exacerbate','worsen,active','C1'],
      ['exacerbating','adj','Currently exacerbating','worsen,ongoing','C1'],
      ['exacerbated','adj','Having been exacerbated','worsen,completed','C1'],
      ['reexacerbate','v','To exacerbate again','worsen again,repeat','C1'],
      ['unexacerbate','v','To reverse exacerbating','reverse,undo','C2'],
      ['overexacerbate','v','To exacerbate excessively','excess,too much','C2'],
      ['underexacerbate','v','To exacerbate insufficiently','insufficient,inadequate','C2'],
      ['misexacerbate','v','To exacerbate incorrectly','wrongly,incorrectly','C2'],
      ['preexacerbate','v','To exacerbate beforehand','before,in advance','C2'],
      ['coexacerbate','v','To exacerbate together','jointly,together','C2'],
      ['reexacerbatation','n','The act of exacerbating again','re-worsen','C2'],
      ['overexacerbatation','n','Excessive exacerbating','excess worsen','C2'],
      ['convalescation','n','The act of convalescing','recover process','C1'],
      ['convalescment','n','The result of convalescing','recover outcome','C1'],
      ['convalescance','n','The state of convalescing','recover state','C1'],
      ['convalescence','n','The quality of convalescing','recover quality','C1'],
      ['convalescal','n','An act of convalescing','recover event','C2'],
      ['convalescer','n','One who convalesces','recover person','C1'],
      ['convalescor','n','One who convalesces','recover agent','C1'],
      ['convalescee','n','One who is convalesced','recover recipient','C2'],
      ['convalescable','adj','Capable of being convalesced','recover,possible','C2'],
      ['convalescible','adj','Able to be convalesced','recover,feasible','C2'],
      ['convalescive','adj','Tending to convalesce','recover,active','C1'],
      ['convalescing','adj','Currently convalescing','recover,ongoing','C1'],
      ['convalesced','adj','Having been convalesced','recover,completed','C1'],
      ['reconvalesce','v','To convalesce again','recover again,repeat','C1'],
      ['unconvalesce','v','To reverse convalescing','reverse,undo','C2'],
      ['overconvalesce','v','To convalesce excessively','excess,too much','C2'],
      ['underconvalesce','v','To convalesce insufficiently','insufficient,inadequate','C2'],
      ['misconvalesce','v','To convalesce incorrectly','wrongly,incorrectly','C2'],
      ['preconvalesce','v','To convalesce beforehand','before,in advance','C2'],
      ['coconvalesce','v','To convalesce together','jointly,together','C2'],
      ['reconvalescation','n','The act of convalescing again','re-recover','C2'],
      ['overconvalescation','n','Excessive convalescing','excess recover','C2'],
      ['inoculatation','n','The act of inoculating','vaccinate process','C1'],
      ['inoculatment','n','The result of inoculating','vaccinate outcome','C1'],
      ['inoculatance','n','The state of inoculating','vaccinate state','C1'],
      ['inoculatence','n','The quality of inoculating','vaccinate quality','C1'],
      ['inoculatal','n','An act of inoculating','vaccinate event','C2'],
      ['inoculater','n','One who inoculates','vaccinate person','C1'],
      ['inoculator','n','One who inoculates','vaccinate agent','C1'],
      ['inoculatee','n','One who is inoculated','vaccinate recipient','C2'],
      ['inoculatable','adj','Capable of being inoculated','vaccinate,possible','C2'],
      ['inoculatible','adj','Able to be inoculated','vaccinate,feasible','C2'],
      ['inoculative','adj','Tending to inoculate','vaccinate,active','C1'],
      ['inoculating','adj','Currently inoculating','vaccinate,ongoing','C1'],
      ['inoculated','adj','Having been inoculated','vaccinate,completed','C1'],
      ['reinoculate','v','To inoculate again','vaccinate again,repeat','C1'],
      ['uninoculate','v','To reverse inoculating','reverse,undo','C2'],
      ['overinoculate','v','To inoculate excessively','excess,too much','C2'],
      ['underinoculate','v','To inoculate insufficiently','insufficient,inadequate','C2'],
      ['misinoculate','v','To inoculate incorrectly','wrongly,incorrectly','C2'],
      ['preinoculate','v','To inoculate beforehand','before,in advance','C2'],
      ['coinoculate','v','To inoculate together','jointly,together','C2'],
      ['reinoculatation','n','The act of inoculating again','re-vaccinate','C2'],
      ['overinoculatation','n','Excessive inoculating','excess vaccinate','C2'],
      ['debilitatation','n','The act of debilitating','weaken process','C1'],
      ['debilitatment','n','The result of debilitating','weaken outcome','C1'],
      ['debilitatance','n','The state of debilitating','weaken state','C1'],
      ['debilitatence','n','The quality of debilitating','weaken quality','C1'],
      ['debilitatal','n','An act of debilitating','weaken event','C2'],
      ['debilitater','n','One who debilitates','weaken person','C1'],
      ['debilitator','n','One who debilitates','weaken agent','C1'],
      ['debilitatee','n','One who is debilitated','weaken recipient','C2'],
      ['debilitatable','adj','Capable of being debilitated','weaken,possible','C2'],
      ['debilitatible','adj','Able to be debilitated','weaken,feasible','C2'],
      ['debilitative','adj','Tending to debilitate','weaken,active','C1'],
      ['debilitated','adj','Having been debilitated','weaken,completed','C1'],
      ['redebilitate','v','To debilitate again','weaken again,repeat','C1'],
      ['undebilitate','v','To reverse debilitating','reverse,undo','C2'],
      ['overdebilitate','v','To debilitate excessively','excess,too much','C2'],
      ['underdebilitate','v','To debilitate insufficiently','insufficient,inadequate','C2'],
      ['misdebilitate','v','To debilitate incorrectly','wrongly,incorrectly','C2'],
      ['predebilitate','v','To debilitate beforehand','before,in advance','C2'],
      ['codebilitate','v','To debilitate together','jointly,together','C2'],
      ['redebilitatation','n','The act of debilitating again','re-weaken','C2'],
      ['overdebilitatation','n','Excessive debilitating','excess weaken','C2'],
      ['anaesthetize','v','To administer anaesthesia','numb,sedate,desensitize','C1'],
      ['anaesthetization','n','The act of anaesthetizing','numb process','C1'],
      ['anaesthetizment','n','The result of anaesthetizing','numb outcome','C1'],
      ['anaesthetizance','n','The state of anaesthetizing','numb state','C1'],
      ['anaesthetizence','n','The quality of anaesthetizing','numb quality','C1'],
      ['anaesthetizal','n','An act of anaesthetizing','numb event','C2'],
      ['anaesthetizer','n','One who anaesthetizes','numb person','C1'],
      ['anaesthetizor','n','One who anaesthetizes','numb agent','C1'],
      ['anaesthetizee','n','One who is anaesthetized','numb recipient','C2'],
      ['anaesthetizable','adj','Capable of being anaesthetized','numb,possible','C2'],
      ['anaesthetizible','adj','Able to be anaesthetized','numb,feasible','C2'],
    ],
  },
  collocations: {}
};
