// Auto-generated vocab boost group 86
module.exports = {
  vocab: {
    history: [
      ['antiimperialism','adj','Opposed to imperialism','against,opposing','C1'],
      ['nonimperialism','adj','Not involving imperialism','without,lacking','B2'],
      ['preimperialism','n','Before imperialism','preceding,prior','C1'],
      ['postimperialism','n','After imperialism','following,subsequent','C1'],
      ['subimperialism','n','A subdivision of imperialism','subset,branch','C1'],
      ['multiimperialism','adj','Involving many imperialisms','multiple,several','C1'],
      ['interimperialism','adj','Between imperialisms','cross,between','C1'],
      ['genocideic','adj','Of or relating to genocide','mass murder-based,characteristic','C1'],
      ['genocideous','adj','Full of genocide','mass murder-filled,abundant','C2'],
      ['genocideful','adj','Full of genocide','mass murder-rich,abounding','C1'],
      ['genocideless','adj','Without genocide','lacking,without','C1'],
      ['genocideism','n','The ideology of genocide','mass murder ideology,doctrine','C2'],
      ['genocideist','n','A person focused on genocide','mass murder specialist,advocate','C2'],
      ['genocideise','v','To make into genocide','mass murder,convert','C2'],
      ['genocideize','v','To make or become genocide','mass murder,transform','C2'],
      ['antigenocide','adj','Opposed to genocide','against,opposing','C2'],
      ['nongenocide','adj','Not involving genocide','without,lacking','C1'],
      ['pregenocide','n','Before genocide','preceding,prior','C2'],
      ['postgenocide','n','After genocide','following,subsequent','C2'],
      ['subgenocide','n','A subdivision of genocide','subset,branch','C2'],
      ['multigenocide','adj','Involving many genocides','multiple,several','C2'],
      ['intergenocide','adj','Between genocides','cross,between','C2'],
      ['reparations','n','Compensation for historical wrongs','compensation,restitution,amends','C1'],
      ['reparationsal','adj','Relating to reparations','compensation-related,pertaining to','C1'],
      ['reparationsic','adj','Of or relating to reparations','compensation-based,characteristic','C1'],
      ['reparationsous','adj','Full of reparations','compensation-filled,abundant','C2'],
      ['reparationsful','adj','Full of reparations','compensation-rich,abounding','C1'],
      ['reparationsless','adj','Without reparations','lacking,without','C1'],
      ['reparationsism','n','The ideology of reparations','compensation ideology,doctrine','C2'],
      ['reparationsist','n','A person focused on reparations','compensation specialist,advocate','C2'],
      ['reparationsise','v','To make into reparations','compensation,convert','C2'],
      ['reparationsize','v','To make or become reparations','compensation,transform','C2'],
      ['antireparations','adj','Opposed to reparations','against,opposing','C2'],
      ['nonreparations','adj','Not involving reparations','without,lacking','C1'],
      ['prereparations','n','Before reparations','preceding,prior','C2'],
      ['postreparations','n','After reparations','following,subsequent','C2'],
      ['subreparations','n','A subdivision of reparations','subset,branch','C2'],
      ['multireparations','adj','Involving many reparationss','multiple,several','C2'],
      ['interreparations','adj','Between reparationss','cross,between','C2'],
      ['archaeologyic','adj','Of or relating to archaeology','excavation-based,characteristic','B2'],
      ['archaeologyous','adj','Full of archaeology','excavation-filled,abundant','C1'],
      ['archaeologyful','adj','Full of archaeology','excavation-rich,abounding','B2'],
      ['archaeologyless','adj','Without archaeology','lacking,without','B2'],
      ['archaeologyism','n','The ideology of archaeology','excavation ideology,doctrine','C1'],
      ['archaeologyist','n','A person focused on archaeology','excavation specialist,advocate','C1'],
      ['archaeologyise','v','To make into archaeology','excavation,convert','C1'],
      ['archaeologyize','v','To make or become archaeology','excavation,transform','C1'],
      ['antiarchaeology','adj','Opposed to archaeology','against,opposing','C1'],
      ['nonarchaeology','adj','Not involving archaeology','without,lacking','B2'],
      ['prearchaeology','n','Before archaeology','preceding,prior','C1'],
      ['postarchaeology','n','After archaeology','following,subsequent','C1'],
      ['subarchaeology','n','A subdivision of archaeology','subset,branch','C1'],
      ['multiarchaeology','adj','Involving many archaeologys','multiple,several','C1'],
      ['interarchaeology','adj','Between archaeologys','cross,between','C1'],
      ['artifact','n','An object from a historical period','relic,antique,antiquity','B2'],
      ['artifactal','adj','Relating to artifact','relic-related,pertaining to','B2'],
      ['artifactic','adj','Of or relating to artifact','relic-based,characteristic','B2'],
      ['artifactous','adj','Full of artifact','relic-filled,abundant','C1'],
      ['artifactful','adj','Full of artifact','relic-rich,abounding','B2'],
      ['artifactless','adj','Without artifact','lacking,without','B2'],
      ['artifactism','n','The ideology of artifact','relic ideology,doctrine','C1'],
      ['artifactist','n','A person focused on artifact','relic specialist,advocate','C1'],
      ['artifactise','v','To make into artifact','relic,convert','C1'],
      ['artifactize','v','To make or become artifact','relic,transform','C1'],
      ['antiartifact','adj','Opposed to artifact','against,opposing','C1'],
      ['nonartifact','adj','Not involving artifact','without,lacking','B2'],
      ['preartifact','n','Before artifact','preceding,prior','C1'],
      ['postartifact','n','After artifact','following,subsequent','C1'],
      ['subartifact','n','A subdivision of artifact','subset,branch','C1'],
      ['multiartifact','adj','Involving many artifacts','multiple,several','C1'],
      ['interartifact','adj','Between artifacts','cross,between','C1'],
      ['manuscriptal','adj','Relating to manuscript','text-related,pertaining to','B2'],
      ['manuscriptic','adj','Of or relating to manuscript','text-based,characteristic','B2'],
      ['manuscriptous','adj','Full of manuscript','text-filled,abundant','C1'],
      ['manuscriptful','adj','Full of manuscript','text-rich,abounding','B2'],
      ['manuscriptless','adj','Without manuscript','lacking,without','B2'],
      ['manuscriptism','n','The ideology of manuscript','text ideology,doctrine','C1'],
      ['manuscriptist','n','A person focused on manuscript','text specialist,advocate','C1'],
      ['manuscriptise','v','To make into manuscript','text,convert','C1'],
      ['manuscriptize','v','To make or become manuscript','text,transform','C1'],
      ['antimanuscript','adj','Opposed to manuscript','against,opposing','C1'],
      ['nonmanuscript','adj','Not involving manuscript','without,lacking','B2'],
      ['premanuscript','n','Before manuscript','preceding,prior','C1'],
      ['postmanuscript','n','After manuscript','following,subsequent','C1'],
      ['submanuscript','n','A subdivision of manuscript','subset,branch','C1'],
      ['multimanuscript','adj','Involving many manuscripts','multiple,several','C1'],
      ['intermanuscript','adj','Between manuscripts','cross,between','C1'],
      ['epochic','adj','Of or relating to epoch','era-based,characteristic','C1'],
      ['epochous','adj','Full of epoch','era-filled,abundant','C2'],
      ['epochful','adj','Full of epoch','era-rich,abounding','C1'],
      ['epochless','adj','Without epoch','lacking,without','C1'],
      ['epochism','n','The ideology of epoch','era ideology,doctrine','C2'],
      ['epochist','n','A person focused on epoch','era specialist,advocate','C2'],
      ['epochise','v','To make into epoch','era,convert','C2'],
      ['epochize','v','To make or become epoch','era,transform','C2'],
      ['antiepoch','adj','Opposed to epoch','against,opposing','C2'],
      ['nonepoch','adj','Not involving epoch','without,lacking','C1'],
      ['preepoch','n','Before epoch','preceding,prior','C2'],
      ['postepoch','n','After epoch','following,subsequent','C2'],
      ['subepoch','n','A subdivision of epoch','subset,branch','C2'],
      ['multiepoch','adj','Involving many epochs','multiple,several','C2'],
      ['interepoch','adj','Between epochs','cross,between','C2'],
      ['zeitgeistic','adj','Of or relating to zeitgeist','spirit of the age-based,characteristic','C2'],
      ['zeitgeistous','adj','Full of zeitgeist','spirit of the age-filled,abundant','C2'],
      ['zeitgeistful','adj','Full of zeitgeist','spirit of the age-rich,abounding','C2'],
      ['zeitgeistless','adj','Without zeitgeist','lacking,without','C2'],
      ['zeitgeistism','n','The ideology of zeitgeist','spirit of the age ideology,doctrine','C2'],
      ['zeitgeistist','n','A person focused on zeitgeist','spirit of the age specialist,advocate','C2'],
      ['zeitgeistise','v','To make into zeitgeist','spirit of the age,convert','C2'],
      ['zeitgeistize','v','To make or become zeitgeist','spirit of the age,transform','C2'],
      ['antizeitgeist','adj','Opposed to zeitgeist','against,opposing','C2'],
      ['nonzeitgeist','adj','Not involving zeitgeist','without,lacking','C2'],
      ['prezeitgeist','n','Before zeitgeist','preceding,prior','C2'],
      ['postzeitgeist','n','After zeitgeist','following,subsequent','C2'],
      ['subzeitgeist','n','A subdivision of zeitgeist','subset,branch','C2'],
      ['multizeitgeist','adj','Involving many zeitgeists','multiple,several','C2'],
      ['interzeitgeist','adj','Between zeitgeists','cross,between','C2'],
      ['anachronismic','adj','Of or relating to anachronism','time error-based,characteristic','C1'],
      ['anachronismous','adj','Full of anachronism','time error-filled,abundant','C2'],
      ['anachronismful','adj','Full of anachronism','time error-rich,abounding','C1'],
      ['anachronismless','adj','Without anachronism','lacking,without','C1'],
      ['anachronismism','n','The ideology of anachronism','time error ideology,doctrine','C2'],
      ['anachronismist','n','A person focused on anachronism','time error specialist,advocate','C2'],
      ['anachronismise','v','To make into anachronism','time error,convert','C2'],
      ['anachronismize','v','To make or become anachronism','time error,transform','C2'],
      ['antianachronism','adj','Opposed to anachronism','against,opposing','C2'],
      ['nonanachronism','adj','Not involving anachronism','without,lacking','C1'],
      ['preanachronism','n','Before anachronism','preceding,prior','C2'],
      ['postanachronism','n','After anachronism','following,subsequent','C2'],
      ['subanachronism','n','A subdivision of anachronism','subset,branch','C2'],
      ['multianachronism','adj','Involving many anachronisms','multiple,several','C2'],
      ['interanachronism','adj','Between anachronisms','cross,between','C2'],
      ['historiographyic','adj','Of or relating to historiography','history writing-based,characteristic','C2'],
      ['historiographyous','adj','Full of historiography','history writing-filled,abundant','C2'],
      ['historiographyful','adj','Full of historiography','history writing-rich,abounding','C2'],
      ['historiographyless','adj','Without historiography','lacking,without','C2'],
      ['historiographyism','n','The ideology of historiography','history writing ideology,doctrine','C2'],
      ['historiographyist','n','A person focused on historiography','history writing specialist,advocate','C2'],
      ['historiographyise','v','To make into historiography','history writing,convert','C2'],
      ['historiographyize','v','To make or become historiography','history writing,transform','C2'],
      ['antihistoriography','adj','Opposed to historiography','against,opposing','C2'],
      ['nonhistoriography','adj','Not involving historiography','without,lacking','C2'],
      ['prehistoriography','n','Before historiography','preceding,prior','C2'],
      ['posthistoriography','n','After historiography','following,subsequent','C2'],
      ['subhistoriography','n','A subdivision of historiography','subset,branch','C2'],
      ['multihistoriography','adj','Involving many historiographys','multiple,several','C2'],
      ['interhistoriography','adj','Between historiographys','cross,between','C2'],
      ['revisionismic','adj','Of or relating to revisionism','reassessment-based,characteristic','C1'],
      ['revisionismous','adj','Full of revisionism','reassessment-filled,abundant','C2'],
      ['revisionismful','adj','Full of revisionism','reassessment-rich,abounding','C1'],
      ['revisionismless','adj','Without revisionism','lacking,without','C1'],
      ['revisionismism','n','The ideology of revisionism','reassessment ideology,doctrine','C2'],
      ['revisionismist','n','A person focused on revisionism','reassessment specialist,advocate','C2'],
      ['revisionismise','v','To make into revisionism','reassessment,convert','C2'],
      ['revisionismize','v','To make or become revisionism','reassessment,transform','C2'],
      ['antirevisionism','adj','Opposed to revisionism','against,opposing','C2'],
      ['nonrevisionism','adj','Not involving revisionism','without,lacking','C1'],
      ['prerevisionism','n','Before revisionism','preceding,prior','C2'],
      ['postrevisionism','n','After revisionism','following,subsequent','C2'],
      ['subrevisionism','n','A subdivision of revisionism','subset,branch','C2'],
      ['multirevisionism','adj','Involving many revisionisms','multiple,several','C2'],
      ['interrevisionism','adj','Between revisionisms','cross,between','C2'],
      ['antebellumity','n','The state of being antebellum','pre-war condition','C2'],
      ['inantebellum','adj','Not antebellum','not pre-war','C2'],
      ['nonantebellum','adj','Not antebellum','not pre-war','C2'],
      ['semiantebellum','adj','Partially antebellum','partly pre-war','C2'],
      ['overantebellum','adj','Excessively antebellum','too pre-war','C2'],
      ['ultraantebellum','adj','Extremely antebellum','very pre-war','C2'],
      ['posthumous','adj','Occurring after someones death','post-mortem,after death','C1'],
      ['posthumously','adv','In a posthumous manner','post-mortem way','C1'],
      ['posthumousness','n','The quality of being posthumous','post-mortem quality','C1'],
      ['posthumousity','n','The state of being posthumous','post-mortem condition','C2'],
      ['unposthumous','adj','Not posthumous','not post-mortem','C1'],
      ['inposthumous','adj','Not posthumous','not post-mortem','C2'],
      ['nonposthumous','adj','Not posthumous','not post-mortem','C1'],
      ['semiposthumous','adj','Partially posthumous','partly post-mortem','C2'],
      ['overposthumous','adj','Excessively posthumous','too post-mortem','C2'],
      ['ultraposthumous','adj','Extremely posthumous','very post-mortem','C2'],
      ['seminally','adv','In a seminal manner','groundbreaking way','C1'],
      ['seminalness','n','The quality of being seminal','groundbreaking quality','C1'],
      ['seminality','n','The state of being seminal','groundbreaking condition','C2'],
      ['unseminal','adj','Not seminal','not groundbreaking','C1'],
      ['inseminal','adj','Not seminal','not groundbreaking','C2'],
      ['nonseminal','adj','Not seminal','not groundbreaking','C1'],
      ['semiseminal','adj','Partially seminal','partly groundbreaking','C2'],
      ['overseminal','adj','Excessively seminal','too groundbreaking','C2'],
      ['ultraseminal','adj','Extremely seminal','very groundbreaking','C2'],
      ['iconoclasticly','adv','In a iconoclastic manner','rebellious way','C2'],
      ['iconoclasticness','n','The quality of being iconoclastic','rebellious quality','C2'],
      ['iconoclasticity','n','The state of being iconoclastic','rebellious condition','C2'],
      ['uniconoclastic','adj','Not iconoclastic','not rebellious','C2'],
      ['iniconoclastic','adj','Not iconoclastic','not rebellious','C2'],
      ['noniconoclastic','adj','Not iconoclastic','not rebellious','C2'],
      ['semiiconoclastic','adj','Partially iconoclastic','partly rebellious','C2'],
      ['overiconoclastic','adj','Excessively iconoclastic','too rebellious','C2'],
      ['ultraiconoclastic','adj','Extremely iconoclastic','very rebellious','C2'],
      ['atavisticly','adv','In a atavistic manner','primitive way','C2'],
      ['atavisticness','n','The quality of being atavistic','primitive quality','C2'],
      ['atavisticity','n','The state of being atavistic','primitive condition','C2'],
      ['unatavistic','adj','Not atavistic','not primitive','C2'],
      ['inatavistic','adj','Not atavistic','not primitive','C2'],
      ['nonatavistic','adj','Not atavistic','not primitive','C2'],
      ['semiatavistic','adj','Partially atavistic','partly primitive','C2'],
      ['overatavistic','adj','Excessively atavistic','too primitive','C2'],
      ['ultraatavistic','adj','Extremely atavistic','very primitive','C2'],
      ['suzerain','n','A state controlling another','overlord,sovereign,ruler','C2'],
      ['suzerainal','adj','Relating to suzerain','overlord-related,pertaining to','C2'],
      ['suzerainic','adj','Of or relating to suzerain','overlord-based,characteristic','C2'],
      ['suzerainous','adj','Full of suzerain','overlord-filled,abundant','C2'],
      ['suzerainful','adj','Full of suzerain','overlord-rich,abounding','C2'],
      ['suzerainless','adj','Without suzerain','lacking,without','C2'],
      ['suzerainism','n','The ideology of suzerain','overlord ideology,doctrine','C2'],
      ['suzerainist','n','A person focused on suzerain','overlord specialist,advocate','C2'],
      ['suzerainise','v','To make into suzerain','overlord,convert','C2'],
      ['suzerainize','v','To make or become suzerain','overlord,transform','C2'],
      ['antisuzerain','adj','Opposed to suzerain','against,opposing','C2'],
      ['nonsuzerain','adj','Not involving suzerain','without,lacking','C2'],
      ['presuzerain','n','Before suzerain','preceding,prior','C2'],
      ['postsuzerain','n','After suzerain','following,subsequent','C2'],
      ['subsuzerain','n','A subdivision of suzerain','subset,branch','C2'],
      ['multisuzerain','adj','Involving many suzerains','multiple,several','C2'],
      ['intersuzerain','adj','Between suzerains','cross,between','C2'],
      ['vassalal','adj','Relating to vassal','subject-related,pertaining to','C1'],
      ['vassalic','adj','Of or relating to vassal','subject-based,characteristic','C1'],
      ['vassalous','adj','Full of vassal','subject-filled,abundant','C2'],
      ['vassalful','adj','Full of vassal','subject-rich,abounding','C1'],
      ['vassalless','adj','Without vassal','lacking,without','C1'],
      ['vassalism','n','The ideology of vassal','subject ideology,doctrine','C2'],
      ['vassalist','n','A person focused on vassal','subject specialist,advocate','C2'],
      ['vassalise','v','To make into vassal','subject,convert','C2'],
      ['vassalize','v','To make or become vassal','subject,transform','C2'],
      ['antivassal','adj','Opposed to vassal','against,opposing','C2'],
      ['nonvassal','adj','Not involving vassal','without,lacking','C1'],
      ['prevassal','n','Before vassal','preceding,prior','C2'],
      ['postvassal','n','After vassal','following,subsequent','C2'],
      ['subvassal','n','A subdivision of vassal','subset,branch','C2'],
      ['multivassal','adj','Involving many vassals','multiple,several','C2'],
      ['intervassal','adj','Between vassals','cross,between','C2'],
      ['armisticeic','adj','Of or relating to armistice','ceasefire-based,characteristic','C1'],
      ['armisticeous','adj','Full of armistice','ceasefire-filled,abundant','C2'],
      ['armisticeful','adj','Full of armistice','ceasefire-rich,abounding','C1'],
      ['armisticeless','adj','Without armistice','lacking,without','C1'],
      ['armisticeism','n','The ideology of armistice','ceasefire ideology,doctrine','C2'],
      ['armisticeist','n','A person focused on armistice','ceasefire specialist,advocate','C2'],
      ['armisticeise','v','To make into armistice','ceasefire,convert','C2'],
      ['armisticeize','v','To make or become armistice','ceasefire,transform','C2'],
      ['antiarmistice','adj','Opposed to armistice','against,opposing','C2'],
      ['nonarmistice','adj','Not involving armistice','without,lacking','C1'],
      ['prearmistice','n','Before armistice','preceding,prior','C2'],
      ['postarmistice','n','After armistice','following,subsequent','C2'],
    ],
  },
  collocations: {}
};
