module.exports = {
  vocab: {
    economy: [
    ['stagflational','adj','Relating to stagflation','inflation stagnation-related','C1'],
    ['autarkyal','adj','Relating to autarky','self-reliance-related','C2'],
    ['mercantilismal','adj','Relating to mercantilism','trade protectionism-related','C2'],
    ['wageal','adj','Relating to wage','pay-related','A2'],
    ['loanal','adj','Relating to loan','credit-related','B1'],
    ['mortgageal','adj','Relating to mortgage','home loan-related','B1'],
    ['bankruptcyal','adj','Relating to bankruptcy','insolvency-related','B1'],
    ['commodityal','adj','Relating to commodity','goods-related','B2'],
    ['bondal','adj','Relating to bond','security-related','B2'],
    ['derivativesal','adj','Relating to derivatives','futures-related','C1'],
    ['oligopsonyal','adj','Relating to oligopsony','buyer monopoly-related','C2'],
    ['monopsonyal','adj','Relating to monopsony','single buyer-related','C2'],
    ['disinflational','adj','Relating to disinflation','inflation reduction-related','C1'],
    ['hyperinflational','adj','Relating to hyperinflation','runaway inflation-related','B2'],
    ['deflationarily','adv','In a deflationary manner','price-declining way','C1'],
    ['deflationaryness','n','The quality of being deflationary','price-declining quality','C2'],
    ['undeflationary','adj','Not deflationary','not price-declining','C1'],
    ['laissez-fairely','adv','In a laissez-faire manner','free market way','B2'],
    ['laissez-faireness','n','The quality of being laissez-faire','free market quality','C1'],
    ['unlaissez-faire','adj','Not laissez-faire','not free market','B2'],
    ['rentieral','adj','Relating to rentier','investor-related','C2'],
    ['beggar-thy-neighbourly','adv','In a beggar-thy-neighbour manner','competitive devaluation way','C2'],
    ['beggar-thy-neighbourness','n','The quality of being beggar-thy-neighbour','competitive devaluation quality','C2'],
    ['unbeggar-thy-neighbour','adj','Not beggar-thy-neighbour','not competitive devaluation','C2']
    ],
    society: [
    ['integration','n','The process of combining into a whole','inclusion,incorporation,assimilation','B2'],
    ['marginalisation','n','Treating a group as insignificant','exclusion,sidelining,disenfranchisement','B2'],
    ['anomie','n','Lack of social or moral norms','normlessness,social breakdown','C1'],
    ['homelessness','n','The state of having no permanent home','destitution,rough sleeping','B1'],
    ['activism','n','Vigorous action for political or social change','campaigning,advocacy,militancy','B2'],
    ['vigilantism','n','Law enforcement by unauthorised individuals','mob justice,self-appointed policing','C1'],
    ['misogyny','n','Hatred or prejudice against women','sexism,woman-hating,gender bias','B2'],
    ['gerontocracy','n','Government by elderly people','rule by elders,age-based leadership','C2'],
    ['intersectionality','n','Overlapping social identities creating disadvantage','multiple discrimination,identity overlap','C1'],
    ['social contract','n','An implicit agreement between citizens and state','civic agreement,governance pact','B2'],
    ['civil society','n','Non-governmental organisations and institutions','voluntary sector,public sphere','B2'],
    ['grassroots','adj','Organised by ordinary people at a local level','bottom-up,community-based,local','B2'],
    ['communityal','adj','Relating to community','neighbourhood-related','A2'],
    ['familyal','adj','Relating to family','household-related','A2'],
    ['friendal','adj','Relating to friend','companion-related','A2'],
    ['neighboural','adj','Relating to neighbour','resident-related','A2'],
    ['ruleal','adj','Relating to rule','law-related','A2'],
    ['equalityal','adj','Relating to equality','fairness-related','B1'],
    ['povertyal','adj','Relating to poverty','deprivation-related','B1'],
    ['diversityal','adj','Relating to diversity','variety-related','B1'],
    ['volunteeral','adj','Relating to volunteer','helper-related','B1'],
    ['welfareal','adj','Relating to welfare','well-being-related','B1'],
    ['charityal','adj','Relating to charity','nonprofit-related','B1'],
    ['discriminational','adj','Relating to discrimination','bias-related','B1'],
    ['integrational','adj','Relating to integration','inclusion-related','B2'],
    ['marginalisational','adj','Relating to marginalisation','exclusion-related','B2'],
    ['gentrificational','adj','Relating to gentrification','urban renewal-related','B2'],
    ['stratificational','adj','Relating to stratification','class division-related','B2'],
    ['demographicly','adv','In a demographic manner','population-based way','B2'],
    ['demographicness','n','The quality of being demographic','population-based quality','C1'],
    ['undemographic','adj','Not demographic','not population-based','B2'],
    ['egalitarianly','adv','In a egalitarian manner','equal way','B2'],
    ['egalitarianness','n','The quality of being egalitarian','equal quality','C1'],
    ['unegalitarian','adj','Not egalitarian','not equal','B2'],
    ['cohesional','adj','Relating to cohesion','togetherness-related','B2'],
    ['altruismal','adj','Relating to altruism','selflessness-related','C1'],
    ['hegemonyal','adj','Relating to hegemony','supremacy-related','C1'],
    ['anomieal','adj','Relating to anomie','normlessness-related','C1'],
    ['meritocracyal','adj','Relating to meritocracy','ability-based system-related','C1'],
    ['plutocracyal','adj','Relating to plutocracy','rule of the rich-related','C2'],
    ['oligarchyal','adj','Relating to oligarchy','ruling class-related','C2'],
    ['protestal','adj','Relating to protest','demonstration-related','B1'],
    ['petitional','adj','Relating to petition','appeal-related','B1'],
    ['refugeeal','adj','Relating to refugee','displaced person-related','B1'],
    ['homelessnessal','adj','Relating to homelessness','destitution-related','B1'],
    ['activismal','adj','Relating to activism','campaigning-related','B2'],
    ['philanthropyal','adj','Relating to philanthropy','beneficence-related','B2'],
    ['urbanisational','adj','Relating to urbanisation','city growth-related','B2'],
    ['stigmaal','adj','Relating to stigma','shame-related','B2'],
    ['nepotismal','adj','Relating to nepotism','favouritism-related','C1'],
    ['paternalismal','adj','Relating to paternalism','overprotection-related','C1'],
    ['vigilantismal','adj','Relating to vigilantism','mob justice-related','C1'],
    ['misogynyal','adj','Relating to misogyny','sexism-related','B2'],
    ['xenophobiaal','adj','Relating to xenophobia','anti-immigrant sentiment-related','B2'],
    ['gerontocracyal','adj','Relating to gerontocracy','rule by elders-related','C2'],
    ['intersectionalityal','adj','Relating to intersectionality','multiple discrimination-related','C1'],
    ['grassrootsly','adv','In a grassroots manner','bottom-up way','B2'],
    ['grassrootsness','n','The quality of being grassroots','bottom-up quality','C1'],
    ['ungrassroots','adj','Not grassroots','not bottom-up','B2'],
    ['disenfranchisation','n','The act or process of disenfranchising','exclude process,marginalise process,strip rights process','C1'],
    ['disenfranchiser','n','A person who disenfranchises','exclude person,marginalise person,strip rights person','C2'],
    ['disenfranchisable','adj','Able to be disenfranchised','exclude,possible','C2'],
    ['disenfranchising','n','The process of disenfranchising something','exclude activity','C1'],
    ['gentrifyation','n','The act or process of gentrifying','upgrade process,renew process,upscale process','C1'],
    ['gentrifyer','n','A person who gentrifys','upgrade person,renew person,upscale person','C2'],
    ['gentrifyable','adj','Able to be gentrifyd','upgrade,possible','C2'],
    ['gentrifying','n','The process of gentrifying something','upgrade activity','C1']
    ],
    culture: [
    ['assimilation','n','Absorbing one culture into another','integration,incorporation,blending','B2'],
    ['multiculturalism','n','The coexistence of diverse cultures','diversity,pluralism,inclusion','B2'],
    ['syncretism','n','The merging of different cultural practices','blending,fusion,amalgamation','C1'],
    ['iconoclasm','n','The rejection of established beliefs','tradition-breaking,rebellion','C2'],
    ['liminality','n','The state of being between cultural stages','transition,threshold,in-between','C2'],
    ['embroidery','n','Decorative needlework','stitching,needlepoint,cross-stitch','B1'],
    ['mythology','n','A collection of myths of a particular group','legend,folklore,saga','B1'],
    ['patrimonial','adj','Relating to inherited property or tradition','hereditary,ancestral,inherited','C1'],
    ['totem','n','A natural object serving as a cultural emblem','symbol,sacred object,icon','B2'],
    ['efflorescence','n','A period of cultural flowering','bloom,renaissance,golden age','C2'],
    ['simulacrum','n','An image or representation of something','copy,imitation,replica','C2'],
    ['kitsch','n','Art considered to be in poor taste','tackiness,vulgarity,bad taste','C1'],
    ['festivalal','adj','Relating to festival','holiday-related','A2'],
    ['musical','adj','Relating to music','melody-related','A2'],
    ['danceal','adj','Relating to dance','ballet-related','A2'],
    ['languageal','adj','Relating to language','tongue-related','A2'],
    ['religional','adj','Relating to religion','faith-related','A2'],
    ['artal','adj','Relating to art','artwork-related','A2'],
    ['costumeal','adj','Relating to costume','outfit-related','A2'],
    ['heritageal','adj','Relating to heritage','legacy-related','B1'],
    ['ritualal','adj','Relating to ritual','ceremony-related','B1'],
    ['folkloreal','adj','Relating to folklore','legend-related','B1'],
    ['cuisineal','adj','Relating to cuisine','food-related','B1'],
    ['tabooal','adj','Relating to taboo','ban-related','B1'],
    ['stereotypeal','adj','Relating to stereotype','generalisation-related','B1'],
    ['assimilational','adj','Relating to assimilation','integration-related','B2'],
    ['multiculturalismal','adj','Relating to multiculturalism','diversity-related','B2'],
    ['ethnocentrismal','adj','Relating to ethnocentrism','cultural bias-related','B2'],
    ['indigenously','adv','In a indigenous manner','native way','B2'],
    ['indigenousness','n','The quality of being indigenous','native quality','C1'],
    ['unindigenous','adj','Not indigenous','not native','B2'],
    ['vernacularal','adj','Relating to vernacular','dialect-related','B2'],
    ['diasporaal','adj','Relating to diaspora','scattering-related','C1'],
    ['acculturational','adj','Relating to acculturation','cultural exchange-related','C1'],
    ['syncretismal','adj','Relating to syncretism','blending-related','C1'],
    ['iconoclasmal','adj','Relating to iconoclasm','tradition-breaking-related','C2'],
    ['liminalityal','adj','Relating to liminality','transition-related','C2'],
    ['potteryal','adj','Relating to pottery','ceramics-related','A2'],
    ['embroideryal','adj','Relating to embroidery','stitching-related','B1'],
    ['calligraphyal','adj','Relating to calligraphy','penmanship-related','B1'],
    ['mythologyal','adj','Relating to mythology','legend-related','B1'],
    ['artefactal','adj','Relating to artefact','relic-related','B1'],
    ['mosaical','adj','Relating to mosaic','tile art-related','B2'],
    ['pilgrimageal','adj','Relating to pilgrimage','holy trip-related','B2'],
    ['patrimonially','adv','In a patrimonial manner','hereditary way','C1'],
    ['patrimonialness','n','The quality of being patrimonial','hereditary quality','C2'],
    ['unpatrimonial','adj','Not patrimonial','not hereditary','C1'],
    ['anthropologyal','adj','Relating to anthropology','cultural science-related','B2'],
    ['totemal','adj','Relating to totem','symbol-related','B2'],
    ['efflorescenceal','adj','Relating to efflorescence','bloom-related','C2'],
    ['bricolageal','adj','Relating to bricolage','assemblage-related','C2']
    ],
  },
  collocations: {
  }
};
