// Auto-generated vocab boost group 82
module.exports = {
  vocab: {
    employment: [
      ['nonapprenticeship','adj','Not involving apprenticeship','without,lacking','B2'],
      ['preapprenticeship','n','Before apprenticeship','preceding,prior','C1'],
      ['postapprenticeship','n','After apprenticeship','following,subsequent','C1'],
      ['subapprenticeship','n','A subdivision of apprenticeship','subset,branch','C1'],
      ['multiapprenticeship','adj','Involving many apprenticeships','multiple,several','C1'],
      ['interapprenticeship','adj','Between apprenticeships','cross,between','C1'],
      ['severanceic','adj','Of or relating to severance','termination pay-based,characteristic','C1'],
      ['severanceous','adj','Full of severance','termination pay-filled,abundant','C2'],
      ['severanceful','adj','Full of severance','termination pay-rich,abounding','C1'],
      ['severanceless','adj','Without severance','lacking,without','C1'],
      ['severanceism','n','The ideology of severance','termination pay ideology,doctrine','C2'],
      ['severanceist','n','A person focused on severance','termination pay specialist,advocate','C2'],
      ['severanceise','v','To make into severance','termination pay,convert','C2'],
      ['severanceize','v','To make or become severance','termination pay,transform','C2'],
      ['antiseverance','adj','Opposed to severance','against,opposing','C2'],
      ['nonseverance','adj','Not involving severance','without,lacking','C1'],
      ['preseverance','n','Before severance','preceding,prior','C2'],
      ['postseverance','n','After severance','following,subsequent','C2'],
      ['subseverance','n','A subdivision of severance','subset,branch','C2'],
      ['multiseverance','adj','Involving many severances','multiple,several','C2'],
      ['interseverance','adj','Between severances','cross,between','C2'],
      ['gratuity','n','A monetary gift for services','tip,bonus,reward','B2'],
      ['gratuityal','adj','Relating to gratuity','tip-related,pertaining to','B2'],
      ['gratuityic','adj','Of or relating to gratuity','tip-based,characteristic','B2'],
      ['gratuityous','adj','Full of gratuity','tip-filled,abundant','C1'],
      ['gratuityful','adj','Full of gratuity','tip-rich,abounding','B2'],
      ['gratuityless','adj','Without gratuity','lacking,without','B2'],
      ['gratuityism','n','The ideology of gratuity','tip ideology,doctrine','C1'],
      ['gratuityist','n','A person focused on gratuity','tip specialist,advocate','C1'],
      ['gratuityise','v','To make into gratuity','tip,convert','C1'],
      ['gratuityize','v','To make or become gratuity','tip,transform','C1'],
      ['antigratuity','adj','Opposed to gratuity','against,opposing','C1'],
      ['nongratuity','adj','Not involving gratuity','without,lacking','B2'],
      ['pregratuity','n','Before gratuity','preceding,prior','C1'],
      ['postgratuity','n','After gratuity','following,subsequent','C1'],
      ['subgratuity','n','A subdivision of gratuity','subset,branch','C1'],
      ['multigratuity','adj','Involving many gratuitys','multiple,several','C1'],
      ['intergratuity','adj','Between gratuitys','cross,between','C1'],
      ['sabbaticalic','adj','Of or relating to sabbatical','leave of absence-based,characteristic','C1'],
      ['sabbaticalous','adj','Full of sabbatical','leave of absence-filled,abundant','C2'],
      ['sabbaticalful','adj','Full of sabbatical','leave of absence-rich,abounding','C1'],
      ['sabbaticalless','adj','Without sabbatical','lacking,without','C1'],
      ['sabbaticalism','n','The ideology of sabbatical','leave of absence ideology,doctrine','C2'],
      ['sabbaticalist','n','A person focused on sabbatical','leave of absence specialist,advocate','C2'],
      ['sabbaticalise','v','To make into sabbatical','leave of absence,convert','C2'],
      ['sabbaticalize','v','To make or become sabbatical','leave of absence,transform','C2'],
      ['antisabbatical','adj','Opposed to sabbatical','against,opposing','C2'],
      ['nonsabbatical','adj','Not involving sabbatical','without,lacking','C1'],
      ['presabbatical','n','Before sabbatical','preceding,prior','C2'],
      ['postsabbatical','n','After sabbatical','following,subsequent','C2'],
      ['subsabbatical','n','A subdivision of sabbatical','subset,branch','C2'],
      ['multisabbatical','adj','Involving many sabbaticals','multiple,several','C2'],
      ['intersabbatical','adj','Between sabbaticals','cross,between','C2'],
      ['glass ceilingal','adj','Relating to glass ceiling','career barrier-related,pertaining to','B2'],
      ['glass ceilingic','adj','Of or relating to glass ceiling','career barrier-based,characteristic','B2'],
      ['glass ceilingous','adj','Full of glass ceiling','career barrier-filled,abundant','C1'],
      ['glass ceilingful','adj','Full of glass ceiling','career barrier-rich,abounding','B2'],
      ['glass ceilingless','adj','Without glass ceiling','lacking,without','B2'],
      ['glass ceilingism','n','The ideology of glass ceiling','career barrier ideology,doctrine','C1'],
      ['glass ceilingist','n','A person focused on glass ceiling','career barrier specialist,advocate','C1'],
      ['glass ceilingise','v','To make into glass ceiling','career barrier,convert','C1'],
      ['glass ceilingize','v','To make or become glass ceiling','career barrier,transform','C1'],
      ['antiglass ceiling','adj','Opposed to glass ceiling','against,opposing','C1'],
      ['nonglass ceiling','adj','Not involving glass ceiling','without,lacking','B2'],
      ['preglass ceiling','n','Before glass ceiling','preceding,prior','C1'],
      ['postglass ceiling','n','After glass ceiling','following,subsequent','C1'],
      ['subglass ceiling','n','A subdivision of glass ceiling','subset,branch','C1'],
      ['multiglass ceiling','adj','Involving many glass ceilings','multiple,several','C1'],
      ['interglass ceiling','adj','Between glass ceilings','cross,between','C1'],
      ['gig economyal','adj','Relating to gig economy','freelance market-related,pertaining to','B2'],
      ['gig economyic','adj','Of or relating to gig economy','freelance market-based,characteristic','B2'],
      ['gig economyous','adj','Full of gig economy','freelance market-filled,abundant','C1'],
      ['gig economyful','adj','Full of gig economy','freelance market-rich,abounding','B2'],
      ['gig economyless','adj','Without gig economy','lacking,without','B2'],
      ['gig economyism','n','The ideology of gig economy','freelance market ideology,doctrine','C1'],
      ['gig economyist','n','A person focused on gig economy','freelance market specialist,advocate','C1'],
      ['gig economyise','v','To make into gig economy','freelance market,convert','C1'],
      ['gig economyize','v','To make or become gig economy','freelance market,transform','C1'],
      ['antigig economy','adj','Opposed to gig economy','against,opposing','C1'],
      ['nongig economy','adj','Not involving gig economy','without,lacking','B2'],
      ['pregig economy','n','Before gig economy','preceding,prior','C1'],
      ['postgig economy','n','After gig economy','following,subsequent','C1'],
      ['subgig economy','n','A subdivision of gig economy','subset,branch','C1'],
      ['multigig economy','adj','Involving many gig economys','multiple,several','C1'],
      ['intergig economy','adj','Between gig economys','cross,between','C1'],
      ['underemployment','n','Having a job below ones qualifications','partial employment,inadequate work','B2'],
      ['underemploymental','adj','Relating to underemployment','partial employment-related,pertaining to','B2'],
      ['underemploymentic','adj','Of or relating to underemployment','partial employment-based,characteristic','B2'],
      ['underemploymentous','adj','Full of underemployment','partial employment-filled,abundant','C1'],
      ['underemploymentful','adj','Full of underemployment','partial employment-rich,abounding','B2'],
      ['underemploymentless','adj','Without underemployment','lacking,without','B2'],
      ['underemploymentism','n','The ideology of underemployment','partial employment ideology,doctrine','C1'],
      ['underemploymentist','n','A person focused on underemployment','partial employment specialist,advocate','C1'],
      ['underemploymentise','v','To make into underemployment','partial employment,convert','C1'],
      ['underemploymentize','v','To make or become underemployment','partial employment,transform','C1'],
      ['antiunderemployment','adj','Opposed to underemployment','against,opposing','C1'],
      ['nonunderemployment','adj','Not involving underemployment','without,lacking','B2'],
      ['preunderemployment','n','Before underemployment','preceding,prior','C1'],
      ['postunderemployment','n','After underemployment','following,subsequent','C1'],
      ['subunderemployment','n','A subdivision of underemployment','subset,branch','C1'],
      ['multiunderemployment','adj','Involving many underemployments','multiple,several','C1'],
      ['interunderemployment','adj','Between underemployments','cross,between','C1'],
      ['white-collarity','n','The state of being white-collar','professional condition','C1'],
      ['inwhite-collar','adj','Not white-collar','not professional','C1'],
      ['nonwhite-collar','adj','Not white-collar','not professional','B2'],
      ['semiwhite-collar','adj','Partially white-collar','partly professional','C1'],
      ['overwhite-collar','adj','Excessively white-collar','too professional','C1'],
      ['ultrawhite-collar','adj','Extremely white-collar','very professional','C1'],
      ['blue-collarly','adv','In a blue-collar manner','manual way','B2'],
      ['blue-collarness','n','The quality of being blue-collar','manual quality','B2'],
      ['blue-collarity','n','The state of being blue-collar','manual condition','C1'],
      ['unblue-collar','adj','Not blue-collar','not manual','B2'],
      ['inblue-collar','adj','Not blue-collar','not manual','C1'],
      ['nonblue-collar','adj','Not blue-collar','not manual','B2'],
      ['semiblue-collar','adj','Partially blue-collar','partly manual','C1'],
      ['overblue-collar','adj','Excessively blue-collar','too manual','C1'],
      ['ultrablue-collar','adj','Extremely blue-collar','very manual','C1'],
      ['headhuntation','n','The act of headhunting','recruit process','B2'],
      ['headhuntment','n','The result of headhunting','recruit outcome','B2'],
      ['headhuntance','n','The state of headhunting','recruit state','B2'],
      ['headhuntence','n','The quality of headhunting','recruit quality','B2'],
      ['headhuntal','n','An act of headhunting','recruit event','C1'],
      ['headhuntor','n','One who headhunts','recruit agent','B2'],
      ['headhuntee','n','One who is headhuntd','recruit recipient','C1'],
      ['headhuntable','adj','Capable of being headhuntd','recruit,possible','C1'],
      ['headhuntible','adj','Able to be headhuntd','recruit,feasible','C1'],
      ['headhuntive','adj','Tending to headhunt','recruit,active','B2'],
      ['headhunting','adj','Currently headhunting','recruit,ongoing','B2'],
      ['headhunted','adj','Having been headhuntd','recruit,completed','B2'],
      ['reheadhunt','v','To headhunt again','recruit again,repeat','B2'],
      ['unheadhunt','v','To reverse headhunting','reverse,undo','C1'],
      ['overheadhunt','v','To headhunt excessively','excess,too much','C1'],
      ['underheadhunt','v','To headhunt insufficiently','insufficient,inadequate','C1'],
      ['misheadhunt','v','To headhunt incorrectly','wrongly,incorrectly','C1'],
      ['preheadhunt','v','To headhunt beforehand','before,in advance','C1'],
      ['coheadhunt','v','To headhunt together','jointly,together','C1'],
      ['reheadhuntation','n','The act of headhunting again','re-recruit','C1'],
      ['overheadhuntation','n','Excessive headhunting','excess recruit','C1'],
      ['moonlightation','n','The act of moonlighting','double-job process','C1'],
      ['moonlightment','n','The result of moonlighting','double-job outcome','C1'],
      ['moonlightance','n','The state of moonlighting','double-job state','C1'],
      ['moonlightence','n','The quality of moonlighting','double-job quality','C1'],
      ['moonlightal','n','An act of moonlighting','double-job event','C2'],
      ['moonlighter','n','One who moonlights','double-job person','C1'],
      ['moonlightor','n','One who moonlights','double-job agent','C1'],
      ['moonlightee','n','One who is moonlightd','double-job recipient','C2'],
      ['moonlightable','adj','Capable of being moonlightd','double-job,possible','C2'],
      ['moonlightible','adj','Able to be moonlightd','double-job,feasible','C2'],
      ['moonlightive','adj','Tending to moonlight','double-job,active','C1'],
      ['moonlighted','adj','Having been moonlightd','double-job,completed','C1'],
      ['remoonlight','v','To moonlight again','double-job again,repeat','C1'],
      ['unmoonlight','v','To reverse moonlighting','reverse,undo','C2'],
      ['overmoonlight','v','To moonlight excessively','excess,too much','C2'],
      ['undermoonlight','v','To moonlight insufficiently','insufficient,inadequate','C2'],
      ['mismoonlight','v','To moonlight incorrectly','wrongly,incorrectly','C2'],
      ['premoonlight','v','To moonlight beforehand','before,in advance','C2'],
      ['comoonlight','v','To moonlight together','jointly,together','C2'],
      ['remoonlightation','n','The act of moonlighting again','re-double-job','C2'],
      ['overmoonlightation','n','Excessive moonlighting','excess double-job','C2'],
      ['furloughation','n','The act of furloughing','suspend process','C1'],
      ['furloughment','n','The result of furloughing','suspend outcome','C1'],
      ['furloughance','n','The state of furloughing','suspend state','C1'],
      ['furloughence','n','The quality of furloughing','suspend quality','C1'],
      ['furlougher','n','One who furloughs','suspend person','C1'],
      ['furloughor','n','One who furloughs','suspend agent','C1'],
      ['furloughee','n','One who is furloughd','suspend recipient','C2'],
      ['furloughable','adj','Capable of being furloughd','suspend,possible','C2'],
      ['furloughible','adj','Able to be furloughd','suspend,feasible','C2'],
      ['furloughive','adj','Tending to furlough','suspend,active','C1'],
      ['furloughing','adj','Currently furloughing','suspend,ongoing','C1'],
      ['furloughed','adj','Having been furloughd','suspend,completed','C1'],
      ['refurlough','v','To furlough again','suspend again,repeat','C1'],
      ['unfurlough','v','To reverse furloughing','reverse,undo','C2'],
      ['overfurlough','v','To furlough excessively','excess,too much','C2'],
      ['underfurlough','v','To furlough insufficiently','insufficient,inadequate','C2'],
      ['misfurlough','v','To furlough incorrectly','wrongly,incorrectly','C2'],
      ['prefurlough','v','To furlough beforehand','before,in advance','C2'],
      ['cofurlough','v','To furlough together','jointly,together','C2'],
      ['refurloughation','n','The act of furloughing again','re-suspend','C2'],
      ['overfurloughation','n','Excessive furloughing','excess suspend','C2'],
      ['telecommutment','n','The result of telecommuting','remote work outcome','B2'],
      ['telecommutance','n','The state of telecommuting','remote work state','B2'],
      ['telecommutence','n','The quality of telecommuting','remote work quality','B2'],
      ['telecommutal','n','An act of telecommuting','remote work event','C1'],
      ['telecommutor','n','One who telecommutes','remote work agent','B2'],
      ['telecommutee','n','One who is telecommuted','remote work recipient','C1'],
      ['telecommutible','adj','Able to be telecommuted','remote work,feasible','C1'],
      ['telecommutive','adj','Tending to telecommute','remote work,active','B2'],
      ['telecommuted','adj','Having been telecommuted','remote work,completed','B2'],
      ['retelecommute','v','To telecommute again','remote work again,repeat','B2'],
      ['untelecommute','v','To reverse telecommuting','reverse,undo','C1'],
      ['overtelecommute','v','To telecommute excessively','excess,too much','C1'],
      ['undertelecommute','v','To telecommute insufficiently','insufficient,inadequate','C1'],
      ['mistelecommute','v','To telecommute incorrectly','wrongly,incorrectly','C1'],
      ['pretelecommute','v','To telecommute beforehand','before,in advance','C1'],
      ['cotelecommute','v','To telecommute together','jointly,together','C1'],
      ['retelecommutation','n','The act of telecommuting again','re-remote work','C1'],
      ['overtelecommutation','n','Excessive telecommuting','excess remote work','C1'],
      ['burnoutic','adj','Of or relating to burnout','exhaustion-based,characteristic','B2'],
      ['burnoutous','adj','Full of burnout','exhaustion-filled,abundant','C1'],
      ['burnoutful','adj','Full of burnout','exhaustion-rich,abounding','B2'],
      ['burnoutless','adj','Without burnout','lacking,without','B2'],
      ['burnoutism','n','The ideology of burnout','exhaustion ideology,doctrine','C1'],
      ['burnoutist','n','A person focused on burnout','exhaustion specialist,advocate','C1'],
      ['burnoutise','v','To make into burnout','exhaustion,convert','C1'],
      ['burnoutize','v','To make or become burnout','exhaustion,transform','C1'],
      ['antiburnout','adj','Opposed to burnout','against,opposing','C1'],
      ['nonburnout','adj','Not involving burnout','without,lacking','B2'],
      ['preburnout','n','Before burnout','preceding,prior','C1'],
      ['postburnout','n','After burnout','following,subsequent','C1'],
      ['subburnout','n','A subdivision of burnout','subset,branch','C1'],
      ['multiburnout','adj','Involving many burnouts','multiple,several','C1'],
      ['interburnout','adj','Between burnouts','cross,between','C1'],
      ['mentorship','n','Guidance from an experienced person','coaching,guidance,tutoring','B2'],
      ['mentorshipal','adj','Relating to mentorship','coaching-related,pertaining to','B2'],
      ['mentorshipic','adj','Of or relating to mentorship','coaching-based,characteristic','B2'],
      ['mentorshipous','adj','Full of mentorship','coaching-filled,abundant','C1'],
      ['mentorshipful','adj','Full of mentorship','coaching-rich,abounding','B2'],
      ['mentorshipless','adj','Without mentorship','lacking,without','B2'],
      ['mentorshipism','n','The ideology of mentorship','coaching ideology,doctrine','C1'],
      ['mentorshipist','n','A person focused on mentorship','coaching specialist,advocate','C1'],
      ['mentorshipise','v','To make into mentorship','coaching,convert','C1'],
      ['mentorshipize','v','To make or become mentorship','coaching,transform','C1'],
      ['antimentorship','adj','Opposed to mentorship','against,opposing','C1'],
      ['nonmentorship','adj','Not involving mentorship','without,lacking','B2'],
      ['prementorship','n','Before mentorship','preceding,prior','C1'],
      ['postmentorship','n','After mentorship','following,subsequent','C1'],
      ['submentorship','n','A subdivision of mentorship','subset,branch','C1'],
      ['multimentorship','adj','Involving many mentorships','multiple,several','C1'],
      ['intermentorship','adj','Between mentorships','cross,between','C1'],
      ['prerequisiteal','adj','Relating to prerequisite','requirement-related,pertaining to','B2'],
      ['prerequisiteic','adj','Of or relating to prerequisite','requirement-based,characteristic','B2'],
      ['prerequisiteous','adj','Full of prerequisite','requirement-filled,abundant','C1'],
      ['prerequisiteful','adj','Full of prerequisite','requirement-rich,abounding','B2'],
      ['prerequisiteless','adj','Without prerequisite','lacking,without','B2'],
      ['prerequisiteism','n','The ideology of prerequisite','requirement ideology,doctrine','C1'],
      ['prerequisiteist','n','A person focused on prerequisite','requirement specialist,advocate','C1'],
      ['prerequisiteise','v','To make into prerequisite','requirement,convert','C1'],
      ['prerequisiteize','v','To make or become prerequisite','requirement,transform','C1'],
      ['antiprerequisite','adj','Opposed to prerequisite','against,opposing','C1'],
      ['nonprerequisite','adj','Not involving prerequisite','without,lacking','B2'],
      ['preprerequisite','n','Before prerequisite','preceding,prior','C1'],
      ['postprerequisite','n','After prerequisite','following,subsequent','C1'],
      ['subprerequisite','n','A subdivision of prerequisite','subset,branch','C1'],
      ['multiprerequisite','adj','Involving many prerequisites','multiple,several','C1'],
      ['interprerequisite','adj','Between prerequisites','cross,between','C1'],
      ['remunerational','adj','Relating to remuneration','compensation-related,pertaining to','B2'],
      ['remunerationic','adj','Of or relating to remuneration','compensation-based,characteristic','B2'],
      ['remunerationous','adj','Full of remuneration','compensation-filled,abundant','C1'],
      ['remunerationful','adj','Full of remuneration','compensation-rich,abounding','B2'],
    ],
  },
  collocations: {}
};
