module.exports = {
  vocab: {
    sports: [
    ['practicer','n','A person who practices','train person,drill person,exercise person','B1'],
    ['practicable','adj','Able to be practiced','train,possible','B1'],
    ['practicing','n','The process of practicing something','train activity','A2'],
    ['coachal','adj','Relating to coach','trainer-related','A2'],
    ['tournamental','adj','Relating to tournament','championship-related','B1'],
    ['athleteal','adj','Relating to athlete','sportsperson-related','B1'],
    ['refereeal','adj','Relating to referee','umpire-related','B1'],
    ['staminaal','adj','Relating to stamina','endurance-related','B1'],
    ['opponental','adj','Relating to opponent','rival-related','B1'],
    ['tactical','adj','Relating to tactic','strategy-related','B1'],
    ['sportsmanshipal','adj','Relating to sportsmanship','fair play-related','B2'],
    ['dopingal','adj','Relating to doping','drug use-related','B2'],
    ['physiologyal','adj','Relating to physiology','body science-related','B2'],
    ['biomechanicsal','adj','Relating to biomechanics','motion science-related','B2'],
    ['periodisational','adj','Relating to periodisation','training phases-related','C1'],
    ['proprioceptional','adj','Relating to proprioception','body sense-related','C1'],
    ['plyometricsal','adj','Relating to plyometrics','jump training-related','C1'],
    ['ergogenicly','adv','In a ergogenic manner','performance-boosting way','C2'],
    ['ergogenicness','n','The quality of being ergogenic','performance-boosting quality','C2'],
    ['unergogenic','adj','Not ergogenic','not performance-boosting','C2'],
    ['trophyal','adj','Relating to trophy','cup-related','A2'],
    ['stadiumal','adj','Relating to stadium','arena-related','A2'],
    ['marathonal','adj','Relating to marathon','endurance race-related','B1'],
    ['sprintal','adj','Relating to sprint','dash-related','B1'],
    ['penaltyal','adj','Relating to penalty','foul-related','B1'],
    ['underdogal','adj','Relating to underdog','outsider-related','B1'],
    ['fixtureal','adj','Relating to fixture','match-related','B2'],
    ['relegational','adj','Relating to relegation','demotion-related','B2'],
    ['concussional','adj','Relating to concussion','head injury-related','B2'],
    ['calisthenicsal','adj','Relating to calisthenics','bodyweight training-related','B2'],
    ['ergometeral','adj','Relating to ergometer','rowing machine-related','C1'],
    ['anaerobicly','adv','In a anaerobic manner','oxygen-free way','C1'],
    ['anaerobicness','n','The quality of being anaerobic','oxygen-free quality','C2'],
    ['unanaerobic','adj','Not anaerobic','not oxygen-free','C1'],
    ['isometricly','adv','In a isometric manner','static way','C1'],
    ['isometricness','n','The quality of being isometric','static quality','C2'],
    ['unisometric','adj','Not isometric','not static','C1'],
    ['proprioceptively','adv','In a proprioceptive manner','balance-sensing way','C1'],
    ['proprioceptiveness','n','The quality of being proprioceptive','balance-sensing quality','C2'],
    ['unproprioceptive','adj','Not proprioceptive','not balance-sensing','C1'],
    ['velodromeal','adj','Relating to velodrome','cycling arena-related','C1'],
    ['parkoural','adj','Relating to parkour','free running-related','B2'],
    ['boulderingal','adj','Relating to bouldering','rock climbing-related','B2'],
    ['decathlonal','adj','Relating to decathlon','multi-event-related','B2'],
    ['heptathlonal','adj','Relating to heptathlon','seven-event contest-related','C1'],
    ['pelotonal','adj','Relating to peloton','pack-related','C1']
    ],
    food: [
    ['molecular gastronomy','n','Scientific techniques applied to cooking','food science,culinary innovation','C1'],
    ['locavore','n','A person who eats locally produced food','local eater,food localist','C1'],
    ['orthorexia','n','An obsession with eating healthy food','health food fixation,clean eating obsession','C2'],
    ['gluten','n','A protein found in wheat and grains','wheat protein,bread protein','B1'],
    ['pâtisserie','n','A shop selling pastries and cakes','bakery,cake shop,confectionery','C1'],
    ['gastrique','n','A sweet and sour sauce base','caramel vinegar,reduction sauce','C2'],
    ['mise en place','n','Preparation of ingredients before cooking','prep work,kitchen setup','C1'],
    ['caramelise','v','To cook sugar until golden brown','brown,toast,glaze','B2'],
    ['confit','n','Food cooked slowly in fat or sugar','preserved,slow-cooked,fat-poached','C1'],
    ['emulsify','v','To combine two liquids that normally separate','blend,mix,homogenise','C1'],
    ['cookation','n','The act or process of cooking','make process,prepare process,bake process','A2'],
    ['cooker','n','A person who cooks','make person,prepare person,bake person','B1'],
    ['cookable','adj','Able to be cookd','make,possible','B1'],
    ['cooking','n','The process of cooking something','make activity','A2'],
    ['mealal','adj','Relating to meal','dinner-related','A2'],
    ['fruital','adj','Relating to fruit','produce-related','A2'],
    ['vegetableal','adj','Relating to vegetable','green-related','A2'],
    ['recipeal','adj','Relating to recipe','method-related','A2'],
    ['tasteal','adj','Relating to taste','flavour-related','A2'],
    ['kitchenal','adj','Relating to kitchen','cookhouse-related','A2'],
    ['ingrediental','adj','Relating to ingredient','element-related','B1'],
    ['organicly','adv','In a organic manner','natural way','B1'],
    ['organicness','n','The quality of being organic','natural quality','B2'],
    ['unorganic','adj','Not organic','not natural','B1'],
    ['portional','adj','Relating to portion','serving-related','B1'],
    ['additiveal','adj','Relating to additive','preservative-related','B1'],
    ['fermentational','adj','Relating to fermentation','brewing-related','B2'],
    ['gastronomyal','adj','Relating to gastronomy','culinary arts-related','B2'],
    ['artisanally','adv','In a artisanal manner','handcrafted way','B2'],
    ['artisanalness','n','The quality of being artisanal','handcrafted quality','C1'],
    ['unartisanal','adj','Not artisanal','not handcrafted','B2'],
    ['umamial','adj','Relating to umami','fifth taste-related','B2'],
    ['terroiral','adj','Relating to terroir','land influence-related','C1'],
    ['locavoreal','adj','Relating to locavore','local eater-related','C1'],
    ['orthorexiaal','adj','Relating to orthorexia','health food fixation-related','C2'],
    ['spiceal','adj','Relating to spice','seasoning-related','A2'],
    ['dessertal','adj','Relating to dessert','pudding-related','A2'],
    ['roastation','n','The act or process of roasting','bake process,grill process,broil process','A2'],
    ['roaster','n','A person who roasts','bake person,grill person,broil person','B1'],
    ['roastable','adj','Able to be roastd','bake,possible','B1'],
    ['roasting','n','The process of roasting something','bake activity','A2'],
    ['appetiseral','adj','Relating to appetiser','starter-related','B1'],
    ['marinatation','n','The act or process of marinating','season process,infuse process,steep process','B1'],
    ['marinater','n','A person who marinates','season person,infuse person,steep person','B2'],
    ['marinatable','adj','Able to be marinated','season,possible','B2'],
    ['marinating','n','The process of marinating something','season activity','B1'],
    ['glutenal','adj','Relating to gluten','wheat protein-related','B1'],
    ['delicacyal','adj','Relating to delicacy','treat-related','B2'],
    ['sommelieral','adj','Relating to sommelier','wine steward-related','C1'],
    ['gastriqueal','adj','Relating to gastrique','caramel vinegar-related','C2'],
    ['blanchation','n','The act or process of blanching','parboil process,scald process,pre-cook process','B2'],
    ['blancher','n','A person who blanchs','parboil person,scald person,pre-cook person','C1'],
    ['blanchable','adj','Able to be blanchd','parboil,possible','C1'],
    ['blanching','n','The process of blanching something','parboil activity','B2'],
    ['juliennation','n','The act or process of julienning','shred process,slice thinly process,cut matchstick process','B2'],
    ['julienner','n','A person who juliennes','shred person,slice thinly person,cut matchstick person','C1'],
    ['juliennable','adj','Able to be julienned','shred,possible','C1'],
    ['julienning','n','The process of julienning something','shred activity','B2'],
    ['caramelisation','n','The act or process of caramelising','brown process,toast process,glaze process','B2'],
    ['carameliser','n','A person who caramelises','brown person,toast person,glaze person','C1'],
    ['caramelisable','adj','Able to be caramelised','brown,possible','C1'],
    ['caramelising','n','The process of caramelising something','brown activity','B2'],
    ['deglazation','n','The act or process of deglazing','loosen process,dissolve process,wash process','C1'],
    ['deglazer','n','A person who deglazes','loosen person,dissolve person,wash person','C2'],
    ['deglazable','adj','Able to be deglazed','loosen,possible','C2'],
    ['deglazing','n','The process of deglazing something','loosen activity','C1'],
    ['confital','adj','Relating to confit','preserved-related','C1'],
    ['emulsifyation','n','The act or process of emulsifying','blend process,mix process,homogenise process','C1'],
    ['emulsifyer','n','A person who emulsifys','blend person,mix person,homogenise person','C2'],
    ['emulsifyable','adj','Able to be emulsifyd','blend,possible','C2'],
    ['emulsifying','n','The process of emulsifying something','blend activity','C1']
    ],
    housing: [
    ['flat','n','A set of rooms on one floor','apartment,unit,dwelling','A2'],
    ['brownfield','n','Previously developed land available for reuse','redevelopment site,former industrial land','C1'],
    ['cohousing','n','A community with shared facilities','communal living,cooperative housing','C1'],
    ['geodesic','adj','Relating to dome-shaped structures','dome,spherical,Buckminster Fuller','C2'],
    ['cellar','n','An underground room beneath a building','basement,vault,underground','B1'],
    ['retrofitting','n','Adding new features to existing buildings','upgrading,modernising,improving','B2'],
    ['modular housing','n','Homes built from pre-made sections','prefab,factory-built,kit homes','B2'],
    ['passive house','n','A building with ultra-low energy use','energy-neutral home,zero-energy design','C1'],
    ['council estate','n','A group of public housing buildings','social housing,housing project','B2'],
    ['gazumping','n','Accepting a higher offer after agreeing a sale','outbidding,price raising','C2'],
    ['conveyancing','n','The legal transfer of property ownership','property law,title transfer','C1'],
    ['cladding','n','External covering applied to a building','facing,siding,exterior panel','B2'],
    ['dormer','n','A window projecting from a roof','roof window,skylight,attic window','C1'],
    ['terraced','adj','In a row of joined houses','row house,townhouse,linked','B1'],
    ['maisonette','n','A two-storey apartment','duplex,split-level flat','C1'],
    ['houseal','adj','Relating to house','home-related','A2'],
    ['flatal','adj','Relating to flat','apartment-related','A2'],
    ['roomal','adj','Relating to room','chamber-related','A2'],
    ['rentation','n','The act or process of renting','lease process,hire process,let process','A2'],
    ['renter','n','A person who rents','lease person,hire person,let person','B1'],
    ['rentable','adj','Able to be rentd','lease,possible','B1'],
    ['renting','n','The process of renting something','lease activity','A2'],
    ['buildation','n','The act or process of building','construct process,erect process,assemble process','A2'],
    ['builder','n','A person who builds','construct person,erect person,assemble person','B1'],
    ['buildable','adj','Able to be buildd','construct,possible','B1']
    ],
  },
  collocations: {
  }
};
