// Auto-generated vocab boost group 58
module.exports = {
  vocab: {
    crime: [
      ['misdemeanour','n','A minor criminal offence','minor crime,infraction,petty offence','C1'],
      ['misdemeanoural','adj','Relating to misdemeanour','minor crime-related,pertaining to','C1'],
      ['misdemeanouric','adj','Of or relating to misdemeanour','minor crime-based,characteristic','C1'],
      ['misdemeanourous','adj','Full of misdemeanour','minor crime-filled,abundant','C2'],
      ['misdemeanourful','adj','Full of misdemeanour','minor crime-rich,abounding','C1'],
      ['misdemeanourless','adj','Without misdemeanour','lacking,without','C1'],
      ['misdemeanourism','n','The ideology of misdemeanour','minor crime ideology,doctrine','C2'],
      ['misdemeanourist','n','A person focused on misdemeanour','minor crime specialist,advocate','C2'],
      ['misdemeanourise','v','To make into misdemeanour','minor crime,convert','C2'],
      ['misdemeanourize','v','To make or become misdemeanour','minor crime,transform','C2'],
      ['antimisdemeanour','adj','Opposed to misdemeanour','against,opposing','C2'],
      ['nonmisdemeanour','adj','Not involving misdemeanour','without,lacking','C1'],
      ['premisdemeanour','n','Before misdemeanour','preceding,prior','C2'],
      ['postmisdemeanour','n','After misdemeanour','following,subsequent','C2'],
      ['submisdemeanour','n','A subdivision of misdemeanour','subset,branch','C2'],
      ['multimisdemeanour','adj','Involving many misdemeanours','multiple,several','C2'],
      ['intermisdemeanour','adj','Between misdemeanours','cross,between','C2'],
      ['felonyal','adj','Relating to felony','major crime-related,pertaining to','C1'],
      ['felonyic','adj','Of or relating to felony','major crime-based,characteristic','C1'],
      ['felonyous','adj','Full of felony','major crime-filled,abundant','C2'],
      ['felonyful','adj','Full of felony','major crime-rich,abounding','C1'],
      ['felonyless','adj','Without felony','lacking,without','C1'],
      ['felonyism','n','The ideology of felony','major crime ideology,doctrine','C2'],
      ['felonyist','n','A person focused on felony','major crime specialist,advocate','C2'],
      ['felonyise','v','To make into felony','major crime,convert','C2'],
      ['felonyize','v','To make or become felony','major crime,transform','C2'],
      ['antifelony','adj','Opposed to felony','against,opposing','C2'],
      ['nonfelony','adj','Not involving felony','without,lacking','C1'],
      ['prefelony','n','Before felony','preceding,prior','C2'],
      ['postfelony','n','After felony','following,subsequent','C2'],
      ['subfelony','n','A subdivision of felony','subset,branch','C2'],
      ['multifelony','adj','Involving many felonys','multiple,several','C2'],
      ['interfelony','adj','Between felonys','cross,between','C2'],
      ['indictmental','adj','Relating to indictment','charge-related,pertaining to','C1'],
      ['indictmentic','adj','Of or relating to indictment','charge-based,characteristic','C1'],
      ['indictmentous','adj','Full of indictment','charge-filled,abundant','C2'],
      ['indictmentful','adj','Full of indictment','charge-rich,abounding','C1'],
      ['indictmentless','adj','Without indictment','lacking,without','C1'],
      ['indictmentism','n','The ideology of indictment','charge ideology,doctrine','C2'],
      ['indictmentist','n','A person focused on indictment','charge specialist,advocate','C2'],
      ['indictmentise','v','To make into indictment','charge,convert','C2'],
      ['indictmentize','v','To make or become indictment','charge,transform','C2'],
      ['antiindictment','adj','Opposed to indictment','against,opposing','C2'],
      ['nonindictment','adj','Not involving indictment','without,lacking','C1'],
      ['preindictment','n','Before indictment','preceding,prior','C2'],
      ['postindictment','n','After indictment','following,subsequent','C2'],
      ['subindictment','n','A subdivision of indictment','subset,branch','C2'],
      ['multiindictment','adj','Involving many indictments','multiple,several','C2'],
      ['interindictment','adj','Between indictments','cross,between','C2'],
      ['acquittalal','adj','Relating to acquittal','clearance-related,pertaining to','C1'],
      ['acquittalic','adj','Of or relating to acquittal','clearance-based,characteristic','C1'],
      ['acquittalous','adj','Full of acquittal','clearance-filled,abundant','C2'],
      ['acquittalful','adj','Full of acquittal','clearance-rich,abounding','C1'],
      ['acquittalless','adj','Without acquittal','lacking,without','C1'],
      ['acquittalism','n','The ideology of acquittal','clearance ideology,doctrine','C2'],
      ['acquittalist','n','A person focused on acquittal','clearance specialist,advocate','C2'],
      ['acquittalise','v','To make into acquittal','clearance,convert','C2'],
      ['acquittalize','v','To make or become acquittal','clearance,transform','C2'],
      ['antiacquittal','adj','Opposed to acquittal','against,opposing','C2'],
      ['nonacquittal','adj','Not involving acquittal','without,lacking','C1'],
      ['preacquittal','n','Before acquittal','preceding,prior','C2'],
      ['postacquittal','n','After acquittal','following,subsequent','C2'],
      ['subacquittal','n','A subdivision of acquittal','subset,branch','C2'],
      ['multiacquittal','adj','Involving many acquittals','multiple,several','C2'],
      ['interacquittal','adj','Between acquittals','cross,between','C2'],
      ['homicideal','adj','Relating to homicide','murder-related,pertaining to','B2'],
      ['homicideic','adj','Of or relating to homicide','murder-based,characteristic','B2'],
      ['homicideous','adj','Full of homicide','murder-filled,abundant','C1'],
      ['homicideful','adj','Full of homicide','murder-rich,abounding','B2'],
      ['homicideless','adj','Without homicide','lacking,without','B2'],
      ['homicideism','n','The ideology of homicide','murder ideology,doctrine','C1'],
      ['homicideist','n','A person focused on homicide','murder specialist,advocate','C1'],
      ['homicideise','v','To make into homicide','murder,convert','C1'],
      ['homicideize','v','To make or become homicide','murder,transform','C1'],
      ['antihomicide','adj','Opposed to homicide','against,opposing','C1'],
      ['nonhomicide','adj','Not involving homicide','without,lacking','B2'],
      ['prehomicide','n','Before homicide','preceding,prior','C1'],
      ['posthomicide','n','After homicide','following,subsequent','C1'],
      ['subhomicide','n','A subdivision of homicide','subset,branch','C1'],
      ['multihomicide','adj','Involving many homicides','multiple,several','C1'],
      ['interhomicide','adj','Between homicides','cross,between','C1'],
      ['fraudic','adj','Of or relating to fraud','deception-based,characteristic','B2'],
      ['fraudous','adj','Full of fraud','deception-filled,abundant','C1'],
      ['fraudful','adj','Full of fraud','deception-rich,abounding','B2'],
      ['fraudless','adj','Without fraud','lacking,without','B2'],
      ['fraudism','n','The ideology of fraud','deception ideology,doctrine','C1'],
      ['fraudist','n','A person focused on fraud','deception specialist,advocate','C1'],
      ['fraudise','v','To make into fraud','deception,convert','C1'],
      ['fraudize','v','To make or become fraud','deception,transform','C1'],
      ['antifraud','adj','Opposed to fraud','against,opposing','C1'],
      ['nonfraud','adj','Not involving fraud','without,lacking','B2'],
      ['prefraud','n','Before fraud','preceding,prior','C1'],
      ['postfraud','n','After fraud','following,subsequent','C1'],
      ['subfraud','n','A subdivision of fraud','subset,branch','C1'],
      ['multifraud','adj','Involving many frauds','multiple,several','C1'],
      ['interfraud','adj','Between frauds','cross,between','C1'],
      ['arsonic','adj','Of or relating to arson','fire-setting-based,characteristic','C1'],
      ['arsonous','adj','Full of arson','fire-setting-filled,abundant','C2'],
      ['arsonful','adj','Full of arson','fire-setting-rich,abounding','C1'],
      ['arsonless','adj','Without arson','lacking,without','C1'],
      ['arsonism','n','The ideology of arson','fire-setting ideology,doctrine','C2'],
      ['arsonist','n','A person focused on arson','fire-setting specialist,advocate','C2'],
      ['arsonise','v','To make into arson','fire-setting,convert','C2'],
      ['arsonize','v','To make or become arson','fire-setting,transform','C2'],
      ['antiarson','adj','Opposed to arson','against,opposing','C2'],
      ['nonarson','adj','Not involving arson','without,lacking','C1'],
      ['prearson','n','Before arson','preceding,prior','C2'],
      ['postarson','n','After arson','following,subsequent','C2'],
      ['subarson','n','A subdivision of arson','subset,branch','C2'],
      ['multiarson','adj','Involving many arsons','multiple,several','C2'],
      ['interarson','adj','Between arsons','cross,between','C2'],
      ['perjuryic','adj','Of or relating to perjury','false testimony-based,characteristic','C1'],
      ['perjuryous','adj','Full of perjury','false testimony-filled,abundant','C2'],
      ['perjuryful','adj','Full of perjury','false testimony-rich,abounding','C1'],
      ['perjuryless','adj','Without perjury','lacking,without','C1'],
      ['perjuryism','n','The ideology of perjury','false testimony ideology,doctrine','C2'],
      ['perjuryist','n','A person focused on perjury','false testimony specialist,advocate','C2'],
      ['perjuryise','v','To make into perjury','false testimony,convert','C2'],
      ['perjuryize','v','To make or become perjury','false testimony,transform','C2'],
      ['antiperjury','adj','Opposed to perjury','against,opposing','C2'],
      ['nonperjury','adj','Not involving perjury','without,lacking','C1'],
      ['preperjury','n','Before perjury','preceding,prior','C2'],
      ['postperjury','n','After perjury','following,subsequent','C2'],
      ['subperjury','n','A subdivision of perjury','subset,branch','C2'],
      ['multiperjury','adj','Involving many perjurys','multiple,several','C2'],
      ['interperjury','adj','Between perjurys','cross,between','C2'],
      ['statuteal','adj','Relating to statute','law-related,pertaining to','B2'],
      ['statuteic','adj','Of or relating to statute','law-based,characteristic','B2'],
      ['statuteous','adj','Full of statute','law-filled,abundant','C1'],
      ['statuteful','adj','Full of statute','law-rich,abounding','B2'],
      ['statuteless','adj','Without statute','lacking,without','B2'],
      ['statuteism','n','The ideology of statute','law ideology,doctrine','C1'],
      ['statuteist','n','A person focused on statute','law specialist,advocate','C1'],
      ['statuteise','v','To make into statute','law,convert','C1'],
      ['statuteize','v','To make or become statute','law,transform','C1'],
      ['antistatute','adj','Opposed to statute','against,opposing','C1'],
      ['nonstatute','adj','Not involving statute','without,lacking','B2'],
      ['prestatute','n','Before statute','preceding,prior','C1'],
      ['poststatute','n','After statute','following,subsequent','C1'],
      ['substatute','n','A subdivision of statute','subset,branch','C1'],
      ['multistatute','adj','Involving many statutes','multiple,several','C1'],
      ['interstatute','adj','Between statutes','cross,between','C1'],
      ['jurisprudenceic','adj','Of or relating to jurisprudence','legal theory-based,characteristic','C2'],
      ['jurisprudenceous','adj','Full of jurisprudence','legal theory-filled,abundant','C2'],
      ['jurisprudenceful','adj','Full of jurisprudence','legal theory-rich,abounding','C2'],
      ['jurisprudenceless','adj','Without jurisprudence','lacking,without','C2'],
      ['jurisprudenceism','n','The ideology of jurisprudence','legal theory ideology,doctrine','C2'],
      ['jurisprudenceist','n','A person focused on jurisprudence','legal theory specialist,advocate','C2'],
      ['jurisprudenceise','v','To make into jurisprudence','legal theory,convert','C2'],
      ['jurisprudenceize','v','To make or become jurisprudence','legal theory,transform','C2'],
      ['antijurisprudence','adj','Opposed to jurisprudence','against,opposing','C2'],
      ['nonjurisprudence','adj','Not involving jurisprudence','without,lacking','C2'],
      ['prejurisprudence','n','Before jurisprudence','preceding,prior','C2'],
      ['postjurisprudence','n','After jurisprudence','following,subsequent','C2'],
      ['subjurisprudence','n','A subdivision of jurisprudence','subset,branch','C2'],
      ['multijurisprudence','adj','Involving many jurisprudences','multiple,several','C2'],
      ['interjurisprudence','adj','Between jurisprudences','cross,between','C2'],
      ['habeas corpusal','adj','Relating to habeas corpus','legal safeguard-related,pertaining to','C2'],
      ['habeas corpusic','adj','Of or relating to habeas corpus','legal safeguard-based,characteristic','C2'],
      ['habeas corpusous','adj','Full of habeas corpus','legal safeguard-filled,abundant','C2'],
      ['habeas corpusful','adj','Full of habeas corpus','legal safeguard-rich,abounding','C2'],
      ['habeas corpusless','adj','Without habeas corpus','lacking,without','C2'],
      ['habeas corpusism','n','The ideology of habeas corpus','legal safeguard ideology,doctrine','C2'],
      ['habeas corpusist','n','A person focused on habeas corpus','legal safeguard specialist,advocate','C2'],
      ['habeas corpusise','v','To make into habeas corpus','legal safeguard,convert','C2'],
      ['habeas corpusize','v','To make or become habeas corpus','legal safeguard,transform','C2'],
      ['antihabeas corpus','adj','Opposed to habeas corpus','against,opposing','C2'],
      ['nonhabeas corpus','adj','Not involving habeas corpus','without,lacking','C2'],
      ['prehabeas corpus','n','Before habeas corpus','preceding,prior','C2'],
      ['posthabeas corpus','n','After habeas corpus','following,subsequent','C2'],
      ['subhabeas corpus','n','A subdivision of habeas corpus','subset,branch','C2'],
      ['multihabeas corpus','adj','Involving many habeas corpuss','multiple,several','C2'],
      ['interhabeas corpus','adj','Between habeas corpuss','cross,between','C2'],
      ['culpablely','adv','In a culpable manner','guilty way','C1'],
      ['culpableness','n','The quality of being culpable','guilty quality','C1'],
      ['culpableity','n','The state of being culpable','guilty condition','C2'],
      ['unculpable','adj','Not culpable','not guilty','C1'],
      ['inculpable','adj','Not culpable','not guilty','C2'],
      ['nonculpable','adj','Not culpable','not guilty','C1'],
      ['semiculpable','adj','Partially culpable','partly guilty','C2'],
      ['overculpable','adj','Excessively culpable','too guilty','C2'],
      ['ultraculpable','adj','Extremely culpable','very guilty','C2'],
      ['inadmissible','adj','Not accepted as valid evidence','unacceptable,invalid,rejected','C1'],
      ['inadmissiblely','adv','In a inadmissible manner','unacceptable way','C1'],
      ['inadmissibleness','n','The quality of being inadmissible','unacceptable quality','C1'],
      ['inadmissibleity','n','The state of being inadmissible','unacceptable condition','C2'],
      ['uninadmissible','adj','Not inadmissible','not unacceptable','C1'],
      ['ininadmissible','adj','Not inadmissible','not unacceptable','C2'],
      ['noninadmissible','adj','Not inadmissible','not unacceptable','C1'],
      ['semiinadmissible','adj','Partially inadmissible','partly unacceptable','C2'],
      ['overinadmissible','adj','Excessively inadmissible','too unacceptable','C2'],
      ['ultrainadmissible','adj','Extremely inadmissible','very unacceptable','C2'],
      ['circumstantial','adj','Based on inference rather than proof','indirect,presumptive,suggestive','C1'],
      ['circumstantially','adv','In a circumstantial manner','indirect way','C1'],
      ['circumstantialness','n','The quality of being circumstantial','indirect quality','C1'],
      ['circumstantiality','n','The state of being circumstantial','indirect condition','C2'],
      ['uncircumstantial','adj','Not circumstantial','not indirect','C1'],
      ['incircumstantial','adj','Not circumstantial','not indirect','C2'],
      ['noncircumstantial','adj','Not circumstantial','not indirect','C1'],
      ['semicircumstantial','adj','Partially circumstantial','partly indirect','C2'],
      ['overcircumstantial','adj','Excessively circumstantial','too indirect','C2'],
      ['ultracircumstantial','adj','Extremely circumstantial','very indirect','C2'],
      ['premeditatedity','n','The state of being premeditated','planned condition','C2'],
      ['inpremeditated','adj','Not premeditated','not planned','C2'],
      ['nonpremeditated','adj','Not premeditated','not planned','C1'],
      ['semipremeditated','adj','Partially premeditated','partly planned','C2'],
      ['overpremeditated','adj','Excessively premeditated','too planned','C2'],
      ['ultrapremeditated','adj','Extremely premeditated','very planned','C2'],
      ['clandestinely','adv','In a clandestine manner','secret way','C1'],
      ['clandestineness','n','The quality of being clandestine','secret quality','C1'],
      ['clandestineity','n','The state of being clandestine','secret condition','C2'],
      ['unclandestine','adj','Not clandestine','not secret','C1'],
      ['inclandestine','adj','Not clandestine','not secret','C2'],
      ['nonclandestine','adj','Not clandestine','not secret','C1'],
      ['semiclandestine','adj','Partially clandestine','partly secret','C2'],
      ['overclandestine','adj','Excessively clandestine','too secret','C2'],
      ['ultraclandestine','adj','Extremely clandestine','very secret','C2'],
      ['illicit','adj','Forbidden by law or rules','illegal,unlawful,prohibited','C1'],
      ['illicitly','adv','In a illicit manner','illegal way','C1'],
      ['illicitness','n','The quality of being illicit','illegal quality','C1'],
      ['illicitity','n','The state of being illicit','illegal condition','C2'],
      ['unillicit','adj','Not illicit','not illegal','C1'],
      ['inillicit','adj','Not illicit','not illegal','C2'],
      ['nonillicit','adj','Not illicit','not illegal','C1'],
      ['semiillicit','adj','Partially illicit','partly illegal','C2'],
      ['overillicit','adj','Excessively illicit','too illegal','C2'],
      ['ultraillicit','adj','Extremely illicit','very illegal','C2'],
      ['judiciary','n','The judicial branch of government','courts,judges,legal system','B2'],
      ['judiciaryal','adj','Relating to judiciary','courts-related,pertaining to','B2'],
      ['judiciaryic','adj','Of or relating to judiciary','courts-based,characteristic','B2'],
      ['judiciaryous','adj','Full of judiciary','courts-filled,abundant','C1'],
      ['judiciaryful','adj','Full of judiciary','courts-rich,abounding','B2'],
      ['judiciaryless','adj','Without judiciary','lacking,without','B2'],
      ['judiciaryism','n','The ideology of judiciary','courts ideology,doctrine','C1'],
      ['judiciaryist','n','A person focused on judiciary','courts specialist,advocate','C1'],
      ['judiciaryise','v','To make into judiciary','courts,convert','C1'],
      ['judiciaryize','v','To make or become judiciary','courts,transform','C1'],
      ['antijudiciary','adj','Opposed to judiciary','against,opposing','C1'],
      ['nonjudiciary','adj','Not involving judiciary','without,lacking','B2'],
      ['prejudiciary','n','Before judiciary','preceding,prior','C1'],
      ['postjudiciary','n','After judiciary','following,subsequent','C1'],
      ['subjudiciary','n','A subdivision of judiciary','subset,branch','C1'],
      ['multijudiciary','adj','Involving many judiciarys','multiple,several','C1'],
      ['interjudiciary','adj','Between judiciarys','cross,between','C1'],
      ['whistlebloweric','adj','Of or relating to whistleblower','informant-based,characteristic','B2'],
      ['whistleblowerous','adj','Full of whistleblower','informant-filled,abundant','C1'],
      ['whistleblowerful','adj','Full of whistleblower','informant-rich,abounding','B2'],
      ['whistleblowerless','adj','Without whistleblower','lacking,without','B2'],
      ['whistleblowerism','n','The ideology of whistleblower','informant ideology,doctrine','C1'],
      ['whistleblowerist','n','A person focused on whistleblower','informant specialist,advocate','C1'],
    ],
  },
  collocations: {}
};
