module.exports = {
  vocab: {
    communication: [
    ['semaphoreal','adj','Relating to semaphore','flag signals-related','B2'],
    ['telegraphicly','adv','In a telegraphic manner','concise way','C1'],
    ['telegraphicness','n','The quality of being telegraphic','concise quality','C2'],
    ['untelegraphic','adj','Not telegraphic','not concise','C1'],
    ['multimodally','adv','In a multimodal manner','multi-channel way','B2'],
    ['multimodalness','n','The quality of being multimodal','multi-channel quality','C1'],
    ['unmultimodal','adj','Not multimodal','not multi-channel','B2']
    ],
    travel: [
    ['flâneur','n','A person who strolls observing society','wanderer,urban explorer,stroller','C2'],
    ['staycation','n','A holiday spent at or near home','home holiday,local break','B2'],
    ['voluntourism','n','Volunteering combined with tourism','volunteer travel,service tourism','B2'],
    ['glamping','n','Luxury camping in comfort','glamorous camping,luxury outdoors','B2'],
    ['xenophilia','n','An attraction to foreign cultures','culture love,foreign fascination','C1'],
    ['wayfinding','n','Navigation through unfamiliar environments','orientation,route finding','C1'],
    ['heritage tourism','n','Visiting sites of historical significance','cultural tourism,history tourism','B2'],
    ['caravanserai','n','A historical inn for travellers','rest house,roadside inn','C2'],
    ['acclimatise','v','To adjust to new conditions','adapt,get used to,adjust','B2'],
    ['vagrant','adj','Having no settled home','homeless,transient,rootless','C1'],
    ['airportal','adj','Relating to airport','airfield-related','A2'],
    ['hotelal','adj','Relating to hotel','inn-related','A2'],
    ['ticketal','adj','Relating to ticket','pass-related','A2'],
    ['passportal','adj','Relating to passport','travel document-related','A2'],
    ['luggageal','adj','Relating to luggage','baggage-related','A2'],
    ['touristal','adj','Relating to tourist','visitor-related','A2'],
    ['holidayal','adj','Relating to holiday','vacation-related','A2'],
    ['journeyal','adj','Relating to journey','trip-related','A2'],
    ['itineraryal','adj','Relating to itinerary','travel plan-related','B1'],
    ['accommodational','adj','Relating to accommodation','lodging-related','B1'],
    ['destinational','adj','Relating to destination','goal-related','B1'],
    ['excursional','adj','Relating to excursion','outing-related','B1'],
    ['currencyal','adj','Relating to currency','money-related','B1'],
    ['customsal','adj','Relating to customs','border control-related','B1'],
    ['backpackingal','adj','Relating to backpacking','budget travel-related','B1'],
    ['ecotourismal','adj','Relating to ecotourism','green travel-related','B2'],
    ['expeditional','adj','Relating to expedition','quest-related','B2'],
    ['sojournal','adj','Relating to sojourn','visit-related','B2'],
    ['wanderlustal','adj','Relating to wanderlust','travel fever-related','B2'],
    ['infrastructureal','adj','Relating to infrastructure','transport network-related','B2'],
    ['cosmopolitanly','adv','In a cosmopolitan manner','worldly way','C1'],
    ['cosmopolitanness','n','The quality of being cosmopolitan','worldly quality','C2'],
    ['uncosmopolitan','adj','Not cosmopolitan','not worldly','C1'],
    ['visaal','adj','Relating to visa','entry permit-related','A2'],
    ['souveniral','adj','Relating to souvenir','memento-related','A2'],
    ['guidebookal','adj','Relating to guidebook','travel guide-related','A2'],
    ['hostelal','adj','Relating to hostel','dormitory-related','B1'],
    ['cruiseal','adj','Relating to cruise','sea voyage-related','B1'],
    ['layoveral','adj','Relating to layover','stopover-related','B1'],
    ['all-inclusively','adv','In a all-inclusive manner','comprehensive way','B1'],
    ['all-inclusiveness','n','The quality of being all-inclusive','comprehensive quality','B2'],
    ['unall-inclusive','adj','Not all-inclusive','not comprehensive','B1'],
    ['staycational','adj','Relating to staycation','home holiday-related','B2'],
    ['voluntourismal','adj','Relating to voluntourism','volunteer travel-related','B2'],
    ['glampingal','adj','Relating to glamping','glamorous camping-related','B2'],
    ['xenophiliaal','adj','Relating to xenophilia','culture love-related','C1'],
    ['wayfindingal','adj','Relating to wayfinding','orientation-related','C1'],
    ['repatriational','adj','Relating to repatriation','homecoming-related','C1'],
    ['peregrinational','adj','Relating to peregrination','wandering-related','C2'],
    ['circumnavigational','adj','Relating to circumnavigation','round trip-related','C1'],
    ['caravanseraial','adj','Relating to caravanserai','rest house-related','C2'],
    ['acclimatisation','n','The act or process of acclimatising','adapt process,get used to process,adjust process','B2'],
    ['acclimatiser','n','A person who acclimatises','adapt person,get used to person,adjust person','C1'],
    ['acclimatisable','adj','Able to be acclimatised','adapt,possible','C1'],
    ['acclimatising','n','The process of acclimatising something','adapt activity','B2'],
    ['itinerantly','adv','In a itinerant manner','wandering way','C1'],
    ['itinerantness','n','The quality of being itinerant','wandering quality','C2'],
    ['unitinerant','adj','Not itinerant','not wandering','C1'],
    ['vagrantly','adv','In a vagrant manner','homeless way','C1'],
    ['vagrantness','n','The quality of being vagrant','homeless quality','C2'],
    ['unvagrant','adj','Not vagrant','not homeless','C1']
    ],
    government: [
    ['federalism','n','A system dividing power between central and regional governments','devolution,decentralisation','B2'],
    ['coup','n','A sudden seizure of government power','overthrow,takeover,putsch','B2'],
    ['impeachment','n','Charging a public official with misconduct','removal,prosecution,indictment','B2'],
    ['junta','n','A military group ruling after a coup','military regime,ruling council','C1'],
    ['realpolitik','n','Politics based on practical considerations','pragmatic politics,power-focused policy','C2'],
    ['balkanise','v','To divide a region into hostile factions','fragment,partition,split','C1'],
    ['presidental','adj','Relating to president','head of state-related','A2'],
    ['electional','adj','Relating to election','vote-related','A2'],
    ['votation','n','The act or process of voting','ballot process,elect process,choose process','A2'],
    ['voter','n','A person who votes','ballot person,elect person,choose person','B1'],
    ['votable','adj','Able to be voted','ballot,possible','B1'],
    ['voting','n','The process of voting something','ballot activity','A2'],
    ['countryal','adj','Relating to country','nation-related','A2'],
    ['parliamental','adj','Relating to parliament','congress-related','B1'],
    ['democracyal','adj','Relating to democracy','self-rule-related','B1'],
    ['policyal','adj','Relating to policy','plan-related','B1'],
    ['citizenal','adj','Relating to citizen','national-related','B1'],
    ['reformal','adj','Relating to reform','improvement-related','B1'],
    ['oppositional','adj','Relating to opposition','rival party-related','B1'],
    ['bureaucracyal','adj','Relating to bureaucracy','red tape-related','B2'],
    ['sovereigntyal','adj','Relating to sovereignty','independence-related','B2'],
    ['legislational','adj','Relating to legislation','statutes-related','B2'],
    ['referendumal','adj','Relating to referendum','plebiscite-related','B2'],
    ['lobbyation','n','The act or process of lobbying','campaign process,petition process,advocate process','B2'],
    ['lobbyer','n','A person who lobbys','campaign person,petition person,advocate person','C1'],
    ['lobbyable','adj','Able to be lobbyd','campaign,possible','C1'],
    ['lobbying','n','The process of lobbying something','campaign activity','B2'],
    ['federalismal','adj','Relating to federalism','devolution-related','B2'],
    ['bipartisanly','adv','In a bipartisan manner','cross-party way','B2'],
    ['bipartisanness','n','The quality of being bipartisan','cross-party quality','C1'],
    ['unbipartisan','adj','Not bipartisan','not cross-party','B2'],
    ['geopoliticsal','adj','Relating to geopolitics','international relations-related','C1'],
    ['autocracyal','adj','Relating to autocracy','dictatorship-related','C1'],
    ['theocracyal','adj','Relating to theocracy','religious rule-related','C1'],
    ['kleptocracyal','adj','Relating to kleptocracy','corrupt rule-related','C2'],
    ['kakistocracyal','adj','Relating to kakistocracy','rule by incompetents-related','C2'],
    ['mayoral','adj','Relating to mayor','city leader-related','A2'],
    ['ministeral','adj','Relating to minister','secretary-related','B1'],
    ['cabinetal','adj','Relating to cabinet','council-related','B1'],
    ['amendmental','adj','Relating to amendment','revision-related','B1'],
    ['diplomatal','adj','Relating to diplomat','ambassador-related','B1'],
    ['sanctional','adj','Relating to sanction','restriction-related','B2'],
    ['vetoal','adj','Relating to veto','rejection-related','B2'],
    ['coupal','adj','Relating to coup','overthrow-related','B2'],
    ['impeachmental','adj','Relating to impeachment','removal-related','B2'],
    ['gerrymanderingal','adj','Relating to gerrymandering','boundary rigging-related','C1'],
    ['filibusteral','adj','Relating to filibuster','obstruction-related','C1'],
    ['totalitarianly','adv','In a totalitarian manner','authoritarian way','B2'],
    ['totalitarianness','n','The quality of being totalitarian','authoritarian quality','C1'],
    ['untotalitarian','adj','Not totalitarian','not authoritarian','B2'],
    ['plebisciteal','adj','Relating to plebiscite','referendum-related','C1'],
    ['devolutional','adj','Relating to devolution','decentralisation-related','C1'],
    ['juntaal','adj','Relating to junta','military regime-related','C1'],
    ['demagogueryal','adj','Relating to demagoguery','populism-related','C2'],
    ['realpolitikal','adj','Relating to realpolitik','pragmatic politics-related','C2'],
    ['balkaniser','n','A person who balkanises','fragment person,partition person,split person','C2'],
    ['balkanisable','adj','Able to be balkanised','fragment,possible','C2'],
    ['balkanising','n','The process of balkanising something','fragment activity','C1'],
    ['enfranchisation','n','The act or process of enfranchising','empower process,give voting rights process','C1'],
    ['enfranchiser','n','A person who enfranchises','empower person,give voting rights person','C2'],
    ['enfranchisable','adj','Able to be enfranchised','empower,possible','C2'],
    ['enfranchising','n','The process of enfranchising something','empower activity','C1'],
    ['mandateal','adj','Relating to mandate','authorisation-related','B2']
    ],
    psychology: [
    ['neuroplasticity','n','The brains ability to reorganise itself','brain adaptability,neural flexibility','B2'],
    ['cognitive dissonance','n','Mental discomfort from conflicting beliefs','belief conflict,mental tension','C1'],
    ['psychopath','n','A person with antisocial personality disorder','sociopath,antisocial person','B2'],
    ['priming','n','Exposure influencing subsequent responses','influence,preparation,conditioning','C1'],
    ['limbic','adj','Relating to the emotional brain region','emotion-controlling,mid-brain','C1'],
    ['somatoform','adj','Physical symptoms from psychological causes','psychogenic,mind-caused,stress-induced','C2'],
    ['thanatophobia','n','An extreme fear of death','death anxiety,mortality fear','C2'],
    ['projective','adj','Revealing hidden emotions through responses','interpretive,diagnostic,revealing','C1'],
    ['desensitisation','n','Reducing emotional response through exposure','habituation,tolerance building','B2'],
    ['brainal','adj','Relating to brain','mind-related','A2'],
    ['happily','adv','In a happy manner','joyful way','A2']
    ],
  },
  collocations: {
  }
};
