// Auto-generated vocab boost group 44
module.exports = {
  vocab: {
    environment: [
      ['aquiferise','v','To make into aquifer','water table,convert','C2'],
      ['aquiferize','v','To make or become aquifer','water table,transform','C2'],
      ['antiaquifer','adj','Opposed to aquifer','against,opposing','C2'],
      ['nonaquifer','adj','Not involving aquifer','without,lacking','C1'],
      ['preaquifer','n','Before aquifer','preceding,prior','C2'],
      ['postaquifer','n','After aquifer','following,subsequent','C2'],
      ['subaquifer','n','A subdivision of aquifer','subset,branch','C2'],
      ['multiaquifer','adj','Involving many aquifers','multiple,several','C2'],
      ['interaquifer','adj','Between aquifers','cross,between','C2'],
      ['biodiversityic','adj','Of or relating to biodiversity','biological variety-based,characteristic','B2'],
      ['biodiversityous','adj','Full of biodiversity','biological variety-filled,abundant','C1'],
      ['biodiversityful','adj','Full of biodiversity','biological variety-rich,abounding','B2'],
      ['biodiversityless','adj','Without biodiversity','lacking,without','B2'],
      ['biodiversityism','n','The ideology of biodiversity','biological variety ideology,doctrine','C1'],
      ['biodiversityist','n','A person focused on biodiversity','biological variety specialist,advocate','C1'],
      ['biodiversityise','v','To make into biodiversity','biological variety,convert','C1'],
      ['biodiversityize','v','To make or become biodiversity','biological variety,transform','C1'],
      ['antibiodiversity','adj','Opposed to biodiversity','against,opposing','C1'],
      ['nonbiodiversity','adj','Not involving biodiversity','without,lacking','B2'],
      ['prebiodiversity','n','Before biodiversity','preceding,prior','C1'],
      ['postbiodiversity','n','After biodiversity','following,subsequent','C1'],
      ['subbiodiversity','n','A subdivision of biodiversity','subset,branch','C1'],
      ['multibiodiversity','adj','Involving many biodiversitys','multiple,several','C1'],
      ['interbiodiversity','adj','Between biodiversitys','cross,between','C1'],
      ['ecosystemic','adj','Of or relating to ecosystem','habitat-based,characteristic','B2'],
      ['ecosystemous','adj','Full of ecosystem','habitat-filled,abundant','C1'],
      ['ecosystemful','adj','Full of ecosystem','habitat-rich,abounding','B2'],
      ['ecosystemless','adj','Without ecosystem','lacking,without','B2'],
      ['ecosystemism','n','The ideology of ecosystem','habitat ideology,doctrine','C1'],
      ['ecosystemist','n','A person focused on ecosystem','habitat specialist,advocate','C1'],
      ['ecosystemise','v','To make into ecosystem','habitat,convert','C1'],
      ['ecosystemize','v','To make or become ecosystem','habitat,transform','C1'],
      ['antiecosystem','adj','Opposed to ecosystem','against,opposing','C1'],
      ['nonecosystem','adj','Not involving ecosystem','without,lacking','B2'],
      ['preecosystem','n','Before ecosystem','preceding,prior','C1'],
      ['postecosystem','n','After ecosystem','following,subsequent','C1'],
      ['subecosystem','n','A subdivision of ecosystem','subset,branch','C1'],
      ['multiecosystem','adj','Involving many ecosystems','multiple,several','C1'],
      ['interecosystem','adj','Between ecosystems','cross,between','C1'],
      ['watershedal','adj','Relating to watershed','drainage basin-related,pertaining to','C1'],
      ['watershedic','adj','Of or relating to watershed','drainage basin-based,characteristic','C1'],
      ['watershedous','adj','Full of watershed','drainage basin-filled,abundant','C2'],
      ['watershedful','adj','Full of watershed','drainage basin-rich,abounding','C1'],
      ['watershedless','adj','Without watershed','lacking,without','C1'],
      ['watershedism','n','The ideology of watershed','drainage basin ideology,doctrine','C2'],
      ['watershedist','n','A person focused on watershed','drainage basin specialist,advocate','C2'],
      ['watershedise','v','To make into watershed','drainage basin,convert','C2'],
      ['watershedize','v','To make or become watershed','drainage basin,transform','C2'],
      ['antiwatershed','adj','Opposed to watershed','against,opposing','C2'],
      ['nonwatershed','adj','Not involving watershed','without,lacking','C1'],
      ['prewatershed','n','Before watershed','preceding,prior','C2'],
      ['postwatershed','n','After watershed','following,subsequent','C2'],
      ['subwatershed','n','A subdivision of watershed','subset,branch','C2'],
      ['multiwatershed','adj','Involving many watersheds','multiple,several','C2'],
      ['interwatershed','adj','Between watersheds','cross,between','C2'],
      ['effluental','adj','Relating to effluent','waste water-related,pertaining to','C1'],
      ['effluentic','adj','Of or relating to effluent','waste water-based,characteristic','C1'],
      ['effluentous','adj','Full of effluent','waste water-filled,abundant','C2'],
      ['effluentful','adj','Full of effluent','waste water-rich,abounding','C1'],
      ['effluentless','adj','Without effluent','lacking,without','C1'],
      ['effluentism','n','The ideology of effluent','waste water ideology,doctrine','C2'],
      ['effluentist','n','A person focused on effluent','waste water specialist,advocate','C2'],
      ['effluentise','v','To make into effluent','waste water,convert','C2'],
      ['effluentize','v','To make or become effluent','waste water,transform','C2'],
      ['antieffluent','adj','Opposed to effluent','against,opposing','C2'],
      ['noneffluent','adj','Not involving effluent','without,lacking','C1'],
      ['preeffluent','n','Before effluent','preceding,prior','C2'],
      ['posteffluent','n','After effluent','following,subsequent','C2'],
      ['subeffluent','n','A subdivision of effluent','subset,branch','C2'],
      ['multieffluent','adj','Involving many effluents','multiple,several','C2'],
      ['intereffluent','adj','Between effluents','cross,between','C2'],
      ['particulateal','adj','Relating to particulate','particle-related,pertaining to','C1'],
      ['particulateic','adj','Of or relating to particulate','particle-based,characteristic','C1'],
      ['particulateous','adj','Full of particulate','particle-filled,abundant','C2'],
      ['particulateful','adj','Full of particulate','particle-rich,abounding','C1'],
      ['particulateless','adj','Without particulate','lacking,without','C1'],
      ['particulateism','n','The ideology of particulate','particle ideology,doctrine','C2'],
      ['particulateist','n','A person focused on particulate','particle specialist,advocate','C2'],
      ['particulateise','v','To make into particulate','particle,convert','C2'],
      ['particulateize','v','To make or become particulate','particle,transform','C2'],
      ['antiparticulate','adj','Opposed to particulate','against,opposing','C2'],
      ['nonparticulate','adj','Not involving particulate','without,lacking','C1'],
      ['preparticulate','n','Before particulate','preceding,prior','C2'],
      ['postparticulate','n','After particulate','following,subsequent','C2'],
      ['subparticulate','n','A subdivision of particulate','subset,branch','C2'],
      ['multiparticulate','adj','Involving many particulates','multiple,several','C2'],
      ['interparticulate','adj','Between particulates','cross,between','C2'],
      ['emissionic','adj','Of or relating to emission','discharge-based,characteristic','B2'],
      ['emissionous','adj','Full of emission','discharge-filled,abundant','C1'],
      ['emissionful','adj','Full of emission','discharge-rich,abounding','B2'],
      ['emissionless','adj','Without emission','lacking,without','B2'],
      ['emissionism','n','The ideology of emission','discharge ideology,doctrine','C1'],
      ['emissionist','n','A person focused on emission','discharge specialist,advocate','C1'],
      ['emissionise','v','To make into emission','discharge,convert','C1'],
      ['emissionize','v','To make or become emission','discharge,transform','C1'],
      ['antiemission','adj','Opposed to emission','against,opposing','C1'],
      ['nonemission','adj','Not involving emission','without,lacking','B2'],
      ['preemission','n','Before emission','preceding,prior','C1'],
      ['postemission','n','After emission','following,subsequent','C1'],
      ['subemission','n','A subdivision of emission','subset,branch','C1'],
      ['multiemission','adj','Involving many emissions','multiple,several','C1'],
      ['interemission','adj','Between emissions','cross,between','C1'],
      ['deforestationic','adj','Of or relating to deforestation','tree removal-based,characteristic','B2'],
      ['deforestationous','adj','Full of deforestation','tree removal-filled,abundant','C1'],
      ['deforestationful','adj','Full of deforestation','tree removal-rich,abounding','B2'],
      ['deforestationless','adj','Without deforestation','lacking,without','B2'],
      ['deforestationism','n','The ideology of deforestation','tree removal ideology,doctrine','C1'],
      ['deforestationist','n','A person focused on deforestation','tree removal specialist,advocate','C1'],
      ['deforestationise','v','To make into deforestation','tree removal,convert','C1'],
      ['deforestationize','v','To make or become deforestation','tree removal,transform','C1'],
      ['antideforestation','adj','Opposed to deforestation','against,opposing','C1'],
      ['nondeforestation','adj','Not involving deforestation','without,lacking','B2'],
      ['predeforestation','n','Before deforestation','preceding,prior','C1'],
      ['postdeforestation','n','After deforestation','following,subsequent','C1'],
      ['subdeforestation','n','A subdivision of deforestation','subset,branch','C1'],
      ['multideforestation','adj','Involving many deforestations','multiple,several','C1'],
      ['interdeforestation','adj','Between deforestations','cross,between','C1'],
      ['eutrophicationic','adj','Of or relating to eutrophication','nutrient overload-based,characteristic','C2'],
      ['eutrophicationous','adj','Full of eutrophication','nutrient overload-filled,abundant','C2'],
      ['eutrophicationful','adj','Full of eutrophication','nutrient overload-rich,abounding','C2'],
      ['eutrophicationless','adj','Without eutrophication','lacking,without','C2'],
      ['eutrophicationism','n','The ideology of eutrophication','nutrient overload ideology,doctrine','C2'],
      ['eutrophicationist','n','A person focused on eutrophication','nutrient overload specialist,advocate','C2'],
      ['eutrophicationise','v','To make into eutrophication','nutrient overload,convert','C2'],
      ['eutrophicationize','v','To make or become eutrophication','nutrient overload,transform','C2'],
      ['antieutrophication','adj','Opposed to eutrophication','against,opposing','C2'],
      ['noneutrophication','adj','Not involving eutrophication','without,lacking','C2'],
      ['preeutrophication','n','Before eutrophication','preceding,prior','C2'],
      ['posteutrophication','n','After eutrophication','following,subsequent','C2'],
      ['subeutrophication','n','A subdivision of eutrophication','subset,branch','C2'],
      ['multieutrophication','adj','Involving many eutrophications','multiple,several','C2'],
      ['intereutrophication','adj','Between eutrophications','cross,between','C2'],
      ['desertificationic','adj','Of or relating to desertification','land degradation-based,characteristic','C1'],
      ['desertificationous','adj','Full of desertification','land degradation-filled,abundant','C2'],
      ['desertificationful','adj','Full of desertification','land degradation-rich,abounding','C1'],
      ['desertificationless','adj','Without desertification','lacking,without','C1'],
      ['desertificationism','n','The ideology of desertification','land degradation ideology,doctrine','C2'],
      ['desertificationist','n','A person focused on desertification','land degradation specialist,advocate','C2'],
      ['desertificationise','v','To make into desertification','land degradation,convert','C2'],
      ['desertificationize','v','To make or become desertification','land degradation,transform','C2'],
      ['antidesertification','adj','Opposed to desertification','against,opposing','C2'],
      ['nondesertification','adj','Not involving desertification','without,lacking','C1'],
      ['predesertification','n','Before desertification','preceding,prior','C2'],
      ['postdesertification','n','After desertification','following,subsequent','C2'],
      ['subdesertification','n','A subdivision of desertification','subset,branch','C2'],
      ['multidesertification','adj','Involving many desertifications','multiple,several','C2'],
      ['interdesertification','adj','Between desertifications','cross,between','C2'],
      ['carbon footprintal','adj','Relating to carbon footprint','emission level-related,pertaining to','B2'],
      ['carbon footprintic','adj','Of or relating to carbon footprint','emission level-based,characteristic','B2'],
      ['carbon footprintous','adj','Full of carbon footprint','emission level-filled,abundant','C1'],
      ['carbon footprintful','adj','Full of carbon footprint','emission level-rich,abounding','B2'],
      ['carbon footprintless','adj','Without carbon footprint','lacking,without','B2'],
      ['carbon footprintism','n','The ideology of carbon footprint','emission level ideology,doctrine','C1'],
      ['carbon footprintist','n','A person focused on carbon footprint','emission level specialist,advocate','C1'],
      ['carbon footprintise','v','To make into carbon footprint','emission level,convert','C1'],
      ['carbon footprintize','v','To make or become carbon footprint','emission level,transform','C1'],
      ['anticarbon footprint','adj','Opposed to carbon footprint','against,opposing','C1'],
      ['noncarbon footprint','adj','Not involving carbon footprint','without,lacking','B2'],
      ['precarbon footprint','n','Before carbon footprint','preceding,prior','C1'],
      ['postcarbon footprint','n','After carbon footprint','following,subsequent','C1'],
      ['subcarbon footprint','n','A subdivision of carbon footprint','subset,branch','C1'],
      ['multicarbon footprint','adj','Involving many carbon footprints','multiple,several','C1'],
      ['intercarbon footprint','adj','Between carbon footprints','cross,between','C1'],
      ['greenhouse effectal','adj','Relating to greenhouse effect','global warming-related,pertaining to','B2'],
      ['greenhouse effectic','adj','Of or relating to greenhouse effect','global warming-based,characteristic','B2'],
      ['greenhouse effectous','adj','Full of greenhouse effect','global warming-filled,abundant','C1'],
      ['greenhouse effectful','adj','Full of greenhouse effect','global warming-rich,abounding','B2'],
      ['greenhouse effectless','adj','Without greenhouse effect','lacking,without','B2'],
      ['greenhouse effectism','n','The ideology of greenhouse effect','global warming ideology,doctrine','C1'],
      ['greenhouse effectist','n','A person focused on greenhouse effect','global warming specialist,advocate','C1'],
      ['greenhouse effectise','v','To make into greenhouse effect','global warming,convert','C1'],
      ['greenhouse effectize','v','To make or become greenhouse effect','global warming,transform','C1'],
      ['antigreenhouse effect','adj','Opposed to greenhouse effect','against,opposing','C1'],
      ['nongreenhouse effect','adj','Not involving greenhouse effect','without,lacking','B2'],
      ['pregreenhouse effect','n','Before greenhouse effect','preceding,prior','C1'],
      ['postgreenhouse effect','n','After greenhouse effect','following,subsequent','C1'],
      ['subgreenhouse effect','n','A subdivision of greenhouse effect','subset,branch','C1'],
      ['multigreenhouse effect','adj','Involving many greenhouse effects','multiple,several','C1'],
      ['intergreenhouse effect','adj','Between greenhouse effects','cross,between','C1'],
      ['fossil fuelal','adj','Relating to fossil fuel','coal-related,pertaining to','B2'],
      ['fossil fuelic','adj','Of or relating to fossil fuel','coal-based,characteristic','B2'],
      ['fossil fuelous','adj','Full of fossil fuel','coal-filled,abundant','C1'],
      ['fossil fuelful','adj','Full of fossil fuel','coal-rich,abounding','B2'],
      ['fossil fuelless','adj','Without fossil fuel','lacking,without','B2'],
      ['fossil fuelism','n','The ideology of fossil fuel','coal ideology,doctrine','C1'],
      ['fossil fuelist','n','A person focused on fossil fuel','coal specialist,advocate','C1'],
      ['fossil fuelise','v','To make into fossil fuel','coal,convert','C1'],
      ['fossil fuelize','v','To make or become fossil fuel','coal,transform','C1'],
      ['antifossil fuel','adj','Opposed to fossil fuel','against,opposing','C1'],
      ['nonfossil fuel','adj','Not involving fossil fuel','without,lacking','B2'],
      ['prefossil fuel','n','Before fossil fuel','preceding,prior','C1'],
      ['postfossil fuel','n','After fossil fuel','following,subsequent','C1'],
      ['subfossil fuel','n','A subdivision of fossil fuel','subset,branch','C1'],
      ['multifossil fuel','adj','Involving many fossil fuels','multiple,several','C1'],
      ['interfossil fuel','adj','Between fossil fuels','cross,between','C1'],
      ['ozone layeral','adj','Relating to ozone layer','ozone shield-related,pertaining to','B2'],
      ['ozone layeric','adj','Of or relating to ozone layer','ozone shield-based,characteristic','B2'],
      ['ozone layerous','adj','Full of ozone layer','ozone shield-filled,abundant','C1'],
      ['ozone layerful','adj','Full of ozone layer','ozone shield-rich,abounding','B2'],
      ['ozone layerless','adj','Without ozone layer','lacking,without','B2'],
      ['ozone layerism','n','The ideology of ozone layer','ozone shield ideology,doctrine','C1'],
      ['ozone layerist','n','A person focused on ozone layer','ozone shield specialist,advocate','C1'],
      ['ozone layerise','v','To make into ozone layer','ozone shield,convert','C1'],
      ['ozone layerize','v','To make or become ozone layer','ozone shield,transform','C1'],
      ['antiozone layer','adj','Opposed to ozone layer','against,opposing','C1'],
      ['nonozone layer','adj','Not involving ozone layer','without,lacking','B2'],
      ['preozone layer','n','Before ozone layer','preceding,prior','C1'],
      ['postozone layer','n','After ozone layer','following,subsequent','C1'],
      ['subozone layer','n','A subdivision of ozone layer','subset,branch','C1'],
      ['multiozone layer','adj','Involving many ozone layers','multiple,several','C1'],
      ['interozone layer','adj','Between ozone layers','cross,between','C1'],
      ['habitat lossal','adj','Relating to habitat loss','environment destruction-related,pertaining to','B2'],
      ['habitat lossic','adj','Of or relating to habitat loss','environment destruction-based,characteristic','B2'],
      ['habitat lossous','adj','Full of habitat loss','environment destruction-filled,abundant','C1'],
      ['habitat lossful','adj','Full of habitat loss','environment destruction-rich,abounding','B2'],
      ['habitat lossless','adj','Without habitat loss','lacking,without','B2'],
      ['habitat lossism','n','The ideology of habitat loss','environment destruction ideology,doctrine','C1'],
      ['habitat lossist','n','A person focused on habitat loss','environment destruction specialist,advocate','C1'],
      ['habitat lossise','v','To make into habitat loss','environment destruction,convert','C1'],
      ['habitat lossize','v','To make or become habitat loss','environment destruction,transform','C1'],
      ['antihabitat loss','adj','Opposed to habitat loss','against,opposing','C1'],
      ['nonhabitat loss','adj','Not involving habitat loss','without,lacking','B2'],
      ['prehabitat loss','n','Before habitat loss','preceding,prior','C1'],
      ['posthabitat loss','n','After habitat loss','following,subsequent','C1'],
      ['subhabitat loss','n','A subdivision of habitat loss','subset,branch','C1'],
      ['multihabitat loss','adj','Involving many habitat losss','multiple,several','C1'],
      ['interhabitat loss','adj','Between habitat losss','cross,between','C1'],
      ['invasive species','n','Non-native organisms that cause harm','alien species,pest species','C1'],
      ['invasive speciesal','adj','Relating to invasive species','alien species-related,pertaining to','C1'],
      ['invasive speciesic','adj','Of or relating to invasive species','alien species-based,characteristic','C1'],
      ['invasive speciesous','adj','Full of invasive species','alien species-filled,abundant','C2'],
      ['invasive speciesful','adj','Full of invasive species','alien species-rich,abounding','C1'],
      ['invasive speciesless','adj','Without invasive species','lacking,without','C1'],
      ['invasive speciesism','n','The ideology of invasive species','alien species ideology,doctrine','C2'],
      ['invasive speciesist','n','A person focused on invasive species','alien species specialist,advocate','C2'],
      ['invasive speciesise','v','To make into invasive species','alien species,convert','C2'],
      ['invasive speciesize','v','To make or become invasive species','alien species,transform','C2'],
      ['antiinvasive species','adj','Opposed to invasive species','against,opposing','C2'],
      ['noninvasive species','adj','Not involving invasive species','without,lacking','C1'],
      ['preinvasive species','n','Before invasive species','preceding,prior','C2'],
      ['postinvasive species','n','After invasive species','following,subsequent','C2'],
      ['subinvasive species','n','A subdivision of invasive species','subset,branch','C2'],
      ['multiinvasive species','adj','Involving many invasive speciess','multiple,several','C2'],
      ['interinvasive species','adj','Between invasive speciess','cross,between','C2'],
      ['microplasticic','adj','Of or relating to microplastic','plastic particle-based,characteristic','B2'],
      ['microplasticous','adj','Full of microplastic','plastic particle-filled,abundant','C1'],
      ['microplasticful','adj','Full of microplastic','plastic particle-rich,abounding','B2'],
      ['microplasticless','adj','Without microplastic','lacking,without','B2'],
      ['microplasticism','n','The ideology of microplastic','plastic particle ideology,doctrine','C1'],
      ['microplasticist','n','A person focused on microplastic','plastic particle specialist,advocate','C1'],
    ],
  },
  collocations: {}
};
