// Auto-generated vocab boost group 63
module.exports = {
  vocab: {
    communication: [
      ['diatribeful','adj','Full of diatribe','tirade-rich,abounding','C2'],
      ['diatribeless','adj','Without diatribe','lacking,without','C2'],
      ['diatribeism','n','The ideology of diatribe','tirade ideology,doctrine','C2'],
      ['diatribeist','n','A person focused on diatribe','tirade specialist,advocate','C2'],
      ['diatribeise','v','To make into diatribe','tirade,convert','C2'],
      ['diatribeize','v','To make or become diatribe','tirade,transform','C2'],
      ['antidiatribe','adj','Opposed to diatribe','against,opposing','C2'],
      ['nondiatribe','adj','Not involving diatribe','without,lacking','C2'],
      ['prediatribe','n','Before diatribe','preceding,prior','C2'],
      ['postdiatribe','n','After diatribe','following,subsequent','C2'],
      ['subdiatribe','n','A subdivision of diatribe','subset,branch','C2'],
      ['multidiatribe','adj','Involving many diatribes','multiple,several','C2'],
      ['interdiatribe','adj','Between diatribes','cross,between','C2'],
      ['repartee','n','Conversation with quick witty replies','banter,wit,wordplay','C2'],
      ['reparteeal','adj','Relating to repartee','banter-related,pertaining to','C2'],
      ['reparteeic','adj','Of or relating to repartee','banter-based,characteristic','C2'],
      ['reparteeous','adj','Full of repartee','banter-filled,abundant','C2'],
      ['reparteeful','adj','Full of repartee','banter-rich,abounding','C2'],
      ['reparteeless','adj','Without repartee','lacking,without','C2'],
      ['reparteeism','n','The ideology of repartee','banter ideology,doctrine','C2'],
      ['reparteeist','n','A person focused on repartee','banter specialist,advocate','C2'],
      ['reparteeise','v','To make into repartee','banter,convert','C2'],
      ['reparteeize','v','To make or become repartee','banter,transform','C2'],
      ['antirepartee','adj','Opposed to repartee','against,opposing','C2'],
      ['nonrepartee','adj','Not involving repartee','without,lacking','C2'],
      ['prerepartee','n','Before repartee','preceding,prior','C2'],
      ['postrepartee','n','After repartee','following,subsequent','C2'],
      ['subrepartee','n','A subdivision of repartee','subset,branch','C2'],
      ['multirepartee','adj','Involving many repartees','multiple,several','C2'],
      ['interrepartee','adj','Between repartees','cross,between','C2'],
      ['laconicly','adv','In a laconic manner','terse way','C2'],
      ['laconicness','n','The quality of being laconic','terse quality','C2'],
      ['laconicity','n','The state of being laconic','terse condition','C2'],
      ['unlaconic','adj','Not laconic','not terse','C2'],
      ['inlaconic','adj','Not laconic','not terse','C2'],
      ['nonlaconic','adj','Not laconic','not terse','C2'],
      ['semilaconic','adj','Partially laconic','partly terse','C2'],
      ['overlaconic','adj','Excessively laconic','too terse','C2'],
      ['ultralaconic','adj','Extremely laconic','very terse','C2'],
      ['garrulously','adv','In a garrulous manner','chatty way','C2'],
      ['garrulousness','n','The quality of being garrulous','chatty quality','C2'],
      ['garrulousity','n','The state of being garrulous','chatty condition','C2'],
      ['ungarrulous','adj','Not garrulous','not chatty','C2'],
      ['ingarrulous','adj','Not garrulous','not chatty','C2'],
      ['nongarrulous','adj','Not garrulous','not chatty','C2'],
      ['semigarrulous','adj','Partially garrulous','partly chatty','C2'],
      ['overgarrulous','adj','Excessively garrulous','too chatty','C2'],
      ['ultragarrulous','adj','Extremely garrulous','very chatty','C2'],
      ['loquaciously','adv','In a loquacious manner','talkative way','C2'],
      ['loquaciousness','n','The quality of being loquacious','talkative quality','C2'],
      ['loquaciousity','n','The state of being loquacious','talkative condition','C2'],
      ['unloquacious','adj','Not loquacious','not talkative','C2'],
      ['inloquacious','adj','Not loquacious','not talkative','C2'],
      ['nonloquacious','adj','Not loquacious','not talkative','C2'],
      ['semiloquacious','adj','Partially loquacious','partly talkative','C2'],
      ['overloquacious','adj','Excessively loquacious','too talkative','C2'],
      ['ultraloquacious','adj','Extremely loquacious','very talkative','C2'],
      ['taciturnly','adv','In a taciturn manner','quiet way','C1'],
      ['taciturnness','n','The quality of being taciturn','quiet quality','C1'],
      ['taciturnity','n','The state of being taciturn','quiet condition','C2'],
      ['untaciturn','adj','Not taciturn','not quiet','C1'],
      ['intaciturn','adj','Not taciturn','not quiet','C2'],
      ['nontaciturn','adj','Not taciturn','not quiet','C1'],
      ['semitaciturn','adj','Partially taciturn','partly quiet','C2'],
      ['overtaciturn','adj','Excessively taciturn','too quiet','C2'],
      ['ultrataciturn','adj','Extremely taciturn','very quiet','C2'],
      ['circumlocutionic','adj','Of or relating to circumlocution','periphrasis-based,characteristic','C2'],
      ['circumlocutionous','adj','Full of circumlocution','periphrasis-filled,abundant','C2'],
      ['circumlocutionful','adj','Full of circumlocution','periphrasis-rich,abounding','C2'],
      ['circumlocutionless','adj','Without circumlocution','lacking,without','C2'],
      ['circumlocutionism','n','The ideology of circumlocution','periphrasis ideology,doctrine','C2'],
      ['circumlocutionist','n','A person focused on circumlocution','periphrasis specialist,advocate','C2'],
      ['circumlocutionise','v','To make into circumlocution','periphrasis,convert','C2'],
      ['circumlocutionize','v','To make or become circumlocution','periphrasis,transform','C2'],
      ['anticircumlocution','adj','Opposed to circumlocution','against,opposing','C2'],
      ['noncircumlocution','adj','Not involving circumlocution','without,lacking','C2'],
      ['precircumlocution','n','Before circumlocution','preceding,prior','C2'],
      ['postcircumlocution','n','After circumlocution','following,subsequent','C2'],
      ['subcircumlocution','n','A subdivision of circumlocution','subset,branch','C2'],
      ['multicircumlocution','adj','Involving many circumlocutions','multiple,several','C2'],
      ['intercircumlocution','adj','Between circumlocutions','cross,between','C2'],
      ['malapropismic','adj','Of or relating to malapropism','word confusion-based,characteristic','C2'],
      ['malapropismous','adj','Full of malapropism','word confusion-filled,abundant','C2'],
      ['malapropismful','adj','Full of malapropism','word confusion-rich,abounding','C2'],
      ['malapropismless','adj','Without malapropism','lacking,without','C2'],
      ['malapropismism','n','The ideology of malapropism','word confusion ideology,doctrine','C2'],
      ['malapropismist','n','A person focused on malapropism','word confusion specialist,advocate','C2'],
      ['malapropismise','v','To make into malapropism','word confusion,convert','C2'],
      ['malapropismize','v','To make or become malapropism','word confusion,transform','C2'],
      ['antimalapropism','adj','Opposed to malapropism','against,opposing','C2'],
      ['nonmalapropism','adj','Not involving malapropism','without,lacking','C2'],
      ['premalapropism','n','Before malapropism','preceding,prior','C2'],
      ['postmalapropism','n','After malapropism','following,subsequent','C2'],
      ['submalapropism','n','A subdivision of malapropism','subset,branch','C2'],
      ['multimalapropism','adj','Involving many malapropisms','multiple,several','C2'],
      ['intermalapropism','adj','Between malapropisms','cross,between','C2'],
      ['soliloquyic','adj','Of or relating to soliloquy','monologue-based,characteristic','C1'],
      ['soliloquyous','adj','Full of soliloquy','monologue-filled,abundant','C2'],
      ['soliloquyful','adj','Full of soliloquy','monologue-rich,abounding','C1'],
      ['soliloquyless','adj','Without soliloquy','lacking,without','C1'],
      ['soliloquyism','n','The ideology of soliloquy','monologue ideology,doctrine','C2'],
      ['soliloquyist','n','A person focused on soliloquy','monologue specialist,advocate','C2'],
      ['soliloquyise','v','To make into soliloquy','monologue,convert','C2'],
      ['soliloquyize','v','To make or become soliloquy','monologue,transform','C2'],
      ['antisoliloquy','adj','Opposed to soliloquy','against,opposing','C2'],
      ['nonsoliloquy','adj','Not involving soliloquy','without,lacking','C1'],
      ['presoliloquy','n','Before soliloquy','preceding,prior','C2'],
      ['postsoliloquy','n','After soliloquy','following,subsequent','C2'],
      ['subsoliloquy','n','A subdivision of soliloquy','subset,branch','C2'],
      ['multisoliloquy','adj','Involving many soliloquys','multiple,several','C2'],
      ['intersoliloquy','adj','Between soliloquys','cross,between','C2'],
      ['colloquyal','adj','Relating to colloquy','dialogue-related,pertaining to','C2'],
      ['colloquyic','adj','Of or relating to colloquy','dialogue-based,characteristic','C2'],
      ['colloquyous','adj','Full of colloquy','dialogue-filled,abundant','C2'],
      ['colloquyful','adj','Full of colloquy','dialogue-rich,abounding','C2'],
      ['colloquyless','adj','Without colloquy','lacking,without','C2'],
      ['colloquyism','n','The ideology of colloquy','dialogue ideology,doctrine','C2'],
      ['colloquyist','n','A person focused on colloquy','dialogue specialist,advocate','C2'],
      ['colloquyise','v','To make into colloquy','dialogue,convert','C2'],
      ['colloquyize','v','To make or become colloquy','dialogue,transform','C2'],
      ['anticolloquy','adj','Opposed to colloquy','against,opposing','C2'],
      ['noncolloquy','adj','Not involving colloquy','without,lacking','C2'],
      ['precolloquy','n','Before colloquy','preceding,prior','C2'],
      ['postcolloquy','n','After colloquy','following,subsequent','C2'],
      ['subcolloquy','n','A subdivision of colloquy','subset,branch','C2'],
      ['multicolloquy','adj','Involving many colloquys','multiple,several','C2'],
      ['intercolloquy','adj','Between colloquys','cross,between','C2'],
    ],
    travel: [
      ['traversation','n','The act of traversing','cross process','B2'],
      ['traversment','n','The result of traversing','cross outcome','B2'],
      ['traversance','n','The state of traversing','cross state','B2'],
      ['traversence','n','The quality of traversing','cross quality','B2'],
      ['traversal','n','An act of traversing','cross event','C1'],
      ['traverser','n','One who traverses','cross person','B2'],
      ['traversor','n','One who traverses','cross agent','B2'],
      ['traversee','n','One who is traversed','cross recipient','C1'],
      ['traversable','adj','Capable of being traversed','cross,possible','C1'],
      ['traversible','adj','Able to be traversed','cross,feasible','C1'],
      ['traversive','adj','Tending to traverse','cross,active','B2'],
      ['traversing','adj','Currently traversing','cross,ongoing','B2'],
      ['traversed','adj','Having been traversed','cross,completed','B2'],
      ['retraverse','v','To traverse again','cross again,repeat','B2'],
      ['untraverse','v','To reverse traversing','reverse,undo','C1'],
      ['overtraverse','v','To traverse excessively','excess,too much','C1'],
      ['undertraverse','v','To traverse insufficiently','insufficient,inadequate','C1'],
      ['mistraverse','v','To traverse incorrectly','wrongly,incorrectly','C1'],
      ['pretraverse','v','To traverse beforehand','before,in advance','C1'],
      ['cotraverse','v','To traverse together','jointly,together','C1'],
      ['retraversation','n','The act of traversing again','re-cross','C1'],
      ['overtraversation','n','Excessive traversing','excess cross','C1'],
      ['embarkment','n','The result of embarking','start outcome','B2'],
      ['embarkance','n','The state of embarking','start state','B2'],
      ['embarkence','n','The quality of embarking','start quality','B2'],
      ['embarkal','n','An act of embarking','start event','C1'],
      ['embarker','n','One who embarks','start person','B2'],
      ['embarkor','n','One who embarks','start agent','B2'],
      ['embarkee','n','One who is embarkd','start recipient','C1'],
      ['embarkable','adj','Capable of being embarkd','start,possible','C1'],
      ['embarkible','adj','Able to be embarkd','start,feasible','C1'],
      ['embarkive','adj','Tending to embark','start,active','B2'],
      ['embarking','adj','Currently embarking','start,ongoing','B2'],
      ['embarked','adj','Having been embarkd','start,completed','B2'],
      ['reembark','v','To embark again','start again,repeat','B2'],
      ['unembark','v','To reverse embarking','reverse,undo','C1'],
      ['overembark','v','To embark excessively','excess,too much','C1'],
      ['underembark','v','To embark insufficiently','insufficient,inadequate','C1'],
      ['misembark','v','To embark incorrectly','wrongly,incorrectly','C1'],
      ['preembark','v','To embark beforehand','before,in advance','C1'],
      ['coembark','v','To embark together','jointly,together','C1'],
      ['reembarkation','n','The act of embarking again','re-start','C1'],
      ['overembarkation','n','Excessive embarking','excess start','C1'],
      ['navigatation','n','The act of navigating','steer process','B1'],
      ['navigatment','n','The result of navigating','steer outcome','B1'],
      ['navigatance','n','The state of navigating','steer state','B1'],
      ['navigatence','n','The quality of navigating','steer quality','B1'],
      ['navigatal','n','An act of navigating','steer event','B2'],
      ['navigater','n','One who navigates','steer person','B1'],
      ['navigator','n','One who navigates','steer agent','B1'],
      ['navigatee','n','One who is navigated','steer recipient','B2'],
      ['navigatable','adj','Capable of being navigated','steer,possible','B2'],
      ['navigatible','adj','Able to be navigated','steer,feasible','B2'],
      ['navigative','adj','Tending to navigate','steer,active','B1'],
      ['navigating','adj','Currently navigating','steer,ongoing','B1'],
      ['navigated','adj','Having been navigated','steer,completed','B1'],
      ['renavigate','v','To navigate again','steer again,repeat','B1'],
      ['unnavigate','v','To reverse navigating','reverse,undo','B2'],
      ['overnavigate','v','To navigate excessively','excess,too much','B2'],
      ['undernavigate','v','To navigate insufficiently','insufficient,inadequate','B2'],
      ['misnavigate','v','To navigate incorrectly','wrongly,incorrectly','B2'],
      ['prenavigate','v','To navigate beforehand','before,in advance','B2'],
      ['conavigate','v','To navigate together','jointly,together','B2'],
      ['renavigatation','n','The act of navigating again','re-steer','B2'],
      ['overnavigatation','n','Excessive navigating','excess steer','B2'],
      ['commutment','n','The result of commuting','travel outcome','B1'],
      ['commutance','n','The state of commuting','travel state','B1'],
      ['commutence','n','The quality of commuting','travel quality','B1'],
      ['commutal','n','An act of commuting','travel event','B2'],
      ['commutor','n','One who commutes','travel agent','B1'],
      ['commutee','n','One who is commuted','travel recipient','B2'],
      ['commutible','adj','Able to be commuted','travel,feasible','B2'],
      ['commutive','adj','Tending to commute','travel,active','B1'],
      ['commuted','adj','Having been commuted','travel,completed','B1'],
      ['recommute','v','To commute again','travel again,repeat','B1'],
      ['uncommute','v','To reverse commuting','reverse,undo','B2'],
      ['overcommute','v','To commute excessively','excess,too much','B2'],
      ['undercommute','v','To commute insufficiently','insufficient,inadequate','B2'],
      ['miscommute','v','To commute incorrectly','wrongly,incorrectly','B2'],
      ['precommute','v','To commute beforehand','before,in advance','B2'],
      ['cocommute','v','To commute together','jointly,together','B2'],
      ['recommutation','n','The act of commuting again','re-travel','B2'],
      ['overcommutation','n','Excessive commuting','excess travel','B2'],
      ['circumnavigatation','n','The act of circumnavigating','circle process','C1'],
      ['circumnavigatment','n','The result of circumnavigating','circle outcome','C1'],
      ['circumnavigatance','n','The state of circumnavigating','circle state','C1'],
      ['circumnavigatence','n','The quality of circumnavigating','circle quality','C1'],
      ['circumnavigatal','n','An act of circumnavigating','circle event','C2'],
      ['circumnavigater','n','One who circumnavigates','circle person','C1'],
      ['circumnavigator','n','One who circumnavigates','circle agent','C1'],
      ['circumnavigatee','n','One who is circumnavigated','circle recipient','C2'],
      ['circumnavigatable','adj','Capable of being circumnavigated','circle,possible','C2'],
      ['circumnavigatible','adj','Able to be circumnavigated','circle,feasible','C2'],
      ['circumnavigative','adj','Tending to circumnavigate','circle,active','C1'],
      ['circumnavigating','adj','Currently circumnavigating','circle,ongoing','C1'],
      ['circumnavigated','adj','Having been circumnavigated','circle,completed','C1'],
      ['recircumnavigate','v','To circumnavigate again','circle again,repeat','C1'],
      ['uncircumnavigate','v','To reverse circumnavigating','reverse,undo','C2'],
      ['overcircumnavigate','v','To circumnavigate excessively','excess,too much','C2'],
      ['undercircumnavigate','v','To circumnavigate insufficiently','insufficient,inadequate','C2'],
      ['miscircumnavigate','v','To circumnavigate incorrectly','wrongly,incorrectly','C2'],
      ['precircumnavigate','v','To circumnavigate beforehand','before,in advance','C2'],
      ['cocircumnavigate','v','To circumnavigate together','jointly,together','C2'],
      ['recircumnavigatation','n','The act of circumnavigating again','re-circle','C2'],
      ['overcircumnavigatation','n','Excessive circumnavigating','excess circle','C2'],
      ['disembarkment','n','The result of disembarking','alight outcome','B2'],
      ['disembarkance','n','The state of disembarking','alight state','B2'],
      ['disembarkence','n','The quality of disembarking','alight quality','B2'],
      ['disembarkal','n','An act of disembarking','alight event','C1'],
      ['disembarker','n','One who disembarks','alight person','B2'],
      ['disembarkor','n','One who disembarks','alight agent','B2'],
      ['disembarkee','n','One who is disembarkd','alight recipient','C1'],
      ['disembarkable','adj','Capable of being disembarkd','alight,possible','C1'],
      ['disembarkible','adj','Able to be disembarkd','alight,feasible','C1'],
      ['disembarkive','adj','Tending to disembark','alight,active','B2'],
      ['disembarking','adj','Currently disembarking','alight,ongoing','B2'],
      ['disembarked','adj','Having been disembarkd','alight,completed','B2'],
      ['redisembark','v','To disembark again','alight again,repeat','B2'],
      ['undisembark','v','To reverse disembarking','reverse,undo','C1'],
      ['overdisembark','v','To disembark excessively','excess,too much','C1'],
      ['underdisembark','v','To disembark insufficiently','insufficient,inadequate','C1'],
      ['misdisembark','v','To disembark incorrectly','wrongly,incorrectly','C1'],
      ['predisembark','v','To disembark beforehand','before,in advance','C1'],
    ],
  },
  collocations: {}
};
