// Auto-generated vocab boost group 84
module.exports = {
  vocab: {
    family: [
      ['kinshipful','adj','Full of kinship','family ties-rich,abounding','C1'],
      ['kinshipless','adj','Without kinship','lacking,without','C1'],
      ['kinshipism','n','The ideology of kinship','family ties ideology,doctrine','C2'],
      ['kinshipist','n','A person focused on kinship','family ties specialist,advocate','C2'],
      ['kinshipise','v','To make into kinship','family ties,convert','C2'],
      ['kinshipize','v','To make or become kinship','family ties,transform','C2'],
      ['antikinship','adj','Opposed to kinship','against,opposing','C2'],
      ['nonkinship','adj','Not involving kinship','without,lacking','C1'],
      ['prekinship','n','Before kinship','preceding,prior','C2'],
      ['postkinship','n','After kinship','following,subsequent','C2'],
      ['subkinship','n','A subdivision of kinship','subset,branch','C2'],
      ['multikinship','adj','Involving many kinships','multiple,several','C2'],
      ['interkinship','adj','Between kinships','cross,between','C2'],
      ['genealogyic','adj','Of or relating to genealogy','ancestry-based,characteristic','C1'],
      ['genealogyous','adj','Full of genealogy','ancestry-filled,abundant','C2'],
      ['genealogyful','adj','Full of genealogy','ancestry-rich,abounding','C1'],
      ['genealogyless','adj','Without genealogy','lacking,without','C1'],
      ['genealogyism','n','The ideology of genealogy','ancestry ideology,doctrine','C2'],
      ['genealogyist','n','A person focused on genealogy','ancestry specialist,advocate','C2'],
      ['genealogyise','v','To make into genealogy','ancestry,convert','C2'],
      ['genealogyize','v','To make or become genealogy','ancestry,transform','C2'],
      ['antigenealogy','adj','Opposed to genealogy','against,opposing','C2'],
      ['nongenealogy','adj','Not involving genealogy','without,lacking','C1'],
      ['pregenealogy','n','Before genealogy','preceding,prior','C2'],
      ['postgenealogy','n','After genealogy','following,subsequent','C2'],
      ['subgenealogy','n','A subdivision of genealogy','subset,branch','C2'],
      ['multigenealogy','adj','Involving many genealogys','multiple,several','C2'],
      ['intergenealogy','adj','Between genealogys','cross,between','C2'],
      ['inheritanceic','adj','Of or relating to inheritance','legacy-based,characteristic','B2'],
      ['inheritanceous','adj','Full of inheritance','legacy-filled,abundant','C1'],
      ['inheritanceful','adj','Full of inheritance','legacy-rich,abounding','B2'],
      ['inheritanceless','adj','Without inheritance','lacking,without','B2'],
      ['inheritanceism','n','The ideology of inheritance','legacy ideology,doctrine','C1'],
      ['inheritanceist','n','A person focused on inheritance','legacy specialist,advocate','C1'],
      ['inheritanceise','v','To make into inheritance','legacy,convert','C1'],
      ['inheritanceize','v','To make or become inheritance','legacy,transform','C1'],
      ['antiinheritance','adj','Opposed to inheritance','against,opposing','C1'],
      ['noninheritance','adj','Not involving inheritance','without,lacking','B2'],
      ['preinheritance','n','Before inheritance','preceding,prior','C1'],
      ['postinheritance','n','After inheritance','following,subsequent','C1'],
      ['subinheritance','n','A subdivision of inheritance','subset,branch','C1'],
      ['multiinheritance','adj','Involving many inheritances','multiple,several','C1'],
      ['interinheritance','adj','Between inheritances','cross,between','C1'],
      ['breadwinneral','adj','Relating to breadwinner','provider-related,pertaining to','B2'],
      ['breadwinneric','adj','Of or relating to breadwinner','provider-based,characteristic','B2'],
      ['breadwinnerous','adj','Full of breadwinner','provider-filled,abundant','C1'],
      ['breadwinnerful','adj','Full of breadwinner','provider-rich,abounding','B2'],
      ['breadwinnerless','adj','Without breadwinner','lacking,without','B2'],
      ['breadwinnerism','n','The ideology of breadwinner','provider ideology,doctrine','C1'],
      ['breadwinnerist','n','A person focused on breadwinner','provider specialist,advocate','C1'],
      ['breadwinnerise','v','To make into breadwinner','provider,convert','C1'],
      ['breadwinnerize','v','To make or become breadwinner','provider,transform','C1'],
      ['antibreadwinner','adj','Opposed to breadwinner','against,opposing','C1'],
      ['nonbreadwinner','adj','Not involving breadwinner','without,lacking','B2'],
      ['prebreadwinner','n','Before breadwinner','preceding,prior','C1'],
      ['postbreadwinner','n','After breadwinner','following,subsequent','C1'],
      ['subbreadwinner','n','A subdivision of breadwinner','subset,branch','C1'],
      ['multibreadwinner','adj','Involving many breadwinners','multiple,several','C1'],
      ['interbreadwinner','adj','Between breadwinners','cross,between','C1'],
      ['adolescenceal','adj','Relating to adolescence','teenage years-related,pertaining to','B2'],
      ['adolescenceic','adj','Of or relating to adolescence','teenage years-based,characteristic','B2'],
      ['adolescenceous','adj','Full of adolescence','teenage years-filled,abundant','C1'],
      ['adolescenceful','adj','Full of adolescence','teenage years-rich,abounding','B2'],
      ['adolescenceless','adj','Without adolescence','lacking,without','B2'],
      ['adolescenceism','n','The ideology of adolescence','teenage years ideology,doctrine','C1'],
      ['adolescenceist','n','A person focused on adolescence','teenage years specialist,advocate','C1'],
      ['adolescenceise','v','To make into adolescence','teenage years,convert','C1'],
      ['adolescenceize','v','To make or become adolescence','teenage years,transform','C1'],
      ['antiadolescence','adj','Opposed to adolescence','against,opposing','C1'],
      ['nonadolescence','adj','Not involving adolescence','without,lacking','B2'],
      ['preadolescence','n','Before adolescence','preceding,prior','C1'],
      ['postadolescence','n','After adolescence','following,subsequent','C1'],
      ['subadolescence','n','A subdivision of adolescence','subset,branch','C1'],
      ['multiadolescence','adj','Involving many adolescences','multiple,several','C1'],
      ['interadolescence','adj','Between adolescences','cross,between','C1'],
      ['guardianic','adj','Of or relating to guardian','carer-based,characteristic','B2'],
      ['guardianous','adj','Full of guardian','carer-filled,abundant','C1'],
      ['guardianful','adj','Full of guardian','carer-rich,abounding','B2'],
      ['guardianless','adj','Without guardian','lacking,without','B2'],
      ['guardianism','n','The ideology of guardian','carer ideology,doctrine','C1'],
      ['guardianist','n','A person focused on guardian','carer specialist,advocate','C1'],
      ['guardianise','v','To make into guardian','carer,convert','C1'],
      ['guardianize','v','To make or become guardian','carer,transform','C1'],
      ['antiguardian','adj','Opposed to guardian','against,opposing','C1'],
      ['nonguardian','adj','Not involving guardian','without,lacking','B2'],
      ['preguardian','n','Before guardian','preceding,prior','C1'],
      ['postguardian','n','After guardian','following,subsequent','C1'],
      ['subguardian','n','A subdivision of guardian','subset,branch','C1'],
      ['multiguardian','adj','Involving many guardians','multiple,several','C1'],
      ['interguardian','adj','Between guardians','cross,between','C1'],
      ['foster parent','n','A person who cares for anothers child','carer,substitute parent','B2'],
      ['foster parental','adj','Relating to foster parent','carer-related,pertaining to','B2'],
      ['foster parentic','adj','Of or relating to foster parent','carer-based,characteristic','B2'],
      ['foster parentous','adj','Full of foster parent','carer-filled,abundant','C1'],
      ['foster parentful','adj','Full of foster parent','carer-rich,abounding','B2'],
      ['foster parentless','adj','Without foster parent','lacking,without','B2'],
      ['foster parentism','n','The ideology of foster parent','carer ideology,doctrine','C1'],
      ['foster parentist','n','A person focused on foster parent','carer specialist,advocate','C1'],
      ['foster parentise','v','To make into foster parent','carer,convert','C1'],
      ['foster parentize','v','To make or become foster parent','carer,transform','C1'],
      ['antifoster parent','adj','Opposed to foster parent','against,opposing','C1'],
      ['nonfoster parent','adj','Not involving foster parent','without,lacking','B2'],
      ['prefoster parent','n','Before foster parent','preceding,prior','C1'],
      ['postfoster parent','n','After foster parent','following,subsequent','C1'],
      ['subfoster parent','n','A subdivision of foster parent','subset,branch','C1'],
      ['multifoster parent','adj','Involving many foster parents','multiple,several','C1'],
      ['interfoster parent','adj','Between foster parents','cross,between','C1'],
      ['single parental','adj','Relating to single parent','lone parent-related,pertaining to','B1'],
      ['single parentic','adj','Of or relating to single parent','lone parent-based,characteristic','B1'],
      ['single parentous','adj','Full of single parent','lone parent-filled,abundant','B2'],
      ['single parentful','adj','Full of single parent','lone parent-rich,abounding','B1'],
      ['single parentless','adj','Without single parent','lacking,without','B1'],
      ['single parentism','n','The ideology of single parent','lone parent ideology,doctrine','B2'],
      ['single parentist','n','A person focused on single parent','lone parent specialist,advocate','B2'],
      ['single parentise','v','To make into single parent','lone parent,convert','B2'],
      ['single parentize','v','To make or become single parent','lone parent,transform','B2'],
      ['antisingle parent','adj','Opposed to single parent','against,opposing','B2'],
      ['nonsingle parent','adj','Not involving single parent','without,lacking','B1'],
      ['presingle parent','n','Before single parent','preceding,prior','B2'],
      ['postsingle parent','n','After single parent','following,subsequent','B2'],
      ['subsingle parent','n','A subdivision of single parent','subset,branch','B2'],
      ['multisingle parent','adj','Involving many single parents','multiple,several','B2'],
      ['intersingle parent','adj','Between single parents','cross,between','B2'],
      ['blended familyal','adj','Relating to blended family','stepfamily-related,pertaining to','B2'],
      ['blended familyic','adj','Of or relating to blended family','stepfamily-based,characteristic','B2'],
      ['blended familyous','adj','Full of blended family','stepfamily-filled,abundant','C1'],
      ['blended familyful','adj','Full of blended family','stepfamily-rich,abounding','B2'],
      ['blended familyless','adj','Without blended family','lacking,without','B2'],
      ['blended familyism','n','The ideology of blended family','stepfamily ideology,doctrine','C1'],
      ['blended familyist','n','A person focused on blended family','stepfamily specialist,advocate','C1'],
      ['blended familyise','v','To make into blended family','stepfamily,convert','C1'],
      ['blended familyize','v','To make or become blended family','stepfamily,transform','C1'],
      ['antiblended family','adj','Opposed to blended family','against,opposing','C1'],
      ['nonblended family','adj','Not involving blended family','without,lacking','B2'],
      ['preblended family','n','Before blended family','preceding,prior','C1'],
      ['postblended family','n','After blended family','following,subsequent','C1'],
      ['subblended family','n','A subdivision of blended family','subset,branch','C1'],
      ['multiblended family','adj','Involving many blended familys','multiple,several','C1'],
      ['interblended family','adj','Between blended familys','cross,between','C1'],
      ['sibling rivalryal','adj','Relating to sibling rivalry','family competition-related,pertaining to','B2'],
      ['sibling rivalryic','adj','Of or relating to sibling rivalry','family competition-based,characteristic','B2'],
      ['sibling rivalryous','adj','Full of sibling rivalry','family competition-filled,abundant','C1'],
      ['sibling rivalryful','adj','Full of sibling rivalry','family competition-rich,abounding','B2'],
      ['sibling rivalryless','adj','Without sibling rivalry','lacking,without','B2'],
      ['sibling rivalryism','n','The ideology of sibling rivalry','family competition ideology,doctrine','C1'],
      ['sibling rivalryist','n','A person focused on sibling rivalry','family competition specialist,advocate','C1'],
      ['sibling rivalryise','v','To make into sibling rivalry','family competition,convert','C1'],
      ['sibling rivalryize','v','To make or become sibling rivalry','family competition,transform','C1'],
      ['antisibling rivalry','adj','Opposed to sibling rivalry','against,opposing','C1'],
      ['nonsibling rivalry','adj','Not involving sibling rivalry','without,lacking','B2'],
      ['presibling rivalry','n','Before sibling rivalry','preceding,prior','C1'],
      ['postsibling rivalry','n','After sibling rivalry','following,subsequent','C1'],
      ['subsibling rivalry','n','A subdivision of sibling rivalry','subset,branch','C1'],
      ['multisibling rivalry','adj','Involving many sibling rivalrys','multiple,several','C1'],
      ['intersibling rivalry','adj','Between sibling rivalrys','cross,between','C1'],
      ['filiality','n','The state of being filial','offspring-related condition','C2'],
      ['infilial','adj','Not filial','not offspring-related','C2'],
      ['nonfilial','adj','Not filial','not offspring-related','C1'],
      ['semifilial','adj','Partially filial','partly offspring-related','C2'],
      ['overfilial','adj','Excessively filial','too offspring-related','C2'],
      ['ultrafilial','adj','Extremely filial','very offspring-related','C2'],
      ['neonatality','n','The state of being neonatal','newborn condition','C2'],
      ['inneonatal','adj','Not neonatal','not newborn','C2'],
      ['nonneonatal','adj','Not neonatal','not newborn','C1'],
      ['semineonatal','adj','Partially neonatal','partly newborn','C2'],
      ['overneonatal','adj','Excessively neonatal','too newborn','C2'],
      ['ultraneonatal','adj','Extremely neonatal','very newborn','C2'],
      ['formativeity','n','The state of being formative','developmental condition','C1'],
      ['informative','adj','Not formative','not developmental','C1'],
      ['nonformative','adj','Not formative','not developmental','B2'],
      ['semiformative','adj','Partially formative','partly developmental','C1'],
      ['overformative','adj','Excessively formative','too developmental','C1'],
      ['ultraformative','adj','Extremely formative','very developmental','C1'],
      ['unconditional','adj','Not subject to any conditions','absolute,total,complete','B2'],
      ['unconditionally','adv','In a unconditional manner','absolute way','B2'],
      ['unconditionalness','n','The quality of being unconditional','absolute quality','B2'],
      ['unconditionality','n','The state of being unconditional','absolute condition','C1'],
      ['ununconditional','adj','Not unconditional','not absolute','B2'],
      ['inunconditional','adj','Not unconditional','not absolute','C1'],
      ['nonunconditional','adj','Not unconditional','not absolute','B2'],
      ['semiunconditional','adj','Partially unconditional','partly absolute','C1'],
      ['overunconditional','adj','Excessively unconditional','too absolute','C1'],
      ['ultraunconditional','adj','Extremely unconditional','very absolute','C1'],
      ['overprotectively','adv','In a overprotective manner','sheltering way','B2'],
      ['overprotectiveness','n','The quality of being overprotective','sheltering quality','B2'],
      ['overprotectiveity','n','The state of being overprotective','sheltering condition','C1'],
      ['unoverprotective','adj','Not overprotective','not sheltering','B2'],
      ['inoverprotective','adj','Not overprotective','not sheltering','C1'],
      ['nonoverprotective','adj','Not overprotective','not sheltering','B2'],
      ['semioverprotective','adj','Partially overprotective','partly sheltering','C1'],
      ['overoverprotective','adj','Excessively overprotective','too sheltering','C1'],
      ['ultraoverprotective','adj','Extremely overprotective','very sheltering','C1'],
      ['permissively','adv','In a permissive manner','lenient way','B2'],
      ['permissiveness','n','The quality of being permissive','lenient quality','B2'],
      ['permissiveity','n','The state of being permissive','lenient condition','C1'],
      ['unpermissive','adj','Not permissive','not lenient','B2'],
      ['inpermissive','adj','Not permissive','not lenient','C1'],
      ['nonpermissive','adj','Not permissive','not lenient','B2'],
      ['semipermissive','adj','Partially permissive','partly lenient','C1'],
      ['overpermissive','adj','Excessively permissive','too lenient','C1'],
      ['ultrapermissive','adj','Extremely permissive','very lenient','C1'],
      ['authoritatively','adv','In a authoritative manner','confident way','B2'],
      ['authoritativeness','n','The quality of being authoritative','confident quality','B2'],
      ['authoritativeity','n','The state of being authoritative','confident condition','C1'],
      ['unauthoritative','adj','Not authoritative','not confident','B2'],
      ['inauthoritative','adj','Not authoritative','not confident','C1'],
      ['nonauthoritative','adj','Not authoritative','not confident','B2'],
      ['semiauthoritative','adj','Partially authoritative','partly confident','C1'],
      ['overauthoritative','adj','Excessively authoritative','too confident','C1'],
      ['ultraauthoritative','adj','Extremely authoritative','very confident','C1'],
      ['intergenerational','adj','Between different generations','cross-generational,multi-age','B2'],
      ['intergenerationally','adv','In a intergenerational manner','cross-generational way','B2'],
      ['intergenerationalness','n','The quality of being intergenerational','cross-generational quality','B2'],
      ['intergenerationality','n','The state of being intergenerational','cross-generational condition','C1'],
      ['unintergenerational','adj','Not intergenerational','not cross-generational','B2'],
      ['inintergenerational','adj','Not intergenerational','not cross-generational','C1'],
      ['nonintergenerational','adj','Not intergenerational','not cross-generational','B2'],
      ['semiintergenerational','adj','Partially intergenerational','partly cross-generational','C1'],
      ['overintergenerational','adj','Excessively intergenerational','too cross-generational','C1'],
      ['ultraintergenerational','adj','Extremely intergenerational','very cross-generational','C1'],
      ['consanguinityic','adj','Of or relating to consanguinity','blood relation-based,characteristic','C2'],
      ['consanguinityous','adj','Full of consanguinity','blood relation-filled,abundant','C2'],
      ['consanguinityful','adj','Full of consanguinity','blood relation-rich,abounding','C2'],
      ['consanguinityless','adj','Without consanguinity','lacking,without','C2'],
      ['consanguinityism','n','The ideology of consanguinity','blood relation ideology,doctrine','C2'],
      ['consanguinityist','n','A person focused on consanguinity','blood relation specialist,advocate','C2'],
      ['consanguinityise','v','To make into consanguinity','blood relation,convert','C2'],
      ['consanguinityize','v','To make or become consanguinity','blood relation,transform','C2'],
      ['anticonsanguinity','adj','Opposed to consanguinity','against,opposing','C2'],
      ['nonconsanguinity','adj','Not involving consanguinity','without,lacking','C2'],
      ['preconsanguinity','n','Before consanguinity','preceding,prior','C2'],
      ['postconsanguinity','n','After consanguinity','following,subsequent','C2'],
      ['subconsanguinity','n','A subdivision of consanguinity','subset,branch','C2'],
      ['multiconsanguinity','adj','Involving many consanguinitys','multiple,several','C2'],
      ['interconsanguinity','adj','Between consanguinitys','cross,between','C2'],
      ['primogenitureic','adj','Of or relating to primogeniture','birthright-based,characteristic','C2'],
      ['primogenitureous','adj','Full of primogeniture','birthright-filled,abundant','C2'],
      ['primogenitureful','adj','Full of primogeniture','birthright-rich,abounding','C2'],
      ['primogenitureless','adj','Without primogeniture','lacking,without','C2'],
      ['primogenitureism','n','The ideology of primogeniture','birthright ideology,doctrine','C2'],
      ['primogenitureist','n','A person focused on primogeniture','birthright specialist,advocate','C2'],
      ['primogenitureise','v','To make into primogeniture','birthright,convert','C2'],
      ['primogenitureize','v','To make or become primogeniture','birthright,transform','C2'],
      ['antiprimogeniture','adj','Opposed to primogeniture','against,opposing','C2'],
      ['nonprimogeniture','adj','Not involving primogeniture','without,lacking','C2'],
      ['preprimogeniture','n','Before primogeniture','preceding,prior','C2'],
      ['postprimogeniture','n','After primogeniture','following,subsequent','C2'],
      ['subprimogeniture','n','A subdivision of primogeniture','subset,branch','C2'],
      ['multiprimogeniture','adj','Involving many primogenitures','multiple,several','C2'],
      ['interprimogeniture','adj','Between primogenitures','cross,between','C2'],
    ],
  },
  collocations: {}
};
