// Auto-generated vocab boost group 42
module.exports = {
  vocab: {
    health: [
      ['inflammationism','n','The ideology of inflammation','swelling ideology,doctrine','C1'],
      ['inflammationist','n','A person focused on inflammation','swelling specialist,advocate','C1'],
      ['inflammationise','v','To make into inflammation','swelling,convert','C1'],
      ['inflammationize','v','To make or become inflammation','swelling,transform','C1'],
      ['antiinflammation','adj','Opposed to inflammation','against,opposing','C1'],
      ['noninflammation','adj','Not involving inflammation','without,lacking','B2'],
      ['preinflammation','n','Before inflammation','preceding,prior','C1'],
      ['postinflammation','n','After inflammation','following,subsequent','C1'],
      ['subinflammation','n','A subdivision of inflammation','subset,branch','C1'],
      ['multiinflammation','adj','Involving many inflammations','multiple,several','C1'],
      ['interinflammation','adj','Between inflammations','cross,between','C1'],
      ['symptomic','adj','Of or relating to symptom','sign-based,characteristic','B1'],
      ['symptomous','adj','Full of symptom','sign-filled,abundant','B2'],
      ['symptomful','adj','Full of symptom','sign-rich,abounding','B1'],
      ['symptomless','adj','Without symptom','lacking,without','B1'],
      ['symptomism','n','The ideology of symptom','sign ideology,doctrine','B2'],
      ['symptomist','n','A person focused on symptom','sign specialist,advocate','B2'],
      ['symptomise','v','To make into symptom','sign,convert','B2'],
      ['symptomize','v','To make or become symptom','sign,transform','B2'],
      ['antisymptom','adj','Opposed to symptom','against,opposing','B2'],
      ['nonsymptom','adj','Not involving symptom','without,lacking','B1'],
      ['presymptom','n','Before symptom','preceding,prior','B2'],
      ['postsymptom','n','After symptom','following,subsequent','B2'],
      ['subsymptom','n','A subdivision of symptom','subset,branch','B2'],
      ['multisymptom','adj','Involving many symptoms','multiple,several','B2'],
      ['intersymptom','adj','Between symptoms','cross,between','B2'],
      ['dosageal','adj','Relating to dosage','dose-related,pertaining to','B2'],
      ['dosageic','adj','Of or relating to dosage','dose-based,characteristic','B2'],
      ['dosageous','adj','Full of dosage','dose-filled,abundant','C1'],
      ['dosageful','adj','Full of dosage','dose-rich,abounding','B2'],
      ['dosageless','adj','Without dosage','lacking,without','B2'],
      ['dosageism','n','The ideology of dosage','dose ideology,doctrine','C1'],
      ['dosageist','n','A person focused on dosage','dose specialist,advocate','C1'],
      ['dosageise','v','To make into dosage','dose,convert','C1'],
      ['dosageize','v','To make or become dosage','dose,transform','C1'],
      ['antidosage','adj','Opposed to dosage','against,opposing','C1'],
      ['nondosage','adj','Not involving dosage','without,lacking','B2'],
      ['predosage','n','Before dosage','preceding,prior','C1'],
      ['postdosage','n','After dosage','following,subsequent','C1'],
      ['subdosage','n','A subdivision of dosage','subset,branch','C1'],
      ['multidosage','adj','Involving many dosages','multiple,several','C1'],
      ['interdosage','adj','Between dosages','cross,between','C1'],
      ['nutrient','n','A substance needed for growth and health','nourishment,sustenance,food element','B2'],
      ['nutriental','adj','Relating to nutrient','nourishment-related,pertaining to','B2'],
      ['nutrientic','adj','Of or relating to nutrient','nourishment-based,characteristic','B2'],
      ['nutrientous','adj','Full of nutrient','nourishment-filled,abundant','C1'],
      ['nutrientful','adj','Full of nutrient','nourishment-rich,abounding','B2'],
      ['nutrientless','adj','Without nutrient','lacking,without','B2'],
      ['nutrientism','n','The ideology of nutrient','nourishment ideology,doctrine','C1'],
      ['nutrientist','n','A person focused on nutrient','nourishment specialist,advocate','C1'],
      ['nutrientise','v','To make into nutrient','nourishment,convert','C1'],
      ['nutrientize','v','To make or become nutrient','nourishment,transform','C1'],
      ['antinutrient','adj','Opposed to nutrient','against,opposing','C1'],
      ['nonnutrient','adj','Not involving nutrient','without,lacking','B2'],
      ['prenutrient','n','Before nutrient','preceding,prior','C1'],
      ['postnutrient','n','After nutrient','following,subsequent','C1'],
      ['subnutrient','n','A subdivision of nutrient','subset,branch','C1'],
      ['multinutrient','adj','Involving many nutrients','multiple,several','C1'],
      ['internutrient','adj','Between nutrients','cross,between','C1'],
      ['antioxidant','n','A substance that prevents cell damage','protective compound,free radical fighter','B2'],
      ['antioxidantal','adj','Relating to antioxidant','protective compound-related,pertaining to','B2'],
      ['antioxidantic','adj','Of or relating to antioxidant','protective compound-based,characteristic','B2'],
      ['antioxidantous','adj','Full of antioxidant','protective compound-filled,abundant','C1'],
      ['antioxidantful','adj','Full of antioxidant','protective compound-rich,abounding','B2'],
      ['antioxidantless','adj','Without antioxidant','lacking,without','B2'],
      ['antioxidantism','n','The ideology of antioxidant','protective compound ideology,doctrine','C1'],
      ['antioxidantist','n','A person focused on antioxidant','protective compound specialist,advocate','C1'],
      ['antioxidantise','v','To make into antioxidant','protective compound,convert','C1'],
      ['antioxidantize','v','To make or become antioxidant','protective compound,transform','C1'],
      ['antiantioxidant','adj','Opposed to antioxidant','against,opposing','C1'],
      ['nonantioxidant','adj','Not involving antioxidant','without,lacking','B2'],
      ['preantioxidant','n','Before antioxidant','preceding,prior','C1'],
      ['postantioxidant','n','After antioxidant','following,subsequent','C1'],
      ['subantioxidant','n','A subdivision of antioxidant','subset,branch','C1'],
      ['multiantioxidant','adj','Involving many antioxidants','multiple,several','C1'],
      ['interantioxidant','adj','Between antioxidants','cross,between','C1'],
      ['holisticity','n','The state of being holistic','comprehensive condition','C1'],
      ['inholistic','adj','Not holistic','not comprehensive','C1'],
      ['nonholistic','adj','Not holistic','not comprehensive','B2'],
      ['semiholistic','adj','Partially holistic','partly comprehensive','C1'],
      ['overholistic','adj','Excessively holistic','too comprehensive','C1'],
      ['ultraholistic','adj','Extremely holistic','very comprehensive','C1'],
      ['prophylacticly','adv','In a prophylactic manner','preventive way','C1'],
      ['prophylacticness','n','The quality of being prophylactic','preventive quality','C1'],
      ['prophylacticity','n','The state of being prophylactic','preventive condition','C2'],
      ['unprophylactic','adj','Not prophylactic','not preventive','C1'],
      ['inprophylactic','adj','Not prophylactic','not preventive','C2'],
      ['nonprophylactic','adj','Not prophylactic','not preventive','C1'],
      ['semiprophylactic','adj','Partially prophylactic','partly preventive','C2'],
      ['overprophylactic','adj','Excessively prophylactic','too preventive','C2'],
      ['ultraprophylactic','adj','Extremely prophylactic','very preventive','C2'],
      ['asymptomaticity','n','The state of being asymptomatic','symptomless condition','C2'],
      ['inasymptomatic','adj','Not asymptomatic','not symptomless','C2'],
      ['nonasymptomatic','adj','Not asymptomatic','not symptomless','C1'],
      ['semiasymptomatic','adj','Partially asymptomatic','partly symptomless','C2'],
      ['overasymptomatic','adj','Excessively asymptomatic','too symptomless','C2'],
      ['ultraasymptomatic','adj','Extremely asymptomatic','very symptomless','C2'],
    ],
    environment: [
      ['conservment','n','The result of conserving','preserve outcome','B1'],
      ['conservance','n','The state of conserving','preserve state','B1'],
      ['conservence','n','The quality of conserving','preserve quality','B1'],
      ['conserval','n','An act of conserving','preserve event','B2'],
      ['conserver','n','One who conserves','preserve person','B1'],
      ['conservor','n','One who conserves','preserve agent','B1'],
      ['conservee','n','One who is conserved','preserve recipient','B2'],
      ['conservable','adj','Capable of being conserved','preserve,possible','B2'],
      ['conservible','adj','Able to be conserved','preserve,feasible','B2'],
      ['conservive','adj','Tending to conserve','preserve,active','B1'],
      ['conserving','adj','Currently conserving','preserve,ongoing','B1'],
      ['conserved','adj','Having been conserved','preserve,completed','B1'],
      ['reconserve','v','To conserve again','preserve again,repeat','B1'],
      ['unconserve','v','To reverse conserving','reverse,undo','B2'],
      ['overconserve','v','To conserve excessively','excess,too much','B2'],
      ['underconserve','v','To conserve insufficiently','insufficient,inadequate','B2'],
      ['misconserve','v','To conserve incorrectly','wrongly,incorrectly','B2'],
      ['preconserve','v','To conserve beforehand','before,in advance','B2'],
      ['coconserve','v','To conserve together','jointly,together','B2'],
      ['reconservation','n','The act of conserving again','re-preserve','B2'],
      ['overconservation','n','Excessive conserving','excess preserve','B2'],
      ['pollutation','n','The act of polluting','contaminate process','B1'],
      ['pollutment','n','The result of polluting','contaminate outcome','B1'],
      ['pollutance','n','The state of polluting','contaminate state','B1'],
      ['pollutence','n','The quality of polluting','contaminate quality','B1'],
      ['pollutal','n','An act of polluting','contaminate event','B2'],
      ['polluter','n','One who pollutes','contaminate person','B1'],
      ['pollutor','n','One who pollutes','contaminate agent','B1'],
      ['pollutee','n','One who is polluted','contaminate recipient','B2'],
      ['pollutable','adj','Capable of being polluted','contaminate,possible','B2'],
      ['pollutible','adj','Able to be polluted','contaminate,feasible','B2'],
      ['pollutive','adj','Tending to pollute','contaminate,active','B1'],
      ['polluting','adj','Currently polluting','contaminate,ongoing','B1'],
      ['polluted','adj','Having been polluted','contaminate,completed','B1'],
      ['repollute','v','To pollute again','contaminate again,repeat','B1'],
      ['unpollute','v','To reverse polluting','reverse,undo','B2'],
      ['overpollute','v','To pollute excessively','excess,too much','B2'],
      ['underpollute','v','To pollute insufficiently','insufficient,inadequate','B2'],
      ['mispollute','v','To pollute incorrectly','wrongly,incorrectly','B2'],
      ['prepollute','v','To pollute beforehand','before,in advance','B2'],
      ['copollute','v','To pollute together','jointly,together','B2'],
      ['repollutation','n','The act of polluting again','re-contaminate','B2'],
      ['overpollutation','n','Excessive polluting','excess contaminate','B2'],
      ['recyclment','n','The result of recycling','reprocess outcome','A2'],
      ['recyclance','n','The state of recycling','reprocess state','A2'],
      ['recyclence','n','The quality of recycling','reprocess quality','A2'],
      ['recyclal','n','An act of recycling','reprocess event','B1'],
      ['recyclor','n','One who recycles','reprocess agent','A2'],
      ['recyclee','n','One who is recycled','reprocess recipient','B1'],
      ['recyclible','adj','Able to be recycled','reprocess,feasible','B1'],
      ['recyclive','adj','Tending to recycle','reprocess,active','A2'],
      ['recycled','adj','Having been recycled','reprocess,completed','A2'],
      ['rerecycle','v','To recycle again','reprocess again,repeat','A2'],
      ['unrecycle','v','To reverse recycling','reverse,undo','B1'],
      ['overrecycle','v','To recycle excessively','excess,too much','B1'],
      ['underrecycle','v','To recycle insufficiently','insufficient,inadequate','B1'],
      ['misrecycle','v','To recycle incorrectly','wrongly,incorrectly','B1'],
      ['prerecycle','v','To recycle beforehand','before,in advance','B1'],
      ['corecycle','v','To recycle together','jointly,together','B1'],
      ['rerecyclation','n','The act of recycling again','re-reprocess','B1'],
      ['overrecyclation','n','Excessive recycling','excess reprocess','B1'],
      ['depletation','n','The act of depleting','exhaust process','B2'],
      ['depletment','n','The result of depleting','exhaust outcome','B2'],
      ['depletance','n','The state of depleting','exhaust state','B2'],
      ['depletence','n','The quality of depleting','exhaust quality','B2'],
      ['depletal','n','An act of depleting','exhaust event','C1'],
      ['depleter','n','One who depletes','exhaust person','B2'],
      ['depletor','n','One who depletes','exhaust agent','B2'],
      ['depletee','n','One who is depleted','exhaust recipient','C1'],
      ['depletable','adj','Capable of being depleted','exhaust,possible','C1'],
      ['depletible','adj','Able to be depleted','exhaust,feasible','C1'],
      ['depletive','adj','Tending to deplete','exhaust,active','B2'],
      ['depleting','adj','Currently depleting','exhaust,ongoing','B2'],
      ['redeplete','v','To deplete again','exhaust again,repeat','B2'],
      ['undeplete','v','To reverse depleting','reverse,undo','C1'],
      ['overdeplete','v','To deplete excessively','excess,too much','C1'],
      ['underdeplete','v','To deplete insufficiently','insufficient,inadequate','C1'],
      ['misdeplete','v','To deplete incorrectly','wrongly,incorrectly','C1'],
      ['predeplete','v','To deplete beforehand','before,in advance','C1'],
      ['codeplete','v','To deplete together','jointly,together','C1'],
      ['redepletation','n','The act of depleting again','re-exhaust','C1'],
      ['overdepletation','n','Excessive depleting','excess exhaust','C1'],
      ['erodation','n','The act of eroding','wear process','B2'],
      ['erodment','n','The result of eroding','wear outcome','B2'],
      ['erodance','n','The state of eroding','wear state','B2'],
      ['erodence','n','The quality of eroding','wear quality','B2'],
      ['erodal','n','An act of eroding','wear event','C1'],
      ['eroder','n','One who erodes','wear person','B2'],
      ['erodor','n','One who erodes','wear agent','B2'],
      ['erodee','n','One who is eroded','wear recipient','C1'],
      ['erodable','adj','Capable of being eroded','wear,possible','C1'],
      ['erodible','adj','Able to be eroded','wear,feasible','C1'],
      ['erodive','adj','Tending to erode','wear,active','B2'],
      ['eroding','adj','Currently eroding','wear,ongoing','B2'],
      ['eroded','adj','Having been eroded','wear,completed','B2'],
      ['reerode','v','To erode again','wear again,repeat','B2'],
      ['unerode','v','To reverse eroding','reverse,undo','C1'],
      ['overerode','v','To erode excessively','excess,too much','C1'],
      ['undererode','v','To erode insufficiently','insufficient,inadequate','C1'],
      ['miserode','v','To erode incorrectly','wrongly,incorrectly','C1'],
      ['preerode','v','To erode beforehand','before,in advance','C1'],
      ['coerode','v','To erode together','jointly,together','C1'],
      ['reerodation','n','The act of eroding again','re-wear','C1'],
      ['overerodation','n','Excessive eroding','excess wear','C1'],
      ['deforest','v','To clear trees from an area','clear-cut,strip,denude','B2'],
      ['deforestment','n','The result of deforesting','clear-cut outcome','B2'],
      ['deforestance','n','The state of deforesting','clear-cut state','B2'],
      ['deforestence','n','The quality of deforesting','clear-cut quality','B2'],
      ['deforestal','n','An act of deforesting','clear-cut event','C1'],
      ['deforester','n','One who deforests','clear-cut person','B2'],
      ['deforestor','n','One who deforests','clear-cut agent','B2'],
      ['deforestee','n','One who is deforestd','clear-cut recipient','C1'],
      ['deforestable','adj','Capable of being deforestd','clear-cut,possible','C1'],
      ['deforestible','adj','Able to be deforestd','clear-cut,feasible','C1'],
      ['deforestive','adj','Tending to deforest','clear-cut,active','B2'],
      ['deforesting','adj','Currently deforesting','clear-cut,ongoing','B2'],
      ['deforested','adj','Having been deforestd','clear-cut,completed','B2'],
      ['redeforest','v','To deforest again','clear-cut again,repeat','B2'],
      ['undeforest','v','To reverse deforesting','reverse,undo','C1'],
      ['overdeforest','v','To deforest excessively','excess,too much','C1'],
      ['underdeforest','v','To deforest insufficiently','insufficient,inadequate','C1'],
      ['misdeforest','v','To deforest incorrectly','wrongly,incorrectly','C1'],
      ['predeforest','v','To deforest beforehand','before,in advance','C1'],
      ['codeforest','v','To deforest together','jointly,together','C1'],
      ['redeforestation','n','The act of deforesting again','re-clear-cut','C1'],
      ['overdeforestation','n','Excessive deforesting','excess clear-cut','C1'],
      ['contaminatation','n','The act of contaminating','pollute process','B2'],
      ['contaminatment','n','The result of contaminating','pollute outcome','B2'],
      ['contaminatance','n','The state of contaminating','pollute state','B2'],
      ['contaminatence','n','The quality of contaminating','pollute quality','B2'],
      ['contaminatal','n','An act of contaminating','pollute event','C1'],
      ['contaminater','n','One who contaminates','pollute person','B2'],
      ['contaminator','n','One who contaminates','pollute agent','B2'],
      ['contaminatee','n','One who is contaminated','pollute recipient','C1'],
      ['contaminatable','adj','Capable of being contaminated','pollute,possible','C1'],
      ['contaminatible','adj','Able to be contaminated','pollute,feasible','C1'],
      ['contaminative','adj','Tending to contaminate','pollute,active','B2'],
      ['contaminating','adj','Currently contaminating','pollute,ongoing','B2'],
      ['contaminated','adj','Having been contaminated','pollute,completed','B2'],
      ['recontaminate','v','To contaminate again','pollute again,repeat','B2'],
      ['uncontaminate','v','To reverse contaminating','reverse,undo','C1'],
      ['overcontaminate','v','To contaminate excessively','excess,too much','C1'],
      ['undercontaminate','v','To contaminate insufficiently','insufficient,inadequate','C1'],
      ['miscontaminate','v','To contaminate incorrectly','wrongly,incorrectly','C1'],
      ['precontaminate','v','To contaminate beforehand','before,in advance','C1'],
      ['cocontaminate','v','To contaminate together','jointly,together','C1'],
      ['recontaminatation','n','The act of contaminating again','re-pollute','C1'],
      ['overcontaminatation','n','Excessive contaminating','excess pollute','C1'],
      ['mitigatation','n','The act of mitigating','reduce process','C1'],
      ['mitigatment','n','The result of mitigating','reduce outcome','C1'],
      ['mitigatance','n','The state of mitigating','reduce state','C1'],
      ['mitigatence','n','The quality of mitigating','reduce quality','C1'],
      ['mitigatal','n','An act of mitigating','reduce event','C2'],
    ],
  },
  collocations: {}
};
