// Auto-generated vocab boost group 68
module.exports = {
  vocab: {
    psychology: [
      ['perceivance','n','The state of perceiving','notice state','B2'],
      ['perceivence','n','The quality of perceiving','notice quality','B2'],
      ['perceival','n','An act of perceiving','notice event','C1'],
      ['perceiver','n','One who perceives','notice person','B2'],
      ['perceivor','n','One who perceives','notice agent','B2'],
      ['perceivee','n','One who is perceived','notice recipient','C1'],
      ['perceivable','adj','Capable of being perceived','notice,possible','C1'],
      ['perceivible','adj','Able to be perceived','notice,feasible','C1'],
      ['perceivive','adj','Tending to perceive','notice,active','B2'],
      ['perceiving','adj','Currently perceiving','notice,ongoing','B2'],
      ['perceived','adj','Having been perceived','notice,completed','B2'],
      ['reperceive','v','To perceive again','notice again,repeat','B2'],
      ['unperceive','v','To reverse perceiving','reverse,undo','C1'],
      ['overperceive','v','To perceive excessively','excess,too much','C1'],
      ['underperceive','v','To perceive insufficiently','insufficient,inadequate','C1'],
      ['misperceive','v','To perceive incorrectly','wrongly,incorrectly','C1'],
      ['preperceive','v','To perceive beforehand','before,in advance','C1'],
      ['coperceive','v','To perceive together','jointly,together','C1'],
      ['reperceivation','n','The act of perceiving again','re-notice','C1'],
      ['overperceivation','n','Excessive perceiving','excess notice','C1'],
      ['rationalizment','n','The result of rationalizing','justify outcome','C1'],
      ['rationalizance','n','The state of rationalizing','justify state','C1'],
      ['rationalizence','n','The quality of rationalizing','justify quality','C1'],
      ['rationalizal','n','An act of rationalizing','justify event','C2'],
      ['rationalizer','n','One who rationalizes','justify person','C1'],
      ['rationalizor','n','One who rationalizes','justify agent','C1'],
      ['rationalizee','n','One who is rationalized','justify recipient','C2'],
      ['rationalizable','adj','Capable of being rationalized','justify,possible','C2'],
      ['rationalizible','adj','Able to be rationalized','justify,feasible','C2'],
      ['rationalizive','adj','Tending to rationalize','justify,active','C1'],
      ['rationalizing','adj','Currently rationalizing','justify,ongoing','C1'],
      ['rationalized','adj','Having been rationalized','justify,completed','C1'],
      ['rerationalize','v','To rationalize again','justify again,repeat','C1'],
      ['unrationalize','v','To reverse rationalizing','reverse,undo','C2'],
      ['overrationalize','v','To rationalize excessively','excess,too much','C2'],
      ['underrationalize','v','To rationalize insufficiently','insufficient,inadequate','C2'],
      ['misrationalize','v','To rationalize incorrectly','wrongly,incorrectly','C2'],
      ['prerationalize','v','To rationalize beforehand','before,in advance','C2'],
      ['corationalize','v','To rationalize together','jointly,together','C2'],
      ['rerationalization','n','The act of rationalizing again','re-justify','C2'],
      ['overrationalization','n','Excessive rationalizing','excess justify','C2'],
      ['traumatization','n','The act of traumatizing','shock process','B2'],
      ['traumatizment','n','The result of traumatizing','shock outcome','B2'],
      ['traumatizance','n','The state of traumatizing','shock state','B2'],
      ['traumatizence','n','The quality of traumatizing','shock quality','B2'],
      ['traumatizal','n','An act of traumatizing','shock event','C1'],
      ['traumatizer','n','One who traumatizes','shock person','B2'],
      ['traumatizor','n','One who traumatizes','shock agent','B2'],
      ['traumatizee','n','One who is traumatized','shock recipient','C1'],
      ['traumatizable','adj','Capable of being traumatized','shock,possible','C1'],
      ['traumatizible','adj','Able to be traumatized','shock,feasible','C1'],
      ['traumatizive','adj','Tending to traumatize','shock,active','B2'],
      ['traumatizing','adj','Currently traumatizing','shock,ongoing','B2'],
      ['traumatized','adj','Having been traumatized','shock,completed','B2'],
      ['retraumatize','v','To traumatize again','shock again,repeat','B2'],
      ['untraumatize','v','To reverse traumatizing','reverse,undo','C1'],
      ['overtraumatize','v','To traumatize excessively','excess,too much','C1'],
      ['undertraumatize','v','To traumatize insufficiently','insufficient,inadequate','C1'],
      ['mistraumatize','v','To traumatize incorrectly','wrongly,incorrectly','C1'],
      ['pretraumatize','v','To traumatize beforehand','before,in advance','C1'],
      ['cotraumatize','v','To traumatize together','jointly,together','C1'],
      ['retraumatization','n','The act of traumatizing again','re-shock','C1'],
      ['overtraumatization','n','Excessive traumatizing','excess shock','C1'],
      ['desensitize','v','To make less sensitive to stimuli','numb,accustom,harden','C1'],
      ['desensitizment','n','The result of desensitizing','numb outcome','C1'],
      ['desensitizance','n','The state of desensitizing','numb state','C1'],
      ['desensitizence','n','The quality of desensitizing','numb quality','C1'],
      ['desensitizal','n','An act of desensitizing','numb event','C2'],
      ['desensitizer','n','One who desensitizes','numb person','C1'],
      ['desensitizor','n','One who desensitizes','numb agent','C1'],
      ['desensitizee','n','One who is desensitized','numb recipient','C2'],
      ['desensitizable','adj','Capable of being desensitized','numb,possible','C2'],
      ['desensitizible','adj','Able to be desensitized','numb,feasible','C2'],
      ['desensitizive','adj','Tending to desensitize','numb,active','C1'],
      ['desensitizing','adj','Currently desensitizing','numb,ongoing','C1'],
      ['desensitized','adj','Having been desensitized','numb,completed','C1'],
      ['redesensitize','v','To desensitize again','numb again,repeat','C1'],
      ['undesensitize','v','To reverse desensitizing','reverse,undo','C2'],
      ['overdesensitize','v','To desensitize excessively','excess,too much','C2'],
      ['underdesensitize','v','To desensitize insufficiently','insufficient,inadequate','C2'],
      ['misdesensitize','v','To desensitize incorrectly','wrongly,incorrectly','C2'],
      ['predesensitize','v','To desensitize beforehand','before,in advance','C2'],
      ['codesensitize','v','To desensitize together','jointly,together','C2'],
      ['redesensitization','n','The act of desensitizing again','re-numb','C2'],
      ['overdesensitization','n','Excessive desensitizing','excess numb','C2'],
      ['empathization','n','The act of empathizing','relate process','B2'],
      ['empathizment','n','The result of empathizing','relate outcome','B2'],
      ['empathizance','n','The state of empathizing','relate state','B2'],
      ['empathizence','n','The quality of empathizing','relate quality','B2'],
      ['empathizal','n','An act of empathizing','relate event','C1'],
      ['empathizer','n','One who empathizes','relate person','B2'],
      ['empathizor','n','One who empathizes','relate agent','B2'],
      ['empathizee','n','One who is empathized','relate recipient','C1'],
      ['empathizable','adj','Capable of being empathized','relate,possible','C1'],
      ['empathizible','adj','Able to be empathized','relate,feasible','C1'],
      ['empathizive','adj','Tending to empathize','relate,active','B2'],
      ['empathizing','adj','Currently empathizing','relate,ongoing','B2'],
      ['empathized','adj','Having been empathized','relate,completed','B2'],
      ['reempathize','v','To empathize again','relate again,repeat','B2'],
      ['unempathize','v','To reverse empathizing','reverse,undo','C1'],
      ['overempathize','v','To empathize excessively','excess,too much','C1'],
      ['underempathize','v','To empathize insufficiently','insufficient,inadequate','C1'],
      ['misempathize','v','To empathize incorrectly','wrongly,incorrectly','C1'],
      ['preempathize','v','To empathize beforehand','before,in advance','C1'],
      ['coempathize','v','To empathize together','jointly,together','C1'],
      ['reempathization','n','The act of empathizing again','re-relate','C1'],
      ['overempathization','n','Excessive empathizing','excess relate','C1'],
      ['suppressation','n','The act of suppressing','restrain process','B2'],
      ['suppressment','n','The result of suppressing','restrain outcome','B2'],
      ['suppressance','n','The state of suppressing','restrain state','B2'],
      ['suppressence','n','The quality of suppressing','restrain quality','B2'],
      ['suppressal','n','An act of suppressing','restrain event','C1'],
      ['suppresser','n','One who suppresss','restrain person','B2'],
      ['suppressor','n','One who suppresss','restrain agent','B2'],
      ['suppressee','n','One who is suppressd','restrain recipient','C1'],
      ['suppressable','adj','Capable of being suppressd','restrain,possible','C1'],
      ['suppressible','adj','Able to be suppressd','restrain,feasible','C1'],
      ['suppressive','adj','Tending to suppress','restrain,active','B2'],
      ['suppressing','adj','Currently suppressing','restrain,ongoing','B2'],
      ['suppressed','adj','Having been suppressd','restrain,completed','B2'],
      ['resuppress','v','To suppress again','restrain again,repeat','B2'],
      ['unsuppress','v','To reverse suppressing','reverse,undo','C1'],
      ['oversuppress','v','To suppress excessively','excess,too much','C1'],
      ['undersuppress','v','To suppress insufficiently','insufficient,inadequate','C1'],
      ['missuppress','v','To suppress incorrectly','wrongly,incorrectly','C1'],
      ['presuppress','v','To suppress beforehand','before,in advance','C1'],
      ['cosuppress','v','To suppress together','jointly,together','C1'],
      ['resuppressation','n','The act of suppressing again','re-restrain','C1'],
      ['oversuppressation','n','Excessive suppressing','excess restrain','C1'],
      ['introspect','v','To examine ones own thoughts','self-reflect,contemplate,meditate','C1'],
      ['introspectation','n','The act of introspecting','self-reflect process','C1'],
      ['introspectment','n','The result of introspecting','self-reflect outcome','C1'],
      ['introspectance','n','The state of introspecting','self-reflect state','C1'],
      ['introspectence','n','The quality of introspecting','self-reflect quality','C1'],
      ['introspectal','n','An act of introspecting','self-reflect event','C2'],
      ['introspecter','n','One who introspects','self-reflect person','C1'],
      ['introspector','n','One who introspects','self-reflect agent','C1'],
      ['introspectee','n','One who is introspectd','self-reflect recipient','C2'],
      ['introspectable','adj','Capable of being introspectd','self-reflect,possible','C2'],
      ['introspectible','adj','Able to be introspectd','self-reflect,feasible','C2'],
      ['introspective','adj','Tending to introspect','self-reflect,active','C1'],
      ['introspecting','adj','Currently introspecting','self-reflect,ongoing','C1'],
      ['introspected','adj','Having been introspectd','self-reflect,completed','C1'],
      ['reintrospect','v','To introspect again','self-reflect again,repeat','C1'],
      ['unintrospect','v','To reverse introspecting','reverse,undo','C2'],
      ['overintrospect','v','To introspect excessively','excess,too much','C2'],
      ['underintrospect','v','To introspect insufficiently','insufficient,inadequate','C2'],
      ['misintrospect','v','To introspect incorrectly','wrongly,incorrectly','C2'],
      ['preintrospect','v','To introspect beforehand','before,in advance','C2'],
      ['cointrospect','v','To introspect together','jointly,together','C2'],
      ['reintrospectation','n','The act of introspecting again','re-self-reflect','C2'],
      ['overintrospectation','n','Excessive introspecting','excess self-reflect','C2'],
      ['sublimate','v','To channel impulses into activities','redirect,transform,channel','C2'],
      ['sublimatation','n','The act of sublimating','redirect process','C2'],
      ['sublimatment','n','The result of sublimating','redirect outcome','C2'],
      ['sublimatance','n','The state of sublimating','redirect state','C2'],
      ['sublimatence','n','The quality of sublimating','redirect quality','C2'],
      ['sublimatal','n','An act of sublimating','redirect event','C2'],
      ['sublimater','n','One who sublimates','redirect person','C2'],
      ['sublimator','n','One who sublimates','redirect agent','C2'],
      ['sublimatee','n','One who is sublimated','redirect recipient','C2'],
      ['sublimatable','adj','Capable of being sublimated','redirect,possible','C2'],
      ['sublimatible','adj','Able to be sublimated','redirect,feasible','C2'],
      ['sublimative','adj','Tending to sublimate','redirect,active','C2'],
      ['sublimating','adj','Currently sublimating','redirect,ongoing','C2'],
      ['sublimated','adj','Having been sublimated','redirect,completed','C2'],
      ['resublimate','v','To sublimate again','redirect again,repeat','C2'],
      ['unsublimate','v','To reverse sublimating','reverse,undo','C2'],
      ['oversublimate','v','To sublimate excessively','excess,too much','C2'],
      ['undersublimate','v','To sublimate insufficiently','insufficient,inadequate','C2'],
      ['missublimate','v','To sublimate incorrectly','wrongly,incorrectly','C2'],
      ['presublimate','v','To sublimate beforehand','before,in advance','C2'],
      ['cosublimate','v','To sublimate together','jointly,together','C2'],
      ['resublimatation','n','The act of sublimating again','re-redirect','C2'],
      ['oversublimatation','n','Excessive sublimating','excess redirect','C2'],
      ['cognitional','adj','Relating to cognition','thought-related,pertaining to','B2'],
      ['cognitionic','adj','Of or relating to cognition','thought-based,characteristic','B2'],
      ['cognitionous','adj','Full of cognition','thought-filled,abundant','C1'],
      ['cognitionful','adj','Full of cognition','thought-rich,abounding','B2'],
      ['cognitionless','adj','Without cognition','lacking,without','B2'],
      ['cognitionism','n','The ideology of cognition','thought ideology,doctrine','C1'],
      ['cognitionist','n','A person focused on cognition','thought specialist,advocate','C1'],
      ['cognitionise','v','To make into cognition','thought,convert','C1'],
      ['cognitionize','v','To make or become cognition','thought,transform','C1'],
      ['anticognition','adj','Opposed to cognition','against,opposing','C1'],
      ['noncognition','adj','Not involving cognition','without,lacking','B2'],
      ['precognition','n','Before cognition','preceding,prior','C1'],
      ['postcognition','n','After cognition','following,subsequent','C1'],
      ['subcognition','n','A subdivision of cognition','subset,branch','C1'],
      ['multicognition','adj','Involving many cognitions','multiple,several','C1'],
      ['intercognition','adj','Between cognitions','cross,between','C1'],
      ['resilienceic','adj','Of or relating to resilience','toughness-based,characteristic','B2'],
      ['resilienceous','adj','Full of resilience','toughness-filled,abundant','C1'],
      ['resilienceful','adj','Full of resilience','toughness-rich,abounding','B2'],
      ['resilienceless','adj','Without resilience','lacking,without','B2'],
      ['resilienceism','n','The ideology of resilience','toughness ideology,doctrine','C1'],
      ['resilienceist','n','A person focused on resilience','toughness specialist,advocate','C1'],
      ['resilienceise','v','To make into resilience','toughness,convert','C1'],
      ['resilienceize','v','To make or become resilience','toughness,transform','C1'],
      ['antiresilience','adj','Opposed to resilience','against,opposing','C1'],
      ['nonresilience','adj','Not involving resilience','without,lacking','B2'],
      ['preresilience','n','Before resilience','preceding,prior','C1'],
      ['postresilience','n','After resilience','following,subsequent','C1'],
      ['subresilience','n','A subdivision of resilience','subset,branch','C1'],
      ['multiresilience','adj','Involving many resiliences','multiple,several','C1'],
      ['interresilience','adj','Between resiliences','cross,between','C1'],
      ['neurosisal','adj','Relating to neurosis','anxiety disorder-related,pertaining to','C1'],
      ['neurosisic','adj','Of or relating to neurosis','anxiety disorder-based,characteristic','C1'],
      ['neurosisous','adj','Full of neurosis','anxiety disorder-filled,abundant','C2'],
      ['neurosisful','adj','Full of neurosis','anxiety disorder-rich,abounding','C1'],
      ['neurosisless','adj','Without neurosis','lacking,without','C1'],
      ['neurosisism','n','The ideology of neurosis','anxiety disorder ideology,doctrine','C2'],
      ['neurosisist','n','A person focused on neurosis','anxiety disorder specialist,advocate','C2'],
      ['neurosisise','v','To make into neurosis','anxiety disorder,convert','C2'],
      ['neurosisize','v','To make or become neurosis','anxiety disorder,transform','C2'],
      ['antineurosis','adj','Opposed to neurosis','against,opposing','C2'],
      ['nonneurosis','adj','Not involving neurosis','without,lacking','C1'],
      ['preneurosis','n','Before neurosis','preceding,prior','C2'],
      ['postneurosis','n','After neurosis','following,subsequent','C2'],
      ['subneurosis','n','A subdivision of neurosis','subset,branch','C2'],
      ['multineurosis','adj','Involving many neurosiss','multiple,several','C2'],
      ['interneurosis','adj','Between neurosiss','cross,between','C2'],
      ['phobiaic','adj','Of or relating to phobia','fear-based,characteristic','B2'],
      ['phobiaous','adj','Full of phobia','fear-filled,abundant','C1'],
      ['phobiaful','adj','Full of phobia','fear-rich,abounding','B2'],
      ['phobialess','adj','Without phobia','lacking,without','B2'],
      ['phobiaism','n','The ideology of phobia','fear ideology,doctrine','C1'],
      ['phobiaist','n','A person focused on phobia','fear specialist,advocate','C1'],
      ['phobiaise','v','To make into phobia','fear,convert','C1'],
      ['phobiaize','v','To make or become phobia','fear,transform','C1'],
      ['antiphobia','adj','Opposed to phobia','against,opposing','C1'],
      ['nonphobia','adj','Not involving phobia','without,lacking','B2'],
      ['prephobia','n','Before phobia','preceding,prior','C1'],
      ['postphobia','n','After phobia','following,subsequent','C1'],
      ['subphobia','n','A subdivision of phobia','subset,branch','C1'],
      ['multiphobia','adj','Involving many phobias','multiple,several','C1'],
      ['interphobia','adj','Between phobias','cross,between','C1'],
      ['empathyic','adj','Of or relating to empathy','understanding-based,characteristic','B2'],
      ['empathyous','adj','Full of empathy','understanding-filled,abundant','C1'],
      ['empathyful','adj','Full of empathy','understanding-rich,abounding','B2'],
      ['empathyless','adj','Without empathy','lacking,without','B2'],
      ['empathyism','n','The ideology of empathy','understanding ideology,doctrine','C1'],
      ['empathyist','n','A person focused on empathy','understanding specialist,advocate','C1'],
      ['empathyise','v','To make into empathy','understanding,convert','C1'],
      ['empathyize','v','To make or become empathy','understanding,transform','C1'],
      ['antiempathy','adj','Opposed to empathy','against,opposing','C1'],
      ['nonempathy','adj','Not involving empathy','without,lacking','B2'],
      ['preempathy','n','Before empathy','preceding,prior','C1'],
      ['postempathy','n','After empathy','following,subsequent','C1'],
      ['subempathy','n','A subdivision of empathy','subset,branch','C1'],
    ],
  },
  collocations: {}
};
