// Auto-generated vocab boost group 88
module.exports = {
  vocab: {
    language: [
      ['interpidgin','adj','Between pidgins','cross,between','C2'],
      ['creoleic','adj','Of or relating to creole','mixed language-based,characteristic','C1'],
      ['creoleous','adj','Full of creole','mixed language-filled,abundant','C2'],
      ['creoleful','adj','Full of creole','mixed language-rich,abounding','C1'],
      ['creoleless','adj','Without creole','lacking,without','C1'],
      ['creoleism','n','The ideology of creole','mixed language ideology,doctrine','C2'],
      ['creoleist','n','A person focused on creole','mixed language specialist,advocate','C2'],
      ['creoleise','v','To make into creole','mixed language,convert','C2'],
      ['creoleize','v','To make or become creole','mixed language,transform','C2'],
      ['anticreole','adj','Opposed to creole','against,opposing','C2'],
      ['noncreole','adj','Not involving creole','without,lacking','C1'],
      ['precreole','n','Before creole','preceding,prior','C2'],
      ['postcreole','n','After creole','following,subsequent','C2'],
      ['subcreole','n','A subdivision of creole','subset,branch','C2'],
      ['multicreole','adj','Involving many creoles','multiple,several','C2'],
      ['intercreole','adj','Between creoles','cross,between','C2'],
      ['lingua francaal','adj','Relating to lingua franca','shared language-related,pertaining to','C1'],
      ['lingua francaic','adj','Of or relating to lingua franca','shared language-based,characteristic','C1'],
      ['lingua francaous','adj','Full of lingua franca','shared language-filled,abundant','C2'],
      ['lingua francaful','adj','Full of lingua franca','shared language-rich,abounding','C1'],
      ['lingua francaless','adj','Without lingua franca','lacking,without','C1'],
      ['lingua francaism','n','The ideology of lingua franca','shared language ideology,doctrine','C2'],
      ['lingua francaist','n','A person focused on lingua franca','shared language specialist,advocate','C2'],
      ['lingua francaise','v','To make into lingua franca','shared language,convert','C2'],
      ['lingua francaize','v','To make or become lingua franca','shared language,transform','C2'],
      ['antilingua franca','adj','Opposed to lingua franca','against,opposing','C2'],
      ['nonlingua franca','adj','Not involving lingua franca','without,lacking','C1'],
      ['prelingua franca','n','Before lingua franca','preceding,prior','C2'],
      ['postlingua franca','n','After lingua franca','following,subsequent','C2'],
      ['sublingua franca','n','A subdivision of lingua franca','subset,branch','C2'],
      ['multilingua franca','adj','Involving many lingua francas','multiple,several','C2'],
      ['interlingua franca','adj','Between lingua francas','cross,between','C2'],
      ['neologismic','adj','Of or relating to neologism','new word-based,characteristic','C1'],
      ['neologismous','adj','Full of neologism','new word-filled,abundant','C2'],
      ['neologismful','adj','Full of neologism','new word-rich,abounding','C1'],
      ['neologismless','adj','Without neologism','lacking,without','C1'],
      ['neologismism','n','The ideology of neologism','new word ideology,doctrine','C2'],
      ['neologismist','n','A person focused on neologism','new word specialist,advocate','C2'],
      ['neologismise','v','To make into neologism','new word,convert','C2'],
      ['neologismize','v','To make or become neologism','new word,transform','C2'],
      ['antineologism','adj','Opposed to neologism','against,opposing','C2'],
      ['nonneologism','adj','Not involving neologism','without,lacking','C1'],
      ['preneologism','n','Before neologism','preceding,prior','C2'],
      ['postneologism','n','After neologism','following,subsequent','C2'],
      ['subneologism','n','A subdivision of neologism','subset,branch','C2'],
      ['multineologism','adj','Involving many neologisms','multiple,several','C2'],
      ['interneologism','adj','Between neologisms','cross,between','C2'],
      ['archaismal','adj','Relating to archaism','dated expression-related,pertaining to','C1'],
      ['archaismic','adj','Of or relating to archaism','dated expression-based,characteristic','C1'],
      ['archaismous','adj','Full of archaism','dated expression-filled,abundant','C2'],
      ['archaismful','adj','Full of archaism','dated expression-rich,abounding','C1'],
      ['archaismless','adj','Without archaism','lacking,without','C1'],
      ['archaismism','n','The ideology of archaism','dated expression ideology,doctrine','C2'],
      ['archaismist','n','A person focused on archaism','dated expression specialist,advocate','C2'],
      ['archaismise','v','To make into archaism','dated expression,convert','C2'],
      ['archaismize','v','To make or become archaism','dated expression,transform','C2'],
      ['antiarchaism','adj','Opposed to archaism','against,opposing','C2'],
      ['nonarchaism','adj','Not involving archaism','without,lacking','C1'],
      ['prearchaism','n','Before archaism','preceding,prior','C2'],
      ['postarchaism','n','After archaism','following,subsequent','C2'],
      ['subarchaism','n','A subdivision of archaism','subset,branch','C2'],
      ['multiarchaism','adj','Involving many archaisms','multiple,several','C2'],
      ['interarchaism','adj','Between archaisms','cross,between','C2'],
      ['onomatopoeiaic','adj','Of or relating to onomatopoeia','sound word-based,characteristic','C1'],
      ['onomatopoeiaous','adj','Full of onomatopoeia','sound word-filled,abundant','C2'],
      ['onomatopoeiaful','adj','Full of onomatopoeia','sound word-rich,abounding','C1'],
      ['onomatopoeialess','adj','Without onomatopoeia','lacking,without','C1'],
      ['onomatopoeiaism','n','The ideology of onomatopoeia','sound word ideology,doctrine','C2'],
      ['onomatopoeiaist','n','A person focused on onomatopoeia','sound word specialist,advocate','C2'],
      ['onomatopoeiaise','v','To make into onomatopoeia','sound word,convert','C2'],
      ['onomatopoeiaize','v','To make or become onomatopoeia','sound word,transform','C2'],
      ['antionomatopoeia','adj','Opposed to onomatopoeia','against,opposing','C2'],
      ['nononomatopoeia','adj','Not involving onomatopoeia','without,lacking','C1'],
      ['preonomatopoeia','n','Before onomatopoeia','preceding,prior','C2'],
      ['postonomatopoeia','n','After onomatopoeia','following,subsequent','C2'],
      ['subonomatopoeia','n','A subdivision of onomatopoeia','subset,branch','C2'],
      ['multionomatopoeia','adj','Involving many onomatopoeias','multiple,several','C2'],
      ['interonomatopoeia','adj','Between onomatopoeias','cross,between','C2'],
      ['alliteration','n','Repetition of initial consonant sounds','sound repetition,consonance','B2'],
      ['alliterational','adj','Relating to alliteration','sound repetition-related,pertaining to','B2'],
      ['alliterationic','adj','Of or relating to alliteration','sound repetition-based,characteristic','B2'],
      ['alliterationous','adj','Full of alliteration','sound repetition-filled,abundant','C1'],
      ['alliterationful','adj','Full of alliteration','sound repetition-rich,abounding','B2'],
      ['alliterationless','adj','Without alliteration','lacking,without','B2'],
      ['alliterationism','n','The ideology of alliteration','sound repetition ideology,doctrine','C1'],
      ['alliterationist','n','A person focused on alliteration','sound repetition specialist,advocate','C1'],
      ['alliterationise','v','To make into alliteration','sound repetition,convert','C1'],
      ['alliterationize','v','To make or become alliteration','sound repetition,transform','C1'],
      ['antialliteration','adj','Opposed to alliteration','against,opposing','C1'],
      ['nonalliteration','adj','Not involving alliteration','without,lacking','B2'],
      ['prealliteration','n','Before alliteration','preceding,prior','C1'],
      ['postalliteration','n','After alliteration','following,subsequent','C1'],
      ['suballiteration','n','A subdivision of alliteration','subset,branch','C1'],
      ['multialliteration','adj','Involving many alliterations','multiple,several','C1'],
      ['interalliteration','adj','Between alliterations','cross,between','C1'],
      ['metaphoric','adj','Of or relating to metaphor','comparison-based,characteristic','B2'],
      ['metaphorous','adj','Full of metaphor','comparison-filled,abundant','C1'],
      ['metaphorful','adj','Full of metaphor','comparison-rich,abounding','B2'],
      ['metaphorless','adj','Without metaphor','lacking,without','B2'],
      ['metaphorism','n','The ideology of metaphor','comparison ideology,doctrine','C1'],
      ['metaphorist','n','A person focused on metaphor','comparison specialist,advocate','C1'],
      ['metaphorise','v','To make into metaphor','comparison,convert','C1'],
      ['metaphorize','v','To make or become metaphor','comparison,transform','C1'],
      ['antimetaphor','adj','Opposed to metaphor','against,opposing','C1'],
      ['nonmetaphor','adj','Not involving metaphor','without,lacking','B2'],
      ['premetaphor','n','Before metaphor','preceding,prior','C1'],
      ['postmetaphor','n','After metaphor','following,subsequent','C1'],
      ['submetaphor','n','A subdivision of metaphor','subset,branch','C1'],
      ['multimetaphor','adj','Involving many metaphors','multiple,several','C1'],
      ['intermetaphor','adj','Between metaphors','cross,between','C1'],
      ['simileic','adj','Of or relating to simile','comparison-based,characteristic','B2'],
      ['simileous','adj','Full of simile','comparison-filled,abundant','C1'],
      ['simileful','adj','Full of simile','comparison-rich,abounding','B2'],
      ['simileless','adj','Without simile','lacking,without','B2'],
      ['simileism','n','The ideology of simile','comparison ideology,doctrine','C1'],
      ['simileist','n','A person focused on simile','comparison specialist,advocate','C1'],
      ['simileise','v','To make into simile','comparison,convert','C1'],
      ['simileize','v','To make or become simile','comparison,transform','C1'],
      ['antisimile','adj','Opposed to simile','against,opposing','C1'],
      ['nonsimile','adj','Not involving simile','without,lacking','B2'],
      ['presimile','n','Before simile','preceding,prior','C1'],
      ['postsimile','n','After simile','following,subsequent','C1'],
      ['subsimile','n','A subdivision of simile','subset,branch','C1'],
      ['multisimile','adj','Involving many similes','multiple,several','C1'],
      ['intersimile','adj','Between similes','cross,between','C1'],
      ['hyperboleic','adj','Of or relating to hyperbole','overstatement-based,characteristic','C1'],
      ['hyperboleous','adj','Full of hyperbole','overstatement-filled,abundant','C2'],
      ['hyperboleful','adj','Full of hyperbole','overstatement-rich,abounding','C1'],
      ['hyperboleless','adj','Without hyperbole','lacking,without','C1'],
      ['hyperboleism','n','The ideology of hyperbole','overstatement ideology,doctrine','C2'],
      ['hyperboleist','n','A person focused on hyperbole','overstatement specialist,advocate','C2'],
      ['hyperboleise','v','To make into hyperbole','overstatement,convert','C2'],
      ['hyperboleize','v','To make or become hyperbole','overstatement,transform','C2'],
      ['antihyperbole','adj','Opposed to hyperbole','against,opposing','C2'],
      ['nonhyperbole','adj','Not involving hyperbole','without,lacking','C1'],
      ['prehyperbole','n','Before hyperbole','preceding,prior','C2'],
      ['posthyperbole','n','After hyperbole','following,subsequent','C2'],
      ['subhyperbole','n','A subdivision of hyperbole','subset,branch','C2'],
      ['multihyperbole','adj','Involving many hyperboles','multiple,several','C2'],
      ['interhyperbole','adj','Between hyperboles','cross,between','C2'],
      ['oxymoronal','adj','Relating to oxymoron','contradiction-related,pertaining to','C1'],
      ['oxymoronic','adj','Of or relating to oxymoron','contradiction-based,characteristic','C1'],
      ['oxymoronous','adj','Full of oxymoron','contradiction-filled,abundant','C2'],
      ['oxymoronful','adj','Full of oxymoron','contradiction-rich,abounding','C1'],
      ['oxymoronless','adj','Without oxymoron','lacking,without','C1'],
      ['oxymoronism','n','The ideology of oxymoron','contradiction ideology,doctrine','C2'],
      ['oxymoronist','n','A person focused on oxymoron','contradiction specialist,advocate','C2'],
      ['oxymoronise','v','To make into oxymoron','contradiction,convert','C2'],
      ['oxymoronize','v','To make or become oxymoron','contradiction,transform','C2'],
      ['antioxymoron','adj','Opposed to oxymoron','against,opposing','C2'],
      ['nonoxymoron','adj','Not involving oxymoron','without,lacking','C1'],
      ['preoxymoron','n','Before oxymoron','preceding,prior','C2'],
      ['postoxymoron','n','After oxymoron','following,subsequent','C2'],
      ['suboxymoron','n','A subdivision of oxymoron','subset,branch','C2'],
      ['multioxymoron','adj','Involving many oxymorons','multiple,several','C2'],
      ['interoxymoron','adj','Between oxymorons','cross,between','C2'],
      ['cognateic','adj','Of or relating to cognate','related word-based,characteristic','C1'],
      ['cognateous','adj','Full of cognate','related word-filled,abundant','C2'],
      ['cognateful','adj','Full of cognate','related word-rich,abounding','C1'],
      ['cognateless','adj','Without cognate','lacking,without','C1'],
      ['cognateism','n','The ideology of cognate','related word ideology,doctrine','C2'],
      ['cognateist','n','A person focused on cognate','related word specialist,advocate','C2'],
      ['cognateise','v','To make into cognate','related word,convert','C2'],
      ['cognateize','v','To make or become cognate','related word,transform','C2'],
      ['anticognate','adj','Opposed to cognate','against,opposing','C2'],
      ['noncognate','adj','Not involving cognate','without,lacking','C1'],
      ['precognate','n','Before cognate','preceding,prior','C2'],
      ['postcognate','n','After cognate','following,subsequent','C2'],
      ['subcognate','n','A subdivision of cognate','subset,branch','C2'],
      ['multicognate','adj','Involving many cognates','multiple,several','C2'],
      ['intercognate','adj','Between cognates','cross,between','C2'],
      ['diphthongic','adj','Of or relating to diphthong','double vowel-based,characteristic','C1'],
      ['diphthongous','adj','Full of diphthong','double vowel-filled,abundant','C2'],
      ['diphthongful','adj','Full of diphthong','double vowel-rich,abounding','C1'],
      ['diphthongless','adj','Without diphthong','lacking,without','C1'],
      ['diphthongism','n','The ideology of diphthong','double vowel ideology,doctrine','C2'],
      ['diphthongist','n','A person focused on diphthong','double vowel specialist,advocate','C2'],
      ['diphthongise','v','To make into diphthong','double vowel,convert','C2'],
      ['diphthongize','v','To make or become diphthong','double vowel,transform','C2'],
      ['antidiphthong','adj','Opposed to diphthong','against,opposing','C2'],
      ['nondiphthong','adj','Not involving diphthong','without,lacking','C1'],
      ['prediphthong','n','Before diphthong','preceding,prior','C2'],
      ['postdiphthong','n','After diphthong','following,subsequent','C2'],
      ['subdiphthong','n','A subdivision of diphthong','subset,branch','C2'],
      ['multidiphthong','adj','Involving many diphthongs','multiple,several','C2'],
      ['interdiphthong','adj','Between diphthongs','cross,between','C2'],
      ['homophoneal','adj','Relating to homophone','sound-alike-related,pertaining to','B2'],
      ['homophoneic','adj','Of or relating to homophone','sound-alike-based,characteristic','B2'],
      ['homophoneous','adj','Full of homophone','sound-alike-filled,abundant','C1'],
      ['homophoneful','adj','Full of homophone','sound-alike-rich,abounding','B2'],
      ['homophoneless','adj','Without homophone','lacking,without','B2'],
      ['homophoneism','n','The ideology of homophone','sound-alike ideology,doctrine','C1'],
      ['homophoneist','n','A person focused on homophone','sound-alike specialist,advocate','C1'],
      ['homophoneise','v','To make into homophone','sound-alike,convert','C1'],
      ['homophoneize','v','To make or become homophone','sound-alike,transform','C1'],
      ['antihomophone','adj','Opposed to homophone','against,opposing','C1'],
      ['nonhomophone','adj','Not involving homophone','without,lacking','B2'],
      ['prehomophone','n','Before homophone','preceding,prior','C1'],
      ['posthomophone','n','After homophone','following,subsequent','C1'],
      ['subhomophone','n','A subdivision of homophone','subset,branch','C1'],
      ['multihomophone','adj','Involving many homophones','multiple,several','C1'],
      ['interhomophone','adj','Between homophones','cross,between','C1'],
      ['synonymic','adj','Of or relating to synonym','equivalent-based,characteristic','B1'],
      ['synonymous','adj','Full of synonym','equivalent-filled,abundant','B2'],
      ['synonymful','adj','Full of synonym','equivalent-rich,abounding','B1'],
      ['synonymless','adj','Without synonym','lacking,without','B1'],
      ['synonymism','n','The ideology of synonym','equivalent ideology,doctrine','B2'],
      ['synonymist','n','A person focused on synonym','equivalent specialist,advocate','B2'],
      ['synonymise','v','To make into synonym','equivalent,convert','B2'],
      ['synonymize','v','To make or become synonym','equivalent,transform','B2'],
      ['antisynonym','adj','Opposed to synonym','against,opposing','B2'],
      ['nonsynonym','adj','Not involving synonym','without,lacking','B1'],
      ['presynonym','n','Before synonym','preceding,prior','B2'],
      ['postsynonym','n','After synonym','following,subsequent','B2'],
      ['subsynonym','n','A subdivision of synonym','subset,branch','B2'],
      ['multisynonym','adj','Involving many synonyms','multiple,several','B2'],
      ['intersynonym','adj','Between synonyms','cross,between','B2'],
      ['antonymic','adj','Of or relating to antonym','opposite-based,characteristic','B1'],
      ['antonymous','adj','Full of antonym','opposite-filled,abundant','B2'],
      ['antonymful','adj','Full of antonym','opposite-rich,abounding','B1'],
      ['antonymless','adj','Without antonym','lacking,without','B1'],
      ['antonymism','n','The ideology of antonym','opposite ideology,doctrine','B2'],
      ['antonymist','n','A person focused on antonym','opposite specialist,advocate','B2'],
      ['antonymise','v','To make into antonym','opposite,convert','B2'],
      ['antonymize','v','To make or become antonym','opposite,transform','B2'],
      ['antiantonym','adj','Opposed to antonym','against,opposing','B2'],
      ['nonantonym','adj','Not involving antonym','without,lacking','B1'],
      ['preantonym','n','Before antonym','preceding,prior','B2'],
      ['postantonym','n','After antonym','following,subsequent','B2'],
      ['subantonym','n','A subdivision of antonym','subset,branch','B2'],
      ['multiantonym','adj','Involving many antonyms','multiple,several','B2'],
      ['interantonym','adj','Between antonyms','cross,between','B2'],
      ['collocational','adj','Relating to collocation','word combination-related,pertaining to','B2'],
      ['collocationic','adj','Of or relating to collocation','word combination-based,characteristic','B2'],
      ['collocationous','adj','Full of collocation','word combination-filled,abundant','C1'],
      ['collocationful','adj','Full of collocation','word combination-rich,abounding','B2'],
      ['collocationless','adj','Without collocation','lacking,without','B2'],
      ['collocationism','n','The ideology of collocation','word combination ideology,doctrine','C1'],
      ['collocationist','n','A person focused on collocation','word combination specialist,advocate','C1'],
      ['collocationise','v','To make into collocation','word combination,convert','C1'],
      ['collocationize','v','To make or become collocation','word combination,transform','C1'],
      ['anticollocation','adj','Opposed to collocation','against,opposing','C1'],
      ['noncollocation','adj','Not involving collocation','without,lacking','B2'],
      ['precollocation','n','Before collocation','preceding,prior','C1'],
      ['postcollocation','n','After collocation','following,subsequent','C1'],
      ['subcollocation','n','A subdivision of collocation','subset,branch','C1'],
      ['multicollocation','adj','Involving many collocations','multiple,several','C1'],
      ['intercollocation','adj','Between collocations','cross,between','C1'],
      ['pragmaticly','adv','In a pragmatic manner','practical way','C1'],
      ['pragmaticness','n','The quality of being pragmatic','practical quality','C1'],
    ],
  },
  collocations: {}
};
