// Auto-generated vocab boost group 76
module.exports = {
  vocab: {
    food: [
      ['nonherbivore','adj','Not involving herbivore','without,lacking','B2'],
      ['preherbivore','n','Before herbivore','preceding,prior','C1'],
      ['postherbivore','n','After herbivore','following,subsequent','C1'],
      ['subherbivore','n','A subdivision of herbivore','subset,branch','C1'],
      ['multiherbivore','adj','Involving many herbivores','multiple,several','C1'],
      ['interherbivore','adj','Between herbivores','cross,between','C1'],
      ['omnivore','n','An organism that eats all foods','all-eater,mixed diet organism','B2'],
      ['omnivoreal','adj','Relating to omnivore','all-eater-related,pertaining to','B2'],
      ['omnivoreic','adj','Of or relating to omnivore','all-eater-based,characteristic','B2'],
      ['omnivoreous','adj','Full of omnivore','all-eater-filled,abundant','C1'],
      ['omnivoreful','adj','Full of omnivore','all-eater-rich,abounding','B2'],
      ['omnivoreless','adj','Without omnivore','lacking,without','B2'],
      ['omnivoreism','n','The ideology of omnivore','all-eater ideology,doctrine','C1'],
      ['omnivoreist','n','A person focused on omnivore','all-eater specialist,advocate','C1'],
      ['omnivoreise','v','To make into omnivore','all-eater,convert','C1'],
      ['omnivoreize','v','To make or become omnivore','all-eater,transform','C1'],
      ['antiomnivore','adj','Opposed to omnivore','against,opposing','C1'],
      ['nonomnivore','adj','Not involving omnivore','without,lacking','B2'],
      ['preomnivore','n','Before omnivore','preceding,prior','C1'],
      ['postomnivore','n','After omnivore','following,subsequent','C1'],
      ['subomnivore','n','A subdivision of omnivore','subset,branch','C1'],
      ['multiomnivore','adj','Involving many omnivores','multiple,several','C1'],
      ['interomnivore','adj','Between omnivores','cross,between','C1'],
      ['veganal','adj','Relating to vegan','plant-based eater-related,pertaining to','B1'],
      ['veganic','adj','Of or relating to vegan','plant-based eater-based,characteristic','B1'],
      ['veganous','adj','Full of vegan','plant-based eater-filled,abundant','B2'],
      ['veganful','adj','Full of vegan','plant-based eater-rich,abounding','B1'],
      ['veganless','adj','Without vegan','lacking,without','B1'],
      ['veganism','n','The ideology of vegan','plant-based eater ideology,doctrine','B2'],
      ['veganist','n','A person focused on vegan','plant-based eater specialist,advocate','B2'],
      ['veganise','v','To make into vegan','plant-based eater,convert','B2'],
      ['veganize','v','To make or become vegan','plant-based eater,transform','B2'],
      ['antivegan','adj','Opposed to vegan','against,opposing','B2'],
      ['nonvegan','adj','Not involving vegan','without,lacking','B1'],
      ['prevegan','n','Before vegan','preceding,prior','B2'],
      ['postvegan','n','After vegan','following,subsequent','B2'],
      ['subvegan','n','A subdivision of vegan','subset,branch','B2'],
      ['multivegan','adj','Involving many vegans','multiple,several','B2'],
      ['intervegan','adj','Between vegans','cross,between','B2'],
      ['dietician','n','An expert in food and nutrition','nutritionist,food specialist','B2'],
      ['dieticianal','adj','Relating to dietician','nutritionist-related,pertaining to','B2'],
      ['dieticianic','adj','Of or relating to dietician','nutritionist-based,characteristic','B2'],
      ['dieticianous','adj','Full of dietician','nutritionist-filled,abundant','C1'],
      ['dieticianful','adj','Full of dietician','nutritionist-rich,abounding','B2'],
      ['dieticianless','adj','Without dietician','lacking,without','B2'],
      ['dieticianism','n','The ideology of dietician','nutritionist ideology,doctrine','C1'],
      ['dieticianist','n','A person focused on dietician','nutritionist specialist,advocate','C1'],
      ['dieticianise','v','To make into dietician','nutritionist,convert','C1'],
      ['dieticianize','v','To make or become dietician','nutritionist,transform','C1'],
      ['antidietician','adj','Opposed to dietician','against,opposing','C1'],
      ['nondietician','adj','Not involving dietician','without,lacking','B2'],
      ['predietician','n','Before dietician','preceding,prior','C1'],
      ['postdietician','n','After dietician','following,subsequent','C1'],
      ['subdietician','n','A subdivision of dietician','subset,branch','C1'],
      ['multidietician','adj','Involving many dieticians','multiple,several','C1'],
      ['interdietician','adj','Between dieticians','cross,between','C1'],
      ['sommelieric','adj','Of or relating to sommelier','wine expert-based,characteristic','C1'],
      ['sommelierous','adj','Full of sommelier','wine expert-filled,abundant','C2'],
      ['sommelierful','adj','Full of sommelier','wine expert-rich,abounding','C1'],
      ['sommelierless','adj','Without sommelier','lacking,without','C1'],
      ['sommelierism','n','The ideology of sommelier','wine expert ideology,doctrine','C2'],
      ['sommelierist','n','A person focused on sommelier','wine expert specialist,advocate','C2'],
      ['sommelierise','v','To make into sommelier','wine expert,convert','C2'],
      ['sommelierize','v','To make or become sommelier','wine expert,transform','C2'],
      ['antisommelier','adj','Opposed to sommelier','against,opposing','C2'],
      ['nonsommelier','adj','Not involving sommelier','without,lacking','C1'],
      ['presommelier','n','Before sommelier','preceding,prior','C2'],
      ['postsommelier','n','After sommelier','following,subsequent','C2'],
      ['subsommelier','n','A subdivision of sommelier','subset,branch','C2'],
      ['multisommelier','adj','Involving many sommeliers','multiple,several','C2'],
      ['intersommelier','adj','Between sommeliers','cross,between','C2'],
      ['confectioneryal','adj','Relating to confectionery','candy-related,pertaining to','B2'],
      ['confectioneryic','adj','Of or relating to confectionery','candy-based,characteristic','B2'],
      ['confectioneryous','adj','Full of confectionery','candy-filled,abundant','C1'],
      ['confectioneryful','adj','Full of confectionery','candy-rich,abounding','B2'],
      ['confectioneryless','adj','Without confectionery','lacking,without','B2'],
      ['confectioneryism','n','The ideology of confectionery','candy ideology,doctrine','C1'],
      ['confectioneryist','n','A person focused on confectionery','candy specialist,advocate','C1'],
      ['confectioneryise','v','To make into confectionery','candy,convert','C1'],
      ['confectioneryize','v','To make or become confectionery','candy,transform','C1'],
      ['anticonfectionery','adj','Opposed to confectionery','against,opposing','C1'],
      ['nonconfectionery','adj','Not involving confectionery','without,lacking','B2'],
      ['preconfectionery','n','Before confectionery','preceding,prior','C1'],
      ['postconfectionery','n','After confectionery','following,subsequent','C1'],
      ['subconfectionery','n','A subdivision of confectionery','subset,branch','C1'],
      ['multiconfectionery','adj','Involving many confectionerys','multiple,several','C1'],
      ['interconfectionery','adj','Between confectionerys','cross,between','C1'],
      ['provenanceic','adj','Of or relating to provenance','origin-based,characteristic','C1'],
      ['provenanceous','adj','Full of provenance','origin-filled,abundant','C2'],
      ['provenanceful','adj','Full of provenance','origin-rich,abounding','C1'],
      ['provenanceless','adj','Without provenance','lacking,without','C1'],
      ['provenanceism','n','The ideology of provenance','origin ideology,doctrine','C2'],
      ['provenanceist','n','A person focused on provenance','origin specialist,advocate','C2'],
      ['provenanceise','v','To make into provenance','origin,convert','C2'],
      ['provenanceize','v','To make or become provenance','origin,transform','C2'],
      ['antiprovenance','adj','Opposed to provenance','against,opposing','C2'],
      ['nonprovenance','adj','Not involving provenance','without,lacking','C1'],
      ['preprovenance','n','Before provenance','preceding,prior','C2'],
      ['postprovenance','n','After provenance','following,subsequent','C2'],
      ['subprovenance','n','A subdivision of provenance','subset,branch','C2'],
      ['multiprovenance','adj','Involving many provenances','multiple,several','C2'],
      ['interprovenance','adj','Between provenances','cross,between','C2'],
      ['aftertaste','n','A taste remaining after eating','residual taste,lingering flavour','B2'],
      ['aftertasteal','adj','Relating to aftertaste','residual taste-related,pertaining to','B2'],
      ['aftertasteic','adj','Of or relating to aftertaste','residual taste-based,characteristic','B2'],
      ['aftertasteous','adj','Full of aftertaste','residual taste-filled,abundant','C1'],
      ['aftertasteful','adj','Full of aftertaste','residual taste-rich,abounding','B2'],
      ['aftertasteless','adj','Without aftertaste','lacking,without','B2'],
      ['aftertasteism','n','The ideology of aftertaste','residual taste ideology,doctrine','C1'],
      ['aftertasteist','n','A person focused on aftertaste','residual taste specialist,advocate','C1'],
      ['aftertasteise','v','To make into aftertaste','residual taste,convert','C1'],
      ['aftertasteize','v','To make or become aftertaste','residual taste,transform','C1'],
      ['antiaftertaste','adj','Opposed to aftertaste','against,opposing','C1'],
      ['nonaftertaste','adj','Not involving aftertaste','without,lacking','B2'],
      ['preaftertaste','n','Before aftertaste','preceding,prior','C1'],
      ['postaftertaste','n','After aftertaste','following,subsequent','C1'],
      ['subaftertaste','n','A subdivision of aftertaste','subset,branch','C1'],
      ['multiaftertaste','adj','Involving many aftertastes','multiple,several','C1'],
      ['interaftertaste','adj','Between aftertastes','cross,between','C1'],
      ['umamiic','adj','Of or relating to umami','savoury flavour-based,characteristic','C1'],
      ['umamious','adj','Full of umami','savoury flavour-filled,abundant','C2'],
      ['umamiful','adj','Full of umami','savoury flavour-rich,abounding','C1'],
      ['umamiless','adj','Without umami','lacking,without','C1'],
      ['umamiism','n','The ideology of umami','savoury flavour ideology,doctrine','C2'],
      ['umamiist','n','A person focused on umami','savoury flavour specialist,advocate','C2'],
      ['umamiise','v','To make into umami','savoury flavour,convert','C2'],
      ['umamiize','v','To make or become umami','savoury flavour,transform','C2'],
      ['antiumami','adj','Opposed to umami','against,opposing','C2'],
      ['nonumami','adj','Not involving umami','without,lacking','C1'],
      ['preumami','n','Before umami','preceding,prior','C2'],
      ['postumami','n','After umami','following,subsequent','C2'],
      ['subumami','n','A subdivision of umami','subset,branch','C2'],
      ['multiumami','adj','Involving many umamis','multiple,several','C2'],
      ['interumami','adj','Between umamis','cross,between','C2'],
      ['palatablely','adv','In a palatable manner','tasty way','B2'],
      ['palatableness','n','The quality of being palatable','tasty quality','B2'],
      ['palatableity','n','The state of being palatable','tasty condition','C1'],
      ['inpalatable','adj','Not palatable','not tasty','C1'],
      ['nonpalatable','adj','Not palatable','not tasty','B2'],
      ['semipalatable','adj','Partially palatable','partly tasty','C1'],
      ['overpalatable','adj','Excessively palatable','too tasty','C1'],
      ['ultrapalatable','adj','Extremely palatable','very tasty','C1'],
      ['rancid','adj','Smelling or tasting unpleasant','spoiled,off,putrid','B2'],
      ['rancidly','adv','In a rancid manner','spoiled way','B2'],
      ['rancidness','n','The quality of being rancid','spoiled quality','B2'],
      ['rancidity','n','The state of being rancid','spoiled condition','C1'],
      ['unrancid','adj','Not rancid','not spoiled','B2'],
      ['inrancid','adj','Not rancid','not spoiled','C1'],
      ['nonrancid','adj','Not rancid','not spoiled','B2'],
      ['semirancid','adj','Partially rancid','partly spoiled','C1'],
      ['overrancid','adj','Excessively rancid','too spoiled','C1'],
      ['ultrarancid','adj','Extremely rancid','very spoiled','C1'],
      ['pungently','adv','In a pungent manner','sharp way','C1'],
      ['pungentness','n','The quality of being pungent','sharp quality','C1'],
      ['pungentity','n','The state of being pungent','sharp condition','C2'],
      ['unpungent','adj','Not pungent','not sharp','C1'],
      ['inpungent','adj','Not pungent','not sharp','C2'],
      ['nonpungent','adj','Not pungent','not sharp','C1'],
      ['semipungent','adj','Partially pungent','partly sharp','C2'],
      ['overpungent','adj','Excessively pungent','too sharp','C2'],
      ['ultrapungent','adj','Extremely pungent','very sharp','C2'],
      ['savourily','adv','In a savoury manner','flavourful way','B1'],
      ['savourness','n','The quality of being savoury','flavourful quality','B1'],
      ['savourity','n','The state of being savoury','flavourful condition','B2'],
      ['unsavoury','adj','Not savoury','not flavourful','B1'],
      ['insavoury','adj','Not savoury','not flavourful','B2'],
      ['nonsavoury','adj','Not savoury','not flavourful','B1'],
      ['semisavoury','adj','Partially savoury','partly flavourful','B2'],
      ['oversavoury','adj','Excessively savoury','too flavourful','B2'],
      ['ultrasavoury','adj','Extremely savoury','very flavourful','B2'],
      ['wholesomely','adv','In a wholesome manner','healthy way','B2'],
      ['wholesomeness','n','The quality of being wholesome','healthy quality','B2'],
      ['wholesomeity','n','The state of being wholesome','healthy condition','C1'],
      ['unwholesome','adj','Not wholesome','not healthy','B2'],
      ['inwholesome','adj','Not wholesome','not healthy','C1'],
      ['nonwholesome','adj','Not wholesome','not healthy','B2'],
      ['semiwholesome','adj','Partially wholesome','partly healthy','C1'],
      ['overwholesome','adj','Excessively wholesome','too healthy','C1'],
      ['ultrawholesome','adj','Extremely wholesome','very healthy','C1'],
      ['insipidly','adv','In a insipid manner','bland way','C1'],
      ['insipidness','n','The quality of being insipid','bland quality','C1'],
      ['insipidity','n','The state of being insipid','bland condition','C2'],
      ['uninsipid','adj','Not insipid','not bland','C1'],
      ['ininsipid','adj','Not insipid','not bland','C2'],
      ['noninsipid','adj','Not insipid','not bland','C1'],
      ['semiinsipid','adj','Partially insipid','partly bland','C2'],
      ['overinsipid','adj','Excessively insipid','too bland','C2'],
      ['ultrainsipid','adj','Extremely insipid','very bland','C2'],
    ],
    housing: [
      ['renovatation','n','The act of renovating','restore process','B2'],
      ['renovatment','n','The result of renovating','restore outcome','B2'],
      ['renovatance','n','The state of renovating','restore state','B2'],
      ['renovatence','n','The quality of renovating','restore quality','B2'],
      ['renovatal','n','An act of renovating','restore event','C1'],
      ['renovater','n','One who renovates','restore person','B2'],
      ['renovator','n','One who renovates','restore agent','B2'],
      ['renovatee','n','One who is renovated','restore recipient','C1'],
      ['renovatable','adj','Capable of being renovated','restore,possible','C1'],
      ['renovatible','adj','Able to be renovated','restore,feasible','C1'],
      ['renovative','adj','Tending to renovate','restore,active','B2'],
      ['renovating','adj','Currently renovating','restore,ongoing','B2'],
      ['renovated','adj','Having been renovated','restore,completed','B2'],
      ['rerenovate','v','To renovate again','restore again,repeat','B2'],
      ['unrenovate','v','To reverse renovating','reverse,undo','C1'],
      ['overrenovate','v','To renovate excessively','excess,too much','C1'],
      ['underrenovate','v','To renovate insufficiently','insufficient,inadequate','C1'],
      ['misrenovate','v','To renovate incorrectly','wrongly,incorrectly','C1'],
      ['prerenovate','v','To renovate beforehand','before,in advance','C1'],
      ['corenovate','v','To renovate together','jointly,together','C1'],
      ['rerenovatation','n','The act of renovating again','re-restore','C1'],
      ['overrenovatation','n','Excessive renovating','excess restore','C1'],
      ['demolishation','n','The act of demolishing','destroy process','B2'],
      ['demolishment','n','The result of demolishing','destroy outcome','B2'],
      ['demolishance','n','The state of demolishing','destroy state','B2'],
      ['demolishence','n','The quality of demolishing','destroy quality','B2'],
      ['demolishal','n','An act of demolishing','destroy event','C1'],
      ['demolisher','n','One who demolishs','destroy person','B2'],
      ['demolishor','n','One who demolishs','destroy agent','B2'],
      ['demolishee','n','One who is demolishd','destroy recipient','C1'],
      ['demolishable','adj','Capable of being demolishd','destroy,possible','C1'],
      ['demolishible','adj','Able to be demolishd','destroy,feasible','C1'],
      ['demolishive','adj','Tending to demolish','destroy,active','B2'],
      ['demolishing','adj','Currently demolishing','destroy,ongoing','B2'],
      ['demolished','adj','Having been demolishd','destroy,completed','B2'],
      ['redemolish','v','To demolish again','destroy again,repeat','B2'],
      ['undemolish','v','To reverse demolishing','reverse,undo','C1'],
      ['overdemolish','v','To demolish excessively','excess,too much','C1'],
      ['underdemolish','v','To demolish insufficiently','insufficient,inadequate','C1'],
      ['misdemolish','v','To demolish incorrectly','wrongly,incorrectly','C1'],
      ['predemolish','v','To demolish beforehand','before,in advance','C1'],
      ['codemolish','v','To demolish together','jointly,together','C1'],
      ['redemolishation','n','The act of demolishing again','re-destroy','C1'],
      ['overdemolishation','n','Excessive demolishing','excess destroy','C1'],
      ['insulatation','n','The act of insulating','protect process','B2'],
      ['insulatment','n','The result of insulating','protect outcome','B2'],
      ['insulatance','n','The state of insulating','protect state','B2'],
      ['insulatence','n','The quality of insulating','protect quality','B2'],
      ['insulatal','n','An act of insulating','protect event','C1'],
      ['insulater','n','One who insulates','protect person','B2'],
      ['insulator','n','One who insulates','protect agent','B2'],
      ['insulatee','n','One who is insulated','protect recipient','C1'],
      ['insulatable','adj','Capable of being insulated','protect,possible','C1'],
      ['insulatible','adj','Able to be insulated','protect,feasible','C1'],
      ['insulative','adj','Tending to insulate','protect,active','B2'],
      ['insulating','adj','Currently insulating','protect,ongoing','B2'],
      ['insulated','adj','Having been insulated','protect,completed','B2'],
      ['reinsulate','v','To insulate again','protect again,repeat','B2'],
      ['uninsulate','v','To reverse insulating','reverse,undo','C1'],
      ['overinsulate','v','To insulate excessively','excess,too much','C1'],
      ['underinsulate','v','To insulate insufficiently','insufficient,inadequate','C1'],
      ['misinsulate','v','To insulate incorrectly','wrongly,incorrectly','C1'],
    ],
  },
  collocations: {}
};
