// Auto-generated vocab boost group 83
module.exports = {
  vocab: {
    employment: [
      ['remunerationless','adj','Without remuneration','lacking,without','B2'],
      ['remunerationism','n','The ideology of remuneration','compensation ideology,doctrine','C1'],
      ['remunerationist','n','A person focused on remuneration','compensation specialist,advocate','C1'],
      ['remunerationise','v','To make into remuneration','compensation,convert','C1'],
      ['remunerationize','v','To make or become remuneration','compensation,transform','C1'],
      ['antiremuneration','adj','Opposed to remuneration','against,opposing','C1'],
      ['nonremuneration','adj','Not involving remuneration','without,lacking','B2'],
      ['preremuneration','n','Before remuneration','preceding,prior','C1'],
      ['postremuneration','n','After remuneration','following,subsequent','C1'],
      ['subremuneration','n','A subdivision of remuneration','subset,branch','C1'],
      ['multiremuneration','adj','Involving many remunerations','multiple,several','C1'],
      ['interremuneration','adj','Between remunerations','cross,between','C1'],
      ['grievanceal','adj','Relating to grievance','complaint-related,pertaining to','B2'],
      ['grievanceic','adj','Of or relating to grievance','complaint-based,characteristic','B2'],
      ['grievanceous','adj','Full of grievance','complaint-filled,abundant','C1'],
      ['grievanceful','adj','Full of grievance','complaint-rich,abounding','B2'],
      ['grievanceless','adj','Without grievance','lacking,without','B2'],
      ['grievanceism','n','The ideology of grievance','complaint ideology,doctrine','C1'],
      ['grievanceist','n','A person focused on grievance','complaint specialist,advocate','C1'],
      ['grievanceise','v','To make into grievance','complaint,convert','C1'],
      ['grievanceize','v','To make or become grievance','complaint,transform','C1'],
      ['antigrievance','adj','Opposed to grievance','against,opposing','C1'],
      ['nongrievance','adj','Not involving grievance','without,lacking','B2'],
      ['pregrievance','n','Before grievance','preceding,prior','C1'],
      ['postgrievance','n','After grievance','following,subsequent','C1'],
      ['subgrievance','n','A subdivision of grievance','subset,branch','C1'],
      ['multigrievance','adj','Involving many grievances','multiple,several','C1'],
      ['intergrievance','adj','Between grievances','cross,between','C1'],
      ['ergonomic','adj','Designed for workplace efficiency','user-friendly,comfortable,adapted','B2'],
      ['ergonomicly','adv','In a ergonomic manner','user-friendly way','B2'],
      ['ergonomicness','n','The quality of being ergonomic','user-friendly quality','B2'],
      ['ergonomicity','n','The state of being ergonomic','user-friendly condition','C1'],
      ['unergonomic','adj','Not ergonomic','not user-friendly','B2'],
      ['inergonomic','adj','Not ergonomic','not user-friendly','C1'],
      ['nonergonomic','adj','Not ergonomic','not user-friendly','B2'],
      ['semiergonomic','adj','Partially ergonomic','partly user-friendly','C1'],
      ['overergonomic','adj','Excessively ergonomic','too user-friendly','C1'],
      ['ultraergonomic','adj','Extremely ergonomic','very user-friendly','C1'],
      ['precariously','adv','In a precarious manner','insecure way','B2'],
      ['precariousness','n','The quality of being precarious','insecure quality','B2'],
      ['precariousity','n','The state of being precarious','insecure condition','C1'],
      ['unprecarious','adj','Not precarious','not insecure','B2'],
      ['inprecarious','adj','Not precarious','not insecure','C1'],
      ['nonprecarious','adj','Not precarious','not insecure','B2'],
      ['semiprecarious','adj','Partially precarious','partly insecure','C1'],
      ['overprecarious','adj','Excessively precarious','too insecure','C1'],
      ['ultraprecarious','adj','Extremely precarious','very insecure','C1'],
    ],
    family: [
      ['nurturment','n','The result of nurturing','raise outcome','B2'],
      ['nurturance','n','The state of nurturing','raise state','B2'],
      ['nurturence','n','The quality of nurturing','raise quality','B2'],
      ['nurtural','n','An act of nurturing','raise event','C1'],
      ['nurturor','n','One who nurtures','raise agent','B2'],
      ['nurturee','n','One who is nurtured','raise recipient','C1'],
      ['nurturible','adj','Able to be nurtured','raise,feasible','C1'],
      ['nurturive','adj','Tending to nurture','raise,active','B2'],
      ['nurtured','adj','Having been nurtured','raise,completed','B2'],
      ['renurture','v','To nurture again','raise again,repeat','B2'],
      ['unnurture','v','To reverse nurturing','reverse,undo','C1'],
      ['overnurture','v','To nurture excessively','excess,too much','C1'],
      ['undernurture','v','To nurture insufficiently','insufficient,inadequate','C1'],
      ['misnurture','v','To nurture incorrectly','wrongly,incorrectly','C1'],
      ['prenurture','v','To nurture beforehand','before,in advance','C1'],
      ['conurture','v','To nurture together','jointly,together','C1'],
      ['renurturation','n','The act of nurturing again','re-raise','C1'],
      ['overnurturation','n','Excessive nurturing','excess raise','C1'],
      ['bondation','n','The act of bonding','connect process','B1'],
      ['bondment','n','The result of bonding','connect outcome','B1'],
      ['bondance','n','The state of bonding','connect state','B1'],
      ['bondence','n','The quality of bonding','connect quality','B1'],
      ['bonder','n','One who bonds','connect person','B1'],
      ['bondor','n','One who bonds','connect agent','B1'],
      ['bondee','n','One who is bondd','connect recipient','B2'],
      ['bondable','adj','Capable of being bondd','connect,possible','B2'],
      ['bondible','adj','Able to be bondd','connect,feasible','B2'],
      ['bondive','adj','Tending to bond','connect,active','B1'],
      ['bonding','adj','Currently bonding','connect,ongoing','B1'],
      ['bonded','adj','Having been bondd','connect,completed','B1'],
      ['rebond','v','To bond again','connect again,repeat','B1'],
      ['unbond','v','To reverse bonding','reverse,undo','B2'],
      ['overbond','v','To bond excessively','excess,too much','B2'],
      ['underbond','v','To bond insufficiently','insufficient,inadequate','B2'],
      ['misbond','v','To bond incorrectly','wrongly,incorrectly','B2'],
      ['prebond','v','To bond beforehand','before,in advance','B2'],
      ['cobond','v','To bond together','jointly,together','B2'],
      ['rebondation','n','The act of bonding again','re-connect','B2'],
      ['overbondation','n','Excessive bonding','excess connect','B2'],
      ['reconcilation','n','The act of reconciling','reunite process','B2'],
      ['reconcilment','n','The result of reconciling','reunite outcome','B2'],
      ['reconcilance','n','The state of reconciling','reunite state','B2'],
      ['reconcilence','n','The quality of reconciling','reunite quality','B2'],
      ['reconcilal','n','An act of reconciling','reunite event','C1'],
      ['reconciler','n','One who reconciles','reunite person','B2'],
      ['reconcilor','n','One who reconciles','reunite agent','B2'],
      ['reconcilee','n','One who is reconciled','reunite recipient','C1'],
      ['reconcilable','adj','Capable of being reconciled','reunite,possible','C1'],
      ['reconcilible','adj','Able to be reconciled','reunite,feasible','C1'],
      ['reconcilive','adj','Tending to reconcile','reunite,active','B2'],
      ['reconciling','adj','Currently reconciling','reunite,ongoing','B2'],
      ['reconciled','adj','Having been reconciled','reunite,completed','B2'],
      ['rereconcile','v','To reconcile again','reunite again,repeat','B2'],
      ['unreconcile','v','To reverse reconciling','reverse,undo','C1'],
      ['overreconcile','v','To reconcile excessively','excess,too much','C1'],
      ['underreconcile','v','To reconcile insufficiently','insufficient,inadequate','C1'],
      ['misreconcile','v','To reconcile incorrectly','wrongly,incorrectly','C1'],
      ['prereconcile','v','To reconcile beforehand','before,in advance','C1'],
      ['coreconcile','v','To reconcile together','jointly,together','C1'],
      ['rereconcilation','n','The act of reconciling again','re-reunite','C1'],
      ['overreconcilation','n','Excessive reconciling','excess reunite','C1'],
      ['estrangation','n','The act of estranging','alienate process','C1'],
      ['estrangment','n','The result of estranging','alienate outcome','C1'],
      ['estrangance','n','The state of estranging','alienate state','C1'],
      ['estrangence','n','The quality of estranging','alienate quality','C1'],
      ['estrangal','n','An act of estranging','alienate event','C2'],
      ['estranger','n','One who estranges','alienate person','C1'],
      ['estrangor','n','One who estranges','alienate agent','C1'],
      ['estrangee','n','One who is estranged','alienate recipient','C2'],
      ['estrangable','adj','Capable of being estranged','alienate,possible','C2'],
      ['estrangible','adj','Able to be estranged','alienate,feasible','C2'],
      ['estrangive','adj','Tending to estrange','alienate,active','C1'],
      ['estranging','adj','Currently estranging','alienate,ongoing','C1'],
      ['reestrange','v','To estrange again','alienate again,repeat','C1'],
      ['unestrange','v','To reverse estranging','reverse,undo','C2'],
      ['overestrange','v','To estrange excessively','excess,too much','C2'],
      ['underestrange','v','To estrange insufficiently','insufficient,inadequate','C2'],
      ['misestrange','v','To estrange incorrectly','wrongly,incorrectly','C2'],
      ['preestrange','v','To estrange beforehand','before,in advance','C2'],
      ['coestrange','v','To estrange together','jointly,together','C2'],
      ['reestrangation','n','The act of estranging again','re-alienate','C2'],
      ['overestrangation','n','Excessive estranging','excess alienate','C2'],
      ['cohabitment','n','The result of cohabiting','live together outcome','B2'],
      ['cohabitance','n','The state of cohabiting','live together state','B2'],
      ['cohabitence','n','The quality of cohabiting','live together quality','B2'],
      ['cohabital','n','An act of cohabiting','live together event','C1'],
      ['cohabiter','n','One who cohabits','live together person','B2'],
      ['cohabitor','n','One who cohabits','live together agent','B2'],
      ['cohabitee','n','One who is cohabitd','live together recipient','C1'],
      ['cohabitable','adj','Capable of being cohabitd','live together,possible','C1'],
      ['cohabitible','adj','Able to be cohabitd','live together,feasible','C1'],
      ['cohabitive','adj','Tending to cohabit','live together,active','B2'],
      ['cohabiting','adj','Currently cohabiting','live together,ongoing','B2'],
      ['cohabited','adj','Having been cohabitd','live together,completed','B2'],
      ['recohabit','v','To cohabit again','live together again,repeat','B2'],
      ['uncohabit','v','To reverse cohabiting','reverse,undo','C1'],
      ['overcohabit','v','To cohabit excessively','excess,too much','C1'],
      ['undercohabit','v','To cohabit insufficiently','insufficient,inadequate','C1'],
      ['miscohabit','v','To cohabit incorrectly','wrongly,incorrectly','C1'],
      ['precohabit','v','To cohabit beforehand','before,in advance','C1'],
      ['cocohabit','v','To cohabit together','jointly,together','C1'],
      ['recohabitation','n','The act of cohabiting again','re-live together','C1'],
      ['overcohabitation','n','Excessive cohabiting','excess live together','C1'],
      ['procreatation','n','The act of procreating','reproduce process','C1'],
      ['procreatment','n','The result of procreating','reproduce outcome','C1'],
      ['procreatance','n','The state of procreating','reproduce state','C1'],
      ['procreatence','n','The quality of procreating','reproduce quality','C1'],
      ['procreatal','n','An act of procreating','reproduce event','C2'],
      ['procreater','n','One who procreates','reproduce person','C1'],
      ['procreator','n','One who procreates','reproduce agent','C1'],
      ['procreatee','n','One who is procreated','reproduce recipient','C2'],
      ['procreatable','adj','Capable of being procreated','reproduce,possible','C2'],
      ['procreatible','adj','Able to be procreated','reproduce,feasible','C2'],
      ['procreative','adj','Tending to procreate','reproduce,active','C1'],
      ['procreating','adj','Currently procreating','reproduce,ongoing','C1'],
      ['procreated','adj','Having been procreated','reproduce,completed','C1'],
      ['reprocreate','v','To procreate again','reproduce again,repeat','C1'],
      ['unprocreate','v','To reverse procreating','reverse,undo','C2'],
      ['overprocreate','v','To procreate excessively','excess,too much','C2'],
      ['underprocreate','v','To procreate insufficiently','insufficient,inadequate','C2'],
      ['misprocreate','v','To procreate incorrectly','wrongly,incorrectly','C2'],
      ['preprocreate','v','To procreate beforehand','before,in advance','C2'],
      ['coprocreate','v','To procreate together','jointly,together','C2'],
      ['reprocreatation','n','The act of procreating again','re-reproduce','C2'],
      ['overprocreatation','n','Excessive procreating','excess reproduce','C2'],
      ['matriarchality','n','The state of being matriarchal','female-dominated condition','C2'],
      ['inmatriarchal','adj','Not matriarchal','not female-dominated','C2'],
      ['nonmatriarchal','adj','Not matriarchal','not female-dominated','C1'],
      ['semimatriarchal','adj','Partially matriarchal','partly female-dominated','C2'],
      ['overmatriarchal','adj','Excessively matriarchal','too female-dominated','C2'],
      ['ultramatriarchal','adj','Extremely matriarchal','very female-dominated','C2'],
      ['nuclearly','adv','In a nuclear manner','immediate way','B2'],
      ['nuclearness','n','The quality of being nuclear','immediate quality','B2'],
      ['nuclearity','n','The state of being nuclear','immediate condition','C1'],
      ['unnuclear','adj','Not nuclear','not immediate','B2'],
      ['innuclear','adj','Not nuclear','not immediate','C1'],
      ['nonnuclear','adj','Not nuclear','not immediate','B2'],
      ['seminuclear','adj','Partially nuclear','partly immediate','C1'],
      ['overnuclear','adj','Excessively nuclear','too immediate','C1'],
      ['ultranuclear','adj','Extremely nuclear','very immediate','C1'],
      ['extended','adj','Including grandparents and relatives','larger,wider,multigenerational','B1'],
      ['extendedly','adv','In a extended manner','larger way','B1'],
      ['extendedness','n','The quality of being extended','larger quality','B1'],
      ['extendedity','n','The state of being extended','larger condition','B2'],
      ['unextended','adj','Not extended','not larger','B1'],
      ['inextended','adj','Not extended','not larger','B2'],
      ['nonextended','adj','Not extended','not larger','B1'],
      ['semiextended','adj','Partially extended','partly larger','B2'],
      ['overextended','adj','Excessively extended','too larger','B2'],
      ['ultraextended','adj','Extremely extended','very larger','B2'],
      ['dysfunctionality','n','The state of being dysfunctional','troubled condition','C1'],
      ['indysfunctional','adj','Not dysfunctional','not troubled','C1'],
      ['nondysfunctional','adj','Not dysfunctional','not troubled','B2'],
      ['semidysfunctional','adj','Partially dysfunctional','partly troubled','C1'],
      ['overdysfunctional','adj','Excessively dysfunctional','too troubled','C1'],
      ['ultradysfunctional','adj','Extremely dysfunctional','very troubled','C1'],
      ['upbringingic','adj','Of or relating to upbringing','childhood-based,characteristic','B2'],
      ['upbringingous','adj','Full of upbringing','childhood-filled,abundant','C1'],
      ['upbringingful','adj','Full of upbringing','childhood-rich,abounding','B2'],
      ['upbringingless','adj','Without upbringing','lacking,without','B2'],
      ['upbringingism','n','The ideology of upbringing','childhood ideology,doctrine','C1'],
      ['upbringingist','n','A person focused on upbringing','childhood specialist,advocate','C1'],
      ['upbringingise','v','To make into upbringing','childhood,convert','C1'],
      ['upbringingize','v','To make or become upbringing','childhood,transform','C1'],
      ['antiupbringing','adj','Opposed to upbringing','against,opposing','C1'],
      ['nonupbringing','adj','Not involving upbringing','without,lacking','B2'],
      ['preupbringing','n','Before upbringing','preceding,prior','C1'],
      ['postupbringing','n','After upbringing','following,subsequent','C1'],
      ['subupbringing','n','A subdivision of upbringing','subset,branch','C1'],
      ['multiupbringing','adj','Involving many upbringings','multiple,several','C1'],
      ['interupbringing','adj','Between upbringings','cross,between','C1'],
      ['custodyic','adj','Of or relating to custody','guardianship-based,characteristic','B2'],
      ['custodyous','adj','Full of custody','guardianship-filled,abundant','C1'],
      ['custodyful','adj','Full of custody','guardianship-rich,abounding','B2'],
      ['custodyless','adj','Without custody','lacking,without','B2'],
      ['custodyism','n','The ideology of custody','guardianship ideology,doctrine','C1'],
      ['custodyist','n','A person focused on custody','guardianship specialist,advocate','C1'],
      ['custodyise','v','To make into custody','guardianship,convert','C1'],
      ['custodyize','v','To make or become custody','guardianship,transform','C1'],
      ['anticustody','adj','Opposed to custody','against,opposing','C1'],
      ['noncustody','adj','Not involving custody','without,lacking','B2'],
      ['precustody','n','Before custody','preceding,prior','C1'],
      ['postcustody','n','After custody','following,subsequent','C1'],
      ['subcustody','n','A subdivision of custody','subset,branch','C1'],
      ['multicustody','adj','Involving many custodys','multiple,several','C1'],
      ['intercustody','adj','Between custodys','cross,between','C1'],
      ['siblingic','adj','Of or relating to sibling','brother-based,characteristic','B1'],
      ['siblingous','adj','Full of sibling','brother-filled,abundant','B2'],
      ['siblingful','adj','Full of sibling','brother-rich,abounding','B1'],
      ['siblingless','adj','Without sibling','lacking,without','B1'],
      ['siblingism','n','The ideology of sibling','brother ideology,doctrine','B2'],
      ['siblingist','n','A person focused on sibling','brother specialist,advocate','B2'],
      ['siblingise','v','To make into sibling','brother,convert','B2'],
      ['siblingize','v','To make or become sibling','brother,transform','B2'],
      ['antisibling','adj','Opposed to sibling','against,opposing','B2'],
      ['nonsibling','adj','Not involving sibling','without,lacking','B1'],
      ['presibling','n','Before sibling','preceding,prior','B2'],
      ['postsibling','n','After sibling','following,subsequent','B2'],
      ['subsibling','n','A subdivision of sibling','subset,branch','B2'],
      ['multisibling','adj','Involving many siblings','multiple,several','B2'],
      ['intersibling','adj','Between siblings','cross,between','B2'],
      ['kinshipic','adj','Of or relating to kinship','family ties-based,characteristic','C1'],
      ['kinshipous','adj','Full of kinship','family ties-filled,abundant','C2'],
    ],
  },
  collocations: {}
};
