// Auto-generated vocab boost group 57
module.exports = {
  vocab: {
    crime: [
      ['extraditation','n','The act of extraditing','transfer process','C1'],
      ['extraditment','n','The result of extraditing','transfer outcome','C1'],
      ['extraditance','n','The state of extraditing','transfer state','C1'],
      ['extraditence','n','The quality of extraditing','transfer quality','C1'],
      ['extradital','n','An act of extraditing','transfer event','C2'],
      ['extraditer','n','One who extradites','transfer person','C1'],
      ['extraditor','n','One who extradites','transfer agent','C1'],
      ['extraditee','n','One who is extradited','transfer recipient','C2'],
      ['extraditable','adj','Capable of being extradited','transfer,possible','C2'],
      ['extraditible','adj','Able to be extradited','transfer,feasible','C2'],
      ['extraditive','adj','Tending to extradite','transfer,active','C1'],
      ['extraditing','adj','Currently extraditing','transfer,ongoing','C1'],
      ['extradited','adj','Having been extradited','transfer,completed','C1'],
      ['reextradite','v','To extradite again','transfer again,repeat','C1'],
      ['unextradite','v','To reverse extraditing','reverse,undo','C2'],
      ['overextradite','v','To extradite excessively','excess,too much','C2'],
      ['underextradite','v','To extradite insufficiently','insufficient,inadequate','C2'],
      ['misextradite','v','To extradite incorrectly','wrongly,incorrectly','C2'],
      ['preextradite','v','To extradite beforehand','before,in advance','C2'],
      ['coextradite','v','To extradite together','jointly,together','C2'],
      ['reextraditation','n','The act of extraditing again','re-transfer','C2'],
      ['overextraditation','n','Excessive extraditing','excess transfer','C2'],
      ['apprehend','v','To arrest or detain someone','arrest,capture,seize','C1'],
      ['apprehendation','n','The act of apprehending','arrest process','C1'],
      ['apprehendment','n','The result of apprehending','arrest outcome','C1'],
      ['apprehendance','n','The state of apprehending','arrest state','C1'],
      ['apprehendence','n','The quality of apprehending','arrest quality','C1'],
      ['apprehendal','n','An act of apprehending','arrest event','C2'],
      ['apprehender','n','One who apprehends','arrest person','C1'],
      ['apprehendor','n','One who apprehends','arrest agent','C1'],
      ['apprehendee','n','One who is apprehendd','arrest recipient','C2'],
      ['apprehendable','adj','Capable of being apprehendd','arrest,possible','C2'],
      ['apprehendible','adj','Able to be apprehendd','arrest,feasible','C2'],
      ['apprehendive','adj','Tending to apprehend','arrest,active','C1'],
      ['apprehending','adj','Currently apprehending','arrest,ongoing','C1'],
      ['apprehended','adj','Having been apprehendd','arrest,completed','C1'],
      ['reapprehend','v','To apprehend again','arrest again,repeat','C1'],
      ['unapprehend','v','To reverse apprehending','reverse,undo','C2'],
      ['overapprehend','v','To apprehend excessively','excess,too much','C2'],
      ['underapprehend','v','To apprehend insufficiently','insufficient,inadequate','C2'],
      ['misapprehend','v','To apprehend incorrectly','wrongly,incorrectly','C2'],
      ['preapprehend','v','To apprehend beforehand','before,in advance','C2'],
      ['coapprehend','v','To apprehend together','jointly,together','C2'],
      ['reapprehendation','n','The act of apprehending again','re-arrest','C2'],
      ['overapprehendation','n','Excessive apprehending','excess arrest','C2'],
      ['embezzle','v','To steal money entrusted to ones care','misappropriate,steal,defraud','C1'],
      ['embezzlation','n','The act of embezzling','misappropriate process','C1'],
      ['embezzlment','n','The result of embezzling','misappropriate outcome','C1'],
      ['embezzlance','n','The state of embezzling','misappropriate state','C1'],
      ['embezzlence','n','The quality of embezzling','misappropriate quality','C1'],
      ['embezzlal','n','An act of embezzling','misappropriate event','C2'],
      ['embezzler','n','One who embezzles','misappropriate person','C1'],
      ['embezzlor','n','One who embezzles','misappropriate agent','C1'],
      ['embezzlee','n','One who is embezzled','misappropriate recipient','C2'],
      ['embezzlable','adj','Capable of being embezzled','misappropriate,possible','C2'],
      ['embezzlible','adj','Able to be embezzled','misappropriate,feasible','C2'],
      ['embezzlive','adj','Tending to embezzle','misappropriate,active','C1'],
      ['embezzling','adj','Currently embezzling','misappropriate,ongoing','C1'],
      ['embezzled','adj','Having been embezzled','misappropriate,completed','C1'],
      ['reembezzle','v','To embezzle again','misappropriate again,repeat','C1'],
      ['unembezzle','v','To reverse embezzling','reverse,undo','C2'],
      ['overembezzle','v','To embezzle excessively','excess,too much','C2'],
      ['underembezzle','v','To embezzle insufficiently','insufficient,inadequate','C2'],
      ['misembezzle','v','To embezzle incorrectly','wrongly,incorrectly','C2'],
      ['preembezzle','v','To embezzle beforehand','before,in advance','C2'],
      ['coembezzle','v','To embezzle together','jointly,together','C2'],
      ['reembezzlation','n','The act of embezzling again','re-misappropriate','C2'],
      ['overembezzlation','n','Excessive embezzling','excess misappropriate','C2'],
      ['perpetrate','v','To carry out a harmful or illegal act','commit,execute,carry out','C1'],
      ['perpetratation','n','The act of perpetrating','commit process','C1'],
      ['perpetratment','n','The result of perpetrating','commit outcome','C1'],
      ['perpetratance','n','The state of perpetrating','commit state','C1'],
      ['perpetratence','n','The quality of perpetrating','commit quality','C1'],
      ['perpetratal','n','An act of perpetrating','commit event','C2'],
      ['perpetrater','n','One who perpetrates','commit person','C1'],
      ['perpetratee','n','One who is perpetrated','commit recipient','C2'],
      ['perpetratable','adj','Capable of being perpetrated','commit,possible','C2'],
      ['perpetratible','adj','Able to be perpetrated','commit,feasible','C2'],
      ['perpetrative','adj','Tending to perpetrate','commit,active','C1'],
      ['perpetrating','adj','Currently perpetrating','commit,ongoing','C1'],
      ['perpetrated','adj','Having been perpetrated','commit,completed','C1'],
      ['reperpetrate','v','To perpetrate again','commit again,repeat','C1'],
      ['unperpetrate','v','To reverse perpetrating','reverse,undo','C2'],
      ['overperpetrate','v','To perpetrate excessively','excess,too much','C2'],
      ['underperpetrate','v','To perpetrate insufficiently','insufficient,inadequate','C2'],
      ['misperpetrate','v','To perpetrate incorrectly','wrongly,incorrectly','C2'],
      ['preperpetrate','v','To perpetrate beforehand','before,in advance','C2'],
      ['coperpetrate','v','To perpetrate together','jointly,together','C2'],
      ['reperpetratation','n','The act of perpetrating again','re-commit','C2'],
      ['overperpetratation','n','Excessive perpetrating','excess commit','C2'],
      ['exoneratment','n','The result of exonerating','acquit outcome','C1'],
      ['exoneratance','n','The state of exonerating','acquit state','C1'],
      ['exoneratence','n','The quality of exonerating','acquit quality','C1'],
      ['exoneratal','n','An act of exonerating','acquit event','C2'],
      ['exonerator','n','One who exonerates','acquit agent','C1'],
      ['exoneratee','n','One who is exonerated','acquit recipient','C2'],
      ['exoneratible','adj','Able to be exonerated','acquit,feasible','C2'],
      ['exonerative','adj','Tending to exonerate','acquit,active','C1'],
      ['exonerated','adj','Having been exonerated','acquit,completed','C1'],
      ['reexonerate','v','To exonerate again','acquit again,repeat','C1'],
      ['unexonerate','v','To reverse exonerating','reverse,undo','C2'],
      ['overexonerate','v','To exonerate excessively','excess,too much','C2'],
      ['underexonerate','v','To exonerate insufficiently','insufficient,inadequate','C2'],
      ['misexonerate','v','To exonerate incorrectly','wrongly,incorrectly','C2'],
      ['preexonerate','v','To exonerate beforehand','before,in advance','C2'],
      ['coexonerate','v','To exonerate together','jointly,together','C2'],
      ['reexoneratation','n','The act of exonerating again','re-acquit','C2'],
      ['overexoneratation','n','Excessive exonerating','excess acquit','C2'],
      ['recidivate','v','To return to criminal behaviour','reoffend,relapse,backslide','C2'],
      ['recidivatation','n','The act of recidivating','reoffend process','C2'],
      ['recidivatment','n','The result of recidivating','reoffend outcome','C2'],
      ['recidivatance','n','The state of recidivating','reoffend state','C2'],
      ['recidivatence','n','The quality of recidivating','reoffend quality','C2'],
      ['recidivatal','n','An act of recidivating','reoffend event','C2'],
      ['recidivater','n','One who recidivates','reoffend person','C2'],
      ['recidivator','n','One who recidivates','reoffend agent','C2'],
      ['recidivatee','n','One who is recidivated','reoffend recipient','C2'],
      ['recidivatable','adj','Capable of being recidivated','reoffend,possible','C2'],
      ['recidivatible','adj','Able to be recidivated','reoffend,feasible','C2'],
      ['recidivative','adj','Tending to recidivate','reoffend,active','C2'],
      ['recidivating','adj','Currently recidivating','reoffend,ongoing','C2'],
      ['recidivated','adj','Having been recidivated','reoffend,completed','C2'],
      ['rerecidivate','v','To recidivate again','reoffend again,repeat','C2'],
      ['unrecidivate','v','To reverse recidivating','reverse,undo','C2'],
      ['overrecidivate','v','To recidivate excessively','excess,too much','C2'],
      ['underrecidivate','v','To recidivate insufficiently','insufficient,inadequate','C2'],
      ['misrecidivate','v','To recidivate incorrectly','wrongly,incorrectly','C2'],
      ['prerecidivate','v','To recidivate beforehand','before,in advance','C2'],
      ['corecidivate','v','To recidivate together','jointly,together','C2'],
      ['rerecidivatation','n','The act of recidivating again','re-reoffend','C2'],
      ['overrecidivatation','n','Excessive recidivating','excess reoffend','C2'],
      ['forensicity','n','The state of being forensic','investigative condition','C1'],
      ['inforensic','adj','Not forensic','not investigative','C1'],
      ['nonforensic','adj','Not forensic','not investigative','B2'],
      ['semiforensic','adj','Partially forensic','partly investigative','C1'],
      ['overforensic','adj','Excessively forensic','too investigative','C1'],
      ['ultraforensic','adj','Extremely forensic','very investigative','C1'],
      ['punitively','adv','In a punitive manner','penal way','C1'],
      ['punitiveness','n','The quality of being punitive','penal quality','C1'],
      ['punitiveity','n','The state of being punitive','penal condition','C2'],
      ['unpunitive','adj','Not punitive','not penal','C1'],
      ['inpunitive','adj','Not punitive','not penal','C2'],
      ['nonpunitive','adj','Not punitive','not penal','C1'],
      ['semipunitive','adj','Partially punitive','partly penal','C2'],
      ['overpunitive','adj','Excessively punitive','too penal','C2'],
      ['ultrapunitive','adj','Extremely punitive','very penal','C2'],
      ['custodial','adj','Relating to imprisonment','prison,incarceration,jail','C1'],
      ['custodially','adv','In a custodial manner','prison way','C1'],
      ['custodialness','n','The quality of being custodial','prison quality','C1'],
      ['custodiality','n','The state of being custodial','prison condition','C2'],
      ['uncustodial','adj','Not custodial','not prison','C1'],
      ['incustodial','adj','Not custodial','not prison','C2'],
      ['noncustodial','adj','Not custodial','not prison','C1'],
      ['semicustodial','adj','Partially custodial','partly prison','C2'],
      ['overcustodial','adj','Excessively custodial','too prison','C2'],
      ['ultracustodial','adj','Extremely custodial','very prison','C2'],
      ['litigiously','adv','In a litigious manner','contentious way','C1'],
      ['litigiousness','n','The quality of being litigious','contentious quality','C1'],
      ['litigiousity','n','The state of being litigious','contentious condition','C2'],
      ['unlitigious','adj','Not litigious','not contentious','C1'],
      ['inlitigious','adj','Not litigious','not contentious','C2'],
      ['nonlitigious','adj','Not litigious','not contentious','C1'],
      ['semilitigious','adj','Partially litigious','partly contentious','C2'],
      ['overlitigious','adj','Excessively litigious','too contentious','C2'],
      ['ultralitigious','adj','Extremely litigious','very contentious','C2'],
      ['mitigatingly','adv','In a mitigating manner','extenuating way','C1'],
      ['mitigatingness','n','The quality of being mitigating','extenuating quality','C1'],
      ['mitigatingity','n','The state of being mitigating','extenuating condition','C2'],
      ['unmitigating','adj','Not mitigating','not extenuating','C1'],
      ['inmitigating','adj','Not mitigating','not extenuating','C2'],
      ['nonmitigating','adj','Not mitigating','not extenuating','C1'],
      ['semimitigating','adj','Partially mitigating','partly extenuating','C2'],
      ['overmitigating','adj','Excessively mitigating','too extenuating','C2'],
      ['ultramitigating','adj','Extremely mitigating','very extenuating','C2'],
      ['deterrental','adj','Relating to deterrent','prevention-related,pertaining to','B2'],
      ['deterrentic','adj','Of or relating to deterrent','prevention-based,characteristic','B2'],
      ['deterrentous','adj','Full of deterrent','prevention-filled,abundant','C1'],
      ['deterrentful','adj','Full of deterrent','prevention-rich,abounding','B2'],
      ['deterrentless','adj','Without deterrent','lacking,without','B2'],
      ['deterrentism','n','The ideology of deterrent','prevention ideology,doctrine','C1'],
      ['deterrentist','n','A person focused on deterrent','prevention specialist,advocate','C1'],
      ['deterrentise','v','To make into deterrent','prevention,convert','C1'],
      ['deterrentize','v','To make or become deterrent','prevention,transform','C1'],
      ['antideterrent','adj','Opposed to deterrent','against,opposing','C1'],
      ['nondeterrent','adj','Not involving deterrent','without,lacking','B2'],
      ['predeterrent','n','Before deterrent','preceding,prior','C1'],
      ['postdeterrent','n','After deterrent','following,subsequent','C1'],
      ['subdeterrent','n','A subdivision of deterrent','subset,branch','C1'],
      ['multideterrent','adj','Involving many deterrents','multiple,several','C1'],
      ['interdeterrent','adj','Between deterrents','cross,between','C1'],
      ['recidivismic','adj','Of or relating to recidivism','reoffending-based,characteristic','C1'],
      ['recidivismous','adj','Full of recidivism','reoffending-filled,abundant','C2'],
      ['recidivismful','adj','Full of recidivism','reoffending-rich,abounding','C1'],
      ['recidivismless','adj','Without recidivism','lacking,without','C1'],
      ['recidivismism','n','The ideology of recidivism','reoffending ideology,doctrine','C2'],
      ['recidivismist','n','A person focused on recidivism','reoffending specialist,advocate','C2'],
      ['recidivismise','v','To make into recidivism','reoffending,convert','C2'],
      ['recidivismize','v','To make or become recidivism','reoffending,transform','C2'],
      ['antirecidivism','adj','Opposed to recidivism','against,opposing','C2'],
      ['nonrecidivism','adj','Not involving recidivism','without,lacking','C1'],
      ['prerecidivism','n','Before recidivism','preceding,prior','C2'],
      ['postrecidivism','n','After recidivism','following,subsequent','C2'],
      ['subrecidivism','n','A subdivision of recidivism','subset,branch','C2'],
      ['multirecidivism','adj','Involving many recidivisms','multiple,several','C2'],
      ['interrecidivism','adj','Between recidivisms','cross,between','C2'],
      ['paroleic','adj','Of or relating to parole','conditional release-based,characteristic','B2'],
      ['paroleous','adj','Full of parole','conditional release-filled,abundant','C1'],
      ['paroleful','adj','Full of parole','conditional release-rich,abounding','B2'],
      ['paroleless','adj','Without parole','lacking,without','B2'],
      ['paroleism','n','The ideology of parole','conditional release ideology,doctrine','C1'],
      ['paroleist','n','A person focused on parole','conditional release specialist,advocate','C1'],
      ['paroleise','v','To make into parole','conditional release,convert','C1'],
      ['paroleize','v','To make or become parole','conditional release,transform','C1'],
      ['antiparole','adj','Opposed to parole','against,opposing','C1'],
      ['nonparole','adj','Not involving parole','without,lacking','B2'],
      ['preparole','n','Before parole','preceding,prior','C1'],
      ['postparole','n','After parole','following,subsequent','C1'],
      ['subparole','n','A subdivision of parole','subset,branch','C1'],
      ['multiparole','adj','Involving many paroles','multiple,several','C1'],
      ['interparole','adj','Between paroles','cross,between','C1'],
      ['probationic','adj','Of or relating to probation','supervision-based,characteristic','B2'],
      ['probationous','adj','Full of probation','supervision-filled,abundant','C1'],
      ['probationful','adj','Full of probation','supervision-rich,abounding','B2'],
      ['probationless','adj','Without probation','lacking,without','B2'],
      ['probationism','n','The ideology of probation','supervision ideology,doctrine','C1'],
      ['probationist','n','A person focused on probation','supervision specialist,advocate','C1'],
      ['probationise','v','To make into probation','supervision,convert','C1'],
      ['probationize','v','To make or become probation','supervision,transform','C1'],
      ['antiprobation','adj','Opposed to probation','against,opposing','C1'],
      ['nonprobation','adj','Not involving probation','without,lacking','B2'],
      ['preprobation','n','Before probation','preceding,prior','C1'],
      ['postprobation','n','After probation','following,subsequent','C1'],
      ['subprobation','n','A subdivision of probation','subset,branch','C1'],
      ['multiprobation','adj','Involving many probations','multiple,several','C1'],
      ['interprobation','adj','Between probations','cross,between','C1'],
      ['jurisdictionic','adj','Of or relating to jurisdiction','authority-based,characteristic','B2'],
      ['jurisdictionous','adj','Full of jurisdiction','authority-filled,abundant','C1'],
      ['jurisdictionful','adj','Full of jurisdiction','authority-rich,abounding','B2'],
      ['jurisdictionless','adj','Without jurisdiction','lacking,without','B2'],
      ['jurisdictionism','n','The ideology of jurisdiction','authority ideology,doctrine','C1'],
      ['jurisdictionist','n','A person focused on jurisdiction','authority specialist,advocate','C1'],
      ['jurisdictionise','v','To make into jurisdiction','authority,convert','C1'],
      ['jurisdictionize','v','To make or become jurisdiction','authority,transform','C1'],
      ['antijurisdiction','adj','Opposed to jurisdiction','against,opposing','C1'],
      ['nonjurisdiction','adj','Not involving jurisdiction','without,lacking','B2'],
      ['prejurisdiction','n','Before jurisdiction','preceding,prior','C1'],
      ['postjurisdiction','n','After jurisdiction','following,subsequent','C1'],
      ['subjurisdiction','n','A subdivision of jurisdiction','subset,branch','C1'],
      ['multijurisdiction','adj','Involving many jurisdictions','multiple,several','C1'],
      ['interjurisdiction','adj','Between jurisdictions','cross,between','C1'],
    ],
  },
  collocations: {}
};
