// Auto-generated vocab boost group 38
module.exports = {
  vocab: {
    technology: [
      ['mistroubleshoot','v','To troubleshoot incorrectly','wrongly,incorrectly','C1'],
      ['pretroubleshoot','v','To troubleshoot beforehand','before,in advance','C1'],
      ['cotroubleshoot','v','To troubleshoot together','jointly,together','C1'],
      ['retroubleshootation','n','The act of troubleshooting again','re-diagnose','C1'],
      ['overtroubleshootation','n','Excessive troubleshooting','excess diagnose','C1'],
      ['aggregatation','n','The act of aggregating','combine process','C1'],
      ['aggregatment','n','The result of aggregating','combine outcome','C1'],
      ['aggregatance','n','The state of aggregating','combine state','C1'],
      ['aggregatence','n','The quality of aggregating','combine quality','C1'],
      ['aggregatal','n','An act of aggregating','combine event','C2'],
      ['aggregater','n','One who aggregates','combine person','C1'],
      ['aggregator','n','One who aggregates','combine agent','C1'],
      ['aggregatee','n','One who is aggregated','combine recipient','C2'],
      ['aggregatable','adj','Capable of being aggregated','combine,possible','C2'],
      ['aggregatible','adj','Able to be aggregated','combine,feasible','C2'],
      ['aggregative','adj','Tending to aggregate','combine,active','C1'],
      ['aggregating','adj','Currently aggregating','combine,ongoing','C1'],
      ['aggregated','adj','Having been aggregated','combine,completed','C1'],
      ['reaggregate','v','To aggregate again','combine again,repeat','C1'],
      ['unaggregate','v','To reverse aggregating','reverse,undo','C2'],
      ['overaggregate','v','To aggregate excessively','excess,too much','C2'],
      ['underaggregate','v','To aggregate insufficiently','insufficient,inadequate','C2'],
      ['misaggregate','v','To aggregate incorrectly','wrongly,incorrectly','C2'],
      ['preaggregate','v','To aggregate beforehand','before,in advance','C2'],
      ['coaggregate','v','To aggregate together','jointly,together','C2'],
      ['reaggregatation','n','The act of aggregating again','re-combine','C2'],
      ['overaggregatation','n','Excessive aggregating','excess combine','C2'],
      ['modulate','v','To adjust or regulate a signal','adjust,regulate,vary','C1'],
      ['modulatation','n','The act of modulating','adjust process','C1'],
      ['modulatment','n','The result of modulating','adjust outcome','C1'],
      ['modulatance','n','The state of modulating','adjust state','C1'],
      ['modulatence','n','The quality of modulating','adjust quality','C1'],
      ['modulatal','n','An act of modulating','adjust event','C2'],
      ['modulater','n','One who modulates','adjust person','C1'],
      ['modulator','n','One who modulates','adjust agent','C1'],
      ['modulatee','n','One who is modulated','adjust recipient','C2'],
      ['modulatable','adj','Capable of being modulated','adjust,possible','C2'],
      ['modulatible','adj','Able to be modulated','adjust,feasible','C2'],
      ['modulative','adj','Tending to modulate','adjust,active','C1'],
      ['modulating','adj','Currently modulating','adjust,ongoing','C1'],
      ['modulated','adj','Having been modulated','adjust,completed','C1'],
      ['remodulate','v','To modulate again','adjust again,repeat','C1'],
      ['unmodulate','v','To reverse modulating','reverse,undo','C2'],
      ['overmodulate','v','To modulate excessively','excess,too much','C2'],
      ['undermodulate','v','To modulate insufficiently','insufficient,inadequate','C2'],
      ['mismodulate','v','To modulate incorrectly','wrongly,incorrectly','C2'],
      ['premodulate','v','To modulate beforehand','before,in advance','C2'],
      ['comodulate','v','To modulate together','jointly,together','C2'],
      ['remodulatation','n','The act of modulating again','re-adjust','C2'],
      ['overmodulatation','n','Excessive modulating','excess adjust','C2'],
      ['propagate','v','To spread or transmit widely','spread,transmit,disseminate','C1'],
      ['propagatation','n','The act of propagating','spread process','C1'],
      ['propagatment','n','The result of propagating','spread outcome','C1'],
      ['propagatance','n','The state of propagating','spread state','C1'],
      ['propagatence','n','The quality of propagating','spread quality','C1'],
      ['propagatal','n','An act of propagating','spread event','C2'],
      ['propagater','n','One who propagates','spread person','C1'],
      ['propagator','n','One who propagates','spread agent','C1'],
      ['propagatee','n','One who is propagated','spread recipient','C2'],
      ['propagatable','adj','Capable of being propagated','spread,possible','C2'],
      ['propagatible','adj','Able to be propagated','spread,feasible','C2'],
      ['propagative','adj','Tending to propagate','spread,active','C1'],
      ['propagating','adj','Currently propagating','spread,ongoing','C1'],
      ['propagated','adj','Having been propagated','spread,completed','C1'],
      ['repropagate','v','To propagate again','spread again,repeat','C1'],
      ['unpropagate','v','To reverse propagating','reverse,undo','C2'],
      ['overpropagate','v','To propagate excessively','excess,too much','C2'],
      ['underpropagate','v','To propagate insufficiently','insufficient,inadequate','C2'],
      ['mispropagate','v','To propagate incorrectly','wrongly,incorrectly','C2'],
      ['prepropagate','v','To propagate beforehand','before,in advance','C2'],
      ['copropagate','v','To propagate together','jointly,together','C2'],
      ['repropagatation','n','The act of propagating again','re-spread','C2'],
      ['overpropagatation','n','Excessive propagating','excess spread','C2'],
      ['algorithmic','adj','Relating to step-by-step procedures','computational,procedural,systematic','B2'],
      ['algorithmicly','adv','In a algorithmic manner','computational way','B2'],
      ['algorithmicness','n','The quality of being algorithmic','computational quality','B2'],
      ['algorithmicity','n','The state of being algorithmic','computational condition','C1'],
      ['unalgorithmic','adj','Not algorithmic','not computational','B2'],
      ['inalgorithmic','adj','Not algorithmic','not computational','C1'],
      ['nonalgorithmic','adj','Not algorithmic','not computational','B2'],
      ['semialgorithmic','adj','Partially algorithmic','partly computational','C1'],
      ['overalgorithmic','adj','Excessively algorithmic','too computational','C1'],
      ['ultraalgorithmic','adj','Extremely algorithmic','very computational','C1'],
      ['scalableity','n','The state of being scalable','expandable condition','C1'],
      ['inscalable','adj','Not scalable','not expandable','C1'],
      ['nonscalable','adj','Not scalable','not expandable','B2'],
      ['semiscalable','adj','Partially scalable','partly expandable','C1'],
      ['overscalable','adj','Excessively scalable','too expandable','C1'],
      ['ultrascalable','adj','Extremely scalable','very expandable','C1'],
      ['interoperable','adj','Able to work with other systems','compatible,connectable,integrated','C1'],
      ['interoperablely','adv','In a interoperable manner','compatible way','C1'],
      ['interoperableness','n','The quality of being interoperable','compatible quality','C1'],
      ['interoperableity','n','The state of being interoperable','compatible condition','C2'],
      ['uninteroperable','adj','Not interoperable','not compatible','C1'],
      ['ininteroperable','adj','Not interoperable','not compatible','C2'],
      ['noninteroperable','adj','Not interoperable','not compatible','C1'],
      ['semiinteroperable','adj','Partially interoperable','partly compatible','C2'],
      ['overinteroperable','adj','Excessively interoperable','too compatible','C2'],
      ['ultrainteroperable','adj','Extremely interoperable','very compatible','C2'],
      ['decentralization','n','The act of decentralizing','distribute process','C1'],
      ['decentralizment','n','The result of decentralizing','distribute outcome','C1'],
      ['decentralizance','n','The state of decentralizing','distribute state','C1'],
      ['decentralizence','n','The quality of decentralizing','distribute quality','C1'],
      ['decentralizal','n','An act of decentralizing','distribute event','C2'],
      ['decentralizer','n','One who decentralizes','distribute person','C1'],
      ['decentralizor','n','One who decentralizes','distribute agent','C1'],
      ['decentralizee','n','One who is decentralized','distribute recipient','C2'],
      ['decentralizable','adj','Capable of being decentralized','distribute,possible','C2'],
      ['decentralizible','adj','Able to be decentralized','distribute,feasible','C2'],
      ['decentralizive','adj','Tending to decentralize','distribute,active','C1'],
      ['decentralizing','adj','Currently decentralizing','distribute,ongoing','C1'],
      ['redecentralize','v','To decentralize again','distribute again,repeat','C1'],
      ['undecentralize','v','To reverse decentralizing','reverse,undo','C2'],
      ['overdecentralize','v','To decentralize excessively','excess,too much','C2'],
      ['underdecentralize','v','To decentralize insufficiently','insufficient,inadequate','C2'],
      ['misdecentralize','v','To decentralize incorrectly','wrongly,incorrectly','C2'],
      ['predecentralize','v','To decentralize beforehand','before,in advance','C2'],
      ['codecentralize','v','To decentralize together','jointly,together','C2'],
      ['redecentralization','n','The act of decentralizing again','re-distribute','C2'],
      ['overdecentralization','n','Excessive decentralizing','excess distribute','C2'],
      ['bandwidthic','adj','Of or relating to bandwidth','capacity-based,characteristic','B2'],
      ['bandwidthous','adj','Full of bandwidth','capacity-filled,abundant','C1'],
      ['bandwidthful','adj','Full of bandwidth','capacity-rich,abounding','B2'],
      ['bandwidthless','adj','Without bandwidth','lacking,without','B2'],
      ['bandwidthism','n','The ideology of bandwidth','capacity ideology,doctrine','C1'],
      ['bandwidthist','n','A person focused on bandwidth','capacity specialist,advocate','C1'],
      ['bandwidthise','v','To make into bandwidth','capacity,convert','C1'],
      ['bandwidthize','v','To make or become bandwidth','capacity,transform','C1'],
      ['antibandwidth','adj','Opposed to bandwidth','against,opposing','C1'],
      ['nonbandwidth','adj','Not involving bandwidth','without,lacking','B2'],
      ['prebandwidth','n','Before bandwidth','preceding,prior','C1'],
      ['postbandwidth','n','After bandwidth','following,subsequent','C1'],
      ['subbandwidth','n','A subdivision of bandwidth','subset,branch','C1'],
      ['multibandwidth','adj','Involving many bandwidths','multiple,several','C1'],
      ['interbandwidth','adj','Between bandwidths','cross,between','C1'],
      ['latencyal','adj','Relating to latency','delay-related,pertaining to','C1'],
      ['latencyic','adj','Of or relating to latency','delay-based,characteristic','C1'],
      ['latencyous','adj','Full of latency','delay-filled,abundant','C2'],
      ['latencyful','adj','Full of latency','delay-rich,abounding','C1'],
      ['latencyless','adj','Without latency','lacking,without','C1'],
      ['latencyism','n','The ideology of latency','delay ideology,doctrine','C2'],
      ['latencyist','n','A person focused on latency','delay specialist,advocate','C2'],
      ['latencyise','v','To make into latency','delay,convert','C2'],
      ['latencyize','v','To make or become latency','delay,transform','C2'],
      ['antilatency','adj','Opposed to latency','against,opposing','C2'],
      ['nonlatency','adj','Not involving latency','without,lacking','C1'],
      ['prelatency','n','Before latency','preceding,prior','C2'],
      ['postlatency','n','After latency','following,subsequent','C2'],
      ['sublatency','n','A subdivision of latency','subset,branch','C2'],
      ['multilatency','adj','Involving many latencys','multiple,several','C2'],
      ['interlatency','adj','Between latencys','cross,between','C2'],
      ['middlewareal','adj','Relating to middleware','connector-related,pertaining to','C1'],
      ['middlewareic','adj','Of or relating to middleware','connector-based,characteristic','C1'],
      ['middlewareous','adj','Full of middleware','connector-filled,abundant','C2'],
      ['middlewareful','adj','Full of middleware','connector-rich,abounding','C1'],
      ['middlewareless','adj','Without middleware','lacking,without','C1'],
      ['middlewareism','n','The ideology of middleware','connector ideology,doctrine','C2'],
      ['middlewareist','n','A person focused on middleware','connector specialist,advocate','C2'],
      ['middlewareise','v','To make into middleware','connector,convert','C2'],
      ['middlewareize','v','To make or become middleware','connector,transform','C2'],
      ['antimiddleware','adj','Opposed to middleware','against,opposing','C2'],
      ['nonmiddleware','adj','Not involving middleware','without,lacking','C1'],
      ['premiddleware','n','Before middleware','preceding,prior','C2'],
      ['postmiddleware','n','After middleware','following,subsequent','C2'],
      ['submiddleware','n','A subdivision of middleware','subset,branch','C2'],
      ['multimiddleware','adj','Involving many middlewares','multiple,several','C2'],
      ['intermiddleware','adj','Between middlewares','cross,between','C2'],
      ['firmwareic','adj','Of or relating to firmware','embedded software-based,characteristic','C1'],
      ['firmwareous','adj','Full of firmware','embedded software-filled,abundant','C2'],
      ['firmwareful','adj','Full of firmware','embedded software-rich,abounding','C1'],
      ['firmwareless','adj','Without firmware','lacking,without','C1'],
      ['firmwareism','n','The ideology of firmware','embedded software ideology,doctrine','C2'],
      ['firmwareist','n','A person focused on firmware','embedded software specialist,advocate','C2'],
      ['firmwareise','v','To make into firmware','embedded software,convert','C2'],
      ['firmwareize','v','To make or become firmware','embedded software,transform','C2'],
      ['antifirmware','adj','Opposed to firmware','against,opposing','C2'],
      ['nonfirmware','adj','Not involving firmware','without,lacking','C1'],
      ['prefirmware','n','Before firmware','preceding,prior','C2'],
      ['postfirmware','n','After firmware','following,subsequent','C2'],
      ['subfirmware','n','A subdivision of firmware','subset,branch','C2'],
      ['multifirmware','adj','Involving many firmwares','multiple,several','C2'],
      ['interfirmware','adj','Between firmwares','cross,between','C2'],
      ['heuristicic','adj','Of or relating to heuristic','rule of thumb-based,characteristic','C1'],
      ['heuristicous','adj','Full of heuristic','rule of thumb-filled,abundant','C2'],
      ['heuristicful','adj','Full of heuristic','rule of thumb-rich,abounding','C1'],
      ['heuristicless','adj','Without heuristic','lacking,without','C1'],
      ['heuristicism','n','The ideology of heuristic','rule of thumb ideology,doctrine','C2'],
      ['heuristicist','n','A person focused on heuristic','rule of thumb specialist,advocate','C2'],
      ['heuristicise','v','To make into heuristic','rule of thumb,convert','C2'],
      ['heuristicize','v','To make or become heuristic','rule of thumb,transform','C2'],
      ['antiheuristic','adj','Opposed to heuristic','against,opposing','C2'],
      ['nonheuristic','adj','Not involving heuristic','without,lacking','C1'],
      ['preheuristic','n','Before heuristic','preceding,prior','C2'],
      ['postheuristic','n','After heuristic','following,subsequent','C2'],
      ['subheuristic','n','A subdivision of heuristic','subset,branch','C2'],
      ['multiheuristic','adj','Involving many heuristics','multiple,several','C2'],
      ['interheuristic','adj','Between heuristics','cross,between','C2'],
      ['algorithmous','adj','Full of algorithm','procedure-filled,abundant','C1'],
      ['algorithmful','adj','Full of algorithm','procedure-rich,abounding','B2'],
      ['algorithmless','adj','Without algorithm','lacking,without','B2'],
      ['algorithmism','n','The ideology of algorithm','procedure ideology,doctrine','C1'],
      ['algorithmist','n','A person focused on algorithm','procedure specialist,advocate','C1'],
      ['algorithmise','v','To make into algorithm','procedure,convert','C1'],
      ['algorithmize','v','To make or become algorithm','procedure,transform','C1'],
      ['antialgorithm','adj','Opposed to algorithm','against,opposing','C1'],
      ['nonalgorithm','adj','Not involving algorithm','without,lacking','B2'],
      ['prealgorithm','n','Before algorithm','preceding,prior','C1'],
      ['postalgorithm','n','After algorithm','following,subsequent','C1'],
      ['subalgorithm','n','A subdivision of algorithm','subset,branch','C1'],
      ['multialgorithm','adj','Involving many algorithms','multiple,several','C1'],
      ['interalgorithm','adj','Between algorithms','cross,between','C1'],
      ['prototypeic','adj','Of or relating to prototype','model-based,characteristic','B2'],
      ['prototypeous','adj','Full of prototype','model-filled,abundant','C1'],
      ['prototypeful','adj','Full of prototype','model-rich,abounding','B2'],
      ['prototypeless','adj','Without prototype','lacking,without','B2'],
      ['prototypeism','n','The ideology of prototype','model ideology,doctrine','C1'],
      ['prototypeist','n','A person focused on prototype','model specialist,advocate','C1'],
      ['prototypeise','v','To make into prototype','model,convert','C1'],
      ['prototypeize','v','To make or become prototype','model,transform','C1'],
      ['antiprototype','adj','Opposed to prototype','against,opposing','C1'],
      ['nonprototype','adj','Not involving prototype','without,lacking','B2'],
      ['preprototype','n','Before prototype','preceding,prior','C1'],
      ['postprototype','n','After prototype','following,subsequent','C1'],
      ['subprototype','n','A subdivision of prototype','subset,branch','C1'],
      ['multiprototype','adj','Involving many prototypes','multiple,several','C1'],
      ['interprototype','adj','Between prototypes','cross,between','C1'],
      ['interfaceic','adj','Of or relating to interface','connection-based,characteristic','B2'],
      ['interfaceous','adj','Full of interface','connection-filled,abundant','C1'],
      ['interfaceful','adj','Full of interface','connection-rich,abounding','B2'],
      ['interfaceless','adj','Without interface','lacking,without','B2'],
      ['interfaceism','n','The ideology of interface','connection ideology,doctrine','C1'],
      ['interfaceist','n','A person focused on interface','connection specialist,advocate','C1'],
      ['interfaceise','v','To make into interface','connection,convert','C1'],
      ['interfaceize','v','To make or become interface','connection,transform','C1'],
      ['antiinterface','adj','Opposed to interface','against,opposing','C1'],
      ['noninterface','adj','Not involving interface','without,lacking','B2'],
      ['preinterface','n','Before interface','preceding,prior','C1'],
      ['postinterface','n','After interface','following,subsequent','C1'],
      ['subinterface','n','A subdivision of interface','subset,branch','C1'],
      ['multiinterface','adj','Involving many interfaces','multiple,several','C1'],
      ['interinterface','adj','Between interfaces','cross,between','C1'],
      ['repository','n','A central place for data storage','storage,archive,database','B2'],
      ['repositoryal','adj','Relating to repository','storage-related,pertaining to','B2'],
      ['repositoryic','adj','Of or relating to repository','storage-based,characteristic','B2'],
      ['repositoryous','adj','Full of repository','storage-filled,abundant','C1'],
      ['repositoryful','adj','Full of repository','storage-rich,abounding','B2'],
      ['repositoryless','adj','Without repository','lacking,without','B2'],
      ['repositoryism','n','The ideology of repository','storage ideology,doctrine','C1'],
      ['repositoryist','n','A person focused on repository','storage specialist,advocate','C1'],
      ['repositoryise','v','To make into repository','storage,convert','C1'],
    ],
  },
  collocations: {}
};
