// Auto-generated vocab boost group 59
module.exports = {
  vocab: {
    crime: [
      ['whistleblowerise','v','To make into whistleblower','informant,convert','C1'],
      ['whistleblowerize','v','To make or become whistleblower','informant,transform','C1'],
      ['antiwhistleblower','adj','Opposed to whistleblower','against,opposing','C1'],
      ['nonwhistleblower','adj','Not involving whistleblower','without,lacking','B2'],
      ['prewhistleblower','n','Before whistleblower','preceding,prior','C1'],
      ['postwhistleblower','n','After whistleblower','following,subsequent','C1'],
      ['subwhistleblower','n','A subdivision of whistleblower','subset,branch','C1'],
      ['multiwhistleblower','adj','Involving many whistleblowers','multiple,several','C1'],
      ['interwhistleblower','adj','Between whistleblowers','cross,between','C1'],
    ],
    media: [
      ['broadcastation','n','The act of broadcasting','transmit process','B1'],
      ['broadcastment','n','The result of broadcasting','transmit outcome','B1'],
      ['broadcastance','n','The state of broadcasting','transmit state','B1'],
      ['broadcastence','n','The quality of broadcasting','transmit quality','B1'],
      ['broadcaster','n','One who broadcasts','transmit person','B1'],
      ['broadcastor','n','One who broadcasts','transmit agent','B1'],
      ['broadcastee','n','One who is broadcastd','transmit recipient','B2'],
      ['broadcastable','adj','Capable of being broadcastd','transmit,possible','B2'],
      ['broadcastible','adj','Able to be broadcastd','transmit,feasible','B2'],
      ['broadcastive','adj','Tending to broadcast','transmit,active','B1'],
      ['broadcasting','adj','Currently broadcasting','transmit,ongoing','B1'],
      ['broadcasted','adj','Having been broadcastd','transmit,completed','B1'],
      ['rebroadcast','v','To broadcast again','transmit again,repeat','B1'],
      ['unbroadcast','v','To reverse broadcasting','reverse,undo','B2'],
      ['overbroadcast','v','To broadcast excessively','excess,too much','B2'],
      ['underbroadcast','v','To broadcast insufficiently','insufficient,inadequate','B2'],
      ['misbroadcast','v','To broadcast incorrectly','wrongly,incorrectly','B2'],
      ['prebroadcast','v','To broadcast beforehand','before,in advance','B2'],
      ['cobroadcast','v','To broadcast together','jointly,together','B2'],
      ['rebroadcastation','n','The act of broadcasting again','re-transmit','B2'],
      ['overbroadcastation','n','Excessive broadcasting','excess transmit','B2'],
      ['sensationalize','v','To present in an exciting manner','exaggerate,dramatize,hype','C1'],
      ['sensationalization','n','The act of sensationalizing','exaggerate process','C1'],
      ['sensationalizment','n','The result of sensationalizing','exaggerate outcome','C1'],
      ['sensationalizance','n','The state of sensationalizing','exaggerate state','C1'],
      ['sensationalizence','n','The quality of sensationalizing','exaggerate quality','C1'],
      ['sensationalizal','n','An act of sensationalizing','exaggerate event','C2'],
      ['sensationalizer','n','One who sensationalizes','exaggerate person','C1'],
      ['sensationalizor','n','One who sensationalizes','exaggerate agent','C1'],
      ['sensationalizee','n','One who is sensationalized','exaggerate recipient','C2'],
      ['sensationalizable','adj','Capable of being sensationalized','exaggerate,possible','C2'],
      ['sensationalizible','adj','Able to be sensationalized','exaggerate,feasible','C2'],
      ['sensationalizive','adj','Tending to sensationalize','exaggerate,active','C1'],
      ['sensationalizing','adj','Currently sensationalizing','exaggerate,ongoing','C1'],
      ['sensationalized','adj','Having been sensationalized','exaggerate,completed','C1'],
      ['resensationalize','v','To sensationalize again','exaggerate again,repeat','C1'],
      ['unsensationalize','v','To reverse sensationalizing','reverse,undo','C2'],
      ['oversensationalize','v','To sensationalize excessively','excess,too much','C2'],
      ['undersensationalize','v','To sensationalize insufficiently','insufficient,inadequate','C2'],
      ['missensationalize','v','To sensationalize incorrectly','wrongly,incorrectly','C2'],
      ['presensationalize','v','To sensationalize beforehand','before,in advance','C2'],
      ['cosensationalize','v','To sensationalize together','jointly,together','C2'],
      ['resensationalization','n','The act of sensationalizing again','re-exaggerate','C2'],
      ['oversensationalization','n','Excessive sensationalizing','excess exaggerate','C2'],
      ['censor','v','To suppress unacceptable content','ban,suppress,restrict','B2'],
      ['censoration','n','The act of censoring','ban process','B2'],
      ['censorment','n','The result of censoring','ban outcome','B2'],
      ['censorance','n','The state of censoring','ban state','B2'],
      ['censorence','n','The quality of censoring','ban quality','B2'],
      ['censoral','n','An act of censoring','ban event','C1'],
      ['censorer','n','One who censors','ban person','B2'],
      ['censoror','n','One who censors','ban agent','B2'],
      ['censoree','n','One who is censord','ban recipient','C1'],
      ['censorable','adj','Capable of being censord','ban,possible','C1'],
      ['censorible','adj','Able to be censord','ban,feasible','C1'],
      ['censorive','adj','Tending to censor','ban,active','B2'],
      ['censoring','adj','Currently censoring','ban,ongoing','B2'],
      ['censored','adj','Having been censord','ban,completed','B2'],
      ['recensor','v','To censor again','ban again,repeat','B2'],
      ['uncensor','v','To reverse censoring','reverse,undo','C1'],
      ['overcensor','v','To censor excessively','excess,too much','C1'],
      ['undercensor','v','To censor insufficiently','insufficient,inadequate','C1'],
      ['miscensor','v','To censor incorrectly','wrongly,incorrectly','C1'],
      ['precensor','v','To censor beforehand','before,in advance','C1'],
      ['cocensor','v','To censor together','jointly,together','C1'],
      ['recensoration','n','The act of censoring again','re-ban','C1'],
      ['overcensoration','n','Excessive censoring','excess ban','C1'],
      ['editorialize','v','To express opinions in reporting','opine,comment,bias','C1'],
      ['editorialization','n','The act of editorializing','opine process','C1'],
      ['editorializment','n','The result of editorializing','opine outcome','C1'],
      ['editorializance','n','The state of editorializing','opine state','C1'],
      ['editorializence','n','The quality of editorializing','opine quality','C1'],
      ['editorializal','n','An act of editorializing','opine event','C2'],
      ['editorializer','n','One who editorializes','opine person','C1'],
      ['editorializor','n','One who editorializes','opine agent','C1'],
      ['editorializee','n','One who is editorialized','opine recipient','C2'],
      ['editorializable','adj','Capable of being editorialized','opine,possible','C2'],
      ['editorializible','adj','Able to be editorialized','opine,feasible','C2'],
      ['editorializive','adj','Tending to editorialize','opine,active','C1'],
      ['editorializing','adj','Currently editorializing','opine,ongoing','C1'],
      ['editorialized','adj','Having been editorialized','opine,completed','C1'],
      ['reeditorialize','v','To editorialize again','opine again,repeat','C1'],
      ['uneditorialize','v','To reverse editorializing','reverse,undo','C2'],
      ['overeditorialize','v','To editorialize excessively','excess,too much','C2'],
      ['undereditorialize','v','To editorialize insufficiently','insufficient,inadequate','C2'],
      ['miseditorialize','v','To editorialize incorrectly','wrongly,incorrectly','C2'],
      ['preeditorialize','v','To editorialize beforehand','before,in advance','C2'],
      ['coeditorialize','v','To editorialize together','jointly,together','C2'],
      ['reeditorialization','n','The act of editorializing again','re-opine','C2'],
      ['overeditorialization','n','Excessive editorializing','excess opine','C2'],
      ['satirize','v','To mock using humour or irony','mock,parody,ridicule','C1'],
      ['satirization','n','The act of satirizing','mock process','C1'],
      ['satirizment','n','The result of satirizing','mock outcome','C1'],
      ['satirizance','n','The state of satirizing','mock state','C1'],
      ['satirizence','n','The quality of satirizing','mock quality','C1'],
      ['satirizal','n','An act of satirizing','mock event','C2'],
      ['satirizer','n','One who satirizes','mock person','C1'],
      ['satirizor','n','One who satirizes','mock agent','C1'],
      ['satirizee','n','One who is satirized','mock recipient','C2'],
      ['satirizable','adj','Capable of being satirized','mock,possible','C2'],
      ['satirizible','adj','Able to be satirized','mock,feasible','C2'],
      ['satirizive','adj','Tending to satirize','mock,active','C1'],
      ['satirizing','adj','Currently satirizing','mock,ongoing','C1'],
      ['satirized','adj','Having been satirized','mock,completed','C1'],
      ['resatirize','v','To satirize again','mock again,repeat','C1'],
      ['unsatirize','v','To reverse satirizing','reverse,undo','C2'],
      ['oversatirize','v','To satirize excessively','excess,too much','C2'],
      ['undersatirize','v','To satirize insufficiently','insufficient,inadequate','C2'],
      ['missatirize','v','To satirize incorrectly','wrongly,incorrectly','C2'],
      ['presatirize','v','To satirize beforehand','before,in advance','C2'],
      ['cosatirize','v','To satirize together','jointly,together','C2'],
      ['resatirization','n','The act of satirizing again','re-mock','C2'],
      ['oversatirization','n','Excessive satirizing','excess mock','C2'],
      ['defame','v','To damage the reputation of someone','slander,libel,smear','C1'],
      ['defamment','n','The result of defaming','slander outcome','C1'],
      ['defamance','n','The state of defaming','slander state','C1'],
      ['defamence','n','The quality of defaming','slander quality','C1'],
      ['defamal','n','An act of defaming','slander event','C2'],
      ['defamer','n','One who defames','slander person','C1'],
      ['defamor','n','One who defames','slander agent','C1'],
      ['defamee','n','One who is defamed','slander recipient','C2'],
      ['defamable','adj','Capable of being defamed','slander,possible','C2'],
      ['defamible','adj','Able to be defamed','slander,feasible','C2'],
      ['defamive','adj','Tending to defame','slander,active','C1'],
      ['defaming','adj','Currently defaming','slander,ongoing','C1'],
      ['defamed','adj','Having been defamed','slander,completed','C1'],
      ['redefame','v','To defame again','slander again,repeat','C1'],
      ['undefame','v','To reverse defaming','reverse,undo','C2'],
      ['overdefame','v','To defame excessively','excess,too much','C2'],
      ['underdefame','v','To defame insufficiently','insufficient,inadequate','C2'],
      ['misdefame','v','To defame incorrectly','wrongly,incorrectly','C2'],
      ['predefame','v','To defame beforehand','before,in advance','C2'],
      ['codefame','v','To defame together','jointly,together','C2'],
      ['redefamation','n','The act of defaming again','re-slander','C2'],
      ['overdefamation','n','Excessive defaming','excess slander','C2'],
      ['syndicatation','n','The act of syndicating','distribute process','C1'],
      ['syndicatment','n','The result of syndicating','distribute outcome','C1'],
      ['syndicatance','n','The state of syndicating','distribute state','C1'],
      ['syndicatence','n','The quality of syndicating','distribute quality','C1'],
      ['syndicatal','n','An act of syndicating','distribute event','C2'],
      ['syndicater','n','One who syndicates','distribute person','C1'],
      ['syndicator','n','One who syndicates','distribute agent','C1'],
      ['syndicatee','n','One who is syndicated','distribute recipient','C2'],
      ['syndicatable','adj','Capable of being syndicated','distribute,possible','C2'],
      ['syndicatible','adj','Able to be syndicated','distribute,feasible','C2'],
      ['syndicative','adj','Tending to syndicate','distribute,active','C1'],
      ['syndicating','adj','Currently syndicating','distribute,ongoing','C1'],
      ['syndicated','adj','Having been syndicated','distribute,completed','C1'],
      ['resyndicate','v','To syndicate again','distribute again,repeat','C1'],
      ['unsyndicate','v','To reverse syndicating','reverse,undo','C2'],
      ['oversyndicate','v','To syndicate excessively','excess,too much','C2'],
      ['undersyndicate','v','To syndicate insufficiently','insufficient,inadequate','C2'],
      ['missyndicate','v','To syndicate incorrectly','wrongly,incorrectly','C2'],
      ['presyndicate','v','To syndicate beforehand','before,in advance','C2'],
      ['cosyndicate','v','To syndicate together','jointly,together','C2'],
      ['resyndicatation','n','The act of syndicating again','re-distribute','C2'],
      ['oversyndicatation','n','Excessive syndicating','excess distribute','C2'],
      ['livestream','v','To broadcast in real time online','stream,webcast,broadcast','B2'],
      ['livestreamation','n','The act of livestreaming','stream process','B2'],
      ['livestreamment','n','The result of livestreaming','stream outcome','B2'],
      ['livestreamance','n','The state of livestreaming','stream state','B2'],
      ['livestreamence','n','The quality of livestreaming','stream quality','B2'],
      ['livestreamal','n','An act of livestreaming','stream event','C1'],
      ['livestreamer','n','One who livestreams','stream person','B2'],
      ['livestreamor','n','One who livestreams','stream agent','B2'],
      ['livestreamee','n','One who is livestreamd','stream recipient','C1'],
      ['livestreamable','adj','Capable of being livestreamd','stream,possible','C1'],
      ['livestreamible','adj','Able to be livestreamd','stream,feasible','C1'],
      ['livestreamive','adj','Tending to livestream','stream,active','B2'],
      ['livestreaming','adj','Currently livestreaming','stream,ongoing','B2'],
      ['livestreamed','adj','Having been livestreamd','stream,completed','B2'],
      ['relivestream','v','To livestream again','stream again,repeat','B2'],
      ['unlivestream','v','To reverse livestreaming','reverse,undo','C1'],
      ['overlivestream','v','To livestream excessively','excess,too much','C1'],
      ['underlivestream','v','To livestream insufficiently','insufficient,inadequate','C1'],
      ['mislivestream','v','To livestream incorrectly','wrongly,incorrectly','C1'],
      ['prelivestream','v','To livestream beforehand','before,in advance','C1'],
      ['colivestream','v','To livestream together','jointly,together','C1'],
      ['relivestreamation','n','The act of livestreaming again','re-stream','C1'],
      ['overlivestreamation','n','Excessive livestreaming','excess stream','C1'],
      ['clickbaitic','adj','Of or relating to clickbait','bait-based,characteristic','B2'],
      ['clickbaitous','adj','Full of clickbait','bait-filled,abundant','C1'],
      ['clickbaitful','adj','Full of clickbait','bait-rich,abounding','B2'],
      ['clickbaitless','adj','Without clickbait','lacking,without','B2'],
      ['clickbaitism','n','The ideology of clickbait','bait ideology,doctrine','C1'],
      ['clickbaitist','n','A person focused on clickbait','bait specialist,advocate','C1'],
      ['clickbaitise','v','To make into clickbait','bait,convert','C1'],
      ['clickbaitize','v','To make or become clickbait','bait,transform','C1'],
      ['anticlickbait','adj','Opposed to clickbait','against,opposing','C1'],
      ['nonclickbait','adj','Not involving clickbait','without,lacking','B2'],
      ['preclickbait','n','Before clickbait','preceding,prior','C1'],
      ['postclickbait','n','After clickbait','following,subsequent','C1'],
      ['subclickbait','n','A subdivision of clickbait','subset,branch','C1'],
      ['multiclickbait','adj','Involving many clickbaits','multiple,several','C1'],
      ['interclickbait','adj','Between clickbaits','cross,between','C1'],
      ['propagandaic','adj','Of or relating to propaganda','misinformation-based,characteristic','B2'],
      ['propagandaous','adj','Full of propaganda','misinformation-filled,abundant','C1'],
      ['propagandaful','adj','Full of propaganda','misinformation-rich,abounding','B2'],
      ['propagandaless','adj','Without propaganda','lacking,without','B2'],
      ['propagandaism','n','The ideology of propaganda','misinformation ideology,doctrine','C1'],
      ['propagandaist','n','A person focused on propaganda','misinformation specialist,advocate','C1'],
      ['propagandaise','v','To make into propaganda','misinformation,convert','C1'],
      ['propagandaize','v','To make or become propaganda','misinformation,transform','C1'],
      ['antipropaganda','adj','Opposed to propaganda','against,opposing','C1'],
      ['nonpropaganda','adj','Not involving propaganda','without,lacking','B2'],
      ['prepropaganda','n','Before propaganda','preceding,prior','C1'],
      ['postpropaganda','n','After propaganda','following,subsequent','C1'],
      ['subpropaganda','n','A subdivision of propaganda','subset,branch','C1'],
      ['multipropaganda','adj','Involving many propagandas','multiple,several','C1'],
      ['interpropaganda','adj','Between propagandas','cross,between','C1'],
      ['tabloidic','adj','Of or relating to tabloid','popular press-based,characteristic','B2'],
      ['tabloidous','adj','Full of tabloid','popular press-filled,abundant','C1'],
      ['tabloidful','adj','Full of tabloid','popular press-rich,abounding','B2'],
      ['tabloidless','adj','Without tabloid','lacking,without','B2'],
      ['tabloidism','n','The ideology of tabloid','popular press ideology,doctrine','C1'],
      ['tabloidist','n','A person focused on tabloid','popular press specialist,advocate','C1'],
      ['tabloidise','v','To make into tabloid','popular press,convert','C1'],
      ['tabloidize','v','To make or become tabloid','popular press,transform','C1'],
      ['antitabloid','adj','Opposed to tabloid','against,opposing','C1'],
      ['nontabloid','adj','Not involving tabloid','without,lacking','B2'],
      ['pretabloid','n','Before tabloid','preceding,prior','C1'],
      ['posttabloid','n','After tabloid','following,subsequent','C1'],
      ['subtabloid','n','A subdivision of tabloid','subset,branch','C1'],
      ['multitabloid','adj','Involving many tabloids','multiple,several','C1'],
      ['intertabloid','adj','Between tabloids','cross,between','C1'],
      ['editorialic','adj','Of or relating to editorial','opinion piece-based,characteristic','B2'],
      ['editorialous','adj','Full of editorial','opinion piece-filled,abundant','C1'],
      ['editorialful','adj','Full of editorial','opinion piece-rich,abounding','B2'],
      ['editorialless','adj','Without editorial','lacking,without','B2'],
      ['editorialism','n','The ideology of editorial','opinion piece ideology,doctrine','C1'],
      ['editorialist','n','A person focused on editorial','opinion piece specialist,advocate','C1'],
      ['editorialise','v','To make into editorial','opinion piece,convert','C1'],
      ['antieditorial','adj','Opposed to editorial','against,opposing','C1'],
      ['noneditorial','adj','Not involving editorial','without,lacking','B2'],
      ['preeditorial','n','Before editorial','preceding,prior','C1'],
      ['posteditorial','n','After editorial','following,subsequent','C1'],
      ['subeditorial','n','A subdivision of editorial','subset,branch','C1'],
      ['multieditorial','adj','Involving many editorials','multiple,several','C1'],
      ['intereditorial','adj','Between editorials','cross,between','C1'],
      ['coverageal','adj','Relating to coverage','reporting-related,pertaining to','B2'],
      ['coverageic','adj','Of or relating to coverage','reporting-based,characteristic','B2'],
    ],
  },
  collocations: {}
};
