'use strict';
module.exports = {
  vocab: {
    education: [
      ["absent","adj","Not present in a place","missing,away","A2"],
      ["achieve","verb","To successfully reach a goal through effort","accomplish,attain","A2"],
      ["admission","noun","The process of being accepted into a school","entry,acceptance","A2"],
      ["assess","verb","To evaluate or estimate the quality of something","evaluate,judge","A2"],
      ["attendance","noun","The act of being present at a place","presence,participation","B1"],
      ["bachelor","noun","A person who holds an undergraduate degree","graduate,degree holder","B1"],
      ["boarding school","noun","A school where students live during term time","residential school,live-in school","B1"],
      ["cheat","verb","To act dishonestly to gain an advantage","deceive,swindle","B1"],
      ["degree","noun","An academic qualification awarded by a university","qualification,credential","B1"],
      ["discipline","noun","The practice of training people to obey rules","order,control","B2"],
      ["educate","verb","To give intellectual and moral instruction","teach,instruct","B2"],
      ["extracurricular","adj","Pursued in addition to the normal course of study","supplementary,additional","B2"],
      ["fluent","adj","Able to express oneself easily in a language","proficient,articulate","B2"],
      ["grade","noun","A mark indicating the quality of a student s work","mark,score","B2"],
      ["illiterate","adj","Unable to read or write","uneducated,unlettered","B2"],
      ["intellectual","adj","Relating to the intellect or understanding","cognitive,cerebral","C1"],
      ["knowledge","noun","Facts and information acquired through experience or education","understanding,awareness","C1"],
      ["learn","verb","To gain knowledge or skill through study","study,acquire","C1"],
      ["major","noun","A student s principal subject of study","specialisation,concentration","C1"],
      ["numeracy","noun","The ability to understand and work with numbers","mathematical skill,number literacy","C2"],
      ["obedient","adj","Complying with an order or request","compliant,dutiful","A2"],
      ["participate","verb","To take part in an activity","join in,engage","A2"],
      ["plagiarism","noun","The practice of taking someone else s work as your own","copying,theft of ideas","A2"],
      ["pupil","noun","A student in a school","student,learner","A2"],
      ["register","verb","To enter one s name on an official list","enrol,sign up","B1"],
      ["academic","adj","Relating to education and scholarship","scholarly,educational","B1"],
      ["strict","adj","Demanding that rules be obeyed","stern,rigorous","B1"],
      ["tutor","noun","A private teacher","instructor,coach","B1"],
      ["uniform","noun","A set of standard clothing worn by students","outfit,dress code","B1"],
      ["wisdom","noun","The quality of having experience, knowledge, and good judgement","insight,sagacity","B2"],
    ],
    technology: [
      ["artificial intelligence","noun","Computer systems that perform tasks normally requiring human intelligence","AI,machine intelligence","A2"],
      ["automate","verb","To convert a process to be operated by machines","mechanise,computerise","A2"],
      ["backup","noun","A copy of data stored separately for safety","reserve copy,duplicate","A2"],
      ["broadband","noun","High-capacity data transmission","high-speed internet,fast connection","A2"],
      ["cable","noun","A thick rope of wire for transmitting electricity or data","wire,cord","B1"],
      ["chip","noun","A very small piece of silicon with electronic circuits","microchip,processor","B1"],
      ["code","noun","Instructions written for a computer program","programming,script","B1"],
      ["crash","noun","A sudden failure of a computer system","breakdown,system failure","B1"],
      ["cursor","noun","A movable indicator on a computer screen","pointer,arrow","B1"],
      ["data","noun","Facts and statistics collected for analysis","information,figures","B2"],
      ["digital","adj","Relating to technology that uses electronic signals","electronic,computerised","B2"],
      ["disk","noun","A device on which data is stored","drive,storage media","B2"],
      ["drone","noun","An unmanned aircraft controlled remotely","UAV,remote aircraft","B2"],
      ["file","noun","A collection of data stored under one name","document,record","B2"],
      ["folder","noun","A virtual container for computer files","directory,category","B2"],
      ["format","verb","To prepare a storage medium for use","initialise,configure","C1"],
      ["glitch","noun","A sudden brief malfunction in equipment","bug,error","C1"],
      ["hacker","noun","A person who gains unauthorised access to systems","intruder,cybercriminal","C1"],
      ["icon","noun","A small picture on a computer screen representing a program","symbol,graphic","C1"],
      ["innovation","noun","A new method, idea, or product","invention,novelty","C2"],
      ["internet","noun","A global computer network for communication","web,cyberspace","A2"],
      ["link","noun","A connection between web pages","hyperlink,URL","A2"],
      ["memory","noun","The part of a computer where data is stored temporarily","RAM,storage","A2"],
      ["modem","noun","A device for connecting a computer to the internet","connector,adapter","A2"],
      ["navigate","verb","To move around a website or application","browse,explore","B1"],
      ["notification","noun","An alert or message sent by an application","alert,update","B1"],
      ["obsolete","adj","No longer produced or used; out of date","outdated,antiquated","B1"],
      ["processor","noun","The part of a computer that carries out instructions","CPU,chip","B1"],
      ["reboot","verb","To restart a computer system","restart,reset","B1"],
      ["resolution","noun","The detail an image or screen holds","clarity,definition","B2"],
    ],
    health: [
      ["ache","noun","A continuous dull pain","pain,soreness","A2"],
      ["addiction","noun","The state of being unable to stop using something","dependence,compulsion","A2"],
      ["asthma","noun","A condition causing difficulty in breathing","respiratory condition,breathing disorder","A2"],
      ["balanced","adj","Having different elements in the correct proportions","well-proportioned,even","A2"],
      ["bleed","verb","To lose blood from the body","haemorrhage,flow","B1"],
      ["bruise","noun","An area of discoloured skin caused by injury","contusion,mark","B1"],
      ["capsule","noun","A small case of medicine to be swallowed","pill,tablet","B1"],
      ["contagious","adj","Able to spread from one person to another","infectious,transmissible","B1"],
      ["dental","adj","Relating to the teeth","oral,tooth-related","B1"],
      ["disorder","noun","A disruption of normal physical or mental functions","condition,illness","B2"],
      ["epidemic","noun","A widespread occurrence of a disease","outbreak,plague","B2"],
      ["first aid","noun","Help given to a sick or injured person before treatment","emergency care,initial treatment","B2"],
      ["fracture","noun","A break, especially in a bone","break,crack","B2"],
      ["germs","noun","Microorganisms that cause disease","bacteria,microbes","B2"],
      ["heal","verb","To become healthy again after injury","recover,mend","B2"],
      ["injection","noun","The act of introducing a substance into the body with a needle","shot,jab","C1"],
      ["limb","noun","An arm or leg of a person","extremity,appendage","C1"],
      ["mental","adj","Relating to the mind","psychological,cognitive","C1"],
      ["nausea","noun","A feeling of sickness with an urge to vomit","queasiness,sickness","C1"],
      ["organ","noun","A part of the body with a specific function","body part,vital organ","C2"],
      ["physical","adj","Relating to the body","bodily,corporeal","A2"],
      ["pulse","noun","The rhythmic beating of blood through arteries","heartbeat,heart rate","A2"],
      ["rash","noun","An area of red spots on the skin","skin irritation,eruption","A2"],
      ["scar","noun","A mark left on the skin after a wound has healed","mark,blemish","A2"],
      ["swallow","verb","To cause food or drink to pass down the throat","ingest,gulp","B1"],
      ["tablet","noun","A flat disc of compressed medicine","pill,capsule","B1"],
      ["thermometer","noun","An instrument for measuring temperature","temperature gauge,heat meter","B1"],
      ["unconscious","adj","Not awake and aware of surroundings","senseless,knocked out","B1"],
      ["ward","noun","A room in a hospital for patients","hospital room,unit","B1"],
      ["x-ray","noun","An image produced by radiation to examine bones","radiograph,scan","B2"],
    ],
    environment: [
      ["acid rain","noun","Rainfall made acidic by atmospheric pollution","polluted rain,chemical rain","A2"],
      ["arctic","adj","Relating to the regions around the North Pole","polar,frigid","A2"],
      ["avalanche","noun","A mass of snow and ice falling rapidly down a mountain","snowslide,landslide","A2"],
      ["breeze","noun","A gentle wind","light wind,draught","A2"],
      ["bushfire","noun","A fire in scrub or forest land","wildfire,forest fire","B1"],
      ["canal","noun","An artificial waterway for navigation or irrigation","channel,waterway","B1"],
      ["cliff","noun","A steep rock face at the edge of land","bluff,escarpment","B1"],
      ["coast","noun","The land near the sea","shore,seashore","B1"],
      ["dam","noun","A barrier constructed to hold back water","barrage,weir","B1"],
      ["desert","noun","A dry barren area of land","wasteland,arid region","B2"],
      ["ecosystem","noun","A biological community of interacting organisms","biome,habitat","B2"],
      ["famine","noun","Extreme scarcity of food","starvation,food crisis","B2"],
      ["fog","noun","A thick cloud of tiny water droplets near the ground","mist,haze","B2"],
      ["forest","noun","A large area covered chiefly with trees","woodland,woods","B2"],
      ["frost","noun","A thin layer of ice on a surface","ice,rime","B2"],
      ["heatwave","noun","A prolonged period of abnormally hot weather","hot spell,extreme heat","C1"],
      ["iceberg","noun","A large floating mass of ice","ice mass,floating ice","C1"],
      ["island","noun","A piece of land surrounded by water","isle,atoll","C1"],
      ["jungle","noun","An area of land with dense tropical vegetation","rainforest,tropical forest","C1"],
      ["lake","noun","A large body of water surrounded by land","pond,reservoir","C2"],
      ["meadow","noun","A field of grass and wildflowers","pasture,grassland","A2"],
      ["mountain","noun","A large natural elevation of the earth s surface","peak,summit","A2"],
      ["ocean","noun","A very large expanse of sea","sea,deep","A2"],
      ["peak","noun","The pointed top of a mountain","summit,apex","A2"],
      ["reef","noun","A ridge of rock or coral at or near the sea surface","coral reef,shoal","B1"],
      ["river","noun","A large natural stream of water","waterway,stream","B1"],
      ["soil","noun","The upper layer of earth where plants grow","ground,earth","B1"],
      ["storm","noun","A violent disturbance of the atmosphere","tempest,gale","B1"],
      ["valley","noun","A low area of land between hills or mountains","dale,glen","B1"],
      ["waterfall","noun","A cascade of water falling from a height","cascade,falls","B2"],
    ],
    business: [
      ["agenda","noun","A list of items to be discussed at a meeting","schedule,programme","A2"],
      ["audit","noun","An official inspection of financial accounts","review,examination","A2"],
      ["branch","noun","A division of a large company","office,division","A2"],
      ["chairman","noun","A person who presides over a meeting or organisation","chairperson,president","A2"],
      ["compensation","noun","Something given to make up for loss or injury","payment,reimbursement","B1"],
      ["conference","noun","A formal meeting for discussion","summit,convention","B1"],
      ["consultant","noun","A person who provides expert advice professionally","advisor,specialist","B1"],
      ["corporate","adj","Relating to a large company or group","business,commercial","B1"],
      ["customer","noun","A person who buys goods or services","client,buyer","B1"],
      ["deliver","verb","To bring goods to the person who has ordered them","transport,distribute","B2"],
      ["department","noun","A division of a large organisation","section,unit","B2"],
      ["director","noun","A person who is in charge of an organisation","head,chief executive","B2"],
      ["distribute","verb","To give shares of something to a number of recipients","allocate,supply","B2"],
      ["efficient","adj","Achieving maximum productivity with minimum wasted effort","productive,effective","B2"],
      ["executive","noun","A person with senior management responsibility","manager,director","B2"],
      ["guarantee","noun","A promise that something will work as described","warranty,assurance","C1"],
      ["industry","noun","Economic activity concerned with manufacturing","sector,trade","C1"],
      ["invest","verb","To put money into something to earn a return","fund,finance","C1"],
      ["logo","noun","A symbol or design adopted by an organisation","emblem,trademark","C1"],
      ["manager","noun","A person responsible for controlling an organisation","supervisor,director","C2"],
      ["negotiation","noun","Discussion aimed at reaching an agreement","bargaining,mediation","A2"],
      ["objective","noun","A thing aimed at or sought; a goal","goal,target","A2"],
      ["pension","noun","A regular payment made to retired persons","retirement fund,annuity","A2"],
      ["product","noun","An article manufactured for sale","goods,merchandise","A2"],
      ["proposal","noun","A plan or suggestion put forward for consideration","proposition,plan","B1"],
      ["recruit","verb","To find new people to join an organisation","hire,employ","B1"],
      ["refund","noun","A repayment of a sum of money","reimbursement,return","B1"],
      ["resign","verb","To voluntarily leave a position","quit,step down","B1"],
      ["strategy","noun","A plan of action designed to achieve a goal","approach,plan","B1"],
      ["warehouse","noun","A large building for storing goods","depot,storehouse","B2"],
    ],
    economy: [
      ["bankrupt","adj","Declared legally unable to pay debts","insolvent,broke","A2"],
      ["bargain","noun","A good deal at a lower price","deal,offer","A2"],
      ["bond","noun","A fixed income investment instrument","security,note","A2"],
      ["borrow","verb","To take and use money with the intention of returning it","loan,get a loan","A2"],
      ["budget","verb","To plan how to spend money","plan financially,allocate funds","B1"],
      ["cashier","noun","A person who handles payments in a shop","checkout operator,teller","B1"],
      ["cheque","noun","A written order directing a bank to pay money","check,bank draft","B1"],
      ["cost","noun","The amount of money required for something","price,expense","B1"],
      ["credit","noun","The ability to buy now and pay later","loan,deferred payment","B1"],
      ["deposit","noun","A sum paid into a bank account","payment,down payment","B2"],
      ["earn","verb","To receive money in return for labour","make,gain","B2"],
      ["economic","adj","Relating to the economy or economics","financial,monetary","B2"],
      ["fee","noun","A payment made for professional services","charge,cost","B2"],
      ["fund","noun","A sum of money saved for a purpose","reserve,pool","B2"],
      ["grant","noun","Money given by a government or organisation","subsidy,funding","B2"],
      ["gross","adj","The total amount before deductions","total,overall","C1"],
      ["household","adj","Relating to a house and its occupants","domestic,family","C1"],
      ["income tax","noun","Tax levied directly on personal earnings","earnings tax,direct tax","C1"],
      ["lend","verb","To give something temporarily with expectation of return","loan,advance","C1"],
      ["net","adj","The amount remaining after deductions","after tax,take-home","C2"],
      ["owe","verb","To be indebted to someone for money","be in debt,have a liability","A2"],
      ["payment","noun","The act of paying money for goods or services","transaction,settlement","A2"],
      ["price","noun","The amount of money for which something is sold","cost,value","A2"],
      ["purchase","verb","To buy something","buy,acquire","A2"],
      ["receipt","noun","A written acknowledgement that money has been paid","proof of payment,slip","B1"],
      ["refund","verb","To return money to a buyer","reimburse,pay back","B1"],
      ["retail","adj","The sale of goods to consumers","consumer,shop","B1"],
      ["spend","verb","To pay out money for goods or services","expend,use","B1"],
      ["tax","noun","A compulsory payment to the government","levy,duty","B1"],
      ["wholesale","noun","The selling of goods in large quantities","bulk selling,trade selling","B2"],
    ],
    society: [
      ["abuse","noun","Cruel and violent treatment of a person","mistreatment,maltreatment","A2"],
      ["adopt","verb","To legally take another person s child as your own","take in,foster","A2"],
      ["ban","verb","To officially prohibit something","prohibit,forbid","A2"],
      ["campaign","noun","An organised course of action to achieve a goal","drive,movement","A2"],
      ["ceremony","noun","A formal public occasion","ritual,celebration","B1"],
      ["civil","adj","Relating to ordinary citizens and their concerns","civic,public","B1"],
      ["class","noun","A social division based on economic status","social group,caste","B1"],
      ["crime rate","noun","The number of crimes in an area over time","offence rate,criminal activity level","B1"],
      ["cultural","adj","Relating to the culture of a society","social,artistic","B1"],
      ["demonstrate","verb","To take part in a public protest","protest,march","B2"],
      ["donate","verb","To give money or goods to a cause","contribute,give","B2"],
      ["ethnic group","noun","A community sharing cultural traditions","cultural group,racial group","B2"],
      ["freedom","noun","The state of being free from restrictions","liberty,independence","B2"],
      ["gender","noun","The state of being male or female","sex,identity","B2"],
      ["heritage","noun","Valued objects and qualities from past generations","legacy,inheritance","B2"],
      ["homeless","noun","People without a permanent home","rough sleepers,displaced people","C1"],
      ["human rights","noun","Basic rights and freedoms to which all people are entitled","civil liberties,fundamental rights","C1"],
      ["justice","noun","The quality of being fair and reasonable","fairness,equity","C1"],
      ["migrant","noun","A person who moves from one place to another","immigrant,relocator","C1"],
      ["moral","adj","Concerned with the principles of right and wrong","ethical,virtuous","C2"],
      ["national","adj","Relating to a nation","countrywide,domestic","A2"],
      ["petition","verb","To make a formal request to an authority","appeal,request","A2"],
      ["poverty line","noun","The minimum income level for basic necessities","breadline,subsistence level","A2"],
      ["racial","adj","Relating to the differences between races","ethnic,interracial","A2"],
      ["security","noun","The state of being free from danger or threat","safety,protection","B1"],
      ["social","adj","Relating to society or its organisation","communal,public","B1"],
      ["status","noun","Relative social or professional standing","position,rank","B1"],
      ["tolerance","noun","Willingness to accept different opinions or behaviour","acceptance,open-mindedness","B1"],
      ["victim","noun","A person harmed by a crime or event","sufferer,casualty","B1"],
      ["youth","noun","The period between childhood and adulthood","adolescence,teenage years","B2"],
    ],
    culture: [
      ["ancestor","noun","A person from whom one is descended","forebear,predecessor","A2"],
      ["antique","noun","An object that is old and valuable","relic,collectible","A2"],
      ["ceremony","noun","A formal event performed on a special occasion","ritual,rite","A2"],
      ["civilisation","noun","An advanced state of human society","society,culture","A2"],
      ["costume","noun","A set of clothes in a style typical of a period or group","outfit,dress","B1"],
      ["custom","noun","A traditional practice or usual way of behaving","tradition,convention","B1"],
      ["dance","noun","A series of movements performed to music","choreography,ballet","B1"],
      ["diversity","noun","The state of having many different types of something","variety,range","B1"],
      ["ethnic","adj","Relating to a group sharing cultural identity","cultural,tribal","B1"],
      ["festival","noun","A day or period of celebration","feast,celebration","B2"],
      ["folklore","noun","Traditional beliefs and stories of a community","legends,myths","B2"],
      ["heritage","noun","Property or traditions inherited from past generations","legacy,birthright","B2"],
      ["identity","noun","The characteristics that define who someone is","character,selfhood","B2"],
      ["legend","noun","A traditional story sometimes regarded as historical","myth,tale","B2"],
      ["multicultural","adj","Relating to several cultural groups","diverse,pluralistic","B2"],
      ["myth","noun","A traditional story explaining a natural phenomenon","legend,fable","C1"],
      ["origin","noun","The point where something begins","source,beginning","C1"],
      ["preserve","verb","To maintain something in its original state","conserve,protect","C1"],
      ["ritual","noun","A ceremony consisting of a series of actions","rite,custom","C1"],
      ["sacred","adj","Regarded as holy or deserving great respect","holy,divine","C2"],
      ["sculpture","noun","A carved or cast figure or design","statue,carving","A2"],
      ["symbol","noun","A thing representing something else","emblem,sign","A2"],
      ["temple","noun","A building devoted to worship","shrine,sanctuary","A2"],
      ["tradition","noun","A custom handed down through generations","practice,convention","A2"],
      ["tribal","adj","Relating to a tribe or tribal culture","indigenous,native","B1"],
      ["unique","adj","Being the only one of its kind","distinctive,one of a kind","B1"],
      ["value","noun","Principles or standards of behaviour","belief,moral","B1"],
      ["worship","verb","To show reverence and adoration for a deity","pray,revere","B1"],
    ],
    science: [
      ["atom","noun","The smallest unit of a chemical element","particle,molecule","A2"],
      ["bacteria","noun","Microscopic single-celled organisms","microbes,germs","A2"],
      ["cell","noun","The smallest structural unit of an organism","unit,building block","A2"],
      ["chemical","noun","A substance produced by or used in chemistry","compound,substance","A2"],
      ["clone","noun","An organism genetically identical to another","copy,replica","B1"],
      ["conduct","verb","To carry out a scientific experiment","perform,execute","B1"],
      ["discovery","noun","The act of finding something for the first time","finding,breakthrough","B1"],
      ["DNA","noun","The molecule carrying genetic instructions","genetic code,deoxyribonucleic acid","B1"],
      ["element","noun","A substance that cannot be broken down further","component,basic substance","B1"],
      ["energy","noun","The capacity for doing work","power,force","B2"],
      ["evolution","noun","The process of gradual development over time","development,progression","B2"],
      ["experiment","noun","A scientific procedure to test a hypothesis","test,trial","B2"],
      ["formula","noun","A mathematical or chemical symbolic expression","equation,expression","B2"],
      ["gene","noun","A unit of heredity in a living organism","DNA segment,hereditary unit","B2"],
      ["gravity","noun","The force that attracts objects toward the earth","gravitational pull,attraction","B2"],
      ["hypothesis","noun","A proposed explanation for a phenomenon","theory,assumption","C1"],
      ["laboratory","noun","A room equipped for scientific research","lab,research facility","C1"],
      ["microscope","noun","An instrument for viewing very small objects","magnifier,optical instrument","C1"],
      ["molecule","noun","A group of atoms bonded together","compound,particle","C1"],
      ["nucleus","noun","The central part of an atom or cell","core,centre","C2"],
      ["observation","noun","The act of watching something carefully","monitoring,examination","A2"],
      ["organism","noun","A living animal, plant, or single-celled life form","creature,being","A2"],
      ["particle","noun","A tiny portion of matter","speck,fragment","A2"],
      ["phenomenon","noun","A fact or situation observed to exist","occurrence,event","A2"],
      ["physics","noun","The science of matter, energy, and their interactions","natural science,physical science","B1"],
      ["radiation","noun","Energy emitted in the form of waves or particles","emission,rays","B1"],
      ["research","noun","Systematic investigation to establish facts","study,investigation","B1"],
      ["species","noun","A group of similar organisms capable of interbreeding","type,kind","B1"],
      ["theory","noun","A system of ideas intended to explain something","hypothesis,concept","B1"],
      ["vaccine","noun","A substance used to provide immunity against disease","immunisation,inoculation","B2"],
    ],
    history: [
      ["ancient","adj","Belonging to the very distant past","old,antique","A2"],
      ["archaeologist","noun","A person who studies human history through excavation","digger,historian","A2"],
      ["artefact","noun","An object made by a human being in the past","relic,antiquity","A2"],
      ["battle","noun","A sustained fight between armed forces","conflict,engagement","A2"],
      ["century","noun","A period of one hundred years","hundred years,era","B1"],
      ["chronicle","noun","A factual written account of historical events","record,annals","B1"],
      ["civilisation","noun","A complex human society with cultural development","culture,society","B1"],
      ["colony","noun","A territory under the control of another country","settlement,dominion","B1"],
      ["conquer","verb","To overcome and take control of a place by force","defeat,subjugate","B1"],
      ["decade","noun","A period of ten years","ten years,period","B2"],
      ["dynasty","noun","A succession of rulers from the same family","ruling family,royal line","B2"],
      ["empire","noun","A group of states ruled over by a single authority","realm,kingdom","B2"],
      ["era","noun","A long and distinct period of history","age,epoch","B2"],
      ["excavation","noun","The process of digging up archaeological remains","dig,unearthing","B2"],
      ["historical","adj","Relating to or concerning history","past,bygone","B2"],
      ["independence","noun","The state of being free from outside control","freedom,sovereignty","C1"],
      ["invasion","noun","An instance of invading a country by military force","attack,incursion","C1"],
      ["kingdom","noun","A country ruled by a king or queen","realm,monarchy","C1"],
      ["medieval","adj","Relating to the Middle Ages","middle ages,feudal","C1"],
      ["monument","noun","A structure built to commemorate something","memorial,statue","C2"],
      ["palace","noun","The official residence of a ruler","royal residence,castle","A2"],
      ["pharaoh","noun","A ruler in ancient Egypt","Egyptian king,monarch","A2"],
      ["prehistoric","adj","Relating to the time before written records","ancient,primeval","A2"],
      ["reign","noun","The period of rule of a monarch","rule,sovereignty","A2"],
      ["revolution","noun","A forcible overthrow of a government","uprising,revolt","B1"],
      ["ruin","noun","The remains of a building that has been destroyed","remains,wreckage","B1"],
      ["settler","noun","A person who moves to a new area to live","colonist,pioneer","B1"],
      ["slave","noun","A person who is the legal property of another","servant,bondsman","B1"],
      ["tomb","noun","A burial place for a dead person","grave,sepulchre","B1"],
      ["warrior","noun","A brave or experienced soldier","fighter,combatant","B2"],
    ],
  },
  collocations: {
    education: [
      ["acquire skills","To develop new abilities through practice","gain skills,develop competencies","A2"],
      ["broaden horizons","To expand one s range of interests or knowledge","widen perspectives,expand knowledge","A2"],
      ["catch up with classmates","To reach the same level as others in a class","keep pace,close the gap","A2"],
      ["deliver a lecture","To give a formal academic talk","give a presentation,present a topic","A2"],
      ["do research","To investigate a subject systematically","conduct research,carry out a study","B1"],
      ["follow instructions","To do what you are told to do","obey directions,comply with guidance","B1"],
      ["further education","To continue studying after school","continue learning,advance education","B1"],
      ["get good grades","To receive high marks in assessments","score well,achieve high marks","B1"],
      ["keep up with studies","To manage to stay current with coursework","stay on top of work,maintain progress","B1"],
      ["memorise facts","To commit information to memory","learn by rote,remember data","B2"],
      ["pursue a career","To work towards a particular profession","follow a career path,seek a vocation","B2"],
      ["receive an education","To be taught at a school or institution","get schooling,be educated","B2"],
      ["skip a class","To deliberately not attend a lesson","miss a lesson,cut a class","B2"],
      ["submit an essay","To hand in a piece of written work","turn in a paper,present an assignment","B2"],
      ["study abroad","To attend an educational institution in another country","learn overseas,study in a foreign country","B2"],
      ["take an exam","To sit a formal test","do a test,write an examination","C1"],
    ],
    technology: [
      ["artificial intelligence","The simulation of human intelligence by machines","AI,machine learning","A2"],
      ["browse social media","To look through social networking content","scroll through feeds,check social networks","A2"],
      ["connect to WiFi","To link a device to a wireless network","join a network,get wireless access","A2"],
      ["develop an application","To create a software program","build an app,program software","A2"],
      ["go digital","To switch from physical to electronic methods","digitise,move online","B1"],
      ["hack into a system","To gain unauthorised access to a computer","breach security,infiltrate a network","B1"],
      ["keep up with technology","To stay current with technological advances","stay updated,follow tech trends","B1"],
      ["plug in a device","To connect equipment to an electrical supply","connect a device,power a gadget","B1"],
      ["protect personal data","To keep private information safe","safeguard privacy,secure information","B1"],
      ["set up an account","To create a new user profile on a service","register,create a profile","B2"],
      ["surf the internet","To browse websites casually","go online,explore the web","B2"],
      ["take a selfie","To photograph yourself with a smartphone","snap a self-portrait,photograph yourself","B2"],
      ["turn on a computer","To start a computer by pressing the power button","boot up,switch on","B2"],
      ["update a profile","To change information on an online account","edit an account,modify settings","B2"],
      ["use a search engine","To find information on the internet","google something,search online","B2"],
      ["wipe data","To permanently delete all information from a device","erase data,clear storage","C1"],
    ],
    health: [
      ["build stamina","To develop endurance through exercise","increase endurance,develop fitness","A2"],
      ["burn calories","To use energy through physical activity","expend energy,work off food","A2"],
      ["catch a disease","To become infected with an illness","contract an illness,get sick","A2"],
      ["do a blood test","To have blood analysed for medical purposes","take a blood sample,run blood work","A2"],
      ["eat healthily","To consume a nutritious and balanced diet","have a good diet,eat well","B1"],
      ["feel under the weather","To feel slightly ill","feel unwell,be a bit sick","B1"],
      ["give up smoking","To stop the habit of smoking tobacco","quit smoking,stop smoking","B1"],
      ["have a sore throat","To experience pain in the throat","suffer from throat pain,have throat discomfort","B1"],
      ["keep fit","To maintain good physical health","stay in shape,exercise regularly","B1"],
      ["monitor health","To check and track physical wellbeing regularly","track fitness,check vital signs","B2"],
      ["put on weight","To become heavier","gain weight,increase body mass","B2"],
      ["spread infection","To cause a disease to pass to others","transmit germs,pass on illness","B2"],
      ["strengthen muscles","To make muscles firmer and stronger","build muscle,tone up","B2"],
      ["suffer side effects","To experience unwanted effects from medicine","have adverse reactions,experience complications","B2"],
      ["take a deep breath","To inhale slowly and deeply","breathe deeply,fill your lungs","B2"],
      ["wear a mask","To put a protective covering over the face","use a face covering,put on a mask","C1"],
    ],
    environment: [
      ["build a dam","To construct a barrier to hold back water","create a reservoir,erect a barrage","A2"],
      ["chop down trees","To cut trees so they fall","fell trees,clear forest","A2"],
      ["clear a forest","To remove all trees from an area of land","deforest,strip woodland","A2"],
      ["create a nature reserve","To establish a protected area for wildlife","set up a sanctuary,designate a preserve","A2"],
      ["dump waste","To dispose of rubbish irresponsibly","throw away trash,discard refuse","B1"],
      ["emit greenhouse gases","To release gases that trap heat in the atmosphere","produce carbon,discharge pollutants","B1"],
      ["face a drought","To experience a long period without rain","suffer water shortage,endure dry conditions","B1"],
      ["harvest crops","To gather ripe crops from the fields","reap produce,pick crops","B1"],
      ["melt glaciers","For large ice masses to turn to water due to heat","thaw ice,lose ice cover","B1"],
      ["preserve natural habitats","To protect areas where animals and plants live","conserve ecosystems,maintain wildlife areas","B2"],
      ["purify water","To make water clean and safe to drink","clean water,filter water","B2"],
      ["release carbon dioxide","To emit CO2 into the atmosphere","produce CO2,discharge carbon","B2"],
      ["restore ecosystems","To return natural environments to their original state","rehabilitate habitats,renew ecology","B2"],
      ["run out of resources","To use up the available supply of materials","deplete resources,exhaust supplies","B2"],
      ["sort rubbish","To separate waste into different categories","segregate waste,categorise trash","B2"],
      ["threaten biodiversity","To put the variety of life at risk","endanger species,harm wildlife diversity","C1"],
    ],
    business: [
      ["break even","To make neither a profit nor a loss","cover costs,reach break-even point","A2"],
      ["carry out market research","To investigate consumer needs and preferences","conduct surveys,analyse the market","A2"],
      ["chair a meeting","To lead and control a formal meeting","preside over a meeting,run a meeting","A2"],
      ["draft a proposal","To write a preliminary version of a plan","prepare a proposal,write up a plan","A2"],
      ["enter the market","To start selling products in a particular area","join the market,begin trading","B1"],
      ["fill a vacancy","To find someone for an empty job position","hire for a role,recruit for a post","B1"],
      ["gain experience","To acquire knowledge through work","build expertise,develop skills","B1"],
      ["go bankrupt","To be declared unable to pay debts","become insolvent,fail financially","B1"],
      ["increase market share","To grow a company s portion of total sales","expand presence,capture more of the market","B1"],
      ["lay off workers","To dismiss employees due to lack of work","make redundant,let staff go","B2"],
      ["meet customer needs","To provide what customers want","satisfy demand,fulfil requirements","B2"],
      ["offer a discount","To reduce the price of goods or services","give a price cut,provide a reduction","B2"],
      ["place an advertisement","To pay for a promotional notice","run an ad,publish a commercial","B2"],
      ["set a budget","To establish a financial plan","create a spending plan,allocate funds","B2"],
      ["take out a loan","To borrow money from a bank","secure a loan,get financing","B2"],
      ["work in partnership","To collaborate with another person or company","cooperate,work together","C1"],
    ],
    economy: [
      ["accumulate wealth","To gradually gather riches over time","build fortune,amass assets","A2"],
      ["boost consumer confidence","To increase public trust in the economy","raise optimism,improve sentiment","A2"],
      ["cause a recession","To trigger an economic downturn","lead to a slump,provoke a decline","A2"],
      ["diversify investments","To spread money across different asset types","vary portfolio,spread risk","A2"],
      ["experience growth","To go through a period of economic expansion","see an upturn,have a boom","B1"],
      ["face financial difficulties","To encounter money problems","struggle financially,be in trouble","B1"],
      ["increase exports","To sell more goods to foreign countries","boost foreign sales,grow trade","B1"],
      ["lower the cost of living","To reduce everyday expenses","decrease living expenses,cut daily costs","B1"],
      ["manage debt","To handle financial obligations responsibly","control borrowing,service loans","B1"],
      ["print money","For a central bank to issue new currency","increase money supply,expand currency","B2"],
      ["raise the minimum wage","To increase the lowest legal pay rate","hike base pay,boost lowest wages","B2"],
      ["reduce government spending","To cut public expenditure","trim the budget,lower state costs","B2"],
      ["regulate the market","To control economic activity through rules","supervise commerce,oversee trade","B2"],
      ["stabilise the currency","To prevent large changes in money value","steady exchange rates,support the currency","B2"],
      ["suffer from poverty","To live with very little money or resources","endure hardship,experience destitution","B2"],
      ["support small businesses","To help and encourage local enterprises","aid local firms,back small companies","C1"],
    ],
    history: [
      ["build an empire","To create a large and powerful state","establish dominion,expand territory","A2"],
      ["declare independence","To formally announce freedom from another country","proclaim sovereignty,assert autonomy","A2"],
      ["discover a civilisation","To find evidence of a past human society","unearth a culture,find ancient remains","A2"],
      ["fight a battle","To engage in armed conflict","wage war,enter combat","A2"],
      ["form an alliance","To create a union between groups or countries","make a pact,establish a partnership","B1"],
      ["invade a country","To enter a territory with armed forces","attack a nation,conquer a land","B1"],
      ["lead a revolution","To direct an uprising against authority","head a revolt,command an insurrection","B1"],
      ["make a discovery","To find something for the first time","uncover,reveal","B1"],
      ["overthrow a government","To remove a ruling power by force","topple a regime,stage a coup","B1"],
      ["preserve artefacts","To protect historical objects from damage","conserve relics,maintain antiquities","B2"],
      ["record history","To write down accounts of past events","document the past,chronicle events","B2"],
      ["restore a monument","To repair and return a memorial to its original state","renovate a landmark,rebuild a memorial","B2"],
      ["rule a kingdom","To govern a territory as a monarch","reign over a land,control a realm","B2"],
      ["settle a territory","To establish a community in a new area","colonise land,pioneer a region","B2"],
      ["sign a peace treaty","To formally agree to end a conflict","make peace,end hostilities","B2"],
      ["trace origins","To find the beginning or source of something","discover roots,investigate ancestry","C1"],
    ],
    science: [
      ["carry out an experiment","To perform a scientific test","conduct a trial,run a study","A2"],
      ["collect data","To gather information for analysis","accumulate information,compile results","A2"],
      ["come to a conclusion","To reach a final decision after analysis","draw a conclusion,arrive at a result","A2"],
      ["develop a theory","To create an explanation for observed facts","formulate a hypothesis,propose a concept","A2"],
      ["discover a cure","To find a remedy for a disease","find a treatment,develop a medicine","B1"],
      ["do fieldwork","To conduct research outside a laboratory","study in the field,investigate on site","B1"],
      ["form a hypothesis","To propose a tentative explanation","suggest a theory,make an assumption","B1"],
      ["launch a satellite","To send an object into orbit around the earth","deploy a satellite,put into orbit","B1"],
      ["make a breakthrough","To achieve a sudden important discovery","have a eureka moment,reach a milestone","B1"],
      ["observe a phenomenon","To watch and study a natural event","monitor an occurrence,examine an event","B2"],
      ["perform surgery","To carry out a medical operation","do an operation,operate on a patient","B2"],
      ["prove a theory","To demonstrate that an explanation is correct","confirm a hypothesis,verify a concept","B2"],
      ["publish findings","To make research results available to others","release results,report discoveries","B2"],
      ["run a simulation","To use a model to test possible outcomes","model a scenario,simulate conditions","B2"],
      ["test a hypothesis","To check if a proposed explanation is correct","examine a theory,trial a concept","B2"],
      ["weigh evidence","To consider the strength of facts carefully","assess proof,evaluate data","C1"],
    ],
  },
};
