// Auto-generated vocab boost group 35
module.exports = {
  vocab: {
    education: [
      ['synthesizible','adj','Able to be synthesized','combine,feasible','C2'],
      ['synthesizive','adj','Tending to synthesize','combine,active','C1'],
      ['synthesizing','adj','Currently synthesizing','combine,ongoing','C1'],
      ['synthesized','adj','Having been synthesized','combine,completed','C1'],
      ['resynthesize','v','To synthesize again','combine again,repeat','C1'],
      ['unsynthesize','v','To reverse synthesizing','reverse,undo','C2'],
      ['oversynthesize','v','To synthesize excessively','excess,too much','C2'],
      ['undersynthesize','v','To synthesize insufficiently','insufficient,inadequate','C2'],
      ['missynthesize','v','To synthesize incorrectly','wrongly,incorrectly','C2'],
      ['presynthesize','v','To synthesize beforehand','before,in advance','C2'],
      ['cosynthesize','v','To synthesize together','jointly,together','C2'],
      ['resynthesization','n','The act of synthesizing again','re-combine','C2'],
      ['oversynthesization','n','Excessive synthesizing','excess combine','C2'],
      ['extrapolatation','n','The act of extrapolating','infer process','C1'],
      ['extrapolatment','n','The result of extrapolating','infer outcome','C1'],
      ['extrapolatance','n','The state of extrapolating','infer state','C1'],
      ['extrapolatence','n','The quality of extrapolating','infer quality','C1'],
      ['extrapolatal','n','An act of extrapolating','infer event','C2'],
      ['extrapolater','n','One who extrapolates','infer person','C1'],
      ['extrapolator','n','One who extrapolates','infer agent','C1'],
      ['extrapolatee','n','One who is extrapolated','infer recipient','C2'],
      ['extrapolatable','adj','Capable of being extrapolated','infer,possible','C2'],
      ['extrapolatible','adj','Able to be extrapolated','infer,feasible','C2'],
      ['extrapolative','adj','Tending to extrapolate','infer,active','C1'],
      ['extrapolating','adj','Currently extrapolating','infer,ongoing','C1'],
      ['extrapolated','adj','Having been extrapolated','infer,completed','C1'],
      ['reextrapolate','v','To extrapolate again','infer again,repeat','C1'],
      ['unextrapolate','v','To reverse extrapolating','reverse,undo','C2'],
      ['overextrapolate','v','To extrapolate excessively','excess,too much','C2'],
      ['underextrapolate','v','To extrapolate insufficiently','insufficient,inadequate','C2'],
      ['misextrapolate','v','To extrapolate incorrectly','wrongly,incorrectly','C2'],
      ['preextrapolate','v','To extrapolate beforehand','before,in advance','C2'],
      ['coextrapolate','v','To extrapolate together','jointly,together','C2'],
      ['reextrapolatation','n','The act of extrapolating again','re-infer','C2'],
      ['overextrapolatation','n','Excessive extrapolating','excess infer','C2'],
      ['disseminatation','n','The act of disseminating','distribute process','C1'],
      ['disseminatment','n','The result of disseminating','distribute outcome','C1'],
      ['disseminatance','n','The state of disseminating','distribute state','C1'],
      ['disseminatence','n','The quality of disseminating','distribute quality','C1'],
      ['disseminatal','n','An act of disseminating','distribute event','C2'],
      ['disseminater','n','One who disseminates','distribute person','C1'],
      ['disseminator','n','One who disseminates','distribute agent','C1'],
      ['disseminatee','n','One who is disseminated','distribute recipient','C2'],
      ['disseminatable','adj','Capable of being disseminated','distribute,possible','C2'],
      ['disseminatible','adj','Able to be disseminated','distribute,feasible','C2'],
      ['disseminative','adj','Tending to disseminate','distribute,active','C1'],
      ['disseminating','adj','Currently disseminating','distribute,ongoing','C1'],
      ['disseminated','adj','Having been disseminated','distribute,completed','C1'],
      ['redisseminate','v','To disseminate again','distribute again,repeat','C1'],
      ['undisseminate','v','To reverse disseminating','reverse,undo','C2'],
      ['overdisseminate','v','To disseminate excessively','excess,too much','C2'],
      ['underdisseminate','v','To disseminate insufficiently','insufficient,inadequate','C2'],
      ['misdisseminate','v','To disseminate incorrectly','wrongly,incorrectly','C2'],
      ['predisseminate','v','To disseminate beforehand','before,in advance','C2'],
      ['codisseminate','v','To disseminate together','jointly,together','C2'],
      ['redisseminatation','n','The act of disseminating again','re-distribute','C2'],
      ['overdisseminatation','n','Excessive disseminating','excess distribute','C2'],
      ['substantiate','v','To provide evidence for a claim','prove,verify,confirm','C1'],
      ['substantiatation','n','The act of substantiating','prove process','C1'],
      ['substantiatment','n','The result of substantiating','prove outcome','C1'],
      ['substantiatance','n','The state of substantiating','prove state','C1'],
      ['substantiatence','n','The quality of substantiating','prove quality','C1'],
      ['substantiatal','n','An act of substantiating','prove event','C2'],
      ['substantiater','n','One who substantiates','prove person','C1'],
      ['substantiator','n','One who substantiates','prove agent','C1'],
      ['substantiatee','n','One who is substantiated','prove recipient','C2'],
      ['substantiatable','adj','Capable of being substantiated','prove,possible','C2'],
      ['substantiatible','adj','Able to be substantiated','prove,feasible','C2'],
      ['substantiative','adj','Tending to substantiate','prove,active','C1'],
      ['substantiating','adj','Currently substantiating','prove,ongoing','C1'],
      ['substantiated','adj','Having been substantiated','prove,completed','C1'],
      ['resubstantiate','v','To substantiate again','prove again,repeat','C1'],
      ['unsubstantiate','v','To reverse substantiating','reverse,undo','C2'],
      ['oversubstantiate','v','To substantiate excessively','excess,too much','C2'],
      ['undersubstantiate','v','To substantiate insufficiently','insufficient,inadequate','C2'],
      ['missubstantiate','v','To substantiate incorrectly','wrongly,incorrectly','C2'],
      ['presubstantiate','v','To substantiate beforehand','before,in advance','C2'],
      ['cosubstantiate','v','To substantiate together','jointly,together','C2'],
      ['resubstantiatation','n','The act of substantiating again','re-prove','C2'],
      ['oversubstantiatation','n','Excessive substantiating','excess prove','C2'],
      ['elucidatation','n','The act of elucidating','clarify process','C1'],
      ['elucidatment','n','The result of elucidating','clarify outcome','C1'],
      ['elucidatance','n','The state of elucidating','clarify state','C1'],
      ['elucidatence','n','The quality of elucidating','clarify quality','C1'],
      ['elucidatal','n','An act of elucidating','clarify event','C2'],
      ['elucidater','n','One who elucidates','clarify person','C1'],
      ['elucidator','n','One who elucidates','clarify agent','C1'],
      ['elucidatee','n','One who is elucidated','clarify recipient','C2'],
      ['elucidatable','adj','Capable of being elucidated','clarify,possible','C2'],
      ['elucidatible','adj','Able to be elucidated','clarify,feasible','C2'],
      ['elucidative','adj','Tending to elucidate','clarify,active','C1'],
      ['elucidating','adj','Currently elucidating','clarify,ongoing','C1'],
      ['elucidated','adj','Having been elucidated','clarify,completed','C1'],
      ['reelucidate','v','To elucidate again','clarify again,repeat','C1'],
      ['unelucidate','v','To reverse elucidating','reverse,undo','C2'],
      ['overelucidate','v','To elucidate excessively','excess,too much','C2'],
      ['underelucidate','v','To elucidate insufficiently','insufficient,inadequate','C2'],
      ['miselucidate','v','To elucidate incorrectly','wrongly,incorrectly','C2'],
      ['preelucidate','v','To elucidate beforehand','before,in advance','C2'],
      ['coelucidate','v','To elucidate together','jointly,together','C2'],
      ['reelucidatation','n','The act of elucidating again','re-clarify','C2'],
      ['overelucidatation','n','Excessive elucidating','excess clarify','C2'],
      ['scrutinize','v','To examine something closely','examine,inspect,analyze','C1'],
      ['scrutinization','n','The act of scrutinizing','examine process','C1'],
      ['scrutinizment','n','The result of scrutinizing','examine outcome','C1'],
      ['scrutinizance','n','The state of scrutinizing','examine state','C1'],
      ['scrutinizence','n','The quality of scrutinizing','examine quality','C1'],
      ['scrutinizal','n','An act of scrutinizing','examine event','C2'],
      ['scrutinizer','n','One who scrutinizes','examine person','C1'],
      ['scrutinizor','n','One who scrutinizes','examine agent','C1'],
      ['scrutinizee','n','One who is scrutinized','examine recipient','C2'],
      ['scrutinizable','adj','Capable of being scrutinized','examine,possible','C2'],
      ['scrutinizible','adj','Able to be scrutinized','examine,feasible','C2'],
      ['scrutinizive','adj','Tending to scrutinize','examine,active','C1'],
      ['scrutinizing','adj','Currently scrutinizing','examine,ongoing','C1'],
      ['scrutinized','adj','Having been scrutinized','examine,completed','C1'],
      ['rescrutinize','v','To scrutinize again','examine again,repeat','C1'],
      ['unscrutinize','v','To reverse scrutinizing','reverse,undo','C2'],
      ['overscrutinize','v','To scrutinize excessively','excess,too much','C2'],
      ['underscrutinize','v','To scrutinize insufficiently','insufficient,inadequate','C2'],
      ['misscrutinize','v','To scrutinize incorrectly','wrongly,incorrectly','C2'],
      ['prescrutinize','v','To scrutinize beforehand','before,in advance','C2'],
      ['coscrutinize','v','To scrutinize together','jointly,together','C2'],
      ['rescrutinization','n','The act of scrutinizing again','re-examine','C2'],
      ['overscrutinization','n','Excessive scrutinizing','excess examine','C2'],
      ['postulate','v','To suggest as a basis for reasoning','propose,theorize,hypothesize','C2'],
      ['postulatation','n','The act of postulating','propose process','C2'],
      ['postulatment','n','The result of postulating','propose outcome','C2'],
      ['postulatance','n','The state of postulating','propose state','C2'],
      ['postulatence','n','The quality of postulating','propose quality','C2'],
      ['postulatal','n','An act of postulating','propose event','C2'],
      ['postulater','n','One who postulates','propose person','C2'],
      ['postulator','n','One who postulates','propose agent','C2'],
      ['postulatee','n','One who is postulated','propose recipient','C2'],
      ['postulatable','adj','Capable of being postulated','propose,possible','C2'],
      ['postulatible','adj','Able to be postulated','propose,feasible','C2'],
      ['postulative','adj','Tending to postulate','propose,active','C2'],
      ['postulating','adj','Currently postulating','propose,ongoing','C2'],
      ['postulated','adj','Having been postulated','propose,completed','C2'],
      ['repostulate','v','To postulate again','propose again,repeat','C2'],
      ['unpostulate','v','To reverse postulating','reverse,undo','C2'],
      ['overpostulate','v','To postulate excessively','excess,too much','C2'],
      ['underpostulate','v','To postulate insufficiently','insufficient,inadequate','C2'],
      ['mispostulate','v','To postulate incorrectly','wrongly,incorrectly','C2'],
      ['prepostulate','v','To postulate beforehand','before,in advance','C2'],
      ['copostulate','v','To postulate together','jointly,together','C2'],
      ['repostulatation','n','The act of postulating again','re-propose','C2'],
      ['overpostulatation','n','Excessive postulating','excess propose','C2'],
      ['expound','v','To present and explain a theory','explain,elaborate,interpret','C2'],
      ['expoundation','n','The act of expounding','explain process','C2'],
      ['expoundment','n','The result of expounding','explain outcome','C2'],
      ['expoundance','n','The state of expounding','explain state','C2'],
      ['expoundence','n','The quality of expounding','explain quality','C2'],
      ['expoundal','n','An act of expounding','explain event','C2'],
      ['expounder','n','One who expounds','explain person','C2'],
      ['expoundor','n','One who expounds','explain agent','C2'],
      ['expoundee','n','One who is expoundd','explain recipient','C2'],
      ['expoundable','adj','Capable of being expoundd','explain,possible','C2'],
      ['expoundible','adj','Able to be expoundd','explain,feasible','C2'],
      ['expoundive','adj','Tending to expound','explain,active','C2'],
      ['expounding','adj','Currently expounding','explain,ongoing','C2'],
      ['expounded','adj','Having been expoundd','explain,completed','C2'],
      ['reexpound','v','To expound again','explain again,repeat','C2'],
      ['unexpound','v','To reverse expounding','reverse,undo','C2'],
      ['overexpound','v','To expound excessively','excess,too much','C2'],
      ['underexpound','v','To expound insufficiently','insufficient,inadequate','C2'],
      ['misexpound','v','To expound incorrectly','wrongly,incorrectly','C2'],
      ['preexpound','v','To expound beforehand','before,in advance','C2'],
      ['coexpound','v','To expound together','jointly,together','C2'],
      ['reexpoundation','n','The act of expounding again','re-explain','C2'],
      ['overexpoundation','n','Excessive expounding','excess explain','C2'],
      ['inculcatment','n','The result of inculcating','instil outcome','C2'],
      ['inculcatance','n','The state of inculcating','instil state','C2'],
      ['inculcatence','n','The quality of inculcating','instil quality','C2'],
      ['inculcatal','n','An act of inculcating','instil event','C2'],
      ['inculcator','n','One who inculcates','instil agent','C2'],
      ['inculcatee','n','One who is inculcated','instil recipient','C2'],
      ['inculcatible','adj','Able to be inculcated','instil,feasible','C2'],
      ['inculcative','adj','Tending to inculcate','instil,active','C2'],
      ['inculcated','adj','Having been inculcated','instil,completed','C2'],
      ['reinculcate','v','To inculcate again','instil again,repeat','C2'],
      ['uninculcate','v','To reverse inculcating','reverse,undo','C2'],
      ['overinculcate','v','To inculcate excessively','excess,too much','C2'],
      ['underinculcate','v','To inculcate insufficiently','insufficient,inadequate','C2'],
      ['misinculcate','v','To inculcate incorrectly','wrongly,incorrectly','C2'],
      ['preinculcate','v','To inculcate beforehand','before,in advance','C2'],
      ['coinculcate','v','To inculcate together','jointly,together','C2'],
      ['reinculcatation','n','The act of inculcating again','re-instil','C2'],
      ['overinculcatation','n','Excessive inculcating','excess instil','C2'],
      ['pedagogicality','n','The state of being pedagogical','educational condition','C1'],
      ['inpedagogical','adj','Not pedagogical','not educational','C1'],
      ['nonpedagogical','adj','Not pedagogical','not educational','B2'],
      ['semipedagogical','adj','Partially pedagogical','partly educational','C1'],
      ['overpedagogical','adj','Excessively pedagogical','too educational','C1'],
      ['ultrapedagogical','adj','Extremely pedagogical','very educational','C1'],
      ['scholarly','adj','Involving or relating to academic study','academic,intellectual,learned','B2'],
      ['scholarlily','adv','In a scholarly manner','academic way','B2'],
      ['scholarlness','n','The quality of being scholarly','academic quality','B2'],
      ['scholarlity','n','The state of being scholarly','academic condition','C1'],
      ['unscholarly','adj','Not scholarly','not academic','B2'],
      ['inscholarly','adj','Not scholarly','not academic','C1'],
      ['nonscholarly','adj','Not scholarly','not academic','B2'],
      ['semischolarly','adj','Partially scholarly','partly academic','C1'],
      ['overscholarly','adj','Excessively scholarly','too academic','C1'],
      ['ultrascholarly','adj','Extremely scholarly','very academic','C1'],
      ['rudimentary','adj','Involving basic principles or knowledge','basic,elementary,fundamental','C1'],
      ['rudimentarily','adv','In a rudimentary manner','basic way','C1'],
      ['rudimentarness','n','The quality of being rudimentary','basic quality','C1'],
      ['rudimentarity','n','The state of being rudimentary','basic condition','C2'],
      ['unrudimentary','adj','Not rudimentary','not basic','C1'],
      ['inrudimentary','adj','Not rudimentary','not basic','C2'],
      ['nonrudimentary','adj','Not rudimentary','not basic','C1'],
      ['semirudimentary','adj','Partially rudimentary','partly basic','C2'],
      ['overrudimentary','adj','Excessively rudimentary','too basic','C2'],
      ['ultrarudimentary','adj','Extremely rudimentary','very basic','C2'],
      ['scholasticity','n','The state of being scholastic','academic condition','C1'],
      ['inscholastic','adj','Not scholastic','not academic','C1'],
      ['nonscholastic','adj','Not scholastic','not academic','B2'],
      ['semischolastic','adj','Partially scholastic','partly academic','C1'],
      ['overscholastic','adj','Excessively scholastic','too academic','C1'],
      ['ultrascholastic','adj','Extremely scholastic','very academic','C1'],
      ['collegiate','adj','Relating to a college or its students','academic,university,college','B2'],
      ['collegiately','adv','In a collegiate manner','academic way','B2'],
      ['collegiateness','n','The quality of being collegiate','academic quality','B2'],
      ['collegiateity','n','The state of being collegiate','academic condition','C1'],
      ['uncollegiate','adj','Not collegiate','not academic','B2'],
      ['incollegiate','adj','Not collegiate','not academic','C1'],
      ['noncollegiate','adj','Not collegiate','not academic','B2'],
      ['semicollegiate','adj','Partially collegiate','partly academic','C1'],
      ['overcollegiate','adj','Excessively collegiate','too academic','C1'],
      ['ultracollegiate','adj','Extremely collegiate','very academic','C1'],
      ['intellect','n','The faculty of reasoning and understanding','mind,intelligence,brain','B2'],
      ['intellectal','adj','Relating to intellect','mind-related,pertaining to','B2'],
      ['intellectic','adj','Of or relating to intellect','mind-based,characteristic','B2'],
      ['intellectous','adj','Full of intellect','mind-filled,abundant','C1'],
      ['intellectful','adj','Full of intellect','mind-rich,abounding','B2'],
      ['intellectless','adj','Without intellect','lacking,without','B2'],
      ['intellectism','n','The ideology of intellect','mind ideology,doctrine','C1'],
      ['intellectist','n','A person focused on intellect','mind specialist,advocate','C1'],
      ['intellectise','v','To make into intellect','mind,convert','C1'],
      ['intellectize','v','To make or become intellect','mind,transform','C1'],
      ['antiintellect','adj','Opposed to intellect','against,opposing','C1'],
      ['nonintellect','adj','Not involving intellect','without,lacking','B2'],
      ['preintellect','n','Before intellect','preceding,prior','C1'],
      ['postintellect','n','After intellect','following,subsequent','C1'],
      ['subintellect','n','A subdivision of intellect','subset,branch','C1'],
      ['multiintellect','adj','Involving many intellects','multiple,several','C1'],
      ['interintellect','adj','Between intellects','cross,between','C1'],
      ['curriculum vitaeal','adj','Relating to curriculum vitae','resume-related,pertaining to','B2'],
      ['curriculum vitaeic','adj','Of or relating to curriculum vitae','resume-based,characteristic','B2'],
    ],
  },
  collocations: {}
};
