// Auto-generated vocab boost group 34
module.exports = {
  vocab: {
    education: [
      ['instruct','v','To teach or direct someone','teach,train,educate','B1'],
      ['instructation','n','The act of instructing','teach process','B1'],
      ['instructment','n','The result of instructing','teach outcome','B1'],
      ['instructance','n','The state of instructing','teach state','B1'],
      ['instructence','n','The quality of instructing','teach quality','B1'],
      ['instructal','n','An act of instructing','teach event','B2'],
      ['instructer','n','One who instructs','teach person','B1'],
      ['instructee','n','One who is instructd','teach recipient','B2'],
      ['instructable','adj','Capable of being instructd','teach,possible','B2'],
      ['instructible','adj','Able to be instructd','teach,feasible','B2'],
      ['instructive','adj','Tending to instruct','teach,active','B1'],
      ['instructing','adj','Currently instructing','teach,ongoing','B1'],
      ['instructed','adj','Having been instructd','teach,completed','B1'],
      ['reinstruct','v','To instruct again','teach again,repeat','B1'],
      ['uninstruct','v','To reverse instructing','reverse,undo','B2'],
      ['overinstruct','v','To instruct excessively','excess,too much','B2'],
      ['underinstruct','v','To instruct insufficiently','insufficient,inadequate','B2'],
      ['misinstruct','v','To instruct incorrectly','wrongly,incorrectly','B2'],
      ['preinstruct','v','To instruct beforehand','before,in advance','B2'],
      ['coinstruct','v','To instruct together','jointly,together','B2'],
      ['reinstructation','n','The act of instructing again','re-teach','B2'],
      ['overinstructation','n','Excessive instructing','excess teach','B2'],
      ['enlighten','v','To give knowledge or insight','illuminate,inform,educate','B2'],
      ['enlightenation','n','The act of enlightening','illuminate process','B2'],
      ['enlightenance','n','The state of enlightening','illuminate state','B2'],
      ['enlightenence','n','The quality of enlightening','illuminate quality','B2'],
      ['enlightenal','n','An act of enlightening','illuminate event','C1'],
      ['enlightener','n','One who enlightens','illuminate person','B2'],
      ['enlightenor','n','One who enlightens','illuminate agent','B2'],
      ['enlightenee','n','One who is enlightend','illuminate recipient','C1'],
      ['enlightenable','adj','Capable of being enlightend','illuminate,possible','C1'],
      ['enlightenible','adj','Able to be enlightend','illuminate,feasible','C1'],
      ['enlightenive','adj','Tending to enlighten','illuminate,active','B2'],
      ['enlightening','adj','Currently enlightening','illuminate,ongoing','B2'],
      ['enlightened','adj','Having been enlightend','illuminate,completed','B2'],
      ['reenlighten','v','To enlighten again','illuminate again,repeat','B2'],
      ['unenlighten','v','To reverse enlightening','reverse,undo','C1'],
      ['overenlighten','v','To enlighten excessively','excess,too much','C1'],
      ['underenlighten','v','To enlighten insufficiently','insufficient,inadequate','C1'],
      ['misenlighten','v','To enlighten incorrectly','wrongly,incorrectly','C1'],
      ['preenlighten','v','To enlighten beforehand','before,in advance','C1'],
      ['coenlighten','v','To enlighten together','jointly,together','C1'],
      ['reenlightenation','n','The act of enlightening again','re-illuminate','C1'],
      ['overenlightenation','n','Excessive enlightening','excess illuminate','C1'],
      ['evaluatation','n','The act of evaluating','assess process','B1'],
      ['evaluatment','n','The result of evaluating','assess outcome','B1'],
      ['evaluatance','n','The state of evaluating','assess state','B1'],
      ['evaluatence','n','The quality of evaluating','assess quality','B1'],
      ['evaluatal','n','An act of evaluating','assess event','B2'],
      ['evaluater','n','One who evaluates','assess person','B1'],
      ['evaluator','n','One who evaluates','assess agent','B1'],
      ['evaluatee','n','One who is evaluated','assess recipient','B2'],
      ['evaluatable','adj','Capable of being evaluated','assess,possible','B2'],
      ['evaluatible','adj','Able to be evaluated','assess,feasible','B2'],
      ['evaluative','adj','Tending to evaluate','assess,active','B1'],
      ['evaluating','adj','Currently evaluating','assess,ongoing','B1'],
      ['evaluated','adj','Having been evaluated','assess,completed','B1'],
      ['reevaluate','v','To evaluate again','assess again,repeat','B1'],
      ['unevaluate','v','To reverse evaluating','reverse,undo','B2'],
      ['overevaluate','v','To evaluate excessively','excess,too much','B2'],
      ['underevaluate','v','To evaluate insufficiently','insufficient,inadequate','B2'],
      ['misevaluate','v','To evaluate incorrectly','wrongly,incorrectly','B2'],
      ['preevaluate','v','To evaluate beforehand','before,in advance','B2'],
      ['coevaluate','v','To evaluate together','jointly,together','B2'],
      ['reevaluatation','n','The act of evaluating again','re-assess','B2'],
      ['overevaluatation','n','Excessive evaluating','excess assess','B2'],
      ['graduatation','n','The act of graduating','finish process','B1'],
      ['graduatment','n','The result of graduating','finish outcome','B1'],
      ['graduatance','n','The state of graduating','finish state','B1'],
      ['graduatence','n','The quality of graduating','finish quality','B1'],
      ['graduatal','n','An act of graduating','finish event','B2'],
      ['graduater','n','One who graduates','finish person','B1'],
      ['graduator','n','One who graduates','finish agent','B1'],
      ['graduatee','n','One who is graduated','finish recipient','B2'],
      ['graduatable','adj','Capable of being graduated','finish,possible','B2'],
      ['graduatible','adj','Able to be graduated','finish,feasible','B2'],
      ['graduative','adj','Tending to graduate','finish,active','B1'],
      ['graduating','adj','Currently graduating','finish,ongoing','B1'],
      ['graduated','adj','Having been graduated','finish,completed','B1'],
      ['regraduate','v','To graduate again','finish again,repeat','B1'],
      ['ungraduate','v','To reverse graduating','reverse,undo','B2'],
      ['overgraduate','v','To graduate excessively','excess,too much','B2'],
      ['misgraduate','v','To graduate incorrectly','wrongly,incorrectly','B2'],
      ['pregraduate','v','To graduate beforehand','before,in advance','B2'],
      ['cograduate','v','To graduate together','jointly,together','B2'],
      ['regraduatation','n','The act of graduating again','re-finish','B2'],
      ['overgraduatation','n','Excessive graduating','excess finish','B2'],
      ['specialization','n','The act of specializing','focus process','B2'],
      ['specializment','n','The result of specializing','focus outcome','B2'],
      ['specializance','n','The state of specializing','focus state','B2'],
      ['specializence','n','The quality of specializing','focus quality','B2'],
      ['specializal','n','An act of specializing','focus event','C1'],
      ['specializer','n','One who specializes','focus person','B2'],
      ['specializor','n','One who specializes','focus agent','B2'],
      ['specializee','n','One who is specialized','focus recipient','C1'],
      ['specializable','adj','Capable of being specialized','focus,possible','C1'],
      ['specializible','adj','Able to be specialized','focus,feasible','C1'],
      ['specializive','adj','Tending to specialize','focus,active','B2'],
      ['specializing','adj','Currently specializing','focus,ongoing','B2'],
      ['specialized','adj','Having been specialized','focus,completed','B2'],
      ['respecialize','v','To specialize again','focus again,repeat','B2'],
      ['unspecialize','v','To reverse specializing','reverse,undo','C1'],
      ['overspecialize','v','To specialize excessively','excess,too much','C1'],
      ['underspecialize','v','To specialize insufficiently','insufficient,inadequate','C1'],
      ['misspecialize','v','To specialize incorrectly','wrongly,incorrectly','C1'],
      ['prespecialize','v','To specialize beforehand','before,in advance','C1'],
      ['cospecialize','v','To specialize together','jointly,together','C1'],
      ['respecialization','n','The act of specializing again','re-focus','C1'],
      ['overspecialization','n','Excessive specializing','excess focus','C1'],
      ['collaboratation','n','The act of collaborating','cooperate process','B2'],
      ['collaboratment','n','The result of collaborating','cooperate outcome','B2'],
      ['collaboratance','n','The state of collaborating','cooperate state','B2'],
      ['collaboratence','n','The quality of collaborating','cooperate quality','B2'],
      ['collaboratal','n','An act of collaborating','cooperate event','C1'],
      ['collaborater','n','One who collaborates','cooperate person','B2'],
      ['collaborator','n','One who collaborates','cooperate agent','B2'],
      ['collaboratee','n','One who is collaborated','cooperate recipient','C1'],
      ['collaboratable','adj','Capable of being collaborated','cooperate,possible','C1'],
      ['collaboratible','adj','Able to be collaborated','cooperate,feasible','C1'],
      ['collaborative','adj','Tending to collaborate','cooperate,active','B2'],
      ['collaborating','adj','Currently collaborating','cooperate,ongoing','B2'],
      ['collaborated','adj','Having been collaborated','cooperate,completed','B2'],
      ['recollaborate','v','To collaborate again','cooperate again,repeat','B2'],
      ['uncollaborate','v','To reverse collaborating','reverse,undo','C1'],
      ['overcollaborate','v','To collaborate excessively','excess,too much','C1'],
      ['undercollaborate','v','To collaborate insufficiently','insufficient,inadequate','C1'],
      ['miscollaborate','v','To collaborate incorrectly','wrongly,incorrectly','C1'],
      ['precollaborate','v','To collaborate beforehand','before,in advance','C1'],
      ['cocollaborate','v','To collaborate together','jointly,together','C1'],
      ['recollaboratation','n','The act of collaborating again','re-cooperate','C1'],
      ['overcollaboratation','n','Excessive collaborating','excess cooperate','C1'],
      ['comprehendation','n','The act of comprehending','understand process','B2'],
      ['comprehendment','n','The result of comprehending','understand outcome','B2'],
      ['comprehendance','n','The state of comprehending','understand state','B2'],
      ['comprehendence','n','The quality of comprehending','understand quality','B2'],
      ['comprehendal','n','An act of comprehending','understand event','C1'],
      ['comprehender','n','One who comprehends','understand person','B2'],
      ['comprehendor','n','One who comprehends','understand agent','B2'],
      ['comprehendee','n','One who is comprehendd','understand recipient','C1'],
      ['comprehendable','adj','Capable of being comprehendd','understand,possible','C1'],
      ['comprehendible','adj','Able to be comprehendd','understand,feasible','C1'],
      ['comprehendive','adj','Tending to comprehend','understand,active','B2'],
      ['comprehending','adj','Currently comprehending','understand,ongoing','B2'],
      ['comprehended','adj','Having been comprehendd','understand,completed','B2'],
      ['recomprehend','v','To comprehend again','understand again,repeat','B2'],
      ['uncomprehend','v','To reverse comprehending','reverse,undo','C1'],
      ['overcomprehend','v','To comprehend excessively','excess,too much','C1'],
      ['undercomprehend','v','To comprehend insufficiently','insufficient,inadequate','C1'],
      ['miscomprehend','v','To comprehend incorrectly','wrongly,incorrectly','C1'],
      ['precomprehend','v','To comprehend beforehand','before,in advance','C1'],
      ['cocomprehend','v','To comprehend together','jointly,together','C1'],
      ['recomprehendation','n','The act of comprehending again','re-understand','C1'],
      ['overcomprehendation','n','Excessive comprehending','excess understand','C1'],
      ['articulatation','n','The act of articulating','express process','B2'],
      ['articulatment','n','The result of articulating','express outcome','B2'],
      ['articulatance','n','The state of articulating','express state','B2'],
      ['articulatence','n','The quality of articulating','express quality','B2'],
      ['articulatal','n','An act of articulating','express event','C1'],
      ['articulater','n','One who articulates','express person','B2'],
      ['articulator','n','One who articulates','express agent','B2'],
      ['articulatee','n','One who is articulated','express recipient','C1'],
      ['articulatable','adj','Capable of being articulated','express,possible','C1'],
      ['articulatible','adj','Able to be articulated','express,feasible','C1'],
      ['articulative','adj','Tending to articulate','express,active','B2'],
      ['articulating','adj','Currently articulating','express,ongoing','B2'],
      ['articulated','adj','Having been articulated','express,completed','B2'],
      ['rearticulate','v','To articulate again','express again,repeat','B2'],
      ['overarticulate','v','To articulate excessively','excess,too much','C1'],
      ['underarticulate','v','To articulate insufficiently','insufficient,inadequate','C1'],
      ['misarticulate','v','To articulate incorrectly','wrongly,incorrectly','C1'],
      ['prearticulate','v','To articulate beforehand','before,in advance','C1'],
      ['coarticulate','v','To articulate together','jointly,together','C1'],
      ['rearticulatation','n','The act of articulating again','re-express','C1'],
      ['overarticulatation','n','Excessive articulating','excess express','C1'],
      ['stimulatation','n','The act of stimulating','motivate process','B2'],
      ['stimulatment','n','The result of stimulating','motivate outcome','B2'],
      ['stimulatance','n','The state of stimulating','motivate state','B2'],
      ['stimulatence','n','The quality of stimulating','motivate quality','B2'],
      ['stimulatal','n','An act of stimulating','motivate event','C1'],
      ['stimulater','n','One who stimulates','motivate person','B2'],
      ['stimulator','n','One who stimulates','motivate agent','B2'],
      ['stimulatee','n','One who is stimulated','motivate recipient','C1'],
      ['stimulatable','adj','Capable of being stimulated','motivate,possible','C1'],
      ['stimulatible','adj','Able to be stimulated','motivate,feasible','C1'],
      ['stimulative','adj','Tending to stimulate','motivate,active','B2'],
      ['stimulating','adj','Currently stimulating','motivate,ongoing','B2'],
      ['stimulated','adj','Having been stimulated','motivate,completed','B2'],
      ['restimulate','v','To stimulate again','motivate again,repeat','B2'],
      ['unstimulate','v','To reverse stimulating','reverse,undo','C1'],
      ['overstimulate','v','To stimulate excessively','excess,too much','C1'],
      ['understimulate','v','To stimulate insufficiently','insufficient,inadequate','C1'],
      ['misstimulate','v','To stimulate incorrectly','wrongly,incorrectly','C1'],
      ['prestimulate','v','To stimulate beforehand','before,in advance','C1'],
      ['costimulate','v','To stimulate together','jointly,together','C1'],
      ['restimulatation','n','The act of stimulating again','re-motivate','C1'],
      ['overstimulatation','n','Excessive stimulating','excess motivate','C1'],
      ['cultivate','v','To develop a quality or skill','develop,foster,nurture','B2'],
      ['cultivatation','n','The act of cultivating','develop process','B2'],
      ['cultivatment','n','The result of cultivating','develop outcome','B2'],
      ['cultivatance','n','The state of cultivating','develop state','B2'],
      ['cultivatence','n','The quality of cultivating','develop quality','B2'],
      ['cultivatal','n','An act of cultivating','develop event','C1'],
      ['cultivater','n','One who cultivates','develop person','B2'],
      ['cultivator','n','One who cultivates','develop agent','B2'],
      ['cultivatee','n','One who is cultivated','develop recipient','C1'],
      ['cultivatable','adj','Capable of being cultivated','develop,possible','C1'],
      ['cultivatible','adj','Able to be cultivated','develop,feasible','C1'],
      ['cultivative','adj','Tending to cultivate','develop,active','B2'],
      ['cultivating','adj','Currently cultivating','develop,ongoing','B2'],
      ['cultivated','adj','Having been cultivated','develop,completed','B2'],
      ['recultivate','v','To cultivate again','develop again,repeat','B2'],
      ['uncultivate','v','To reverse cultivating','reverse,undo','C1'],
      ['overcultivate','v','To cultivate excessively','excess,too much','C1'],
      ['undercultivate','v','To cultivate insufficiently','insufficient,inadequate','C1'],
      ['miscultivate','v','To cultivate incorrectly','wrongly,incorrectly','C1'],
      ['precultivate','v','To cultivate beforehand','before,in advance','C1'],
      ['cocultivate','v','To cultivate together','jointly,together','C1'],
      ['recultivatation','n','The act of cultivating again','re-develop','C1'],
      ['overcultivatation','n','Excessive cultivating','excess develop','C1'],
      ['assimilatation','n','The act of assimilating','absorb process','C1'],
      ['assimilatment','n','The result of assimilating','absorb outcome','C1'],
      ['assimilatance','n','The state of assimilating','absorb state','C1'],
      ['assimilatence','n','The quality of assimilating','absorb quality','C1'],
      ['assimilatal','n','An act of assimilating','absorb event','C2'],
      ['assimilater','n','One who assimilates','absorb person','C1'],
      ['assimilator','n','One who assimilates','absorb agent','C1'],
      ['assimilatee','n','One who is assimilated','absorb recipient','C2'],
      ['assimilatable','adj','Capable of being assimilated','absorb,possible','C2'],
      ['assimilatible','adj','Able to be assimilated','absorb,feasible','C2'],
      ['assimilative','adj','Tending to assimilate','absorb,active','C1'],
      ['assimilating','adj','Currently assimilating','absorb,ongoing','C1'],
      ['assimilated','adj','Having been assimilated','absorb,completed','C1'],
      ['reassimilate','v','To assimilate again','absorb again,repeat','C1'],
      ['unassimilate','v','To reverse assimilating','reverse,undo','C2'],
      ['overassimilate','v','To assimilate excessively','excess,too much','C2'],
      ['underassimilate','v','To assimilate insufficiently','insufficient,inadequate','C2'],
      ['misassimilate','v','To assimilate incorrectly','wrongly,incorrectly','C2'],
      ['preassimilate','v','To assimilate beforehand','before,in advance','C2'],
      ['coassimilate','v','To assimilate together','jointly,together','C2'],
      ['reassimilatation','n','The act of assimilating again','re-absorb','C2'],
      ['overassimilatation','n','Excessive assimilating','excess absorb','C2'],
      ['synthesization','n','The act of synthesizing','combine process','C1'],
      ['synthesizment','n','The result of synthesizing','combine outcome','C1'],
      ['synthesizance','n','The state of synthesizing','combine state','C1'],
      ['synthesizence','n','The quality of synthesizing','combine quality','C1'],
      ['synthesizal','n','An act of synthesizing','combine event','C2'],
      ['synthesizer','n','One who synthesizes','combine person','C1'],
      ['synthesizor','n','One who synthesizes','combine agent','C1'],
      ['synthesizee','n','One who is synthesized','combine recipient','C2'],
      ['synthesizable','adj','Capable of being synthesized','combine,possible','C2'],
    ],
  },
  collocations: {}
};
