// Auto-generated vocab boost group 64
module.exports = {
  vocab: {
    travel: [
      ['codisembark','v','To disembark together','jointly,together','C1'],
      ['redisembarkation','n','The act of disembarking again','re-alight','C1'],
      ['overdisembarkation','n','Excessive disembarking','excess alight','C1'],
      ['itineraryic','adj','Of or relating to itinerary','schedule-based,characteristic','B2'],
      ['itineraryous','adj','Full of itinerary','schedule-filled,abundant','C1'],
      ['itineraryful','adj','Full of itinerary','schedule-rich,abounding','B2'],
      ['itineraryless','adj','Without itinerary','lacking,without','B2'],
      ['itineraryism','n','The ideology of itinerary','schedule ideology,doctrine','C1'],
      ['itineraryist','n','A person focused on itinerary','schedule specialist,advocate','C1'],
      ['itineraryise','v','To make into itinerary','schedule,convert','C1'],
      ['itineraryize','v','To make or become itinerary','schedule,transform','C1'],
      ['antiitinerary','adj','Opposed to itinerary','against,opposing','C1'],
      ['nonitinerary','adj','Not involving itinerary','without,lacking','B2'],
      ['preitinerary','n','Before itinerary','preceding,prior','C1'],
      ['postitinerary','n','After itinerary','following,subsequent','C1'],
      ['subitinerary','n','A subdivision of itinerary','subset,branch','C1'],
      ['multiitinerary','adj','Involving many itinerarys','multiple,several','C1'],
      ['interitinerary','adj','Between itinerarys','cross,between','C1'],
      ['excursionic','adj','Of or relating to excursion','outing-based,characteristic','B2'],
      ['excursionous','adj','Full of excursion','outing-filled,abundant','C1'],
      ['excursionful','adj','Full of excursion','outing-rich,abounding','B2'],
      ['excursionless','adj','Without excursion','lacking,without','B2'],
      ['excursionism','n','The ideology of excursion','outing ideology,doctrine','C1'],
      ['excursionise','v','To make into excursion','outing,convert','C1'],
      ['excursionize','v','To make or become excursion','outing,transform','C1'],
      ['antiexcursion','adj','Opposed to excursion','against,opposing','C1'],
      ['nonexcursion','adj','Not involving excursion','without,lacking','B2'],
      ['preexcursion','n','Before excursion','preceding,prior','C1'],
      ['postexcursion','n','After excursion','following,subsequent','C1'],
      ['subexcursion','n','A subdivision of excursion','subset,branch','C1'],
      ['multiexcursion','adj','Involving many excursions','multiple,several','C1'],
      ['interexcursion','adj','Between excursions','cross,between','C1'],
      ['sojournic','adj','Of or relating to sojourn','visit-based,characteristic','C1'],
      ['sojournous','adj','Full of sojourn','visit-filled,abundant','C2'],
      ['sojournful','adj','Full of sojourn','visit-rich,abounding','C1'],
      ['sojournless','adj','Without sojourn','lacking,without','C1'],
      ['sojournism','n','The ideology of sojourn','visit ideology,doctrine','C2'],
      ['sojournist','n','A person focused on sojourn','visit specialist,advocate','C2'],
      ['sojournise','v','To make into sojourn','visit,convert','C2'],
      ['sojournize','v','To make or become sojourn','visit,transform','C2'],
      ['antisojourn','adj','Opposed to sojourn','against,opposing','C2'],
      ['nonsojourn','adj','Not involving sojourn','without,lacking','C1'],
      ['presojourn','n','Before sojourn','preceding,prior','C2'],
      ['postsojourn','n','After sojourn','following,subsequent','C2'],
      ['subsojourn','n','A subdivision of sojourn','subset,branch','C2'],
      ['multisojourn','adj','Involving many sojourns','multiple,several','C2'],
      ['intersojourn','adj','Between sojourns','cross,between','C2'],
      ['pilgrimageic','adj','Of or relating to pilgrimage','holy journey-based,characteristic','B2'],
      ['pilgrimageous','adj','Full of pilgrimage','holy journey-filled,abundant','C1'],
      ['pilgrimageful','adj','Full of pilgrimage','holy journey-rich,abounding','B2'],
      ['pilgrimageless','adj','Without pilgrimage','lacking,without','B2'],
      ['pilgrimageism','n','The ideology of pilgrimage','holy journey ideology,doctrine','C1'],
      ['pilgrimageist','n','A person focused on pilgrimage','holy journey specialist,advocate','C1'],
      ['pilgrimageise','v','To make into pilgrimage','holy journey,convert','C1'],
      ['pilgrimageize','v','To make or become pilgrimage','holy journey,transform','C1'],
      ['antipilgrimage','adj','Opposed to pilgrimage','against,opposing','C1'],
      ['nonpilgrimage','adj','Not involving pilgrimage','without,lacking','B2'],
      ['prepilgrimage','n','Before pilgrimage','preceding,prior','C1'],
      ['postpilgrimage','n','After pilgrimage','following,subsequent','C1'],
      ['subpilgrimage','n','A subdivision of pilgrimage','subset,branch','C1'],
      ['multipilgrimage','adj','Involving many pilgrimages','multiple,several','C1'],
      ['interpilgrimage','adj','Between pilgrimages','cross,between','C1'],
      ['expeditionic','adj','Of or relating to expedition','voyage-based,characteristic','B2'],
      ['expeditionous','adj','Full of expedition','voyage-filled,abundant','C1'],
      ['expeditionful','adj','Full of expedition','voyage-rich,abounding','B2'],
      ['expeditionless','adj','Without expedition','lacking,without','B2'],
      ['expeditionism','n','The ideology of expedition','voyage ideology,doctrine','C1'],
      ['expeditionist','n','A person focused on expedition','voyage specialist,advocate','C1'],
      ['expeditionise','v','To make into expedition','voyage,convert','C1'],
      ['expeditionize','v','To make or become expedition','voyage,transform','C1'],
      ['antiexpedition','adj','Opposed to expedition','against,opposing','C1'],
      ['nonexpedition','adj','Not involving expedition','without,lacking','B2'],
      ['preexpedition','n','Before expedition','preceding,prior','C1'],
      ['postexpedition','n','After expedition','following,subsequent','C1'],
      ['subexpedition','n','A subdivision of expedition','subset,branch','C1'],
      ['multiexpedition','adj','Involving many expeditions','multiple,several','C1'],
      ['interexpedition','adj','Between expeditions','cross,between','C1'],
      ['wanderlustic','adj','Of or relating to wanderlust','travel desire-based,characteristic','C1'],
      ['wanderlustous','adj','Full of wanderlust','travel desire-filled,abundant','C2'],
      ['wanderlustful','adj','Full of wanderlust','travel desire-rich,abounding','C1'],
      ['wanderlustless','adj','Without wanderlust','lacking,without','C1'],
      ['wanderlustism','n','The ideology of wanderlust','travel desire ideology,doctrine','C2'],
      ['wanderlustist','n','A person focused on wanderlust','travel desire specialist,advocate','C2'],
      ['wanderlustise','v','To make into wanderlust','travel desire,convert','C2'],
      ['wanderlustize','v','To make or become wanderlust','travel desire,transform','C2'],
      ['antiwanderlust','adj','Opposed to wanderlust','against,opposing','C2'],
      ['nonwanderlust','adj','Not involving wanderlust','without,lacking','C1'],
      ['prewanderlust','n','Before wanderlust','preceding,prior','C2'],
      ['postwanderlust','n','After wanderlust','following,subsequent','C2'],
      ['subwanderlust','n','A subdivision of wanderlust','subset,branch','C2'],
      ['multiwanderlust','adj','Involving many wanderlusts','multiple,several','C2'],
      ['interwanderlust','adj','Between wanderlusts','cross,between','C2'],
      ['odysseyal','adj','Relating to odyssey','voyage-related,pertaining to','C1'],
      ['odysseyic','adj','Of or relating to odyssey','voyage-based,characteristic','C1'],
      ['odysseyous','adj','Full of odyssey','voyage-filled,abundant','C2'],
      ['odysseyful','adj','Full of odyssey','voyage-rich,abounding','C1'],
      ['odysseyless','adj','Without odyssey','lacking,without','C1'],
      ['odysseyism','n','The ideology of odyssey','voyage ideology,doctrine','C2'],
      ['odysseyist','n','A person focused on odyssey','voyage specialist,advocate','C2'],
      ['odysseyise','v','To make into odyssey','voyage,convert','C2'],
      ['odysseyize','v','To make or become odyssey','voyage,transform','C2'],
      ['antiodyssey','adj','Opposed to odyssey','against,opposing','C2'],
      ['nonodyssey','adj','Not involving odyssey','without,lacking','C1'],
      ['preodyssey','n','Before odyssey','preceding,prior','C2'],
      ['postodyssey','n','After odyssey','following,subsequent','C2'],
      ['subodyssey','n','A subdivision of odyssey','subset,branch','C2'],
      ['multiodyssey','adj','Involving many odysseys','multiple,several','C2'],
      ['interodyssey','adj','Between odysseys','cross,between','C2'],
      ['vagabondal','adj','Relating to vagabond','wanderer-related,pertaining to','C1'],
      ['vagabondic','adj','Of or relating to vagabond','wanderer-based,characteristic','C1'],
      ['vagabondous','adj','Full of vagabond','wanderer-filled,abundant','C2'],
      ['vagabondful','adj','Full of vagabond','wanderer-rich,abounding','C1'],
      ['vagabondless','adj','Without vagabond','lacking,without','C1'],
      ['vagabondism','n','The ideology of vagabond','wanderer ideology,doctrine','C2'],
      ['vagabondist','n','A person focused on vagabond','wanderer specialist,advocate','C2'],
      ['vagabondise','v','To make into vagabond','wanderer,convert','C2'],
      ['vagabondize','v','To make or become vagabond','wanderer,transform','C2'],
      ['antivagabond','adj','Opposed to vagabond','against,opposing','C2'],
      ['nonvagabond','adj','Not involving vagabond','without,lacking','C1'],
      ['prevagabond','n','Before vagabond','preceding,prior','C2'],
      ['postvagabond','n','After vagabond','following,subsequent','C2'],
      ['subvagabond','n','A subdivision of vagabond','subset,branch','C2'],
      ['multivagabond','adj','Involving many vagabonds','multiple,several','C2'],
      ['intervagabond','adj','Between vagabonds','cross,between','C2'],
      ['acclimatization','n','The act of acclimatizing','adapt process','B2'],
      ['acclimatizment','n','The result of acclimatizing','adapt outcome','B2'],
      ['acclimatizance','n','The state of acclimatizing','adapt state','B2'],
      ['acclimatizence','n','The quality of acclimatizing','adapt quality','B2'],
      ['acclimatizal','n','An act of acclimatizing','adapt event','C1'],
      ['acclimatizer','n','One who acclimatizes','adapt person','B2'],
      ['acclimatizor','n','One who acclimatizes','adapt agent','B2'],
      ['acclimatizee','n','One who is acclimatized','adapt recipient','C1'],
      ['acclimatizable','adj','Capable of being acclimatized','adapt,possible','C1'],
      ['acclimatizible','adj','Able to be acclimatized','adapt,feasible','C1'],
      ['acclimatizive','adj','Tending to acclimatize','adapt,active','B2'],
      ['acclimatizing','adj','Currently acclimatizing','adapt,ongoing','B2'],
      ['acclimatized','adj','Having been acclimatized','adapt,completed','B2'],
      ['reacclimatize','v','To acclimatize again','adapt again,repeat','B2'],
      ['unacclimatize','v','To reverse acclimatizing','reverse,undo','C1'],
      ['overacclimatize','v','To acclimatize excessively','excess,too much','C1'],
      ['underacclimatize','v','To acclimatize insufficiently','insufficient,inadequate','C1'],
      ['misacclimatize','v','To acclimatize incorrectly','wrongly,incorrectly','C1'],
      ['preacclimatize','v','To acclimatize beforehand','before,in advance','C1'],
      ['coacclimatize','v','To acclimatize together','jointly,together','C1'],
      ['reacclimatization','n','The act of acclimatizing again','re-adapt','C1'],
      ['overacclimatization','n','Excessive acclimatizing','excess adapt','C1'],
      ['repatriatation','n','The act of repatriating','return process','C1'],
      ['repatriatment','n','The result of repatriating','return outcome','C1'],
      ['repatriatance','n','The state of repatriating','return state','C1'],
      ['repatriatence','n','The quality of repatriating','return quality','C1'],
      ['repatriatal','n','An act of repatriating','return event','C2'],
      ['repatriater','n','One who repatriates','return person','C1'],
      ['repatriator','n','One who repatriates','return agent','C1'],
      ['repatriatee','n','One who is repatriated','return recipient','C2'],
      ['repatriatable','adj','Capable of being repatriated','return,possible','C2'],
      ['repatriatible','adj','Able to be repatriated','return,feasible','C2'],
      ['repatriative','adj','Tending to repatriate','return,active','C1'],
      ['repatriating','adj','Currently repatriating','return,ongoing','C1'],
      ['repatriated','adj','Having been repatriated','return,completed','C1'],
      ['rerepatriate','v','To repatriate again','return again,repeat','C1'],
      ['unrepatriate','v','To reverse repatriating','reverse,undo','C2'],
      ['overrepatriate','v','To repatriate excessively','excess,too much','C2'],
      ['underrepatriate','v','To repatriate insufficiently','insufficient,inadequate','C2'],
      ['misrepatriate','v','To repatriate incorrectly','wrongly,incorrectly','C2'],
      ['prerepatriate','v','To repatriate beforehand','before,in advance','C2'],
      ['corepatriate','v','To repatriate together','jointly,together','C2'],
      ['rerepatriatation','n','The act of repatriating again','re-return','C2'],
      ['overrepatriatation','n','Excessive repatriating','excess return','C2'],
      ['ecotourismic','adj','Of or relating to ecotourism','green tourism-based,characteristic','B2'],
      ['ecotourismous','adj','Full of ecotourism','green tourism-filled,abundant','C1'],
      ['ecotourismful','adj','Full of ecotourism','green tourism-rich,abounding','B2'],
      ['ecotourismless','adj','Without ecotourism','lacking,without','B2'],
      ['ecotourismism','n','The ideology of ecotourism','green tourism ideology,doctrine','C1'],
      ['ecotourismist','n','A person focused on ecotourism','green tourism specialist,advocate','C1'],
      ['ecotourismise','v','To make into ecotourism','green tourism,convert','C1'],
      ['ecotourismize','v','To make or become ecotourism','green tourism,transform','C1'],
      ['antiecotourism','adj','Opposed to ecotourism','against,opposing','C1'],
      ['nonecotourism','adj','Not involving ecotourism','without,lacking','B2'],
      ['preecotourism','n','Before ecotourism','preceding,prior','C1'],
      ['postecotourism','n','After ecotourism','following,subsequent','C1'],
      ['subecotourism','n','A subdivision of ecotourism','subset,branch','C1'],
      ['multiecotourism','adj','Involving many ecotourisms','multiple,several','C1'],
      ['interecotourism','adj','Between ecotourisms','cross,between','C1'],
      ['backpacker','n','A budget traveller with a rucksack','budget traveller,hiker,trekker','B1'],
      ['backpackeral','adj','Relating to backpacker','budget traveller-related,pertaining to','B1'],
      ['backpackeric','adj','Of or relating to backpacker','budget traveller-based,characteristic','B1'],
      ['backpackerous','adj','Full of backpacker','budget traveller-filled,abundant','B2'],
      ['backpackerful','adj','Full of backpacker','budget traveller-rich,abounding','B1'],
      ['backpackerless','adj','Without backpacker','lacking,without','B1'],
      ['backpackerism','n','The ideology of backpacker','budget traveller ideology,doctrine','B2'],
      ['backpackerist','n','A person focused on backpacker','budget traveller specialist,advocate','B2'],
      ['backpackerise','v','To make into backpacker','budget traveller,convert','B2'],
      ['backpackerize','v','To make or become backpacker','budget traveller,transform','B2'],
      ['antibackpacker','adj','Opposed to backpacker','against,opposing','B2'],
      ['nonbackpacker','adj','Not involving backpacker','without,lacking','B1'],
      ['prebackpacker','n','Before backpacker','preceding,prior','B2'],
      ['postbackpacker','n','After backpacker','following,subsequent','B2'],
      ['subbackpacker','n','A subdivision of backpacker','subset,branch','B2'],
      ['multibackpacker','adj','Involving many backpackers','multiple,several','B2'],
      ['interbackpacker','adj','Between backpackers','cross,between','B2'],
      ['customsic','adj','Of or relating to customs','border control-based,characteristic','B1'],
      ['customsous','adj','Full of customs','border control-filled,abundant','B2'],
      ['customsful','adj','Full of customs','border control-rich,abounding','B1'],
      ['customsless','adj','Without customs','lacking,without','B1'],
      ['customsism','n','The ideology of customs','border control ideology,doctrine','B2'],
      ['customsist','n','A person focused on customs','border control specialist,advocate','B2'],
      ['customsise','v','To make into customs','border control,convert','B2'],
      ['customsize','v','To make or become customs','border control,transform','B2'],
      ['anticustoms','adj','Opposed to customs','against,opposing','B2'],
      ['noncustoms','adj','Not involving customs','without,lacking','B1'],
      ['precustoms','n','Before customs','preceding,prior','B2'],
      ['postcustoms','n','After customs','following,subsequent','B2'],
      ['subcustoms','n','A subdivision of customs','subset,branch','B2'],
      ['multicustoms','adj','Involving many customss','multiple,several','B2'],
      ['intercustoms','adj','Between customss','cross,between','B2'],
      ['quarantineal','adj','Relating to quarantine','isolation-related,pertaining to','B2'],
      ['quarantineic','adj','Of or relating to quarantine','isolation-based,characteristic','B2'],
      ['quarantineous','adj','Full of quarantine','isolation-filled,abundant','C1'],
      ['quarantineful','adj','Full of quarantine','isolation-rich,abounding','B2'],
      ['quarantineless','adj','Without quarantine','lacking,without','B2'],
      ['quarantineism','n','The ideology of quarantine','isolation ideology,doctrine','C1'],
      ['quarantineist','n','A person focused on quarantine','isolation specialist,advocate','C1'],
      ['quarantineise','v','To make into quarantine','isolation,convert','C1'],
      ['quarantineize','v','To make or become quarantine','isolation,transform','C1'],
      ['antiquarantine','adj','Opposed to quarantine','against,opposing','C1'],
      ['nonquarantine','adj','Not involving quarantine','without,lacking','B2'],
      ['postquarantine','n','After quarantine','following,subsequent','C1'],
      ['subquarantine','n','A subdivision of quarantine','subset,branch','C1'],
      ['multiquarantine','adj','Involving many quarantines','multiple,several','C1'],
      ['interquarantine','adj','Between quarantines','cross,between','C1'],
      ['scenicly','adv','In a scenic manner','picturesque way','B1'],
      ['scenicness','n','The quality of being scenic','picturesque quality','B1'],
      ['scenicity','n','The state of being scenic','picturesque condition','B2'],
      ['unscenic','adj','Not scenic','not picturesque','B1'],
      ['inscenic','adj','Not scenic','not picturesque','B2'],
      ['nonscenic','adj','Not scenic','not picturesque','B1'],
      ['semiscenic','adj','Partially scenic','partly picturesque','B2'],
      ['overscenic','adj','Excessively scenic','too picturesque','B2'],
      ['ultrascenic','adj','Extremely scenic','very picturesque','B2'],
      ['off-the-beaten-track','adj','In a place few visitors go','remote,secluded,undiscovered','B2'],
      ['off-the-beaten-trackly','adv','In a off-the-beaten-track manner','remote way','B2'],
      ['off-the-beaten-trackness','n','The quality of being off-the-beaten-track','remote quality','B2'],
      ['off-the-beaten-trackity','n','The state of being off-the-beaten-track','remote condition','C1'],
      ['unoff-the-beaten-track','adj','Not off-the-beaten-track','not remote','B2'],
      ['inoff-the-beaten-track','adj','Not off-the-beaten-track','not remote','C1'],
      ['nonoff-the-beaten-track','adj','Not off-the-beaten-track','not remote','B2'],
      ['semioff-the-beaten-track','adj','Partially off-the-beaten-track','partly remote','C1'],
      ['overoff-the-beaten-track','adj','Excessively off-the-beaten-track','too remote','C1'],
      ['ultraoff-the-beaten-track','adj','Extremely off-the-beaten-track','very remote','C1'],
      ['hospitable','adj','Friendly and welcoming to visitors','welcoming,warm,friendly','B2'],
    ],
  },
  collocations: {}
};
