// Auto-generated vocab boost group 45
module.exports = {
  vocab: {
    environment: [
      ['microplasticise','v','To make into microplastic','plastic particle,convert','C1'],
      ['microplasticize','v','To make or become microplastic','plastic particle,transform','C1'],
      ['antimicroplastic','adj','Opposed to microplastic','against,opposing','C1'],
      ['nonmicroplastic','adj','Not involving microplastic','without,lacking','B2'],
      ['premicroplastic','n','Before microplastic','preceding,prior','C1'],
      ['postmicroplastic','n','After microplastic','following,subsequent','C1'],
      ['submicroplastic','n','A subdivision of microplastic','subset,branch','C1'],
      ['multimicroplastic','adj','Involving many microplastics','multiple,several','C1'],
      ['intermicroplastic','adj','Between microplastics','cross,between','C1'],
    ],
    business: [
      ['negotiatment','n','The result of negotiating','bargain outcome','B1'],
      ['negotiatance','n','The state of negotiating','bargain state','B1'],
      ['negotiatence','n','The quality of negotiating','bargain quality','B1'],
      ['negotiatal','n','An act of negotiating','bargain event','B2'],
      ['negotiator','n','One who negotiates','bargain agent','B1'],
      ['negotiatee','n','One who is negotiated','bargain recipient','B2'],
      ['negotiatible','adj','Able to be negotiated','bargain,feasible','B2'],
      ['negotiative','adj','Tending to negotiate','bargain,active','B1'],
      ['negotiated','adj','Having been negotiated','bargain,completed','B1'],
      ['renegotiate','v','To negotiate again','bargain again,repeat','B1'],
      ['unnegotiate','v','To reverse negotiating','reverse,undo','B2'],
      ['overnegotiate','v','To negotiate excessively','excess,too much','B2'],
      ['undernegotiate','v','To negotiate insufficiently','insufficient,inadequate','B2'],
      ['misnegotiate','v','To negotiate incorrectly','wrongly,incorrectly','B2'],
      ['prenegotiate','v','To negotiate beforehand','before,in advance','B2'],
      ['conegotiate','v','To negotiate together','jointly,together','B2'],
      ['renegotiatation','n','The act of negotiating again','re-bargain','B2'],
      ['overnegotiatation','n','Excessive negotiating','excess bargain','B2'],
      ['diversifyment','n','The result of diversifying','expand outcome','B2'],
      ['diversifyance','n','The state of diversifying','expand state','B2'],
      ['diversifyence','n','The quality of diversifying','expand quality','B2'],
      ['diversifyal','n','An act of diversifying','expand event','C1'],
      ['diversifyor','n','One who diversifys','expand agent','B2'],
      ['diversifyee','n','One who is diversifyd','expand recipient','C1'],
      ['diversifyible','adj','Able to be diversifyd','expand,feasible','C1'],
      ['diversifyive','adj','Tending to diversify','expand,active','B2'],
      ['diversifyed','adj','Having been diversifyd','expand,completed','B2'],
      ['rediversify','v','To diversify again','expand again,repeat','B2'],
      ['undiversify','v','To reverse diversifying','reverse,undo','C1'],
      ['overdiversify','v','To diversify excessively','excess,too much','C1'],
      ['underdiversify','v','To diversify insufficiently','insufficient,inadequate','C1'],
      ['misdiversify','v','To diversify incorrectly','wrongly,incorrectly','C1'],
      ['prediversify','v','To diversify beforehand','before,in advance','C1'],
      ['codiversify','v','To diversify together','jointly,together','C1'],
      ['rediversifyation','n','The act of diversifying again','re-expand','C1'],
      ['overdiversifyation','n','Excessive diversifying','excess expand','C1'],
      ['outsourcment','n','The result of outsourcing','delegate outcome','B2'],
      ['outsourcance','n','The state of outsourcing','delegate state','B2'],
      ['outsourcence','n','The quality of outsourcing','delegate quality','B2'],
      ['outsourcal','n','An act of outsourcing','delegate event','C1'],
      ['outsourcor','n','One who outsources','delegate agent','B2'],
      ['outsourcee','n','One who is outsourced','delegate recipient','C1'],
      ['outsourcible','adj','Able to be outsourced','delegate,feasible','C1'],
      ['outsourcive','adj','Tending to outsource','delegate,active','B2'],
      ['outsourced','adj','Having been outsourced','delegate,completed','B2'],
      ['reoutsource','v','To outsource again','delegate again,repeat','B2'],
      ['unoutsource','v','To reverse outsourcing','reverse,undo','C1'],
      ['overoutsource','v','To outsource excessively','excess,too much','C1'],
      ['underoutsource','v','To outsource insufficiently','insufficient,inadequate','C1'],
      ['misoutsource','v','To outsource incorrectly','wrongly,incorrectly','C1'],
      ['preoutsource','v','To outsource beforehand','before,in advance','C1'],
      ['cooutsource','v','To outsource together','jointly,together','C1'],
      ['reoutsourcation','n','The act of outsourcing again','re-delegate','C1'],
      ['overoutsourcation','n','Excessive outsourcing','excess delegate','C1'],
      ['franchisation','n','The act of franchising','license process','B2'],
      ['franchisment','n','The result of franchising','license outcome','B2'],
      ['franchisance','n','The state of franchising','license state','B2'],
      ['franchisence','n','The quality of franchising','license quality','B2'],
      ['franchisal','n','An act of franchising','license event','C1'],
      ['franchiser','n','One who franchises','license person','B2'],
      ['franchisor','n','One who franchises','license agent','B2'],
      ['franchisee','n','One who is franchised','license recipient','C1'],
      ['franchisable','adj','Capable of being franchised','license,possible','C1'],
      ['franchisible','adj','Able to be franchised','license,feasible','C1'],
      ['franchisive','adj','Tending to franchise','license,active','B2'],
      ['franchising','adj','Currently franchising','license,ongoing','B2'],
      ['franchised','adj','Having been franchised','license,completed','B2'],
      ['refranchise','v','To franchise again','license again,repeat','B2'],
      ['unfranchise','v','To reverse franchising','reverse,undo','C1'],
      ['overfranchise','v','To franchise excessively','excess,too much','C1'],
      ['underfranchise','v','To franchise insufficiently','insufficient,inadequate','C1'],
      ['misfranchise','v','To franchise incorrectly','wrongly,incorrectly','C1'],
      ['prefranchise','v','To franchise beforehand','before,in advance','C1'],
      ['cofranchise','v','To franchise together','jointly,together','C1'],
      ['refranchisation','n','The act of franchising again','re-license','C1'],
      ['overfranchisation','n','Excessive franchising','excess license','C1'],
      ['liquidatation','n','The act of liquidating','dissolve process','C1'],
      ['liquidatment','n','The result of liquidating','dissolve outcome','C1'],
      ['liquidatance','n','The state of liquidating','dissolve state','C1'],
      ['liquidatence','n','The quality of liquidating','dissolve quality','C1'],
      ['liquidatal','n','An act of liquidating','dissolve event','C2'],
      ['liquidater','n','One who liquidates','dissolve person','C1'],
      ['liquidator','n','One who liquidates','dissolve agent','C1'],
      ['liquidatee','n','One who is liquidated','dissolve recipient','C2'],
      ['liquidatable','adj','Capable of being liquidated','dissolve,possible','C2'],
      ['liquidatible','adj','Able to be liquidated','dissolve,feasible','C2'],
      ['liquidative','adj','Tending to liquidate','dissolve,active','C1'],
      ['liquidating','adj','Currently liquidating','dissolve,ongoing','C1'],
      ['liquidated','adj','Having been liquidated','dissolve,completed','C1'],
      ['reliquidate','v','To liquidate again','dissolve again,repeat','C1'],
      ['unliquidate','v','To reverse liquidating','reverse,undo','C2'],
      ['overliquidate','v','To liquidate excessively','excess,too much','C2'],
      ['underliquidate','v','To liquidate insufficiently','insufficient,inadequate','C2'],
      ['misliquidate','v','To liquidate incorrectly','wrongly,incorrectly','C2'],
      ['preliquidate','v','To liquidate beforehand','before,in advance','C2'],
      ['coliquidate','v','To liquidate together','jointly,together','C2'],
      ['reliquidatation','n','The act of liquidating again','re-dissolve','C2'],
      ['overliquidatation','n','Excessive liquidating','excess dissolve','C2'],
      ['monopolize','v','To dominate a market exclusively','control,dominate,corner','B2'],
      ['monopolization','n','The act of monopolizing','control process','B2'],
      ['monopolizment','n','The result of monopolizing','control outcome','B2'],
      ['monopolizance','n','The state of monopolizing','control state','B2'],
      ['monopolizence','n','The quality of monopolizing','control quality','B2'],
      ['monopolizal','n','An act of monopolizing','control event','C1'],
      ['monopolizer','n','One who monopolizes','control person','B2'],
      ['monopolizor','n','One who monopolizes','control agent','B2'],
      ['monopolizee','n','One who is monopolized','control recipient','C1'],
      ['monopolizable','adj','Capable of being monopolized','control,possible','C1'],
      ['monopolizible','adj','Able to be monopolized','control,feasible','C1'],
      ['monopolizive','adj','Tending to monopolize','control,active','B2'],
      ['monopolizing','adj','Currently monopolizing','control,ongoing','B2'],
      ['monopolized','adj','Having been monopolized','control,completed','B2'],
      ['remonopolize','v','To monopolize again','control again,repeat','B2'],
      ['unmonopolize','v','To reverse monopolizing','reverse,undo','C1'],
      ['overmonopolize','v','To monopolize excessively','excess,too much','C1'],
      ['undermonopolize','v','To monopolize insufficiently','insufficient,inadequate','C1'],
      ['mismonopolize','v','To monopolize incorrectly','wrongly,incorrectly','C1'],
      ['premonopolize','v','To monopolize beforehand','before,in advance','C1'],
      ['comonopolize','v','To monopolize together','jointly,together','C1'],
      ['remonopolization','n','The act of monopolizing again','re-control','C1'],
      ['overmonopolization','n','Excessive monopolizing','excess control','C1'],
      ['capitalization','n','The act of capitalizing','fund process','B2'],
      ['capitalizment','n','The result of capitalizing','fund outcome','B2'],
      ['capitalizance','n','The state of capitalizing','fund state','B2'],
      ['capitalizence','n','The quality of capitalizing','fund quality','B2'],
      ['capitalizal','n','An act of capitalizing','fund event','C1'],
      ['capitalizer','n','One who capitalizes','fund person','B2'],
      ['capitalizor','n','One who capitalizes','fund agent','B2'],
      ['capitalizee','n','One who is capitalized','fund recipient','C1'],
      ['capitalizable','adj','Capable of being capitalized','fund,possible','C1'],
      ['capitalizible','adj','Able to be capitalized','fund,feasible','C1'],
      ['capitalizive','adj','Tending to capitalize','fund,active','B2'],
      ['capitalizing','adj','Currently capitalizing','fund,ongoing','B2'],
      ['capitalized','adj','Having been capitalized','fund,completed','B2'],
      ['uncapitalize','v','To reverse capitalizing','reverse,undo','C1'],
      ['overcapitalize','v','To capitalize excessively','excess,too much','C1'],
      ['undercapitalize','v','To capitalize insufficiently','insufficient,inadequate','C1'],
      ['miscapitalize','v','To capitalize incorrectly','wrongly,incorrectly','C1'],
      ['precapitalize','v','To capitalize beforehand','before,in advance','C1'],
      ['cocapitalize','v','To capitalize together','jointly,together','C1'],
      ['recapitalization','n','The act of capitalizing again','re-fund','C1'],
      ['overcapitalization','n','Excessive capitalizing','excess fund','C1'],
      ['streamlination','n','The act of streamlining','simplify process','B2'],
      ['streamlinment','n','The result of streamlining','simplify outcome','B2'],
      ['streamlinance','n','The state of streamlining','simplify state','B2'],
      ['streamlinence','n','The quality of streamlining','simplify quality','B2'],
      ['streamlinal','n','An act of streamlining','simplify event','C1'],
      ['streamliner','n','One who streamlines','simplify person','B2'],
      ['streamlinor','n','One who streamlines','simplify agent','B2'],
      ['streamlinee','n','One who is streamlined','simplify recipient','C1'],
      ['streamlinable','adj','Capable of being streamlined','simplify,possible','C1'],
      ['streamlinible','adj','Able to be streamlined','simplify,feasible','C1'],
      ['streamlinive','adj','Tending to streamline','simplify,active','B2'],
      ['streamlining','adj','Currently streamlining','simplify,ongoing','B2'],
      ['streamlined','adj','Having been streamlined','simplify,completed','B2'],
      ['restreamline','v','To streamline again','simplify again,repeat','B2'],
      ['unstreamline','v','To reverse streamlining','reverse,undo','C1'],
      ['overstreamline','v','To streamline excessively','excess,too much','C1'],
      ['understreamline','v','To streamline insufficiently','insufficient,inadequate','C1'],
      ['misstreamline','v','To streamline incorrectly','wrongly,incorrectly','C1'],
      ['prestreamline','v','To streamline beforehand','before,in advance','C1'],
      ['costreamline','v','To streamline together','jointly,together','C1'],
      ['restreamlination','n','The act of streamlining again','re-simplify','C1'],
      ['overstreamlination','n','Excessive streamlining','excess simplify','C1'],
      ['rebrand','v','To change the brand image of a product','rename,reposition,redesign','B2'],
      ['rebrandation','n','The act of rebranding','rename process','B2'],
      ['rebrandment','n','The result of rebranding','rename outcome','B2'],
      ['rebrandance','n','The state of rebranding','rename state','B2'],
      ['rebrandence','n','The quality of rebranding','rename quality','B2'],
      ['rebrandal','n','An act of rebranding','rename event','C1'],
      ['rebrander','n','One who rebrands','rename person','B2'],
      ['rebrandor','n','One who rebrands','rename agent','B2'],
      ['rebrandee','n','One who is rebrandd','rename recipient','C1'],
      ['rebrandable','adj','Capable of being rebrandd','rename,possible','C1'],
      ['rebrandible','adj','Able to be rebrandd','rename,feasible','C1'],
      ['rebrandive','adj','Tending to rebrand','rename,active','B2'],
      ['rebranding','adj','Currently rebranding','rename,ongoing','B2'],
      ['rebranded','adj','Having been rebrandd','rename,completed','B2'],
      ['rerebrand','v','To rebrand again','rename again,repeat','B2'],
      ['unrebrand','v','To reverse rebranding','reverse,undo','C1'],
      ['overrebrand','v','To rebrand excessively','excess,too much','C1'],
      ['underrebrand','v','To rebrand insufficiently','insufficient,inadequate','C1'],
      ['misrebrand','v','To rebrand incorrectly','wrongly,incorrectly','C1'],
      ['prerebrand','v','To rebrand beforehand','before,in advance','C1'],
      ['corebrand','v','To rebrand together','jointly,together','C1'],
      ['rerebrandation','n','The act of rebranding again','re-rename','C1'],
      ['overrebrandation','n','Excessive rebranding','excess rename','C1'],
      ['benchmarkation','n','The act of benchmarking','measure process','B2'],
      ['benchmarkment','n','The result of benchmarking','measure outcome','B2'],
      ['benchmarkance','n','The state of benchmarking','measure state','B2'],
      ['benchmarkence','n','The quality of benchmarking','measure quality','B2'],
      ['benchmarker','n','One who benchmarks','measure person','B2'],
      ['benchmarkor','n','One who benchmarks','measure agent','B2'],
      ['benchmarkee','n','One who is benchmarkd','measure recipient','C1'],
      ['benchmarkable','adj','Capable of being benchmarkd','measure,possible','C1'],
      ['benchmarkible','adj','Able to be benchmarkd','measure,feasible','C1'],
      ['benchmarkive','adj','Tending to benchmark','measure,active','B2'],
      ['benchmarked','adj','Having been benchmarkd','measure,completed','B2'],
      ['rebenchmark','v','To benchmark again','measure again,repeat','B2'],
      ['unbenchmark','v','To reverse benchmarking','reverse,undo','C1'],
      ['overbenchmark','v','To benchmark excessively','excess,too much','C1'],
      ['underbenchmark','v','To benchmark insufficiently','insufficient,inadequate','C1'],
      ['misbenchmark','v','To benchmark incorrectly','wrongly,incorrectly','C1'],
      ['cobenchmark','v','To benchmark together','jointly,together','C1'],
      ['rebenchmarkation','n','The act of benchmarking again','re-measure','C1'],
      ['overbenchmarkation','n','Excessive benchmarking','excess measure','C1'],
      ['leveragment','n','The result of leveraging','exploit outcome','B2'],
      ['leveragance','n','The state of leveraging','exploit state','B2'],
      ['leveragence','n','The quality of leveraging','exploit quality','B2'],
      ['leveragal','n','An act of leveraging','exploit event','C1'],
      ['leveragor','n','One who leverages','exploit agent','B2'],
      ['leveragee','n','One who is leveraged','exploit recipient','C1'],
      ['leveragible','adj','Able to be leveraged','exploit,feasible','C1'],
      ['leveragive','adj','Tending to leverage','exploit,active','B2'],
      ['leveraged','adj','Having been leveraged','exploit,completed','B2'],
      ['releverage','v','To leverage again','exploit again,repeat','B2'],
      ['unleverage','v','To reverse leveraging','reverse,undo','C1'],
      ['overleverage','v','To leverage excessively','excess,too much','C1'],
      ['underleverage','v','To leverage insufficiently','insufficient,inadequate','C1'],
      ['misleverage','v','To leverage incorrectly','wrongly,incorrectly','C1'],
      ['preleverage','v','To leverage beforehand','before,in advance','C1'],
      ['coleverage','v','To leverage together','jointly,together','C1'],
      ['releveragation','n','The act of leveraging again','re-exploit','C1'],
      ['overleveragation','n','Excessive leveraging','excess exploit','C1'],
      ['synergize','v','To combine for greater effect','collaborate,cooperate,merge','C1'],
      ['synergization','n','The act of synergizing','collaborate process','C1'],
      ['synergizment','n','The result of synergizing','collaborate outcome','C1'],
      ['synergizance','n','The state of synergizing','collaborate state','C1'],
      ['synergizence','n','The quality of synergizing','collaborate quality','C1'],
      ['synergizal','n','An act of synergizing','collaborate event','C2'],
      ['synergizer','n','One who synergizes','collaborate person','C1'],
      ['synergizor','n','One who synergizes','collaborate agent','C1'],
      ['synergizee','n','One who is synergized','collaborate recipient','C2'],
      ['synergizable','adj','Capable of being synergized','collaborate,possible','C2'],
      ['synergizible','adj','Able to be synergized','collaborate,feasible','C2'],
      ['synergizive','adj','Tending to synergize','collaborate,active','C1'],
      ['synergizing','adj','Currently synergizing','collaborate,ongoing','C1'],
      ['synergized','adj','Having been synergized','collaborate,completed','C1'],
      ['resynergize','v','To synergize again','collaborate again,repeat','C1'],
      ['unsynergize','v','To reverse synergizing','reverse,undo','C2'],
      ['oversynergize','v','To synergize excessively','excess,too much','C2'],
    ],
  },
  collocations: {}
};
