// Auto-generated vocab boost group 36
module.exports = {
  vocab: {
    education: [
      ['curriculum vitaeous','adj','Full of curriculum vitae','resume-filled,abundant','C1'],
      ['curriculum vitaeful','adj','Full of curriculum vitae','resume-rich,abounding','B2'],
      ['curriculum vitaeless','adj','Without curriculum vitae','lacking,without','B2'],
      ['curriculum vitaeism','n','The ideology of curriculum vitae','resume ideology,doctrine','C1'],
      ['curriculum vitaeist','n','A person focused on curriculum vitae','resume specialist,advocate','C1'],
      ['curriculum vitaeise','v','To make into curriculum vitae','resume,convert','C1'],
      ['curriculum vitaeize','v','To make or become curriculum vitae','resume,transform','C1'],
      ['anticurriculum vitae','adj','Opposed to curriculum vitae','against,opposing','C1'],
      ['noncurriculum vitae','adj','Not involving curriculum vitae','without,lacking','B2'],
      ['precurriculum vitae','n','Before curriculum vitae','preceding,prior','C1'],
      ['postcurriculum vitae','n','After curriculum vitae','following,subsequent','C1'],
      ['subcurriculum vitae','n','A subdivision of curriculum vitae','subset,branch','C1'],
      ['multicurriculum vitae','adj','Involving many curriculum vitaes','multiple,several','C1'],
      ['intercurriculum vitae','adj','Between curriculum vitaes','cross,between','C1'],
      ['apprenticeic','adj','Of or relating to apprentice','trainee-based,characteristic','B1'],
      ['apprenticeous','adj','Full of apprentice','trainee-filled,abundant','B2'],
      ['apprenticeful','adj','Full of apprentice','trainee-rich,abounding','B1'],
      ['apprenticeless','adj','Without apprentice','lacking,without','B1'],
      ['apprenticeism','n','The ideology of apprentice','trainee ideology,doctrine','B2'],
      ['apprenticeist','n','A person focused on apprentice','trainee specialist,advocate','B2'],
      ['apprenticeise','v','To make into apprentice','trainee,convert','B2'],
      ['apprenticeize','v','To make or become apprentice','trainee,transform','B2'],
      ['antiapprentice','adj','Opposed to apprentice','against,opposing','B2'],
      ['nonapprentice','adj','Not involving apprentice','without,lacking','B1'],
      ['preapprentice','n','Before apprentice','preceding,prior','B2'],
      ['postapprentice','n','After apprentice','following,subsequent','B2'],
      ['subapprentice','n','A subdivision of apprentice','subset,branch','B2'],
      ['multiapprentice','adj','Involving many apprentices','multiple,several','B2'],
      ['interapprentice','adj','Between apprentices','cross,between','B2'],
      ['prodigy','n','A young person with exceptional abilities','genius,talent,wonder','C1'],
      ['prodigyal','adj','Relating to prodigy','genius-related,pertaining to','C1'],
      ['prodigyic','adj','Of or relating to prodigy','genius-based,characteristic','C1'],
      ['prodigyous','adj','Full of prodigy','genius-filled,abundant','C2'],
      ['prodigyful','adj','Full of prodigy','genius-rich,abounding','C1'],
      ['prodigyless','adj','Without prodigy','lacking,without','C1'],
      ['prodigyism','n','The ideology of prodigy','genius ideology,doctrine','C2'],
      ['prodigyist','n','A person focused on prodigy','genius specialist,advocate','C2'],
      ['prodigyise','v','To make into prodigy','genius,convert','C2'],
      ['prodigyize','v','To make or become prodigy','genius,transform','C2'],
      ['antiprodigy','adj','Opposed to prodigy','against,opposing','C2'],
      ['nonprodigy','adj','Not involving prodigy','without,lacking','C1'],
      ['preprodigy','n','Before prodigy','preceding,prior','C2'],
      ['postprodigy','n','After prodigy','following,subsequent','C2'],
      ['subprodigy','n','A subdivision of prodigy','subset,branch','C2'],
      ['multiprodigy','adj','Involving many prodigys','multiple,several','C2'],
      ['interprodigy','adj','Between prodigys','cross,between','C2'],
      ['acumenal','adj','Relating to acumen','insight-related,pertaining to','C1'],
      ['acumenic','adj','Of or relating to acumen','insight-based,characteristic','C1'],
      ['acumenous','adj','Full of acumen','insight-filled,abundant','C2'],
      ['acumenful','adj','Full of acumen','insight-rich,abounding','C1'],
      ['acumenless','adj','Without acumen','lacking,without','C1'],
      ['acumenism','n','The ideology of acumen','insight ideology,doctrine','C2'],
      ['acumenist','n','A person focused on acumen','insight specialist,advocate','C2'],
      ['acumenise','v','To make into acumen','insight,convert','C2'],
      ['acumenize','v','To make or become acumen','insight,transform','C2'],
      ['antiacumen','adj','Opposed to acumen','against,opposing','C2'],
      ['nonacumen','adj','Not involving acumen','without,lacking','C1'],
      ['preacumen','n','Before acumen','preceding,prior','C2'],
      ['postacumen','n','After acumen','following,subsequent','C2'],
      ['subacumen','n','A subdivision of acumen','subset,branch','C2'],
      ['multiacumen','adj','Involving many acumens','multiple,several','C2'],
      ['interacumen','adj','Between acumens','cross,between','C2'],
      ['erudition','n','Great academic knowledge or learning','scholarship,learning,knowledge','C2'],
      ['eruditional','adj','Relating to erudition','scholarship-related,pertaining to','C2'],
      ['eruditionic','adj','Of or relating to erudition','scholarship-based,characteristic','C2'],
      ['eruditionous','adj','Full of erudition','scholarship-filled,abundant','C2'],
      ['eruditionful','adj','Full of erudition','scholarship-rich,abounding','C2'],
      ['eruditionless','adj','Without erudition','lacking,without','C2'],
      ['eruditionism','n','The ideology of erudition','scholarship ideology,doctrine','C2'],
      ['eruditionist','n','A person focused on erudition','scholarship specialist,advocate','C2'],
      ['eruditionise','v','To make into erudition','scholarship,convert','C2'],
      ['eruditionize','v','To make or become erudition','scholarship,transform','C2'],
      ['antierudition','adj','Opposed to erudition','against,opposing','C2'],
      ['nonerudition','adj','Not involving erudition','without,lacking','C2'],
      ['preerudition','n','Before erudition','preceding,prior','C2'],
      ['posterudition','n','After erudition','following,subsequent','C2'],
      ['suberudition','n','A subdivision of erudition','subset,branch','C2'],
      ['multierudition','adj','Involving many eruditions','multiple,several','C2'],
      ['intererudition','adj','Between eruditions','cross,between','C2'],
      ['edificational','adj','Relating to edification','enlightenment-related,pertaining to','C2'],
      ['edificationic','adj','Of or relating to edification','enlightenment-based,characteristic','C2'],
      ['edificationous','adj','Full of edification','enlightenment-filled,abundant','C2'],
      ['edificationful','adj','Full of edification','enlightenment-rich,abounding','C2'],
      ['edificationless','adj','Without edification','lacking,without','C2'],
      ['edificationism','n','The ideology of edification','enlightenment ideology,doctrine','C2'],
      ['edificationist','n','A person focused on edification','enlightenment specialist,advocate','C2'],
      ['edificationise','v','To make into edification','enlightenment,convert','C2'],
      ['edificationize','v','To make or become edification','enlightenment,transform','C2'],
      ['antiedification','adj','Opposed to edification','against,opposing','C2'],
      ['nonedification','adj','Not involving edification','without,lacking','C2'],
      ['preedification','n','Before edification','preceding,prior','C2'],
      ['postedification','n','After edification','following,subsequent','C2'],
      ['subedification','n','A subdivision of edification','subset,branch','C2'],
      ['multiedification','adj','Involving many edifications','multiple,several','C2'],
      ['interedification','adj','Between edifications','cross,between','C2'],
      ['cognizant','adj','Having knowledge or awareness','aware,conscious,mindful','C1'],
      ['cognizantly','adv','In a cognizant manner','aware way','C1'],
      ['cognizantness','n','The quality of being cognizant','aware quality','C1'],
      ['cognizantity','n','The state of being cognizant','aware condition','C2'],
      ['uncognizant','adj','Not cognizant','not aware','C1'],
      ['incognizant','adj','Not cognizant','not aware','C2'],
      ['noncognizant','adj','Not cognizant','not aware','C1'],
      ['semicognizant','adj','Partially cognizant','partly aware','C2'],
      ['overcognizant','adj','Excessively cognizant','too aware','C2'],
      ['ultracognizant','adj','Extremely cognizant','very aware','C2'],
      ['enumerate','v','To list items one by one','list,count,detail','B2'],
      ['enumeratation','n','The act of enumerating','list process','B2'],
      ['enumeratment','n','The result of enumerating','list outcome','B2'],
      ['enumeratance','n','The state of enumerating','list state','B2'],
      ['enumeratence','n','The quality of enumerating','list quality','B2'],
      ['enumeratal','n','An act of enumerating','list event','C1'],
      ['enumerater','n','One who enumerates','list person','B2'],
      ['enumerator','n','One who enumerates','list agent','B2'],
      ['enumeratee','n','One who is enumerated','list recipient','C1'],
      ['enumeratable','adj','Capable of being enumerated','list,possible','C1'],
      ['enumeratible','adj','Able to be enumerated','list,feasible','C1'],
      ['enumerative','adj','Tending to enumerate','list,active','B2'],
      ['enumerating','adj','Currently enumerating','list,ongoing','B2'],
      ['enumerated','adj','Having been enumerated','list,completed','B2'],
      ['reenumerate','v','To enumerate again','list again,repeat','B2'],
      ['unenumerate','v','To reverse enumerating','reverse,undo','C1'],
      ['overenumerate','v','To enumerate excessively','excess,too much','C1'],
      ['underenumerate','v','To enumerate insufficiently','insufficient,inadequate','C1'],
      ['misenumerate','v','To enumerate incorrectly','wrongly,incorrectly','C1'],
      ['preenumerate','v','To enumerate beforehand','before,in advance','C1'],
      ['coenumerate','v','To enumerate together','jointly,together','C1'],
      ['reenumeratation','n','The act of enumerating again','re-list','C1'],
      ['overenumeratation','n','Excessive enumerating','excess list','C1'],
      ['annotate','v','To add explanatory notes to a text','comment,note,gloss','C1'],
      ['annotatation','n','The act of annotating','comment process','C1'],
      ['annotatment','n','The result of annotating','comment outcome','C1'],
      ['annotatance','n','The state of annotating','comment state','C1'],
      ['annotatence','n','The quality of annotating','comment quality','C1'],
      ['annotatal','n','An act of annotating','comment event','C2'],
      ['annotater','n','One who annotates','comment person','C1'],
      ['annotator','n','One who annotates','comment agent','C1'],
      ['annotatee','n','One who is annotated','comment recipient','C2'],
      ['annotatable','adj','Capable of being annotated','comment,possible','C2'],
      ['annotatible','adj','Able to be annotated','comment,feasible','C2'],
      ['annotative','adj','Tending to annotate','comment,active','C1'],
      ['annotating','adj','Currently annotating','comment,ongoing','C1'],
      ['annotated','adj','Having been annotated','comment,completed','C1'],
      ['reannotate','v','To annotate again','comment again,repeat','C1'],
      ['unannotate','v','To reverse annotating','reverse,undo','C2'],
      ['overannotate','v','To annotate excessively','excess,too much','C2'],
      ['underannotate','v','To annotate insufficiently','insufficient,inadequate','C2'],
      ['misannotate','v','To annotate incorrectly','wrongly,incorrectly','C2'],
      ['preannotate','v','To annotate beforehand','before,in advance','C2'],
      ['coannotate','v','To annotate together','jointly,together','C2'],
      ['reannotatation','n','The act of annotating again','re-comment','C2'],
      ['overannotatation','n','Excessive annotating','excess comment','C2'],
      ['deliberate','v','To think carefully about something','consider,ponder,reflect','B2'],
      ['deliberatation','n','The act of deliberating','consider process','B2'],
      ['deliberatment','n','The result of deliberating','consider outcome','B2'],
      ['deliberatance','n','The state of deliberating','consider state','B2'],
      ['deliberatence','n','The quality of deliberating','consider quality','B2'],
      ['deliberatal','n','An act of deliberating','consider event','C1'],
      ['deliberater','n','One who deliberates','consider person','B2'],
      ['deliberator','n','One who deliberates','consider agent','B2'],
      ['deliberatee','n','One who is deliberated','consider recipient','C1'],
      ['deliberatable','adj','Capable of being deliberated','consider,possible','C1'],
      ['deliberatible','adj','Able to be deliberated','consider,feasible','C1'],
      ['deliberative','adj','Tending to deliberate','consider,active','B2'],
      ['deliberating','adj','Currently deliberating','consider,ongoing','B2'],
      ['deliberated','adj','Having been deliberated','consider,completed','B2'],
      ['redeliberate','v','To deliberate again','consider again,repeat','B2'],
      ['undeliberate','v','To reverse deliberating','reverse,undo','C1'],
      ['overdeliberate','v','To deliberate excessively','excess,too much','C1'],
      ['underdeliberate','v','To deliberate insufficiently','insufficient,inadequate','C1'],
      ['misdeliberate','v','To deliberate incorrectly','wrongly,incorrectly','C1'],
      ['predeliberate','v','To deliberate beforehand','before,in advance','C1'],
      ['codeliberate','v','To deliberate together','jointly,together','C1'],
      ['redeliberatation','n','The act of deliberating again','re-consider','C1'],
      ['overdeliberatation','n','Excessive deliberating','excess consider','C1'],
      ['corroboratation','n','The act of corroborating','confirm process','C1'],
      ['corroboratment','n','The result of corroborating','confirm outcome','C1'],
      ['corroboratance','n','The state of corroborating','confirm state','C1'],
      ['corroboratence','n','The quality of corroborating','confirm quality','C1'],
      ['corroboratal','n','An act of corroborating','confirm event','C2'],
      ['corroborater','n','One who corroborates','confirm person','C1'],
      ['corroborator','n','One who corroborates','confirm agent','C1'],
      ['corroboratee','n','One who is corroborated','confirm recipient','C2'],
      ['corroboratable','adj','Capable of being corroborated','confirm,possible','C2'],
      ['corroboratible','adj','Able to be corroborated','confirm,feasible','C2'],
      ['corroborative','adj','Tending to corroborate','confirm,active','C1'],
      ['corroborating','adj','Currently corroborating','confirm,ongoing','C1'],
      ['corroborated','adj','Having been corroborated','confirm,completed','C1'],
      ['recorroborate','v','To corroborate again','confirm again,repeat','C1'],
      ['uncorroborate','v','To reverse corroborating','reverse,undo','C2'],
      ['overcorroborate','v','To corroborate excessively','excess,too much','C2'],
      ['undercorroborate','v','To corroborate insufficiently','insufficient,inadequate','C2'],
      ['miscorroborate','v','To corroborate incorrectly','wrongly,incorrectly','C2'],
      ['precorroborate','v','To corroborate beforehand','before,in advance','C2'],
      ['cocorroborate','v','To corroborate together','jointly,together','C2'],
      ['recorroboratation','n','The act of corroborating again','re-confirm','C2'],
      ['overcorroboratation','n','Excessive corroborating','excess confirm','C2'],
      ['interpolate','v','To insert something between fixed points','insert,interject,add','C2'],
      ['interpolatation','n','The act of interpolating','insert process','C2'],
      ['interpolatment','n','The result of interpolating','insert outcome','C2'],
      ['interpolatance','n','The state of interpolating','insert state','C2'],
      ['interpolatence','n','The quality of interpolating','insert quality','C2'],
      ['interpolatal','n','An act of interpolating','insert event','C2'],
      ['interpolater','n','One who interpolates','insert person','C2'],
      ['interpolator','n','One who interpolates','insert agent','C2'],
      ['interpolatee','n','One who is interpolated','insert recipient','C2'],
      ['interpolatable','adj','Capable of being interpolated','insert,possible','C2'],
      ['interpolatible','adj','Able to be interpolated','insert,feasible','C2'],
      ['interpolative','adj','Tending to interpolate','insert,active','C2'],
      ['interpolating','adj','Currently interpolating','insert,ongoing','C2'],
      ['interpolated','adj','Having been interpolated','insert,completed','C2'],
      ['reinterpolate','v','To interpolate again','insert again,repeat','C2'],
      ['uninterpolate','v','To reverse interpolating','reverse,undo','C2'],
      ['overinterpolate','v','To interpolate excessively','excess,too much','C2'],
      ['underinterpolate','v','To interpolate insufficiently','insufficient,inadequate','C2'],
      ['misinterpolate','v','To interpolate incorrectly','wrongly,incorrectly','C2'],
      ['preinterpolate','v','To interpolate beforehand','before,in advance','C2'],
      ['cointerpolate','v','To interpolate together','jointly,together','C2'],
      ['reinterpolatation','n','The act of interpolating again','re-insert','C2'],
      ['overinterpolatation','n','Excessive interpolating','excess insert','C2'],
      ['matriculatment','n','The result of matriculating','enrol outcome','C1'],
      ['matriculatance','n','The state of matriculating','enrol state','C1'],
      ['matriculatence','n','The quality of matriculating','enrol quality','C1'],
      ['matriculatal','n','An act of matriculating','enrol event','C2'],
      ['matriculator','n','One who matriculates','enrol agent','C1'],
      ['matriculatee','n','One who is matriculated','enrol recipient','C2'],
      ['matriculatible','adj','Able to be matriculated','enrol,feasible','C2'],
      ['matriculative','adj','Tending to matriculate','enrol,active','C1'],
      ['matriculated','adj','Having been matriculated','enrol,completed','C1'],
      ['rematriculate','v','To matriculate again','enrol again,repeat','C1'],
      ['unmatriculate','v','To reverse matriculating','reverse,undo','C2'],
      ['overmatriculate','v','To matriculate excessively','excess,too much','C2'],
      ['undermatriculate','v','To matriculate insufficiently','insufficient,inadequate','C2'],
      ['mismatriculate','v','To matriculate incorrectly','wrongly,incorrectly','C2'],
      ['prematriculate','v','To matriculate beforehand','before,in advance','C2'],
      ['comatriculate','v','To matriculate together','jointly,together','C2'],
      ['rematriculatation','n','The act of matriculating again','re-enrol','C2'],
      ['overmatriculatation','n','Excessive matriculating','excess enrol','C2'],
      ['benchmarkic','adj','Of or relating to benchmark','standard-based,characteristic','B2'],
      ['benchmarkous','adj','Full of benchmark','standard-filled,abundant','C1'],
      ['benchmarkful','adj','Full of benchmark','standard-rich,abounding','B2'],
      ['benchmarkless','adj','Without benchmark','lacking,without','B2'],
      ['benchmarkism','n','The ideology of benchmark','standard ideology,doctrine','C1'],
      ['benchmarkist','n','A person focused on benchmark','standard specialist,advocate','C1'],
      ['benchmarkise','v','To make into benchmark','standard,convert','C1'],
      ['benchmarkize','v','To make or become benchmark','standard,transform','C1'],
      ['antibenchmark','adj','Opposed to benchmark','against,opposing','C1'],
      ['nonbenchmark','adj','Not involving benchmark','without,lacking','B2'],
      ['prebenchmark','n','Before benchmark','preceding,prior','C1'],
      ['postbenchmark','n','After benchmark','following,subsequent','C1'],
      ['subbenchmark','n','A subdivision of benchmark','subset,branch','C1'],
    ],
  },
  collocations: {}
};
