// Auto-generated vocab boost group 56
module.exports = {
  vocab: {
    science: [
      ['subentropy','n','A subdivision of entropy','subset,branch','C2'],
      ['multientropy','adj','Involving many entropys','multiple,several','C2'],
      ['interentropy','adj','Between entropys','cross,between','C2'],
      ['paradigmic','adj','Of or relating to paradigm','model-based,characteristic','B2'],
      ['paradigmous','adj','Full of paradigm','model-filled,abundant','C1'],
      ['paradigmful','adj','Full of paradigm','model-rich,abounding','B2'],
      ['paradigmless','adj','Without paradigm','lacking,without','B2'],
      ['paradigmism','n','The ideology of paradigm','model ideology,doctrine','C1'],
      ['paradigmist','n','A person focused on paradigm','model specialist,advocate','C1'],
      ['paradigmise','v','To make into paradigm','model,convert','C1'],
      ['paradigmize','v','To make or become paradigm','model,transform','C1'],
      ['antiparadigm','adj','Opposed to paradigm','against,opposing','C1'],
      ['nonparadigm','adj','Not involving paradigm','without,lacking','B2'],
      ['preparadigm','n','Before paradigm','preceding,prior','C1'],
      ['postparadigm','n','After paradigm','following,subsequent','C1'],
      ['subparadigm','n','A subdivision of paradigm','subset,branch','C1'],
      ['multiparadigm','adj','Involving many paradigms','multiple,several','C1'],
      ['interparadigm','adj','Between paradigms','cross,between','C1'],
      ['phenomenonal','adj','Relating to phenomenon','occurrence-related,pertaining to','B2'],
      ['phenomenonic','adj','Of or relating to phenomenon','occurrence-based,characteristic','B2'],
      ['phenomenonous','adj','Full of phenomenon','occurrence-filled,abundant','C1'],
      ['phenomenonful','adj','Full of phenomenon','occurrence-rich,abounding','B2'],
      ['phenomenonless','adj','Without phenomenon','lacking,without','B2'],
      ['phenomenonism','n','The ideology of phenomenon','occurrence ideology,doctrine','C1'],
      ['phenomenonist','n','A person focused on phenomenon','occurrence specialist,advocate','C1'],
      ['phenomenonise','v','To make into phenomenon','occurrence,convert','C1'],
      ['phenomenonize','v','To make or become phenomenon','occurrence,transform','C1'],
      ['antiphenomenon','adj','Opposed to phenomenon','against,opposing','C1'],
      ['nonphenomenon','adj','Not involving phenomenon','without,lacking','B2'],
      ['prephenomenon','n','Before phenomenon','preceding,prior','C1'],
      ['postphenomenon','n','After phenomenon','following,subsequent','C1'],
      ['subphenomenon','n','A subdivision of phenomenon','subset,branch','C1'],
      ['multiphenomenon','adj','Involving many phenomenons','multiple,several','C1'],
      ['interphenomenon','adj','Between phenomenons','cross,between','C1'],
      ['taxonomyal','adj','Relating to taxonomy','classification-related,pertaining to','C1'],
      ['taxonomyic','adj','Of or relating to taxonomy','classification-based,characteristic','C1'],
      ['taxonomyous','adj','Full of taxonomy','classification-filled,abundant','C2'],
      ['taxonomyful','adj','Full of taxonomy','classification-rich,abounding','C1'],
      ['taxonomyless','adj','Without taxonomy','lacking,without','C1'],
      ['taxonomyism','n','The ideology of taxonomy','classification ideology,doctrine','C2'],
      ['taxonomyist','n','A person focused on taxonomy','classification specialist,advocate','C2'],
      ['taxonomyise','v','To make into taxonomy','classification,convert','C2'],
      ['taxonomyize','v','To make or become taxonomy','classification,transform','C2'],
      ['antitaxonomy','adj','Opposed to taxonomy','against,opposing','C2'],
      ['nontaxonomy','adj','Not involving taxonomy','without,lacking','C1'],
      ['pretaxonomy','n','Before taxonomy','preceding,prior','C2'],
      ['posttaxonomy','n','After taxonomy','following,subsequent','C2'],
      ['subtaxonomy','n','A subdivision of taxonomy','subset,branch','C2'],
      ['multitaxonomy','adj','Involving many taxonomys','multiple,several','C2'],
      ['intertaxonomy','adj','Between taxonomys','cross,between','C2'],
      ['peer reviewal','adj','Relating to peer review','expert evaluation-related,pertaining to','B2'],
      ['peer reviewic','adj','Of or relating to peer review','expert evaluation-based,characteristic','B2'],
      ['peer reviewous','adj','Full of peer review','expert evaluation-filled,abundant','C1'],
      ['peer reviewful','adj','Full of peer review','expert evaluation-rich,abounding','B2'],
      ['peer reviewless','adj','Without peer review','lacking,without','B2'],
      ['peer reviewism','n','The ideology of peer review','expert evaluation ideology,doctrine','C1'],
      ['peer reviewist','n','A person focused on peer review','expert evaluation specialist,advocate','C1'],
      ['peer reviewise','v','To make into peer review','expert evaluation,convert','C1'],
      ['peer reviewize','v','To make or become peer review','expert evaluation,transform','C1'],
      ['antipeer review','adj','Opposed to peer review','against,opposing','C1'],
      ['nonpeer review','adj','Not involving peer review','without,lacking','B2'],
      ['prepeer review','n','Before peer review','preceding,prior','C1'],
      ['postpeer review','n','After peer review','following,subsequent','C1'],
      ['subpeer review','n','A subdivision of peer review','subset,branch','C1'],
      ['multipeer review','adj','Involving many peer reviews','multiple,several','C1'],
      ['interpeer review','adj','Between peer reviews','cross,between','C1'],
      ['control group','n','A group used as a baseline in experiments','reference group,baseline group','B2'],
      ['control groupal','adj','Relating to control group','reference group-related,pertaining to','B2'],
      ['control groupic','adj','Of or relating to control group','reference group-based,characteristic','B2'],
      ['control groupous','adj','Full of control group','reference group-filled,abundant','C1'],
      ['control groupful','adj','Full of control group','reference group-rich,abounding','B2'],
      ['control groupless','adj','Without control group','lacking,without','B2'],
      ['control groupism','n','The ideology of control group','reference group ideology,doctrine','C1'],
      ['control groupist','n','A person focused on control group','reference group specialist,advocate','C1'],
      ['control groupise','v','To make into control group','reference group,convert','C1'],
      ['control groupize','v','To make or become control group','reference group,transform','C1'],
      ['anticontrol group','adj','Opposed to control group','against,opposing','C1'],
      ['noncontrol group','adj','Not involving control group','without,lacking','B2'],
      ['precontrol group','n','Before control group','preceding,prior','C1'],
      ['postcontrol group','n','After control group','following,subsequent','C1'],
      ['subcontrol group','n','A subdivision of control group','subset,branch','C1'],
      ['multicontrol group','adj','Involving many control groups','multiple,several','C1'],
      ['intercontrol group','adj','Between control groups','cross,between','C1'],
      ['double blind','adj','Where neither subject nor tester knows','unbiased,concealed,anonymous','C1'],
      ['double blindly','adv','In a double blind manner','unbiased way','C1'],
      ['double blindness','n','The quality of being double blind','unbiased quality','C1'],
      ['double blindity','n','The state of being double blind','unbiased condition','C2'],
      ['undouble blind','adj','Not double blind','not unbiased','C1'],
      ['indouble blind','adj','Not double blind','not unbiased','C2'],
      ['nondouble blind','adj','Not double blind','not unbiased','C1'],
      ['semidouble blind','adj','Partially double blind','partly unbiased','C2'],
      ['overdouble blind','adj','Excessively double blind','too unbiased','C2'],
      ['ultradouble blind','adj','Extremely double blind','very unbiased','C2'],
      ['longitudinally','adv','In a longitudinal manner','long-term way','C1'],
      ['longitudinalness','n','The quality of being longitudinal','long-term quality','C1'],
      ['longitudinality','n','The state of being longitudinal','long-term condition','C2'],
      ['unlongitudinal','adj','Not longitudinal','not long-term','C1'],
      ['inlongitudinal','adj','Not longitudinal','not long-term','C2'],
      ['nonlongitudinal','adj','Not longitudinal','not long-term','C1'],
      ['semilongitudinal','adj','Partially longitudinal','partly long-term','C2'],
      ['overlongitudinal','adj','Excessively longitudinal','too long-term','C2'],
      ['ultralongitudinal','adj','Extremely longitudinal','very long-term','C2'],
      ['interdisciplinarily','adv','In a interdisciplinary manner','cross-disciplinary way','C1'],
      ['interdisciplinarness','n','The quality of being interdisciplinary','cross-disciplinary quality','C1'],
      ['interdisciplinarity','n','The state of being interdisciplinary','cross-disciplinary condition','C2'],
      ['uninterdisciplinary','adj','Not interdisciplinary','not cross-disciplinary','C1'],
      ['ininterdisciplinary','adj','Not interdisciplinary','not cross-disciplinary','C2'],
      ['noninterdisciplinary','adj','Not interdisciplinary','not cross-disciplinary','C1'],
      ['semiinterdisciplinary','adj','Partially interdisciplinary','partly cross-disciplinary','C2'],
      ['overinterdisciplinary','adj','Excessively interdisciplinary','too cross-disciplinary','C2'],
      ['ultrainterdisciplinary','adj','Extremely interdisciplinary','very cross-disciplinary','C2'],
      ['spectrometric','adj','Relating to measurement of spectra','spectral,analytical,diagnostic','C2'],
      ['spectrometricly','adv','In a spectrometric manner','spectral way','C2'],
      ['spectrometricness','n','The quality of being spectrometric','spectral quality','C2'],
      ['spectrometricity','n','The state of being spectrometric','spectral condition','C2'],
      ['unspectrometric','adj','Not spectrometric','not spectral','C2'],
      ['inspectrometric','adj','Not spectrometric','not spectral','C2'],
      ['nonspectrometric','adj','Not spectrometric','not spectral','C2'],
      ['semispectrometric','adj','Partially spectrometric','partly spectral','C2'],
      ['overspectrometric','adj','Excessively spectrometric','too spectral','C2'],
      ['ultraspectrometric','adj','Extremely spectrometric','very spectral','C2'],
      ['stochasticly','adv','In a stochastic manner','random way','C2'],
      ['stochasticness','n','The quality of being stochastic','random quality','C2'],
      ['stochasticity','n','The state of being stochastic','random condition','C2'],
      ['unstochastic','adj','Not stochastic','not random','C2'],
      ['instochastic','adj','Not stochastic','not random','C2'],
      ['nonstochastic','adj','Not stochastic','not random','C2'],
      ['semistochastic','adj','Partially stochastic','partly random','C2'],
      ['overstochastic','adj','Excessively stochastic','too random','C2'],
      ['ultrastochastic','adj','Extremely stochastic','very random','C2'],
      ['thermodynamic','adj','Relating to heat and energy','heat-related,energy-based','C1'],
      ['thermodynamicly','adv','In a thermodynamic manner','heat-related way','C1'],
      ['thermodynamicness','n','The quality of being thermodynamic','heat-related quality','C1'],
      ['thermodynamicity','n','The state of being thermodynamic','heat-related condition','C2'],
      ['unthermodynamic','adj','Not thermodynamic','not heat-related','C1'],
      ['inthermodynamic','adj','Not thermodynamic','not heat-related','C2'],
      ['nonthermodynamic','adj','Not thermodynamic','not heat-related','C1'],
      ['semithermodynamic','adj','Partially thermodynamic','partly heat-related','C2'],
      ['overthermodynamic','adj','Excessively thermodynamic','too heat-related','C2'],
      ['ultrathermodynamic','adj','Extremely thermodynamic','very heat-related','C2'],
      ['electromagnetic','adj','Relating to electric and magnetic fields','electric-magnetic,EM,radiation','B2'],
      ['electromagneticly','adv','In a electromagnetic manner','electric-magnetic way','B2'],
      ['electromagneticness','n','The quality of being electromagnetic','electric-magnetic quality','B2'],
      ['electromagneticity','n','The state of being electromagnetic','electric-magnetic condition','C1'],
      ['unelectromagnetic','adj','Not electromagnetic','not electric-magnetic','B2'],
      ['inelectromagnetic','adj','Not electromagnetic','not electric-magnetic','C1'],
      ['nonelectromagnetic','adj','Not electromagnetic','not electric-magnetic','B2'],
      ['semielectromagnetic','adj','Partially electromagnetic','partly electric-magnetic','C1'],
      ['overelectromagnetic','adj','Excessively electromagnetic','too electric-magnetic','C1'],
      ['ultraelectromagnetic','adj','Extremely electromagnetic','very electric-magnetic','C1'],
      ['geothermally','adv','In a geothermal manner','earth-heat way','B2'],
      ['geothermalness','n','The quality of being geothermal','earth-heat quality','B2'],
      ['geothermality','n','The state of being geothermal','earth-heat condition','C1'],
      ['ungeothermal','adj','Not geothermal','not earth-heat','B2'],
      ['ingeothermal','adj','Not geothermal','not earth-heat','C1'],
      ['nongeothermal','adj','Not geothermal','not earth-heat','B2'],
      ['semigeothermal','adj','Partially geothermal','partly earth-heat','C1'],
      ['overgeothermal','adj','Excessively geothermal','too earth-heat','C1'],
      ['ultrageothermal','adj','Extremely geothermal','very earth-heat','C1'],
      ['biotechnological','adj','Relating to the use of living systems','biotech,bio-based,genetic','B2'],
      ['biotechnologically','adv','In a biotechnological manner','biotech way','B2'],
      ['biotechnologicalness','n','The quality of being biotechnological','biotech quality','B2'],
      ['biotechnologicality','n','The state of being biotechnological','biotech condition','C1'],
      ['unbiotechnological','adj','Not biotechnological','not biotech','B2'],
      ['inbiotechnological','adj','Not biotechnological','not biotech','C1'],
      ['nonbiotechnological','adj','Not biotechnological','not biotech','B2'],
      ['semibiotechnological','adj','Partially biotechnological','partly biotech','C1'],
      ['overbiotechnological','adj','Excessively biotechnological','too biotech','C1'],
      ['ultrabiotechnological','adj','Extremely biotechnological','very biotech','C1'],
    ],
    crime: [
      ['prosecute','v','To bring legal proceedings against','charge,sue,indict','B2'],
      ['prosecutation','n','The act of prosecuting','charge process','B2'],
      ['prosecutment','n','The result of prosecuting','charge outcome','B2'],
      ['prosecutance','n','The state of prosecuting','charge state','B2'],
      ['prosecutence','n','The quality of prosecuting','charge quality','B2'],
      ['prosecutal','n','An act of prosecuting','charge event','C1'],
      ['prosecuter','n','One who prosecutes','charge person','B2'],
      ['prosecutor','n','One who prosecutes','charge agent','B2'],
      ['prosecutee','n','One who is prosecuted','charge recipient','C1'],
      ['prosecutable','adj','Capable of being prosecuted','charge,possible','C1'],
      ['prosecutible','adj','Able to be prosecuted','charge,feasible','C1'],
      ['prosecutive','adj','Tending to prosecute','charge,active','B2'],
      ['prosecuting','adj','Currently prosecuting','charge,ongoing','B2'],
      ['prosecuted','adj','Having been prosecuted','charge,completed','B2'],
      ['reprosecute','v','To prosecute again','charge again,repeat','B2'],
      ['unprosecute','v','To reverse prosecuting','reverse,undo','C1'],
      ['overprosecute','v','To prosecute excessively','excess,too much','C1'],
      ['underprosecute','v','To prosecute insufficiently','insufficient,inadequate','C1'],
      ['misprosecute','v','To prosecute incorrectly','wrongly,incorrectly','C1'],
      ['preprosecute','v','To prosecute beforehand','before,in advance','C1'],
      ['coprosecute','v','To prosecute together','jointly,together','C1'],
      ['reprosecutation','n','The act of prosecuting again','re-charge','C1'],
      ['overprosecutation','n','Excessive prosecuting','excess charge','C1'],
      ['incarceratment','n','The result of incarcerating','imprison outcome','C1'],
      ['incarceratance','n','The state of incarcerating','imprison state','C1'],
      ['incarceratence','n','The quality of incarcerating','imprison quality','C1'],
      ['incarceratal','n','An act of incarcerating','imprison event','C2'],
      ['incarcerator','n','One who incarcerates','imprison agent','C1'],
      ['incarceratee','n','One who is incarcerated','imprison recipient','C2'],
      ['incarceratible','adj','Able to be incarcerated','imprison,feasible','C2'],
      ['incarcerative','adj','Tending to incarcerate','imprison,active','C1'],
      ['incarcerated','adj','Having been incarcerated','imprison,completed','C1'],
      ['reincarcerate','v','To incarcerate again','imprison again,repeat','C1'],
      ['unincarcerate','v','To reverse incarcerating','reverse,undo','C2'],
      ['overincarcerate','v','To incarcerate excessively','excess,too much','C2'],
      ['underincarcerate','v','To incarcerate insufficiently','insufficient,inadequate','C2'],
      ['misincarcerate','v','To incarcerate incorrectly','wrongly,incorrectly','C2'],
      ['preincarcerate','v','To incarcerate beforehand','before,in advance','C2'],
      ['coincarcerate','v','To incarcerate together','jointly,together','C2'],
      ['reincarceratation','n','The act of incarcerating again','re-imprison','C2'],
      ['overincarceratation','n','Excessive incarcerating','excess imprison','C2'],
      ['adjudicatment','n','The result of adjudicating','judge outcome','C1'],
      ['adjudicatance','n','The state of adjudicating','judge state','C1'],
      ['adjudicatence','n','The quality of adjudicating','judge quality','C1'],
      ['adjudicatal','n','An act of adjudicating','judge event','C2'],
      ['adjudicator','n','One who adjudicates','judge agent','C1'],
      ['adjudicatee','n','One who is adjudicated','judge recipient','C2'],
      ['adjudicatible','adj','Able to be adjudicated','judge,feasible','C2'],
      ['adjudicative','adj','Tending to adjudicate','judge,active','C1'],
      ['adjudicated','adj','Having been adjudicated','judge,completed','C1'],
      ['readjudicate','v','To adjudicate again','judge again,repeat','C1'],
      ['unadjudicate','v','To reverse adjudicating','reverse,undo','C2'],
      ['overadjudicate','v','To adjudicate excessively','excess,too much','C2'],
      ['underadjudicate','v','To adjudicate insufficiently','insufficient,inadequate','C2'],
      ['misadjudicate','v','To adjudicate incorrectly','wrongly,incorrectly','C2'],
      ['preadjudicate','v','To adjudicate beforehand','before,in advance','C2'],
      ['coadjudicate','v','To adjudicate together','jointly,together','C2'],
      ['readjudicatation','n','The act of adjudicating again','re-judge','C2'],
      ['overadjudicatation','n','Excessive adjudicating','excess judge','C2'],
      ['confiscatation','n','The act of confiscating','seize process','B2'],
      ['confiscatment','n','The result of confiscating','seize outcome','B2'],
      ['confiscatance','n','The state of confiscating','seize state','B2'],
      ['confiscatence','n','The quality of confiscating','seize quality','B2'],
      ['confiscatal','n','An act of confiscating','seize event','C1'],
      ['confiscater','n','One who confiscates','seize person','B2'],
      ['confiscator','n','One who confiscates','seize agent','B2'],
      ['confiscatee','n','One who is confiscated','seize recipient','C1'],
      ['confiscatable','adj','Capable of being confiscated','seize,possible','C1'],
      ['confiscatible','adj','Able to be confiscated','seize,feasible','C1'],
      ['confiscative','adj','Tending to confiscate','seize,active','B2'],
      ['confiscating','adj','Currently confiscating','seize,ongoing','B2'],
      ['confiscated','adj','Having been confiscated','seize,completed','B2'],
      ['reconfiscate','v','To confiscate again','seize again,repeat','B2'],
      ['unconfiscate','v','To reverse confiscating','reverse,undo','C1'],
      ['overconfiscate','v','To confiscate excessively','excess,too much','C1'],
      ['underconfiscate','v','To confiscate insufficiently','insufficient,inadequate','C1'],
      ['misconfiscate','v','To confiscate incorrectly','wrongly,incorrectly','C1'],
      ['preconfiscate','v','To confiscate beforehand','before,in advance','C1'],
      ['coconfiscate','v','To confiscate together','jointly,together','C1'],
      ['reconfiscatation','n','The act of confiscating again','re-seize','C1'],
      ['overconfiscatation','n','Excessive confiscating','excess seize','C1'],
    ],
  },
  collocations: {}
};
