// Auto-generated vocab boost group 89
module.exports = {
  vocab: {
    language: [
      ['pragmaticity','n','The state of being pragmatic','practical condition','C2'],
      ['unpragmatic','adj','Not pragmatic','not practical','C1'],
      ['inpragmatic','adj','Not pragmatic','not practical','C2'],
      ['nonpragmatic','adj','Not pragmatic','not practical','C1'],
      ['semipragmatic','adj','Partially pragmatic','partly practical','C2'],
      ['overpragmatic','adj','Excessively pragmatic','too practical','C2'],
      ['ultrapragmatic','adj','Extremely pragmatic','very practical','C2'],
      ['pejoratively','adv','In a pejorative manner','derogatory way','C2'],
      ['pejorativeness','n','The quality of being pejorative','derogatory quality','C2'],
      ['pejorativeity','n','The state of being pejorative','derogatory condition','C2'],
      ['unpejorative','adj','Not pejorative','not derogatory','C2'],
      ['inpejorative','adj','Not pejorative','not derogatory','C2'],
      ['nonpejorative','adj','Not pejorative','not derogatory','C2'],
      ['semipejorative','adj','Partially pejorative','partly derogatory','C2'],
      ['overpejorative','adj','Excessively pejorative','too derogatory','C2'],
      ['ultrapejorative','adj','Extremely pejorative','very derogatory','C2'],
      ['prosodyic','adj','Of or relating to prosody','intonation-based,characteristic','C2'],
      ['prosodyous','adj','Full of prosody','intonation-filled,abundant','C2'],
      ['prosodyful','adj','Full of prosody','intonation-rich,abounding','C2'],
      ['prosodyless','adj','Without prosody','lacking,without','C2'],
      ['prosodyism','n','The ideology of prosody','intonation ideology,doctrine','C2'],
      ['prosodyist','n','A person focused on prosody','intonation specialist,advocate','C2'],
      ['prosodyise','v','To make into prosody','intonation,convert','C2'],
      ['prosodyize','v','To make or become prosody','intonation,transform','C2'],
      ['antiprosody','adj','Opposed to prosody','against,opposing','C2'],
      ['nonprosody','adj','Not involving prosody','without,lacking','C2'],
      ['preprosody','n','Before prosody','preceding,prior','C2'],
      ['postprosody','n','After prosody','following,subsequent','C2'],
      ['subprosody','n','A subdivision of prosody','subset,branch','C2'],
      ['multiprosody','adj','Involving many prosodys','multiple,several','C2'],
      ['interprosody','adj','Between prosodys','cross,between','C2'],
      ['semioticsic','adj','Of or relating to semiotics','sign study-based,characteristic','C2'],
      ['semioticsous','adj','Full of semiotics','sign study-filled,abundant','C2'],
      ['semioticsful','adj','Full of semiotics','sign study-rich,abounding','C2'],
      ['semioticsless','adj','Without semiotics','lacking,without','C2'],
      ['semioticsism','n','The ideology of semiotics','sign study ideology,doctrine','C2'],
      ['semioticsist','n','A person focused on semiotics','sign study specialist,advocate','C2'],
      ['semioticsise','v','To make into semiotics','sign study,convert','C2'],
      ['semioticsize','v','To make or become semiotics','sign study,transform','C2'],
      ['antisemiotics','adj','Opposed to semiotics','against,opposing','C2'],
      ['nonsemiotics','adj','Not involving semiotics','without,lacking','C2'],
      ['presemiotics','n','Before semiotics','preceding,prior','C2'],
      ['postsemiotics','n','After semiotics','following,subsequent','C2'],
      ['subsemiotics','n','A subdivision of semiotics','subset,branch','C2'],
      ['multisemiotics','adj','Involving many semioticss','multiple,several','C2'],
      ['intersemiotics','adj','Between semioticss','cross,between','C2'],
      ['polyglotal','adj','Relating to polyglot','multilingual person-related,pertaining to','C1'],
      ['polyglotic','adj','Of or relating to polyglot','multilingual person-based,characteristic','C1'],
      ['polyglotous','adj','Full of polyglot','multilingual person-filled,abundant','C2'],
      ['polyglotful','adj','Full of polyglot','multilingual person-rich,abounding','C1'],
      ['polyglotless','adj','Without polyglot','lacking,without','C1'],
      ['polyglotism','n','The ideology of polyglot','multilingual person ideology,doctrine','C2'],
      ['polyglotist','n','A person focused on polyglot','multilingual person specialist,advocate','C2'],
      ['polyglotise','v','To make into polyglot','multilingual person,convert','C2'],
      ['polyglotize','v','To make or become polyglot','multilingual person,transform','C2'],
      ['antipolyglot','adj','Opposed to polyglot','against,opposing','C2'],
      ['nonpolyglot','adj','Not involving polyglot','without,lacking','C1'],
      ['prepolyglot','n','Before polyglot','preceding,prior','C2'],
      ['postpolyglot','n','After polyglot','following,subsequent','C2'],
      ['subpolyglot','n','A subdivision of polyglot','subset,branch','C2'],
      ['multipolyglot','adj','Involving many polyglots','multiple,several','C2'],
      ['interpolyglot','adj','Between polyglots','cross,between','C2'],
      ['pidginization','n','The act of pidginizing','simplify process','C2'],
      ['pidginizment','n','The result of pidginizing','simplify outcome','C2'],
      ['pidginizance','n','The state of pidginizing','simplify state','C2'],
      ['pidginizence','n','The quality of pidginizing','simplify quality','C2'],
      ['pidginizal','n','An act of pidginizing','simplify event','C2'],
      ['pidginizer','n','One who pidginizes','simplify person','C2'],
      ['pidginizor','n','One who pidginizes','simplify agent','C2'],
      ['pidginizee','n','One who is pidginized','simplify recipient','C2'],
      ['pidginizable','adj','Capable of being pidginized','simplify,possible','C2'],
      ['pidginizible','adj','Able to be pidginized','simplify,feasible','C2'],
      ['pidginizive','adj','Tending to pidginize','simplify,active','C2'],
      ['pidginizing','adj','Currently pidginizing','simplify,ongoing','C2'],
      ['pidginized','adj','Having been pidginized','simplify,completed','C2'],
      ['repidginize','v','To pidginize again','simplify again,repeat','C2'],
      ['unpidginize','v','To reverse pidginizing','reverse,undo','C2'],
      ['overpidginize','v','To pidginize excessively','excess,too much','C2'],
      ['underpidginize','v','To pidginize insufficiently','insufficient,inadequate','C2'],
      ['mispidginize','v','To pidginize incorrectly','wrongly,incorrectly','C2'],
      ['prepidginize','v','To pidginize beforehand','before,in advance','C2'],
      ['copidginize','v','To pidginize together','jointly,together','C2'],
      ['repidginization','n','The act of pidginizing again','re-simplify','C2'],
      ['overpidginization','n','Excessive pidginizing','excess simplify','C2'],
    ],
    globalization: [
      ['homogenize','v','To make uniform or similar','standardize,unify,level','C1'],
      ['homogenization','n','The act of homogenizing','standardize process','C1'],
      ['homogenizment','n','The result of homogenizing','standardize outcome','C1'],
      ['homogenizance','n','The state of homogenizing','standardize state','C1'],
      ['homogenizence','n','The quality of homogenizing','standardize quality','C1'],
      ['homogenizal','n','An act of homogenizing','standardize event','C2'],
      ['homogenizer','n','One who homogenizes','standardize person','C1'],
      ['homogenizor','n','One who homogenizes','standardize agent','C1'],
      ['homogenizee','n','One who is homogenized','standardize recipient','C2'],
      ['homogenizable','adj','Capable of being homogenized','standardize,possible','C2'],
      ['homogenizible','adj','Able to be homogenized','standardize,feasible','C2'],
      ['homogenizive','adj','Tending to homogenize','standardize,active','C1'],
      ['homogenizing','adj','Currently homogenizing','standardize,ongoing','C1'],
      ['homogenized','adj','Having been homogenized','standardize,completed','C1'],
      ['rehomogenize','v','To homogenize again','standardize again,repeat','C1'],
      ['unhomogenize','v','To reverse homogenizing','reverse,undo','C2'],
      ['overhomogenize','v','To homogenize excessively','excess,too much','C2'],
      ['underhomogenize','v','To homogenize insufficiently','insufficient,inadequate','C2'],
      ['mishomogenize','v','To homogenize incorrectly','wrongly,incorrectly','C2'],
      ['prehomogenize','v','To homogenize beforehand','before,in advance','C2'],
      ['cohomogenize','v','To homogenize together','jointly,together','C2'],
      ['rehomogenization','n','The act of homogenizing again','re-standardize','C2'],
      ['overhomogenization','n','Excessive homogenizing','excess standardize','C2'],
      ['localize','v','To adapt for a local market','customize,adapt,tailor','B2'],
      ['localization','n','The act of localizing','customize process','B2'],
      ['localizment','n','The result of localizing','customize outcome','B2'],
      ['localizance','n','The state of localizing','customize state','B2'],
      ['localizence','n','The quality of localizing','customize quality','B2'],
      ['localizal','n','An act of localizing','customize event','C1'],
      ['localizer','n','One who localizes','customize person','B2'],
      ['localizor','n','One who localizes','customize agent','B2'],
      ['localizee','n','One who is localized','customize recipient','C1'],
      ['localizable','adj','Capable of being localized','customize,possible','C1'],
      ['localizible','adj','Able to be localized','customize,feasible','C1'],
      ['localizive','adj','Tending to localize','customize,active','B2'],
      ['localizing','adj','Currently localizing','customize,ongoing','B2'],
      ['localized','adj','Having been localized','customize,completed','B2'],
      ['relocalize','v','To localize again','customize again,repeat','B2'],
      ['unlocalize','v','To reverse localizing','reverse,undo','C1'],
      ['overlocalize','v','To localize excessively','excess,too much','C1'],
      ['underlocalize','v','To localize insufficiently','insufficient,inadequate','C1'],
      ['mislocalize','v','To localize incorrectly','wrongly,incorrectly','C1'],
      ['prelocalize','v','To localize beforehand','before,in advance','C1'],
      ['colocalize','v','To localize together','jointly,together','C1'],
      ['relocalization','n','The act of localizing again','re-customize','C1'],
      ['overlocalization','n','Excessive localizing','excess customize','C1'],
      ['expatriatation','n','The act of expatriating','emigrate process','C1'],
      ['expatriatment','n','The result of expatriating','emigrate outcome','C1'],
      ['expatriatance','n','The state of expatriating','emigrate state','C1'],
      ['expatriatence','n','The quality of expatriating','emigrate quality','C1'],
      ['expatriatal','n','An act of expatriating','emigrate event','C2'],
      ['expatriater','n','One who expatriates','emigrate person','C1'],
      ['expatriator','n','One who expatriates','emigrate agent','C1'],
      ['expatriatee','n','One who is expatriated','emigrate recipient','C2'],
      ['expatriatable','adj','Capable of being expatriated','emigrate,possible','C2'],
      ['expatriatible','adj','Able to be expatriated','emigrate,feasible','C2'],
      ['expatriative','adj','Tending to expatriate','emigrate,active','C1'],
      ['expatriating','adj','Currently expatriating','emigrate,ongoing','C1'],
      ['expatriated','adj','Having been expatriated','emigrate,completed','C1'],
      ['reexpatriate','v','To expatriate again','emigrate again,repeat','C1'],
      ['unexpatriate','v','To reverse expatriating','reverse,undo','C2'],
      ['overexpatriate','v','To expatriate excessively','excess,too much','C2'],
      ['underexpatriate','v','To expatriate insufficiently','insufficient,inadequate','C2'],
      ['misexpatriate','v','To expatriate incorrectly','wrongly,incorrectly','C2'],
      ['preexpatriate','v','To expatriate beforehand','before,in advance','C2'],
      ['coexpatriate','v','To expatriate together','jointly,together','C2'],
      ['reexpatriatation','n','The act of expatriating again','re-emigrate','C2'],
      ['overexpatriatation','n','Excessive expatriating','excess emigrate','C2'],
      ['protectionismic','adj','Of or relating to protectionism','trade barriers-based,characteristic','B2'],
      ['protectionismous','adj','Full of protectionism','trade barriers-filled,abundant','C1'],
      ['protectionismful','adj','Full of protectionism','trade barriers-rich,abounding','B2'],
      ['protectionismless','adj','Without protectionism','lacking,without','B2'],
      ['protectionismism','n','The ideology of protectionism','trade barriers ideology,doctrine','C1'],
      ['protectionismist','n','A person focused on protectionism','trade barriers specialist,advocate','C1'],
      ['protectionismise','v','To make into protectionism','trade barriers,convert','C1'],
      ['protectionismize','v','To make or become protectionism','trade barriers,transform','C1'],
      ['antiprotectionism','adj','Opposed to protectionism','against,opposing','C1'],
      ['nonprotectionism','adj','Not involving protectionism','without,lacking','B2'],
      ['preprotectionism','n','Before protectionism','preceding,prior','C1'],
      ['postprotectionism','n','After protectionism','following,subsequent','C1'],
      ['subprotectionism','n','A subdivision of protectionism','subset,branch','C1'],
      ['multiprotectionism','adj','Involving many protectionisms','multiple,several','C1'],
      ['interprotectionism','adj','Between protectionisms','cross,between','C1'],
      ['multilateralismal','adj','Relating to multilateralism','international cooperation-related,pertaining to','C1'],
      ['multilateralismic','adj','Of or relating to multilateralism','international cooperation-based,characteristic','C1'],
      ['multilateralismous','adj','Full of multilateralism','international cooperation-filled,abundant','C2'],
      ['multilateralismful','adj','Full of multilateralism','international cooperation-rich,abounding','C1'],
      ['multilateralismless','adj','Without multilateralism','lacking,without','C1'],
      ['multilateralismism','n','The ideology of multilateralism','international cooperation ideology,doctrine','C2'],
      ['multilateralismist','n','A person focused on multilateralism','international cooperation specialist,advocate','C2'],
      ['multilateralismise','v','To make into multilateralism','international cooperation,convert','C2'],
      ['multilateralismize','v','To make or become multilateralism','international cooperation,transform','C2'],
      ['antimultilateralism','adj','Opposed to multilateralism','against,opposing','C2'],
      ['nonmultilateralism','adj','Not involving multilateralism','without,lacking','C1'],
      ['premultilateralism','n','Before multilateralism','preceding,prior','C2'],
      ['postmultilateralism','n','After multilateralism','following,subsequent','C2'],
      ['submultilateralism','n','A subdivision of multilateralism','subset,branch','C2'],
      ['multimultilateralism','adj','Involving many multilateralisms','multiple,several','C2'],
      ['intermultilateralism','adj','Between multilateralisms','cross,between','C2'],
      ['xenophobiaic','adj','Of or relating to xenophobia','racism-based,characteristic','C1'],
      ['xenophobiaous','adj','Full of xenophobia','racism-filled,abundant','C2'],
      ['xenophobiaful','adj','Full of xenophobia','racism-rich,abounding','C1'],
      ['xenophobialess','adj','Without xenophobia','lacking,without','C1'],
      ['xenophobiaism','n','The ideology of xenophobia','racism ideology,doctrine','C2'],
      ['xenophobiaist','n','A person focused on xenophobia','racism specialist,advocate','C2'],
      ['xenophobiaise','v','To make into xenophobia','racism,convert','C2'],
      ['xenophobiaize','v','To make or become xenophobia','racism,transform','C2'],
      ['antixenophobia','adj','Opposed to xenophobia','against,opposing','C2'],
      ['nonxenophobia','adj','Not involving xenophobia','without,lacking','C1'],
      ['prexenophobia','n','Before xenophobia','preceding,prior','C2'],
      ['postxenophobia','n','After xenophobia','following,subsequent','C2'],
      ['subxenophobia','n','A subdivision of xenophobia','subset,branch','C2'],
      ['multixenophobia','adj','Involving many xenophobias','multiple,several','C2'],
      ['interxenophobia','adj','Between xenophobias','cross,between','C2'],
      ['cosmopolitanism','n','The ideology of global citizenship','internationalism,worldliness','C1'],
      ['cosmopolitanismal','adj','Relating to cosmopolitanism','internationalism-related,pertaining to','C1'],
      ['cosmopolitanismic','adj','Of or relating to cosmopolitanism','internationalism-based,characteristic','C1'],
      ['cosmopolitanismous','adj','Full of cosmopolitanism','internationalism-filled,abundant','C2'],
      ['cosmopolitanismful','adj','Full of cosmopolitanism','internationalism-rich,abounding','C1'],
      ['cosmopolitanismless','adj','Without cosmopolitanism','lacking,without','C1'],
      ['cosmopolitanismism','n','The ideology of cosmopolitanism','internationalism ideology,doctrine','C2'],
      ['cosmopolitanismist','n','A person focused on cosmopolitanism','internationalism specialist,advocate','C2'],
      ['cosmopolitanismise','v','To make into cosmopolitanism','internationalism,convert','C2'],
      ['cosmopolitanismize','v','To make or become cosmopolitanism','internationalism,transform','C2'],
      ['anticosmopolitanism','adj','Opposed to cosmopolitanism','against,opposing','C2'],
      ['noncosmopolitanism','adj','Not involving cosmopolitanism','without,lacking','C1'],
      ['precosmopolitanism','n','Before cosmopolitanism','preceding,prior','C2'],
      ['postcosmopolitanism','n','After cosmopolitanism','following,subsequent','C2'],
      ['subcosmopolitanism','n','A subdivision of cosmopolitanism','subset,branch','C2'],
      ['multicosmopolitanism','adj','Involving many cosmopolitanisms','multiple,several','C2'],
      ['intercosmopolitanism','adj','Between cosmopolitanisms','cross,between','C2'],
      ['remittanceic','adj','Of or relating to remittance','transfer-based,characteristic','B2'],
      ['remittanceous','adj','Full of remittance','transfer-filled,abundant','C1'],
      ['remittanceful','adj','Full of remittance','transfer-rich,abounding','B2'],
      ['remittanceless','adj','Without remittance','lacking,without','B2'],
      ['remittanceism','n','The ideology of remittance','transfer ideology,doctrine','C1'],
      ['remittanceist','n','A person focused on remittance','transfer specialist,advocate','C1'],
      ['remittanceise','v','To make into remittance','transfer,convert','C1'],
      ['remittanceize','v','To make or become remittance','transfer,transform','C1'],
      ['antiremittance','adj','Opposed to remittance','against,opposing','C1'],
      ['nonremittance','adj','Not involving remittance','without,lacking','B2'],
      ['preremittance','n','Before remittance','preceding,prior','C1'],
      ['postremittance','n','After remittance','following,subsequent','C1'],
      ['subremittance','n','A subdivision of remittance','subset,branch','C1'],
      ['multiremittance','adj','Involving many remittances','multiple,several','C1'],
      ['interremittance','adj','Between remittances','cross,between','C1'],
      ['neoliberality','n','The state of being neoliberal','free-market condition','C2'],
      ['inneoliberal','adj','Not neoliberal','not free-market','C2'],
      ['nonneoliberal','adj','Not neoliberal','not free-market','C1'],
      ['semineoliberal','adj','Partially neoliberal','partly free-market','C2'],
      ['overneoliberal','adj','Excessively neoliberal','too free-market','C2'],
      ['ultraneoliberal','adj','Extremely neoliberal','very free-market','C2'],
      ['transnationality','n','The state of being transnational','cross-border condition','C1'],
      ['intransnational','adj','Not transnational','not cross-border','C1'],
      ['nontransnational','adj','Not transnational','not cross-border','B2'],
      ['semitransnational','adj','Partially transnational','partly cross-border','C1'],
      ['overtransnational','adj','Excessively transnational','too cross-border','C1'],
      ['ultratransnational','adj','Extremely transnational','very cross-border','C1'],
      ['protectionist','adj','Shielding domestic industry from competition','trade-restricting,import-blocking','B2'],
      ['protectionistly','adv','In a protectionist manner','trade-restricting way','B2'],
      ['protectionistness','n','The quality of being protectionist','trade-restricting quality','B2'],
      ['protectionistity','n','The state of being protectionist','trade-restricting condition','C1'],
      ['unprotectionist','adj','Not protectionist','not trade-restricting','B2'],
      ['inprotectionist','adj','Not protectionist','not trade-restricting','C1'],
      ['nonprotectionist','adj','Not protectionist','not trade-restricting','B2'],
      ['semiprotectionist','adj','Partially protectionist','partly trade-restricting','C1'],
    ],
  },
  collocations: {}
};
