module.exports = {
  vocab: {
    housing: [
    ['building','n','The process of building something','construct activity','A2'],
    ['gardenal','adj','Relating to garden','yard-related','A2'],
    ['tenantal','adj','Relating to tenant','renter-related','B1'],
    ['landlordal','adj','Relating to landlord','property owner-related','B1'],
    ['renovational','adj','Relating to renovation','restoration-related','B1'],
    ['suburbal','adj','Relating to suburb','outskirts-related','B1'],
    ['affordablely','adv','In a affordable manner','economical way','B1'],
    ['affordableness','n','The quality of being affordable','economical quality','B2'],
    ['unaffordable','adj','Not affordable','not economical','B1'],
    ['zoningal','adj','Relating to zoning','land use planning-related','B2'],
    ['sustainablely','adv','In a sustainable manner','eco-friendly way','B2'],
    ['sustainableness','n','The quality of being sustainable','eco-friendly quality','C1'],
    ['unsustainable','adj','Not sustainable','not eco-friendly','B2'],
    ['prefabricatedly','adv','In a prefabricated manner','pre-built way','B2'],
    ['prefabricatedness','n','The quality of being prefabricated','pre-built quality','C1'],
    ['unprefabricated','adj','Not prefabricated','not pre-built','B2'],
    ['brownfieldal','adj','Relating to brownfield','redevelopment site-related','C1'],
    ['cohousingal','adj','Relating to cohousing','communal living-related','C1'],
    ['geodesicly','adv','In a geodesic manner','dome way','C2'],
    ['geodesicness','n','The quality of being geodesic','dome quality','C2'],
    ['ungeodesic','adj','Not geodesic','not dome','C2'],
    ['roofal','adj','Relating to roof','rooftop-related','A2'],
    ['stairsal','adj','Relating to stairs','staircase-related','A2'],
    ['balconyal','adj','Relating to balcony','terrace-related','A2'],
    ['cellaral','adj','Relating to cellar','basement-related','B1'],
    ['attical','adj','Relating to attic','loft-related','B1'],
    ['detachedly','adv','In a detached manner','standalone way','B1'],
    ['detachedness','n','The quality of being detached','standalone quality','B2'],
    ['undetached','adj','Not detached','not standalone','B1'],
    ['semi-detachedly','adv','In a semi-detached manner','semi way','B1'],
    ['semi-detachedness','n','The quality of being semi-detached','semi quality','B2'],
    ['unsemi-detached','adj','Not semi-detached','not semi','B1'],
    ['insulational','adj','Relating to insulation','thermal barrier-related','B2'],
    ['retrofittingal','adj','Relating to retrofitting','upgrading-related','B2'],
    ['leaseholdal','adj','Relating to leasehold','term ownership-related','C1'],
    ['freeholdal','adj','Relating to freehold','full ownership-related','C1'],
    ['gazumpingal','adj','Relating to gazumping','outbidding-related','C2'],
    ['conveyancingal','adj','Relating to conveyancing','property law-related','C1'],
    ['claddingal','adj','Relating to cladding','facing-related','B2'],
    ['dormeral','adj','Relating to dormer','roof window-related','C1'],
    ['terracedly','adv','In a terraced manner','row house way','B1'],
    ['terracedness','n','The quality of being terraced','row house quality','B2'],
    ['unterraced','adj','Not terraced','not row house','B1'],
    ['maisonetteal','adj','Relating to maisonette','duplex-related','C1']
    ],
    transport: [
    ['hyperloop','n','A high-speed transport system in tubes','vacuum train,tube transport','C1'],
    ['maglev','n','A train levitated by magnetic force','magnetic levitation,floating train','C1'],
    ['induced demand','n','New roads generating more traffic','traffic generation,road paradox','C2'],
    ['depot','n','A storage facility for vehicles','station,terminal,warehouse','B2'],
    ['tailgating','n','Driving too closely behind another vehicle','following closely,rear-approaching','B2'],
    ['haulage','n','The commercial transport of goods','trucking,shipping,freight transport','C1'],
    ['contra-flow','n','A temporary reversal of traffic direction','reversed traffic,opposite lane use','C1'],
    ['pneumatic','adj','Operated by compressed air','air-powered,pressurised','C1'],
    ['funicular','n','A cable railway on a steep slope','cable car,incline railway','C1'],
    ['caral','adj','Relating to car','automobile-related','A2'],
    ['busal','adj','Relating to bus','coach-related','A2'],
    ['trainal','adj','Relating to train','railway-related','A2'],
    ['bicycleal','adj','Relating to bicycle','bike-related','A2'],
    ['drivation','n','The act or process of driving','steer process,pilot process,navigate process','A2'],
    ['drivable','adj','Able to be drived','steer,possible','B1'],
    ['driving','n','The process of driving something','steer activity','A2'],
    ['walkation','n','The act or process of walking','stroll process,hike process,march process','A2'],
    ['walker','n','A person who walks','stroll person,hike person,march person','B1'],
    ['walkable','adj','Able to be walkd','stroll,possible','B1'],
    ['walking','n','The process of walking something','stroll activity','A2'],
    ['flyation','n','The act or process of flying','jet process,soar process,take a flight process','A2'],
    ['flyer','n','A person who flys','jet person,soar person,take a flight person','B1'],
    ['flyable','adj','Able to be flyd','jet,possible','B1'],
    ['flying','n','The process of flying something','jet activity','A2'],
    ['traffical','adj','Relating to traffic','congestion-related','B1'],
    ['commutation','n','The act or process of commuting','travel process,shuttle process,journey process','B1'],
    ['commutable','adj','Able to be commuted','travel,possible','B2'],
    ['fareal','adj','Relating to fare','ticket price-related','B1'],
    ['routeal','adj','Relating to route','path-related','B1'],
    ['congestional','adj','Relating to congestion','traffic jam-related','B1'],
    ['emissional','adj','Relating to emission','exhaust-related','B1'],
    ['autonomously','adv','In a autonomous manner','self-driving way','B2'],
    ['autonomousness','n','The quality of being autonomous','self-driving quality','C1'],
    ['unautonomous','adj','Not autonomous','not self-driving','B2'],
    ['logisticsal','adj','Relating to logistics','supply chain-related','B2'],
    ['intermodally','adv','In a intermodal manner','cross-mode way','B2'],
    ['intermodalness','n','The quality of being intermodal','cross-mode quality','C1'],
    ['unintermodal','adj','Not intermodal','not cross-mode','B2'],
    ['hyperloopal','adj','Relating to hyperloop','vacuum train-related','C1'],
    ['magleval','adj','Relating to maglev','magnetic levitation-related','C1'],
    ['motorwayal','adj','Relating to motorway','highway-related','A2'],
    ['roundaboutal','adj','Relating to roundabout','rotary-related','B1'],
    ['pedestrianal','adj','Relating to pedestrian','walker-related','A2'],
    ['tramal','adj','Relating to tram','streetcar-related','B1'],
    ['ferryal','adj','Relating to ferry','boat-related','A2'],
    ['freightal','adj','Relating to freight','cargo-related','B2'],
    ['depotal','adj','Relating to depot','station-related','B2'],
    ['turbulenceal','adj','Relating to turbulence','bumps-related','B2'],
    ['gridlockal','adj','Relating to gridlock','deadlock-related','B2'],
    ['carpoolation','n','The act or process of carpooling','ride-share process,share a lift process,commute together process','B1'],
    ['carpooler','n','A person who carpools','ride-share person,share a lift person,commute together person','B2'],
    ['carpoolable','adj','Able to be carpoold','ride-share,possible','B2'],
    ['carpooling','n','The process of carpooling something','ride-share activity','B1'],
    ['tailgatingal','adj','Relating to tailgating','following closely-related','B2'],
    ['flyoveral','adj','Relating to flyover','overpass-related','B2'],
    ['bypassal','adj','Relating to bypass','ring road-related','B1'],
    ['haulageal','adj','Relating to haulage','trucking-related','C1'],
    ['axleal','adj','Relating to axle','shaft-related','B2'],
    ['interchangeal','adj','Relating to interchange','junction-related','B2'],
    ['pneumaticly','adv','In a pneumatic manner','air-powered way','C1'],
    ['pneumaticness','n','The quality of being pneumatic','air-powered quality','C2'],
    ['unpneumatic','adj','Not pneumatic','not air-powered','C1'],
    ['funicularal','adj','Relating to funicular','cable car-related','C1']
    ],
    employment: [
    ['resignation','n','The act of leaving a job voluntarily','quitting,departure,withdrawal','B1'],
    ['workplace','n','A location where people perform their jobs','office,site,premises','B1'],
    ['telecommute','v','To work remotely using technology','remote work,work from home','B2'],
    ['upskill','v','To learn new skills for a better role','retrain,develop,advance','B2'],
    ['occupational hazard','n','A risk inherent in a particular job','workplace danger,job risk','B2'],
    ['presenteeism','n','Working while sick reducing productivity','unproductive attendance,sick working','C2'],
    ['moonlighting','n','Working a second job secretly','side job,dual employment','C1'],
    ['headhunter','n','A person who recruits senior staff','recruiter,talent scout,executive searcher','B2'],
    ['retrenchment','n','Reducing staff numbers to cut costs','downsizing,redundancy,cutbacks','C1'],
    ['golden parachute','n','A generous severance for top executives','exit bonus,executive payout','C2'],
    ['ergonomics','n','Designing workplaces for comfort and efficiency','workplace design,human factors','B2'],
    ['jobal','adj','Relating to job','work-related','A2'],
    ['salaryal','adj','Relating to salary','pay-related','A2'],
    ['bossal','adj','Relating to boss','manager-related','A2'],
    ['interviewal','adj','Relating to interview','assessment-related','A2'],
    ['applyation','n','The act or process of applying','submit process,request process,petition process','A2'],
    ['applyer','n','A person who applys','submit person,request person,petition person','B1'],
    ['applyable','adj','Able to be applyd','submit,possible','B1'],
    ['applying','n','The process of applying something','submit activity','A2'],
    ['retiration','n','The act or process of retiring','withdraw process,step down process,quit process','A2'],
    ['retirer','n','A person who retires','withdraw person,step down person,quit person','B1'],
    ['retirable','adj','Able to be retired','withdraw,possible','B1'],
    ['retiring','n','The process of retiring something','withdraw activity','A2'],
    ['careeral','adj','Relating to career','vocation-related','B1'],
    ['promotional','adj','Relating to promotion','advancement-related','B1'],
    ['redundancyal','adj','Relating to redundancy','layoff-related','B1'],
    ['freelancely','adv','In a freelance manner','self-employed way','B1'],
    ['freelanceness','n','The quality of being freelance','self-employed quality','B2'],
    ['unfreelance','adj','Not freelance','not self-employed','B1'],
    ['apprenticeal','adj','Relating to apprentice','trainee-related','B1'],
    ['resignational','adj','Relating to resignation','quitting-related','B1'],
    ['workplaceal','adj','Relating to workplace','office-related','B1'],
    ['telecommutation','n','The act or process of telecommuting','remote work process,work from home process','B2'],
    ['telecommuter','n','A person who telecommutes','remote work person,work from home person','C1'],
    ['telecommutable','adj','Able to be telecommuted','remote work,possible','C1']
    ],
  },
  collocations: {
  }
};
