// Auto-generated vocab boost group 49
module.exports = {
  vocab: {
    economy: [
      ['subinflation','n','A subdivision of inflation','subset,branch','C1'],
      ['multiinflation','adj','Involving many inflations','multiple,several','C1'],
      ['interinflation','adj','Between inflations','cross,between','C1'],
      ['deflational','adj','Relating to deflation','price fall-related,pertaining to','C1'],
      ['deflationic','adj','Of or relating to deflation','price fall-based,characteristic','C1'],
      ['deflationous','adj','Full of deflation','price fall-filled,abundant','C2'],
      ['deflationful','adj','Full of deflation','price fall-rich,abounding','C1'],
      ['deflationless','adj','Without deflation','lacking,without','C1'],
      ['deflationism','n','The ideology of deflation','price fall ideology,doctrine','C2'],
      ['deflationist','n','A person focused on deflation','price fall specialist,advocate','C2'],
      ['deflationise','v','To make into deflation','price fall,convert','C2'],
      ['deflationize','v','To make or become deflation','price fall,transform','C2'],
      ['antideflation','adj','Opposed to deflation','against,opposing','C2'],
      ['nondeflation','adj','Not involving deflation','without,lacking','C1'],
      ['predeflation','n','Before deflation','preceding,prior','C2'],
      ['postdeflation','n','After deflation','following,subsequent','C2'],
      ['subdeflation','n','A subdivision of deflation','subset,branch','C2'],
      ['multideflation','adj','Involving many deflations','multiple,several','C2'],
      ['interdeflation','adj','Between deflations','cross,between','C2'],
      ['austerityic','adj','Of or relating to austerity','cutbacks-based,characteristic','B2'],
      ['austerityous','adj','Full of austerity','cutbacks-filled,abundant','C1'],
      ['austerityful','adj','Full of austerity','cutbacks-rich,abounding','B2'],
      ['austerityless','adj','Without austerity','lacking,without','B2'],
      ['austerityism','n','The ideology of austerity','cutbacks ideology,doctrine','C1'],
      ['austerityist','n','A person focused on austerity','cutbacks specialist,advocate','C1'],
      ['austerityise','v','To make into austerity','cutbacks,convert','C1'],
      ['austerityize','v','To make or become austerity','cutbacks,transform','C1'],
      ['antiausterity','adj','Opposed to austerity','against,opposing','C1'],
      ['nonausterity','adj','Not involving austerity','without,lacking','B2'],
      ['preausterity','n','Before austerity','preceding,prior','C1'],
      ['postausterity','n','After austerity','following,subsequent','C1'],
      ['subausterity','n','A subdivision of austerity','subset,branch','C1'],
      ['multiausterity','adj','Involving many austeritys','multiple,several','C1'],
      ['interausterity','adj','Between austeritys','cross,between','C1'],
      ['tariffic','adj','Of or relating to tariff','duty-based,characteristic','B2'],
      ['tariffous','adj','Full of tariff','duty-filled,abundant','C1'],
      ['tariffful','adj','Full of tariff','duty-rich,abounding','B2'],
      ['tariffless','adj','Without tariff','lacking,without','B2'],
      ['tariffism','n','The ideology of tariff','duty ideology,doctrine','C1'],
      ['tariffist','n','A person focused on tariff','duty specialist,advocate','C1'],
      ['tariffise','v','To make into tariff','duty,convert','C1'],
      ['tariffize','v','To make or become tariff','duty,transform','C1'],
      ['antitariff','adj','Opposed to tariff','against,opposing','C1'],
      ['nontariff','adj','Not involving tariff','without,lacking','B2'],
      ['pretariff','n','Before tariff','preceding,prior','C1'],
      ['posttariff','n','After tariff','following,subsequent','C1'],
      ['subtariff','n','A subdivision of tariff','subset,branch','C1'],
      ['multitariff','adj','Involving many tariffs','multiple,several','C1'],
      ['intertariff','adj','Between tariffs','cross,between','C1'],
      ['subsidyic','adj','Of or relating to subsidy','grant-based,characteristic','B2'],
      ['subsidyous','adj','Full of subsidy','grant-filled,abundant','C1'],
      ['subsidyful','adj','Full of subsidy','grant-rich,abounding','B2'],
      ['subsidyless','adj','Without subsidy','lacking,without','B2'],
      ['subsidyism','n','The ideology of subsidy','grant ideology,doctrine','C1'],
      ['subsidyist','n','A person focused on subsidy','grant specialist,advocate','C1'],
      ['subsidyise','v','To make into subsidy','grant,convert','C1'],
      ['subsidyize','v','To make or become subsidy','grant,transform','C1'],
      ['antisubsidy','adj','Opposed to subsidy','against,opposing','C1'],
      ['nonsubsidy','adj','Not involving subsidy','without,lacking','B2'],
      ['presubsidy','n','Before subsidy','preceding,prior','C1'],
      ['postsubsidy','n','After subsidy','following,subsequent','C1'],
      ['subsubsidy','n','A subdivision of subsidy','subset,branch','C1'],
      ['multisubsidy','adj','Involving many subsidys','multiple,several','C1'],
      ['intersubsidy','adj','Between subsidys','cross,between','C1'],
      ['embargoic','adj','Of or relating to embargo','ban-based,characteristic','C1'],
      ['embargoous','adj','Full of embargo','ban-filled,abundant','C2'],
      ['embargoful','adj','Full of embargo','ban-rich,abounding','C1'],
      ['embargoless','adj','Without embargo','lacking,without','C1'],
      ['embargoism','n','The ideology of embargo','ban ideology,doctrine','C2'],
      ['embargoist','n','A person focused on embargo','ban specialist,advocate','C2'],
      ['embargoise','v','To make into embargo','ban,convert','C2'],
      ['embargoize','v','To make or become embargo','ban,transform','C2'],
      ['antiembargo','adj','Opposed to embargo','against,opposing','C2'],
      ['nonembargo','adj','Not involving embargo','without,lacking','C1'],
      ['preembargo','n','Before embargo','preceding,prior','C2'],
      ['postembargo','n','After embargo','following,subsequent','C2'],
      ['subembargo','n','A subdivision of embargo','subset,branch','C2'],
      ['multiembargo','adj','Involving many embargos','multiple,several','C2'],
      ['interembargo','adj','Between embargos','cross,between','C2'],
      ['surplusic','adj','Of or relating to surplus','excess-based,characteristic','B2'],
      ['surplusous','adj','Full of surplus','excess-filled,abundant','C1'],
      ['surplusful','adj','Full of surplus','excess-rich,abounding','B2'],
      ['surplusless','adj','Without surplus','lacking,without','B2'],
      ['surplusism','n','The ideology of surplus','excess ideology,doctrine','C1'],
      ['surplusist','n','A person focused on surplus','excess specialist,advocate','C1'],
      ['surplusise','v','To make into surplus','excess,convert','C1'],
      ['surplusize','v','To make or become surplus','excess,transform','C1'],
      ['antisurplus','adj','Opposed to surplus','against,opposing','C1'],
      ['nonsurplus','adj','Not involving surplus','without,lacking','B2'],
      ['presurplus','n','Before surplus','preceding,prior','C1'],
      ['postsurplus','n','After surplus','following,subsequent','C1'],
      ['subsurplus','n','A subdivision of surplus','subset,branch','C1'],
      ['multisurplus','adj','Involving many surpluss','multiple,several','C1'],
      ['intersurplus','adj','Between surpluss','cross,between','C1'],
      ['deficitic','adj','Of or relating to deficit','shortfall-based,characteristic','B2'],
      ['deficitous','adj','Full of deficit','shortfall-filled,abundant','C1'],
      ['deficitful','adj','Full of deficit','shortfall-rich,abounding','B2'],
      ['deficitless','adj','Without deficit','lacking,without','B2'],
      ['deficitism','n','The ideology of deficit','shortfall ideology,doctrine','C1'],
      ['deficitist','n','A person focused on deficit','shortfall specialist,advocate','C1'],
      ['deficitise','v','To make into deficit','shortfall,convert','C1'],
      ['deficitize','v','To make or become deficit','shortfall,transform','C1'],
      ['antideficit','adj','Opposed to deficit','against,opposing','C1'],
      ['nondeficit','adj','Not involving deficit','without,lacking','B2'],
      ['predeficit','n','Before deficit','preceding,prior','C1'],
      ['postdeficit','n','After deficit','following,subsequent','C1'],
      ['subdeficit','n','A subdivision of deficit','subset,branch','C1'],
      ['multideficit','adj','Involving many deficits','multiple,several','C1'],
      ['interdeficit','adj','Between deficits','cross,between','C1'],
      ['commodityic','adj','Of or relating to commodity','product-based,characteristic','B2'],
      ['commodityous','adj','Full of commodity','product-filled,abundant','C1'],
      ['commodityful','adj','Full of commodity','product-rich,abounding','B2'],
      ['commodityless','adj','Without commodity','lacking,without','B2'],
      ['commodityism','n','The ideology of commodity','product ideology,doctrine','C1'],
      ['commodityist','n','A person focused on commodity','product specialist,advocate','C1'],
      ['commodityise','v','To make into commodity','product,convert','C1'],
      ['commodityize','v','To make or become commodity','product,transform','C1'],
      ['anticommodity','adj','Opposed to commodity','against,opposing','C1'],
      ['noncommodity','adj','Not involving commodity','without,lacking','B2'],
      ['precommodity','n','Before commodity','preceding,prior','C1'],
      ['postcommodity','n','After commodity','following,subsequent','C1'],
      ['subcommodity','n','A subdivision of commodity','subset,branch','C1'],
      ['multicommodity','adj','Involving many commoditys','multiple,several','C1'],
      ['intercommodity','adj','Between commoditys','cross,between','C1'],
      ['liquidityic','adj','Of or relating to liquidity','cash flow-based,characteristic','C1'],
      ['liquidityous','adj','Full of liquidity','cash flow-filled,abundant','C2'],
      ['liquidityful','adj','Full of liquidity','cash flow-rich,abounding','C1'],
      ['liquidityless','adj','Without liquidity','lacking,without','C1'],
      ['liquidityism','n','The ideology of liquidity','cash flow ideology,doctrine','C2'],
      ['liquidityist','n','A person focused on liquidity','cash flow specialist,advocate','C2'],
      ['liquidityise','v','To make into liquidity','cash flow,convert','C2'],
      ['liquidityize','v','To make or become liquidity','cash flow,transform','C2'],
      ['antiliquidity','adj','Opposed to liquidity','against,opposing','C2'],
      ['nonliquidity','adj','Not involving liquidity','without,lacking','C1'],
      ['preliquidity','n','Before liquidity','preceding,prior','C2'],
      ['postliquidity','n','After liquidity','following,subsequent','C2'],
      ['subliquidity','n','A subdivision of liquidity','subset,branch','C2'],
      ['multiliquidity','adj','Involving many liquiditys','multiple,several','C2'],
      ['interliquidity','adj','Between liquiditys','cross,between','C2'],
      ['yieldal','adj','Relating to yield','return-related,pertaining to','B2'],
      ['yieldic','adj','Of or relating to yield','return-based,characteristic','B2'],
      ['yieldous','adj','Full of yield','return-filled,abundant','C1'],
      ['yieldful','adj','Full of yield','return-rich,abounding','B2'],
      ['yieldless','adj','Without yield','lacking,without','B2'],
      ['yieldism','n','The ideology of yield','return ideology,doctrine','C1'],
      ['yieldist','n','A person focused on yield','return specialist,advocate','C1'],
      ['yieldise','v','To make into yield','return,convert','C1'],
      ['yieldize','v','To make or become yield','return,transform','C1'],
      ['antiyield','adj','Opposed to yield','against,opposing','C1'],
      ['nonyield','adj','Not involving yield','without,lacking','B2'],
      ['preyield','n','Before yield','preceding,prior','C1'],
      ['postyield','n','After yield','following,subsequent','C1'],
      ['subyield','n','A subdivision of yield','subset,branch','C1'],
      ['multiyield','adj','Involving many yields','multiple,several','C1'],
      ['interyield','adj','Between yields','cross,between','C1'],
      ['stagflationic','adj','Of or relating to stagflation','economic malaise-based,characteristic','C1'],
      ['stagflationous','adj','Full of stagflation','economic malaise-filled,abundant','C2'],
      ['stagflationful','adj','Full of stagflation','economic malaise-rich,abounding','C1'],
      ['stagflationless','adj','Without stagflation','lacking,without','C1'],
      ['stagflationism','n','The ideology of stagflation','economic malaise ideology,doctrine','C2'],
      ['stagflationist','n','A person focused on stagflation','economic malaise specialist,advocate','C2'],
      ['stagflationise','v','To make into stagflation','economic malaise,convert','C2'],
      ['stagflationize','v','To make or become stagflation','economic malaise,transform','C2'],
      ['antistagflation','adj','Opposed to stagflation','against,opposing','C2'],
      ['nonstagflation','adj','Not involving stagflation','without,lacking','C1'],
      ['prestagflation','n','Before stagflation','preceding,prior','C2'],
      ['poststagflation','n','After stagflation','following,subsequent','C2'],
      ['substagflation','n','A subdivision of stagflation','subset,branch','C2'],
      ['multistagflation','adj','Involving many stagflations','multiple,several','C2'],
      ['interstagflation','adj','Between stagflations','cross,between','C2'],
      ['oligopolyic','adj','Of or relating to oligopoly','limited competition-based,characteristic','C1'],
      ['oligopolyous','adj','Full of oligopoly','limited competition-filled,abundant','C2'],
      ['oligopolyful','adj','Full of oligopoly','limited competition-rich,abounding','C1'],
      ['oligopolyless','adj','Without oligopoly','lacking,without','C1'],
      ['oligopolyism','n','The ideology of oligopoly','limited competition ideology,doctrine','C2'],
      ['oligopolyist','n','A person focused on oligopoly','limited competition specialist,advocate','C2'],
      ['oligopolyise','v','To make into oligopoly','limited competition,convert','C2'],
      ['oligopolyize','v','To make or become oligopoly','limited competition,transform','C2'],
      ['antioligopoly','adj','Opposed to oligopoly','against,opposing','C2'],
      ['nonoligopoly','adj','Not involving oligopoly','without,lacking','C1'],
      ['preoligopoly','n','Before oligopoly','preceding,prior','C2'],
      ['postoligopoly','n','After oligopoly','following,subsequent','C2'],
      ['suboligopoly','n','A subdivision of oligopoly','subset,branch','C2'],
      ['multioligopoly','adj','Involving many oligopolys','multiple,several','C2'],
      ['interoligopoly','adj','Between oligopolys','cross,between','C2'],
      ['quantitative easingal','adj','Relating to quantitative easing','monetary expansion-related,pertaining to','C1'],
      ['quantitative easingic','adj','Of or relating to quantitative easing','monetary expansion-based,characteristic','C1'],
      ['quantitative easingous','adj','Full of quantitative easing','monetary expansion-filled,abundant','C2'],
      ['quantitative easingful','adj','Full of quantitative easing','monetary expansion-rich,abounding','C1'],
      ['quantitative easingless','adj','Without quantitative easing','lacking,without','C1'],
      ['quantitative easingism','n','The ideology of quantitative easing','monetary expansion ideology,doctrine','C2'],
      ['quantitative easingist','n','A person focused on quantitative easing','monetary expansion specialist,advocate','C2'],
      ['quantitative easingise','v','To make into quantitative easing','monetary expansion,convert','C2'],
      ['quantitative easingize','v','To make or become quantitative easing','monetary expansion,transform','C2'],
      ['antiquantitative easing','adj','Opposed to quantitative easing','against,opposing','C2'],
      ['nonquantitative easing','adj','Not involving quantitative easing','without,lacking','C1'],
      ['prequantitative easing','n','Before quantitative easing','preceding,prior','C2'],
      ['postquantitative easing','n','After quantitative easing','following,subsequent','C2'],
      ['subquantitative easing','n','A subdivision of quantitative easing','subset,branch','C2'],
      ['multiquantitative easing','adj','Involving many quantitative easings','multiple,several','C2'],
      ['interquantitative easing','adj','Between quantitative easings','cross,between','C2'],
      ['gross domestic product','n','Total value of goods produced nationally','GDP,national output,economic output','B2'],
      ['gross domestic productal','adj','Relating to gross domestic product','GDP-related,pertaining to','B2'],
      ['gross domestic productic','adj','Of or relating to gross domestic product','GDP-based,characteristic','B2'],
      ['gross domestic productous','adj','Full of gross domestic product','GDP-filled,abundant','C1'],
      ['gross domestic productful','adj','Full of gross domestic product','GDP-rich,abounding','B2'],
      ['gross domestic productless','adj','Without gross domestic product','lacking,without','B2'],
      ['gross domestic productism','n','The ideology of gross domestic product','GDP ideology,doctrine','C1'],
      ['gross domestic productist','n','A person focused on gross domestic product','GDP specialist,advocate','C1'],
      ['gross domestic productise','v','To make into gross domestic product','GDP,convert','C1'],
      ['gross domestic productize','v','To make or become gross domestic product','GDP,transform','C1'],
      ['antigross domestic product','adj','Opposed to gross domestic product','against,opposing','C1'],
      ['nongross domestic product','adj','Not involving gross domestic product','without,lacking','B2'],
      ['pregross domestic product','n','Before gross domestic product','preceding,prior','C1'],
      ['postgross domestic product','n','After gross domestic product','following,subsequent','C1'],
      ['subgross domestic product','n','A subdivision of gross domestic product','subset,branch','C1'],
      ['multigross domestic product','adj','Involving many gross domestic products','multiple,several','C1'],
      ['intergross domestic product','adj','Between gross domestic products','cross,between','C1'],
      ['purchasing poweral','adj','Relating to purchasing power','buying power-related,pertaining to','B2'],
      ['purchasing poweric','adj','Of or relating to purchasing power','buying power-based,characteristic','B2'],
      ['purchasing powerous','adj','Full of purchasing power','buying power-filled,abundant','C1'],
      ['purchasing powerful','adj','Full of purchasing power','buying power-rich,abounding','B2'],
      ['purchasing powerless','adj','Without purchasing power','lacking,without','B2'],
      ['purchasing powerism','n','The ideology of purchasing power','buying power ideology,doctrine','C1'],
      ['purchasing powerist','n','A person focused on purchasing power','buying power specialist,advocate','C1'],
      ['purchasing powerise','v','To make into purchasing power','buying power,convert','C1'],
      ['purchasing powerize','v','To make or become purchasing power','buying power,transform','C1'],
      ['antipurchasing power','adj','Opposed to purchasing power','against,opposing','C1'],
      ['nonpurchasing power','adj','Not involving purchasing power','without,lacking','B2'],
      ['prepurchasing power','n','Before purchasing power','preceding,prior','C1'],
      ['postpurchasing power','n','After purchasing power','following,subsequent','C1'],
      ['subpurchasing power','n','A subdivision of purchasing power','subset,branch','C1'],
      ['multipurchasing power','adj','Involving many purchasing powers','multiple,several','C1'],
      ['interpurchasing power','adj','Between purchasing powers','cross,between','C1'],
      ['trade deficit','n','When imports exceed exports','negative balance,import surplus','B2'],
      ['trade deficital','adj','Relating to trade deficit','negative balance-related,pertaining to','B2'],
      ['trade deficitic','adj','Of or relating to trade deficit','negative balance-based,characteristic','B2'],
      ['trade deficitous','adj','Full of trade deficit','negative balance-filled,abundant','C1'],
      ['trade deficitful','adj','Full of trade deficit','negative balance-rich,abounding','B2'],
      ['trade deficitless','adj','Without trade deficit','lacking,without','B2'],
      ['trade deficitism','n','The ideology of trade deficit','negative balance ideology,doctrine','C1'],
      ['trade deficitist','n','A person focused on trade deficit','negative balance specialist,advocate','C1'],
      ['trade deficitise','v','To make into trade deficit','negative balance,convert','C1'],
      ['trade deficitize','v','To make or become trade deficit','negative balance,transform','C1'],
      ['antitrade deficit','adj','Opposed to trade deficit','against,opposing','C1'],
      ['nontrade deficit','adj','Not involving trade deficit','without,lacking','B2'],
      ['pretrade deficit','n','Before trade deficit','preceding,prior','C1'],
      ['posttrade deficit','n','After trade deficit','following,subsequent','C1'],
      ['subtrade deficit','n','A subdivision of trade deficit','subset,branch','C1'],
      ['multitrade deficit','adj','Involving many trade deficits','multiple,several','C1'],
    ],
  },
  collocations: {}
};
