// Auto-generated vocab boost group 55
module.exports = {
  vocab: {
    science: [
      ['catalyse','v','To cause or accelerate a reaction','accelerate,trigger,spark','C1'],
      ['catalysation','n','The act of catalysing','accelerate process','C1'],
      ['catalysment','n','The result of catalysing','accelerate outcome','C1'],
      ['catalysance','n','The state of catalysing','accelerate state','C1'],
      ['catalysence','n','The quality of catalysing','accelerate quality','C1'],
      ['catalysal','n','An act of catalysing','accelerate event','C2'],
      ['catalyser','n','One who catalyses','accelerate person','C1'],
      ['catalysor','n','One who catalyses','accelerate agent','C1'],
      ['catalysee','n','One who is catalysed','accelerate recipient','C2'],
      ['catalysable','adj','Capable of being catalysed','accelerate,possible','C2'],
      ['catalysible','adj','Able to be catalysed','accelerate,feasible','C2'],
      ['catalysive','adj','Tending to catalyse','accelerate,active','C1'],
      ['catalysing','adj','Currently catalysing','accelerate,ongoing','C1'],
      ['catalysed','adj','Having been catalysed','accelerate,completed','C1'],
      ['recatalyse','v','To catalyse again','accelerate again,repeat','C1'],
      ['uncatalyse','v','To reverse catalysing','reverse,undo','C2'],
      ['overcatalyse','v','To catalyse excessively','excess,too much','C2'],
      ['undercatalyse','v','To catalyse insufficiently','insufficient,inadequate','C2'],
      ['miscatalyse','v','To catalyse incorrectly','wrongly,incorrectly','C2'],
      ['precatalyse','v','To catalyse beforehand','before,in advance','C2'],
      ['cocatalyse','v','To catalyse together','jointly,together','C2'],
      ['recatalysation','n','The act of catalysing again','re-accelerate','C2'],
      ['overcatalysation','n','Excessive catalysing','excess accelerate','C2'],
      ['distil','v','To purify a liquid by heating','purify,refine,extract','C1'],
      ['distilation','n','The act of distiling','purify process','C1'],
      ['distilment','n','The result of distiling','purify outcome','C1'],
      ['distilance','n','The state of distiling','purify state','C1'],
      ['distilence','n','The quality of distiling','purify quality','C1'],
      ['distilal','n','An act of distiling','purify event','C2'],
      ['distiler','n','One who distils','purify person','C1'],
      ['distilor','n','One who distils','purify agent','C1'],
      ['distilee','n','One who is distild','purify recipient','C2'],
      ['distilable','adj','Capable of being distild','purify,possible','C2'],
      ['distilible','adj','Able to be distild','purify,feasible','C2'],
      ['distilive','adj','Tending to distil','purify,active','C1'],
      ['distiling','adj','Currently distiling','purify,ongoing','C1'],
      ['distiled','adj','Having been distild','purify,completed','C1'],
      ['redistil','v','To distil again','purify again,repeat','C1'],
      ['undistil','v','To reverse distiling','reverse,undo','C2'],
      ['overdistil','v','To distil excessively','excess,too much','C2'],
      ['underdistil','v','To distil insufficiently','insufficient,inadequate','C2'],
      ['misdistil','v','To distil incorrectly','wrongly,incorrectly','C2'],
      ['predistil','v','To distil beforehand','before,in advance','C2'],
      ['codistil','v','To distil together','jointly,together','C2'],
      ['redistilation','n','The act of distiling again','re-purify','C2'],
      ['overdistilation','n','Excessive distiling','excess purify','C2'],
      ['dissect','v','To cut apart for examination','analyse,examine,investigate','B2'],
      ['dissectation','n','The act of dissecting','analyse process','B2'],
      ['dissectment','n','The result of dissecting','analyse outcome','B2'],
      ['dissectance','n','The state of dissecting','analyse state','B2'],
      ['dissectence','n','The quality of dissecting','analyse quality','B2'],
      ['dissectal','n','An act of dissecting','analyse event','C1'],
      ['dissecter','n','One who dissects','analyse person','B2'],
      ['dissector','n','One who dissects','analyse agent','B2'],
      ['dissectee','n','One who is dissectd','analyse recipient','C1'],
      ['dissectable','adj','Capable of being dissectd','analyse,possible','C1'],
      ['dissectible','adj','Able to be dissectd','analyse,feasible','C1'],
      ['dissective','adj','Tending to dissect','analyse,active','B2'],
      ['dissecting','adj','Currently dissecting','analyse,ongoing','B2'],
      ['dissected','adj','Having been dissectd','analyse,completed','B2'],
      ['redissect','v','To dissect again','analyse again,repeat','B2'],
      ['undissect','v','To reverse dissecting','reverse,undo','C1'],
      ['overdissect','v','To dissect excessively','excess,too much','C1'],
      ['underdissect','v','To dissect insufficiently','insufficient,inadequate','C1'],
      ['misdissect','v','To dissect incorrectly','wrongly,incorrectly','C1'],
      ['predissect','v','To dissect beforehand','before,in advance','C1'],
      ['codissect','v','To dissect together','jointly,together','C1'],
      ['redissectation','n','The act of dissecting again','re-analyse','C1'],
      ['overdissectation','n','Excessive dissecting','excess analyse','C1'],
      ['empiricality','n','The state of being empirical','experimental condition','C1'],
      ['inempirical','adj','Not empirical','not experimental','C1'],
      ['nonempirical','adj','Not empirical','not experimental','B2'],
      ['semiempirical','adj','Partially empirical','partly experimental','C1'],
      ['overempirical','adj','Excessively empirical','too experimental','C1'],
      ['ultraempirical','adj','Extremely empirical','very experimental','C1'],
      ['theoretically','adv','In a theoretical manner','abstract way','B2'],
      ['theoreticalness','n','The quality of being theoretical','abstract quality','B2'],
      ['theoreticality','n','The state of being theoretical','abstract condition','C1'],
      ['untheoretical','adj','Not theoretical','not abstract','B2'],
      ['intheoretical','adj','Not theoretical','not abstract','C1'],
      ['nontheoretical','adj','Not theoretical','not abstract','B2'],
      ['semitheoretical','adj','Partially theoretical','partly abstract','C1'],
      ['overtheoretical','adj','Excessively theoretical','too abstract','C1'],
      ['ultratheoretical','adj','Extremely theoretical','very abstract','C1'],
      ['molecular','adj','Relating to molecules','atomic,chemical,microscopic','B2'],
      ['molecularly','adv','In a molecular manner','atomic way','B2'],
      ['molecularness','n','The quality of being molecular','atomic quality','B2'],
      ['molecularity','n','The state of being molecular','atomic condition','C1'],
      ['unmolecular','adj','Not molecular','not atomic','B2'],
      ['inmolecular','adj','Not molecular','not atomic','C1'],
      ['nonmolecular','adj','Not molecular','not atomic','B2'],
      ['semimolecular','adj','Partially molecular','partly atomic','C1'],
      ['overmolecular','adj','Excessively molecular','too atomic','C1'],
      ['ultramolecular','adj','Extremely molecular','very atomic','C1'],
      ['quantitatively','adv','In a quantitative manner','numerical way','B2'],
      ['quantitativeness','n','The quality of being quantitative','numerical quality','B2'],
      ['quantitativeity','n','The state of being quantitative','numerical condition','C1'],
      ['unquantitative','adj','Not quantitative','not numerical','B2'],
      ['inquantitative','adj','Not quantitative','not numerical','C1'],
      ['nonquantitative','adj','Not quantitative','not numerical','B2'],
      ['semiquantitative','adj','Partially quantitative','partly numerical','C1'],
      ['overquantitative','adj','Excessively quantitative','too numerical','C1'],
      ['ultraquantitative','adj','Extremely quantitative','very numerical','C1'],
      ['qualitatively','adv','In a qualitative manner','descriptive way','B2'],
      ['qualitativeness','n','The quality of being qualitative','descriptive quality','B2'],
      ['qualitativeity','n','The state of being qualitative','descriptive condition','C1'],
      ['unqualitative','adj','Not qualitative','not descriptive','B2'],
      ['inqualitative','adj','Not qualitative','not descriptive','C1'],
      ['nonqualitative','adj','Not qualitative','not descriptive','B2'],
      ['semiqualitative','adj','Partially qualitative','partly descriptive','C1'],
      ['overqualitative','adj','Excessively qualitative','too descriptive','C1'],
      ['ultraqualitative','adj','Extremely qualitative','very descriptive','C1'],
      ['replicable','adj','Able to be reproduced','reproducible,repeatable,verifiable','C1'],
      ['replicablely','adv','In a replicable manner','reproducible way','C1'],
      ['replicableness','n','The quality of being replicable','reproducible quality','C1'],
      ['replicableity','n','The state of being replicable','reproducible condition','C2'],
      ['unreplicable','adj','Not replicable','not reproducible','C1'],
      ['inreplicable','adj','Not replicable','not reproducible','C2'],
      ['nonreplicable','adj','Not replicable','not reproducible','C1'],
      ['semireplicable','adj','Partially replicable','partly reproducible','C2'],
      ['overreplicable','adj','Excessively replicable','too reproducible','C2'],
      ['ultrareplicable','adj','Extremely replicable','very reproducible','C2'],
      ['anomalous','adj','Deviating from what is expected','abnormal,irregular,unusual','C1'],
      ['anomalously','adv','In a anomalous manner','abnormal way','C1'],
      ['anomalousness','n','The quality of being anomalous','abnormal quality','C1'],
      ['anomalousity','n','The state of being anomalous','abnormal condition','C2'],
      ['unanomalous','adj','Not anomalous','not abnormal','C1'],
      ['inanomalous','adj','Not anomalous','not abnormal','C2'],
      ['nonanomalous','adj','Not anomalous','not abnormal','C1'],
      ['semianomalous','adj','Partially anomalous','partly abnormal','C2'],
      ['overanomalous','adj','Excessively anomalous','too abnormal','C2'],
      ['ultraanomalous','adj','Extremely anomalous','very abnormal','C2'],
      ['hypothesisic','adj','Of or relating to hypothesis','theory-based,characteristic','B2'],
      ['hypothesisous','adj','Full of hypothesis','theory-filled,abundant','C1'],
      ['hypothesisful','adj','Full of hypothesis','theory-rich,abounding','B2'],
      ['hypothesisless','adj','Without hypothesis','lacking,without','B2'],
      ['hypothesisism','n','The ideology of hypothesis','theory ideology,doctrine','C1'],
      ['hypothesisist','n','A person focused on hypothesis','theory specialist,advocate','C1'],
      ['hypothesisise','v','To make into hypothesis','theory,convert','C1'],
      ['hypothesisize','v','To make or become hypothesis','theory,transform','C1'],
      ['antihypothesis','adj','Opposed to hypothesis','against,opposing','C1'],
      ['nonhypothesis','adj','Not involving hypothesis','without,lacking','B2'],
      ['prehypothesis','n','Before hypothesis','preceding,prior','C1'],
      ['posthypothesis','n','After hypothesis','following,subsequent','C1'],
      ['subhypothesis','n','A subdivision of hypothesis','subset,branch','C1'],
      ['multihypothesis','adj','Involving many hypothesiss','multiple,several','C1'],
      ['interhypothesis','adj','Between hypothesiss','cross,between','C1'],
      ['variableic','adj','Of or relating to variable','factor-based,characteristic','B2'],
      ['variableous','adj','Full of variable','factor-filled,abundant','C1'],
      ['variableful','adj','Full of variable','factor-rich,abounding','B2'],
      ['variableless','adj','Without variable','lacking,without','B2'],
      ['variableism','n','The ideology of variable','factor ideology,doctrine','C1'],
      ['variableist','n','A person focused on variable','factor specialist,advocate','C1'],
      ['variableise','v','To make into variable','factor,convert','C1'],
      ['variableize','v','To make or become variable','factor,transform','C1'],
      ['antivariable','adj','Opposed to variable','against,opposing','C1'],
      ['nonvariable','adj','Not involving variable','without,lacking','B2'],
      ['prevariable','n','Before variable','preceding,prior','C1'],
      ['postvariable','n','After variable','following,subsequent','C1'],
      ['subvariable','n','A subdivision of variable','subset,branch','C1'],
      ['multivariable','adj','Involving many variables','multiple,several','C1'],
      ['intervariable','adj','Between variables','cross,between','C1'],
      ['catalystic','adj','Of or relating to catalyst','accelerator-based,characteristic','B2'],
      ['catalystous','adj','Full of catalyst','accelerator-filled,abundant','C1'],
      ['catalystful','adj','Full of catalyst','accelerator-rich,abounding','B2'],
      ['catalystless','adj','Without catalyst','lacking,without','B2'],
      ['catalystism','n','The ideology of catalyst','accelerator ideology,doctrine','C1'],
      ['catalystist','n','A person focused on catalyst','accelerator specialist,advocate','C1'],
      ['catalystise','v','To make into catalyst','accelerator,convert','C1'],
      ['catalystize','v','To make or become catalyst','accelerator,transform','C1'],
      ['anticatalyst','adj','Opposed to catalyst','against,opposing','C1'],
      ['noncatalyst','adj','Not involving catalyst','without,lacking','B2'],
      ['precatalyst','n','Before catalyst','preceding,prior','C1'],
      ['postcatalyst','n','After catalyst','following,subsequent','C1'],
      ['subcatalyst','n','A subdivision of catalyst','subset,branch','C1'],
      ['multicatalyst','adj','Involving many catalysts','multiple,several','C1'],
      ['intercatalyst','adj','Between catalysts','cross,between','C1'],
      ['isotopeic','adj','Of or relating to isotope','atomic variant-based,characteristic','C1'],
      ['isotopeous','adj','Full of isotope','atomic variant-filled,abundant','C2'],
      ['isotopeful','adj','Full of isotope','atomic variant-rich,abounding','C1'],
      ['isotopeless','adj','Without isotope','lacking,without','C1'],
      ['isotopeism','n','The ideology of isotope','atomic variant ideology,doctrine','C2'],
      ['isotopeist','n','A person focused on isotope','atomic variant specialist,advocate','C2'],
      ['isotopeise','v','To make into isotope','atomic variant,convert','C2'],
      ['isotopeize','v','To make or become isotope','atomic variant,transform','C2'],
      ['antiisotope','adj','Opposed to isotope','against,opposing','C2'],
      ['nonisotope','adj','Not involving isotope','without,lacking','C1'],
      ['preisotope','n','Before isotope','preceding,prior','C2'],
      ['postisotope','n','After isotope','following,subsequent','C2'],
      ['subisotope','n','A subdivision of isotope','subset,branch','C2'],
      ['multiisotope','adj','Involving many isotopes','multiple,several','C2'],
      ['interisotope','adj','Between isotopes','cross,between','C2'],
      ['genomeic','adj','Of or relating to genome','DNA sequence-based,characteristic','B2'],
      ['genomeous','adj','Full of genome','DNA sequence-filled,abundant','C1'],
      ['genomeful','adj','Full of genome','DNA sequence-rich,abounding','B2'],
      ['genomeless','adj','Without genome','lacking,without','B2'],
      ['genomeism','n','The ideology of genome','DNA sequence ideology,doctrine','C1'],
      ['genomeist','n','A person focused on genome','DNA sequence specialist,advocate','C1'],
      ['genomeise','v','To make into genome','DNA sequence,convert','C1'],
      ['genomeize','v','To make or become genome','DNA sequence,transform','C1'],
      ['antigenome','adj','Opposed to genome','against,opposing','C1'],
      ['nongenome','adj','Not involving genome','without,lacking','B2'],
      ['pregenome','n','Before genome','preceding,prior','C1'],
      ['postgenome','n','After genome','following,subsequent','C1'],
      ['subgenome','n','A subdivision of genome','subset,branch','C1'],
      ['multigenome','adj','Involving many genomes','multiple,several','C1'],
      ['intergenome','adj','Between genomes','cross,between','C1'],
      ['photosynthesisic','adj','Of or relating to photosynthesis','light conversion-based,characteristic','B2'],
      ['photosynthesisous','adj','Full of photosynthesis','light conversion-filled,abundant','C1'],
      ['photosynthesisful','adj','Full of photosynthesis','light conversion-rich,abounding','B2'],
      ['photosynthesisless','adj','Without photosynthesis','lacking,without','B2'],
      ['photosynthesisism','n','The ideology of photosynthesis','light conversion ideology,doctrine','C1'],
      ['photosynthesisist','n','A person focused on photosynthesis','light conversion specialist,advocate','C1'],
      ['photosynthesisise','v','To make into photosynthesis','light conversion,convert','C1'],
      ['photosynthesisize','v','To make or become photosynthesis','light conversion,transform','C1'],
      ['antiphotosynthesis','adj','Opposed to photosynthesis','against,opposing','C1'],
      ['nonphotosynthesis','adj','Not involving photosynthesis','without,lacking','B2'],
      ['prephotosynthesis','n','Before photosynthesis','preceding,prior','C1'],
      ['postphotosynthesis','n','After photosynthesis','following,subsequent','C1'],
      ['subphotosynthesis','n','A subdivision of photosynthesis','subset,branch','C1'],
      ['multiphotosynthesis','adj','Involving many photosynthesiss','multiple,several','C1'],
      ['interphotosynthesis','adj','Between photosynthesiss','cross,between','C1'],
      ['osmosisal','adj','Relating to osmosis','diffusion-related,pertaining to','C1'],
      ['osmosisic','adj','Of or relating to osmosis','diffusion-based,characteristic','C1'],
      ['osmosisous','adj','Full of osmosis','diffusion-filled,abundant','C2'],
      ['osmosisful','adj','Full of osmosis','diffusion-rich,abounding','C1'],
      ['osmosisless','adj','Without osmosis','lacking,without','C1'],
      ['osmosisism','n','The ideology of osmosis','diffusion ideology,doctrine','C2'],
      ['osmosisist','n','A person focused on osmosis','diffusion specialist,advocate','C2'],
      ['osmosisise','v','To make into osmosis','diffusion,convert','C2'],
      ['osmosisize','v','To make or become osmosis','diffusion,transform','C2'],
      ['antiosmosis','adj','Opposed to osmosis','against,opposing','C2'],
      ['nonosmosis','adj','Not involving osmosis','without,lacking','C1'],
      ['preosmosis','n','Before osmosis','preceding,prior','C2'],
      ['postosmosis','n','After osmosis','following,subsequent','C2'],
      ['subosmosis','n','A subdivision of osmosis','subset,branch','C2'],
      ['multiosmosis','adj','Involving many osmosiss','multiple,several','C2'],
      ['interosmosis','adj','Between osmosiss','cross,between','C2'],
      ['entropyic','adj','Of or relating to entropy','disorder-based,characteristic','C1'],
      ['entropyous','adj','Full of entropy','disorder-filled,abundant','C2'],
      ['entropyful','adj','Full of entropy','disorder-rich,abounding','C1'],
      ['entropyless','adj','Without entropy','lacking,without','C1'],
      ['entropyism','n','The ideology of entropy','disorder ideology,doctrine','C2'],
      ['entropyist','n','A person focused on entropy','disorder specialist,advocate','C2'],
      ['entropyise','v','To make into entropy','disorder,convert','C2'],
      ['entropyize','v','To make or become entropy','disorder,transform','C2'],
      ['antientropy','adj','Opposed to entropy','against,opposing','C2'],
      ['nonentropy','adj','Not involving entropy','without,lacking','C1'],
      ['preentropy','n','Before entropy','preceding,prior','C2'],
      ['postentropy','n','After entropy','following,subsequent','C2'],
    ],
  },
  collocations: {}
};
