// Auto-generated vocab boost group 50
module.exports = {
  vocab: {
    economy: [
      ['intertrade deficit','adj','Between trade deficits','cross,between','C1'],
      ['supply and demand','n','Economic model of price determination','market forces,price mechanism','B2'],
      ['supply and demandal','adj','Relating to supply and demand','market forces-related,pertaining to','B2'],
      ['supply and demandic','adj','Of or relating to supply and demand','market forces-based,characteristic','B2'],
      ['supply and demandous','adj','Full of supply and demand','market forces-filled,abundant','C1'],
      ['supply and demandful','adj','Full of supply and demand','market forces-rich,abounding','B2'],
      ['supply and demandless','adj','Without supply and demand','lacking,without','B2'],
      ['supply and demandism','n','The ideology of supply and demand','market forces ideology,doctrine','C1'],
      ['supply and demandist','n','A person focused on supply and demand','market forces specialist,advocate','C1'],
      ['supply and demandise','v','To make into supply and demand','market forces,convert','C1'],
      ['supply and demandize','v','To make or become supply and demand','market forces,transform','C1'],
      ['antisupply and demand','adj','Opposed to supply and demand','against,opposing','C1'],
      ['nonsupply and demand','adj','Not involving supply and demand','without,lacking','B2'],
      ['presupply and demand','n','Before supply and demand','preceding,prior','C1'],
      ['postsupply and demand','n','After supply and demand','following,subsequent','C1'],
      ['subsupply and demand','n','A subdivision of supply and demand','subset,branch','C1'],
      ['multisupply and demand','adj','Involving many supply and demands','multiple,several','C1'],
      ['intersupply and demand','adj','Between supply and demands','cross,between','C1'],
    ],
    society: [
      ['marginalize','v','To treat as insignificant','exclude,sideline,ostracize','B2'],
      ['marginalization','n','The act of marginalizing','exclude process','B2'],
      ['marginalizment','n','The result of marginalizing','exclude outcome','B2'],
      ['marginalizance','n','The state of marginalizing','exclude state','B2'],
      ['marginalizence','n','The quality of marginalizing','exclude quality','B2'],
      ['marginalizal','n','An act of marginalizing','exclude event','C1'],
      ['marginalizer','n','One who marginalizes','exclude person','B2'],
      ['marginalizor','n','One who marginalizes','exclude agent','B2'],
      ['marginalizee','n','One who is marginalized','exclude recipient','C1'],
      ['marginalizable','adj','Capable of being marginalized','exclude,possible','C1'],
      ['marginalizible','adj','Able to be marginalized','exclude,feasible','C1'],
      ['marginalizive','adj','Tending to marginalize','exclude,active','B2'],
      ['marginalizing','adj','Currently marginalizing','exclude,ongoing','B2'],
      ['marginalized','adj','Having been marginalized','exclude,completed','B2'],
      ['remarginalize','v','To marginalize again','exclude again,repeat','B2'],
      ['unmarginalize','v','To reverse marginalizing','reverse,undo','C1'],
      ['overmarginalize','v','To marginalize excessively','excess,too much','C1'],
      ['undermarginalize','v','To marginalize insufficiently','insufficient,inadequate','C1'],
      ['mismarginalize','v','To marginalize incorrectly','wrongly,incorrectly','C1'],
      ['premarginalize','v','To marginalize beforehand','before,in advance','C1'],
      ['comarginalize','v','To marginalize together','jointly,together','C1'],
      ['remarginalization','n','The act of marginalizing again','re-exclude','C1'],
      ['overmarginalization','n','Excessive marginalizing','excess exclude','C1'],
      ['emancipatation','n','The act of emancipating','liberate process','C1'],
      ['emancipatment','n','The result of emancipating','liberate outcome','C1'],
      ['emancipatance','n','The state of emancipating','liberate state','C1'],
      ['emancipatence','n','The quality of emancipating','liberate quality','C1'],
      ['emancipatal','n','An act of emancipating','liberate event','C2'],
      ['emancipater','n','One who emancipates','liberate person','C1'],
      ['emancipator','n','One who emancipates','liberate agent','C1'],
      ['emancipatee','n','One who is emancipated','liberate recipient','C2'],
      ['emancipatable','adj','Capable of being emancipated','liberate,possible','C2'],
      ['emancipatible','adj','Able to be emancipated','liberate,feasible','C2'],
      ['emancipative','adj','Tending to emancipate','liberate,active','C1'],
      ['emancipating','adj','Currently emancipating','liberate,ongoing','C1'],
      ['emancipated','adj','Having been emancipated','liberate,completed','C1'],
      ['reemancipate','v','To emancipate again','liberate again,repeat','C1'],
      ['unemancipate','v','To reverse emancipating','reverse,undo','C2'],
      ['overemancipate','v','To emancipate excessively','excess,too much','C2'],
      ['underemancipate','v','To emancipate insufficiently','insufficient,inadequate','C2'],
      ['misemancipate','v','To emancipate incorrectly','wrongly,incorrectly','C2'],
      ['preemancipate','v','To emancipate beforehand','before,in advance','C2'],
      ['coemancipate','v','To emancipate together','jointly,together','C2'],
      ['reemancipatation','n','The act of emancipating again','re-liberate','C2'],
      ['overemancipatation','n','Excessive emancipating','excess liberate','C2'],
      ['segregate','v','To set apart from others','separate,isolate,divide','B2'],
      ['segregatation','n','The act of segregating','separate process','B2'],
      ['segregatment','n','The result of segregating','separate outcome','B2'],
      ['segregatance','n','The state of segregating','separate state','B2'],
      ['segregatence','n','The quality of segregating','separate quality','B2'],
      ['segregatal','n','An act of segregating','separate event','C1'],
      ['segregater','n','One who segregates','separate person','B2'],
      ['segregator','n','One who segregates','separate agent','B2'],
      ['segregatee','n','One who is segregated','separate recipient','C1'],
      ['segregatable','adj','Capable of being segregated','separate,possible','C1'],
      ['segregatible','adj','Able to be segregated','separate,feasible','C1'],
      ['segregative','adj','Tending to segregate','separate,active','B2'],
      ['segregating','adj','Currently segregating','separate,ongoing','B2'],
      ['segregated','adj','Having been segregated','separate,completed','B2'],
      ['resegregate','v','To segregate again','separate again,repeat','B2'],
      ['unsegregate','v','To reverse segregating','reverse,undo','C1'],
      ['oversegregate','v','To segregate excessively','excess,too much','C1'],
      ['undersegregate','v','To segregate insufficiently','insufficient,inadequate','C1'],
      ['missegregate','v','To segregate incorrectly','wrongly,incorrectly','C1'],
      ['presegregate','v','To segregate beforehand','before,in advance','C1'],
      ['cosegregate','v','To segregate together','jointly,together','C1'],
      ['resegregatation','n','The act of segregating again','re-separate','C1'],
      ['oversegregatation','n','Excessive segregating','excess separate','C1'],
      ['stratify','v','To arrange in social layers','layer,classify,rank','C1'],
      ['stratifyation','n','The act of stratifying','layer process','C1'],
      ['stratifyment','n','The result of stratifying','layer outcome','C1'],
      ['stratifyance','n','The state of stratifying','layer state','C1'],
      ['stratifyence','n','The quality of stratifying','layer quality','C1'],
      ['stratifyal','n','An act of stratifying','layer event','C2'],
      ['stratifyer','n','One who stratifys','layer person','C1'],
      ['stratifyor','n','One who stratifys','layer agent','C1'],
      ['stratifyee','n','One who is stratifyd','layer recipient','C2'],
      ['stratifyable','adj','Capable of being stratifyd','layer,possible','C2'],
      ['stratifyible','adj','Able to be stratifyd','layer,feasible','C2'],
      ['stratifyive','adj','Tending to stratify','layer,active','C1'],
      ['stratifying','adj','Currently stratifying','layer,ongoing','C1'],
      ['stratifyed','adj','Having been stratifyd','layer,completed','C1'],
      ['restratify','v','To stratify again','layer again,repeat','C1'],
      ['unstratify','v','To reverse stratifying','reverse,undo','C2'],
      ['overstratify','v','To stratify excessively','excess,too much','C2'],
      ['understratify','v','To stratify insufficiently','insufficient,inadequate','C2'],
      ['misstratify','v','To stratify incorrectly','wrongly,incorrectly','C2'],
      ['prestratify','v','To stratify beforehand','before,in advance','C2'],
      ['costratify','v','To stratify together','jointly,together','C2'],
      ['restratifyation','n','The act of stratifying again','re-layer','C2'],
      ['overstratifyation','n','Excessive stratifying','excess layer','C2'],
      ['disenfranchisment','n','The result of disenfranchising','exclude outcome','C1'],
      ['disenfranchisance','n','The state of disenfranchising','exclude state','C1'],
      ['disenfranchisence','n','The quality of disenfranchising','exclude quality','C1'],
      ['disenfranchisal','n','An act of disenfranchising','exclude event','C2'],
      ['disenfranchisor','n','One who disenfranchises','exclude agent','C1'],
      ['disenfranchisee','n','One who is disenfranchised','exclude recipient','C2'],
      ['disenfranchisible','adj','Able to be disenfranchised','exclude,feasible','C2'],
      ['disenfranchisive','adj','Tending to disenfranchise','exclude,active','C1'],
      ['disenfranchised','adj','Having been disenfranchised','exclude,completed','C1'],
      ['redisenfranchise','v','To disenfranchise again','exclude again,repeat','C1'],
      ['undisenfranchise','v','To reverse disenfranchising','reverse,undo','C2'],
      ['overdisenfranchise','v','To disenfranchise excessively','excess,too much','C2'],
      ['underdisenfranchise','v','To disenfranchise insufficiently','insufficient,inadequate','C2'],
      ['misdisenfranchise','v','To disenfranchise incorrectly','wrongly,incorrectly','C2'],
      ['predisenfranchise','v','To disenfranchise beforehand','before,in advance','C2'],
      ['codisenfranchise','v','To disenfranchise together','jointly,together','C2'],
      ['redisenfranchisation','n','The act of disenfranchising again','re-exclude','C2'],
      ['overdisenfranchisation','n','Excessive disenfranchising','excess exclude','C2'],
      ['ostracize','v','To exclude from a group','shun,reject,banish','C1'],
      ['ostracization','n','The act of ostracizing','shun process','C1'],
      ['ostracizment','n','The result of ostracizing','shun outcome','C1'],
      ['ostracizance','n','The state of ostracizing','shun state','C1'],
      ['ostracizence','n','The quality of ostracizing','shun quality','C1'],
      ['ostracizal','n','An act of ostracizing','shun event','C2'],
      ['ostracizer','n','One who ostracizes','shun person','C1'],
      ['ostracizor','n','One who ostracizes','shun agent','C1'],
      ['ostracizee','n','One who is ostracized','shun recipient','C2'],
      ['ostracizable','adj','Capable of being ostracized','shun,possible','C2'],
      ['ostracizible','adj','Able to be ostracized','shun,feasible','C2'],
      ['ostracizive','adj','Tending to ostracize','shun,active','C1'],
      ['ostracizing','adj','Currently ostracizing','shun,ongoing','C1'],
      ['ostracized','adj','Having been ostracized','shun,completed','C1'],
      ['reostracize','v','To ostracize again','shun again,repeat','C1'],
      ['unostracize','v','To reverse ostracizing','reverse,undo','C2'],
      ['overostracize','v','To ostracize excessively','excess,too much','C2'],
      ['underostracize','v','To ostracize insufficiently','insufficient,inadequate','C2'],
      ['misostracize','v','To ostracize incorrectly','wrongly,incorrectly','C2'],
      ['preostracize','v','To ostracize beforehand','before,in advance','C2'],
      ['coostracize','v','To ostracize together','jointly,together','C2'],
      ['reostracization','n','The act of ostracizing again','re-shun','C2'],
      ['overostracization','n','Excessive ostracizing','excess shun','C2'],
      ['stigmatize','v','To regard as worthy of disgrace','label,brand,condemn','C1'],
      ['stigmatization','n','The act of stigmatizing','label process','C1'],
      ['stigmatizment','n','The result of stigmatizing','label outcome','C1'],
      ['stigmatizance','n','The state of stigmatizing','label state','C1'],
      ['stigmatizence','n','The quality of stigmatizing','label quality','C1'],
      ['stigmatizal','n','An act of stigmatizing','label event','C2'],
      ['stigmatizer','n','One who stigmatizes','label person','C1'],
      ['stigmatizor','n','One who stigmatizes','label agent','C1'],
      ['stigmatizee','n','One who is stigmatized','label recipient','C2'],
      ['stigmatizable','adj','Capable of being stigmatized','label,possible','C2'],
      ['stigmatizible','adj','Able to be stigmatized','label,feasible','C2'],
      ['stigmatizive','adj','Tending to stigmatize','label,active','C1'],
      ['stigmatizing','adj','Currently stigmatizing','label,ongoing','C1'],
      ['stigmatized','adj','Having been stigmatized','label,completed','C1'],
      ['restigmatize','v','To stigmatize again','label again,repeat','C1'],
      ['unstigmatize','v','To reverse stigmatizing','reverse,undo','C2'],
      ['overstigmatize','v','To stigmatize excessively','excess,too much','C2'],
      ['understigmatize','v','To stigmatize insufficiently','insufficient,inadequate','C2'],
      ['misstigmatize','v','To stigmatize incorrectly','wrongly,incorrectly','C2'],
      ['prestigmatize','v','To stigmatize beforehand','before,in advance','C2'],
      ['costigmatize','v','To stigmatize together','jointly,together','C2'],
      ['restigmatization','n','The act of stigmatizing again','re-label','C2'],
      ['overstigmatization','n','Excessive stigmatizing','excess label','C2'],
      ['radicalize','v','To cause to adopt extreme views','extremize,polarize,convert','C1'],
      ['radicalization','n','The act of radicalizing','extremize process','C1'],
      ['radicalizment','n','The result of radicalizing','extremize outcome','C1'],
      ['radicalizance','n','The state of radicalizing','extremize state','C1'],
      ['radicalizence','n','The quality of radicalizing','extremize quality','C1'],
      ['radicalizal','n','An act of radicalizing','extremize event','C2'],
      ['radicalizer','n','One who radicalizes','extremize person','C1'],
      ['radicalizor','n','One who radicalizes','extremize agent','C1'],
      ['radicalizee','n','One who is radicalized','extremize recipient','C2'],
      ['radicalizable','adj','Capable of being radicalized','extremize,possible','C2'],
      ['radicalizible','adj','Able to be radicalized','extremize,feasible','C2'],
      ['radicalizive','adj','Tending to radicalize','extremize,active','C1'],
      ['radicalizing','adj','Currently radicalizing','extremize,ongoing','C1'],
      ['radicalized','adj','Having been radicalized','extremize,completed','C1'],
      ['reradicalize','v','To radicalize again','extremize again,repeat','C1'],
      ['unradicalize','v','To reverse radicalizing','reverse,undo','C2'],
      ['overradicalize','v','To radicalize excessively','excess,too much','C2'],
      ['underradicalize','v','To radicalize insufficiently','insufficient,inadequate','C2'],
      ['misradicalize','v','To radicalize incorrectly','wrongly,incorrectly','C2'],
      ['preradicalize','v','To radicalize beforehand','before,in advance','C2'],
      ['coradicalize','v','To radicalize together','jointly,together','C2'],
      ['reradicalization','n','The act of radicalizing again','re-extremize','C2'],
      ['overradicalization','n','Excessive radicalizing','excess extremize','C2'],
      ['socioeconomicly','adv','In a socioeconomic manner','social-economic way','B2'],
      ['socioeconomicness','n','The quality of being socioeconomic','social-economic quality','B2'],
      ['socioeconomicity','n','The state of being socioeconomic','social-economic condition','C1'],
      ['unsocioeconomic','adj','Not socioeconomic','not social-economic','B2'],
      ['insocioeconomic','adj','Not socioeconomic','not social-economic','C1'],
      ['nonsocioeconomic','adj','Not socioeconomic','not social-economic','B2'],
      ['semisocioeconomic','adj','Partially socioeconomic','partly social-economic','C1'],
      ['oversocioeconomic','adj','Excessively socioeconomic','too social-economic','C1'],
      ['ultrasocioeconomic','adj','Extremely socioeconomic','very social-economic','C1'],
      ['egalitarianity','n','The state of being egalitarian','equal condition','C2'],
      ['inegalitarian','adj','Not egalitarian','not equal','C2'],
      ['nonegalitarian','adj','Not egalitarian','not equal','C1'],
      ['semiegalitarian','adj','Partially egalitarian','partly equal','C2'],
      ['overegalitarian','adj','Excessively egalitarian','too equal','C2'],
      ['ultraegalitarian','adj','Extremely egalitarian','very equal','C2'],
      ['patriarchality','n','The state of being patriarchal','male-led condition','C2'],
      ['inpatriarchal','adj','Not patriarchal','not male-led','C2'],
      ['nonpatriarchal','adj','Not patriarchal','not male-led','C1'],
      ['semipatriarchal','adj','Partially patriarchal','partly male-led','C2'],
      ['overpatriarchal','adj','Excessively patriarchal','too male-led','C2'],
      ['ultrapatriarchal','adj','Extremely patriarchal','very male-led','C2'],
      ['pluralistic','adj','Allowing diverse groups to coexist','diverse,multicultural,inclusive','C1'],
      ['pluralisticly','adv','In a pluralistic manner','diverse way','C1'],
      ['pluralisticness','n','The quality of being pluralistic','diverse quality','C1'],
      ['pluralisticity','n','The state of being pluralistic','diverse condition','C2'],
      ['unpluralistic','adj','Not pluralistic','not diverse','C1'],
      ['inpluralistic','adj','Not pluralistic','not diverse','C2'],
      ['nonpluralistic','adj','Not pluralistic','not diverse','C1'],
      ['semipluralistic','adj','Partially pluralistic','partly diverse','C2'],
      ['overpluralistic','adj','Excessively pluralistic','too diverse','C2'],
      ['ultrapluralistic','adj','Extremely pluralistic','very diverse','C2'],
      ['meritocraticity','n','The state of being meritocratic','merit-based condition','C2'],
      ['inmeritocratic','adj','Not meritocratic','not merit-based','C2'],
      ['nonmeritocratic','adj','Not meritocratic','not merit-based','C1'],
      ['semimeritocratic','adj','Partially meritocratic','partly merit-based','C2'],
      ['overmeritocratic','adj','Excessively meritocratic','too merit-based','C2'],
      ['ultrameritocratic','adj','Extremely meritocratic','very merit-based','C2'],
      ['homogeneously','adv','In a homogeneous manner','uniform way','C1'],
      ['homogeneousness','n','The quality of being homogeneous','uniform quality','C1'],
      ['homogeneousity','n','The state of being homogeneous','uniform condition','C2'],
      ['unhomogeneous','adj','Not homogeneous','not uniform','C1'],
      ['inhomogeneous','adj','Not homogeneous','not uniform','C2'],
      ['nonhomogeneous','adj','Not homogeneous','not uniform','C1'],
      ['semihomogeneous','adj','Partially homogeneous','partly uniform','C2'],
      ['overhomogeneous','adj','Excessively homogeneous','too uniform','C2'],
      ['ultrahomogeneous','adj','Extremely homogeneous','very uniform','C2'],
      ['heterogeneously','adv','In a heterogeneous manner','mixed way','C1'],
      ['heterogeneousness','n','The quality of being heterogeneous','mixed quality','C1'],
      ['heterogeneousity','n','The state of being heterogeneous','mixed condition','C2'],
      ['unheterogeneous','adj','Not heterogeneous','not mixed','C1'],
      ['inheterogeneous','adj','Not heterogeneous','not mixed','C2'],
      ['nonheterogeneous','adj','Not heterogeneous','not mixed','C1'],
      ['semiheterogeneous','adj','Partially heterogeneous','partly mixed','C2'],
      ['overheterogeneous','adj','Excessively heterogeneous','too mixed','C2'],
    ],
  },
  collocations: {}
};
