// Auto-generated vocab boost group 61
module.exports = {
  vocab: {
    media: [
      ['amplifyment','n','The result of amplifying','boost outcome','B2'],
      ['amplifyance','n','The state of amplifying','boost state','B2'],
      ['amplifyence','n','The quality of amplifying','boost quality','B2'],
      ['amplifyal','n','An act of amplifying','boost event','C1'],
      ['amplifyer','n','One who amplifys','boost person','B2'],
      ['amplifyor','n','One who amplifys','boost agent','B2'],
      ['amplifyee','n','One who is amplifyd','boost recipient','C1'],
      ['amplifyable','adj','Capable of being amplifyd','boost,possible','C1'],
      ['amplifyible','adj','Able to be amplifyd','boost,feasible','C1'],
      ['amplifyive','adj','Tending to amplify','boost,active','B2'],
      ['amplifying','adj','Currently amplifying','boost,ongoing','B2'],
      ['amplifyed','adj','Having been amplifyd','boost,completed','B2'],
      ['reamplify','v','To amplify again','boost again,repeat','B2'],
      ['unamplify','v','To reverse amplifying','reverse,undo','C1'],
      ['overamplify','v','To amplify excessively','excess,too much','C1'],
      ['underamplify','v','To amplify insufficiently','insufficient,inadequate','C1'],
      ['misamplify','v','To amplify incorrectly','wrongly,incorrectly','C1'],
      ['preamplify','v','To amplify beforehand','before,in advance','C1'],
      ['coamplify','v','To amplify together','jointly,together','C1'],
      ['reamplifyation','n','The act of amplifying again','re-boost','C1'],
      ['overamplifyation','n','Excessive amplifying','excess boost','C1'],
      ['misinform','v','To give false information','mislead,deceive,distort','B2'],
      ['misinformment','n','The result of misinforming','mislead outcome','B2'],
      ['misinformance','n','The state of misinforming','mislead state','B2'],
      ['misinformence','n','The quality of misinforming','mislead quality','B2'],
      ['misinformal','n','An act of misinforming','mislead event','C1'],
      ['misinformer','n','One who misinforms','mislead person','B2'],
      ['misinformor','n','One who misinforms','mislead agent','B2'],
      ['misinformee','n','One who is misinformd','mislead recipient','C1'],
      ['misinformable','adj','Capable of being misinformd','mislead,possible','C1'],
      ['misinformible','adj','Able to be misinformd','mislead,feasible','C1'],
      ['misinformive','adj','Tending to misinform','mislead,active','B2'],
      ['misinforming','adj','Currently misinforming','mislead,ongoing','B2'],
      ['misinformed','adj','Having been misinformd','mislead,completed','B2'],
      ['remisinform','v','To misinform again','mislead again,repeat','B2'],
      ['unmisinform','v','To reverse misinforming','reverse,undo','C1'],
      ['overmisinform','v','To misinform excessively','excess,too much','C1'],
      ['undermisinform','v','To misinform insufficiently','insufficient,inadequate','C1'],
      ['mismisinform','v','To misinform incorrectly','wrongly,incorrectly','C1'],
      ['premisinform','v','To misinform beforehand','before,in advance','C1'],
      ['comisinform','v','To misinform together','jointly,together','C1'],
      ['remisinformation','n','The act of misinforming again','re-mislead','C1'],
      ['overmisinformation','n','Excessive misinforming','excess mislead','C1'],
      ['satirically','adv','In a satirical manner','mocking way','B2'],
      ['satiricalness','n','The quality of being satirical','mocking quality','B2'],
      ['satiricality','n','The state of being satirical','mocking condition','C1'],
      ['unsatirical','adj','Not satirical','not mocking','B2'],
      ['insatirical','adj','Not satirical','not mocking','C1'],
      ['nonsatirical','adj','Not satirical','not mocking','B2'],
      ['semisatirical','adj','Partially satirical','partly mocking','C1'],
      ['oversatirical','adj','Excessively satirical','too mocking','C1'],
      ['ultrasatirical','adj','Extremely satirical','very mocking','C1'],
      ['polemically','adv','In a polemical manner','contentious way','C1'],
      ['polemicalness','n','The quality of being polemical','contentious quality','C1'],
      ['polemicality','n','The state of being polemical','contentious condition','C2'],
      ['unpolemical','adj','Not polemical','not contentious','C1'],
      ['inpolemical','adj','Not polemical','not contentious','C2'],
      ['nonpolemical','adj','Not polemical','not contentious','C1'],
      ['semipolemical','adj','Partially polemical','partly contentious','C2'],
      ['overpolemical','adj','Excessively polemical','too contentious','C2'],
      ['ultrapolemical','adj','Extremely polemical','very contentious','C2'],
      ['scurrilous','adj','Making scandalous claims','defamatory,slanderous,malicious','C2'],
      ['scurrilously','adv','In a scurrilous manner','defamatory way','C2'],
      ['scurrilousness','n','The quality of being scurrilous','defamatory quality','C2'],
      ['scurrilousity','n','The state of being scurrilous','defamatory condition','C2'],
      ['unscurrilous','adj','Not scurrilous','not defamatory','C2'],
      ['inscurrilous','adj','Not scurrilous','not defamatory','C2'],
      ['nonscurrilous','adj','Not scurrilous','not defamatory','C2'],
      ['semiscurrilous','adj','Partially scurrilous','partly defamatory','C2'],
      ['overscurrilous','adj','Excessively scurrilous','too defamatory','C2'],
      ['ultrascurrilous','adj','Extremely scurrilous','very defamatory','C2'],
      ['broadsheetic','adj','Of or relating to broadsheet','quality paper-based,characteristic','B2'],
      ['broadsheetous','adj','Full of broadsheet','quality paper-filled,abundant','C1'],
      ['broadsheetful','adj','Full of broadsheet','quality paper-rich,abounding','B2'],
      ['broadsheetless','adj','Without broadsheet','lacking,without','B2'],
      ['broadsheetism','n','The ideology of broadsheet','quality paper ideology,doctrine','C1'],
      ['broadsheetist','n','A person focused on broadsheet','quality paper specialist,advocate','C1'],
      ['broadsheetise','v','To make into broadsheet','quality paper,convert','C1'],
      ['broadsheetize','v','To make or become broadsheet','quality paper,transform','C1'],
      ['antibroadsheet','adj','Opposed to broadsheet','against,opposing','C1'],
      ['nonbroadsheet','adj','Not involving broadsheet','without,lacking','B2'],
      ['prebroadsheet','n','Before broadsheet','preceding,prior','C1'],
      ['postbroadsheet','n','After broadsheet','following,subsequent','C1'],
      ['subbroadsheet','n','A subdivision of broadsheet','subset,branch','C1'],
      ['multibroadsheet','adj','Involving many broadsheets','multiple,several','C1'],
      ['interbroadsheet','adj','Between broadsheets','cross,between','C1'],
    ],
    communication: [
      ['paraphrasment','n','The result of paraphrasing','rephrase outcome','B2'],
      ['paraphrasance','n','The state of paraphrasing','rephrase state','B2'],
      ['paraphrasence','n','The quality of paraphrasing','rephrase quality','B2'],
      ['paraphrasal','n','An act of paraphrasing','rephrase event','C1'],
      ['paraphrasor','n','One who paraphrases','rephrase agent','B2'],
      ['paraphrasee','n','One who is paraphrased','rephrase recipient','C1'],
      ['paraphrasible','adj','Able to be paraphrased','rephrase,feasible','C1'],
      ['paraphrasive','adj','Tending to paraphrase','rephrase,active','B2'],
      ['paraphrased','adj','Having been paraphrased','rephrase,completed','B2'],
      ['reparaphrase','v','To paraphrase again','rephrase again,repeat','B2'],
      ['unparaphrase','v','To reverse paraphrasing','reverse,undo','C1'],
      ['overparaphrase','v','To paraphrase excessively','excess,too much','C1'],
      ['underparaphrase','v','To paraphrase insufficiently','insufficient,inadequate','C1'],
      ['misparaphrase','v','To paraphrase incorrectly','wrongly,incorrectly','C1'],
      ['preparaphrase','v','To paraphrase beforehand','before,in advance','C1'],
      ['coparaphrase','v','To paraphrase together','jointly,together','C1'],
      ['reparaphrasation','n','The act of paraphrasing again','re-rephrase','C1'],
      ['overparaphrasation','n','Excessive paraphrasing','excess rephrase','C1'],
      ['elaboratation','n','The act of elaborating','expand process','B2'],
      ['elaboratment','n','The result of elaborating','expand outcome','B2'],
      ['elaboratance','n','The state of elaborating','expand state','B2'],
      ['elaboratence','n','The quality of elaborating','expand quality','B2'],
      ['elaboratal','n','An act of elaborating','expand event','C1'],
      ['elaborater','n','One who elaborates','expand person','B2'],
      ['elaborator','n','One who elaborates','expand agent','B2'],
      ['elaboratee','n','One who is elaborated','expand recipient','C1'],
      ['elaboratable','adj','Capable of being elaborated','expand,possible','C1'],
      ['elaboratible','adj','Able to be elaborated','expand,feasible','C1'],
      ['elaborative','adj','Tending to elaborate','expand,active','B2'],
      ['elaborating','adj','Currently elaborating','expand,ongoing','B2'],
      ['elaborated','adj','Having been elaborated','expand,completed','B2'],
      ['reelaborate','v','To elaborate again','expand again,repeat','B2'],
      ['unelaborate','v','To reverse elaborating','reverse,undo','C1'],
      ['overelaborate','v','To elaborate excessively','excess,too much','C1'],
      ['underelaborate','v','To elaborate insufficiently','insufficient,inadequate','C1'],
      ['miselaborate','v','To elaborate incorrectly','wrongly,incorrectly','C1'],
      ['preelaborate','v','To elaborate beforehand','before,in advance','C1'],
      ['coelaborate','v','To elaborate together','jointly,together','C1'],
      ['reelaboratation','n','The act of elaborating again','re-expand','C1'],
      ['overelaboratation','n','Excessive elaborating','excess expand','C1'],
      ['persuadment','n','The result of persuading','convince outcome','B1'],
      ['persuadance','n','The state of persuading','convince state','B1'],
      ['persuadence','n','The quality of persuading','convince quality','B1'],
      ['persuadal','n','An act of persuading','convince event','B2'],
      ['persuador','n','One who persuades','convince agent','B1'],
      ['persuadee','n','One who is persuaded','convince recipient','B2'],
      ['persuadible','adj','Able to be persuaded','convince,feasible','B2'],
      ['persuadive','adj','Tending to persuade','convince,active','B1'],
      ['persuaded','adj','Having been persuaded','convince,completed','B1'],
      ['repersuade','v','To persuade again','convince again,repeat','B1'],
      ['unpersuade','v','To reverse persuading','reverse,undo','B2'],
      ['overpersuade','v','To persuade excessively','excess,too much','B2'],
      ['underpersuade','v','To persuade insufficiently','insufficient,inadequate','B2'],
      ['mispersuade','v','To persuade incorrectly','wrongly,incorrectly','B2'],
      ['prepersuade','v','To persuade beforehand','before,in advance','B2'],
      ['copersuade','v','To persuade together','jointly,together','B2'],
      ['repersuadation','n','The act of persuading again','re-convince','B2'],
      ['overpersuadation','n','Excessive persuading','excess convince','B2'],
      ['mediatation','n','The act of mediating','arbitrate process','B2'],
      ['mediatment','n','The result of mediating','arbitrate outcome','B2'],
      ['mediatance','n','The state of mediating','arbitrate state','B2'],
      ['mediatence','n','The quality of mediating','arbitrate quality','B2'],
      ['mediatal','n','An act of mediating','arbitrate event','C1'],
      ['mediater','n','One who mediates','arbitrate person','B2'],
      ['mediator','n','One who mediates','arbitrate agent','B2'],
      ['mediatee','n','One who is mediated','arbitrate recipient','C1'],
      ['mediatable','adj','Capable of being mediated','arbitrate,possible','C1'],
      ['mediatible','adj','Able to be mediated','arbitrate,feasible','C1'],
      ['mediative','adj','Tending to mediate','arbitrate,active','B2'],
      ['mediating','adj','Currently mediating','arbitrate,ongoing','B2'],
      ['mediated','adj','Having been mediated','arbitrate,completed','B2'],
      ['unmediate','v','To reverse mediating','reverse,undo','C1'],
      ['overmediate','v','To mediate excessively','excess,too much','C1'],
      ['undermediate','v','To mediate insufficiently','insufficient,inadequate','C1'],
      ['mismediate','v','To mediate incorrectly','wrongly,incorrectly','C1'],
      ['premediate','v','To mediate beforehand','before,in advance','C1'],
      ['comediate','v','To mediate together','jointly,together','C1'],
      ['overmediatation','n','Excessive mediating','excess arbitrate','C1'],
      ['gesticulatation','n','The act of gesticulating','gesture process','C1'],
      ['gesticulatment','n','The result of gesticulating','gesture outcome','C1'],
      ['gesticulatance','n','The state of gesticulating','gesture state','C1'],
      ['gesticulatence','n','The quality of gesticulating','gesture quality','C1'],
      ['gesticulatal','n','An act of gesticulating','gesture event','C2'],
      ['gesticulater','n','One who gesticulates','gesture person','C1'],
      ['gesticulator','n','One who gesticulates','gesture agent','C1'],
      ['gesticulatee','n','One who is gesticulated','gesture recipient','C2'],
      ['gesticulatable','adj','Capable of being gesticulated','gesture,possible','C2'],
      ['gesticulatible','adj','Able to be gesticulated','gesture,feasible','C2'],
      ['gesticulative','adj','Tending to gesticulate','gesture,active','C1'],
      ['gesticulating','adj','Currently gesticulating','gesture,ongoing','C1'],
      ['gesticulated','adj','Having been gesticulated','gesture,completed','C1'],
      ['regesticulate','v','To gesticulate again','gesture again,repeat','C1'],
      ['ungesticulate','v','To reverse gesticulating','reverse,undo','C2'],
      ['overgesticulate','v','To gesticulate excessively','excess,too much','C2'],
      ['undergesticulate','v','To gesticulate insufficiently','insufficient,inadequate','C2'],
      ['misgesticulate','v','To gesticulate incorrectly','wrongly,incorrectly','C2'],
      ['pregesticulate','v','To gesticulate beforehand','before,in advance','C2'],
      ['cogesticulate','v','To gesticulate together','jointly,together','C2'],
      ['regesticulatation','n','The act of gesticulating again','re-gesture','C2'],
      ['overgesticulatation','n','Excessive gesticulating','excess gesture','C2'],
      ['enunciatation','n','The act of enunciating','pronounce process','C1'],
      ['enunciatment','n','The result of enunciating','pronounce outcome','C1'],
      ['enunciatance','n','The state of enunciating','pronounce state','C1'],
      ['enunciatence','n','The quality of enunciating','pronounce quality','C1'],
      ['enunciatal','n','An act of enunciating','pronounce event','C2'],
      ['enunciater','n','One who enunciates','pronounce person','C1'],
      ['enunciator','n','One who enunciates','pronounce agent','C1'],
      ['enunciatee','n','One who is enunciated','pronounce recipient','C2'],
      ['enunciatable','adj','Capable of being enunciated','pronounce,possible','C2'],
      ['enunciatible','adj','Able to be enunciated','pronounce,feasible','C2'],
      ['enunciative','adj','Tending to enunciate','pronounce,active','C1'],
      ['enunciating','adj','Currently enunciating','pronounce,ongoing','C1'],
      ['enunciated','adj','Having been enunciated','pronounce,completed','C1'],
      ['reenunciate','v','To enunciate again','pronounce again,repeat','C1'],
      ['unenunciate','v','To reverse enunciating','reverse,undo','C2'],
      ['overenunciate','v','To enunciate excessively','excess,too much','C2'],
      ['underenunciate','v','To enunciate insufficiently','insufficient,inadequate','C2'],
      ['misenunciate','v','To enunciate incorrectly','wrongly,incorrectly','C2'],
      ['preenunciate','v','To enunciate beforehand','before,in advance','C2'],
      ['coenunciate','v','To enunciate together','jointly,together','C2'],
      ['reenunciatation','n','The act of enunciating again','re-pronounce','C2'],
      ['overenunciatation','n','Excessive enunciating','excess pronounce','C2'],
      ['insinuate','v','To suggest something indirectly','imply,hint,suggest','C1'],
      ['insinuatation','n','The act of insinuating','imply process','C1'],
      ['insinuatment','n','The result of insinuating','imply outcome','C1'],
      ['insinuatance','n','The state of insinuating','imply state','C1'],
      ['insinuatence','n','The quality of insinuating','imply quality','C1'],
      ['insinuatal','n','An act of insinuating','imply event','C2'],
      ['insinuater','n','One who insinuates','imply person','C1'],
      ['insinuator','n','One who insinuates','imply agent','C1'],
      ['insinuatee','n','One who is insinuated','imply recipient','C2'],
      ['insinuatable','adj','Capable of being insinuated','imply,possible','C2'],
      ['insinuatible','adj','Able to be insinuated','imply,feasible','C2'],
      ['insinuative','adj','Tending to insinuate','imply,active','C1'],
      ['insinuating','adj','Currently insinuating','imply,ongoing','C1'],
      ['insinuated','adj','Having been insinuated','imply,completed','C1'],
      ['reinsinuate','v','To insinuate again','imply again,repeat','C1'],
      ['uninsinuate','v','To reverse insinuating','reverse,undo','C2'],
      ['overinsinuate','v','To insinuate excessively','excess,too much','C2'],
      ['underinsinuate','v','To insinuate insufficiently','insufficient,inadequate','C2'],
      ['misinsinuate','v','To insinuate incorrectly','wrongly,incorrectly','C2'],
      ['preinsinuate','v','To insinuate beforehand','before,in advance','C2'],
      ['coinsinuate','v','To insinuate together','jointly,together','C2'],
      ['reinsinuatation','n','The act of insinuating again','re-imply','C2'],
      ['overinsinuatation','n','Excessive insinuating','excess imply','C2'],
      ['rhetoricic','adj','Of or relating to rhetoric','eloquence-based,characteristic','B2'],
      ['rhetoricous','adj','Full of rhetoric','eloquence-filled,abundant','C1'],
      ['rhetoricful','adj','Full of rhetoric','eloquence-rich,abounding','B2'],
      ['rhetoricless','adj','Without rhetoric','lacking,without','B2'],
      ['rhetoricism','n','The ideology of rhetoric','eloquence ideology,doctrine','C1'],
      ['rhetoricist','n','A person focused on rhetoric','eloquence specialist,advocate','C1'],
      ['rhetoricise','v','To make into rhetoric','eloquence,convert','C1'],
      ['rhetoricize','v','To make or become rhetoric','eloquence,transform','C1'],
      ['antirhetoric','adj','Opposed to rhetoric','against,opposing','C1'],
      ['nonrhetoric','adj','Not involving rhetoric','without,lacking','B2'],
      ['prerhetoric','n','Before rhetoric','preceding,prior','C1'],
      ['postrhetoric','n','After rhetoric','following,subsequent','C1'],
      ['subrhetoric','n','A subdivision of rhetoric','subset,branch','C1'],
      ['multirhetoric','adj','Involving many rhetorics','multiple,several','C1'],
      ['interrhetoric','adj','Between rhetorics','cross,between','C1'],
      ['discourseic','adj','Of or relating to discourse','discussion-based,characteristic','B2'],
      ['discourseous','adj','Full of discourse','discussion-filled,abundant','C1'],
      ['discourseful','adj','Full of discourse','discussion-rich,abounding','B2'],
      ['discourseless','adj','Without discourse','lacking,without','B2'],
    ],
  },
  collocations: {}
};
