// Auto-generated vocab boost group 52
module.exports = {
  vocab: {
    society: [
      ['prepeer pressure','n','Before peer pressure','preceding,prior','B2'],
      ['postpeer pressure','n','After peer pressure','following,subsequent','B2'],
      ['subpeer pressure','n','A subdivision of peer pressure','subset,branch','B2'],
      ['multipeer pressure','adj','Involving many peer pressures','multiple,several','B2'],
      ['interpeer pressure','adj','Between peer pressures','cross,between','B2'],
      ['social cohesion','n','Bonds that hold society together','unity,solidarity,togetherness','B2'],
      ['social cohesional','adj','Relating to social cohesion','unity-related,pertaining to','B2'],
      ['social cohesionic','adj','Of or relating to social cohesion','unity-based,characteristic','B2'],
      ['social cohesionous','adj','Full of social cohesion','unity-filled,abundant','C1'],
      ['social cohesionful','adj','Full of social cohesion','unity-rich,abounding','B2'],
      ['social cohesionless','adj','Without social cohesion','lacking,without','B2'],
      ['social cohesionism','n','The ideology of social cohesion','unity ideology,doctrine','C1'],
      ['social cohesionist','n','A person focused on social cohesion','unity specialist,advocate','C1'],
      ['social cohesionise','v','To make into social cohesion','unity,convert','C1'],
      ['social cohesionize','v','To make or become social cohesion','unity,transform','C1'],
      ['antisocial cohesion','adj','Opposed to social cohesion','against,opposing','C1'],
      ['nonsocial cohesion','adj','Not involving social cohesion','without,lacking','B2'],
      ['presocial cohesion','n','Before social cohesion','preceding,prior','C1'],
      ['postsocial cohesion','n','After social cohesion','following,subsequent','C1'],
      ['subsocial cohesion','n','A subdivision of social cohesion','subset,branch','C1'],
      ['multisocial cohesion','adj','Involving many social cohesions','multiple,several','C1'],
      ['intersocial cohesion','adj','Between social cohesions','cross,between','C1'],
      ['income inequality','n','Uneven distribution of wealth','wealth gap,economic disparity','B2'],
      ['income inequalityal','adj','Relating to income inequality','wealth gap-related,pertaining to','B2'],
      ['income inequalityic','adj','Of or relating to income inequality','wealth gap-based,characteristic','B2'],
      ['income inequalityous','adj','Full of income inequality','wealth gap-filled,abundant','C1'],
      ['income inequalityful','adj','Full of income inequality','wealth gap-rich,abounding','B2'],
      ['income inequalityless','adj','Without income inequality','lacking,without','B2'],
      ['income inequalityism','n','The ideology of income inequality','wealth gap ideology,doctrine','C1'],
      ['income inequalityist','n','A person focused on income inequality','wealth gap specialist,advocate','C1'],
      ['income inequalityise','v','To make into income inequality','wealth gap,convert','C1'],
      ['income inequalityize','v','To make or become income inequality','wealth gap,transform','C1'],
      ['antiincome inequality','adj','Opposed to income inequality','against,opposing','C1'],
      ['nonincome inequality','adj','Not involving income inequality','without,lacking','B2'],
      ['preincome inequality','n','Before income inequality','preceding,prior','C1'],
      ['postincome inequality','n','After income inequality','following,subsequent','C1'],
      ['subincome inequality','n','A subdivision of income inequality','subset,branch','C1'],
      ['multiincome inequality','adj','Involving many income inequalitys','multiple,several','C1'],
      ['interincome inequality','adj','Between income inequalitys','cross,between','C1'],
      ['homelessnessic','adj','Of or relating to homelessness','rough sleeping-based,characteristic','B2'],
      ['homelessnessous','adj','Full of homelessness','rough sleeping-filled,abundant','C1'],
      ['homelessnessful','adj','Full of homelessness','rough sleeping-rich,abounding','B2'],
      ['homelessnessless','adj','Without homelessness','lacking,without','B2'],
      ['homelessnessism','n','The ideology of homelessness','rough sleeping ideology,doctrine','C1'],
      ['homelessnessist','n','A person focused on homelessness','rough sleeping specialist,advocate','C1'],
      ['homelessnessise','v','To make into homelessness','rough sleeping,convert','C1'],
      ['homelessnessize','v','To make or become homelessness','rough sleeping,transform','C1'],
      ['antihomelessness','adj','Opposed to homelessness','against,opposing','C1'],
      ['nonhomelessness','adj','Not involving homelessness','without,lacking','B2'],
      ['prehomelessness','n','Before homelessness','preceding,prior','C1'],
      ['posthomelessness','n','After homelessness','following,subsequent','C1'],
      ['subhomelessness','n','A subdivision of homelessness','subset,branch','C1'],
      ['multihomelessness','adj','Involving many homelessnesss','multiple,several','C1'],
      ['interhomelessness','adj','Between homelessnesss','cross,between','C1'],
      ['volunteerism','n','The use of unpaid volunteers','voluntary work,community service','B2'],
      ['volunteerismal','adj','Relating to volunteerism','voluntary work-related,pertaining to','B2'],
      ['volunteerismic','adj','Of or relating to volunteerism','voluntary work-based,characteristic','B2'],
      ['volunteerismous','adj','Full of volunteerism','voluntary work-filled,abundant','C1'],
      ['volunteerismful','adj','Full of volunteerism','voluntary work-rich,abounding','B2'],
      ['volunteerismless','adj','Without volunteerism','lacking,without','B2'],
      ['volunteerismism','n','The ideology of volunteerism','voluntary work ideology,doctrine','C1'],
      ['volunteerismist','n','A person focused on volunteerism','voluntary work specialist,advocate','C1'],
      ['volunteerismise','v','To make into volunteerism','voluntary work,convert','C1'],
      ['volunteerismize','v','To make or become volunteerism','voluntary work,transform','C1'],
      ['antivolunteerism','adj','Opposed to volunteerism','against,opposing','C1'],
      ['nonvolunteerism','adj','Not involving volunteerism','without,lacking','B2'],
      ['prevolunteerism','n','Before volunteerism','preceding,prior','C1'],
      ['postvolunteerism','n','After volunteerism','following,subsequent','C1'],
      ['subvolunteerism','n','A subdivision of volunteerism','subset,branch','C1'],
      ['multivolunteerism','adj','Involving many volunteerisms','multiple,several','C1'],
      ['intervolunteerism','adj','Between volunteerisms','cross,between','C1'],
      ['conformity','n','Compliance with standards or norms','compliance,obedience,adherence','B2'],
      ['conformityal','adj','Relating to conformity','compliance-related,pertaining to','B2'],
      ['conformityic','adj','Of or relating to conformity','compliance-based,characteristic','B2'],
      ['conformityous','adj','Full of conformity','compliance-filled,abundant','C1'],
      ['conformityful','adj','Full of conformity','compliance-rich,abounding','B2'],
      ['conformityless','adj','Without conformity','lacking,without','B2'],
      ['conformityism','n','The ideology of conformity','compliance ideology,doctrine','C1'],
      ['conformityist','n','A person focused on conformity','compliance specialist,advocate','C1'],
      ['conformityise','v','To make into conformity','compliance,convert','C1'],
      ['conformityize','v','To make or become conformity','compliance,transform','C1'],
      ['anticonformity','adj','Opposed to conformity','against,opposing','C1'],
      ['nonconformity','adj','Not involving conformity','without,lacking','B2'],
      ['preconformity','n','Before conformity','preceding,prior','C1'],
      ['postconformity','n','After conformity','following,subsequent','C1'],
      ['subconformity','n','A subdivision of conformity','subset,branch','C1'],
      ['multiconformity','adj','Involving many conformitys','multiple,several','C1'],
      ['interconformity','adj','Between conformitys','cross,between','C1'],
      ['dissent','n','Disagreement with official policy','opposition,protest,objection','C1'],
      ['dissental','adj','Relating to dissent','opposition-related,pertaining to','C1'],
      ['dissentic','adj','Of or relating to dissent','opposition-based,characteristic','C1'],
      ['dissentous','adj','Full of dissent','opposition-filled,abundant','C2'],
      ['dissentful','adj','Full of dissent','opposition-rich,abounding','C1'],
      ['dissentless','adj','Without dissent','lacking,without','C1'],
      ['dissentism','n','The ideology of dissent','opposition ideology,doctrine','C2'],
      ['dissentist','n','A person focused on dissent','opposition specialist,advocate','C2'],
      ['dissentise','v','To make into dissent','opposition,convert','C2'],
      ['dissentize','v','To make or become dissent','opposition,transform','C2'],
      ['antidissent','adj','Opposed to dissent','against,opposing','C2'],
      ['nondissent','adj','Not involving dissent','without,lacking','C1'],
      ['predissent','n','Before dissent','preceding,prior','C2'],
      ['postdissent','n','After dissent','following,subsequent','C2'],
      ['subdissent','n','A subdivision of dissent','subset,branch','C2'],
      ['multidissent','adj','Involving many dissents','multiple,several','C2'],
      ['interdissent','adj','Between dissents','cross,between','C2'],
      ['solidarityal','adj','Relating to solidarity','unity-related,pertaining to','B2'],
      ['solidarityic','adj','Of or relating to solidarity','unity-based,characteristic','B2'],
      ['solidarityous','adj','Full of solidarity','unity-filled,abundant','C1'],
      ['solidarityful','adj','Full of solidarity','unity-rich,abounding','B2'],
      ['solidarityless','adj','Without solidarity','lacking,without','B2'],
      ['solidarityism','n','The ideology of solidarity','unity ideology,doctrine','C1'],
      ['solidarityist','n','A person focused on solidarity','unity specialist,advocate','C1'],
      ['solidarityise','v','To make into solidarity','unity,convert','C1'],
      ['solidarityize','v','To make or become solidarity','unity,transform','C1'],
      ['antisolidarity','adj','Opposed to solidarity','against,opposing','C1'],
      ['nonsolidarity','adj','Not involving solidarity','without,lacking','B2'],
      ['presolidarity','n','Before solidarity','preceding,prior','C1'],
      ['postsolidarity','n','After solidarity','following,subsequent','C1'],
      ['subsolidarity','n','A subdivision of solidarity','subset,branch','C1'],
      ['multisolidarity','adj','Involving many solidaritys','multiple,several','C1'],
      ['intersolidarity','adj','Between solidaritys','cross,between','C1'],
    ],
    culture: [
      ['acculturate','v','To adopt a different culture','adapt,assimilate,integrate','C1'],
      ['acculturatation','n','The act of acculturating','adapt process','C1'],
      ['acculturatment','n','The result of acculturating','adapt outcome','C1'],
      ['acculturatance','n','The state of acculturating','adapt state','C1'],
      ['acculturatence','n','The quality of acculturating','adapt quality','C1'],
      ['acculturatal','n','An act of acculturating','adapt event','C2'],
      ['acculturater','n','One who acculturates','adapt person','C1'],
      ['acculturator','n','One who acculturates','adapt agent','C1'],
      ['acculturatee','n','One who is acculturated','adapt recipient','C2'],
      ['acculturatable','adj','Capable of being acculturated','adapt,possible','C2'],
      ['acculturatible','adj','Able to be acculturated','adapt,feasible','C2'],
      ['acculturative','adj','Tending to acculturate','adapt,active','C1'],
      ['acculturating','adj','Currently acculturating','adapt,ongoing','C1'],
      ['acculturated','adj','Having been acculturated','adapt,completed','C1'],
      ['reacculturate','v','To acculturate again','adapt again,repeat','C1'],
      ['unacculturate','v','To reverse acculturating','reverse,undo','C2'],
      ['overacculturate','v','To acculturate excessively','excess,too much','C2'],
      ['underacculturate','v','To acculturate insufficiently','insufficient,inadequate','C2'],
      ['misacculturate','v','To acculturate incorrectly','wrongly,incorrectly','C2'],
      ['preacculturate','v','To acculturate beforehand','before,in advance','C2'],
      ['coacculturate','v','To acculturate together','jointly,together','C2'],
      ['reacculturatation','n','The act of acculturating again','re-adapt','C2'],
      ['overacculturatation','n','Excessive acculturating','excess adapt','C2'],
      ['appropriate','v','To take cultural elements from others','borrow,adopt,co-opt','B2'],
      ['appropriatation','n','The act of appropriating','borrow process','B2'],
      ['appropriatment','n','The result of appropriating','borrow outcome','B2'],
      ['appropriatance','n','The state of appropriating','borrow state','B2'],
      ['appropriatence','n','The quality of appropriating','borrow quality','B2'],
      ['appropriatal','n','An act of appropriating','borrow event','C1'],
      ['appropriater','n','One who appropriates','borrow person','B2'],
      ['appropriator','n','One who appropriates','borrow agent','B2'],
      ['appropriatee','n','One who is appropriated','borrow recipient','C1'],
      ['appropriatable','adj','Capable of being appropriated','borrow,possible','C1'],
      ['appropriatible','adj','Able to be appropriated','borrow,feasible','C1'],
      ['appropriative','adj','Tending to appropriate','borrow,active','B2'],
      ['appropriating','adj','Currently appropriating','borrow,ongoing','B2'],
      ['appropriated','adj','Having been appropriated','borrow,completed','B2'],
      ['reappropriate','v','To appropriate again','borrow again,repeat','B2'],
      ['unappropriate','v','To reverse appropriating','reverse,undo','C1'],
      ['overappropriate','v','To appropriate excessively','excess,too much','C1'],
      ['underappropriate','v','To appropriate insufficiently','insufficient,inadequate','C1'],
      ['misappropriate','v','To appropriate incorrectly','wrongly,incorrectly','C1'],
      ['preappropriate','v','To appropriate beforehand','before,in advance','C1'],
      ['coappropriate','v','To appropriate together','jointly,together','C1'],
      ['reappropriatation','n','The act of appropriating again','re-borrow','C1'],
      ['overappropriatation','n','Excessive appropriating','excess borrow','C1'],
      ['commemoratation','n','The act of commemorating','remember process','B2'],
      ['commemoratment','n','The result of commemorating','remember outcome','B2'],
      ['commemoratance','n','The state of commemorating','remember state','B2'],
      ['commemoratence','n','The quality of commemorating','remember quality','B2'],
      ['commemoratal','n','An act of commemorating','remember event','C1'],
      ['commemorater','n','One who commemorates','remember person','B2'],
      ['commemorator','n','One who commemorates','remember agent','B2'],
      ['commemoratee','n','One who is commemorated','remember recipient','C1'],
      ['commemoratable','adj','Capable of being commemorated','remember,possible','C1'],
      ['commemoratible','adj','Able to be commemorated','remember,feasible','C1'],
      ['commemorative','adj','Tending to commemorate','remember,active','B2'],
      ['commemorating','adj','Currently commemorating','remember,ongoing','B2'],
      ['commemorated','adj','Having been commemorated','remember,completed','B2'],
      ['recommemorate','v','To commemorate again','remember again,repeat','B2'],
      ['uncommemorate','v','To reverse commemorating','reverse,undo','C1'],
      ['overcommemorate','v','To commemorate excessively','excess,too much','C1'],
      ['undercommemorate','v','To commemorate insufficiently','insufficient,inadequate','C1'],
      ['miscommemorate','v','To commemorate incorrectly','wrongly,incorrectly','C1'],
      ['precommemorate','v','To commemorate beforehand','before,in advance','C1'],
      ['cocommemorate','v','To commemorate together','jointly,together','C1'],
      ['recommemoratation','n','The act of commemorating again','re-remember','C1'],
      ['overcommemoratation','n','Excessive commemorating','excess remember','C1'],
      ['ritualize','v','To make into a formal ceremony','formalize,ceremonialize,sanctify','C1'],
      ['ritualization','n','The act of ritualizing','formalize process','C1'],
      ['ritualizment','n','The result of ritualizing','formalize outcome','C1'],
      ['ritualizance','n','The state of ritualizing','formalize state','C1'],
      ['ritualizence','n','The quality of ritualizing','formalize quality','C1'],
      ['ritualizal','n','An act of ritualizing','formalize event','C2'],
      ['ritualizer','n','One who ritualizes','formalize person','C1'],
      ['ritualizor','n','One who ritualizes','formalize agent','C1'],
      ['ritualizee','n','One who is ritualized','formalize recipient','C2'],
      ['ritualizable','adj','Capable of being ritualized','formalize,possible','C2'],
      ['ritualizible','adj','Able to be ritualized','formalize,feasible','C2'],
      ['ritualizive','adj','Tending to ritualize','formalize,active','C1'],
      ['ritualizing','adj','Currently ritualizing','formalize,ongoing','C1'],
      ['ritualized','adj','Having been ritualized','formalize,completed','C1'],
      ['reritualize','v','To ritualize again','formalize again,repeat','C1'],
      ['unritualize','v','To reverse ritualizing','reverse,undo','C2'],
      ['overritualize','v','To ritualize excessively','excess,too much','C2'],
      ['underritualize','v','To ritualize insufficiently','insufficient,inadequate','C2'],
      ['misritualize','v','To ritualize incorrectly','wrongly,incorrectly','C2'],
      ['preritualize','v','To ritualize beforehand','before,in advance','C2'],
      ['coritualize','v','To ritualize together','jointly,together','C2'],
      ['reritualization','n','The act of ritualizing again','re-formalize','C2'],
      ['overritualization','n','Excessive ritualizing','excess formalize','C2'],
      ['consecrate','v','To declare something sacred','sanctify,bless,dedicate','C1'],
      ['consecratation','n','The act of consecrating','sanctify process','C1'],
      ['consecratment','n','The result of consecrating','sanctify outcome','C1'],
      ['consecratance','n','The state of consecrating','sanctify state','C1'],
      ['consecratence','n','The quality of consecrating','sanctify quality','C1'],
      ['consecratal','n','An act of consecrating','sanctify event','C2'],
      ['consecrater','n','One who consecrates','sanctify person','C1'],
      ['consecrator','n','One who consecrates','sanctify agent','C1'],
      ['consecratee','n','One who is consecrated','sanctify recipient','C2'],
      ['consecratable','adj','Capable of being consecrated','sanctify,possible','C2'],
      ['consecratible','adj','Able to be consecrated','sanctify,feasible','C2'],
      ['consecrative','adj','Tending to consecrate','sanctify,active','C1'],
      ['consecrating','adj','Currently consecrating','sanctify,ongoing','C1'],
      ['consecrated','adj','Having been consecrated','sanctify,completed','C1'],
      ['reconsecrate','v','To consecrate again','sanctify again,repeat','C1'],
      ['unconsecrate','v','To reverse consecrating','reverse,undo','C2'],
      ['overconsecrate','v','To consecrate excessively','excess,too much','C2'],
      ['underconsecrate','v','To consecrate insufficiently','insufficient,inadequate','C2'],
      ['misconsecrate','v','To consecrate incorrectly','wrongly,incorrectly','C2'],
      ['preconsecrate','v','To consecrate beforehand','before,in advance','C2'],
      ['coconsecrate','v','To consecrate together','jointly,together','C2'],
      ['reconsecratation','n','The act of consecrating again','re-sanctify','C2'],
      ['overconsecratation','n','Excessive consecrating','excess sanctify','C2'],
      ['venerate','v','To regard with great respect','revere,honour,worship','C1'],
      ['veneratation','n','The act of venerating','revere process','C1'],
      ['veneratment','n','The result of venerating','revere outcome','C1'],
      ['veneratance','n','The state of venerating','revere state','C1'],
      ['veneratence','n','The quality of venerating','revere quality','C1'],
      ['veneratal','n','An act of venerating','revere event','C2'],
      ['venerater','n','One who venerates','revere person','C1'],
      ['venerator','n','One who venerates','revere agent','C1'],
      ['veneratee','n','One who is venerated','revere recipient','C2'],
      ['veneratable','adj','Capable of being venerated','revere,possible','C2'],
      ['veneratible','adj','Able to be venerated','revere,feasible','C2'],
      ['venerative','adj','Tending to venerate','revere,active','C1'],
      ['venerating','adj','Currently venerating','revere,ongoing','C1'],
      ['venerated','adj','Having been venerated','revere,completed','C1'],
      ['revenerate','v','To venerate again','revere again,repeat','C1'],
    ],
  },
  collocations: {}
};
