// Auto-generated vocab boost group 90
module.exports = {
  vocab: {
    globalization: [
      ['overprotectionist','adj','Excessively protectionist','too trade-restricting','C1'],
      ['ultraprotectionist','adj','Extremely protectionist','very trade-restricting','C1'],
      ['interdependent','adj','Mutually reliant on each other','connected,interlinked,mutual','B2'],
      ['interdependently','adv','In a interdependent manner','connected way','B2'],
      ['interdependentness','n','The quality of being interdependent','connected quality','B2'],
      ['interdependentity','n','The state of being interdependent','connected condition','C1'],
      ['uninterdependent','adj','Not interdependent','not connected','B2'],
      ['ininterdependent','adj','Not interdependent','not connected','C1'],
      ['noninterdependent','adj','Not interdependent','not connected','B2'],
      ['semiinterdependent','adj','Partially interdependent','partly connected','C1'],
      ['overinterdependent','adj','Excessively interdependent','too connected','C1'],
      ['ultrainterdependent','adj','Extremely interdependent','very connected','C1'],
      ['assimilationistly','adv','In a assimilationist manner','integrationist way','C1'],
      ['assimilationistness','n','The quality of being assimilationist','integrationist quality','C1'],
      ['assimilationistity','n','The state of being assimilationist','integrationist condition','C2'],
      ['unassimilationist','adj','Not assimilationist','not integrationist','C1'],
      ['inassimilationist','adj','Not assimilationist','not integrationist','C2'],
      ['nonassimilationist','adj','Not assimilationist','not integrationist','C1'],
      ['semiassimilationist','adj','Partially assimilationist','partly integrationist','C2'],
      ['overassimilationist','adj','Excessively assimilationist','too integrationist','C2'],
      ['ultraassimilationist','adj','Extremely assimilationist','very integrationist','C2'],
      ['supranationally','adv','In a supranational manner','above-national way','C1'],
      ['supranationalness','n','The quality of being supranational','above-national quality','C1'],
      ['supranationality','n','The state of being supranational','above-national condition','C2'],
      ['unsupranational','adj','Not supranational','not above-national','C1'],
      ['insupranational','adj','Not supranational','not above-national','C2'],
      ['nonsupranational','adj','Not supranational','not above-national','C1'],
      ['semisupranational','adj','Partially supranational','partly above-national','C2'],
      ['oversupranational','adj','Excessively supranational','too above-national','C2'],
      ['ultrasupranational','adj','Extremely supranational','very above-national','C2'],
      ['autarkicly','adv','In a autarkic manner','self-reliant way','C2'],
      ['autarkicness','n','The quality of being autarkic','self-reliant quality','C2'],
      ['autarkicity','n','The state of being autarkic','self-reliant condition','C2'],
      ['unautarkic','adj','Not autarkic','not self-reliant','C2'],
      ['inautarkic','adj','Not autarkic','not self-reliant','C2'],
      ['nonautarkic','adj','Not autarkic','not self-reliant','C2'],
      ['semiautarkic','adj','Partially autarkic','partly self-reliant','C2'],
      ['overautarkic','adj','Excessively autarkic','too self-reliant','C2'],
      ['ultraautarkic','adj','Extremely autarkic','very self-reliant','C2'],
      ['commodificational','adj','Relating to commodification','commercialization-related,pertaining to','C1'],
      ['commodificationic','adj','Of or relating to commodification','commercialization-based,characteristic','C1'],
      ['commodificationous','adj','Full of commodification','commercialization-filled,abundant','C2'],
      ['commodificationful','adj','Full of commodification','commercialization-rich,abounding','C1'],
      ['commodificationless','adj','Without commodification','lacking,without','C1'],
      ['commodificationism','n','The ideology of commodification','commercialization ideology,doctrine','C2'],
      ['commodificationist','n','A person focused on commodification','commercialization specialist,advocate','C2'],
      ['commodificationise','v','To make into commodification','commercialization,convert','C2'],
      ['commodificationize','v','To make or become commodification','commercialization,transform','C2'],
      ['anticommodification','adj','Opposed to commodification','against,opposing','C2'],
      ['noncommodification','adj','Not involving commodification','without,lacking','C1'],
      ['precommodification','n','Before commodification','preceding,prior','C2'],
      ['postcommodification','n','After commodification','following,subsequent','C2'],
      ['subcommodification','n','A subdivision of commodification','subset,branch','C2'],
      ['multicommodification','adj','Involving many commodifications','multiple,several','C2'],
      ['intercommodification','adj','Between commodifications','cross,between','C2'],
      ['glocalizational','adj','Relating to glocalization','local adaptation-related,pertaining to','C1'],
      ['glocalizationic','adj','Of or relating to glocalization','local adaptation-based,characteristic','C1'],
      ['glocalizationous','adj','Full of glocalization','local adaptation-filled,abundant','C2'],
      ['glocalizationful','adj','Full of glocalization','local adaptation-rich,abounding','C1'],
      ['glocalizationless','adj','Without glocalization','lacking,without','C1'],
      ['glocalizationism','n','The ideology of glocalization','local adaptation ideology,doctrine','C2'],
      ['glocalizationist','n','A person focused on glocalization','local adaptation specialist,advocate','C2'],
      ['glocalizationise','v','To make into glocalization','local adaptation,convert','C2'],
      ['glocalizationize','v','To make or become glocalization','local adaptation,transform','C2'],
      ['antiglocalization','adj','Opposed to glocalization','against,opposing','C2'],
      ['nonglocalization','adj','Not involving glocalization','without,lacking','C1'],
      ['preglocalization','n','Before glocalization','preceding,prior','C2'],
      ['postglocalization','n','After glocalization','following,subsequent','C2'],
      ['subglocalization','n','A subdivision of glocalization','subset,branch','C2'],
      ['multiglocalization','adj','Involving many glocalizations','multiple,several','C2'],
      ['interglocalization','adj','Between glocalizations','cross,between','C2'],
      ['brain drainal','adj','Relating to brain drain','talent loss-related,pertaining to','B2'],
      ['brain drainic','adj','Of or relating to brain drain','talent loss-based,characteristic','B2'],
      ['brain drainous','adj','Full of brain drain','talent loss-filled,abundant','C1'],
      ['brain drainful','adj','Full of brain drain','talent loss-rich,abounding','B2'],
      ['brain drainless','adj','Without brain drain','lacking,without','B2'],
      ['brain drainism','n','The ideology of brain drain','talent loss ideology,doctrine','C1'],
      ['brain drainist','n','A person focused on brain drain','talent loss specialist,advocate','C1'],
      ['brain drainise','v','To make into brain drain','talent loss,convert','C1'],
      ['brain drainize','v','To make or become brain drain','talent loss,transform','C1'],
      ['antibrain drain','adj','Opposed to brain drain','against,opposing','C1'],
      ['nonbrain drain','adj','Not involving brain drain','without,lacking','B2'],
      ['prebrain drain','n','Before brain drain','preceding,prior','C1'],
      ['postbrain drain','n','After brain drain','following,subsequent','C1'],
      ['subbrain drain','n','A subdivision of brain drain','subset,branch','C1'],
      ['multibrain drain','adj','Involving many brain drains','multiple,several','C1'],
      ['interbrain drain','adj','Between brain drains','cross,between','C1'],
      ['cultural imperialism','n','Imposing culture on other countries','cultural dominance,Western influence','C1'],
      ['cultural imperialismal','adj','Relating to cultural imperialism','cultural dominance-related,pertaining to','C1'],
      ['cultural imperialismic','adj','Of or relating to cultural imperialism','cultural dominance-based,characteristic','C1'],
      ['cultural imperialismous','adj','Full of cultural imperialism','cultural dominance-filled,abundant','C2'],
      ['cultural imperialismful','adj','Full of cultural imperialism','cultural dominance-rich,abounding','C1'],
      ['cultural imperialismless','adj','Without cultural imperialism','lacking,without','C1'],
      ['cultural imperialismism','n','The ideology of cultural imperialism','cultural dominance ideology,doctrine','C2'],
      ['cultural imperialismist','n','A person focused on cultural imperialism','cultural dominance specialist,advocate','C2'],
      ['cultural imperialismise','v','To make into cultural imperialism','cultural dominance,convert','C2'],
      ['cultural imperialismize','v','To make or become cultural imperialism','cultural dominance,transform','C2'],
      ['anticultural imperialism','adj','Opposed to cultural imperialism','against,opposing','C2'],
      ['noncultural imperialism','adj','Not involving cultural imperialism','without,lacking','C1'],
      ['precultural imperialism','n','Before cultural imperialism','preceding,prior','C2'],
      ['postcultural imperialism','n','After cultural imperialism','following,subsequent','C2'],
      ['subcultural imperialism','n','A subdivision of cultural imperialism','subset,branch','C2'],
      ['multicultural imperialism','adj','Involving many cultural imperialisms','multiple,several','C2'],
      ['intercultural imperialism','adj','Between cultural imperialisms','cross,between','C2'],
      ['free tradeal','adj','Relating to free trade','open trade-related,pertaining to','B2'],
      ['free tradeic','adj','Of or relating to free trade','open trade-based,characteristic','B2'],
      ['free tradeous','adj','Full of free trade','open trade-filled,abundant','C1'],
      ['free tradeful','adj','Full of free trade','open trade-rich,abounding','B2'],
      ['free tradeless','adj','Without free trade','lacking,without','B2'],
      ['free tradeism','n','The ideology of free trade','open trade ideology,doctrine','C1'],
      ['free tradeist','n','A person focused on free trade','open trade specialist,advocate','C1'],
      ['free tradeise','v','To make into free trade','open trade,convert','C1'],
      ['free tradeize','v','To make or become free trade','open trade,transform','C1'],
      ['antifree trade','adj','Opposed to free trade','against,opposing','C1'],
      ['nonfree trade','adj','Not involving free trade','without,lacking','B2'],
      ['prefree trade','n','Before free trade','preceding,prior','C1'],
      ['postfree trade','n','After free trade','following,subsequent','C1'],
      ['subfree trade','n','A subdivision of free trade','subset,branch','C1'],
      ['multifree trade','adj','Involving many free trades','multiple,several','C1'],
      ['interfree trade','adj','Between free trades','cross,between','C1'],
      ['trade surplus','n','When exports exceed imports','positive balance,export surplus','B2'],
      ['trade surplusal','adj','Relating to trade surplus','positive balance-related,pertaining to','B2'],
      ['trade surplusic','adj','Of or relating to trade surplus','positive balance-based,characteristic','B2'],
      ['trade surplusous','adj','Full of trade surplus','positive balance-filled,abundant','C1'],
      ['trade surplusful','adj','Full of trade surplus','positive balance-rich,abounding','B2'],
      ['trade surplusless','adj','Without trade surplus','lacking,without','B2'],
      ['trade surplusism','n','The ideology of trade surplus','positive balance ideology,doctrine','C1'],
      ['trade surplusist','n','A person focused on trade surplus','positive balance specialist,advocate','C1'],
      ['trade surplusise','v','To make into trade surplus','positive balance,convert','C1'],
      ['trade surplusize','v','To make or become trade surplus','positive balance,transform','C1'],
      ['antitrade surplus','adj','Opposed to trade surplus','against,opposing','C1'],
      ['nontrade surplus','adj','Not involving trade surplus','without,lacking','B2'],
      ['pretrade surplus','n','Before trade surplus','preceding,prior','C1'],
      ['posttrade surplus','n','After trade surplus','following,subsequent','C1'],
      ['subtrade surplus','n','A subdivision of trade surplus','subset,branch','C1'],
      ['multitrade surplus','adj','Involving many trade surpluss','multiple,several','C1'],
      ['intertrade surplus','adj','Between trade surpluss','cross,between','C1'],
      ['supply chainal','adj','Relating to supply chain','production chain-related,pertaining to','B2'],
      ['supply chainic','adj','Of or relating to supply chain','production chain-based,characteristic','B2'],
      ['supply chainous','adj','Full of supply chain','production chain-filled,abundant','C1'],
      ['supply chainful','adj','Full of supply chain','production chain-rich,abounding','B2'],
      ['supply chainless','adj','Without supply chain','lacking,without','B2'],
      ['supply chainism','n','The ideology of supply chain','production chain ideology,doctrine','C1'],
      ['supply chainist','n','A person focused on supply chain','production chain specialist,advocate','C1'],
      ['supply chainise','v','To make into supply chain','production chain,convert','C1'],
      ['supply chainize','v','To make or become supply chain','production chain,transform','C1'],
      ['antisupply chain','adj','Opposed to supply chain','against,opposing','C1'],
      ['nonsupply chain','adj','Not involving supply chain','without,lacking','B2'],
      ['presupply chain','n','Before supply chain','preceding,prior','C1'],
      ['postsupply chain','n','After supply chain','following,subsequent','C1'],
      ['subsupply chain','n','A subdivision of supply chain','subset,branch','C1'],
      ['multisupply chain','adj','Involving many supply chains','multiple,several','C1'],
      ['intersupply chain','adj','Between supply chains','cross,between','C1'],
      ['foreign direct investment','n','Investment in another country','FDI,overseas investment','B2'],
      ['foreign direct investmental','adj','Relating to foreign direct investment','FDI-related,pertaining to','B2'],
      ['foreign direct investmentic','adj','Of or relating to foreign direct investment','FDI-based,characteristic','B2'],
      ['foreign direct investmentous','adj','Full of foreign direct investment','FDI-filled,abundant','C1'],
      ['foreign direct investmentful','adj','Full of foreign direct investment','FDI-rich,abounding','B2'],
      ['foreign direct investmentless','adj','Without foreign direct investment','lacking,without','B2'],
      ['foreign direct investmentism','n','The ideology of foreign direct investment','FDI ideology,doctrine','C1'],
      ['foreign direct investmentist','n','A person focused on foreign direct investment','FDI specialist,advocate','C1'],
      ['foreign direct investmentise','v','To make into foreign direct investment','FDI,convert','C1'],
      ['foreign direct investmentize','v','To make or become foreign direct investment','FDI,transform','C1'],
      ['antiforeign direct investment','adj','Opposed to foreign direct investment','against,opposing','C1'],
      ['nonforeign direct investment','adj','Not involving foreign direct investment','without,lacking','B2'],
      ['preforeign direct investment','n','Before foreign direct investment','preceding,prior','C1'],
      ['postforeign direct investment','n','After foreign direct investment','following,subsequent','C1'],
      ['subforeign direct investment','n','A subdivision of foreign direct investment','subset,branch','C1'],
      ['multiforeign direct investment','adj','Involving many foreign direct investments','multiple,several','C1'],
      ['interforeign direct investment','adj','Between foreign direct investments','cross,between','C1'],
      ['offshore','adj','Located or based in another country','overseas,foreign,abroad','B2'],
      ['offshorely','adv','In a offshore manner','overseas way','B2'],
      ['offshoreness','n','The quality of being offshore','overseas quality','B2'],
      ['offshoreity','n','The state of being offshore','overseas condition','C1'],
      ['unoffshore','adj','Not offshore','not overseas','B2'],
      ['inoffshore','adj','Not offshore','not overseas','C1'],
      ['nonoffshore','adj','Not offshore','not overseas','B2'],
      ['semioffshore','adj','Partially offshore','partly overseas','C1'],
      ['overoffshore','adj','Excessively offshore','too overseas','C1'],
      ['ultraoffshore','adj','Extremely offshore','very overseas','C1'],
      ['sweatshopic','adj','Of or relating to sweatshop','exploitative factory-based,characteristic','B2'],
      ['sweatshopous','adj','Full of sweatshop','exploitative factory-filled,abundant','C1'],
      ['sweatshopful','adj','Full of sweatshop','exploitative factory-rich,abounding','B2'],
      ['sweatshopless','adj','Without sweatshop','lacking,without','B2'],
      ['sweatshopism','n','The ideology of sweatshop','exploitative factory ideology,doctrine','C1'],
      ['sweatshopist','n','A person focused on sweatshop','exploitative factory specialist,advocate','C1'],
      ['sweatshopise','v','To make into sweatshop','exploitative factory,convert','C1'],
      ['sweatshopize','v','To make or become sweatshop','exploitative factory,transform','C1'],
      ['antisweatshop','adj','Opposed to sweatshop','against,opposing','C1'],
      ['nonsweatshop','adj','Not involving sweatshop','without,lacking','B2'],
      ['presweatshop','n','Before sweatshop','preceding,prior','C1'],
      ['postsweatshop','n','After sweatshop','following,subsequent','C1'],
      ['subsweatshop','n','A subdivision of sweatshop','subset,branch','C1'],
      ['multisweatshop','adj','Involving many sweatshops','multiple,several','C1'],
      ['intersweatshop','adj','Between sweatshops','cross,between','C1'],
      ['fair trade','n','Trade ensuring fair prices for producers','ethical trade,equitable commerce','B2'],
      ['fair tradeal','adj','Relating to fair trade','ethical trade-related,pertaining to','B2'],
      ['fair tradeic','adj','Of or relating to fair trade','ethical trade-based,characteristic','B2'],
      ['fair tradeous','adj','Full of fair trade','ethical trade-filled,abundant','C1'],
      ['fair tradeful','adj','Full of fair trade','ethical trade-rich,abounding','B2'],
      ['fair tradeless','adj','Without fair trade','lacking,without','B2'],
      ['fair tradeism','n','The ideology of fair trade','ethical trade ideology,doctrine','C1'],
      ['fair tradeist','n','A person focused on fair trade','ethical trade specialist,advocate','C1'],
      ['fair tradeise','v','To make into fair trade','ethical trade,convert','C1'],
      ['fair tradeize','v','To make or become fair trade','ethical trade,transform','C1'],
      ['antifair trade','adj','Opposed to fair trade','against,opposing','C1'],
      ['nonfair trade','adj','Not involving fair trade','without,lacking','B2'],
      ['prefair trade','n','Before fair trade','preceding,prior','C1'],
      ['postfair trade','n','After fair trade','following,subsequent','C1'],
      ['subfair trade','n','A subdivision of fair trade','subset,branch','C1'],
      ['multifair trade','adj','Involving many fair trades','multiple,several','C1'],
      ['interfair trade','adj','Between fair trades','cross,between','C1'],
      ['developing nation','n','A country with low economic output','third world,emerging economy','B2'],
      ['developing national','adj','Relating to developing nation','third world-related,pertaining to','B2'],
      ['developing nationic','adj','Of or relating to developing nation','third world-based,characteristic','B2'],
      ['developing nationous','adj','Full of developing nation','third world-filled,abundant','C1'],
      ['developing nationful','adj','Full of developing nation','third world-rich,abounding','B2'],
      ['developing nationless','adj','Without developing nation','lacking,without','B2'],
      ['developing nationism','n','The ideology of developing nation','third world ideology,doctrine','C1'],
      ['developing nationist','n','A person focused on developing nation','third world specialist,advocate','C1'],
      ['developing nationise','v','To make into developing nation','third world,convert','C1'],
      ['developing nationize','v','To make or become developing nation','third world,transform','C1'],
      ['antideveloping nation','adj','Opposed to developing nation','against,opposing','C1'],
      ['nondeveloping nation','adj','Not involving developing nation','without,lacking','B2'],
      ['predeveloping nation','n','Before developing nation','preceding,prior','C1'],
      ['postdeveloping nation','n','After developing nation','following,subsequent','C1'],
      ['subdeveloping nation','n','A subdivision of developing nation','subset,branch','C1'],
      ['multideveloping nation','adj','Involving many developing nations','multiple,several','C1'],
      ['interdeveloping nation','adj','Between developing nations','cross,between','C1'],
      ['decolonize','v','To free from colonial status','liberate,free,emancipate','C1'],
      ['decolonization','n','The act of decolonizing','liberate process','C1'],
      ['decolonizment','n','The result of decolonizing','liberate outcome','C1'],
      ['decolonizance','n','The state of decolonizing','liberate state','C1'],
      ['decolonizence','n','The quality of decolonizing','liberate quality','C1'],
      ['decolonizal','n','An act of decolonizing','liberate event','C2'],
      ['decolonizer','n','One who decolonizes','liberate person','C1'],
      ['decolonizor','n','One who decolonizes','liberate agent','C1'],
      ['decolonizee','n','One who is decolonized','liberate recipient','C2'],
      ['decolonizable','adj','Capable of being decolonized','liberate,possible','C2'],
      ['decolonizible','adj','Able to be decolonized','liberate,feasible','C2'],
      ['decolonizive','adj','Tending to decolonize','liberate,active','C1'],
      ['decolonizing','adj','Currently decolonizing','liberate,ongoing','C1'],
      ['decolonized','adj','Having been decolonized','liberate,completed','C1'],
      ['redecolonize','v','To decolonize again','liberate again,repeat','C1'],
      ['undecolonize','v','To reverse decolonizing','reverse,undo','C2'],
      ['overdecolonize','v','To decolonize excessively','excess,too much','C2'],
      ['underdecolonize','v','To decolonize insufficiently','insufficient,inadequate','C2'],
      ['misdecolonize','v','To decolonize incorrectly','wrongly,incorrectly','C2'],
      ['predecolonize','v','To decolonize beforehand','before,in advance','C2'],
      ['codecolonize','v','To decolonize together','jointly,together','C2'],
    ],
  },
  collocations: {}
};
