export const HTTP_STATUS_CODES = {
  SUCCESS: 200,
  CREATED: 201,
  ACCEPTED: 202,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  TOO_MANY_REQUEST: 429,
  TOO_MANY_REQUESTS: 429,
  PAYMENT_REQUIRED: 402,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503
};

export const CODES = {
  InvalidBody: 'InvalidBody',
  EmptyContentType: 'EmptyContentType',
  InvalidContentType: 'InvalidContentType',
  EmptyAuthorization: 'EmptyAuthorization',
  NotAuthorized: 'NotAuthorized',
  Forbidden: 'Forbidden',
  EmptyURC: 'EmptyURC',
  InvalidURC: 'InvalidURC',
  InvalidQueryParam: 'InvalidQueryParam',
  MissingUserId: 'MissingUserId',
  InvalidUserId: 'InvalidUserId',
  GenericErrorMessage: 'GenericErrorMessage',
  NotFound: 'NotFound',
  OpenAIError: 'OpenAIError',
  OpenAIQuotaExceeded: 'OpenAIQuotaExceeded',
  OpenAIInvalidRequest: 'OpenAIInvalidRequest',
  OpenAIRateLimit: 'OpenAIRateLimit',
  InvalidQuery: 'InvalidQuery',
  InvalidField: 'InvalidField',
  InvalidGeospatialQuery: 'InvalidGeospatialQuery',
  UserAlreadyExists: 'UserAlreadyExists',
  InvalidCredentials: 'InvalidCredentials',
  RefreshTokenRevoked: 'RefreshTokenRevoked',
  UsageLimitReached: 'UsageLimitReached',
  PremiumRequired: 'PremiumRequired',
  StripeError: 'StripeError',
  NotImplemented: 'NotImplemented'
};
