/**
 * Static list of all blog post slugs for sitemap generation and SSG.
 * Auto-generated from Supabase DB — 585 posts across 12 clusters.
 */

export interface BlogSlugEntry {
  slug: string;
  cluster: string;
  title: string;
}

export const blogSlugs: BlogSlugEntry[] = [
  /* SPEAKING (75) */
  { slug: 'answering-questions-about-social-media-in-ielts-speaking', cluster: 'speaking', title: 'Answering Questions About Social Media in IELTS Speaking' },
  { slug: 'best-ways-to-describe-your-hometown-in-ielts-speaking', cluster: 'speaking', title: 'Best Ways to Describe Your Hometown in IELTS Speaking' },
  { slug: 'discussing-animals-and-pets-in-ielts-speaking', cluster: 'speaking', title: 'Discussing Animals and Pets in IELTS Speaking' },
  { slug: 'discussing-birthdays-and-special-occasions-in-ielts-speaking', cluster: 'speaking', title: 'Discussing Birthdays and Special Occasions in IELTS Speaking' },
  { slug: 'discussing-education-and-learning-in-ielts-speaking', cluster: 'speaking', title: 'Discussing Education and Learning in IELTS Speaking' },
  { slug: 'discussing-news-and-media-in-ielts-speaking', cluster: 'speaking', title: 'Discussing News and Media in IELTS Speaking' },
  { slug: 'discussing-noise-and-quiet-places-in-ielts-speaking', cluster: 'speaking', title: 'Discussing Noise and Quiet Places in IELTS Speaking' },
  { slug: 'discussing-stars-celebrities-and-role-models', cluster: 'speaking', title: 'Discussing Stars Celebrities and Role Models' },
  { slug: 'discussing-transport-and-commuting-in-ielts-speaking', cluster: 'speaking', title: 'Discussing Transport and Commuting in IELTS Speaking' },
  { slug: 'discussing-water-and-rivers-in-ielts-speaking', cluster: 'speaking', title: 'Discussing Water and Rivers in IELTS Speaking' },
  { slug: 'how-to-answer-ielts-speaking-questions-about-travel', cluster: 'speaking', title: 'How to Answer IELTS Speaking Questions About Travel' },
  { slug: 'how-to-answer-questions-about-politeness-and-manners', cluster: 'speaking', title: 'How to Answer Questions About Politeness and Manners' },
  { slug: 'how-to-answer-questions-about-sleep-and-rest', cluster: 'speaking', title: 'How to Answer Questions About Sleep and Rest' },
  { slug: 'how-to-answer-questions-about-your-daily-routine', cluster: 'speaking', title: 'How to Answer Questions About Your Daily Routine' },
  { slug: 'how-to-avoid-hesitation-in-ielts-speaking', cluster: 'speaking', title: 'How to Avoid Hesitation in IELTS Speaking' },
  { slug: 'how-to-describe-a-crowded-place-you-visited', cluster: 'speaking', title: 'How to Describe a Crowded Place You Visited' },
  { slug: 'how-to-describe-a-difficult-decision-you-made', cluster: 'speaking', title: 'How to Describe a Difficult Decision You Made' },
  { slug: 'how-to-describe-a-festival-or-celebration', cluster: 'speaking', title: 'How to Describe a Festival or Celebration' },
  { slug: 'how-to-describe-a-historical-place-in-ielts-speaking', cluster: 'speaking', title: 'How to Describe a Historical Place in IELTS Speaking' },
  { slug: 'how-to-describe-a-memorable-event-in-ielts-speaking', cluster: 'speaking', title: 'How to Describe a Memorable Event in IELTS Speaking' },
  { slug: 'how-to-describe-a-place-you-have-visited', cluster: 'speaking', title: 'How to Describe a Place You Have Visited' },
  { slug: 'how-to-describe-your-favourite-food-in-ielts-speaking', cluster: 'speaking', title: 'How to Describe Your Favourite Food in IELTS Speaking' },
  { slug: 'how-to-discuss-advertisements-in-ielts-speaking', cluster: 'speaking', title: 'How to Discuss Advertisements in IELTS Speaking' },
  { slug: 'how-to-discuss-art-and-creativity-in-ielts-speaking', cluster: 'speaking', title: 'How to Discuss Art and Creativity in IELTS Speaking' },
  { slug: 'how-to-discuss-health-and-fitness-in-ielts-speaking', cluster: 'speaking', title: 'How to Discuss Health and Fitness in IELTS Speaking' },
  { slug: 'how-to-discuss-law-and-rules-in-ielts-speaking', cluster: 'speaking', title: 'How to Discuss Law and Rules in IELTS Speaking' },
  { slug: 'how-to-discuss-movies-and-tv-shows-in-ielts-speaking', cluster: 'speaking', title: 'How to Discuss Movies and TV Shows in IELTS Speaking' },
  { slug: 'how-to-discuss-music-and-entertainment-in-ielts-speaking', cluster: 'speaking', title: 'How to Discuss Music and Entertainment in IELTS Speaking' },
  { slug: 'how-to-discuss-patience-and-waiting-in-ielts-speaking', cluster: 'speaking', title: 'How to Discuss Patience and Waiting in IELTS Speaking' },
  { slug: 'how-to-end-your-answer-smoothly-in-ielts-speaking', cluster: 'speaking', title: 'How to End Your Answer Smoothly in IELTS Speaking' },
  { slug: 'how-to-give-extended-answers-in-ielts-speaking-part-3', cluster: 'speaking', title: 'How to Give Extended Answers in IELTS Speaking Part 3' },
  { slug: 'how-to-handle-difficult-questions-in-ielts-speaking', cluster: 'speaking', title: 'How to Handle Difficult Questions in IELTS Speaking' },
  { slug: 'how-to-handle-the-two-minute-talk-in-part-2', cluster: 'speaking', title: 'How to Handle the Two-Minute Talk in Part 2' },
  { slug: 'how-to-introduce-yourself-in-ielts-speaking-part-1', cluster: 'speaking', title: 'How to Introduce Yourself in IELTS Speaking Part 1' },
  { slug: 'how-to-paraphrase-in-ielts-speaking', cluster: 'speaking', title: 'How to Paraphrase in IELTS Speaking' },
  { slug: 'how-to-self-correct-without-losing-marks', cluster: 'speaking', title: 'How to Self-Correct Without Losing Marks' },
  { slug: 'how-to-stay-calm-during-ielts-speaking', cluster: 'speaking', title: 'How to Stay Calm During IELTS Speaking' },
  { slug: 'how-to-talk-about-colours-and-preferences', cluster: 'speaking', title: 'How to Talk About Colours and Preferences' },
  { slug: 'how-to-talk-about-cooking-in-ielts-speaking', cluster: 'speaking', title: 'How to Talk About Cooking in IELTS Speaking' },
  { slug: 'how-to-talk-about-gardens-and-nature', cluster: 'speaking', title: 'How to Talk About Gardens and Nature' },
  { slug: 'how-to-talk-about-money-and-spending-in-ielts-speaking', cluster: 'speaking', title: 'How to Talk About Money and Spending in IELTS Speaking' },
  { slug: 'how-to-talk-about-neighbours-and-community', cluster: 'speaking', title: 'How to Talk About Neighbours and Community' },
  { slug: 'how-to-talk-about-pollution-and-environment', cluster: 'speaking', title: 'How to Talk About Pollution and Environment' },
  { slug: 'how-to-talk-about-teamwork-in-ielts-speaking', cluster: 'speaking', title: 'How to Talk About Teamwork in IELTS Speaking' },
  { slug: 'how-to-talk-about-technology-in-ielts-speaking', cluster: 'speaking', title: 'How to Talk About Technology in IELTS Speaking' },
  { slug: 'how-to-talk-about-your-family-in-ielts-speaking', cluster: 'speaking', title: 'How to Talk About Your Family in IELTS Speaking' },
  { slug: 'how-to-talk-about-your-future-plans-in-ielts-speaking', cluster: 'speaking', title: 'How to Talk About Your Future Plans in IELTS Speaking' },
  { slug: 'how-to-use-linking-words-in-ielts-speaking', cluster: 'speaking', title: 'How to Use Linking Words in IELTS Speaking' },
  { slug: 'ielts-speaking-band-descriptors-explained', cluster: 'speaking', title: 'IELTS Speaking Band Descriptors Explained' },
  { slug: 'ielts-speaking-mistakes-that-lower-your-score', cluster: 'speaking', title: 'IELTS Speaking Mistakes That Lower Your Score' },
  { slug: 'ielts-speaking-part-1-work-and-studies-questions', cluster: 'speaking', title: 'IELTS Speaking Part 1 Work and Studies Questions' },
  { slug: 'ielts-speaking-part-2-describe-a-building-you-like', cluster: 'speaking', title: 'IELTS Speaking Part 2 Describe a Building You Like' },
  { slug: 'ielts-speaking-part-2-describe-a-gift-you-received', cluster: 'speaking', title: 'IELTS Speaking Part 2 Describe a Gift You Received' },
  { slug: 'ielts-speaking-part-2-describe-a-person-you-admire', cluster: 'speaking', title: 'IELTS Speaking Part 2 Describe a Person You Admire' },
  { slug: 'ielts-speaking-part-2-describe-a-photo-you-like', cluster: 'speaking', title: 'IELTS Speaking Part 2 Describe a Photo You Like' },
  { slug: 'ielts-speaking-part-2-describe-a-piece-of-good-news', cluster: 'speaking', title: 'IELTS Speaking Part 2 Describe a Piece of Good News' },
  { slug: 'ielts-speaking-part-2-describe-a-skill-you-learned', cluster: 'speaking', title: 'IELTS Speaking Part 2 Describe a Skill You Learned' },
  { slug: 'ielts-speaking-part-2-describe-a-time-you-helped-someone', cluster: 'speaking', title: 'IELTS Speaking Part 2 Describe a Time You Helped Someone' },
  { slug: 'ielts-speaking-part-2-describe-an-exciting-activity', cluster: 'speaking', title: 'IELTS Speaking Part 2 Describe an Exciting Activity' },
  { slug: 'ielts-speaking-part-3-society-and-culture-questions', cluster: 'speaking', title: 'IELTS Speaking Part 3 Society and Culture Questions' },
  { slug: 'ielts-speaking-part-3-technology-and-society', cluster: 'speaking', title: 'IELTS Speaking Part 3 Technology and Society' },
  { slug: 'ielts-speaking-topics-about-weather-and-seasons', cluster: 'speaking', title: 'IELTS Speaking Topics About Weather and Seasons' },
  { slug: 'improving-fluency-for-ielts-speaking', cluster: 'speaking', title: 'Improving Fluency for IELTS Speaking' },
  { slug: 'pronunciation-tips-for-ielts-speaking-band-7', cluster: 'speaking', title: 'Pronunciation Tips for IELTS Speaking Band 7' },
  { slug: 'talking-about-books-and-reading-in-ielts-speaking', cluster: 'speaking', title: 'Talking About Books and Reading in IELTS Speaking' },
  { slug: 'talking-about-childhood-memories-in-ielts-speaking', cluster: 'speaking', title: 'Talking About Childhood Memories in IELTS Speaking' },
  { slug: 'talking-about-clothes-and-fashion-in-ielts-speaking', cluster: 'speaking', title: 'Talking About Clothes and Fashion in IELTS Speaking' },
  { slug: 'talking-about-hobbies-and-leisure-in-ielts-speaking', cluster: 'speaking', title: 'Talking About Hobbies and Leisure in IELTS Speaking' },
  { slug: 'talking-about-maps-and-directions-in-ielts-speaking', cluster: 'speaking', title: 'Talking About Maps and Directions in IELTS Speaking' },
  { slug: 'talking-about-public-transport-in-ielts-speaking', cluster: 'speaking', title: 'Talking About Public Transport in IELTS Speaking' },
  { slug: 'talking-about-shopping-habits-in-ielts-speaking', cluster: 'speaking', title: 'Talking About Shopping Habits in IELTS Speaking' },
  { slug: 'talking-about-sports-and-exercise-in-ielts-speaking', cluster: 'speaking', title: 'Talking About Sports and Exercise in IELTS Speaking' },
  { slug: 'talking-about-volunteering-in-ielts-speaking', cluster: 'speaking', title: 'Talking About Volunteering in IELTS Speaking' },
  { slug: 'using-complex-grammar-in-ielts-speaking', cluster: 'speaking', title: 'Using Complex Grammar in IELTS Speaking' },
  { slug: 'using-idioms-naturally-in-ielts-speaking', cluster: 'speaking', title: 'Using Idioms Naturally in IELTS Speaking' },
  /* WRITING (75) */
  { slug: 'common-ielts-writing-mistakes-and-how-to-fix-them', cluster: 'writing', title: 'Common IELTS Writing Mistakes and How to Fix Them' },
  { slug: 'how-to-achieve-coherence-and-cohesion-in-ielts-writing', cluster: 'writing', title: 'How to Achieve Coherence and Cohesion in IELTS Writing' },
  { slug: 'how-to-avoid-repetition-in-ielts-writing', cluster: 'writing', title: 'How to Avoid Repetition in IELTS Writing' },
  { slug: 'how-to-compare-data-in-ielts-writing-task-1', cluster: 'writing', title: 'How to Compare Data in IELTS Writing Task 1' },
  { slug: 'how-to-describe-a-line-graph-in-ielts-writing-task-1', cluster: 'writing', title: 'How to Describe a Line Graph in IELTS Writing Task 1' },
  { slug: 'how-to-describe-a-table-in-ielts-writing-task-1', cluster: 'writing', title: 'How to Describe a Table in IELTS Writing Task 1' },
  { slug: 'how-to-develop-ideas-fully-in-ielts-task-2', cluster: 'writing', title: 'How to Develop Ideas Fully in IELTS Task 2' },
  { slug: 'how-to-discuss-cultural-topics-in-ielts-writing', cluster: 'writing', title: 'How to Discuss Cultural Topics in IELTS Writing' },
  { slug: 'how-to-discuss-health-topics-in-ielts-writing', cluster: 'writing', title: 'How to Discuss Health Topics in IELTS Writing' },
  { slug: 'how-to-handle-abstract-topics-in-ielts-writing', cluster: 'writing', title: 'How to Handle Abstract Topics in IELTS Writing' },
  { slug: 'how-to-handle-double-graph-questions-in-ielts-task-1', cluster: 'writing', title: 'How to Handle Double Graph Questions in IELTS Task 1' },
  { slug: 'how-to-improve-your-ielts-writing-band-score', cluster: 'writing', title: 'How to Improve Your IELTS Writing Band Score' },
  { slug: 'how-to-manage-time-in-ielts-writing', cluster: 'writing', title: 'How to Manage Time in IELTS Writing' },
  { slug: 'how-to-organise-paragraphs-in-ielts-task-2', cluster: 'writing', title: 'How to Organise Paragraphs in IELTS Task 2' },
  { slug: 'how-to-paraphrase-the-question-in-ielts-writing', cluster: 'writing', title: 'How to Paraphrase the Question in IELTS Writing' },
  { slug: 'how-to-plan-your-essay-before-writing-in-ielts', cluster: 'writing', title: 'How to Plan Your Essay Before Writing in IELTS' },
  { slug: 'how-to-present-statistics-in-ielts-writing-task-1', cluster: 'writing', title: 'How to Present Statistics in IELTS Writing Task 1' },
  { slug: 'how-to-proofread-your-ielts-essay-quickly', cluster: 'writing', title: 'How to Proofread Your IELTS Essay Quickly' },
  { slug: 'how-to-use-conditional-sentences-in-ielts-writing', cluster: 'writing', title: 'How to Use Conditional Sentences in IELTS Writing' },
  { slug: 'how-to-use-examples-effectively-in-ielts-writing', cluster: 'writing', title: 'How to Use Examples Effectively in IELTS Writing' },
  { slug: 'how-to-use-formal-register-in-ielts-academic-writing', cluster: 'writing', title: 'How to Use Formal Register in IELTS Academic Writing' },
  { slug: 'how-to-use-hedging-language-in-ielts-writing', cluster: 'writing', title: 'How to Use Hedging Language in IELTS Writing' },
  { slug: 'how-to-use-passive-voice-correctly-in-ielts-writing', cluster: 'writing', title: 'How to Use Passive Voice Correctly in IELTS Writing' },
  { slug: 'how-to-write-a-balanced-argument-in-ielts-task-2', cluster: 'writing', title: 'How to Write a Balanced Argument in IELTS Task 2' },
  { slug: 'how-to-write-a-direct-question-essay-for-ielts', cluster: 'writing', title: 'How to Write a Direct Question Essay for IELTS' },
  { slug: 'how-to-write-a-discussion-essay-for-ielts', cluster: 'writing', title: 'How to Write a Discussion Essay for IELTS' },
  { slug: 'how-to-write-a-formal-letter-for-ielts-general-training', cluster: 'writing', title: 'How to Write a Formal Letter for IELTS General Training' },
  { slug: 'how-to-write-a-problem-solution-essay-for-ielts', cluster: 'writing', title: 'How to Write a Problem Solution Essay for IELTS' },
  { slug: 'how-to-write-a-strong-conclusion-for-ielts-task-2', cluster: 'writing', title: 'How to Write a Strong Conclusion for IELTS Task 2' },
  { slug: 'how-to-write-about-animal-rights-in-ielts', cluster: 'writing', title: 'How to Write About Animal Rights in IELTS' },
  { slug: 'how-to-write-about-food-and-diet-in-ielts-task-2', cluster: 'writing', title: 'How to Write About Food and Diet in IELTS Task 2' },
  { slug: 'how-to-write-about-government-and-policy-in-ielts', cluster: 'writing', title: 'How to Write About Government and Policy in IELTS' },
  { slug: 'how-to-write-about-housing-and-urban-development', cluster: 'writing', title: 'How to Write About Housing and Urban Development' },
  { slug: 'how-to-write-about-language-and-communication-in-ielts', cluster: 'writing', title: 'How to Write About Language and Communication in IELTS' },
  { slug: 'how-to-write-about-poverty-and-inequality-in-ielts', cluster: 'writing', title: 'How to Write About Poverty and Inequality in IELTS' },
  { slug: 'how-to-write-about-technology-topics-in-ielts', cluster: 'writing', title: 'How to Write About Technology Topics in IELTS' },
  { slug: 'how-to-write-an-ielts-general-training-letter', cluster: 'writing', title: 'How to Write an IELTS General Training Letter' },
  { slug: 'how-to-write-an-ielts-task-2-essay-introduction', cluster: 'writing', title: 'How to Write an IELTS Task 2 Essay Introduction' },
  { slug: 'how-to-write-an-informal-letter-for-ielts-general', cluster: 'writing', title: 'How to Write an Informal Letter for IELTS General' },
  { slug: 'ielts-writing-common-grammatical-errors-to-avoid', cluster: 'writing', title: 'IELTS Writing Common Grammatical Errors to Avoid' },
  { slug: 'ielts-writing-scoring-criteria-breakdown', cluster: 'writing', title: 'IELTS Writing Scoring Criteria Breakdown' },
  { slug: 'ielts-writing-task-1-academic-bar-chart-description', cluster: 'writing', title: 'IELTS Writing Task 1 Academic Bar Chart Description' },
  { slug: 'ielts-writing-task-1-comparing-two-maps-over-time', cluster: 'writing', title: 'IELTS Writing Task 1 Comparing Two Maps Over Time' },
  { slug: 'ielts-writing-task-1-flow-chart-description', cluster: 'writing', title: 'IELTS Writing Task 1 Flow Chart Description' },
  { slug: 'ielts-writing-task-1-general-semi-formal-letter', cluster: 'writing', title: 'IELTS Writing Task 1 General Semi-Formal Letter' },
  { slug: 'ielts-writing-task-1-map-description-strategy', cluster: 'writing', title: 'IELTS Writing Task 1 Map Description Strategy' },
  { slug: 'ielts-writing-task-1-mixed-chart-description', cluster: 'writing', title: 'IELTS Writing Task 1 Mixed Chart Description' },
  { slug: 'ielts-writing-task-1-natural-process-description', cluster: 'writing', title: 'IELTS Writing Task 1 Natural Process Description' },
  { slug: 'ielts-writing-task-1-process-diagram-explanation', cluster: 'writing', title: 'IELTS Writing Task 1 Process Diagram Explanation' },
  { slug: 'ielts-writing-task-2-advantages-and-disadvantages-essay', cluster: 'writing', title: 'IELTS Writing Task 2 Advantages and Disadvantages Essay' },
  { slug: 'ielts-writing-task-2-agree-or-disagree-strategy', cluster: 'writing', title: 'IELTS Writing Task 2 Agree or Disagree Strategy' },
  { slug: 'ielts-writing-task-2-arts-and-culture-topics', cluster: 'writing', title: 'IELTS Writing Task 2 Arts and Culture Topics' },
  { slug: 'ielts-writing-task-2-children-and-parenting-topics', cluster: 'writing', title: 'IELTS Writing Task 2 Children and Parenting Topics' },
  { slug: 'ielts-writing-task-2-crime-and-punishment-topics', cluster: 'writing', title: 'IELTS Writing Task 2 Crime and Punishment Topics' },
  { slug: 'ielts-writing-task-2-environment-and-climate-topics', cluster: 'writing', title: 'IELTS Writing Task 2 Environment and Climate Topics' },
  { slug: 'ielts-writing-task-2-gender-equality-topics', cluster: 'writing', title: 'IELTS Writing Task 2 Gender Equality Topics' },
  { slug: 'ielts-writing-task-2-globalisation-essay-ideas', cluster: 'writing', title: 'IELTS Writing Task 2 Globalisation Essay Ideas' },
  { slug: 'ielts-writing-task-2-happiness-and-life-satisfaction', cluster: 'writing', title: 'IELTS Writing Task 2 Happiness and Life Satisfaction' },
  { slug: 'ielts-writing-task-2-immigration-topics', cluster: 'writing', title: 'IELTS Writing Task 2 Immigration Topics' },
  { slug: 'ielts-writing-task-2-media-and-advertising-topics', cluster: 'writing', title: 'IELTS Writing Task 2 Media and Advertising Topics' },
  { slug: 'ielts-writing-task-2-opinion-essay-structure', cluster: 'writing', title: 'IELTS Writing Task 2 Opinion Essay Structure' },
  { slug: 'ielts-writing-task-2-science-and-research-topics', cluster: 'writing', title: 'IELTS Writing Task 2 Science and Research Topics' },
  { slug: 'ielts-writing-task-2-social-media-topics', cluster: 'writing', title: 'IELTS Writing Task 2 Social Media Topics' },
  { slug: 'ielts-writing-task-2-space-exploration-topics', cluster: 'writing', title: 'IELTS Writing Task 2 Space Exploration Topics' },
  { slug: 'ielts-writing-task-2-sports-and-competition-topics', cluster: 'writing', title: 'IELTS Writing Task 2 Sports and Competition Topics' },
  { slug: 'ielts-writing-task-2-topics-about-education', cluster: 'writing', title: 'IELTS Writing Task 2 Topics About Education' },
  { slug: 'ielts-writing-task-2-topics-about-work-and-employment', cluster: 'writing', title: 'IELTS Writing Task 2 Topics About Work and Employment' },
  { slug: 'ielts-writing-task-2-tourism-and-travel-topics', cluster: 'writing', title: 'IELTS Writing Task 2 Tourism and Travel Topics' },
  { slug: 'ielts-writing-task-2-transport-and-infrastructure-topics', cluster: 'writing', title: 'IELTS Writing Task 2 Transport and Infrastructure Topics' },
  { slug: 'ielts-writing-task-2-two-part-question-strategy', cluster: 'writing', title: 'IELTS Writing Task 2 Two-Part Question Strategy' },
  { slug: 'ielts-writing-vocabulary-for-band-7-and-above', cluster: 'writing', title: 'IELTS Writing Vocabulary for Band 7 and Above' },
  { slug: 'understanding-ielts-writing-band-descriptors', cluster: 'writing', title: 'Understanding IELTS Writing Band Descriptors' },
  { slug: 'using-cohesive-devices-in-ielts-writing', cluster: 'writing', title: 'Using Cohesive Devices in IELTS Writing' },
  { slug: 'using-complex-sentences-in-ielts-writing', cluster: 'writing', title: 'Using Complex Sentences in IELTS Writing' },
  { slug: 'writing-about-pie-charts-in-ielts-academic-task-1', cluster: 'writing', title: 'Writing About Pie Charts in IELTS Academic Task 1' },
  /* READING (60) */
  { slug: 'how-to-answer-summary-completion-in-ielts-reading', cluster: 'reading', title: 'How to Answer Summary Completion in IELTS Reading' },
  { slug: 'how-to-answer-yes-no-not-given-in-ielts-reading', cluster: 'reading', title: 'How to Answer Yes No Not Given in IELTS Reading' },
  { slug: 'how-to-approach-the-hardest-reading-passage', cluster: 'reading', title: 'How to Approach the Hardest Reading Passage' },
  { slug: 'how-to-avoid-common-traps-in-ielts-reading', cluster: 'reading', title: 'How to Avoid Common Traps in IELTS Reading' },
  { slug: 'how-to-build-ielts-reading-vocabulary', cluster: 'reading', title: 'How to Build IELTS Reading Vocabulary' },
  { slug: 'how-to-build-reading-stamina-for-ielts', cluster: 'reading', title: 'How to Build Reading Stamina for IELTS' },
  { slug: 'how-to-deal-with-long-passages-in-ielts-reading', cluster: 'reading', title: 'How to Deal With Long Passages in IELTS Reading' },
  { slug: 'how-to-handle-biology-and-nature-passages-in-ielts-reading', cluster: 'reading', title: 'How to Handle Biology and Nature Passages in IELTS Reading' },
  { slug: 'how-to-handle-classification-questions-in-ielts-reading', cluster: 'reading', title: 'How to Handle Classification Questions in IELTS Reading' },
  { slug: 'how-to-handle-diagram-labelling-in-ielts-reading', cluster: 'reading', title: 'How to Handle Diagram Labelling in IELTS Reading' },
  { slug: 'how-to-handle-multiple-choice-in-ielts-reading', cluster: 'reading', title: 'How to Handle Multiple Choice in IELTS Reading' },
  { slug: 'how-to-handle-negative-statements-in-ielts-reading', cluster: 'reading', title: 'How to Handle Negative Statements in IELTS Reading' },
  { slug: 'how-to-handle-paraphrase-in-ielts-reading', cluster: 'reading', title: 'How to Handle Paraphrase in IELTS Reading' },
  { slug: 'how-to-handle-two-correct-looking-answers-in-ielts-reading', cluster: 'reading', title: 'How to Handle Two Correct-Looking Answers in IELTS Reading' },
  { slug: 'how-to-handle-unfamiliar-vocabulary-in-ielts-reading', cluster: 'reading', title: 'How to Handle Unfamiliar Vocabulary in IELTS Reading' },
  { slug: 'how-to-identify-keywords-in-ielts-reading-questions', cluster: 'reading', title: 'How to Identify Keywords in IELTS Reading Questions' },
  { slug: 'how-to-improve-comprehension-for-ielts-reading', cluster: 'reading', title: 'How to Improve Comprehension for IELTS Reading' },
  { slug: 'how-to-improve-reading-speed-for-ielts', cluster: 'reading', title: 'How to Improve Reading Speed for IELTS' },
  { slug: 'how-to-manage-time-in-ielts-reading', cluster: 'reading', title: 'How to Manage Time in IELTS Reading' },
  { slug: 'how-to-practise-active-reading-for-ielts', cluster: 'reading', title: 'How to Practise Active Reading for IELTS' },
  { slug: 'how-to-practise-ielts-reading-at-home', cluster: 'reading', title: 'How to Practise IELTS Reading at Home' },
  { slug: 'how-to-read-academic-passages-faster-for-ielts', cluster: 'reading', title: 'How to Read Academic Passages Faster for IELTS' },
  { slug: 'how-to-read-economics-and-business-passages-for-ielts', cluster: 'reading', title: 'How to Read Economics and Business Passages for IELTS' },
  { slug: 'how-to-read-efficiently-under-exam-pressure', cluster: 'reading', title: 'How to Read Efficiently Under Exam Pressure' },
  { slug: 'how-to-read-graphs-and-visuals-in-ielts-reading', cluster: 'reading', title: 'How to Read Graphs and Visuals in IELTS Reading' },
  { slug: 'how-to-score-band-8-in-ielts-reading', cluster: 'reading', title: 'How to Score Band 8 in IELTS Reading' },
  { slug: 'how-to-skim-and-scan-effectively-in-ielts-reading', cluster: 'reading', title: 'How to Skim and Scan Effectively in IELTS Reading' },
  { slug: 'how-to-transfer-answers-to-the-answer-sheet', cluster: 'reading', title: 'How to Transfer Answers to the Answer Sheet' },
  { slug: 'how-to-understand-complex-sentences-in-ielts-reading', cluster: 'reading', title: 'How to Understand Complex Sentences in IELTS Reading' },
  { slug: 'how-to-use-context-clues-in-ielts-reading', cluster: 'reading', title: 'How to Use Context Clues in IELTS Reading' },
  { slug: 'ielts-reading-academic-vs-general-training-differences', cluster: 'reading', title: 'IELTS Reading Academic vs General Training Differences' },
  { slug: 'ielts-reading-annotation-techniques-that-work', cluster: 'reading', title: 'IELTS Reading Annotation Techniques That Work' },
  { slug: 'ielts-reading-double-passage-strategy', cluster: 'reading', title: 'IELTS Reading Double Passage Strategy' },
  { slug: 'ielts-reading-finding-the-writers-opinion', cluster: 'reading', title: 'IELTS Reading Finding the Writers Opinion' },
  { slug: 'ielts-reading-flow-chart-completion-strategy', cluster: 'reading', title: 'IELTS Reading Flow Chart Completion Strategy' },
  { slug: 'ielts-reading-general-training-section-strategy', cluster: 'reading', title: 'IELTS Reading General Training Section Strategy' },
  { slug: 'ielts-reading-global-vs-detail-questions', cluster: 'reading', title: 'IELTS Reading Global vs Detail Questions' },
  { slug: 'ielts-reading-inference-questions-strategy', cluster: 'reading', title: 'IELTS Reading Inference Questions Strategy' },
  { slug: 'ielts-reading-list-selection-questions-strategy', cluster: 'reading', title: 'IELTS Reading List Selection Questions Strategy' },
  { slug: 'ielts-reading-locating-information-questions-tips', cluster: 'reading', title: 'IELTS Reading Locating Information Questions Tips' },
  { slug: 'ielts-reading-matching-features-strategy', cluster: 'reading', title: 'IELTS Reading Matching Features Strategy' },
  { slug: 'ielts-reading-matching-headings-tips', cluster: 'reading', title: 'IELTS Reading Matching Headings Tips' },
  { slug: 'ielts-reading-matching-information-questions', cluster: 'reading', title: 'IELTS Reading Matching Information Questions' },
  { slug: 'ielts-reading-matching-sentence-endings-tips', cluster: 'reading', title: 'IELTS Reading Matching Sentence Endings Tips' },
  { slug: 'ielts-reading-note-completion-tips', cluster: 'reading', title: 'IELTS Reading Note Completion Tips' },
  { slug: 'ielts-reading-paragraph-matching-techniques', cluster: 'reading', title: 'IELTS Reading Paragraph Matching Techniques' },
  { slug: 'ielts-reading-passage-topics-you-should-know', cluster: 'reading', title: 'IELTS Reading Passage Topics You Should Know' },
  { slug: 'ielts-reading-practice-with-scientific-passages', cluster: 'reading', title: 'IELTS Reading Practice With Scientific Passages' },
  { slug: 'ielts-reading-psychology-and-behaviour-passages', cluster: 'reading', title: 'IELTS Reading Psychology and Behaviour Passages' },
  { slug: 'ielts-reading-question-order-and-passage-navigation', cluster: 'reading', title: 'IELTS Reading Question Order and Passage Navigation' },
  { slug: 'ielts-reading-sentence-completion-strategy', cluster: 'reading', title: 'IELTS Reading Sentence Completion Strategy' },
  { slug: 'ielts-reading-short-answer-questions-strategy', cluster: 'reading', title: 'IELTS Reading Short Answer Questions Strategy' },
  { slug: 'ielts-reading-strategies-for-band-7-plus', cluster: 'reading', title: 'IELTS Reading Strategies for Band 7 Plus' },
  { slug: 'ielts-reading-strategies-for-different-question-types', cluster: 'reading', title: 'IELTS Reading Strategies for Different Question Types' },
  { slug: 'ielts-reading-strategies-for-history-and-archaeology-passages', cluster: 'reading', title: 'IELTS Reading Strategies for History and Archaeology Passages' },
  { slug: 'ielts-reading-table-completion-tips', cluster: 'reading', title: 'IELTS Reading Table Completion Tips' },
  { slug: 'ielts-reading-test-format-and-timing-guide', cluster: 'reading', title: 'IELTS Reading Test Format and Timing Guide' },
  { slug: 'ielts-reading-tips-for-non-native-english-speakers', cluster: 'reading', title: 'IELTS Reading Tips for Non-Native English Speakers' },
  { slug: 'ielts-reading-tips-for-the-final-ten-minutes', cluster: 'reading', title: 'IELTS Reading Tips for the Final Ten Minutes' },
  { slug: 'ielts-reading-true-false-not-given-strategy', cluster: 'reading', title: 'IELTS Reading True False Not Given Strategy' },
  /* LISTENING (55) */
  { slug: 'how-to-answer-map-labelling-in-ielts-listening', cluster: 'listening', title: 'How to Answer Map Labelling in IELTS Listening' },
  { slug: 'how-to-answer-sentence-completion-in-ielts-listening', cluster: 'listening', title: 'How to Answer Sentence Completion in IELTS Listening' },
  { slug: 'how-to-build-listening-skills-with-podcasts-for-ielts', cluster: 'listening', title: 'How to Build Listening Skills With Podcasts for IELTS' },
  { slug: 'how-to-handle-conversations-with-multiple-speakers', cluster: 'listening', title: 'How to Handle Conversations With Multiple Speakers' },
  { slug: 'how-to-handle-different-accents-in-ielts-listening', cluster: 'listening', title: 'How to Handle Different Accents in IELTS Listening' },
  { slug: 'how-to-handle-fast-speakers-in-ielts-listening', cluster: 'listening', title: 'How to Handle Fast Speakers in IELTS Listening' },
  { slug: 'how-to-handle-ielts-listening-section-3-discussions', cluster: 'listening', title: 'How to Handle IELTS Listening Section 3 Discussions' },
  { slug: 'how-to-handle-ielts-listening-under-exam-pressure', cluster: 'listening', title: 'How to Handle IELTS Listening Under Exam Pressure' },
  { slug: 'how-to-handle-ielts-listening-when-you-miss-an-answer', cluster: 'listening', title: 'How to Handle IELTS Listening When You Miss an Answer' },
  { slug: 'how-to-handle-matching-questions-in-ielts-listening', cluster: 'listening', title: 'How to Handle Matching Questions in IELTS Listening' },
  { slug: 'how-to-handle-note-completion-in-ielts-listening', cluster: 'listening', title: 'How to Handle Note Completion in IELTS Listening' },
  { slug: 'how-to-handle-technical-vocabulary-in-ielts-listening', cluster: 'listening', title: 'How to Handle Technical Vocabulary in IELTS Listening' },
  { slug: 'how-to-improve-concentration-during-ielts-listening', cluster: 'listening', title: 'How to Improve Concentration During IELTS Listening' },
  { slug: 'how-to-improve-listening-comprehension-for-ielts', cluster: 'listening', title: 'How to Improve Listening Comprehension for IELTS' },
  { slug: 'how-to-improve-your-ielts-listening-score', cluster: 'listening', title: 'How to Improve Your IELTS Listening Score' },
  { slug: 'how-to-listen-for-specific-information-in-ielts', cluster: 'listening', title: 'How to Listen for Specific Information in IELTS' },
  { slug: 'how-to-practise-ielts-listening-at-home', cluster: 'listening', title: 'How to Practise IELTS Listening at Home' },
  { slug: 'how-to-predict-answers-in-ielts-listening', cluster: 'listening', title: 'How to Predict Answers in IELTS Listening' },
  { slug: 'how-to-prepare-for-ielts-listening-in-two-weeks', cluster: 'listening', title: 'How to Prepare for IELTS Listening in Two Weeks' },
  { slug: 'how-to-prepare-for-ielts-listening-section-1', cluster: 'listening', title: 'How to Prepare for IELTS Listening Section 1' },
  { slug: 'how-to-recognise-distractors-in-ielts-listening', cluster: 'listening', title: 'How to Recognise Distractors in IELTS Listening' },
  { slug: 'how-to-score-band-8-or-higher-in-ielts-listening', cluster: 'listening', title: 'How to Score Band 8 or Higher in IELTS Listening' },
  { slug: 'how-to-stay-focused-during-a-30-minute-listening-test', cluster: 'listening', title: 'How to Stay Focused During a 30-Minute Listening Test' },
  { slug: 'how-to-take-notes-while-listening-in-ielts', cluster: 'listening', title: 'How to Take Notes While Listening in IELTS' },
  { slug: 'how-to-transfer-answers-accurately-in-ielts-listening', cluster: 'listening', title: 'How to Transfer Answers Accurately in IELTS Listening' },
  { slug: 'how-to-understand-connected-speech-in-ielts-listening', cluster: 'listening', title: 'How to Understand Connected Speech in IELTS Listening' },
  { slug: 'how-to-use-process-of-elimination-in-ielts-listening', cluster: 'listening', title: 'How to Use Process of Elimination in IELTS Listening' },
  { slug: 'how-to-use-the-30-seconds-preview-time', cluster: 'listening', title: 'How to Use the 30 Seconds Preview Time' },
  { slug: 'ielts-listening-academic-vs-general-differences', cluster: 'listening', title: 'IELTS Listening Academic vs General Differences' },
  { slug: 'ielts-listening-classification-questions-tips', cluster: 'listening', title: 'IELTS Listening Classification Questions Tips' },
  { slug: 'ielts-listening-common-mistakes-and-how-to-avoid-them', cluster: 'listening', title: 'IELTS Listening Common Mistakes and How to Avoid Them' },
  { slug: 'ielts-listening-flow-chart-completion-strategy', cluster: 'listening', title: 'IELTS Listening Flow Chart Completion Strategy' },
  { slug: 'ielts-listening-form-completion-tips', cluster: 'listening', title: 'IELTS Listening Form Completion Tips' },
  { slug: 'ielts-listening-gap-fill-strategies', cluster: 'listening', title: 'IELTS Listening Gap Fill Strategies' },
  { slug: 'ielts-listening-identifying-opinion-vs-fact', cluster: 'listening', title: 'IELTS Listening Identifying Opinion vs Fact' },
  { slug: 'ielts-listening-multiple-choice-question-strategy', cluster: 'listening', title: 'IELTS Listening Multiple Choice Question Strategy' },
  { slug: 'ielts-listening-number-and-date-questions', cluster: 'listening', title: 'IELTS Listening Number and Date Questions' },
  { slug: 'ielts-listening-paraphrase-recognition-skills', cluster: 'listening', title: 'IELTS Listening Paraphrase Recognition Skills' },
  { slug: 'ielts-listening-picking-up-key-details-strategy', cluster: 'listening', title: 'IELTS Listening Picking Up Key Details Strategy' },
  { slug: 'ielts-listening-plan-and-diagram-labelling', cluster: 'listening', title: 'IELTS Listening Plan and Diagram Labelling' },
  { slug: 'ielts-listening-practice-with-news-broadcasts', cluster: 'listening', title: 'IELTS Listening Practice With News Broadcasts' },
  { slug: 'ielts-listening-section-2-monologue-strategy', cluster: 'listening', title: 'IELTS Listening Section 2 Monologue Strategy' },
  { slug: 'ielts-listening-section-4-academic-lecture-tips', cluster: 'listening', title: 'IELTS Listening Section 4 Academic Lecture Tips' },
  { slug: 'ielts-listening-section-transitions-and-cues', cluster: 'listening', title: 'IELTS Listening Section Transitions and Cues' },
  { slug: 'ielts-listening-short-answer-questions-tips', cluster: 'listening', title: 'IELTS Listening Short Answer Questions Tips' },
  { slug: 'ielts-listening-signpost-words-and-phrases', cluster: 'listening', title: 'IELTS Listening Signpost Words and Phrases' },
  { slug: 'ielts-listening-spelling-mistakes-to-avoid', cluster: 'listening', title: 'IELTS Listening Spelling Mistakes to Avoid' },
  { slug: 'ielts-listening-strategies-for-band-7-plus', cluster: 'listening', title: 'IELTS Listening Strategies for Band 7 Plus' },
  { slug: 'ielts-listening-strategies-for-different-question-formats', cluster: 'listening', title: 'IELTS Listening Strategies for Different Question Formats' },
  { slug: 'ielts-listening-summary-completion-tips', cluster: 'listening', title: 'IELTS Listening Summary Completion Tips' },
  { slug: 'ielts-listening-table-completion-strategy', cluster: 'listening', title: 'IELTS Listening Table Completion Strategy' },
  { slug: 'ielts-listening-tips-for-test-day', cluster: 'listening', title: 'IELTS Listening Tips for Test Day' },
  { slug: 'ielts-listening-understanding-tone-and-attitude', cluster: 'listening', title: 'IELTS Listening Understanding Tone and Attitude' },
  { slug: 'ielts-listening-vocabulary-for-common-topics', cluster: 'listening', title: 'IELTS Listening Vocabulary for Common Topics' },
  { slug: 'ielts-listening-word-limit-rules-explained', cluster: 'listening', title: 'IELTS Listening Word Limit Rules Explained' },
  /* VOCABULARY (55) */
  { slug: 'academic-word-list-for-ielts-reading-and-writing', cluster: 'vocabulary', title: 'Academic Word List for IELTS Reading and Writing' },
  { slug: 'architecture-and-buildings-vocabulary-for-ielts', cluster: 'vocabulary', title: 'Architecture and Buildings Vocabulary for IELTS' },
  { slug: 'arts-and-culture-vocabulary-for-ielts', cluster: 'vocabulary', title: 'Arts and Culture Vocabulary for IELTS' },
  { slug: 'communication-and-language-vocabulary-for-ielts', cluster: 'vocabulary', title: 'Communication and Language Vocabulary for IELTS' },
  { slug: 'crime-and-justice-vocabulary-for-ielts', cluster: 'vocabulary', title: 'Crime and Justice Vocabulary for IELTS' },
  { slug: 'environment-and-climate-change-vocabulary-for-ielts', cluster: 'vocabulary', title: 'Environment and Climate Change Vocabulary for IELTS' },
  { slug: 'essential-ielts-vocabulary-for-band-7-speaking', cluster: 'vocabulary', title: 'Essential IELTS Vocabulary for Band 7 Speaking' },
  { slug: 'family-and-relationships-vocabulary-for-ielts', cluster: 'vocabulary', title: 'Family and Relationships Vocabulary for IELTS' },
  { slug: 'food-and-nutrition-vocabulary-for-ielts', cluster: 'vocabulary', title: 'Food and Nutrition Vocabulary for IELTS' },
  { slug: 'happiness-and-wellbeing-vocabulary-for-ielts', cluster: 'vocabulary', title: 'Happiness and Wellbeing Vocabulary for IELTS' },
  { slug: 'how-to-avoid-overusing-common-ielts-vocabulary', cluster: 'vocabulary', title: 'How to Avoid Overusing Common IELTS Vocabulary' },
  { slug: 'how-to-avoid-vocabulary-errors-in-ielts-writing', cluster: 'vocabulary', title: 'How to Avoid Vocabulary Errors in IELTS Writing' },
  { slug: 'how-to-build-a-personal-ielts-vocabulary-notebook', cluster: 'vocabulary', title: 'How to Build a Personal IELTS Vocabulary Notebook' },
  { slug: 'how-to-expand-your-ielts-vocabulary-quickly', cluster: 'vocabulary', title: 'How to Expand Your IELTS Vocabulary Quickly' },
  { slug: 'how-to-group-ielts-vocabulary-by-theme', cluster: 'vocabulary', title: 'How to Group IELTS Vocabulary by Theme' },
  { slug: 'how-to-learn-collocations-for-ielts', cluster: 'vocabulary', title: 'How to Learn Collocations for IELTS' },
  { slug: 'how-to-memorise-ielts-vocabulary-using-spaced-repetition', cluster: 'vocabulary', title: 'How to Memorise IELTS Vocabulary Using Spaced Repetition' },
  { slug: 'how-to-remember-ielts-vocabulary-long-term', cluster: 'vocabulary', title: 'How to Remember IELTS Vocabulary Long Term' },
  { slug: 'how-to-use-accurate-vocabulary-for-data-description', cluster: 'vocabulary', title: 'How to Use Accurate Vocabulary for Data Description' },
  { slug: 'how-to-use-descriptive-language-in-ielts-speaking', cluster: 'vocabulary', title: 'How to Use Descriptive Language in IELTS Speaking' },
  { slug: 'how-to-use-formal-vs-informal-vocabulary-in-ielts', cluster: 'vocabulary', title: 'How to Use Formal vs Informal Vocabulary in IELTS' },
  { slug: 'how-to-use-less-common-vocabulary-without-sounding-forced', cluster: 'vocabulary', title: 'How to Use Less Common Vocabulary Without Sounding Forced' },
  { slug: 'how-to-use-linking-and-transition-words-in-ielts', cluster: 'vocabulary', title: 'How to Use Linking and Transition Words in IELTS' },
  { slug: 'how-to-use-phrasal-verbs-naturally-in-ielts', cluster: 'vocabulary', title: 'How to Use Phrasal Verbs Naturally in IELTS' },
  { slug: 'how-to-use-synonyms-effectively-in-ielts', cluster: 'vocabulary', title: 'How to Use Synonyms Effectively in IELTS' },
  { slug: 'how-to-use-topic-specific-vocabulary-in-ielts-speaking', cluster: 'vocabulary', title: 'How to Use Topic-Specific Vocabulary in IELTS Speaking' },
  { slug: 'ielts-vocabulary-for-aging-population-topics', cluster: 'vocabulary', title: 'IELTS Vocabulary for Aging Population Topics' },
  { slug: 'ielts-vocabulary-for-agriculture-and-rural-life', cluster: 'vocabulary', title: 'IELTS Vocabulary for Agriculture and Rural Life' },
  { slug: 'ielts-vocabulary-for-children-and-parenting-topics', cluster: 'vocabulary', title: 'IELTS Vocabulary for Children and Parenting Topics' },
  { slug: 'ielts-vocabulary-for-economics-and-trade', cluster: 'vocabulary', title: 'IELTS Vocabulary for Economics and Trade' },
  { slug: 'ielts-vocabulary-for-education-topics', cluster: 'vocabulary', title: 'IELTS Vocabulary for Education Topics' },
  { slug: 'ielts-vocabulary-for-gender-and-equality-topics', cluster: 'vocabulary', title: 'IELTS Vocabulary for Gender and Equality Topics' },
  { slug: 'ielts-vocabulary-for-globalisation-topics', cluster: 'vocabulary', title: 'IELTS Vocabulary for Globalisation Topics' },
  { slug: 'ielts-vocabulary-for-government-and-politics', cluster: 'vocabulary', title: 'IELTS Vocabulary for Government and Politics' },
  { slug: 'ielts-vocabulary-for-health-and-wellbeing-topics', cluster: 'vocabulary', title: 'IELTS Vocabulary for Health and Wellbeing Topics' },
  { slug: 'ielts-vocabulary-for-history-and-tradition-topics', cluster: 'vocabulary', title: 'IELTS Vocabulary for History and Tradition Topics' },
  { slug: 'ielts-vocabulary-for-immigration-and-migration-topics', cluster: 'vocabulary', title: 'IELTS Vocabulary for Immigration and Migration Topics' },
  { slug: 'ielts-vocabulary-for-media-and-advertising', cluster: 'vocabulary', title: 'IELTS Vocabulary for Media and Advertising' },
  { slug: 'ielts-vocabulary-for-money-and-finance-topics', cluster: 'vocabulary', title: 'IELTS Vocabulary for Money and Finance Topics' },
  { slug: 'ielts-vocabulary-for-noise-and-pollution-topics', cluster: 'vocabulary', title: 'IELTS Vocabulary for Noise and Pollution Topics' },
  { slug: 'ielts-vocabulary-for-psychology-and-behaviour', cluster: 'vocabulary', title: 'IELTS Vocabulary for Psychology and Behaviour' },
  { slug: 'ielts-vocabulary-for-science-and-research', cluster: 'vocabulary', title: 'IELTS Vocabulary for Science and Research' },
  { slug: 'ielts-vocabulary-for-social-issues-and-inequality', cluster: 'vocabulary', title: 'IELTS Vocabulary for Social Issues and Inequality' },
  { slug: 'ielts-vocabulary-for-technology-and-innovation', cluster: 'vocabulary', title: 'IELTS Vocabulary for Technology and Innovation' },
  { slug: 'ielts-vocabulary-for-urbanisation-and-housing', cluster: 'vocabulary', title: 'IELTS Vocabulary for Urbanisation and Housing' },
  { slug: 'ielts-vocabulary-for-work-and-employment-topics', cluster: 'vocabulary', title: 'IELTS Vocabulary for Work and Employment Topics' },
  { slug: 'leisure-and-entertainment-vocabulary-for-ielts', cluster: 'vocabulary', title: 'Leisure and Entertainment Vocabulary for IELTS' },
  { slug: 'nature-and-wildlife-vocabulary-for-ielts', cluster: 'vocabulary', title: 'Nature and Wildlife Vocabulary for IELTS' },
  { slug: 'shopping-and-consumer-culture-vocabulary-for-ielts', cluster: 'vocabulary', title: 'Shopping and Consumer Culture Vocabulary for IELTS' },
  { slug: 'space-and-exploration-vocabulary-for-ielts', cluster: 'vocabulary', title: 'Space and Exploration Vocabulary for IELTS' },
  { slug: 'sport-and-fitness-vocabulary-for-ielts', cluster: 'vocabulary', title: 'Sport and Fitness Vocabulary for IELTS' },
  { slug: 'technology-addiction-vocabulary-for-ielts', cluster: 'vocabulary', title: 'Technology Addiction Vocabulary for IELTS' },
  { slug: 'tourism-and-hospitality-vocabulary-for-ielts', cluster: 'vocabulary', title: 'Tourism and Hospitality Vocabulary for IELTS' },
  { slug: 'transport-and-travel-vocabulary-for-ielts', cluster: 'vocabulary', title: 'Transport and Travel Vocabulary for IELTS' },
  { slug: 'water-and-energy-vocabulary-for-ielts', cluster: 'vocabulary', title: 'Water and Energy Vocabulary for IELTS' },
  /* GRAMMAR (45) */
  { slug: 'adverbial-clauses-for-ielts-writing', cluster: 'grammar', title: 'Adverbial Clauses for IELTS Writing' },
  { slug: 'common-grammar-mistakes-that-reduce-ielts-scores', cluster: 'grammar', title: 'Common Grammar Mistakes That Reduce IELTS Scores' },
  { slug: 'common-preposition-errors-in-ielts-writing', cluster: 'grammar', title: 'Common Preposition Errors in IELTS Writing' },
  { slug: 'comparative-and-superlative-structures-for-ielts', cluster: 'grammar', title: 'Comparative and Superlative Structures for IELTS' },
  { slug: 'complex-sentence-structures-for-ielts-band-8', cluster: 'grammar', title: 'Complex Sentence Structures for IELTS Band 8' },
  { slug: 'countable-and-uncountable-nouns-in-ielts', cluster: 'grammar', title: 'Countable and Uncountable Nouns in IELTS' },
  { slug: 'ellipsis-and-substitution-in-ielts-grammar', cluster: 'grammar', title: 'Ellipsis and Substitution in IELTS Grammar' },
  { slug: 'essential-grammar-structures-for-ielts-band-7', cluster: 'grammar', title: 'Essential Grammar Structures for IELTS Band 7' },
  { slug: 'future-forms-and-their-uses-in-ielts', cluster: 'grammar', title: 'Future Forms and Their Uses in IELTS' },
  { slug: 'gerunds-and-infinitives-in-ielts-grammar', cluster: 'grammar', title: 'Gerunds and Infinitives in IELTS Grammar' },
  { slug: 'grammar-checklist-before-submitting-your-ielts-essay', cluster: 'grammar', title: 'Grammar Checklist Before Submitting Your IELTS Essay' },
  { slug: 'how-to-avoid-run-on-sentences-in-ielts-writing', cluster: 'grammar', title: 'How to Avoid Run-On Sentences in IELTS Writing' },
  { slug: 'how-to-correct-word-order-errors-in-ielts', cluster: 'grammar', title: 'How to Correct Word Order Errors in IELTS' },
  { slug: 'how-to-fix-subject-verb-agreement-errors-in-ielts', cluster: 'grammar', title: 'How to Fix Subject-Verb Agreement Errors in IELTS' },
  { slug: 'how-to-punctuate-correctly-in-ielts-writing', cluster: 'grammar', title: 'How to Punctuate Correctly in IELTS Writing' },
  { slug: 'how-to-use-adverbs-of-frequency-in-ielts', cluster: 'grammar', title: 'How to Use Adverbs of Frequency in IELTS' },
  { slug: 'how-to-use-cleft-sentences-in-ielts-for-emphasis', cluster: 'grammar', title: 'How to Use Cleft Sentences in IELTS for Emphasis' },
  { slug: 'how-to-use-concessive-clauses-in-ielts', cluster: 'grammar', title: 'How to Use Concessive Clauses in IELTS' },
  { slug: 'how-to-use-conditional-sentences-correctly-in-ielts', cluster: 'grammar', title: 'How to Use Conditional Sentences Correctly in IELTS' },
  { slug: 'how-to-use-determiners-accurately-in-ielts', cluster: 'grammar', title: 'How to Use Determiners Accurately in IELTS' },
  { slug: 'how-to-use-emphatic-structures-in-ielts-speaking', cluster: 'grammar', title: 'How to Use Emphatic Structures in IELTS Speaking' },
  { slug: 'how-to-use-fronting-and-extraposition-in-ielts', cluster: 'grammar', title: 'How to Use Fronting and Extraposition in IELTS' },
  { slug: 'how-to-use-hedging-language-for-academic-ielts', cluster: 'grammar', title: 'How to Use Hedging Language for Academic IELTS' },
  { slug: 'how-to-use-linking-words-without-overusing-them', cluster: 'grammar', title: 'How to Use Linking Words Without Overusing Them' },
  { slug: 'how-to-use-mixed-conditionals-for-ielts-band-8', cluster: 'grammar', title: 'How to Use Mixed Conditionals for IELTS Band 8' },
  { slug: 'how-to-use-modal-verbs-for-ielts-writing-and-speaking', cluster: 'grammar', title: 'How to Use Modal Verbs for IELTS Writing and Speaking' },
  { slug: 'how-to-use-noun-clauses-in-ielts-writing', cluster: 'grammar', title: 'How to Use Noun Clauses in IELTS Writing' },
  { slug: 'how-to-use-prepositions-correctly-in-ielts', cluster: 'grammar', title: 'How to Use Prepositions Correctly in IELTS' },
  { slug: 'how-to-use-present-perfect-correctly-in-ielts', cluster: 'grammar', title: 'How to Use Present Perfect Correctly in IELTS' },
  { slug: 'how-to-use-quantifiers-correctly-in-ielts', cluster: 'grammar', title: 'How to Use Quantifiers Correctly in IELTS' },
  { slug: 'how-to-use-tenses-accurately-in-ielts', cluster: 'grammar', title: 'How to Use Tenses Accurately in IELTS' },
  { slug: 'how-to-use-the-passive-voice-in-ielts', cluster: 'grammar', title: 'How to Use the Passive Voice in IELTS' },
  { slug: 'how-to-write-complex-compound-sentences-for-ielts', cluster: 'grammar', title: 'How to Write Complex-Compound Sentences for IELTS' },
  { slug: 'inversion-for-emphasis-in-ielts-academic-writing', cluster: 'grammar', title: 'Inversion for Emphasis in IELTS Academic Writing' },
  { slug: 'nominalization-for-ielts-academic-writing', cluster: 'grammar', title: 'Nominalization for IELTS Academic Writing' },
  { slug: 'parallel-structure-in-ielts-academic-writing', cluster: 'grammar', title: 'Parallel Structure in IELTS Academic Writing' },
  { slug: 'participle-clauses-for-advanced-ielts-grammar', cluster: 'grammar', title: 'Participle Clauses for Advanced IELTS Grammar' },
  { slug: 'past-perfect-vs-past-simple-in-ielts', cluster: 'grammar', title: 'Past Perfect vs Past Simple in IELTS' },
  { slug: 'relative-clauses-for-ielts-writing-and-speaking', cluster: 'grammar', title: 'Relative Clauses for IELTS Writing and Speaking' },
  { slug: 'sentence-variety-techniques-for-ielts-writing', cluster: 'grammar', title: 'Sentence Variety Techniques for IELTS Writing' },
  { slug: 'subjunctive-mood-in-ielts-academic-writing', cluster: 'grammar', title: 'Subjunctive Mood in IELTS Academic Writing' },
  { slug: 'using-articles-correctly-in-ielts-writing', cluster: 'grammar', title: 'Using Articles Correctly in IELTS Writing' },
  { slug: 'using-conjunctions-accurately-in-ielts', cluster: 'grammar', title: 'Using Conjunctions Accurately in IELTS' },
  { slug: 'using-discourse-markers-in-ielts-speaking', cluster: 'grammar', title: 'Using Discourse Markers in IELTS Speaking' },
  { slug: 'using-reported-speech-in-ielts-writing-and-speaking', cluster: 'grammar', title: 'Using Reported Speech in IELTS Writing and Speaking' },
  /* EXAM-STRATEGY (50) */
  { slug: 'how-to-analyse-your-ielts-practice-test-results', cluster: 'exam-strategy', title: 'How to Analyse Your IELTS Practice Test Results' },
  { slug: 'how-to-balance-all-four-ielts-skills-in-preparation', cluster: 'exam-strategy', title: 'How to Balance All Four IELTS Skills in Preparation' },
  { slug: 'how-to-build-exam-stamina-for-ielts', cluster: 'exam-strategy', title: 'How to Build Exam Stamina for IELTS' },
  { slug: 'how-to-choose-between-ielts-academic-and-general-training', cluster: 'exam-strategy', title: 'How to Choose Between IELTS Academic and General Training' },
  { slug: 'how-to-combine-ielts-preparation-with-daily-life', cluster: 'exam-strategy', title: 'How to Combine IELTS Preparation With Daily Life' },
  { slug: 'how-to-create-a-30-day-ielts-study-plan', cluster: 'exam-strategy', title: 'How to Create a 30-Day IELTS Study Plan' },
  { slug: 'how-to-create-an-effective-ielts-study-schedule', cluster: 'exam-strategy', title: 'How to Create an Effective IELTS Study Schedule' },
  { slug: 'how-to-get-your-ielts-results-and-request-a-remark', cluster: 'exam-strategy', title: 'How to Get Your IELTS Results and Request a Remark' },
  { slug: 'how-to-handle-nervousness-before-ielts-speaking', cluster: 'exam-strategy', title: 'How to Handle Nervousness Before IELTS Speaking' },
  { slug: 'how-to-identify-your-weakest-ielts-module', cluster: 'exam-strategy', title: 'How to Identify Your Weakest IELTS Module' },
  { slug: 'how-to-improve-from-band-6-to-band-7-in-ielts', cluster: 'exam-strategy', title: 'How to Improve From Band 6 to Band 7 in IELTS' },
  { slug: 'how-to-manage-time-across-all-ielts-sections', cluster: 'exam-strategy', title: 'How to Manage Time Across All IELTS Sections' },
  { slug: 'how-to-overcome-ielts-test-anxiety', cluster: 'exam-strategy', title: 'How to Overcome IELTS Test Anxiety' },
  { slug: 'how-to-prepare-for-ielts-in-three-months', cluster: 'exam-strategy', title: 'How to Prepare for IELTS in Three Months' },
  { slug: 'how-to-prepare-for-ielts-while-working-full-time', cluster: 'exam-strategy', title: 'How to Prepare for IELTS While Working Full Time' },
  { slug: 'how-to-prepare-for-ielts-with-limited-english', cluster: 'exam-strategy', title: 'How to Prepare for IELTS With Limited English' },
  { slug: 'how-to-request-an-ielts-score-review', cluster: 'exam-strategy', title: 'How to Request an IELTS Score Review' },
  { slug: 'how-to-retake-ielts-and-improve-your-score', cluster: 'exam-strategy', title: 'How to Retake IELTS and Improve Your Score' },
  { slug: 'how-to-set-a-realistic-ielts-target-score', cluster: 'exam-strategy', title: 'How to Set a Realistic IELTS Target Score' },
  { slug: 'how-to-stay-motivated-while-preparing-for-ielts', cluster: 'exam-strategy', title: 'How to Stay Motivated While Preparing for IELTS' },
  { slug: 'how-to-track-your-ielts-progress-over-time', cluster: 'exam-strategy', title: 'How to Track Your IELTS Progress Over Time' },
  { slug: 'how-to-use-ai-tools-for-ielts-preparation', cluster: 'exam-strategy', title: 'How to Use AI Tools for IELTS Preparation' },
  { slug: 'how-to-use-ielts-past-papers-for-preparation', cluster: 'exam-strategy', title: 'How to Use IELTS Past Papers for Preparation' },
  { slug: 'how-to-use-practice-tests-effectively-for-ielts', cluster: 'exam-strategy', title: 'How to Use Practice Tests Effectively for IELTS' },
  { slug: 'how-to-use-youtube-for-ielts-preparation', cluster: 'exam-strategy', title: 'How to Use YouTube for IELTS Preparation' },
  { slug: 'ielts-academic-vs-general-scoring-differences', cluster: 'exam-strategy', title: 'IELTS Academic vs General Scoring Differences' },
  { slug: 'ielts-apps-and-tools-that-actually-help', cluster: 'exam-strategy', title: 'IELTS Apps and Tools That Actually Help' },
  { slug: 'ielts-band-score-calculator-how-scores-are-calculated', cluster: 'exam-strategy', title: 'IELTS Band Score Calculator How Scores Are Calculated' },
  { slug: 'ielts-common-myths-and-misconceptions-debunked', cluster: 'exam-strategy', title: 'IELTS Common Myths and Misconceptions Debunked' },
  { slug: 'ielts-computer-delivered-vs-paper-based-which-is-better', cluster: 'exam-strategy', title: 'IELTS Computer-Delivered vs Paper-Based Which Is Better' },
  { slug: 'ielts-exam-day-checklist-what-to-bring-and-expect', cluster: 'exam-strategy', title: 'IELTS Exam Day Checklist What to Bring and Expect' },
  { slug: 'ielts-for-healthcare-professionals-score-requirements', cluster: 'exam-strategy', title: 'IELTS for Healthcare Professionals Score Requirements' },
  { slug: 'ielts-for-skilled-worker-visa-requirements', cluster: 'exam-strategy', title: 'IELTS for Skilled Worker Visa Requirements' },
  { slug: 'ielts-for-teachers-and-educators-requirements', cluster: 'exam-strategy', title: 'IELTS for Teachers and Educators Requirements' },
  { slug: 'ielts-for-university-admission-minimum-score-requirements', cluster: 'exam-strategy', title: 'IELTS for University Admission Minimum Score Requirements' },
  { slug: 'ielts-frequently-asked-questions-answered', cluster: 'exam-strategy', title: 'IELTS Frequently Asked Questions Answered' },
  { slug: 'ielts-mock-test-strategy-how-often-to-practise', cluster: 'exam-strategy', title: 'IELTS Mock Test Strategy How Often to Practise' },
  { slug: 'ielts-one-skill-retake-everything-you-need-to-know', cluster: 'exam-strategy', title: 'IELTS One Skill Retake Everything You Need to Know' },
  { slug: 'ielts-online-test-option-what-you-need-to-know', cluster: 'exam-strategy', title: 'IELTS Online Test Option What You Need to Know' },
  { slug: 'ielts-preparation-for-immigration-purposes', cluster: 'exam-strategy', title: 'IELTS Preparation for Immigration Purposes' },
  { slug: 'ielts-preparation-mistakes-that-waste-your-time', cluster: 'exam-strategy', title: 'IELTS Preparation Mistakes That Waste Your Time' },
  { slug: 'ielts-preparation-on-a-budget-free-resources-guide', cluster: 'exam-strategy', title: 'IELTS Preparation on a Budget Free Resources Guide' },
  { slug: 'ielts-results-day-what-to-expect', cluster: 'exam-strategy', title: 'IELTS Results Day What to Expect' },
  { slug: 'ielts-score-requirements-for-different-countries', cluster: 'exam-strategy', title: 'IELTS Score Requirements for Different Countries' },
  { slug: 'ielts-score-validity-how-long-do-results-last', cluster: 'exam-strategy', title: 'IELTS Score Validity How Long Do Results Last' },
  { slug: 'ielts-scoring-system-explained-simply', cluster: 'exam-strategy', title: 'IELTS Scoring System Explained Simply' },
  { slug: 'ielts-studying-alone-vs-taking-a-course', cluster: 'exam-strategy', title: 'IELTS Studying Alone vs Taking a Course' },
  { slug: 'ielts-test-centres-how-to-choose-and-register', cluster: 'exam-strategy', title: 'IELTS Test Centres How to Choose and Register' },
  { slug: 'ielts-test-day-mistakes-to-avoid', cluster: 'exam-strategy', title: 'IELTS Test Day Mistakes to Avoid' },
  { slug: 'ielts-two-week-intensive-study-plan', cluster: 'exam-strategy', title: 'IELTS Two-Week Intensive Study Plan' },
  /* PRONUNCIATION (30) */
  { slug: 'common-pronunciation-errors-by-chinese-speakers-in-ielts', cluster: 'pronunciation', title: 'Common Pronunciation Errors by Chinese Speakers in IELTS' },
  { slug: 'common-pronunciation-mistakes-by-arabic-speakers-in-ielts', cluster: 'pronunciation', title: 'Common Pronunciation Mistakes by Arabic Speakers in IELTS' },
  { slug: 'connected-speech-patterns-you-need-for-ielts', cluster: 'pronunciation', title: 'Connected Speech Patterns You Need for IELTS' },
  { slug: 'consonant-clusters-that-ielts-candidates-struggle-with', cluster: 'pronunciation', title: 'Consonant Clusters That IELTS Candidates Struggle With' },
  { slug: 'elision-and-assimilation-in-natural-english', cluster: 'pronunciation', title: 'Elision and Assimilation in Natural English' },
  { slug: 'how-to-fix-fossilised-pronunciation-errors', cluster: 'pronunciation', title: 'How to Fix Fossilised Pronunciation Errors' },
  { slug: 'how-to-improve-english-pronunciation-for-ielts-speaking', cluster: 'pronunciation', title: 'How to Improve English Pronunciation for IELTS Speaking' },
  { slug: 'how-to-improve-pronunciation-through-listening', cluster: 'pronunciation', title: 'How to Improve Pronunciation Through Listening' },
  { slug: 'how-to-improve-pronunciation-using-shadowing', cluster: 'pronunciation', title: 'How to Improve Pronunciation Using Shadowing' },
  { slug: 'how-to-practise-pronunciation-without-a-teacher', cluster: 'pronunciation', title: 'How to Practise Pronunciation Without a Teacher' },
  { slug: 'how-to-pronounce-academic-vocabulary-for-ielts', cluster: 'pronunciation', title: 'How to Pronounce Academic Vocabulary for IELTS' },
  { slug: 'how-to-pronounce-difficult-english-sounds-for-ielts', cluster: 'pronunciation', title: 'How to Pronounce Difficult English Sounds for IELTS' },
  { slug: 'how-to-pronounce-numbers-and-dates-clearly-for-ielts', cluster: 'pronunciation', title: 'How to Pronounce Numbers and Dates Clearly for IELTS' },
  { slug: 'how-to-pronounce-plural-and-past-tense-endings', cluster: 'pronunciation', title: 'How to Pronounce Plural and Past Tense Endings' },
  { slug: 'how-to-pronounce-the-th-sound-for-ielts', cluster: 'pronunciation', title: 'How to Pronounce the TH Sound for IELTS' },
  { slug: 'how-to-record-and-review-your-pronunciation-for-ielts', cluster: 'pronunciation', title: 'How to Record and Review Your Pronunciation for IELTS' },
  { slug: 'how-to-reduce-your-accent-for-ielts-speaking', cluster: 'pronunciation', title: 'How to Reduce Your Accent for IELTS Speaking' },
  { slug: 'how-to-sound-natural-in-ielts-speaking', cluster: 'pronunciation', title: 'How to Sound Natural in IELTS Speaking' },
  { slug: 'how-to-use-intonation-effectively-in-ielts-speaking', cluster: 'pronunciation', title: 'How to Use Intonation Effectively in IELTS Speaking' },
  { slug: 'how-to-use-pausing-and-pacing-in-ielts-speaking', cluster: 'pronunciation', title: 'How to Use Pausing and Pacing in IELTS Speaking' },
  { slug: 'minimal-pairs-practice-for-ielts-speaking', cluster: 'pronunciation', title: 'Minimal Pairs Practice for IELTS Speaking' },
  { slug: 'pronunciation-resources-and-apps-for-ielts', cluster: 'pronunciation', title: 'Pronunciation Resources and Apps for IELTS' },
  { slug: 'pronunciation-scoring-criteria-in-ielts-speaking', cluster: 'pronunciation', title: 'Pronunciation Scoring Criteria in IELTS Speaking' },
  { slug: 'rising-and-falling-intonation-patterns-for-ielts', cluster: 'pronunciation', title: 'Rising and Falling Intonation Patterns for IELTS' },
  { slug: 'sentence-stress-and-rhythm-in-english-for-ielts', cluster: 'pronunciation', title: 'Sentence Stress and Rhythm in English for IELTS' },
  { slug: 'silent-letters-in-english-for-ielts-preparation', cluster: 'pronunciation', title: 'Silent Letters in English for IELTS Preparation' },
  { slug: 'tongue-position-guide-for-difficult-english-sounds', cluster: 'pronunciation', title: 'Tongue Position Guide for Difficult English Sounds' },
  { slug: 'vowel-sounds-in-english-that-ielts-candidates-get-wrong', cluster: 'pronunciation', title: 'Vowel Sounds in English That IELTS Candidates Get Wrong' },
  { slug: 'weak-forms-and-schwa-sound-in-ielts-speaking', cluster: 'pronunciation', title: 'Weak Forms and Schwa Sound in IELTS Speaking' },
  { slug: 'word-stress-rules-for-ielts-speaking', cluster: 'pronunciation', title: 'Word Stress Rules for IELTS Speaking' },
  /* ACADEMIC-SKILLS (30) */
  { slug: 'academic-discussion-skills-for-ielts-speaking-part-3', cluster: 'academic-skills', title: 'Academic Discussion Skills for IELTS Speaking Part 3' },
  { slug: 'academic-register-and-tone-for-ielts-writing', cluster: 'academic-skills', title: 'Academic Register and Tone for IELTS Writing' },
  { slug: 'critical-thinking-skills-for-ielts-academic', cluster: 'academic-skills', title: 'Critical Thinking Skills for IELTS Academic' },
  { slug: 'describing-trends-and-patterns-in-ielts-academic', cluster: 'academic-skills', title: 'Describing Trends and Patterns in IELTS Academic' },
  { slug: 'evaluating-sources-and-claims-in-ielts-reading', cluster: 'academic-skills', title: 'Evaluating Sources and Claims in IELTS Reading' },
  { slug: 'how-to-analyse-visual-data-for-ielts-academic-task-1', cluster: 'academic-skills', title: 'How to Analyse Visual Data for IELTS Academic Task 1' },
  { slug: 'how-to-build-an-academic-vocabulary-bank-for-ielts', cluster: 'academic-skills', title: 'How to Build an Academic Vocabulary Bank for IELTS' },
  { slug: 'how-to-compare-and-contrast-in-ielts-academic-writing', cluster: 'academic-skills', title: 'How to Compare and Contrast in IELTS Academic Writing' },
  { slug: 'how-to-develop-academic-writing-style-for-ielts', cluster: 'academic-skills', title: 'How to Develop Academic Writing Style for IELTS' },
  { slug: 'how-to-handle-abstract-concepts-in-ielts-academic', cluster: 'academic-skills', title: 'How to Handle Abstract Concepts in IELTS Academic' },
  { slug: 'how-to-handle-classification-in-ielts-academic-passages', cluster: 'academic-skills', title: 'How to Handle Classification in IELTS Academic Passages' },
  { slug: 'how-to-identify-argument-structure-in-ielts-reading', cluster: 'academic-skills', title: 'How to Identify Argument Structure in IELTS Reading' },
  { slug: 'how-to-identify-bias-and-opinion-in-ielts-reading', cluster: 'academic-skills', title: 'How to Identify Bias and Opinion in IELTS Reading' },
  { slug: 'how-to-interpret-research-findings-in-ielts', cluster: 'academic-skills', title: 'How to Interpret Research Findings in IELTS' },
  { slug: 'how-to-prepare-for-ielts-academic-from-scratch', cluster: 'academic-skills', title: 'How to Prepare for IELTS Academic From Scratch' },
  { slug: 'how-to-read-abstracts-and-introductions-quickly', cluster: 'academic-skills', title: 'How to Read Abstracts and Introductions Quickly' },
  { slug: 'how-to-summarise-and-paraphrase-for-ielts-academic', cluster: 'academic-skills', title: 'How to Summarise and Paraphrase for IELTS Academic' },
  { slug: 'how-to-use-evidence-in-ielts-academic-writing', cluster: 'academic-skills', title: 'How to Use Evidence in IELTS Academic Writing' },
  { slug: 'how-to-write-effective-supporting-sentences-for-ielts', cluster: 'academic-skills', title: 'How to Write Effective Supporting Sentences for IELTS' },
  { slug: 'how-to-write-topic-sentences-for-ielts-paragraphs', cluster: 'academic-skills', title: 'How to Write Topic Sentences for IELTS Paragraphs' },
  { slug: 'logical-reasoning-skills-for-ielts-reading', cluster: 'academic-skills', title: 'Logical Reasoning Skills for IELTS Reading' },
  { slug: 'note-taking-strategies-for-ielts-listening-and-reading', cluster: 'academic-skills', title: 'Note-Taking Strategies for IELTS Listening and Reading' },
  { slug: 'problem-solution-framework-for-ielts-academic-writing', cluster: 'academic-skills', title: 'Problem-Solution Framework for IELTS Academic Writing' },
  { slug: 'reading-academic-journals-for-ielts-preparation', cluster: 'academic-skills', title: 'Reading Academic Journals for IELTS Preparation' },
  { slug: 'skimming-academic-texts-efficiently-for-ielts', cluster: 'academic-skills', title: 'Skimming Academic Texts Efficiently for IELTS' },
  { slug: 'structuring-an-academic-argument-for-ielts-task-2', cluster: 'academic-skills', title: 'Structuring an Academic Argument for IELTS Task 2' },
  { slug: 'synthesis-skills-for-ielts-academic-reading', cluster: 'academic-skills', title: 'Synthesis Skills for IELTS Academic Reading' },
  { slug: 'understanding-cause-and-effect-in-ielts-academic-passages', cluster: 'academic-skills', title: 'Understanding Cause and Effect in IELTS Academic Passages' },
  { slug: 'understanding-referencing-and-citation-in-ielts-context', cluster: 'academic-skills', title: 'Understanding Referencing and Citation in IELTS Context' },
  { slug: 'understanding-tone-and-register-in-ielts-texts', cluster: 'academic-skills', title: 'Understanding Tone and Register in IELTS Texts' },
  /* IELTS-MIGRATION (40) */
  { slug: 'how-to-achieve-clb-9-in-ielts-for-canada', cluster: 'ielts-migration', title: 'How to Achieve CLB 9 in IELTS for Canada' },
  { slug: 'how-to-achieve-ielts-band-7-for-nursing-registration', cluster: 'ielts-migration', title: 'How to Achieve IELTS Band 7 for Nursing Registration' },
  { slug: 'how-to-achieve-ielts-requirements-for-accounting-bodies', cluster: 'ielts-migration', title: 'How to Achieve IELTS Requirements for Accounting Bodies' },
  { slug: 'how-to-achieve-ielts-requirements-for-veterinary-registration', cluster: 'ielts-migration', title: 'How to Achieve IELTS Requirements for Veterinary Registration' },
  { slug: 'how-to-get-ielts-band-8-for-australian-points-system', cluster: 'ielts-migration', title: 'How to Get IELTS Band 8 for Australian Points System' },
  { slug: 'how-to-meet-ielts-requirements-for-architecture-registration', cluster: 'ielts-migration', title: 'How to Meet IELTS Requirements for Architecture Registration' },
  { slug: 'how-to-meet-ielts-requirements-for-new-zealand-migration', cluster: 'ielts-migration', title: 'How to Meet IELTS Requirements for New Zealand Migration' },
  { slug: 'how-to-meet-ielts-requirements-for-teaching-abroad', cluster: 'ielts-migration', title: 'How to Meet IELTS Requirements for Teaching Abroad' },
  { slug: 'how-to-prepare-ielts-for-australia-visa-application', cluster: 'ielts-migration', title: 'How to Prepare IELTS for Australia Visa Application' },
  { slug: 'how-to-prepare-ielts-for-canadian-express-entry', cluster: 'ielts-migration', title: 'How to Prepare IELTS for Canadian Express Entry' },
  { slug: 'how-to-prepare-ielts-for-engineering-registration', cluster: 'ielts-migration', title: 'How to Prepare IELTS for Engineering Registration' },
  { slug: 'how-to-prepare-ielts-for-family-reunion-visa', cluster: 'ielts-migration', title: 'How to Prepare IELTS for Family Reunion Visa' },
  { slug: 'how-to-prepare-ielts-for-occupational-therapy-registration', cluster: 'ielts-migration', title: 'How to Prepare IELTS for Occupational Therapy Registration' },
  { slug: 'how-to-prepare-ielts-for-pharmacy-registration', cluster: 'ielts-migration', title: 'How to Prepare IELTS for Pharmacy Registration' },
  { slug: 'how-to-prepare-ielts-for-singapore-work-permit', cluster: 'ielts-migration', title: 'How to Prepare IELTS for Singapore Work Permit' },
  { slug: 'how-to-prepare-ielts-for-social-work-registration', cluster: 'ielts-migration', title: 'How to Prepare IELTS for Social Work Registration' },
  { slug: 'how-to-prepare-ielts-for-uk-tier-2-work-visa', cluster: 'ielts-migration', title: 'How to Prepare IELTS for UK Tier 2 Work Visa' },
  { slug: 'how-to-prepare-ielts-when-english-is-your-third-language', cluster: 'ielts-migration', title: 'How to Prepare IELTS When English Is Your Third Language' },
  { slug: 'how-to-understand-ielts-scoring-for-visa-purposes', cluster: 'ielts-migration', title: 'How to Understand IELTS Scoring for Visa Purposes' },
  { slug: 'how-to-use-ielts-results-for-multiple-visa-applications', cluster: 'ielts-migration', title: 'How to Use IELTS Results for Multiple Visa Applications' },
  { slug: 'ielts-academic-vs-general-for-australian-immigration', cluster: 'ielts-migration', title: 'IELTS Academic vs General for Australian Immigration' },
  { slug: 'ielts-clb-conversion-chart-for-canada-immigration', cluster: 'ielts-migration', title: 'IELTS CLB Conversion Chart for Canada Immigration' },
  { slug: 'ielts-for-canadian-citizenship-language-requirements', cluster: 'ielts-migration', title: 'IELTS for Canadian Citizenship Language Requirements' },
  { slug: 'ielts-for-canadian-provincial-nominee-programs', cluster: 'ielts-migration', title: 'IELTS for Canadian Provincial Nominee Programs' },
  { slug: 'ielts-for-medical-professionals-moving-to-australia', cluster: 'ielts-migration', title: 'IELTS for Medical Professionals Moving to Australia' },
  { slug: 'ielts-for-studying-in-the-netherlands-requirements', cluster: 'ielts-migration', title: 'IELTS for Studying in the Netherlands Requirements' },
  { slug: 'ielts-general-training-for-australia-482-visa', cluster: 'ielts-migration', title: 'IELTS General Training for Australia 482 Visa' },
  { slug: 'ielts-requirements-for-dental-registration-in-uk', cluster: 'ielts-migration', title: 'IELTS Requirements for Dental Registration in UK' },
  { slug: 'ielts-requirements-for-dubai-and-uae-work-visa', cluster: 'ielts-migration', title: 'IELTS Requirements for Dubai and UAE Work Visa' },
  { slug: 'ielts-requirements-for-german-university-admission', cluster: 'ielts-migration', title: 'IELTS Requirements for German University Admission' },
  { slug: 'ielts-requirements-for-irish-stamp-4-visa', cluster: 'ielts-migration', title: 'IELTS Requirements for Irish Stamp 4 Visa' },
  { slug: 'ielts-requirements-for-pilot-training-programs', cluster: 'ielts-migration', title: 'IELTS Requirements for Pilot Training Programs' },
  { slug: 'ielts-requirements-for-postgraduate-study-in-uk', cluster: 'ielts-migration', title: 'IELTS Requirements for Postgraduate Study in UK' },
  { slug: 'ielts-requirements-for-real-estate-licensing-abroad', cluster: 'ielts-migration', title: 'IELTS Requirements for Real Estate Licensing Abroad' },
  { slug: 'ielts-requirements-for-uk-spouse-visa', cluster: 'ielts-migration', title: 'IELTS Requirements for UK Spouse Visa' },
  { slug: 'ielts-requirements-for-us-university-admission', cluster: 'ielts-migration', title: 'IELTS Requirements for US University Admission' },
  { slug: 'ielts-requirements-for-working-holiday-visa-programs', cluster: 'ielts-migration', title: 'IELTS Requirements for Working Holiday Visa Programs' },
  { slug: 'ielts-score-requirements-for-canada-pr', cluster: 'ielts-migration', title: 'IELTS Score Requirements for Canada PR' },
  { slug: 'ielts-score-requirements-for-mba-programs-worldwide', cluster: 'ielts-migration', title: 'IELTS Score Requirements for MBA Programs Worldwide' },
  { slug: 'ielts-score-requirements-for-scholarships', cluster: 'ielts-migration', title: 'IELTS Score Requirements for Scholarships' },
  /* COMMON-MISTAKES (35) */
  { slug: 'common-article-errors-in-ielts-writing', cluster: 'common-mistakes', title: 'Common Article Errors in IELTS Writing' },
  { slug: 'common-coherence-and-cohesion-mistakes-in-ielts-writing', cluster: 'common-mistakes', title: 'Common Coherence and Cohesion Mistakes in IELTS Writing' },
  { slug: 'common-ielts-speaking-errors-that-cost-you-marks', cluster: 'common-mistakes', title: 'Common IELTS Speaking Errors That Cost You Marks' },
  { slug: 'common-mistakes-in-ielts-listening-answer-transfer', cluster: 'common-mistakes', title: 'Common Mistakes in IELTS Listening Answer Transfer' },
  { slug: 'common-mistakes-when-using-examples-in-ielts-writing', cluster: 'common-mistakes', title: 'Common Mistakes When Using Examples in IELTS Writing' },
  { slug: 'common-preposition-mistakes-in-ielts', cluster: 'common-mistakes', title: 'Common Preposition Mistakes in IELTS' },
  { slug: 'common-punctuation-errors-in-ielts-writing', cluster: 'common-mistakes', title: 'Common Punctuation Errors in IELTS Writing' },
  { slug: 'common-vocabulary-mistakes-in-ielts-writing', cluster: 'common-mistakes', title: 'Common Vocabulary Mistakes in IELTS Writing' },
  { slug: 'common-word-form-errors-in-ielts-writing', cluster: 'common-mistakes', title: 'Common Word Form Errors in IELTS Writing' },
  { slug: 'how-to-avoid-informal-language-in-ielts-academic', cluster: 'common-mistakes', title: 'How to Avoid Informal Language in IELTS Academic' },
  { slug: 'how-to-avoid-off-topic-answers-in-ielts-writing', cluster: 'common-mistakes', title: 'How to Avoid Off-Topic Answers in IELTS Writing' },
  { slug: 'how-to-avoid-plagiarism-and-memorisation-penalties-in-ielts', cluster: 'common-mistakes', title: 'How to Avoid Plagiarism and Memorisation Penalties in IELTS' },
  { slug: 'how-to-avoid-reading-too-slowly-in-ielts', cluster: 'common-mistakes', title: 'How to Avoid Reading Too Slowly in IELTS' },
  { slug: 'how-to-avoid-repeating-the-same-words-in-ielts', cluster: 'common-mistakes', title: 'How to Avoid Repeating the Same Words in IELTS' },
  { slug: 'how-to-avoid-time-management-mistakes-in-ielts', cluster: 'common-mistakes', title: 'How to Avoid Time Management Mistakes in IELTS' },
  { slug: 'how-to-avoid-using-memorised-answers-in-ielts-speaking', cluster: 'common-mistakes', title: 'How to Avoid Using Memorised Answers in IELTS Speaking' },
  { slug: 'how-to-fix-grammar-errors-that-drop-you-below-band-7', cluster: 'common-mistakes', title: 'How to Fix Grammar Errors That Drop You Below Band 7' },
  { slug: 'how-to-fix-paragraph-organisation-errors-in-ielts', cluster: 'common-mistakes', title: 'How to Fix Paragraph Organisation Errors in IELTS' },
  { slug: 'how-to-fix-run-on-sentences-in-ielts', cluster: 'common-mistakes', title: 'How to Fix Run-On Sentences in IELTS' },
  { slug: 'how-to-fix-tense-consistency-errors-in-ielts', cluster: 'common-mistakes', title: 'How to Fix Tense Consistency Errors in IELTS' },
  { slug: 'how-to-stop-giving-one-word-answers-in-ielts-speaking', cluster: 'common-mistakes', title: 'How to Stop Giving One-Word Answers in IELTS Speaking' },
  { slug: 'how-to-stop-making-careless-errors-in-ielts', cluster: 'common-mistakes', title: 'How to Stop Making Careless Errors in IELTS' },
  { slug: 'how-to-stop-making-spelling-mistakes-in-ielts', cluster: 'common-mistakes', title: 'How to Stop Making Spelling Mistakes in IELTS' },
  { slug: 'how-to-stop-mixing-up-similar-words-in-ielts', cluster: 'common-mistakes', title: 'How to Stop Mixing Up Similar Words in IELTS' },
  { slug: 'how-to-stop-over-generalising-in-ielts-task-2', cluster: 'common-mistakes', title: 'How to Stop Over-Generalising in IELTS Task 2' },
  { slug: 'how-to-stop-panicking-when-you-miss-an-ielts-listening-answer', cluster: 'common-mistakes', title: 'How to Stop Panicking When You Miss an IELTS Listening Answer' },
  { slug: 'ielts-listening-mistakes-you-do-not-realise-you-make', cluster: 'common-mistakes', title: 'IELTS Listening Mistakes You Do Not Realise You Make' },
  { slug: 'ielts-mistakes-when-describing-charts-and-graphs', cluster: 'common-mistakes', title: 'IELTS Mistakes When Describing Charts and Graphs' },
  { slug: 'ielts-reading-mistakes-in-true-false-not-given', cluster: 'common-mistakes', title: 'IELTS Reading Mistakes in True False Not Given' },
  { slug: 'ielts-reading-mistakes-that-lower-your-score', cluster: 'common-mistakes', title: 'IELTS Reading Mistakes That Lower Your Score' },
  { slug: 'ielts-speaking-mistakes-in-pronunciation', cluster: 'common-mistakes', title: 'IELTS Speaking Mistakes in Pronunciation' },
  { slug: 'ielts-task-1-mistakes-in-data-description', cluster: 'common-mistakes', title: 'IELTS Task 1 Mistakes in Data Description' },
  { slug: 'ielts-writing-mistakes-in-concluding-paragraphs', cluster: 'common-mistakes', title: 'IELTS Writing Mistakes in Concluding Paragraphs' },
  { slug: 'ielts-writing-mistakes-in-thesis-statements', cluster: 'common-mistakes', title: 'IELTS Writing Mistakes in Thesis Statements' },
  { slug: 'top-10-ielts-writing-mistakes-and-how-to-fix-them', cluster: 'common-mistakes', title: 'Top 10 IELTS Writing Mistakes and How to Fix Them' },
  /* STUDY-RESOURCES (35) */
  { slug: 'best-free-ielts-practice-tests-online-in-2025', cluster: 'study-resources', title: 'Best Free IELTS Practice Tests Online in 2025' },
  { slug: 'best-ielts-apps-for-practice-on-the-go', cluster: 'study-resources', title: 'Best IELTS Apps for Practice on the Go' },
  { slug: 'best-ielts-instagram-and-tiktok-accounts', cluster: 'study-resources', title: 'Best IELTS Instagram and TikTok Accounts' },
  { slug: 'best-ielts-mock-test-websites', cluster: 'study-resources', title: 'Best IELTS Mock Test Websites' },
  { slug: 'best-ielts-preparation-books-for-2025', cluster: 'study-resources', title: 'Best IELTS Preparation Books for 2025' },
  { slug: 'best-ielts-preparation-courses-under-50-dollars', cluster: 'study-resources', title: 'Best IELTS Preparation Courses Under 50 Dollars' },
  { slug: 'best-ielts-teachers-and-tutors-to-follow-online', cluster: 'study-resources', title: 'Best IELTS Teachers and Tutors to Follow Online' },
  { slug: 'best-ielts-websites-for-band-9-model-answers', cluster: 'study-resources', title: 'Best IELTS Websites for Band 9 Model Answers' },
  { slug: 'best-podcasts-for-ielts-listening-practice', cluster: 'study-resources', title: 'Best Podcasts for IELTS Listening Practice' },
  { slug: 'free-ielts-course-options-available-online', cluster: 'study-resources', title: 'Free IELTS Course Options Available Online' },
  { slug: 'free-ielts-listening-practice-materials', cluster: 'study-resources', title: 'Free IELTS Listening Practice Materials' },
  { slug: 'free-ielts-reading-passages-for-practice', cluster: 'study-resources', title: 'Free IELTS Reading Passages for Practice' },
  { slug: 'free-ielts-speaking-practice-platforms', cluster: 'study-resources', title: 'Free IELTS Speaking Practice Platforms' },
  { slug: 'free-ielts-vocabulary-lists-and-downloads', cluster: 'study-resources', title: 'Free IELTS Vocabulary Lists and Downloads' },
  { slug: 'free-ielts-writing-feedback-tools-and-websites', cluster: 'study-resources', title: 'Free IELTS Writing Feedback Tools and Websites' },
  { slug: 'free-ielts-writing-sample-essays-and-where-to-find-them', cluster: 'study-resources', title: 'Free IELTS Writing Sample Essays and Where to Find Them' },
  { slug: 'how-to-build-a-study-routine-with-ielts-resources', cluster: 'study-resources', title: 'How to Build a Study Routine With IELTS Resources' },
  { slug: 'how-to-choose-an-ielts-online-course', cluster: 'study-resources', title: 'How to Choose an IELTS Online Course' },
  { slug: 'how-to-create-your-own-ielts-study-materials', cluster: 'study-resources', title: 'How to Create Your Own IELTS Study Materials' },
  { slug: 'how-to-find-an-ielts-study-partner-online', cluster: 'study-resources', title: 'How to Find an IELTS Study Partner Online' },
  { slug: 'how-to-use-ai-chatbots-for-ielts-speaking-practice', cluster: 'study-resources', title: 'How to Use AI Chatbots for IELTS Speaking Practice' },
  { slug: 'how-to-use-audiobooks-for-ielts-preparation', cluster: 'study-resources', title: 'How to Use Audiobooks for IELTS Preparation' },
  { slug: 'how-to-use-bbc-learning-english-for-ielts', cluster: 'study-resources', title: 'How to Use BBC Learning English for IELTS' },
  { slug: 'how-to-use-cambridge-ielts-books-effectively', cluster: 'study-resources', title: 'How to Use Cambridge IELTS Books Effectively' },
  { slug: 'how-to-use-flashcard-apps-for-ielts-vocabulary', cluster: 'study-resources', title: 'How to Use Flashcard Apps for IELTS Vocabulary' },
  { slug: 'how-to-use-google-for-ielts-research-and-practice', cluster: 'study-resources', title: 'How to Use Google for IELTS Research and Practice' },
  { slug: 'how-to-use-grammarly-and-similar-tools-for-ielts', cluster: 'study-resources', title: 'How to Use Grammarly and Similar Tools for IELTS' },
  { slug: 'how-to-use-language-exchange-apps-for-ielts-speaking', cluster: 'study-resources', title: 'How to Use Language Exchange Apps for IELTS Speaking' },
  { slug: 'how-to-use-movie-subtitles-for-ielts-listening', cluster: 'study-resources', title: 'How to Use Movie Subtitles for IELTS Listening' },
  { slug: 'how-to-use-news-websites-for-ielts-reading-practice', cluster: 'study-resources', title: 'How to Use News Websites for IELTS Reading Practice' },
  { slug: 'how-to-use-online-dictionaries-for-ielts-preparation', cluster: 'study-resources', title: 'How to Use Online Dictionaries for IELTS Preparation' },
  { slug: 'how-to-use-reddit-and-forums-for-ielts-tips', cluster: 'study-resources', title: 'How to Use Reddit and Forums for IELTS Tips' },
  { slug: 'how-to-use-ted-talks-for-ielts-listening-practice', cluster: 'study-resources', title: 'How to Use TED Talks for IELTS Listening Practice' },
  { slug: 'spokio-vs-other-ielts-apps-which-is-right-for-you', cluster: 'study-resources', title: 'Spokio vs Other IELTS Apps Which Is Right for You' },
  { slug: 'top-ielts-youtube-channels-for-self-study', cluster: 'study-resources', title: 'Top IELTS YouTube Channels for Self-Study' },
];
